moving admin termstore APIs from beta to v1.0
microsoftgraph/microsoft-graph-docs pull request #13432
Opened 2021-07-09 10:04 UTC by vishriv

2021-07-09 10:06 UTC, opbld32 commented
Docs Build status updates of commit _[32538eb](https://github.com/vishriv/microsoft-graph-docs/commits/32538eb06ae6b51b100228f7fef47f765970b68c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-b0db7d1b)
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-182a07248c6b0e0b9bb6ad822a2dc983-b0db7d1b)
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-9a1ce5075427c9f6299220c5d304a028-b0db7d1b)
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f5a4183ceabd35421ef2cd7c6e705faa-b0db7d1b)
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-4bb24860e5973c65e2113e0136a6e8f2-b0db7d1b)
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-b0036145297b142031bdb0a9df277d74-b0db7d1b)
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-75945fc821007153a740469b1a738447-b0db7d1b)
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a89fcd144357a3cc9cb88737acb76536-b0db7d1b)
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-8ba2df0bc5efc597bca75230547c4df4-b0db7d1b)
[api-reference/v1.0/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-351824f3efc5b5771ed65b87fb5af027-b0db7d1b)
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-ed97e46383c275199ae427ec7f806b7c-b0db7d1b)
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-bbeb1267dad0fa06d99e2015401c896b-b0db7d1b)
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-c1b9061331d67da9045c58e356dc7f8c-b0db7d1b)
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a34eb42b2f6b30ba37f3ce1db2f08ffe-b0db7d1b)
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-3cbb7c521783ed60b73fd867831865c7-b0db7d1b)
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-14dad5230cbbd80ca6bcbb3e49e244d0-b0db7d1b)
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-0b570dc831c819dcaf5295d9cb169285-b0db7d1b)
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-26e2e78bd1710755a4848a6259d0318d-b0db7d1b)
[api-reference/v1.0/api/group-post-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-post-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e93d68b9e8674e589ed0998 [...]

2021-07-12 10:57 UTC, opbld33 commented
Docs Build status updates of commit _[b37b2df](https://github.com/vishriv/microsoft-graph-docs/commits/b37b2dfd54a1c4410a00c0e99433894ac1c57311)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-faffc0d8)
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-182a07248c6b0e0b9bb6ad822a2dc983-faffc0d8)
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-9a1ce5075427c9f6299220c5d304a028-faffc0d8)
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f5a4183ceabd35421ef2cd7c6e705faa-faffc0d8)
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-4bb24860e5973c65e2113e0136a6e8f2-faffc0d8)
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-b0036145297b142031bdb0a9df277d74-faffc0d8)
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-75945fc821007153a740469b1a738447-faffc0d8)
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a89fcd144357a3cc9cb88737acb76536-faffc0d8)
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-8ba2df0bc5efc597bca75230547c4df4-faffc0d8)
[api-reference/v1.0/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-351824f3efc5b5771ed65b87fb5af027-faffc0d8)
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-ed97e46383c275199ae427ec7f806b7c-faffc0d8)
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-bbeb1267dad0fa06d99e2015401c896b-faffc0d8)
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-c1b9061331d67da9045c58e356dc7f8c-faffc0d8)
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a34eb42b2f6b30ba37f3ce1db2f08ffe-faffc0d8)
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-3cbb7c521783ed60b73fd867831865c7-faffc0d8)
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-14dad5230cbbd80ca6bcbb3e49e244d0-faffc0d8)
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-0b570dc831c819dcaf5295d9cb169285-faffc0d8)
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-26e2e78bd1710755a4848a6259d0318d-faffc0d8)
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e84e4b4 [...]

2021-07-12 11:34 UTC, opbld32 commented
Docs Build status updates of commit _[07e8833](https://github.com/vishriv/microsoft-graph-docs/commits/07e8833fdc51d60d4bc48301089c750ae343a8a0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-5918d44c)
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-182a07248c6b0e0b9bb6ad822a2dc983-5918d44c)
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-9a1ce5075427c9f6299220c5d304a028-5918d44c)
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f5a4183ceabd35421ef2cd7c6e705faa-5918d44c)
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-4bb24860e5973c65e2113e0136a6e8f2-5918d44c)
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-b0036145297b142031bdb0a9df277d74-5918d44c)
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-75945fc821007153a740469b1a738447-5918d44c)
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a89fcd144357a3cc9cb88737acb76536-5918d44c)
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-8ba2df0bc5efc597bca75230547c4df4-5918d44c)
[api-reference/v1.0/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-351824f3efc5b5771ed65b87fb5af027-5918d44c)
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-ed97e46383c275199ae427ec7f806b7c-5918d44c)
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-bbeb1267dad0fa06d99e2015401c896b-5918d44c)
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-c1b9061331d67da9045c58e356dc7f8c-5918d44c)
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a34eb42b2f6b30ba37f3ce1db2f08ffe-5918d44c)
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-3cbb7c521783ed60b73fd867831865c7-5918d44c)
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-14dad5230cbbd80ca6bcbb3e49e244d0-5918d44c)
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-0b570dc831c819dcaf5295d9cb169285-5918d44c)
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-26e2e78bd1710755a4848a6259d0318d-5918d44c)
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e84e4b4 [...]

2021-07-13 10:36 UTC, opbld30 commented
Docs Build status updates of commit _[1ca54f1](https://github.com/vishriv/microsoft-graph-docs/commits/1ca54f1bc891f424efa547c6caba6275c7014379)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-bd71606e)
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-182a07248c6b0e0b9bb6ad822a2dc983-bd71606e)
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-9a1ce5075427c9f6299220c5d304a028-bd71606e)
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f5a4183ceabd35421ef2cd7c6e705faa-bd71606e)
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-4bb24860e5973c65e2113e0136a6e8f2-bd71606e)
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-b0036145297b142031bdb0a9df277d74-bd71606e)
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-75945fc821007153a740469b1a738447-bd71606e)
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a89fcd144357a3cc9cb88737acb76536-bd71606e)
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-8ba2df0bc5efc597bca75230547c4df4-bd71606e)
[api-reference/v1.0/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-351824f3efc5b5771ed65b87fb5af027-bd71606e)
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-ed97e46383c275199ae427ec7f806b7c-bd71606e)
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-bbeb1267dad0fa06d99e2015401c896b-bd71606e)
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-c1b9061331d67da9045c58e356dc7f8c-bd71606e)
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a34eb42b2f6b30ba37f3ce1db2f08ffe-bd71606e)
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-3cbb7c521783ed60b73fd867831865c7-bd71606e)
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-14dad5230cbbd80ca6bcbb3e49e244d0-bd71606e)
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-0b570dc831c819dcaf5295d9cb169285-bd71606e)
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-26e2e78bd1710755a4848a6259d0318d-bd71606e)
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e84e4b4 [...]

2021-08-09 09:17 UTC, opbld32 commented
Docs Build status updates of commit _[6f41c6b](https://github.com/vishriv/microsoft-graph-docs/commits/6f41c6ba223c2a37b38173e7030acaada8f26beb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-9a1ce5075427c9f6299220c5d304a028-4a19f563)
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f5a4183ceabd35421ef2cd7c6e705faa-4a19f563)
[api-reference/v1.0/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-351824f3efc5b5771ed65b87fb5af027-4a19f563)
[api-reference/v1.0/api/group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-4a19f563)
[api-reference/v1.0/api/group-post-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-post-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e93d68b9e8674e589ed0998ad0d8e6fe-4a19f563)
[api-reference/v1.0/api/group-list.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-63041a508ca029ff40dcbc62cf60cf47-4a19f563)
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishri [...]

2021-08-09 09:33 UTC, opbld33 commented
Docs Build status updates of commit _[630e374](https://github.com/vishriv/microsoft-graph-docs/commits/630e3748ad868590a2a004513e90a11330885677)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-9a1ce5075427c9f6299220c5d304a028-66092145)
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-ee753de2c204bc0c23b2d81c21aad67b-66092145)
[api-reference/v1.0/api/group-post-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-post-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e93d68b9e8674e589ed0998ad0d8e6fe-66092145)
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [...]

2021-08-09 10:33 UTC, opbld34 commented
Docs Build status updates of commit _[af041e3](https://github.com/vishriv/microsoft-graph-docs/commits/af041e348240bfce46a873484c8a3dbe43b0c141)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-localizeddescription.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-localizeddescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-localizeddescription?view=graph-rest-1.0&branch= [...]

2021-08-10 14:20 UTC, opbld33 commented
Docs Build status updates of commit _[3ce63b1](https://github.com/vishriv/microsoft-graph-docs/commits/3ce63b1fa805c59c6692fcb22bcea5c11348d153)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-localizeddescription.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-localizeddescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-localizeddescription?view=graph-rest-1.0&branch= [...]

2021-08-13 02:26 UTC, Lauragra commented on changelog/Microsoft.SharePoint.json
> +          "ChangedApiName": "termStore.store,termStore.term,termStore.set,termStore.relation",
You're going to need one ChangeList item for each API/Target. Those fields are single valued.

2021-08-13 02:28 UTC, Lauragra commented
@vishriv , please include an update to the toc.yml file in the v1.0 folder, to surface the APIs in the TOC.

2021-08-16 08:57 UTC, opbld30 commented
Docs Build status updates of commit _[ec242bc](https://github.com/vishriv/microsoft-graph-docs/commits/ec242bc298edfe6cd6badadebba538b231464005)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-localizeddescription.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-localizeddescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-localizeddescription?view=graph-rest-1.0&branch= [...]

2021-08-16 09:35 UTC, opbld33 commented
Docs Build status updates of commit _[f5eb5be](https://github.com/vishriv/microsoft-graph-docs/commits/f5eb5be68e9e0151fc7a394d84080a027bf9ce84)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-localizeddescription.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-localizeddescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-localizeddescription?view=graph-rest-1.0&branch= [...]

2021-08-16 09:44 UTC, vishriv commented on changelog/Microsoft.SharePoint.json
> +          "ChangedApiName": "termStore.store,termStore.term,termStore.set,termStore.relation",
Done

2021-08-16 09:45 UTC, vishriv commented
> @vishriv , please include an update to the toc.yml file in the v1.0 folder, to surface the APIs in the TOC.

@Lauragra  updated

2021-08-16 09:48 UTC, opbld32 commented
Docs Build status updates of commit _[f5eb5be](https://github.com/vishriv/microsoft-graph-docs/commits/f5eb5be68e9e0151fc7a394d84080a027bf9ce84)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-localizeddescription.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-localizeddescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-localizeddescription?view=graph-rest-1.0&branch= [...]

2021-08-16 21:16 UTC, JarbasHorst requested changes

2021-08-16 21:16 UTC, JarbasHorst commented on api-reference/v1.0/api/termstore-term-list-relations.md
> +  "@odata.type": "collection(microsoft.graph.termStore.relation)"
Please, replace "@odata.type": "collection(microsoft.graph.termStore.relation)" with "@odata.type": "microsoft.graph.termStore.relation" and add the property: "isCollection": true.

2021-08-16 21:16 UTC, JarbasHorst commented on api-reference/v1.0/api/termstore-term-post.md
> +|labels|[microsoft.graph.termStore.localizedLabel](../resources/termstore-localizedlabel.md) collection|Label for the term to be created|
Please, add a period at the end of the sentence.

2021-08-16 21:16 UTC, JarbasHorst commented on api-reference/v1.0/api/termstore-term-post.md
> +The following table shows the properties that are required when you create the [term](../resources/termstore-term.md).
For consistency, I recommend you to add object after term. Suggested revision: 

- ...create the \[term\]\(../resources/termstore-term.md\) object.

2021-08-16 21:16 UTC, JarbasHorst commented on api-reference/v1.0/api/termstore-term-update.md
> +The following table shows the properties that can be updated for a [term](../resources/termstore-term.md).
For consistency, I recommend you to add object after term. Suggested revision: 

- ...updated for a \[term](../resources/termstore-term.md\) object.

2021-08-16 21:16 UTC, JarbasHorst commented on api-reference/v1.0/api/termstore-term-update.md
> +|labels|[microsoft.graph.termStore.localizedLabel](../resources/termstore-localizedlabel.md) collection|labels of a term|
Please,
- capitalize the first letter of a sentence
- add a period at the end of the sentence

2021-08-16 21:16 UTC, JarbasHorst commented on api-reference/v1.0/api/termstore-term-update.md
> +|descriptions|[microsoft.graph.termStore.localizedDescription](../resources/termstore-localizeddescription.md) collection|description about the term|
Please,
- capitalize the first letter of a sentence
- add a period at the end of the sentence

2021-08-16 21:16 UTC, JarbasHorst commented on api-reference/v1.0/api/termstore-term-update.md
> +|properties|[microsoft.graph.keyValue](../resources/keyvalue.md) collection|properties associated with the term|
Please,
- capitalize the first letter of a sentence
- add a period at the end of the sentence

2021-08-17 13:47 UTC, opbld30 commented
Docs Build status updates of commit _[7f6be39](https://github.com/vishriv/microsoft-graph-docs/commits/7f6be39e4c5e022d62df2a4d721af73f25b7dd9c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-cf67cbd8)
[api-reference/v1.0/api/group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-cf67cbd8)
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-grou [...]

2021-08-17 13:53 UTC, opbld31 commented
Docs Build status updates of commit _[94dafb8](https://github.com/vishriv/microsoft-graph-docs/commits/94dafb8a0c22d7babffa42cea714347db96e4ed5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-localizeddescription.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-localizeddescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-localizeddescription?view=graph-rest-1.0&branch= [...]

2021-08-17 14:52 UTC, opbld32 commented
Docs Build status updates of commit _[9652a42](https://github.com/vishriv/microsoft-graph-docs/commits/9652a4206beb5c474add6550808d8a7a59712fbb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-localizeddescription.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-localizeddescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-localizeddescription?view=graph-rest-1.0&branch= [...]

2021-08-17 15:49 UTC, opbld33 commented
Docs Build status updates of commit _[c3da791](https://github.com/vishriv/microsoft-graph-docs/commits/c3da79128b9655704bf40f9202eaa3a24288ce0c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-localizeddescription.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-localizeddescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-localizeddescription?view=graph-rest-1.0&branch= [...]

2021-08-17 16:20 UTC, opbld33 commented
Docs Build status updates of commit _[990e2fd](https://github.com/vishriv/microsoft-graph-docs/commits/990e2fd61abaf74a1074a7bb8c737ddf63c5247d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-localizeddescription.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-localizeddescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-localizeddescription?view=graph-rest-1.0&branch= [...]

2021-08-17 17:07 UTC, vishriv commented on api-reference/v1.0/api/termstore-relation-post.md
> +
@JarbasHorst Here I added 
<!-- {
  "blockType": "request",
  "name": "create_relation_from_"
}
-->

But the build is failing now :
https://dev.azure.com/msrobots/apidoctor/_build/results?buildId=61608&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dac0b392-2308-5704-b9f7-c5b20adf012e&l=12085

I have tried various strings in name, but couldn't find any success. Can you help me out here?
Resolved all other comments

2021-08-17 21:05 UTC, JarbasHorst requested changes

2021-08-17 21:05 UTC, JarbasHorst commented on changelog/Microsoft.SharePoint.json
> +      "WorkloadArea": "Sites and lists ",
Please, remove the empty space after lists.

2021-08-17 21:05 UTC, JarbasHorst commented on api-reference/v1.0/api/termstore-relation-post.md
> +
Thanks for your changes. I'll check internally how we can handle the build issue and get back to you.

2021-08-18 00:39 UTC, opbld33 commented
Docs Build status updates of commit _[d3db7aa](https://github.com/vishriv/microsoft-graph-docs/commits/d3db7aa5db00c1dc6329f85a81ee4804e2097dc8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-localizeddescription.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-localizeddescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-localizeddescription?view=graph-rest-1.0&branch= [...]

2021-08-18 00:41 UTC, opbld30 commented
Docs Build status updates of commit _[4d5167e](https://github.com/vishriv/microsoft-graph-docs/commits/4d5167e243e8c696decefded02c8a4019af81044)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-localizeddescription.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-localizeddescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-localizeddescription?view=graph-rest-1.0&branch= [...]

2021-08-18 00:44 UTC, opbld31 commented
Docs Build status updates of commit _[aba2927](https://github.com/vishriv/microsoft-graph-docs/commits/aba292731b35c1494d30c2a542af347c39703804)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-localizeddescription.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-localizeddescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-localizeddescription?view=graph-rest-1.0&branch= [...]

2021-08-18 01:03 UTC, opbld32 commented
Docs Build status updates of commit _[22829d7](https://github.com/vishriv/microsoft-graph-docs/commits/22829d74e0bc7aa1c31c3d47199a70a602973539)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-localizeddescription.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-localizeddescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-localizeddescription?view=graph-rest-1.0&branch= [...]

2021-08-18 19:37 UTC, opbld32 commented
Docs Build status updates of commit _[97639d3](https://github.com/vishriv/microsoft-graph-docs/commits/97639d33785d1ba4d4e214e29e0af6dff3906ed7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-localizeddescription.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-localizeddescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-localizeddescription?view=graph-rest-1.0&branch= [...]

2021-08-18 23:24 UTC, millicentachieng commented on api-reference/v1.0/resources/enums-termstore.md
> +  "namespace": "microsoft.graph.termstore"
Replace `termstore` with `termStore`

2021-08-18 23:27 UTC, millicentachieng commented on api-reference/v1.0/resources/termstore-relation.md
> +|[List relations](../api/termstore-term-list-relations.md)|[microsoft.graph.termstore.relation](../resources/termstore-relation.md) collection|Retrieve a list of **relation** objects.|
Replace `termstore` with `termStore`

2021-08-18 23:27 UTC, millicentachieng commented on api-reference/v1.0/resources/termstore-relation.md
> +|[Create relation](../api/termstore-relation-post.md)|[microsoft.graph.termstore.relation](../resources/termstore-relation.md)|Create a new **relation** object.|
Replace `termstore` with `termStore`

2021-08-23 12:50 UTC, opbld31 commented
Docs Build status updates of commit _[ae7aeb2](https://github.com/vishriv/microsoft-graph-docs/commits/ae7aeb2b7e40771325604a6b7f341761b0732cdd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-localizeddescription.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/termstore-localizeddescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-localizeddescription?view=graph-rest-1.0&branch= [...]

2021-08-23 14:08 UTC, vishriv commented on api-reference/v1.0/resources/termstore-relation.md
> +|[Create relation](../api/termstore-relation-post.md)|[microsoft.graph.termstore.relation](../resources/termstore-relation.md)|Create a new **relation** object.|
Done

2021-08-23 14:08 UTC, vishriv commented on api-reference/v1.0/resources/termstore-relation.md
> +|[List relations](../api/termstore-term-list-relations.md)|[microsoft.graph.termstore.relation](../resources/termstore-relation.md) collection|Retrieve a list of **relation** objects.|
Done

2021-08-23 14:08 UTC, vishriv commented on api-reference/v1.0/resources/enums-termstore.md
> +  "namespace": "microsoft.graph.termstore"
Done

2021-08-23 14:16 UTC, vishriv commented
@JarbasHorst @Lauragra @millicentachieng Thanks for reviewing this PR. I have worked on and resolved all the comments.

2021-08-23 21:59 UTC, Lauragra commented on api-reference/v1.0/api/termstore-group-delete.md
> +title: "Delete termStore group"
Global: I see that we're including the subnamespace in the topic title for the v1.0 files, but we didn't do the same in beta, i.e.: https://docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&tabs=http. Let's keep them consistent and remove the subnamespace from the titles in the v1.0 files.

2021-08-23 22:02 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +      - name: Taxonomy
Can you please change ListItems to List items on line 5237? That's an inconsistency I noticed on the site (not related to this PR). Related to this PR, now that the API is GA, we also need to remove "(preview)' from the entry in the beta TOC.

2021-08-23 22:06 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +          - name: List
We should list the CRUD operations in a consistent order in the TOC: List, Create, Get, Update, Delete. Please move List to come before Create.

2021-08-24 08:15 UTC, opbld30 commented
Docs Build status updates of commit _[09fe178](https://github.com/vishriv/microsoft-graph-docs/commits/09fe17875c383dec128db4df0c94a2d757d54b2f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) | [Details](#user-content-0a32ea275f788f452d45484ad97e11ef-4dfbe07e)
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-r [...]

2021-08-24 08:19 UTC, opbld31 commented
Docs Build status updates of commit _[d206f05](https://github.com/vishriv/microsoft-graph-docs/commits/d206f0590b099f6312beba118f818119e919714c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https [...]

2021-08-24 08:24 UTC, vishriv commented on api-reference/v1.0/api/termstore-group-delete.md
> +title: "Delete termStore group"
That was causing issue. Some other file also has the same title and heading 'delete groups', and hence I changed it to complete name. I also changed the title and heading in the corresponding beta file in this PR now for consistency

2021-08-25 01:49 UTC, opbld30 commented
Docs Build status updates of commit _[d98f2e7](https://github.com/vishriv/microsoft-graph-docs/commits/d98f2e7391cf8b007f0a7c2d80a607c32b923022)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https [...]

2021-08-25 02:04 UTC, opbld32 commented
Docs Build status updates of commit _[14104f2](https://github.com/vishriv/microsoft-graph-docs/commits/14104f2d8666e8eab25050ee28ec145ed404e4ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https [...]

2021-08-25 02:10 UTC, opbld34 commented
Docs Build status updates of commit _[f37c42e](https://github.com/vishriv/microsoft-graph-docs/commits/f37c42e94740a81914bb039c980bb900eb2e7216)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/site.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/termstore-group.md](https [...]

2021-08-25 02:12 UTC, opbld31 commented
Docs Build status updates of commit _[598b03e](https://github.com/vishriv/microsoft-graph-docs/commits/598b03ecd8b5f7a0aa5a36c3a39edb2af1affdec)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-f1b966fd)
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e57a71b6a4411d61e991f1e543006dfb-f1b966fd)
[api-reference/v1.0/api/group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-f1b966fd)
[api-reference/v1.0/api/group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-f1b966fd)
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://revie [...]

2021-08-25 02:13 UTC, opbld34 commented
Docs Build status updates of commit _[a223a8c](https://github.com/vishriv/microsoft-graph-docs/commits/a223a8c114538186d66dd5b115078ae9437254af)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-723a69ab)
[api-reference/v1.0/api/group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-723a69ab)
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-relations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-relations?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-termstore.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/resources/enums-termstore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-termstore?view=graph-re [...]

2021-08-25 02:15 UTC, opbld32 commented
Docs Build status updates of commit _[d5295b7](https://github.com/vishriv/microsoft-graph-docs/commits/d5295b74ad978c98e20e39e6e2ab1720f37e4c3c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-0774ffe4)
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e57a71b6a4411d61e991f1e543006dfb-0774ffe4)
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-9a1ce5075427c9f6299220c5d304a028-0774ffe4)
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f5a4183ceabd35421ef2cd7c6e705faa-0774ffe4)
[api-reference/v1.0/api/group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-0774ffe4)
[api-reference/v1.0/api/group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-0774ffe4)
[api-reference/v1.0/api/group-post-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-post-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e93d68b9e8674e589ed0998ad0d8e6fe-0774ffe4)
[api-reference/v1.0/api/group-list.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-63041a508ca029ff40dcbc62cf60cf47-0774ffe4)
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https:// [...]

2021-08-25 02:17 UTC, opbld30 commented
Docs Build status updates of commit _[398a4cc](https://github.com/vishriv/microsoft-graph-docs/commits/398a4cc5ed79dcd9f025fd3e770699d801d49d97)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-5b7e40ae)
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e57a71b6a4411d61e991f1e543006dfb-5b7e40ae)
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-9a1ce5075427c9f6299220c5d304a028-5b7e40ae)
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f5a4183ceabd35421ef2cd7c6e705faa-5b7e40ae)
[api-reference/v1.0/api/group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-5b7e40ae)
[api-reference/v1.0/api/group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-5b7e40ae)
[api-reference/v1.0/api/group-post-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-post-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e93d68b9e8674e589ed0998ad0d8e6fe-5b7e40ae)
[api-reference/v1.0/api/group-list.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-63041a508ca029ff40dcbc62cf60cf47-5b7e40ae)
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https:// [...]

2021-08-25 02:20 UTC, opbld30 commented
Docs Build status updates of commit _[10a0fbe](https://github.com/vishriv/microsoft-graph-docs/commits/10a0fbe4d85e9c76e7009e4e155635c656345a35)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-7057f707)
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e57a71b6a4411d61e991f1e543006dfb-7057f707)
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-9a1ce5075427c9f6299220c5d304a028-7057f707)
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f5a4183ceabd35421ef2cd7c6e705faa-7057f707)
[api-reference/v1.0/api/group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-7057f707)
[api-reference/v1.0/api/group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-7057f707)
[api-reference/v1.0/api/group-list.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-63041a508ca029ff40dcbc62cf60cf47-7057f707)
[api-reference/v1.0/api/group-post-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-post-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e93d68b9e8674e589ed0998ad0d8e6fe-7057f707)
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https:// [...]

2021-08-25 02:22 UTC, opbld30 commented
Docs Build status updates of commit _[036ffe6](https://github.com/vishriv/microsoft-graph-docs/commits/036ffe6d6690187c1238f93653612864eb666c5c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-3f675cd7)
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e57a71b6a4411d61e991f1e543006dfb-3f675cd7)
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-9a1ce5075427c9f6299220c5d304a028-3f675cd7)
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f5a4183ceabd35421ef2cd7c6e705faa-3f675cd7)
[api-reference/v1.0/api/group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-3f675cd7)
[api-reference/v1.0/api/group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-3f675cd7)
[api-reference/v1.0/api/group-list.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-63041a508ca029ff40dcbc62cf60cf47-3f675cd7)
[api-reference/v1.0/api/group-post-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-post-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e93d68b9e8674e589ed0998ad0d8e6fe-3f675cd7)
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https:// [...]

2021-08-25 02:23 UTC, opbld33 commented
Docs Build status updates of commit _[9481d17](https://github.com/vishriv/microsoft-graph-docs/commits/9481d17cc2a360ee4f4a4eac36ddaa9dffa5f462)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-0a1319ae)
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e57a71b6a4411d61e991f1e543006dfb-0a1319ae)
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-9a1ce5075427c9f6299220c5d304a028-0a1319ae)
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f5a4183ceabd35421ef2cd7c6e705faa-0a1319ae)
[api-reference/v1.0/api/group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-0a1319ae)
[api-reference/v1.0/api/group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-0a1319ae)
[api-reference/v1.0/api/group-post-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-post-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e93d68b9e8674e589ed0998ad0d8e6fe-0a1319ae)
[api-reference/v1.0/api/group-list.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-63041a508ca029ff40dcbc62cf60cf47-0a1319ae)
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https:// [...]

2021-08-25 02:25 UTC, opbld30 commented
Docs Build status updates of commit _[cb95e89](https://github.com/vishriv/microsoft-graph-docs/commits/cb95e8905c1012d6e3c8d7447abb392fb72abd75)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-146a5a08)
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e57a71b6a4411d61e991f1e543006dfb-146a5a08)
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-9a1ce5075427c9f6299220c5d304a028-146a5a08)
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f5a4183ceabd35421ef2cd7c6e705faa-146a5a08)
[api-reference/v1.0/api/group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-146a5a08)
[api-reference/v1.0/api/group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-146a5a08)
[api-reference/v1.0/api/group-post-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-post-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e93d68b9e8674e589ed0998ad0d8e6fe-146a5a08)
[api-reference/v1.0/api/group-list.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-63041a508ca029ff40dcbc62cf60cf47-146a5a08)
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https:// [...]

2021-08-25 02:27 UTC, opbld32 commented
Docs Build status updates of commit _[347deb4](https://github.com/vishriv/microsoft-graph-docs/commits/347deb492e1573d8eaf7b9c186e2142805011c3f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-df62f217)
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e57a71b6a4411d61e991f1e543006dfb-df62f217)
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-9a1ce5075427c9f6299220c5d304a028-df62f217)
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f5a4183ceabd35421ef2cd7c6e705faa-df62f217)
[api-reference/v1.0/api/group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-df62f217)
[api-reference/v1.0/api/group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-df62f217)
[api-reference/v1.0/api/group-list.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-63041a508ca029ff40dcbc62cf60cf47-df62f217)
[api-reference/v1.0/api/group-post-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-post-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e93d68b9e8674e589ed0998ad0d8e6fe-df62f217)
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https:// [...]

2021-08-25 02:28 UTC, opbld33 commented
Docs Build status updates of commit _[38223ae](https://github.com/vishriv/microsoft-graph-docs/commits/38223ae12c93fa5c39b7dba432b7456659341f64)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-847462fd)
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e57a71b6a4411d61e991f1e543006dfb-847462fd)
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-9a1ce5075427c9f6299220c5d304a028-847462fd)
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f5a4183ceabd35421ef2cd7c6e705faa-847462fd)
[api-reference/v1.0/api/group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-847462fd)
[api-reference/v1.0/api/group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-847462fd)
[api-reference/v1.0/api/group-post-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-post-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e93d68b9e8674e589ed0998ad0d8e6fe-847462fd)
[api-reference/v1.0/api/group-list.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-63041a508ca029ff40dcbc62cf60cf47-847462fd)
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https:// [...]

2021-08-25 02:30 UTC, Lauragra approved these changes

2021-08-25 02:30 UTC, opbld33 commented
Docs Build status updates of commit _[0e8ab1f](https://github.com/vishriv/microsoft-graph-docs/commits/0e8ab1fb777d867d41637ad8dfbda28ca1c364f8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f692665dd9a05ddc38d36652f22d9882-c5b5f118)
[api-reference/v1.0/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e57a71b6a4411d61e991f1e543006dfb-c5b5f118)
[api-reference/v1.0/api/termstore-group-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-9a1ce5075427c9f6299220c5d304a028-c5b5f118)
[api-reference/v1.0/api/termstore-list-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-list-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-list-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-f5a4183ceabd35421ef2cd7c6e705faa-c5b5f118)
[api-reference/v1.0/api/group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-c5b5f118)
[api-reference/v1.0/api/group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-a10b0358399fc0f83f37a8db1c76d74d-c5b5f118)
[api-reference/v1.0/api/group-post-groups.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-post-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-e93d68b9e8674e589ed0998ad0d8e6fe-c5b5f118)
[api-reference/v1.0/api/group-list.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/group-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) | [Details](#user-content-63041a508ca029ff40dcbc62cf60cf47-c5b5f118)
[api-reference/beta/api/termstore-group-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/api/termstore-group-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-delete?view=graph-rest-beta&branch=pr-en-us-13432) (graph-rest-beta) |
[api-reference/v1.0/api/termstore-group-list-sets.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-group-list-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-list-sets?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-relation-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-relation-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-relation-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-post.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-set-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-set-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-store-update.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-store-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-update?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-delete.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-children.md](https://github.com/vishriv/microsoft-graph-docs/blob/advancingTermStoreAPIs/api-reference/v1.0/api/termstore-term-list-children.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-1.0&branch=pr-en-us-13432) (>= graph-rest-1.0) |
[api-reference/v1.0/api/termstore-term-list-relations.md](https:// [...]

2021-08-25 02:39 UTC, merged