[Substrate Connectors] [Beta] Document breaking changes for beta namespace
microsoftgraph/microsoft-graph-docs pull request #13443
Opened 2021-07-09 19:37 UTC by emzho

For this documentation change, we are updating API references for Search APIs to:
1. Make sure namespace references are updated from microsoft.graph --> microsoft.graph.externalConnectors
2. Remove @odata.type references from code examples
2. Make sure property name is updated from authorizedApps --> authorizedAppIds
3. Update "property" enum to be camel-cased
4. Update error object to be graph.publicError object

2021-07-09 19:38 UTC, opbld33 commented
Docs Build status updates of commit _[69081d7](https://github.com/emzho/microsoft-graph-docs/commits/69081d7b85170c10dcd7b1b2e51d5b1d96bb5715)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3cb82e7a)

<a id="3cb82e7a"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091937522217-13443%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A03%3A42Z&ske=2021-07-13T07%3A08%3A42Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T19%3A33%3A13Z&se=2021-08-09T19%3A38%3A13Z&sr=b&sp=r&sig=CjE8W7inO0XXVqDa7FbwgNR9sVlzefLBeyJ%2BIac7WNk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 19:56 UTC, opbld30 commented
Docs Build status updates of commit _[a506917](https://github.com/emzho/microsoft-graph-docs/commits/a50691764ba5af8b57ee2cbf912401f61794f30a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/configuration?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-abccac792fabab99c14a24e1f5bcfb2f-afb0f3da)
[api-reference/beta/resources/connectionoperation.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/connectionoperation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectionoperation?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-ce39625adf20511404f59b39d2f28f9e-afb0f3da)
[api-reference/beta/resources/errordetail.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/errordetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/errordetail?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-45fc9bec623a6be9bad3d9cf0cfd1337-afb0f3da)
[api-reference/beta/resources/externalfile.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/externalfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalfile?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-eb0f7d67e21050dee482168477c8c0d4-afb0f3da)
[api-reference/beta/resources/innererrordetail.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/innererrordetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/innererrordetail?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-17a770e730eb0683c903742ff295c333-afb0f3da)
[api-reference/beta/resources/property.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/property.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/property?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-456d119d058165c12427213ff1f8b0b3-afb0f3da)
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-afb0f3da)
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delet [...]

2021-07-09 21:05 UTC, opbld30 commented
Docs Build status updates of commit _[2e2b038](https://github.com/emzho/microsoft-graph-docs/commits/2e2b038c8aed076d01327ab9c3420d23f941a116)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-2f80062949c41a89f3f1297b919e186f-638f4a0a)
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-67110970249147ba22e5afddd90e7595-638f4a0a)
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-efe5d39b4370451d340764d571484c81-638f4a0a)
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-ab7eddae7518905e8a3226bc0c911b01-638f4a0a)
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-a27cbdab42647d39611f748cff49a415-638f4a0a)
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-54e86d9c003bb16344a17d6ca9f2fcc4-638f4a0a)
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-86e1716585181f97dc6466c421e6e2e8-638f4a0a)
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-7350ec8c70788eb56949b2a13e543914-638f4a0a)
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-9379084067fb7286c555aa390d4f8252-638f4a0a)
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-b646561123599abfd80d362a45fe499d-638f4a0a)
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-f05bae2aa705fef72ceb7a775852c2fa-638f4a0a)
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-12489e7911afc7e2767d59cadc62d85f-638f4a0a)
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-f0026a283e9d01c12bd3d4f7289b3e5d-638f4a0a)
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-2a81d1655c3ed31afd7199736b0c9903-638f4a0a)
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-0b9c80b80aa5e4b12e95fcf78bbb2a29-638f4a0a)
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-ec420a8f6dbb58ea487374ee617e5f6e-638f4a0a)
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-4b22c74763fa5d197553abcaf6694966-638f4a0a)
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.c [...]

2021-07-09 21:12 UTC, opbld33 commented
Docs Build status updates of commit _[fc23996](https://github.com/emzho/microsoft-graph-docs/commits/fc23996d4aab63db007754e72dbb8716bef80f05)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-2f80062949c41a89f3f1297b919e186f-43496646)
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-67110970249147ba22e5afddd90e7595-43496646)
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-efe5d39b4370451d340764d571484c81-43496646)
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-ab7eddae7518905e8a3226bc0c911b01-43496646)
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-a27cbdab42647d39611f748cff49a415-43496646)
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-54e86d9c003bb16344a17d6ca9f2fcc4-43496646)
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-86e1716585181f97dc6466c421e6e2e8-43496646)
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-7350ec8c70788eb56949b2a13e543914-43496646)
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-9379084067fb7286c555aa390d4f8252-43496646)
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-b646561123599abfd80d362a45fe499d-43496646)
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-f05bae2aa705fef72ceb7a775852c2fa-43496646)
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-12489e7911afc7e2767d59cadc62d85f-43496646)
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-f0026a283e9d01c12bd3d4f7289b3e5d-43496646)
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-2a81d1655c3ed31afd7199736b0c9903-43496646)
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-0b9c80b80aa5e4b12e95fcf78bbb2a29-43496646)
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-ec420a8f6dbb58ea487374ee617e5f6e-43496646)
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-4b22c74763fa5d197553abcaf6694966-43496646)
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.c [...]

2021-07-09 21:33 UTC, opbld30 commented
Docs Build status updates of commit _[1899bc7](https://github.com/emzho/microsoft-graph-docs/commits/1899bc757a574d06b14bb19c60cb2e37ab2a7441)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-c2dcd9f7)
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/configuration?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/connectionoperation.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/connectionoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectionoperation?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github [...]

2021-07-09 22:13 UTC, opbld33 commented
Docs Build status updates of commit _[724da3a](https://github.com/emzho/microsoft-graph-docs/commits/724da3a54acc973fd68400ac341677008203144f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-20e29923)

<a id="20e29923"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107092213287465-13443%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T09%3A21%3A19Z&ske=2021-07-13T09%3A26%3A19Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T22%3A08%3A52Z&se=2021-08-09T22%3A13%3A52Z&sr=b&sp=r&sig=d4FmkIZbxuJGLoo783Nk%2BwIUPsL4tXIP19XFPZF%2BMBI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 22:57 UTC, opbld33 commented
Docs Build status updates of commit _[6248241](https://github.com/emzho/microsoft-graph-docs/commits/624824116f37e7208443a69bae07fdc106cfa8f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-6cb8ceeb)
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/configuration?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/connectionoperation.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/connectionoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectionoperation?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github [...]

2021-07-09 23:42 UTC, opbld32 commented
Docs Build status updates of commit _[68f1378](https://github.com/emzho/microsoft-graph-docs/commits/68f13788ab2781b42d9dd1870b8577659910fea8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-f1ecab5d)
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/configuration?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/connectionoperation.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/connectionoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectionoperation?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github [...]

2021-07-10 00:37 UTC, opbld31 commented
Docs Build status updates of commit _[d8a71eb](https://github.com/emzho/microsoft-graph-docs/commits/d8a71eb00e262b521a1ed229a57e0d35a490b200)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-bd2590b1)
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/configuration?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/connectionoperation.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/connectionoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectionoperation?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github [...]

2021-07-10 00:50 UTC, opbld32 commented
Docs Build status updates of commit _[5259bc3](https://github.com/emzho/microsoft-graph-docs/commits/5259bc3e05bb22e1fb4a3e5ba06e474654aabcdf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-c47801fb)
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/configuration?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/connectionoperation.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/connectionoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectionoperation?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github [...]

2021-07-10 00:54 UTC, opbld33 commented
Docs Build status updates of commit _[e93f191](https://github.com/emzho/microsoft-graph-docs/commits/e93f1918e816edff11cc5a41beefd441271b6d3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-10df47a4)
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/configuration?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/connectionoperation.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/connectionoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectionoperation?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github [...]

2021-07-10 01:05 UTC, opbld30 commented
Docs Build status updates of commit _[72b6202](https://github.com/emzho/microsoft-graph-docs/commits/72b620271fe3445567ba522c1f77d751390f7871)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-10 01:40 UTC, opbld34 commented
Docs Build status updates of commit _[2ea2dc5](https://github.com/emzho/microsoft-graph-docs/commits/2ea2dc5ee09fceb239231f3c366b835e559af42a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-58187a03)
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/configuration?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/connectionoperation.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/connectionoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectionoperation?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github [...]

2021-07-10 02:43 UTC, opbld32 commented
Docs Build status updates of commit _[4bb0385](https://github.com/emzho/microsoft-graph-docs/commits/4bb03858e1f175471701b3f0fd96cbb1e2db594c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-882dcf11)
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/configuration?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/connectionoperation.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/connectionoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectionoperation?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github [...]

2021-07-10 02:49 UTC, opbld30 commented
Docs Build status updates of commit _[7e00823](https://github.com/emzho/microsoft-graph-docs/commits/7e00823996d13744208b94e2a7274779735127ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-7d4d0d3c)
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/configuration?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/connectionoperation.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/connectionoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectionoperation?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github [...]

2021-07-12 15:36 UTC, opbld33 commented
Docs Build status updates of commit _[f07347d](https://github.com/emzho/microsoft-graph-docs/commits/f07347d915d74e83fe718e8796cc942ed9b44ab9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-d5560868)
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/configuration?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/connectionoperation.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/connectionoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectionoperation?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github [...]

2021-07-12 16:30 UTC, opbld30 commented
Docs Build status updates of commit _[259cf29](https://github.com/emzho/microsoft-graph-docs/commits/259cf2913ed8d3ce6de5338186c3eb6c7dc0270c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3b8be2ff)

<a id="3b8be2ff"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107121629323039-13443%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-12T07%3A22%3A02Z&ske=2021-07-19T07%3A27%3A02Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-12T16%3A25%3A05Z&se=2021-08-12T16%3A30%3A05Z&sr=b&sp=r&sig=gl99OvFpj2RRZASpQw%2BXXkrRZDo5ZHhPzQS%2FDnDOSAg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-12 17:29 UTC, opbld33 commented
Docs Build status updates of commit _[f957fa1](https://github.com/emzho/microsoft-graph-docs/commits/f957fa18da27a4e8048d75b2a7d78fb5eb8b149b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-ca40e126)
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/configuration?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/connectionoperation.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/connectionoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectionoperation?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github [...]

2021-07-12 20:32 UTC, opbld33 commented
Docs Build status updates of commit _[b654182](https://github.com/emzho/microsoft-graph-docs/commits/b654182bbd51739ec7195d150d8fdad229ac1030)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-6b2c92be)
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/configuration?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/connectionoperation.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/connectionoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectionoperation?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github [...]

2021-07-12 21:04 UTC, millicentachieng commented on api-reference/beta/resources/externalitem.md
> +  "content": {
Change this back to `"content": {"@odata.type": "microsoft.graph.externalItemContent"}`

2021-07-12 21:16 UTC, opbld32 commented
Docs Build status updates of commit _[bbc653d](https://github.com/emzho/microsoft-graph-docs/commits/bbc653dd76e3ced0d52fc06332a402b97e9c5997)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-7febac2f)
[api-reference/beta/api/connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/configuration?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/connectionoperation.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/connectionoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectionoperation?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github [...]

2021-07-12 21:52 UTC, opbld31 commented
Docs Build status updates of commit _[fcfed36](https://github.com/emzho/microsoft-graph-docs/commits/fcfed361221b080f357f59b5af30ffe71b323e4d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-497eb1fb)
[api-reference/beta/api/external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/configuration.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/configuration?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/connectionoperation.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/connectionoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectionoperation?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[ap [...]

2021-07-12 22:15 UTC, opbld30 commented
Docs Build status updates of commit _[9060d24](https://github.com/emzho/microsoft-graph-docs/commits/9060d24380e7393518685c0c31dd4fa8e2125169)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/externalconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnection?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-bb9c1f640fc94db76e31d9ebcb92af80-d8784f7e)
[api-reference/beta/toc.yml](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d8784f7e)
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-d8784f7e)
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github [...]

2021-07-12 22:21 UTC, opbld30 commented
Docs Build status updates of commit _[ae081ab](https://github.com/emzho/microsoft-graph-docs/commits/ae081ab5a44f4f093583d6383a7abf78ef2438ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-d0198709)
[api-reference/beta/api/externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/errordetail.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/external [...]

2021-07-12 22:56 UTC, opbld33 commented
Docs Build status updates of commit _[1dbc45d](https://github.com/emzho/microsoft-graph-docs/commits/1dbc45ddf531325effa2bcdfa4ceabfb463bc517)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-6e1bcc44)
[api-reference/beta/api/externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/acl.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/acl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acl?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/errordetail.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/ext [...]

2021-07-12 23:33 UTC, opbld30 commented
Docs Build status updates of commit _[accf361](https://github.com/emzho/microsoft-graph-docs/commits/accf361aea68853fc4f44bbc4d2e007fb4a8a7b2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/indexing-api-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/indexing-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/indexing-api-overview?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) | [Details](#user-content-df4ddce7576ff041ab93fae03305f920-27909aed)
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-27909aed)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) |  [...]

2021-07-12 23:38 UTC, opbld32 commented
Docs Build status updates of commit _[d25c65e](https://github.com/emzho/microsoft-graph-docs/commits/d25c65e880359c5c7326cd8c7613abaf32821cf4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-708be94e)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/errordetail.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/errordetail.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalc [...]

2021-07-13 00:03 UTC, opbld34 commented
Docs Build status updates of commit _[ed1d2ae](https://github.com/emzho/microsoft-graph-docs/commits/ed1d2aebddb21f5c88379deb0ef5b5379a76ea69)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-c8f80e46)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-07-13 00:19 UTC, opbld30 commented
Docs Build status updates of commit _[6fa184e](https://github.com/emzho/microsoft-graph-docs/commits/6fa184e85bd9bb2635a58d5437b837d039906fa4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-e8045fd4)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-07-13 01:14 UTC, opbld31 commented
Docs Build status updates of commit _[a6c7bbc](https://github.com/emzho/microsoft-graph-docs/commits/a6c7bbcd13a75eb3d4922e5e246a64ebc2ff714e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-50d554e7)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-07-13 23:52 UTC, opbld33 commented
Docs Build status updates of commit _[2c5765b](https://github.com/emzho/microsoft-graph-docs/commits/2c5765bab151d2fe089bfb7e82b19a9175b68bbe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-565ecae5)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-07-14 00:01 UTC, opbld34 commented
Docs Build status updates of commit _[54a2d17](https://github.com/emzho/microsoft-graph-docs/commits/54a2d17f47b249e255c8357cbcdc3ce89334c14c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-1cec9c82)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-07-14 00:17 UTC, opbld31 commented
Docs Build status updates of commit _[217a344](https://github.com/emzho/microsoft-graph-docs/commits/217a344bfffb22fb04fc047d9912f735e7460ae1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-ee918fe5)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-07-14 00:47 UTC, opbld31 commented
Docs Build status updates of commit _[62e57ef](https://github.com/emzho/microsoft-graph-docs/commits/62e57efaf6589731480e9d3ebd0904a689f3dd60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-c87c4b3a)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-07-14 23:23 UTC, opbld32 commented
Docs Build status updates of commit _[c9417e2](https://github.com/emzho/microsoft-graph-docs/commits/c9417e22a7e757288f944d1091b3bf48f8065719)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-82b624e5)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-07-15 00:08 UTC, opbld31 commented
Docs Build status updates of commit _[85a3697](https://github.com/emzho/microsoft-graph-docs/commits/85a3697975b6ca0b22c77e52c56b4f3710c03477)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-overview.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/concepts/search-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-13443) | [Details](#user-content-7cb11786d41d4703485e1bee03934187-b702fad9)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-07-15 17:17 UTC, jasonjoh commented on api-reference/beta/api/externalconnectors-connectionoperation-get.md
> +If successful, this method returns a `200 OK` response code and the requested [connectionOperation](../resources/externalconnectors-connectionoperation.md) object in the response body.
Renaming files will change their URL. Any links to the old URL will 404 unless we set redirects.

2021-07-15 19:38 UTC, emzho commented on api-reference/beta/api/externalconnectors-connectionoperation-get.md
> +If successful, this method returns a `200 OK` response code and the requested [connectionOperation](../resources/externalconnectors-connectionoperation.md) object in the response body.
Yep! I think I have resolved all the file renames and hyperlinks for this. API doctor / other validation flagged broken hyperlinks for us, which was helpful.

2021-07-15 19:52 UTC, jasonjoh requested changes

2021-07-15 19:52 UTC, jasonjoh commented on api-reference/beta/api/externalconnectors-externalconnection-list.md
> +> [!NOTE]
This needs more context. Just looking at this topic, this is the only mention of the `authorizedApps` property, so it seems confusing to bring it up at all. A note about the property being deprecate may make more sense in the resource topic for `externalConnection`.

2021-07-15 19:52 UTC, jasonjoh commented on api-reference/beta/api/externalconnectors-externalitem-delete.md
> +| connection-id | String | The `id` property of the containing [externalConnection](../resources/externalconnectors-externalconnection.md) |
lowercase `string`

2021-07-15 19:52 UTC, jasonjoh commented on api-reference/beta/api/externalconnectors-externalconnection-put-items.md
> +| connection-id | String | The `id` property of the containing [externalConnection](../resources/externalconnectors-externalconnection.md) |
lowercase `string`

2021-07-15 19:52 UTC, jasonjoh commented on api-reference/beta/api/externalconnectors-externalitem-update.md
> +| connection-id | String | The `id` property of the containing [externalConnection](../resources/externalconnectors-externalconnection.md) |
lowercase `string`

2021-07-15 19:52 UTC, jasonjoh commented on api-reference/beta/resources/externalconnectors-configuration.md
> +| authorizedAppIds | String collection | A collection of application IDs for registered Azure Active Directory apps that are allowed to manage the externalConnection and to index content in the exter
Here would probably be a good place to put the note about renaming the property.

2021-07-15 19:53 UTC, opbld31 commented
Docs Build status updates of commit _[1c66170](https://github.com/emzho/microsoft-graph-docs/commits/1c6617015a5ee16454123f733f28d09f426a2141)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/.openpublishing.redirection.json) | :bulb:Suggestion | | [Details](#user-content-a8f2a63f2a67f506c881c8621af9e49f-2cba8777)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=p [...]

2021-07-15 19:53 UTC, jasonjoh commented on api-reference/beta/api/externalconnectors-connectionoperation-get.md
> +If successful, this method returns a `200 OK` response code and the requested [connectionOperation](../resources/externalconnectors-connectionoperation.md) object in the response body.
I added redirect entries to the .openpublishing.redirect.json so if there are any links out there to the old versions they won't be broken. Can you give the changes to that file a quick glance to see if I missed any?

2021-07-15 19:55 UTC, opbld30 commented
Docs Build status updates of commit _[695d860](https://github.com/emzho/microsoft-graph-docs/commits/695d86017fea3a1944207b261088ef6cadc0faa2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/.openpublishing.redirection.json) | :bulb:Suggestion | | [Details](#user-content-a8f2a63f2a67f506c881c8621af9e49f-8b932973)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=p [...]

2021-07-15 20:29 UTC, emzho commented on api-reference/beta/api/externalconnectors-connectionoperation-get.md
> +ms.author: mecampos
Ok, will do.

2021-07-15 20:31 UTC, emzho commented on api-reference/beta/api/externalconnectors-externalconnection-list.md
> +> [!NOTE]
@snlraju-msft can you help with this?

2021-07-15 20:54 UTC, opbld32 commented
Docs Build status updates of commit _[c29b411](https://github.com/emzho/microsoft-graph-docs/commits/c29b4119f392a42d19cd9cb01cfd3ee4739f3528)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/.openpublishing.redirection.json) | :bulb:Suggestion | | [Details](#user-content-a8f2a63f2a67f506c881c8621af9e49f-e5801edc)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=p [...]

2021-07-15 20:59 UTC, opbld33 commented
Docs Build status updates of commit _[e4d5c97](https://github.com/emzho/microsoft-graph-docs/commits/e4d5c97fadc62f4a70b0d57b2969045b42b648e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/.openpublishing.redirection.json) | :bulb:Suggestion | | [Details](#user-content-a8f2a63f2a67f506c881c8621af9e49f-39b4447b)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=p [...]

2021-07-15 21:01 UTC, jasonjoh commented
Remaining warnings about .openpublishing.redirection.json are caused by values that were already in the file prior to my edits. Opened https://github.com/microsoftgraph/microsoft-graph-docs/issues/13528 to track cleanup of that file as a separate work item.

2021-07-15 21:36 UTC, opbld34 commented
Docs Build status updates of commit _[be950dd](https://github.com/emzho/microsoft-graph-docs/commits/be950dd2454e66a0625a824886af2bb181d85102)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/.openpublishing.redirection.json) | :bulb:Suggestion | | [Details](#user-content-a8f2a63f2a67f506c881c8621af9e49f-aefba56a)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=p [...]

2021-07-15 21:44 UTC, emzho commented on api-reference/beta/resources/externalconnectors-configuration.md
> +| authorizedAppIds | String collection | A collection of application IDs for registered Azure Active Directory apps that are allowed to manage the externalConnection and to index content in the exter
@snlraju-msft -- leaving this for you 👍

2021-07-16 10:16 UTC, millicentachieng commented on api-reference/beta/resources/externalconnectors-externalitem.md
> +  "content": {
Remove `value` and `type` properties. Having `"@odata.type": "microsoft.graph.externalConnectors.externalItemContent"` already indicates these two properties are expected.

2021-07-16 16:59 UTC, snlraju-msft commented on api-reference/beta/api/externalconnectors-externalconnection-list.md
> +> [!NOTE]
Resolving this as this is covered in the breaking changes blog.

2021-07-16 17:27 UTC, jasonjoh commented on api-reference/beta/resources/externalconnectors-externalitem.md
> +  "content": {
Taking care of it.

2021-07-16 17:29 UTC, jasonjoh commented on api-reference/beta/api/externalconnectors-externalconnection-list.md
> +> [!NOTE]
Removed per our convo

2021-07-16 17:31 UTC, jasonjoh commented on api-reference/beta/resources/externalconnectors-configuration.md
> +| authorizedAppIds | String collection | A collection of application IDs for registered Azure Active Directory apps that are allowed to manage the externalConnection and to index content in the exter
Added note.

2021-07-16 17:34 UTC, jasonjoh approved these changes

2021-07-16 17:36 UTC, opbld30 commented
Docs Build status updates of commit _[da8ce46](https://github.com/emzho/microsoft-graph-docs/commits/da8ce4647d976d33c1f82dcea2f3cbb778d955f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/.openpublishing.redirection.json) | :bulb:Suggestion | | [Details](#user-content-a8f2a63f2a67f506c881c8621af9e49f-c51e2241)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=p [...]

2021-07-16 17:51 UTC, opbld30 commented
Docs Build status updates of commit _[de295b1](https://github.com/emzho/microsoft-graph-docs/commits/de295b1ad05b266ef03ccba3406bd6a7d158955e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/.openpublishing.redirection.json) | :bulb:Suggestion | | [Details](#user-content-a8f2a63f2a67f506c881c8621af9e49f-f7bc7e0b)
[api-reference/beta/api/externalconnectors-connectionoperation-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-connectionoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-connectionoperation-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-external-post-connections.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-list.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-list?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-put-items.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-put-items.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-put-items?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalconnection-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalconnection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-delete.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-delete?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13443) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-substrateConnectors-betaNamespaceBreakingChanges/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=p [...]

2021-07-16 17:54 UTC, merged