Promote SCP doc from beta to v1.0
microsoftgraph/microsoft-graph-docs pull request #13463
Opened 2021-07-12 20:57 UTC by payiAzure

Service communications API is new API published on beta. We would like to promote the API doc from beta to v1.0.
So add all API files and resource files under v1.0

2021-07-12 20:59 UTC, opbld34 commented
Docs Build status updates of commit _[5d52d2e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d52d2e7eb6958c79968d6a7c48face3b8c54ebf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) | [Details](#user-content-9cb483daad1ecdde39bd789ce8ce967a-6504993d)
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealthissuepost.md) | :white_check_mark:Succeeded | [View](htt [...]

2021-07-12 21:03 UTC, opbld32 commented
Docs Build status updates of commit _[7df22ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7df22edaaba2c9f95498504eb6e4cea43df36949)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) | [Details](#user-content-9cb483daad1ecdde39bd789ce8ce967a-4c0d85a1)
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealthissuepost.md) | :white_check_mark:Succeeded | [View](htt [...]

2021-07-13 18:37 UTC, opbld31 commented
Docs Build status updates of commit _[488cc89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/488cc89ad78ec7e5b8a086592710bfd6d1f207cc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) | [Details](#user-content-789344de8d68b5fb9e3935d038db437b-fd7d214e)
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) | [Details](#user-content-9cb483daad1ecdde39bd789ce8ce967a-fd7d214e)
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) | [Details](#user-content-28b7198c861b1430e7a2f8ea5e025f79-fd7d214e)
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealthissue.md](https://github.com/microsoftgraph/ [...]

2021-07-13 19:11 UTC, opbld34 commented
Docs Build status updates of commit _[98ce85e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/98ce85eae3b51e3812ec709f7aff8992268c18bc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) | [Details](#user-content-9cb483daad1ecdde39bd789ce8ce967a-ed363985)
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) | [Details](#user-content-789344de8d68b5fb9e3935d038db437b-ed363985)
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) | [Details](#user-content-28b7198c861b1430e7a2f8ea5e025f79-ed363985)
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealthissue.md](https://github.com/microsoftgraph/ [...]

2021-07-13 21:26 UTC, opbld31 commented
Docs Build status updates of commit _[8689cca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8689ccae6c60863826a904a9ae821fc6244f7589)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) | [Details](#user-content-9cb483daad1ecdde39bd789ce8ce967a-08f0760b)
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealthissue.md)  [...]

2021-07-15 15:32 UTC, opbld31 commented
Docs Build status updates of commit _[1ee8c7a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ee8c7ac2b0c7a9f6e805945f4bc0380347ec13f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) | [Details](#user-content-9cb483daad1ecdde39bd789ce8ce967a-28ab9d7a)
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealthissue.md)  [...]

2021-07-15 15:53 UTC, isvargasmsft commented on api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md
> +GET https://graph.microsoft.com/beta/admin/serviceAnnouncement/healthOverviews
Please change this line to v1.

2021-07-15 16:13 UTC, isvargasmsft commented on api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md
> +  "@odata.context": "https://graph.microsoft.com/beta/$metadata#admin/serviceAnnouncement/healthOverviews",
Line 80: Please update to v1 as well.

2021-07-15 20:12 UTC, isvargasmsft commented on concepts/toc.yml
> +      - name: Service health and communications
Please remove the preview tag from the beta TOC as well. APIs that are only available in the beta endpoint and not the GA (v1.0 currently) endpoint are in "preview" status. Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/138210/Mark-beta-API-as-preview

2021-07-15 20:13 UTC, isvargasmsft requested changes
Thank you very much Pan! Just a few comments. 

Please feel free to ping me on the side if you have any questions. 

Kind regards,

Isaac

2021-07-16 04:46 UTC, payiAzure commented on api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md
> +GET https://graph.microsoft.com/beta/admin/serviceAnnouncement/healthOverviews
done

2021-07-16 04:47 UTC, payiAzure commented on api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md
> +  "@odata.context": "https://graph.microsoft.com/beta/$metadata#admin/serviceAnnouncement/healthOverviews",
done

2021-07-16 04:49 UTC, payiAzure commented on concepts/toc.yml
> +      - name: Service health and communications
done.

2021-07-16 04:53 UTC, opbld33 commented
Docs Build status updates of commit _[7ba4b3f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ba4b3fdfc469b2f0c1569aaa861e8abccc8aab1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) | [Details](#user-content-9cb483daad1ecdde39bd789ce8ce967a-f612955b)
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealth.md) | :white_check_mark:Succeed [...]

2021-07-16 21:18 UTC, opbld31 commented
Docs Build status updates of commit _[80601f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80601f394a5d4b07104382c9da71617522283c06)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) | [Details](#user-content-9cb483daad1ecdde39bd789ce8ce967a-6f46ba10)
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealth.md) | :white_check_mark:Succeed [...]

2021-07-20 20:21 UTC, opbld33 commented
Docs Build status updates of commit _[9073938](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9073938323046d32f2ce759bdfebcc7013a20bf5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en- [...]

2021-07-20 20:24 UTC, opbld32 commented
Docs Build status updates of commit _[9797d85](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9797d8583c70ed2fd837cf7578e9c45e62d3783a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en- [...]

2021-07-20 20:34 UTC, isvargasmsft approved these changes
Thank you very much!

2021-07-21 02:41 UTC, Lauragra commented
@payiAzure , when are the APIs getting deployed to v1.0? I don't see them live in v1.0 currently. Thanks.

2021-07-21 02:48 UTC, opbld33 commented
Docs Build status updates of commit _[f9011ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9011ef4e0f26d8166d9e672acddb35264770329)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en- [...]

2021-07-21 02:48 UTC, Lauragra commented on api-reference/beta/resources/service-communications-api-overview.md
> +## Availability in national clouds
Please also update the national cloud deployments topic to indicate that these APIs are available in the cloud envirornments. Specifically, you'll want to list this API in the supported features table in addition to calling it out here so that there's a single location with all the information.

2021-07-21 12:58 UTC, opbld32 commented
Docs Build status updates of commit _[03c2eb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03c2eb605e48ae939bef268fa98c0b0ece54d4d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en- [...]

2021-07-21 21:20 UTC, payiAzure commented
> @payiAzure , when are the APIs getting deployed to v1.0? I don't see them live in v1.0 currently. Thanks.

The API will be on v1.0 by end of next week July 30.

2021-07-21 21:59 UTC, opbld33 commented
Docs Build status updates of commit _[1b00da1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b00da1434f612c8429b95237ead3bc85ced3ee7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/deployments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-13463) | [Details](#user-content-76fa3fc5f60b0863ba97a55220eb943c-fbd90780)
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=gr [...]

2021-07-30 20:37 UTC, payiAzure commented
The API is published to Graph v1.0 today. so mark this doc PR as "Ready To Merge" as planned.

2021-08-02 21:52 UTC, payiAzure commented on api-reference/beta/resources/service-communications-api-overview.md
> +## Availability in national clouds
updated

2021-08-03 02:10 UTC, opbld33 commented
Docs Build status updates of commit _[597de91](https://github.com/microsoftgraph/microsoft-graph-docs/commits/597de912bddebc88f84133ff5a279c4d53898e3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/deployments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-13463) | [Details](#user-content-76fa3fc5f60b0863ba97a55220eb943c-1f910584)
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=gr [...]

2021-08-03 02:12 UTC, opbld30 commented
Docs Build status updates of commit _[9ad7ab5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ad7ab5f118858b7f0c4501cb880948e890593d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/deployments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-13463) | [Details](#user-content-76fa3fc5f60b0863ba97a55220eb943c-93f2056d)
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=gr [...]

2021-08-03 02:15 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/servicehealth.md
> +|status|serviceHealthStatus|Show the overral service health status. Possible values are: `serviceOperational`, `investigating`, `restoringService`, `verifyingService`, `serviceRestored`, `postInciden
Line 25:
To improve the fit and finish now that your API is GA-ing, and applicable to both v1 and beta: it would be helpful if you can indicate if there's a definitive list of these string values for the service property. Or if there is none, then must the customer first do a list healthOverviews before doing a GET.

2021-08-03 02:18 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/serviceupdatemessage.md
> +Represents announcements such as major updates, new features in a product; for example, the publication of a new Windows feature.
After line 16 as a separate paragraph:
To improve the fit and finish now that your API is GA-ing, and applicable to both v1 and beta: it would be helpful if you can clarify, of the few methods that update the "status" of a serviceUpdateMessage, where or how can a developer customer see or get the result of running any of these methods?
For example, there doesn't seem to be any property for a serviceUpdateMessage that indicates it has been marked “read”, or “archived”, or “favorite”.

2021-08-03 02:22 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/serviceupdatemessage.md
> +|tags|Collection(string)|A collection of tags for the service message.|
Line 45:
To improve the fit and finish now that your API is GA-ing, and applicable to both v1 and beta: it would be helpful if you can clarify the context, where they come from, etc. For example, is this typically entered by an admin and dependent on the workflow of the tenant?

2021-08-03 02:28 UTC, angelgolfer-ms requested changes
Hi @payiAzure , I sent you an email just now for more context for my feedback. Please take a look. 

My comments _in the PR_ represent only a subset and are to improve the fit and finish, now that your API and docs will get more attention in v1. There are 2 other issues in my email, which I think are more beneficial to customers if you can incorporate them before publishing.

If on the other hand there is any blog post announcement or specific customer waiting on the v1 docs and that we must publish today, ping me on Teams to let me know. Thanks!

2021-08-03 09:20 UTC, opbld30 commented
Docs Build status updates of commit _[ba50851](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba508510173911ede05af0acac5d7957f299458b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/deployments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-13463) | [Details](#user-content-76fa3fc5f60b0863ba97a55220eb943c-c2c24eba)
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/serviceupdatemessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us- [...]

2021-08-03 09:28 UTC, opbld33 commented
Docs Build status updates of commit _[101bc89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/101bc8925561c75b0bbae54dfa79325a5220f7d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/serviceupdatemessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reso [...]

2021-08-03 09:39 UTC, opbld32 commented
Docs Build status updates of commit _[b778f36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b778f36273433feb98ea2b2de609bdf611f18b59)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/serviceupdatemessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reso [...]

2021-08-03 10:09 UTC, opbld34 commented
Docs Build status updates of commit _[6b13948](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b1394874511ab4eddf8efd11838220d56237d16)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/resources/serviceupdatemessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-13463) (graph-rest-beta) |
[api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-13463) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocsPromoteToV1/api-reference/v1.0/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reso [...]

2021-08-03 10:15 UTC, merged

2021-08-03 10:17 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/serviceupdatemessage.md
> +Represents announcements such as major updates, new features in a product; for example, the publication of a new Windows feature.
Per our email exchange, please @payiAzure , please follow up in your next PR to address this comment. Thanks.

2021-08-03 10:18 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/serviceupdatemessage.md
> +Represents announcements such as major updates, new features in a product; for example, the publication of a new Windows feature.
For our info, I have addressed this comment for both v1 and beta.

2021-08-03 10:18 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/serviceupdatemessage.md
> +|tags|Collection(string)|A collection of tags for the service message.|
Per our email exchange, please @payiAzure , please follow up in your next PR to address this comment. Thanks.

2021-08-03 10:19 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/servicehealth.md
> +|status|serviceHealthStatus|Show the overral service health status. Possible values are: `serviceOperational`, `investigating`, `restoringService`, `verifyingService`, `serviceRestored`, `postInciden
For our info, I addressed this comment in this PR.