Added new properties in education profile status API
microsoftgraph/microsoft-graph-docs pull request #13490
Opened 2021-07-13 22:08 UTC by sergey-vun

Added:
- lastActivityDateTime
- errorCount
- statusMessage

Also added 2 new status enum values: `extracting` and `validating`. New enum values will not be returned to existing users, unless explicitly opt in.

New properties and enum values allow better tracking of the synchronization process.

2021-07-13 22:10 UTC, opbld31 commented
Docs Build status updates of commit _[32ecd8d](https://github.com/sergey-vun/microsoft-graph-docs/commits/32ecd8d9c2e7a6f0bd31f22e87f8fd96afa72bfd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107132208201321-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A37%3A23Z&ske=2021-07-20T08%3A42%3A23Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T22%3A05%3A08Z&se=2021-08-13T22%3A10%3A08Z&sr=b&sp=r&sig=iwWLRBW9WmA4vSwV9bBuhhcwdOri3LbmkZyuEzOXoE8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 15:16 UTC, mlafleur approved these changes

2021-07-14 15:20 UTC, mlafleur commented on api-reference/beta/resources/educationsynchronizationprofilestatus.md
> +"Extracting" and Validating statuses are only returned for opt-in clients. See more about: [evolvable enums](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/best-practices-c
This should explain what an "opt-in client" is and how a developer can opt-in to receiving these statuses. If `extracting` and `validating` statuses are only available to 1st party partners then they shouldn't be included in the public documentation.

2021-07-14 16:21 UTC, opbld32 commented
Docs Build status updates of commit _[27f166e](https://github.com/sergey-vun/microsoft-graph-docs/commits/27f166ef62b21cae49d12f7d83f4077676a568cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107141619334964-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A32%3A20Z&ske=2021-07-20T08%3A37%3A20Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T16%3A16%3A03Z&se=2021-08-14T16%3A21%3A03Z&sr=b&sp=r&sig=ZBU1sF235pgQZmNb8FyXAyHTkyC60zR5FE3kd5m0mjI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 16:21 UTC, sergey-vun commented on api-reference/beta/resources/educationsynchronizationprofilestatus.md
> +"Extracting" and Validating statuses are only returned for opt-in clients. See more about: [evolvable enums](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/best-practices-c
Updated, let me know if further clarification needed. Both `extracting` and `validating` will be available for 3rd party partners.

2021-07-14 17:03 UTC, isvargasmsft commented on changelog/Microsoft.EducationDataSync.json
> +          "Target": "educationsynchronizationprofilestatus"
Could you please create an entry for each property? 
Example here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-examples

2021-07-14 17:04 UTC, isvargasmsft commented on changelog/Microsoft.EducationDataSync.json
> +          "Target": "educationsynchronizationprofilestatus"
Please apply to the enums as well.

2021-07-14 17:07 UTC, isvargasmsft commented on api-reference/beta/resources/educationsynchronizationprofilestatus.md
> +"Extracting" and "Validating" statuses are only returned for applications prepared to handle new enum members. Opt-in is done by setting HTTP prefer request header: `Prefer: include-unknown-enum-memb
Please link this properly, do not expose the github http but the actual document from the concepts docset: /graph/concepts/best-practices-concept.md

2021-07-14 17:20 UTC, opbld34 commented
Docs Build status updates of commit _[a32bdfb](https://github.com/sergey-vun/microsoft-graph-docs/commits/a32bdfb03552173375ae28a48b8d5c389bbf1ba5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) | [Details](#user-content-b1a3d7012d6023aa420f311cf720e1b8-d736bce0)
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

<a id="b1a3d7012d6023aa420f311cf720e1b8-d736bce0"></a>
### [api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md)
 - **Line 37, Column 222**: **[Warning-link-out-of-scope]** `````File '../concepts/best-practices-concept.md' referenced by link '../../../concepts/best-practices-concept.md#evolvable-enums' will not be built because it is not included in build scope.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107141718385165-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A23%3A24Z&ske=2021-07-20T08%3A28%3A24Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T17%3A15%3A47Z&se=2021-08-14T17%3A20%3A47Z&sr=b&sp=r&sig=PbR7SdJCTt5Wb55JzB5QdYhvyynpCHsTnpT36gWfLQA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 17:24 UTC, isvargasmsft requested changes
Thank you very much for your work in this PR. I have a few questions:
1. Could you please add the new enums in the enums.md file? Details: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations
2. Is there a reason to update the entire changelog file instead of just adding the new ChangeList at the top? 

Please feel free to ping me on the side if you have any questions. 

Kind regards, 

Isaac Vargas
isvargas

2021-07-14 17:27 UTC, opbld31 commented
Docs Build status updates of commit _[085f652](https://github.com/sergey-vun/microsoft-graph-docs/commits/085f652949c4cd01b06a2ea33611847bb36f2891)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) | [Details](#user-content-b1a3d7012d6023aa420f311cf720e1b8-80ebdac7)
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

<a id="b1a3d7012d6023aa420f311cf720e1b8-80ebdac7"></a>
### [api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md)
 - **Line 37, Column 222**: **[Warning-link-out-of-scope]** `````File '../concepts/best-practices-concept.md' referenced by link '../../../concepts/best-practices-concept.md#evolvable-enums' will not be built because it is not included in build scope.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107141725272911-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-14T00%3A21%3A32Z&ske=2021-07-21T00%3A26%3A32Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T17%3A22%3A19Z&se=2021-08-14T17%3A27%3A19Z&sr=b&sp=r&sig=noDLRyek4EaUxprbM9%2FR6FUo%2Bycb6A89Ex4BsuZWcRo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 23:18 UTC, opbld32 commented
Docs Build status updates of commit _[1cee319](https://github.com/sergey-vun/microsoft-graph-docs/commits/1cee319fc0e2babdbd0c6a542608e0b1350c6b29)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) | [Details](#user-content-b1a3d7012d6023aa420f311cf720e1b8-edf6d02c)
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

<a id="b1a3d7012d6023aa420f311cf720e1b8-edf6d02c"></a>
### [api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md)
 - **Line 37, Column 222**: **[Warning-link-out-of-scope]** `````File '../concepts/best-practices-concept.md' referenced by link '../../../concepts/best-practices-concept.md#evolvable-enums' will not be built because it is not included in build scope.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107142317077365-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A15%3A48Z&ske=2021-07-20T08%3A20%3A48Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T23%3A13%3A36Z&se=2021-08-14T23%3A18%3A36Z&sr=b&sp=r&sig=ItW%2BbsuhFl92p0I%2B96YcKyCHOxELHL%2B2SBb8Pe7Wuuw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 16:34 UTC, opbld33 commented
Docs Build status updates of commit _[3fdbc4e](https://github.com/sergey-vun/microsoft-graph-docs/commits/3fdbc4e629a24ff91b879d887e600f16379f6fe2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) | [Details](#user-content-b1a3d7012d6023aa420f311cf720e1b8-597d69be)
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |

<a id="b1a3d7012d6023aa420f311cf720e1b8-597d69be"></a>
### [api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md)
 - **Line 37, Column 222**: **[Warning-link-out-of-scope]** `````File '../concepts/best-practices-concept.md' referenced by link '../../../concepts/best-practices-concept.md#evolvable-enums' will not be built because it is not included in build scope.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161632110332-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A09%3A48Z&ske=2021-07-23T08%3A14%3A48Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T16%3A29%3A38Z&se=2021-08-16T16%3A34%3A38Z&sr=b&sp=r&sig=yXlhiW7mEafrsvuqrk30OmbAukA3SfZDdUUhUq5gJ6I%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 16:38 UTC, sergey-vun commented
#feedback-addressed

2021-07-16 16:39 UTC, opbld34 commented
Docs Build status updates of commit _[ae81db2](https://github.com/sergey-vun/microsoft-graph-docs/commits/ae81db2ae16c1d2974a7c04d41c8c3ab6d23343d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) | [Details](#user-content-b1a3d7012d6023aa420f311cf720e1b8-6c4d0508)
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

<a id="b1a3d7012d6023aa420f311cf720e1b8-6c4d0508"></a>
### [api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md)
 - **Line 37, Column 222**: **[Warning-link-out-of-scope]** `````File '../concepts/best-practices-concept.md' referenced by link '../../../concepts/best-practices-concept.md#evolvable-enums' will not be built because it is not included in build scope.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161637367339-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A19%3A43Z&ske=2021-07-23T08%3A24%3A43Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T16%3A34%3A13Z&se=2021-08-16T16%3A39%3A13Z&sr=b&sp=r&sig=2l5h0v5npI8jQvryk18LedEv2jpSis4XWQSX1Lkj7cY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 17:31 UTC, opbld32 commented
Docs Build status updates of commit _[12bbde2](https://github.com/sergey-vun/microsoft-graph-docs/commits/12bbde2127d048239bf6e7610c8a9892ad8ae55d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) | [Details](#user-content-b1a3d7012d6023aa420f311cf720e1b8-7e5e2477)
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

<a id="b1a3d7012d6023aa420f311cf720e1b8-7e5e2477"></a>
### [api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md)
 - **Line 37, Column 222**: **[Warning-link-out-of-scope]** `````File '../concepts/best-practices-concept.md' referenced by link '../../../concepts/best-practices-concept.md#evolvable-enums' will not be built because it is not included in build scope.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161730086136-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A48%3A20Z&ske=2021-07-23T08%3A53%3A20Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T17%3A26%3A39Z&se=2021-08-16T17%3A31%3A39Z&sr=b&sp=r&sig=0wWLI%2FZuHOH2TXEdUADsSj%2F22Bxnb6EYBtv8EzlGwc0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 17:33 UTC, opbld34 commented
Docs Build status updates of commit _[c9d6d81](https://github.com/sergey-vun/microsoft-graph-docs/commits/c9d6d8102b458960582c4e8cb265287a3525de21)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) | [Details](#user-content-b1a3d7012d6023aa420f311cf720e1b8-d7c46973)
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

<a id="b1a3d7012d6023aa420f311cf720e1b8-d7c46973"></a>
### [api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md)
 - **Line 37, Column 222**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/concepts/best-practices-concept.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161732089681-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A06%3A29Z&ske=2021-07-23T08%3A11%3A29Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T17%3A28%3A37Z&se=2021-08-16T17%3A33%3A37Z&sr=b&sp=r&sig=Vy5UiKDblYwUUbcTgo5UjjWz7zkk4CPbSV7bbvCoMa8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 17:51 UTC, opbld32 commented
Docs Build status updates of commit _[7ec18a8](https://github.com/sergey-vun/microsoft-graph-docs/commits/7ec18a88adfa83f95fdb775ba8cf39c9ae8ef446)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161748328951-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A08%3A34Z&ske=2021-07-23T08%3A13%3A34Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T17%3A46%3A05Z&se=2021-08-16T17%3A51%3A05Z&sr=b&sp=r&sig=qJ3hMWLFGZLNTlkYWKVO57p3VYXvuOrs%2FWHV1p8VTzQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 18:03 UTC, opbld33 commented
Docs Build status updates of commit _[b8c850a](https://github.com/sergey-vun/microsoft-graph-docs/commits/b8c850a79325d2464f03e29386195508ee669ed8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161802130274-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A12%3A47Z&ske=2021-07-23T08%3A17%3A47Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T17%3A58%3A49Z&se=2021-08-16T18%3A03%3A49Z&sr=b&sp=r&sig=RRLZGOLFUSiT6sgAYOPpFlhsuC1nkxQJ2gwmBlSLp6c%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 18:10 UTC, opbld31 commented
Docs Build status updates of commit _[37ad20c](https://github.com/sergey-vun/microsoft-graph-docs/commits/37ad20ce2c83e549065efe04a3851d31287d3ef4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161808246725-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T09%3A18%3A34Z&ske=2021-07-23T09%3A23%3A34Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T18%3A05%3A05Z&se=2021-08-16T18%3A10%3A05Z&sr=b&sp=r&sig=Oqxgl3rn3kGoQ2i4jUs%2FKstRuFZH%2BmNKnYte4vQNNoo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 18:32 UTC, opbld34 commented
Docs Build status updates of commit _[eb792ca](https://github.com/sergey-vun/microsoft-graph-docs/commits/eb792caed049c3b8b616b7023324106d8548159b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161829475624-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A09%3A48Z&ske=2021-07-23T08%3A14%3A48Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T18%3A27%3A05Z&se=2021-08-16T18%3A32%3A05Z&sr=b&sp=r&sig=t4u0arQYF9fWREXPH1sZKPYk1q7aUgMTxSGJ%2FvPgrrY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 19:52 UTC, isvargasmsft commented on changelog/Microsoft.EducationDataSync.json
> +          "ChangedApiName": "educationsynchronizationprofilestatus",
ChangedApiName would be the property being added, errorCount in this case.

2021-07-16 19:52 UTC, isvargasmsft commented on changelog/Microsoft.EducationDataSync.json
> +          "ChangedApiName": "educationsynchronizationprofilestatus",
Please apply to other entries as well.

2021-07-16 19:55 UTC, isvargasmsft commented on changelog/Microsoft.EducationDataSync.json
> +          "ChangedApiName": "educationsynchronizationprofilestatus",
According to the enums.md file, you are adding new members to the educationSynchronizationStatus enum type. Please follow the example number 5 here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-examples

2021-07-16 19:56 UTC, isvargasmsft commented on changelog/Microsoft.EducationDataSync.json
> +          "ChangedApiName": "educationsynchronizationprofilestatus",
Please apply to the other members as well.

2021-07-16 20:03 UTC, opbld33 commented
Docs Build status updates of commit _[ce01732](https://github.com/sergey-vun/microsoft-graph-docs/commits/ce017324f15867c0cfe26d01572aeaa65339405b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107162000517309-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A21%3A32Z&ske=2021-07-23T08%3A26%3A32Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T19%3A58%3A26Z&se=2021-08-16T20%3A03%3A26Z&sr=b&sp=r&sig=WsLTZKbZY3YH7siryTfK2qdoCjuwjO0nRZiIjU0dLC0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 20:09 UTC, isvargasmsft commented on changelog/Microsoft.EducationDataSync.json
> +          "Description": "Added new enum value 'Extracting' to the educationSynchronizationStatus enumeration to provide better feedback on profile synchronization progress.",
Just format observations:
1. Please use lower case in the member names. 
2. Please use tick marks ` instead of single quotes '. Tick marks are found at the top left corner of the keyboard, below the Esc key. 
3. Please enclose the enum name with *: *educationSynchronizationStatus*.

2021-07-16 21:06 UTC, opbld31 commented
Docs Build status updates of commit _[a66d998](https://github.com/sergey-vun/microsoft-graph-docs/commits/a66d998c91a46fb673a49d9709ea2277ac2057a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107162104429182-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A26%3A28Z&ske=2021-07-23T08%3A31%3A28Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T21%3A01%3A30Z&se=2021-08-16T21%3A06%3A30Z&sr=b&sp=r&sig=awpFp5jnJF8bxZyCrk8X2%2FoJ6OFoJbME1GWEttUiDTk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 21:10 UTC, isvargasmsft approved these changes
Thank you very much!

2021-07-17 01:52 UTC, Lauragra approved these changes

2021-07-19 14:11 UTC, opbld32 commented
Docs Build status updates of commit _[ca5d7ea](https://github.com/sergey-vun/microsoft-graph-docs/commits/ca5d7ea2006dfc44f60d6f8d4f43face0b7eb9f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107191408254875-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T04%3A19%3A31Z&ske=2021-07-26T04%3A24%3A31Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-19T14%3A06%3A09Z&se=2021-08-19T14%3A11%3A09Z&sr=b&sp=r&sig=XxcMzMhjXh3lqPCqq14wW9FWiUJaYM%2Bb37tvdcMAipc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-20 00:41 UTC, opbld30 commented
Docs Build status updates of commit _[0c60c3c](https://github.com/sergey-vun/microsoft-graph-docs/commits/0c60c3cff7f681b9495e1415df30108b7fe71ad5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsynchronizationprofilestatus-get.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsynchronizationprofilestatus-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsynchronizationprofilestatus-get?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/educationsynchronizationprofilestatus.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationsynchronizationprofilestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsynchronizationprofilestatus?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13490) (graph-rest-beta) |
[changelog/Microsoft.EducationDataSync.json](https://github.com/sergey-vun/microsoft-graph-docs/blob/main/changelog/Microsoft.EducationDataSync.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107200040134653-13490%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A29%3A53Z&ske=2021-07-26T02%3A34%3A53Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-20T00%3A36%3A37Z&se=2021-08-20T00%3A41%3A37Z&sr=b&sp=r&sig=nxzCoH%2BKRk9d3YB9zoKEtVIlpH%2F%2FwdEcOWDbdUefvTk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-20 00:46 UTC, merged