Teams Graph Export Api release for getallmessages (channel/chat)
microsoftgraph/microsoft-graph-docs pull request #13524
Opened 2021-07-15 18:23 UTC by mjaganm

This is documentation update for GA of Team Graph Export Apis for getAllMessages for Channel and Chat.

2021-07-15 18:24 UTC, opbld34 commented
Docs Build status updates of commit _[deb615f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/deb615ff5d4e8ac4b6875569a5035f6db876c92b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :x:Error | | [Details](#user-content-120ddf6b0206b3151769ad0d589ef494-69c0a519)

<a id="120ddf6b0206b3151769ad0d589ef494-69c0a519"></a>
### [api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md)
 - **Line 67, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-allchannelmessages-1-csharp-snippets.md'.`````
 - **Line 71, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-allchannelmessages-1-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-allchannelmessages-1-objc-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/get-allchannelmessages-1-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107151823426161-13524%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A32%3A34Z&ske=2021-07-20T08%3A37%3A34Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T18%3A19%3A57Z&se=2021-08-15T18%3A24%3A57Z&sr=b&sp=r&sig=HWNTdFWN7phWxHYH9AEi0JEg%2BqkJIWxRWfoXHdyptik%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 20:13 UTC, opbld31 commented
Docs Build status updates of commit _[0520919](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0520919c20419a4b1e9e479d2982501811addfed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107152012150773-13524%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A19%3A00Z&ske=2021-07-20T08%3A24%3A00Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T20%3A08%3A42Z&se=2021-08-15T20%3A13%3A42Z&sr=b&sp=r&sig=AGKC%2BldJ2o6qmxsgSskU35sv7RRhHnxg5xZap%2FoFmmE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 20:21 UTC, RamjotSingh requested changes

2021-07-15 20:21 UTC, RamjotSingh commented on api-reference/beta/toc.yml
> +        - name: Get messages across all chats
This is present under this node already i meant to add the channel get all messages under chatMessage node too chats is there already.

2021-07-15 20:21 UTC, RamjotSingh commented on api-reference/v1.0/toc.yml
> +        - name: Get messages across all channels
Add both getallmessages (chat and channel) under chatMessage node as well

2021-07-16 17:52 UTC, opbld32 commented
Docs Build status updates of commit _[a9812f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a9812f5260247d676cb94394f335383dc0998dbe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161749420811-13524%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A16%3A07Z&ske=2021-07-23T08%3A21%3A07Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T17%3A47%3A21Z&se=2021-08-16T17%3A52%3A21Z&sr=b&sp=r&sig=N9nW1%2FxEycdFwtVlEOMFzAMA8bf%2FgyRbXz424e%2FV4Pw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 18:51 UTC, RamjotSingh requested changes

2021-07-16 18:51 UTC, RamjotSingh commented on api-reference/v1.0/api/chats-getallmessages.md
> +Get all messages from all [chats](../resources/chatmessage.md) that a user is a participant in, including one-on-one chats, group chats, and meeting chats.
```suggestion
Get all messages from all [chats](../resources/chatmessage.md) that a user is a participant in, including one-on-one chats, group chats, and meeting chats.
```

```suggestion
Get all messages(../resources/chatmessage.md) from all [chats](../resources/chat.md) that a user is a participant in, including one-on-one chats, group chats, and meeting chats.
```

2021-07-16 18:51 UTC, RamjotSingh commented on api-reference/v1.0/api/chats-getallmessages.md
> +<!-- {
```
<!-- {
  "blockType": "response",
  "truncated": true,
  "@odata.type": "microsoft.graph.chatMessage",
  "isCollection": true,
} -->
```

2021-07-16 19:01 UTC, opbld33 commented
Docs Build status updates of commit _[2828694](https://github.com/microsoftgraph/microsoft-graph-docs/commits/282869466b64f6bf484b03c2f9cce9b0c06938a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161858434032-13524%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A15%3A08Z&ske=2021-07-23T08%3A20%3A08Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T18%3A56%3A12Z&se=2021-08-16T19%3A01%3A12Z&sr=b&sp=r&sig=CFKsQUAvEe%2Ftr8YukKGUoSO5Zp347BhPiwIUDtZlrZM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 19:03 UTC, opbld30 commented
Docs Build status updates of commit _[8eefe16](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8eefe1619a23ca7e4a2fb57bb514cec44169d047)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161902152789-13524%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A08%3A34Z&ske=2021-07-23T08%3A13%3A34Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T18%3A58%3A45Z&se=2021-08-16T19%3A03%3A45Z&sr=b&sp=r&sig=Gz5IxoqgweXylVGV5zfvz0qJDEAroDEL0XBC%2F5LAWnQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 19:08 UTC, RamjotSingh approved these changes

2021-07-29 07:14 UTC, lramosvea commented
@mjaganm is this ready for review? If so, please remove the "do not merge" label and add the "content review" label to start a review. Once completed, label the reviewed PR with the "ready to merge" label when you are ready for the docs team to merge your pull request.

2021-09-27 19:22 UTC, opbld30 commented
Docs Build status updates of commit _[c21035f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c21035f0ebe214c44a525aa61d00017f1d2aa0ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109271920176793-13524%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-28T19%3A22%3A06Z&sr=b&sp=r&sig=3q%2FnDcNKoJjn%2B%2FPjZ0OJssrHLQo2xcxSMx85cIVcBSw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-27 20:12 UTC, opbld33 commented
Docs Build status updates of commit _[8c3f953](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c3f95331a30ee2cf3cb128e36fc225d74f77f52)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109272010027937-13524%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-28T20%3A12%3A15Z&sr=b&sp=r&sig=Z%2B0AYV7nSifab1rt00%2BXN8NcoVcXvVMXoP%2BPOUItkUA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-27 21:11 UTC, JarbasHorst requested changes

2021-09-27 21:11 UTC, JarbasHorst commented on api-reference/v1.0/api/channel-getallmessages.md
> +# [HTTP](#tab/http)
All tabs get added via the weekly SDK snippet automation that runs on the main branch. In this case, you need to remove the HTTP H1 (line 58). So, we don't have just the one tab.

2021-09-27 21:11 UTC, JarbasHorst commented on api-reference/v1.0/api/channel-getallmessages.md
> +  "isCollection": true,
For conformity, please remove the ending comma.

2021-09-27 21:11 UTC, JarbasHorst commented on api-reference/v1.0/api/chats-getallmessages.md
> +Get all messages(../resources/chatmessage.md) from all [chats](../resources/chat.md) that a user is a participant in, including one-on-one chats, group chats, and meeting chats.
A word ending in –ing can be a verb, a noun, or an adjective. Please, avoid using gerunds where possible; in this case, you can change "including" to "that includes".

2021-09-27 21:11 UTC, JarbasHorst commented on api-reference/v1.0/api/chats-getallmessages.md
> +|Delegated (work or school account)| Not supported |
Please, add a period at the end of the sentence.

2021-09-27 21:11 UTC, JarbasHorst commented on api-reference/v1.0/api/chats-getallmessages.md
> +|Delegated (personal Microsoft account) | Not supported |
Please, add a period at the end of the sentence.

2021-09-27 21:11 UTC, JarbasHorst commented on api-reference/v1.0/api/channel-getallmessages.md
> +|Delegated (work or school account) | Not supported |
Please, add a period at the end of the sentence.

2021-09-27 21:11 UTC, JarbasHorst commented on api-reference/v1.0/api/channel-getallmessages.md
> +|Delegated (personal Microsoft account) | Not supported |
Please, add a period at the end of the sentence.

2021-09-27 21:11 UTC, JarbasHorst commented on api-reference/v1.0/api/chats-getallmessages.md
> +> Before calling this API with application permissions, you must request access. For details, see [Protected APIs in Microsoft Teams](/graph/teams-protected-apis).
Please, avoid using gerunds where possible; in this case, you can change "calling" to "you call".

2021-09-27 21:11 UTC, JarbasHorst commented on api-reference/v1.0/api/chats-getallmessages.md
> +  "isCollection": true,
For conformity, please remove the ending comma.

2021-09-27 21:14 UTC, JarbasHorst commented
@mjaganm your PR introduces two new API topics. Please, use the changelog to mention these additions to the corresponding resource topics.

2021-09-28 00:02 UTC, opbld30 commented
Docs Build status updates of commit _[313cc97](https://github.com/microsoftgraph/microsoft-graph-docs/commits/313cc9769f79e2c08b754247165042a98d3ffefc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) | [Details](#user-content-120ddf6b0206b3151769ad0d589ef494-9389f4ed)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |

<a id="120ddf6b0206b3151769ad0d589ef494-9389f4ed"></a>
### [api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md)
 - **Line 58, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 '[HTTP]') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109272359522918-13524%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-29T00%3A02%3A12Z&sr=b&sp=r&sig=e3Uy9clp3eR9Yz5zgQzDpqndjaD6FzOFs81ZH0XCfFc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-28 19:33 UTC, JarbasHorst requested changes

2021-09-28 19:33 UTC, JarbasHorst commented on api-reference/beta/toc.yml
> +        - name: Get messages across all channels
Please, update the following resource topic to include a reference to the channel-getallmessages API topic:
- [BETA] [chatmessage resource topic](https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta) under Methods/Chat messages

2021-09-28 19:33 UTC, JarbasHorst commented on api-reference/v1.0/toc.yml
> +        - name: Get messages across all channels
Please, update the following resource topic to include a reference to the channel-getallmessages API topic:
- [v1.0] [chatmessage resource topic](https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0) under Methods/Chat messages

2021-09-28 19:33 UTC, JarbasHorst commented on api-reference/v1.0/api/channel-getallmessages.md
> +# [HTTP]
You can only have one top-level heading. In this case, you should remove this HTTP heading. All tabs, including HTTP, get added via the weekly SDK snippet automation that runs on the main branch.

2021-09-28 19:37 UTC, JarbasHorst commented
@mjaganm **your PR introduces two new API topics. Please, use the changelog to mention these additions to the corresponding resource topics (chat and channel).**

2021-09-28 21:39 UTC, opbld31 commented
Docs Build status updates of commit _[a65faaa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a65faaa4a706c32173a624cb69328cee75dc4f12)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :x:Error | | [Details](#user-content-120ddf6b0206b3151769ad0d589ef494-abfb2294)
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :x:Error | | [Details](#user-content-558da7ce89cf01845a1b273d84ca427c-abfb2294)

<a id="120ddf6b0206b3151769ad0d589ef494-abfb2294"></a>
### [api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md)
 - **Line 18, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../../includes/teams-model-A-only-disclaimer.md'.`````

<a id="558da7ce89cf01845a1b273d84ca427c-abfb2294"></a>
### [api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md)
 - **Line 16, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../../includes/teams-model-A-only-disclaimer.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109282137369903-13524%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-29T21%3A39%3A26Z&sr=b&sp=r&sig=6Tyq%2BsNcJVLGNwkD3ANYxXbB37XmL6DzQ%2BO5ZFpZclA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-29 01:39 UTC, mjaganm commented
> @mjaganm **your PR introduces two new API topics. Please, use the changelog to mention these additions.** Suggested revision:
> 
> * Added the [getAllMessages](https://docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0) method to the [chat](https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0) resource type.
> * Added the [getAllMessages](https://docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-1.0) method to the [channel](https://docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0) resource type.



> @mjaganm **your PR introduces two new API topics. Please, use the changelog to mention these additions.** Suggested revision:
> 
> * Added the [getAllMessages](https://docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0) method to the [chat](https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0) resource type.
> * Added the [getAllMessages](https://docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-1.0) method to the [channel](https://docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0) resource type.

Added changelog.

2021-09-29 01:45 UTC, opbld30 commented
Docs Build status updates of commit _[a65faaa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a65faaa4a706c32173a624cb69328cee75dc4f12)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :x:Error | | [Details](#user-content-120ddf6b0206b3151769ad0d589ef494-7e6675f3)
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :x:Error | | [Details](#user-content-558da7ce89cf01845a1b273d84ca427c-7e6675f3)

<a id="120ddf6b0206b3151769ad0d589ef494-7e6675f3"></a>
### [api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md)
 - **Line 18, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../../includes/teams-model-A-only-disclaimer.md'.`````

<a id="558da7ce89cf01845a1b273d84ca427c-7e6675f3"></a>
### [api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md)
 - **Line 16, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../../includes/teams-model-A-only-disclaimer.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109290143562897-13524%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-30T01%3A45%3A30Z&sr=b&sp=r&sig=Bbi%2BVu0KZegpitl6%2Fuzkf2aWnUqOxqeGsgBvSILgevo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-29 02:01 UTC, opbld33 commented
Docs Build status updates of commit _[4de57fc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4de57fc23b2b4ecdcc956a434e8e6f6ecac57bb4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/includes/teams-model-A-only-disclaimer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/includes/teams-model-A-only-disclaimer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109290159203975-13524%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-30T02%3A01%3A53Z&sr=b&sp=r&sig=aoqPjGDN%2F5fcfNjD5Jz5faSlWx2lSfCmSkE9sc7WMsc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-29 02:16 UTC, mjaganm commented
@JarbasHorst I had addressed your comments. I intend to release this documentation on 09/30 (Thursday). Please let me know the steps involved.

2021-09-29 20:51 UTC, JarbasHorst requested changes

2021-09-29 20:51 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [Get messages across all chats for user](https://docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&preserve-view=true) to [chats](https://doc
For consistency, please replace the friendly name "Get all channel messages" with "chatsGetAllMessages". Also, use articles to help readers and translation software identify the nouns and modifiers in a sentence. Please, replace chats with chat, and please add type after resource. Suggested revision:

- Added the [chatsGetAllMessages](https://docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&preserve-view=true) method to the [chat](https://docs.microsoft.com/graph/api/resources/chat?view=graph-rest-1.0) resource type.

2021-09-29 20:51 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [Get messages across all chats for user](https://docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&preserve-view=true) to [chats](https://doc
For consistency, please replace the friendly name "Get messages across all chats for user" with "chatsGetAllMessages". Also, use articles to help readers and translation software identify the nouns and modifiers in a sentence. Please, replace chats with chatMessage, and please add type after resource. Suggested revision:

- Added the [chatsGetAllMessages](https://docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&preserve-view=true) method to the [chatMessage](https://docs.microsoft.com/graph/api/resources/chatmessage?view=graph-rest-1.0) resource type.

2021-09-29 20:51 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +        }
@mjaganm please add a new changelog entry to mention the addition of channelsGetAllMessages method to the chatMessage resource type. Suggested description:

- Added the [channelsGetAllMessages](https://docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&preserve-view=true) method to the [chatMessage](https://docs.microsoft.com/graph/api/resources/chatmessage?view=graph-rest-1.0) resource type.

2021-09-29 20:51 UTC, JarbasHorst commented on api-reference/includes/teams-model-A-only-disclaimer.md
> +>**Note**:
I recommend you to provide this information as [!IMPORTANT]. You should mark something as important when the information is essential and required for user success. In this case, I believe the information is required for user success.

2021-09-29 21:16 UTC, JarbasHorst requested changes

2021-09-29 21:16 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Target": "chats-getallmessages"
The target property should contain the element that is the target of the update. In this case, the target is the resource topic and not the API topic. Please, replace "chats-getallmessages" with "chat".

2021-09-29 21:16 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Target": "channel-getallmessages"
The target property should contain the element that is the target of the update. In this case, the target is the resource topic and not the API topic. Please, replace "channel-getallmessages" with "channel".

2021-09-29 21:16 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +        {
I recommend you to delete this changelog entry because the getAllMessages method doesn't really get added to the chatMessage resource type. In this case, channelsGetAllMessages and chatsGetAllMessages are only linked to the chatMessage resource topic.

2021-09-30 02:39 UTC, opbld34 commented
Docs Build status updates of commit _[995f0be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/995f0be2984960176d40d5af854a36b5e5894310)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/includes/teams-model-A-only-disclaimer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/includes/teams-model-A-only-disclaimer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109300238328106-13524%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-31T02%3A39%3A55Z&sr=b&sp=r&sig=CMWjJvD3JJuregrS1w91FM1ZRWe3ULeSXW2pzDC5a9M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-30 02:59 UTC, opbld32 commented
Docs Build status updates of commit _[1bbdb14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1bbdb1481589c5e24f33c7ce59df0d16038f4e85)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/includes/teams-model-A-and-B-disclaimer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/includes/teams-model-A-and-B-disclaimer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109300258050884-13524%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-31T02%3A59%3A25Z&sr=b&sp=r&sig=Rs1NHy3aj4Ft11y3RgmKYud7MI7EwAwcXS3ujVWU4Ww%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-30 19:37 UTC, opbld30 commented
Docs Build status updates of commit _[5a9c46c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a9c46c5f14a2719f914ea7be99b534003934222)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/includes/teams-model-A-and-B-disclaimer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/includes/teams-model-A-and-B-disclaimer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109301936018353-13524%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-31T19%3A37%3A56Z&sr=b&sp=r&sig=PwLV5XYmqnK3C3OkJ%2BApUVo%2BD4HVgPVFPc3%2FcTtvsL8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-30 19:40 UTC, opbld31 commented
Docs Build status updates of commit _[4f42d5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f42d5c90b3b61903e82cbd7d273ac62968a74a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/includes/teams-model-A-and-B-disclaimer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/includes/teams-model-A-and-B-disclaimer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109301937352926-13524%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-31T19%3A40%3A08Z&sr=b&sp=r&sig=EEzhE10V4UHUsLku%2BHL%2BWDWZJoG0Ya%2BVqmbeKa59Hkw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-30 19:42 UTC, opbld31 commented
Docs Build status updates of commit _[fe4d276](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe4d2768009fa381e02b15ad0f00aa8468fb75d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/includes/teams-model-A-and-B-disclaimer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/includes/teams-model-A-and-B-disclaimer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109301939106171-13524%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-31T19%3A42%3A00Z&sr=b&sp=r&sig=Crnqm6S9ysRM0Bo10mW28tK3YPr%2B74Zb7UWbRluKNyk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-30 19:47 UTC, Lauragra approved these changes

2021-10-01 20:19 UTC, opbld31 commented
Docs Build status updates of commit _[677ea36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/677ea36cff2d2b303c6caac20820033189df6480)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13524) (graph-rest-beta) |
[api-reference/includes/teams-model-A-and-B-disclaimer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/includes/teams-model-A-and-B-disclaimer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-1.0&branch=pr-en-us-13524) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jagan/releaseexportapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110012017210786-13524%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T20%3A19%3A02Z&sr=b&sp=r&sig=bme%2FNOm%2FT9jlb4Q5oLeWnUBr2JA2o5iQfDwwbrDDq84%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 20:20 UTC, merged