delete accessPackageAssignmentRequest
microsoftgraph/microsoft-graph-docs pull request #13532
Opened 2021-07-15 23:00 UTC by markwahl-msft

in entitlement management, permit the admin to delete a denied or completed request

2021-07-15 23:02 UTC, opbld32 commented
Docs Build status updates of commit _[da978f7](https://github.com/markwahl-msft/microsoft-graph-docs/commits/da978f722d681a80ff0d6454415e465f99d22a8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-delete.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107152300462708-13532%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A25%3A02Z&ske=2021-07-20T08%3A30%3A02Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T22%3A57%3A55Z&se=2021-08-15T23%3A02%3A55Z&sr=b&sp=r&sig=EXMzHsghZgM%2BUZbI1boszb2czleQ%2FPJu4ymCQoLW0Jk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 19:14 UTC, FaithOmbongi requested changes
- Proposed minor fixes
- You'll need to update the localization metadata for all files from _localization_priority: Normal_ to **ms.localizationpriority: medium**. Otherwise, you'll hit an API Doctor validation error.

2021-09-08 19:14 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-delete.md
> +This request can be made to remove a denied or completed request.  You cannot delete an access package assignment requset if it has any **accessPackageAssignment**.
```suggestion
This request can be made to remove a denied or completed request. You cannot delete an access package assignment request if it has any **accessPackageAssignment** objects.
```
```suggestion
This request can be made to remove a denied or completed request.  You cannot delete an access package assignment requset if it has any **accessPackageAssignment**.
```

2021-09-08 19:14 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-delete.md
> +
Missing a request object here?

2021-09-08 19:14 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +         "Description": "Added the [delete](https://docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-beta) operation for an [accessPackageAssignmentRequest](ht
```suggestion
         "Description": "Added the [delete](https://docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-beta) operation to the [accessPackageAssignmentRequest](https://docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest?view=graph-rest-beta) resource.",
```
```suggestion
         "Description": "Added the [delete](https://docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-beta) operation for an [accessPackageAssignmentRequest](https://docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest?view=graph-rest-beta) resource.",
```

2021-09-08 20:19 UTC, opbld32 commented
Docs Build status updates of commit _[c1bfad5](https://github.com/markwahl-msft/microsoft-graph-docs/commits/c1bfad5c9ac1063286af5759fd74b62d29099b42)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-delete.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109082017105137-13532%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=sVRCWVwJVmoOom%2FPnOD4sAY%2BFNzvhjcXircNQhQDp28%3D&st=2021-09-08T20%3A14%3A13Z&se=2021-10-09T20%3A19%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 20:21 UTC, opbld34 commented
Docs Build status updates of commit _[621d260](https://github.com/markwahl-msft/microsoft-graph-docs/commits/621d2604e9a08b548dcf5e57f0588f88892a1a77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-delete.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109082019471987-13532%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=1OXxJNLDn0jpwPRVPgHEnvF8QP7lI%2FzOK9qkUoi%2BQW4%3D&st=2021-09-08T20%3A16%3A35Z&se=2021-10-09T20%3A21%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 20:39 UTC, opbld33 commented
Docs Build status updates of commit _[7a0f779](https://github.com/markwahl-msft/microsoft-graph-docs/commits/7a0f779625659da8bae0783e02f993eb91934b6c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-delete.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109082037170750-13532%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=p%2BX28Kvi8Hr0ENafgOluIOqCVTftPYcU9MIk94v2Llk%3D&st=2021-09-08T20%3A34%3A03Z&se=2021-10-09T20%3A39%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-13 16:53 UTC, opbld33 commented
Docs Build status updates of commit _[d0641ff](https://github.com/markwahl-msft/microsoft-graph-docs/commits/d0641ff0b97d1fd5e8a4acc082366ba631d6f767)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-delete.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109131651426694-13532%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=XgIfLCeDwTPvOuZxs0vUid%2FNDc0riVSn8Hufg6R%2BlM0%3D&st=2021-09-13T16%3A48%3A41Z&se=2021-10-14T16%3A53%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-13 16:57 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-delete.md
> +This request can be made to remove a denied or completed request.  You cannot delete an access package assignment requset if it has any **accessPackageAssignment**.
fixed typo, thanks

2021-09-13 16:57 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-delete.md
> +
added, thanks

2021-09-13 16:58 UTC, markwahl-msft commented on changelog/Microsoft.DirectoryServices.json
> +         "Description": "Added the [delete](https://docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-beta) operation for an [accessPackageAssignmentRequest](ht
updated

2021-09-13 18:09 UTC, FaithOmbongi approved these changes

2021-09-15 00:59 UTC, opbld30 commented
Docs Build status updates of commit _[450e1c7](https://github.com/markwahl-msft/microsoft-graph-docs/commits/450e1c7a5aa41dc44c9df53cb9ed3e7bce38eb26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-delete.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-beta&branch=pr-en-us-13532) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-dsd/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109150057392593-13532%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=oEa5RBZnFyGB6aD%2BDtdlaw8mbF%2FY8grSYTEfPyZrZ2E%3D&st=2021-09-15T00%3A54%3A21Z&se=2021-10-16T00%3A59%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 01:03 UTC, merged