documentation for Get MessageTrace API
microsoftgraph/microsoft-graph-docs pull request #13536
Opened 2021-07-16 02:22 UTC by rsuven

The API specification is here: https://microsoftgraph.visualstudio.com/_git/onboarding/pullrequest/4372

2021-07-16 02:23 UTC, opbld32 commented
Docs Build status updates of commit _[d9ac43c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9ac43c581252ee0b96c5a5d7d08619731a63c87)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-e453b50a)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-e453b50a)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-e453b50a)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-e453b50a)
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-e453b50a"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'admin'.`````

<a id="bd89255e97aef19c83017cbb21595863-e453b50a"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'admin'.`````

<a id="19592b74a016f386a87e1cc56c5465f1-e453b50a"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'admin'.`````

<a id="00bd20fe718fad569a224144c596cd43-e453b50a"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'admin'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107160222054810-13536%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-15T22%3A28%3A37Z&ske=2021-07-22T22%3A33%3A37Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T02%3A18%3A43Z&se=2021-08-16T02%3A23%3A43Z&sr=b&sp=r&sig=SvkgAjxdyxwgPp8COOcxSMeWe25ho%2B8U1iuMwmEPXPo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 21:58 UTC, opbld31 commented
Docs Build status updates of commit _[c160fce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c160fce00449dd82a32165f60926de85c19142a5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-48057623)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-48057623)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-48057623)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-48057623)
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-48057623"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd89255e97aef19c83017cbb21595863-48057623"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19592b74a016f386a87e1cc56c5465f1-48057623"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="00bd20fe718fad569a224144c596cd43-48057623"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107162155480159-13536%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A55%3A07Z&ske=2021-07-23T09%3A00%3A07Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T21%3A53%3A39Z&se=2021-08-16T21%3A58%3A39Z&sr=b&sp=r&sig=QfBFbRL%2Biu2HFoiu4HGCWKdx5ldVcrHMrJNxFd5eivw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-17 00:25 UTC, opbld34 commented
Docs Build status updates of commit _[e484943](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e48494313aa0f367826a50c59d747acc67d8724d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-3a4dc481)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-3a4dc481)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-3a4dc481)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-3a4dc481)
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-3a4dc481"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd89255e97aef19c83017cbb21595863-3a4dc481"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19592b74a016f386a87e1cc56c5465f1-3a4dc481"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="00bd20fe718fad569a224144c596cd43-3a4dc481"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107170024174097-13536%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A36%3A31Z&ske=2021-07-23T08%3A41%3A31Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-17T00%3A20%3A51Z&se=2021-08-17T00%3A25%3A51Z&sr=b&sp=r&sig=DHEt9eR2JBhCWsKkwppiVhSKEKg2CLPKtask8nXReJw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-17 00:52 UTC, opbld33 commented
Docs Build status updates of commit _[3f0db8b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f0db8b37b86bcb45202906778ca45db22834de1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-b6b40210)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-b6b40210)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-b6b40210)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-b6b40210)
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-b6b40210"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd89255e97aef19c83017cbb21595863-b6b40210"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19592b74a016f386a87e1cc56c5465f1-b6b40210"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="00bd20fe718fad569a224144c596cd43-b6b40210"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107170050227966-13536%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A41%3A44Z&ske=2021-07-23T08%3A46%3A44Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-17T00%3A47%3A22Z&se=2021-08-17T00%3A52%3A22Z&sr=b&sp=r&sig=royZ8lxX0kXTix0z2bfi326hl71wCnDhjNfBWAgX4B4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-17 01:10 UTC, opbld30 commented
Docs Build status updates of commit _[a4ebda3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a4ebda3f4bf5afea78db0173d03ed2513420ba9e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-c1bd4707)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-c1bd4707)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-c1bd4707)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-c1bd4707)
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-c1bd4707"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd89255e97aef19c83017cbb21595863-c1bd4707"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19592b74a016f386a87e1cc56c5465f1-c1bd4707"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="00bd20fe718fad569a224144c596cd43-c1bd4707"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107170108366967-13536%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A02%3A21Z&ske=2021-07-23T08%3A07%3A21Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-17T01%3A05%3A08Z&se=2021-08-17T01%3A10%3A08Z&sr=b&sp=r&sig=KCIf4elb2brK2n9353AjRs1lhcCPAWFfVkyuPuinBqw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-29 23:36 UTC, opbld30 commented
Docs Build status updates of commit _[8807854](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8807854f0bbc552fef474780a5a3866c08543e90)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-1dde5ef8)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-1dde5ef8)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-1dde5ef8)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-1dde5ef8)
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-1dde5ef8"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd89255e97aef19c83017cbb21595863-1dde5ef8"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19592b74a016f386a87e1cc56c5465f1-1dde5ef8"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="00bd20fe718fad569a224144c596cd43-1dde5ef8"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107292334573323-13536%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T04%3A12%3A54Z&ske=2021-08-04T04%3A17%3A54Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-29T23%3A31%3A34Z&se=2021-08-29T23%3A36%3A34Z&sr=b&sp=r&sig=kUmbeE5VlZ1YEXuRt7ojnViR%2BbErIbQbFVIk1zeCzL0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-29 23:43 UTC, opbld33 commented
Docs Build status updates of commit _[1f8f343](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f8f34358dd6038655508e6f58ca86a4cacbd343)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-15d166c2)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-15d166c2)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-15d166c2)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-15d166c2)
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-15d166c2"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd89255e97aef19c83017cbb21595863-15d166c2"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19592b74a016f386a87e1cc56c5465f1-15d166c2"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="00bd20fe718fad569a224144c596cd43-15d166c2"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107292341335761-13536%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T04%3A20%3A50Z&ske=2021-08-04T04%3A25%3A50Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-29T23%3A38%3A03Z&se=2021-08-29T23%3A43%3A03Z&sr=b&sp=r&sig=DATgX1Fa6u55%2Bk1cgUmQFG7RcpFDN8FHaIRkIrA8XVY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-30 08:21 UTC, opbld32 commented
Docs Build status updates of commit _[cd8d240](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd8d240082319dc3888bbf75a6d84d381b83c5a4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-c4faa4c5)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-c4faa4c5)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-c4faa4c5)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-c4faa4c5)
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-c4faa4c5"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd89255e97aef19c83017cbb21595863-c4faa4c5"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19592b74a016f386a87e1cc56c5465f1-c4faa4c5"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="00bd20fe718fad569a224144c596cd43-c4faa4c5"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107300818540411-13536%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-30T06%3A09%3A23Z&ske=2021-08-06T06%3A14%3A23Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-30T08%3A16%3A24Z&se=2021-08-30T08%3A21%3A24Z&sr=b&sp=r&sig=tRJFIdHblLwFJeen5nwHS%2FqYqQKDp41jY11jWASrdgQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-07 04:47 UTC, opbld33 commented
Docs Build status updates of commit _[8a7339a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a7339abb55a63c1d5d9ffd9ffb46fe406a9a4cf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-846f1c33)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-846f1c33)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-846f1c33)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-846f1c33)
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-846f1c33"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd89255e97aef19c83017cbb21595863-846f1c33"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19592b74a016f386a87e1cc56c5465f1-846f1c33"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="00bd20fe718fad569a224144c596cd43-846f1c33"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109070445083810-13536%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=bqrPNlp9yov0SDU0jvnWBW99adE4R8E7Hqm0Ld5GKgk%3D&st=2021-09-07T04%3A42%3A53Z&se=2021-10-08T04%3A47%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-07 04:58 UTC, opbld34 commented
Docs Build status updates of commit _[d6b8c13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6b8c137ea211d9e8d7ec8b9ae5fecf8c4d61b54)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-6ef5b64e)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-6ef5b64e)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-6ef5b64e)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-6ef5b64e)
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-6ef5b64e"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd89255e97aef19c83017cbb21595863-6ef5b64e"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19592b74a016f386a87e1cc56c5465f1-6ef5b64e"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="00bd20fe718fad569a224144c596cd43-6ef5b64e"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109070455431539-13536%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=DamXBVrIhb4iU4hGbVy%2Fm0rbhUjEQE0Z9C9yUIFwAdQ%3D&st=2021-09-07T04%3A53%3A12Z&se=2021-10-08T04%3A58%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-07 16:17 UTC, opbld32 commented
Docs Build status updates of commit _[f5ca8a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5ca8a3f9d9d02476f1a116a58b1562d85d5e135)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-2d5a79cc)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-2d5a79cc)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-2d5a79cc)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-2d5a79cc)
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-2d5a79cc"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd89255e97aef19c83017cbb21595863-2d5a79cc"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19592b74a016f386a87e1cc56c5465f1-2d5a79cc"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="00bd20fe718fad569a224144c596cd43-2d5a79cc"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109071615181775-13536%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=VEnv1lp%2FUz9c5b3RFOkeu6ZspU3LoLfjvkYv24VBe74%3D&st=2021-09-07T16%3A11%3A59Z&se=2021-10-08T16%3A16%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-07 16:32 UTC, opbld32 commented
Docs Build status updates of commit _[20325cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20325cc3ee563c37b384234172545910aa1278d2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-3d9ae741)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-3d9ae741)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-3d9ae741)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-3d9ae741)
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-3d9ae741"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd89255e97aef19c83017cbb21595863-3d9ae741"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19592b74a016f386a87e1cc56c5465f1-3d9ae741"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="00bd20fe718fad569a224144c596cd43-3d9ae741"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109071631206567-13536%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=HMxBnpekkQjN2k2yMX8mlyATWhHnGzlnfGRurUadSgc%3D&st=2021-09-07T16%3A27%3A58Z&se=2021-10-08T16%3A32%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 21:51 UTC, JarbasHorst requested changes

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +|
Please, remove this pipe.

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +|
Please, remove this pipe.

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +|
Please, remove this pipe.

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +## Paging
We don't support non-standard H2s. Please, incorporate that information into the "Optional query parameters" section. You don't need to include the first paragraph because the [paging article](https://docs.microsoft.com/en-us/graph/paging) already explains how to page data in Microsoft Graph.

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +Note that paging is consistent only when a start time and end time is specified or a specific condition is used (such as query by a message id). Without a bounded query, pages may return data that ma
For simplicity and readability, please remove parentheses. Also, in regular text, please use ID as the abbreviation for identity. Suggested revision:

- ...specified or a specific condition is used such as query by a message ID.

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +### Example 3. Get message trace data for a given message Id
In regular text, please use ID as the abbreviation for identity.

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/resources/messageevent.md
> +|id|String|Random id for this event (not a unique key).|
In regular text, please use ID as the abbreviation for identity. Suggested revision:

- Random ID for this event...

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/resources/messagerecipient.md
> +|id|String|Random id for this recipient (not a unique key).|
In regular text, please use ID as the abbreviation for identity. Suggested revision:

- Random ID for this recipient...

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +### Example 1. Get most recent message trace data
For consistency, please replace Example 1. with Example 1: Suggested revision:

- Example 1: Get most...

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +### Example 2. Get message trace data for a specific message
For consistency, please replace Example 2. with Example 2: Suggested revision:

- Example 2: Get message...

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +### Example 3. Get message trace data for a given message Id
For consistency, please replace Example 3. with Example 3: Suggested revision:

- Example 3: Get message...

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +### Example 4. Get message trace data for a given set of recipients in a date range
For consistency, please replace Example 4. with Example 4: Suggested revision:

- Example 4: Get message...

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +### Example 5. Get message trace event detail data for a given recipient
For consistency, please replace Example 5. with Example 5: Suggested revision:

- Example 5: Get message...

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/resources/messagerecipient.md
> +### messageStatus values
Enums must be added to the [Enums resource topic](https://docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta). Please, add the messageStatus enum to the Enums resource, and remove the entire H3 heading "### messageStatus values" from this resource topic.

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/resources/messageevent.md
> +### messageEventType values
Enums must be added to the [Enums resource topic](https://docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta). Please, add the messageEventType enum to the Enums resource, and remove the entire H3 heading "### messageEventType values" from this resource topic.

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +This API is accessible only to Tenant Admin, Security Admin and Security Reader roles.
For clarity, I recommend you to rephrase this sentence. Also, please highlight the sentence using a note.

> **Note**: This API supports admin permissions. Global admins, Security admins, and users with the Security Reader role can access ???.

OR

> **Note**: This API supports admin permissions. Global admins, Security admins, and users with the Security Reader role can access message trace information.

2021-09-08 21:51 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +Message tracing is one of the tools used by administrators to monitor the email messages flowing through Office 365 for their organization. It provides the admin basic information about the messages:
Please replace Office 365 with Microsoft 365.

2021-09-09 03:59 UTC, opbld33 commented
Docs Build status updates of commit _[d5a5ff6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5a5ff645cf9d450b8d0fee87637bd41d6080689)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2c18df76)

<a id="2c18df76"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109090359213725-13536%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=j8zKo4l6IN3v5OaoXfZJV88y3WklY5ZKJD3IToS5uXI%3D&st=2021-09-09T03%3A54%3A43Z&se=2021-10-10T03%3A59%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-09 04:06 UTC, opbld34 commented
Docs Build status updates of commit _[d5b6201](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5b62019eb9a9e31b9fe37c4a062611c688c0969)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-8017d15e)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-8017d15e)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-8017d15e)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-8017d15e)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-8017d15e"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd89255e97aef19c83017cbb21595863-8017d15e"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19592b74a016f386a87e1cc56c5465f1-8017d15e"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="00bd20fe718fad569a224144c596cd43-8017d15e"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109090405077098-13536%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=zkFCEOZxDVruVx3PbSVBieTCdPWcR9ieE%2BF0K8sHTbE%3D&st=2021-09-09T04%3A01%3A46Z&se=2021-10-10T04%3A06%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-09 09:46 UTC, angelgolfer-ms reviewed
Hi @rsuven ,
After a quick glance at your PR, you need to please create 2 additional resource topics:

- One for the admin resource type - looks like you're adding an exchange nav property to the admin resource. This was somehow left out by 2 other teams. I hope you still have access to the generated set of topics for your PR; it should have a topic admin.md there. Please provide a description for that resource and the exchange nav property. You can leave the descriptions for the other nav properties (serviceAnnouncement and windows) blank; I'll try to fill them in.
- The other is the type for the exchange nav property. (I look forward you to send me a link to the CSDL offline on Teams.)

FYI our docs should be complete and describe the segments appearing in a query URL. So that's why the admin and exchange segments should be documented, even though we won't add them to the TOC.

I'll let you know offline about the TOC entry points. When you have the corresponding concept overview and API overview topics updated, I can do a review pass on your PR then.

Thank you!!

2021-09-13 21:15 UTC, JarbasHorst requested changes

2021-09-13 21:15 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +Message tracing is one of the tools used by administrators to monitor the email messages flowing through Microsoft 365 for their organization. It provides the admin basic information about the messag
A word ending in –ing can be a verb, a noun, or an adjective. Please, avoid using gerunds where possible; in this case, you can change "flowing" to "that flows".

2021-09-13 21:15 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +This API allows the administrator to search for messages using various search criteria for messages for the past 10 days. It also provides detailed message trace event details for a specific message
For simplicity and clarity, please rephrase this sentence. Suggested revision:

- Admins can use various search criteria to search for messages for the past 10 days. The search result contains detailed message trace event details for a specific message and recipient.

2021-09-13 22:22 UTC, opbld33 commented
Docs Build status updates of commit _[50ee81d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50ee81d0ce221355658f0574efadbb56806a7ad7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-319fbe2d)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-319fbe2d)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-319fbe2d)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-319fbe2d)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-319fbe2d)
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) | [Details](#user-content-7a9807e1df2711b6b7e6a680b1d1a45f-319fbe2d)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-319fbe2d"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd89255e97aef19c83017cbb21595863-319fbe2d"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19592b74a016f386a87e1cc56c5465f1-319fbe2d"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="00bd20fe718fad569a224144c596cd43-319fbe2d"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a09d4c88442bd2a1124eb581485232a0-319fbe2d"></a>
### [concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md)
 - **Line 65, Column 44**: **[Warning-[hard-coded-locale](https://review. [...]

2021-09-14 00:34 UTC, opbld30 commented
Docs Build status updates of commit _[39f0888](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39f08884741691b97f7c1dbc800ed79c39521beb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-f25d1551)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-f25d1551)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-f25d1551)
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) | [Details](#user-content-7a9807e1df2711b6b7e6a680b1d1a45f-f25d1551)
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="bd89255e97aef19c83017cbb21595863-f25d1551"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 28, Column 12**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#messageeventtype-values' in 'beta/resources/enums.md'.`````

<a id="19592b74a016f386a87e1cc56c5465f1-f25d1551"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 28, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#messagestatus-values' in 'beta/resources/enums.md'.`````

<a id="a09d4c88442bd2a1124eb581485232a0-f25d1551"></a>
### [concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md)
 - **Line 65, Column 44**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/message-trace-scc?view=o365-worldwide' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 65, Column 216**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/monitoring/trace-an-email-message/message-trace-modern-eac' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 65, Column 44**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/message-trace-scc?view=o365-worldwide' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 65, Column 44**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/message-trace-scc?view=o365-worldwide. Otherwise, remove the view parameter.`````
 - **Line 65, Column 216**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/monitoring/trace-an-email-message/message-trace-modern-eac' will be broken in isolated environments. Replace with a relative link.`````

<a id="7a9807e1df2711b6b7e6a680b1d1a45f-f25d1551"></a>
### [concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md)
 - **Line 70, Column 44**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/message-trace-scc?view=o365-worldwide' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 70, Column 216* [...]

2021-09-14 00:36 UTC, rsuven commented on api-reference/beta/api/messagetrace-get.md
> +ms.prod: ""
Using security for ms.prod. Not sure what to use for ms.date, since I see no use in other docs. I have asked Angela, but please let me know as well.

2021-09-14 00:36 UTC, rsuven commented on api-reference/beta/api/messagetrace-get.md
> +Message tracing is one of the tools used by administrators to monitor the email messages flowing through Microsoft 365 for their organization. It provides the admin basic information about the messag
Rewrote that entire part, please take a look.

2021-09-14 00:59 UTC, opbld31 commented
Docs Build status updates of commit _[959f0e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/959f0e3bbacc6d2fa85256e503c03d3284a67ff2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-35939d89)
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) | [Details](#user-content-7a9807e1df2711b6b7e6a680b1d1a45f-35939d89)
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="a09d4c88442bd2a1124eb581485232a0-35939d89"></a>
### [concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md)
 - **Line 65, Column 44**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/message-trace-scc' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 65, Column 190**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/exchange/monitoring/trace-an-email-message/message-trace-modern-eac' will be broken in isolated environments. Replace with a relative link.`````

<a id="7a9807e1df2711b6b7e6a680b1d1a45f-35939d89"></a>
### [concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md)
 - **Line 12, Column 350**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/securityvendorinformation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 22, Column 5**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/security-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 70, Column 44**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/message-trace-scc' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 70, Column 190**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/exchange/monitoring/trace-an-email-message/message-trace-modern-eac' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 85, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/security-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 86, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/security-api-overview?view=grap [...]

2021-09-14 19:28 UTC, JarbasHorst commented on api-reference/beta/api/messagetrace-get.md
> +ms.prod: ""
Setting **ms.date** to the date that a topic was published or updated is a best practice for SEO as it helps readers verify the currency of the content. Most topics don't currently include ms.date because it must be set manually. We recommend adding this value when you add or update content. In the future, ms.date will be automated via API Doctor.

2021-09-14 21:26 UTC, JarbasHorst requested changes

2021-09-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/messageevent.md
> +| dlpRuleTriggered | A Data Loss Prevetion (DLP) policy rule triggered. |
Please, replace "Prevetion" with "Prevention".

2021-09-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/messageevent.md
> +| dropped | Message was dropped without a delivery status notification (also known as a DSN), bounce message, or non-delivery report (NDR). For example, spam messages that were silently dropped witho
For clarity, I recommend you to remove the parentheses. Suggested revision:

-  Message was dropped without a delivery status notification, also known as a DSN, bounce message, or non-delivery report (NDR).

2021-09-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/messageevent.md
> +| malwareDetected | Malware detected in the message. This will show as a failed message delivery with a Malware event. The Malware event contains information about which malware signature matched and
For simplicity, I recommend you not to capitalize the word Malware. Suggested revision:

- ...with a malware event. The malware event...

2021-09-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/messagerecipient.md
> +|id|String|Random ID for this recipient (not a unique key).|
For clarity and readability, I recommend you to remove the information from the parentheses. Suggested revision:

- Random ID for this event. Not a unique key.

2021-09-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/messagerecipient.md
> +|events|[messageEvent](../resources/messageevent.md) collection|details of events during delivery of a mail message to a recipient.|
Please, capitalize the first letter of this sentence.

2021-09-14 21:26 UTC, JarbasHorst commented on api-reference/beta/resources/messagerecipient.md
> +| gettingStatus | The message is waiting for status update. |
A word ending in –ing can be a verb, a noun, or an adjective. Please, avoid using gerunds where possible; in this case, you can change "is waiting" to "waits".

2021-09-14 21:30 UTC, opbld32 commented
Docs Build status updates of commit _[43c4d10](https://github.com/microsoftgraph/microsoft-graph-docs/commits/43c4d10a14c6f160c4e0ccbefd5d0e225b3f5b02)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-7d541b84)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-7d541b84)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-7d541b84)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-7d541b84)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-7d541b84)
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) | [Details](#user-content-7a9807e1df2711b6b7e6a680b1d1a45f-7d541b84)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-7d541b84"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 7, Column 10**: **[Warning-[ms-date-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Invalid date format for 'ms.date': '09-14-2021'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

<a id="bd89255e97aef19c83017cbb21595863-7d541b84"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 7, Column 10**: **[Warning-[ms-date-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Invalid date format for 'ms.date': '09-14-2021'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

<a id="19592b74a016f386a87e1cc56c5465f1-7d541b84"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 7, Column 10**: **[Warning-[ms-date-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Invalid date format for 'ms.date': '09-14-2021'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

<a id="00bd20fe718fad569a224144c596cd43-7d541b84"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 7, Column 10**: **[Warning-[ms-date-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Invalid date format for 'ms.date': '09-14-2021'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

<a id="a09d4c88442bd2a1124eb581485232a0-7d541b84"></a>
### [concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md)
 - **Line 65, Column 44**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/message-trace-scc' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 65, Column 190**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/exchange/monitoring/trace-an-email-message/message-trace-modern-eac' will be broken in isolated environments. Replace with a relative link.`````

<a id="7a9807e1df2711b6b7e6a680b1d1a45f-7d541b84"></a>
### [concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md)
 - **Line 12, Column 350**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link [...]

2021-09-14 21:44 UTC, rsuven commented on api-reference/beta/resources/messagerecipient.md
> +| gettingStatus | The message is waiting for status update. |
I think "is waiting" is a usage as a verb, not as anything else. Making it "waits" removes the continuous nature of the statement.

2021-09-14 21:46 UTC, rsuven commented on api-reference/beta/resources/messageevent.md
> +| dropped | Message was dropped without a delivery status notification (also known as a DSN), bounce message, or non-delivery report (NDR). For example, spam messages that were silently dropped witho
changed it to (DSN).

2021-09-14 22:02 UTC, opbld34 commented
Docs Build status updates of commit _[e62521d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e62521d7b6d609b7a59ce25a483659e16eea1772)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-af2382660c8380c9b6570c8760fbd85c-56640500)
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-bd89255e97aef19c83017cbb21595863-56640500)
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-19592b74a016f386a87e1cc56c5465f1-56640500)
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-00bd20fe718fad569a224144c596cd43-56640500)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-56640500)
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) | [Details](#user-content-7a9807e1df2711b6b7e6a680b1d1a45f-56640500)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="af2382660c8380c9b6570c8760fbd85c-56640500"></a>
### [api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md)
 - **Line 7, Column 10**: **[Warning-[ms-date-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Invalid date format for 'ms.date': '09-14-2021'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

<a id="bd89255e97aef19c83017cbb21595863-56640500"></a>
### [api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md)
 - **Line 7, Column 10**: **[Warning-[ms-date-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Invalid date format for 'ms.date': '09-14-2021'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

<a id="19592b74a016f386a87e1cc56c5465f1-56640500"></a>
### [api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md)
 - **Line 7, Column 10**: **[Warning-[ms-date-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Invalid date format for 'ms.date': '09-14-2021'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

<a id="00bd20fe718fad569a224144c596cd43-56640500"></a>
### [api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md)
 - **Line 7, Column 10**: **[Warning-[ms-date-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Invalid date format for 'ms.date': '09-14-2021'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

<a id="a09d4c88442bd2a1124eb581485232a0-56640500"></a>
### [concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md)
 - **Line 65, Column 44**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/message-trace-scc' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 65, Column 190**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/exchange/monitoring/trace-an-email-message/message-trace-modern-eac' will be broken in isolated environments. Replace with a relative link.`````

<a id="7a9807e1df2711b6b7e6a680b1d1a45f-56640500"></a>
### [concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md)
 - **Line 12, Column 350**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link [...]

2021-09-14 22:05 UTC, opbld34 commented
Docs Build status updates of commit _[cf4945d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cf4945d531fa2735f86e3e692a2c71d6db4f8c81)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-eef07e8b)
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) | [Details](#user-content-7a9807e1df2711b6b7e6a680b1d1a45f-eef07e8b)
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |

<a id="a09d4c88442bd2a1124eb581485232a0-eef07e8b"></a>
### [concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md)
 - **Line 65, Column 44**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/message-trace-scc' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 65, Column 190**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/exchange/monitoring/trace-an-email-message/message-trace-modern-eac' will be broken in isolated environments. Replace with a relative link.`````

<a id="7a9807e1df2711b6b7e6a680b1d1a45f-eef07e8b"></a>
### [concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md)
 - **Line 12, Column 350**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/securityvendorinformation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 22, Column 5**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/security-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 70, Column 44**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/message-trace-scc' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 70, Column 190**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/exchange/monitoring/trace-an-email-message/message-trace-modern-eac' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 85, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/security-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 86, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/security-api-overview?view=grap [...]

2021-09-15 20:20 UTC, JarbasHorst requested changes

2021-09-15 20:20 UTC, JarbasHorst commented on concepts/outlook-mail-concept-overview.md
> +For more information on message trace, see [Message trace in the Microsoft 365 Defender portal](https://docs.microsoft.com/microsoft-365/security/office-365-security/message-trace-scc) and [Message t
The absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/message-trace-scc' will be broken in isolated environments. Replace the absolute link with a relative link.

2021-09-15 20:20 UTC, JarbasHorst commented on concepts/outlook-mail-concept-overview.md
> +For more information on message trace, see [Message trace in the Microsoft 365 Defender portal](https://docs.microsoft.com/microsoft-365/security/office-365-security/message-trace-scc) and [Message t
The absolute link 'https://docs.microsoft.com/exchange/monitoring/trace-an-email-message/message-trace-modern-eac' will be broken in isolated environments. Replace the absolute link with a relative link.

2021-09-15 20:20 UTC, JarbasHorst commented on concepts/security-concept-overview.md
> +For more information on message trace, see [Message trace in the Microsoft 365 Defender portal](https://docs.microsoft.com/microsoft-365/security/office-365-security/message-trace-scc) and [Message t
The absolute link 'https://docs.microsoft.com/microsoft-365/security/office-365-security/message-trace-scc' will be broken in isolated environments. Replace the absolute link with a relative link.

2021-09-15 20:20 UTC, JarbasHorst commented on concepts/security-concept-overview.md
> +For more information on message trace, see [Message trace in the Microsoft 365 Defender portal](https://docs.microsoft.com/microsoft-365/security/office-365-security/message-trace-scc) and [Message t
The absolute link 'https://docs.microsoft.com/exchange/monitoring/trace-an-email-message/message-trace-modern-eac' will be broken in isolated environments. Replace the absolute link with a relative link.

2021-09-15 20:20 UTC, JarbasHorst commented on changelog/Microsoft.GetMessageTraces.json
> +{"changelog":[{"ChangeList":[{"Id":"7e8050b7-daa4-11eb-b17b-013bcf28b7ee","ApiChange":"Resource","ChangedApiName":"messageTrace","ChangeType":"Addition","Description":"Added the [messageTrace](https:
Within a changelog record, all Id properties must have the same value.

2021-09-15 21:58 UTC, JarbasHorst requested changes

2021-09-15 21:58 UTC, JarbasHorst commented on changelog/Microsoft.GetMessageTraces.json
> +{"changelog":[{"ChangeList":[{"Id":"7e8050b7-daa4-11eb-b17b-013bcf28b7ee","ApiChange":"Resource","ChangedApiName":"messageTrace","ChangeType":"Addition","Description":"Added the [messageTrace](https:
For clarity, please extend the description of the messagetrace resource to contain _supported method_ because the messageTrace resource topic contains a method. Suggested revision:

- Added the \[messageTrace\]\(https://docs.microsoft.com/en-us/graph/api/resources/messageTrace?view=graph-rest-beta\) resource type and supported method.

2021-10-01 02:30 UTC, opbld34 commented
Docs Build status updates of commit _[d55fa34](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d55fa346c70d39d878e10c4f336611d192478e63)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2c86034f)

<a id="2c86034f"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110010229554945-13536%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T02%3A30%3A18Z&sr=b&sp=r&sig=t6vG%2FTeyOtYhcGh1PtM4C2j2y2V9y6tiorWWmn5XULg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 02:32 UTC, opbld31 commented
Docs Build status updates of commit _[e401e62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e401e62a9ece5b98b6a4719af1f58fa1d786f012)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3c219540)

<a id="3c219540"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110010231395636-13536%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T02%3A32%3A01Z&sr=b&sp=r&sig=Nwoe%2FckPkX9ZRbwfpGbQMCAeQ8c4BYzUk6lDGCnIEWc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-02 00:24 UTC, opbld30 commented
Docs Build status updates of commit _[e7c5518](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7c55188c1c30f01b20a1f75eff8b21a73ba36f4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) | [Details](#user-content-7a9807e1df2711b6b7e6a680b1d1a45f-e1f043d9)
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/v1.0/api/tablerow-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/v1.0/api/tablerow-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-range?view=graph-rest-1.0&branch=pr-en-us-13536) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookpivottable-refreshall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/v1.0/api/workbookpivottable-refreshall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookpivottable-refreshall?view=graph-rest-1.0&branch=pr-en-us-13536) (>= graph-rest-1.0) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) |

<a id="7a9807e1df2711b6b7e6a680b1d1a45f-e1f043d9"></a>
### [concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md)
 - **Line 12, Column 350**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/securityvendorinformation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 22, Column 5**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/security-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 85, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/security-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 86, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/security-api-overview?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 90, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/security-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110020022589980-13536%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-02T00%3A24%3A42Z&sr=b&sp=r&sig=FIDsyHEO74Am3vUGUNt10Jq7fkGQg5ioN8blXHzWnEk%3D).

**Note:** Broken links written as relative paths are inclu [...]

2021-10-05 21:45 UTC, opbld32 commented
Docs Build status updates of commit _[fe722d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe722d0136b1963901336c6e7c6400bdcd0a6c81)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) | [Details](#user-content-7a9807e1df2711b6b7e6a680b1d1a45f-5d79a158)
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) |

<a id="7a9807e1df2711b6b7e6a680b1d1a45f-5d79a158"></a>
### [concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md)
 - **Line 12, Column 350**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/securityvendorinformation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 22, Column 5**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/security-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 85, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/security-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 86, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/security-api-overview?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 90, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/security-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110052142551678-13536%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-05T21%3A45%3A13Z&sr=b&sp=r&sig=JIhKinFNb4O8L1m4wXglbL5rV2t9%2BWiJGU3CHZ2Vz9U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-06 20:27 UTC, JarbasHorst commented
@angelgolfer-ms this PR is ready for final review. Please, keep in mind that we can publish this PR **only after** the permissions are deployed.

2021-10-13 05:28 UTC, opbld30 commented
Docs Build status updates of commit _[18042c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/18042c8355fef3d103c8b62423162a5cde346927)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) |
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110130526267805-13536%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-13T05%3A28%3A42Z&sr=b&sp=r&sig=S3FqCJsXJTx1Z0mRnj3zYhasHkA0XQlF7muYxpX5GTg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-13 08:56 UTC, opbld34 commented
Docs Build status updates of commit _[ba5698f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba5698f44f7911c4ad1b7b6f978403e23df98b33)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/messagetrace-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/messagetrace-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/messagetrace-get?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) |
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110130855141974-13536%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-13T08%3A56%3A54Z&sr=b&sp=r&sig=0Bti72K56V5JNRdV%2BoGJH0gyUw5qjRKAH5GUfxNJv2U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-15 20:40 UTC, opbld30 commented
Docs Build status updates of commit _[6459dc3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6459dc35ee0955a95d78cb5aa4a534e1b9a94f8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/exchangeadmin-list-messagetraces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/exchangeadmin-list-messagetraces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/exchangeadmin-list-messagetraces?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/exchangeadmin-list-messagetraces?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) |
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110152038253513-13536%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-15T20%3A40%3A34Z&sr=b&sp=r&sig=IT%2FsASVjCZXbypnf5dHbIpaDecjvBltv%2BN%2FkQAeD7%2Bw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-16 03:39 UTC, opbld33 commented
Docs Build status updates of commit _[27917cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27917cf12f1f8992fb21202044d59da529850241)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-0da74140)
[api-reference/beta/api/exchangeadmin-list-messagetraces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/exchangeadmin-list-messagetraces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/exchangeadmin-list-messagetraces?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/exchangeadmin-list-messagetraces?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) |
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) |

<a id="4b33441e61d32f646b88781171f64ffa-0da74140"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md)
 - **Line 2569, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````
 - **Line 2580, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````
 - **Line 2590, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````
 - **Line 2598, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````
 - **Line 2608, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110160337234399-13536%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-16T03%3A39%3A50Z&sr=b&sp=r&sig=6NneexgQ0aWDo9SSQaZJfxlxTlej33%2F6Zf8y1iUUktY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-16 06:25 UTC, opbld31 commented
Docs Build status updates of commit _[c86dcd6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c86dcd6d90dee2f597562833a18cf62c191fb0f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-59acf370)
[api-reference/beta/api/exchangeadmin-list-messagetraces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/exchangeadmin-list-messagetraces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/exchangeadmin-list-messagetraces?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/exchangeadmin-list-messagetraces?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) |
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) |

<a id="4b33441e61d32f646b88781171f64ffa-59acf370"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md)
 - **Line 2569, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````
 - **Line 2580, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````
 - **Line 2590, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````
 - **Line 2598, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````
 - **Line 2608, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110160623156721-13536%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-16T06%3A25%3A54Z&sr=b&sp=r&sig=IDhQrqamszWKfTfy2g2jWJcg74ITkpZdFE6Ci0AiFbA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-16 08:13 UTC, opbld31 commented
Docs Build status updates of commit _[f168014](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f168014b9d43a70a66c8b1c2325c5df63744a774)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-829cc2e0)
[api-reference/beta/api/exchangeadmin-list-messagetraces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/exchangeadmin-list-messagetraces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/exchangeadmin-list-messagetraces?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/exchangeadmin-list-messagetraces?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) |
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) |

<a id="4b33441e61d32f646b88781171f64ffa-829cc2e0"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md)
 - **Line 2569, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````
 - **Line 2580, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````
 - **Line 2590, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````
 - **Line 2598, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````
 - **Line 2608, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110160810558183-13536%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-16T08%3A13%3A22Z&sr=b&sp=r&sig=ICLSg9QzB4%2Bk2VRMBENTUQfbo0AXqMxOPLdIsQnZ5%2FQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-18 22:03 UTC, opbld31 commented
Docs Build status updates of commit _[ce33153](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ce33153c127c0b595df0c91cca202283bc3bbf71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/exchangeadmin-list-messagetraces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/exchangeadmin-list-messagetraces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/exchangeadmin-list-messagetraces?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/exchangeadmin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/exchangeadmin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/exchangeadmin?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/exchangeadmin-list-messagetraces?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) |
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110182159343240-13536%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-18T22%3A03%3A56Z&sr=b&sp=r&sig=w4thxbg9iM5qlEREPHdw6BNnrzav7rtuAtwDgzg3IRo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-18 22:08 UTC, opbld34 commented
Docs Build status updates of commit _[719829d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/719829dbeef59f82e9dcc7be1a5bc6b26610e9d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/exchangeadmin-list-messagetraces.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/api/exchangeadmin-list-messagetraces.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/exchangeadmin-list-messagetraces?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/exchangeadmin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/exchangeadmin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/exchangeadmin?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messageevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messageevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageevent?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagerecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagerecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagerecipient?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/messagetrace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/messagetrace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagetrace?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/exchangeadmin-list-messagetraces?view=graph-rest-beta&branch=pr-en-us-13536) (graph-rest-beta) |
[changelog/Microsoft.GetMessageTraces.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/changelog/Microsoft.GetMessageTraces.json) | :white_check_mark:Succeeded | |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-13536) |
[concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-01-docs_GetMessageTracesCny/concepts/security-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/security-concept-overview?branch=pr-en-us-13536) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110182205444371-13536%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-18T22%3A08%3A38Z&sr=b&sp=r&sig=LJifjgZG1iJrfGJRA47lFhJ3%2BR%2Busudu%2F42Z5R9H0gA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-17 15:17 UTC, isvargasmsft commented
Hello @rsuven, what's the status of this PR?

2022-02-24 15:00 UTC, closed without merging