bug fixes for july train
microsoftgraph/microsoft-graph-docs pull request #13535
Opened 2021-07-15 23:23 UTC by cristobal-buenrostro

2021-07-15 23:25 UTC, opbld31 commented
Docs Build status updates of commit _[1e0f820](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e0f8203eb699403450be9bf7d6491ee88e5382a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107152323495804-13535%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A15%3A48Z&ske=2021-07-20T08%3A20%3A48Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T23%3A20%3A19Z&se=2021-08-15T23%3A25%3A19Z&sr=b&sp=r&sig=ebwM7EdzCLcwvWv7vixrxLV0P3iOLWLw%2FP%2Ft9PHx9uk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 18:17 UTC, opbld33 commented
Docs Build status updates of commit _[8f47011](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f47011372530b2c8332423ea122a7c5f69e08ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/v1.0/api/educationclass-post-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/api/educationclass-post-assignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignment?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161816157554-13535%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A01%3A15Z&ske=2021-07-23T08%3A06%3A15Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T18%3A12%3A51Z&se=2021-08-16T18%3A17%3A51Z&sr=b&sp=r&sig=QMHary3hi91f7bIvwpimElmfTsc8a4eCJLq%2ByBlZurk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-19 15:27 UTC, opbld33 commented
Docs Build status updates of commit _[245a41a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/245a41a8b090c6e0e64b63afcf2c85ad4f308ec2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/v1.0/api/educationclass-post-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/api/educationclass-post-assignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignment?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107191526124104-13535%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T04%3A18%3A24Z&ske=2021-07-26T04%3A23%3A24Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-19T15%3A22%3A42Z&se=2021-08-19T15%3A27%3A42Z&sr=b&sp=r&sig=WXj9y1K2KuB6J8UA%2BLEZvVkkEi9f%2Fep%2Bv9BaluEgx30%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-19 15:37 UTC, isvargasmsft commented on api-reference/beta/api/educationclass-post-assignments.md
>    "name": "create_educationassignment_from_educationclass"
Line 51: please use the proper blocktype: request. Guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor

2021-07-19 15:48 UTC, isvargasmsft commented on api-reference/beta/resources/educationassignmentdefaults.md
> +|addToCalendarAction| educationAddToCalendarOptions|Optional field to control adding assignments to students' and teachers' calendars when the assignment is published.|
I am asking API Doctor team to check this line: https://teams.microsoft.com/l/message/19:d41bffc68cb143978ae9d0d084712efa@thread.skype/1626709634124?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=6d279915-6f5d-452c-895b-7f4f82038843&parentMessageId=1626709634124&teamName=Microsoft%20Graph&channelName=Docs%20-%20API%20Doctor&createdTime=1626709634124

2021-07-19 16:59 UTC, isvargasmsft commented on api-reference/beta/resources/educationassignmentdefaults.md
> +|addToCalendarAction| educationAddToCalendarOptions|Optional field to control adding assignments to students' and teachers' calendars when the assignment is published.|
Response: Please add educationAddToCalendarOptions to the enums.md file in both beta and v1.

2021-07-19 18:56 UTC, cristobal-buenrostro commented on api-reference/beta/resources/educationassignmentdefaults.md
> +|addToCalendarAction| educationAddToCalendarOptions|Optional field to control adding assignments to students' and teachers' calendars when the assignment is published.|
> Response: Please add educationAddToCalendarOptions to the enums.md file in both beta and v1.

Done, it was pending only at v1.0 file

2021-07-19 18:57 UTC, opbld32 commented
Docs Build status updates of commit _[bf8c40c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf8c40c889b9ef9b4d05cf8f1536d5de8c1ec348)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/v1.0/api/educationclass-post-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/api/educationclass-post-assignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignment?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107191854539870-13535%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A12%3A24Z&ske=2021-07-26T03%3A17%3A24Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-19T18%3A52%3A28Z&se=2021-08-19T18%3A57%3A28Z&sr=b&sp=r&sig=Sgt1ZAg6I%2B4xKYqxWYfaDG0WGEcAN3LH7W%2BAuJYhbqI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-19 19:47 UTC, isvargasmsft requested changes
Thank you very much for addressing my comments. 

Please take the time to review my first comment regarding the API Doctor blocktype. It is important that we follow the guidelines here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor

Please use blocktype: request in the example in educationclass-post-assignments.md

2021-07-19 20:55 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationclass-post-assignments.md
>    "name": "create_educationassignment_from_educationclass"
Done, verified it against v1.0, to make sure have the same.

2021-07-19 20:58 UTC, opbld30 commented
Docs Build status updates of commit _[f6bb8e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6bb8e395202b0cbad9365ccaf859cac37d5ad25)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/v1.0/api/educationclass-post-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/api/educationclass-post-assignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignment?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107192054393279-13535%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A39%3A52Z&ske=2021-07-26T02%3A44%3A52Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-19T20%3A53%3A50Z&se=2021-08-19T20%3A58%3A50Z&sr=b&sp=r&sig=ljgjJZ28FwDVw9uXVNr%2B4gKU0ILMHCgY4jGkdLu1eDQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-20 17:17 UTC, opbld33 commented
Docs Build status updates of commit _[f77c617](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f77c6172d0fbdd7c8138141e5ae35ed7e5a24ce1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/v1.0/api/educationclass-post-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/api/educationclass-post-assignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignment?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107201715571662-13535%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A00%3A55Z&ske=2021-07-26T03%3A05%3A55Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-20T17%3A12%3A13Z&se=2021-08-20T17%3A17%3A13Z&sr=b&sp=r&sig=h1nGtX93AUdTaGIi%2BIvuw%2FivfnESL9BKdNsXMYknlJA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-21 13:42 UTC, opbld30 commented
Docs Build status updates of commit _[810acf5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/810acf5dba0cdba7640da40911a9bb2e3192fb7d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/v1.0/api/educationclass-post-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/api/educationclass-post-assignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignment?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107211340429926-13535%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-20T22%3A28%3A21Z&ske=2021-07-27T22%3A33%3A21Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-21T13%3A37%3A22Z&se=2021-08-21T13%3A42%3A22Z&sr=b&sp=r&sig=2miMhcgfsnFd%2BnqkaPVgnCb3m051VTuRuQ6Y%2BIut4V0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-21 14:51 UTC, opbld33 commented
Docs Build status updates of commit _[205ec15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/205ec153e7a2a49ff17124ec71db909e66a178ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/v1.0/api/educationclass-post-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/api/educationclass-post-assignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignment?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107211449460647-13535%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A37%3A59Z&ske=2021-07-26T02%3A42%3A59Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-21T14%3A46%3A22Z&se=2021-08-21T14%3A51%3A22Z&sr=b&sp=r&sig=FU%2BUhJOQ%2BJlxWSnW5e2VuxT9oTUtbsv3D2VGx8gVn1g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-22 16:59 UTC, opbld32 commented
Docs Build status updates of commit _[2b0e69a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b0e69af9045035a503ba77c3bed1635967b06b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/v1.0/api/educationclass-post-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/api/educationclass-post-assignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignment?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107221658098942-13535%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A32%3A49Z&ske=2021-07-26T02%3A37%3A49Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-22T16%3A54%3A50Z&se=2021-08-22T16%3A59%3A50Z&sr=b&sp=r&sig=r8nv0%2FhbILmF1VD5lwDxIe9ucv1q%2F%2F6OLWwhC%2BPPjvM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-22 17:31 UTC, opbld33 commented
Docs Build status updates of commit _[ec05cd2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec05cd2f571c3fc481bf642d4758ca3267d3f315)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-22 17:39 UTC, opbld33 commented
Docs Build status updates of commit _[d81b938](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d81b93847867d208df8d5f69fea2425e07c7d7fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/v1.0/api/educationclass-post-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/api/educationclass-post-assignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignment?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107221738017452-13535%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-20T13%3A52%3A19Z&ske=2021-07-27T13%3A57%3A19Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-22T17%3A34%3A36Z&se=2021-08-22T17%3A39%3A36Z&sr=b&sp=r&sig=0xq%2BSbxzsIho6vennFjq5%2FSm2WVXfBUsobhsjJmja70%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-22 18:26 UTC, sharad-sharma-msft commented on api-reference/v1.0/resources/enums.md
> +### educationAddToCalendarOptions values
this feature is only available in beta so this enum update is not applicable to v1.0

2021-07-22 23:59 UTC, opbld30 commented
Docs Build status updates of commit _[4324b49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4324b498759a3a71c5cd27d4150acac7e0f52fe7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/v1.0/api/educationclass-post-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/api/educationclass-post-assignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignment?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107222358047647-13535%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A13%3A24Z&ske=2021-07-26T02%3A18%3A24Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-22T23%3A54%3A31Z&se=2021-08-22T23%3A59%3A31Z&sr=b&sp=r&sig=GXddKVL5OQmurrcFZQ35WGM08dBH5D%2BsLgYSihG7os0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 20:51 UTC, opbld34 commented
Docs Build status updates of commit _[8f36f70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f36f70e9deddafaba20811def490fc213df7529)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/v1.0/api/educationclass-post-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/api/educationclass-post-assignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignment?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108032046372615-13535%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=xqfTswb5qL1hsdPF%2BpKvy%2BLpRW811pdB9srXbI8jojE%3D&st=2021-08-03T20%3A46%3A57Z&se=2021-09-03T20%3A51%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 20:59 UTC, isvargasmsft commented on api-reference/v1.0/resources/educationassignmentdefaults.md
> +|addToCalendarAction| educationAddToCalendarOptions|Optional field to control adding assignments to students' and teachers' calendars when the assignment is published. Possible values are: `studentsA
API Doctor is showing an error because this enum is not available in v1 yet. Please confirm with technical reviewers, it looks like this row should be removed for v1.

2021-08-03 21:01 UTC, isvargasmsft requested changes
Please confirm whether educationAddToCalendarOptions should be removed from v1 for now.

2021-08-04 19:47 UTC, cristobal-buenrostro commented on api-reference/v1.0/resources/educationassignmentdefaults.md
> +|addToCalendarAction| educationAddToCalendarOptions|Optional field to control adding assignments to students' and teachers' calendars when the assignment is published. Possible values are: `studentsA
I don't think we should remove it, is one of the reasons of this PR... fix a typo in the description.
I suppose that need to add it into v1 too, will confirm with @sharad-sharma-msft and update accordingly

2021-08-04 20:13 UTC, opbld31 commented
Docs Build status updates of commit _[3ea7715](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ea7715a99edf0ac01be61adac6fc936321a9599)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/v1.0/api/educationclass-post-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/api/educationclass-post-assignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignment?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108042010342882-13535%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=8staqsjhIwSZ9d%2B9mS4yDZLzBT41k6MTQ07gm2RNkuA%3D&st=2021-08-04T20%3A08%3A13Z&se=2021-09-04T20%3A13%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 20:14 UTC, cristobal-buenrostro commented on api-reference/v1.0/resources/educationassignmentdefaults.md
> +|addToCalendarAction| educationAddToCalendarOptions|Optional field to control adding assignments to students' and teachers' calendars when the assignment is published. Possible values are: `studentsA
Done, removed from v1.0

2021-08-06 12:56 UTC, opbld30 commented
Docs Build status updates of commit _[c83ec8d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c83ec8d78a42d6e89e3989580d2c94afb53e5e53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/beta/resources/educationassignmentdefaults.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentdefaults?view=graph-rest-beta&branch=pr-en-us-13535) (graph-rest-beta) |
[api-reference/v1.0/api/educationclass-post-assignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21/bugs/api-reference/v1.0/api/educationclass-post-assignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignment?view=graph-rest-1.0&branch=pr-en-us-13535) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108061255163381-13535%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=B0dxxnnFgj3NNE8OKBbOblk0%2B1GUTD2C%2F1jj6GeuzjY%3D&st=2021-08-06T12%3A51%3A46Z&se=2021-09-06T12%3A56%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 13:00 UTC, isvargasmsft approved these changes
Thank you very much for your work. This is ready for final review now.

2021-08-11 01:21 UTC, merged