Azure AD B2C new step in api connectors configuration for enriching a token
microsoftgraph/microsoft-graph-docs pull request #13541
Opened 2021-07-16 13:30 UTC by nickgmicrosoft

Adding a new step that API connectors can be used from in Azure AD B2C user flows.

2021-07-16 13:33 UTC, opbld31 commented
Docs Build status updates of commit _[de35116](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de35116d5705c4b84b94839ffb414ccd4d33ebf0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-get-apiconnectorconfiguration?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/resources/userflowapiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/resources/userflowapiconnectorconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userflowapiconnectorconfiguration?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161330289149-13541%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A34%3A28Z&ske=2021-07-23T08%3A39%3A28Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T13%3A28%3A00Z&se=2021-08-16T13%3A33%3A00Z&sr=b&sp=r&sig=GXoBkHgNAX%2B%2B0Za4bRnrs20CyYVY6r1EdzQ8StRrOYY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 13:38 UTC, opbld34 commented
Docs Build status updates of commit _[378d166](https://github.com/microsoftgraph/microsoft-graph-docs/commits/378d16637931f7cd0867d494a57bf1913990c657)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-get-apiconnectorconfiguration?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/resources/userflowapiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/resources/userflowapiconnectorconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userflowapiconnectorconfiguration?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161336346577-13541%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A05%3A46Z&ske=2021-07-23T08%3A10%3A46Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T13%3A33%3A09Z&se=2021-08-16T13%3A38%3A09Z&sr=b&sp=r&sig=h45%2B7B4dIhZze85sCqiuLOjQ7erjYtA1iuRlBOJKKJE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 17:11 UTC, opbld31 commented
Docs Build status updates of commit _[6e2d8e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e2d8e8eb65c72decc67d1c026c29b55505a54b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-get-apiconnectorconfiguration?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/resources/identityapiconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/resources/identityapiconnector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityapiconnector?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/resources/userflowapiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/resources/userflowapiconnectorconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userflowapiconnectorconfiguration?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161709121850-13541%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A39%3A44Z&ske=2021-07-23T08%3A44%3A44Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T17%3A06%3A41Z&se=2021-08-16T17%3A11%3A41Z&sr=b&sp=r&sig=P04xank%2FYH6z7jKoILeVSE6AMoGcz4ynwm4GaW98uR0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 17:59 UTC, opbld31 commented
Docs Build status updates of commit _[e395d2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e395d2b163bdd5cb53fc519562735776bf341812)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-get-apiconnectorconfiguration?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-get-apiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/api/b2xidentityuserflow-get-apiconnectorconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-get-apiconnectorconfiguration?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/resources/apiauthenticationconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/resources/apiauthenticationconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/apiauthenticationconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/resources/clientcertificateauthentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/resources/clientcertificateauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/clientcertificateauthentication?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/resources/identityapiconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/resources/identityapiconnector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityapiconnector?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/resources/pkcs12CertificateInformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/resources/pkcs12CertificateInformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pkcs12certificateinformation?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/resources/userflowapiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/resources/userflowapiconnectorconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userflowapiconnectorconfiguration?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/v1.0/resources/apiauthenticationconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/v1.0/resources/apiauthenticationconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/apiauthenticationconfigurationbase?view=graph-rest-1.0&branch=pr-en-us-13541) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/clientcertificateauthentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/v1.0/resources/clientcertificateauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/clientcertificateauthentication?view=graph-rest-1.0&branch=pr-en-us-13541) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pkcs12certificateinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/v1.0/resources/pkcs12certificateinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pkcs12certificateinformation?view=graph-rest-1.0&branch=pr-en-us-13541) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108051757214417-13541%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=6qlDRv2V5SUkku%2BhLP4QEECX2q2dMA6QUrCpga9Fn7U%3D&st=2021-08-05T17%3A54%3A51Z&se=2021-09-05T17%3A59%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 18:01 UTC, opbld30 commented
Docs Build status updates of commit _[c9644bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9644bcaab42c39ca90672226eaf45b903e796bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-get-apiconnectorconfiguration?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-get-apiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/api/b2xidentityuserflow-get-apiconnectorconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-get-apiconnectorconfiguration?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/resources/apiauthenticationconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/resources/apiauthenticationconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/apiauthenticationconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/resources/clientcertificateauthentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/resources/clientcertificateauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/clientcertificateauthentication?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/resources/identityapiconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/resources/identityapiconnector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityapiconnector?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/resources/pkcs12CertificateInformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/resources/pkcs12CertificateInformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pkcs12certificateinformation?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/beta/resources/userflowapiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/beta/resources/userflowapiconnectorconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userflowapiconnectorconfiguration?view=graph-rest-beta&branch=pr-en-us-13541) (graph-rest-beta) |
[api-reference/v1.0/resources/apiauthenticationconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/v1.0/resources/apiauthenticationconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/apiauthenticationconfigurationbase?view=graph-rest-1.0&branch=pr-en-us-13541) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/clientcertificateauthentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/v1.0/resources/clientcertificateauthentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/clientcertificateauthentication?view=graph-rest-1.0&branch=pr-en-us-13541) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pkcs12certificateinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/api-reference/v1.0/resources/pkcs12certificateinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pkcs12certificateinformation?view=graph-rest-1.0&branch=pr-en-us-13541) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/b2ctokenaug-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108051759161563-13541%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=qTnt%2FNZ726V%2BL%2FbhpP2j%2Fev4od1CZJ6oKzxWP7S3qD8%3D&st=2021-08-05T17%3A56%3A28Z&se=2021-09-05T18%3A01%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-13 18:52 UTC, FaithOmbongi requested changes
- Proposed fixes.
- NOTE: I believe these 2 files ( [1](api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md), [2](api-reference/beta/api/b2xidentityuserflow-get-apiconnectorconfiguration.md) ) shouldn't exist because apiConnectorConfiguration is not a nav property of b2c/b2xIdentityUserFlow. And if it were, the files would be a -list-*.md.
            - The file can stay for this PR because it has useful info that should be transferred to the relevant files; but, let's chat internally to get the docs in line with the guidance.

2021-08-13 18:52 UTC, FaithOmbongi commented on api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md
> +GET https://graph.microsoft.com/beta/identity/b2cUserFlows/B2C_1_testuserflow/apiConnectorConfiguration?$expand=postFederationSignup,postAttributeCollection,preTokenIssuance
- Delete the **# [HTTP](#tab/http)** header in Line 68. It goes hand-in-hand with the snippets.

2021-08-13 18:52 UTC, FaithOmbongi commented on api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md
> +        "targetUrl": "https://someapi.com/api/postidp",
Global: Updating to an approved domain name.
```suggestion
        "targetUrl": "https://contoso.com/api/postidp",
```

2021-08-13 18:52 UTC, FaithOmbongi commented on api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md
> +        "targetUrl": "https://someapi.com/api/attributecollection",
```suggestion
        "targetUrl": "https://contoso.com/api/attributecollection",
```

2021-08-13 18:52 UTC, FaithOmbongi commented on api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md
> +        "targetUrl": "https://someapi.com/api/tokenaug",
```suggestion
        "targetUrl": "https://contoso.com/api/tokenaug",
```

2021-08-13 18:52 UTC, FaithOmbongi commented on api-reference/beta/api/b2xidentityuserflow-get-apiconnectorconfiguration.md
>          "targetUrl": "https://someotherapi.com/api/endpoint",
```suggestion
        "targetUrl": "https://contoso.com/api/endpoint",
```

2021-08-13 18:52 UTC, FaithOmbongi commented on api-reference/beta/resources/clientcertificateauthentication.md
> +A type derived from apiAuthenticationConfigurationBase which is used to represent Pkcs12 based client certificate authentication in "Get" and "List" operations. This type represents the public proper
Removing the List/Get statement because they are not queried against this complex type rather, objects of this type are returned in identityApiConnector objects.
```suggestion
A type derived from [apiAuthenticationConfigurationBase](apiauthenticationconfigurationbase.md) object. The client certificate authentication object represents the public properties of uploaded Pkcs12-based certificates for an API connector.
```

2021-08-13 18:52 UTC, FaithOmbongi commented on api-reference/beta/resources/pkcs12CertificateInformation.md
>  |notBefore|Integer| The certificate's issue time (not before). This value is a NumericDate as defined in RFC 7519 (A JSON numeric value representing the number of seconds from 1970-01-01T00:00:00Z UT
```suggestion
|notAfter|Int64| The certificate's expiry. This value is a NumericDate as defined in RFC 7519 (A JSON numeric value representing the number of seconds from 1970-01-01T00:00:00Z UTC until the specified UTC date/time, ignoring leap seconds.)|
|notBefore|Int64| The certificate's issue time (not before). This value is a NumericDate as defined in RFC 7519 (A JSON numeric value representing the number of seconds from 1970-01-01T00:00:00Z UTC until the specified UTC date/time, ignoring leap seconds.)|
```

2021-08-13 18:52 UTC, FaithOmbongi commented on api-reference/beta/resources/pkcs12CertificateInformation.md
> +|isActive|Boolean|  Represents whether the certificate is the active certificate to be used for calling the target URL of an API connector. The active certificate is the oldest uploaded certificate w
oldest vs most recently uploaded cert. Kindly confirm.

2021-08-13 18:52 UTC, FaithOmbongi commented on api-reference/v1.0/resources/clientcertificateauthentication.md
> +A type derived from apiAuthenticationConfigurationBase which is used to represent Pkcs12 based client certificate authentication in "Get" and "List" operations. This type represents the public proper
Same principle as in the beta file.
```suggestion
A type derived from [apiAuthenticationConfigurationBase](apiauthenticationconfigurationbase.md) object. The client certificate authentication object represents the public properties of uploaded Pkcs12-based certificates for an API connector.
```

2021-08-13 18:52 UTC, FaithOmbongi commented on api-reference/v1.0/resources/pkcs12certificateinformation.md
> +|isActive|Boolean|  Represents whether the certificate is the active certificate to be used for calling the target URL of an API connector. The active certificate is the oldest uploaded certificate w
Same Q: oldest vs most recently uploaded.

2021-08-13 18:52 UTC, FaithOmbongi commented on api-reference/v1.0/resources/pkcs12certificateinformation.md
> +    "notBefore": 0000000000,
```suggestion
    "isActive": true,
    "thumbprint": "String",
    "notAfter": "Integer",
    "notBefore": "Integer",
```

2021-08-13 18:52 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +    },
Applying the [changelog guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog).
```suggestion
    {
      "ChangeList": [
        {
          "Id": "b3878d32-120c-4469-9ab0-b524a2eb6f79",
          "ApiChange": "Property",
          "ChangedApiName": "preTokenIssuance",
          "ChangeType": "Addition",
          "Description": "Added the **preTokenIssuance** property to the [userFlowApiConnectorConfiguration](https://docs.microsoft.com/graph/api/resources/userflowapiconnectorconfiguration?view=graph-rest-beta&preserve-view=true) resource. This property represents a new step that can be used to enrich tokens in Azure AD B2C user flows.",
          "Target": "userFlowApiConnectorConfiguration"
        }
      ],
      "Id": "b3878d32-120c-4469-9ab0-b524a2eb6f79",
      "Cloud": "prd",
      "Version": "beta",
      "CreatedDateTime": "2021-08-13T16:50:00Z",
      "WorkloadArea": "Identity and access",
      "SubArea": "Identity and sign-in"
    },
```

2021-12-02 06:35 UTC, FaithOmbongi commented
Heads up @nickgmicrosoft, please address the review feedback and get this PR into a mergeable state. Thanks.

2021-12-17 14:58 UTC, isvargasmsft commented
@nickgmicrosoft, what's the status of this PR?

2022-05-04 15:00 UTC, closed without merging