Noninteractivesignindatetime Graph update
microsoftgraph/microsoft-graph-docs pull request #13577
Opened 2021-07-20 03:43 UTC by besiler

Added info for noninteractivesignindatetime to signinactivity resource, as well as info on how the new resource to list users

2021-07-20 03:44 UTC, opbld33 commented
Docs Build status updates of commit _[5354bed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5354bedb18483f2a112daefeb3becb8fcf7526bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-13577) (graph-rest-beta) |
[api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/api-reference/beta/resources/signinactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta&branch=pr-en-us-13577) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107200343135983-13577%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A19%3A18Z&ske=2021-07-26T02%3A24%3A18Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-20T03%3A39%3A56Z&se=2021-08-20T03%3A44%3A56Z&sr=b&sp=r&sig=LDTD2Af5VewgC9TF%2Fs3vbRh4bnScpKGgu%2BWwl9olrnQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-29 21:15 UTC, opbld34 commented
Docs Build status updates of commit _[4929e38](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4929e38c41d6e8b860c3643d91353e24b476dfac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-13577) (graph-rest-beta) |
[api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/api-reference/beta/resources/signinactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta&branch=pr-en-us-13577) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107292114037960-13577%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T04%3A20%3A50Z&ske=2021-08-04T04%3A25%3A50Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-29T21%3A10%3A31Z&se=2021-08-29T21%3A15%3A31Z&sr=b&sp=r&sig=fcsoLlgeUCP2tiTqrD6%2BS9hP0VI3oV39Ss8D%2F7xWrKY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-29 21:20 UTC, opbld34 commented
Docs Build status updates of commit _[9bcd423](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9bcd423dec427689cd129c86a7e028af24c3e534)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-13577) (graph-rest-beta) |
[api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/api-reference/beta/resources/signinactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta&branch=pr-en-us-13577) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107292118352031-13577%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T04%3A18%3A34Z&ske=2021-08-04T04%3A23%3A34Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-29T21%3A15%3A04Z&se=2021-08-29T21%3A20%3A04Z&sr=b&sp=r&sig=uxDOeb2dKymvYTuZwZQzyryvi5TDNAQ92x5ydgF62Hk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-30 17:36 UTC, opbld34 commented
Docs Build status updates of commit _[964b836](https://github.com/microsoftgraph/microsoft-graph-docs/commits/964b83670b5435e4e42bde71c945db52685970a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-13577) (graph-rest-beta) |
[api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/api-reference/beta/resources/signinactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta&branch=pr-en-us-13577) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107301731040002-13577%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-30T06%3A12%3A02Z&ske=2021-08-06T06%3A17%3A02Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-30T17%3A31%3A41Z&se=2021-08-30T17%3A36%3A41Z&sr=b&sp=r&sig=aF4Q47R4T7ezM9mwjM9wMQ%2FWFHYBkI9yoiVVsosumcE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-02 09:35 UTC, FaithOmbongi requested changes
Proposed minor fixes.
Asking a Q to request for clarification internally.

2021-08-02 09:35 UTC, FaithOmbongi commented on api-reference/beta/resources/signinactivity.md
> +|lastNonInteractiveSignInRequestId|String|Request ID of the last non-interactive sign-in performed by this user.|
```suggestion
|lastSignInRequestId|String|Request identifier of the last interactive sign-in performed by this user.|
|lastNonInteractiveSignInDateTime|DateTimeOffset|The last non-interactive sign-in date for a specific user. You can use this field to calculate the last time a client signed in to the directory on behalf of a user. Because some users may use clients to access tenant resources rather than signing into your tenant directly, you can use the non-interactive sign-in date to along with lastSignInDateTime to identify inactive users. The timestamp represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is: `'2014-01-01T00:00:00Z'`. For more information about using the value of this property, see [Manage inactive user accounts in Azure AD](/azure/active-directory/reports-monitoring/howto-manage-inactive-user-accounts).|
|lastNonInteractiveSignInRequestId|String|Request identifier of the last non-interactive sign-in performed by this user.|
```

2021-08-02 09:35 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +            "Description": "Added the **lastNonInteractiveSignInRequestId** property to [signInActivity](https://docs.microsoft.com/en-us/graph/api/resources/signInActivity?view=graph-rest-beta) reso
```suggestion
            "Description": "Added the **lastNonInteractiveSignInDateTime** property to the [signInActivity](https://docs.microsoft.com/en-us/graph/api/resources/signInActivity?view=graph-rest-beta) resource.",
            "Target": "signInActivity"
          },
          {
            "Id": "8e343c2f-6145-40fe-8d23-80914c7f036e",
            "ApiChange": "Property",
            "ChangedApiName": "lastNonInteractiveSignInRequestId",
            "ChangeType": "Addition",
            "Description": "Added the **lastNonInteractiveSignInRequestId** property to the [signInActivity](https://docs.microsoft.com/en-us/graph/api/resources/signInActivity?view=graph-rest-beta) resource.",
```

2021-08-05 00:08 UTC, opbld33 commented
Docs Build status updates of commit _[25d6f26](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25d6f2641476e169d9b5bb4db7e6be3217c6f4b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-13577) (graph-rest-beta) |
[api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/api-reference/beta/resources/signinactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta&branch=pr-en-us-13577) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108050005495189-13577%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=eE8RyQRZXrVVmaO8vii4VGeEzUxyAHcYX79eFLJUfqs%3D&st=2021-08-05T00%3A03%3A18Z&se=2021-09-05T00%3A08%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 00:10 UTC, opbld33 commented
Docs Build status updates of commit _[d7f9c81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d7f9c81e69369173b6ab239bc51e75b05883ca40)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-13577) (graph-rest-beta) |
[api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/api-reference/beta/resources/signinactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta&branch=pr-en-us-13577) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108050006072257-13577%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=XNHhyPz3JCQ7VLKWXnUcatgiuCHSxZu885M61UijqjE%3D&st=2021-08-05T00%3A05%3A00Z&se=2021-09-05T00%3A10%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 06:13 UTC, FaithOmbongi approved these changes

2021-08-17 17:33 UTC, besiler commented
Marked as "Ready to merge" based on a convo with @FaithOmbongi

2021-08-18 01:29 UTC, opbld33 commented
Docs Build status updates of commit _[33b0891](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33b08915c9e3495e7031ba6dbed7ec6fed984559)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-13577) (graph-rest-beta) |
[api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/api-reference/beta/resources/signinactivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta&branch=pr-en-us-13577) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-07-16-besiler-BenT/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108180127444093-13577%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Ae3uqowfILOy4WPVTcPfOejyfARrzpcayDurZcClFL0%3D&st=2021-08-18T01%3A24%3A27Z&se=2021-09-18T01%3A29%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-18 01:45 UTC, merged