Update table-post-rows.md
microsoftgraph/microsoft-graph-docs pull request #13598
Opened 2021-07-21 06:00 UTC by grangeryy

add another example using async mode for add table row in excel.

2021-07-21 06:01 UTC, opbld31 commented
Docs Build status updates of commit _[9421503](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9421503d8f062a31a84a4af6a1a7d8b70c1cb78a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-051c86df)

<a id="e082c22528d72aeb73c0952d6d11ea99-051c86df"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 61, Column 63**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/workbooktablerow.md'.`````
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 181, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 268, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approach would be to batch the rows together in a single call rather than doing single row insertion. For best results, collect the rows to be inserted on the application side and perform single rows add operation. Experiment with the number of rows to determine the ideal number of rows to use in single API call. ' is duplicated in 'v1.0/api/table-post-rows.md(3,14)', 'v1.0/api/tablerowcollection-add.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107210600116111-13598%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-20T05%3A42%3A45Z&ske=2021-07-27T05%3A47%3A45Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-21T05%3A56%3A44Z&se=2021-08-21T06%3A01%3A44Z&sr=b&sp=r&sig=DZEOdLlRgN72dz3zcMpzkQWK0h9gs948XgPwtZ5bCxc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-21 06:06 UTC, opbld31 commented
Docs Build status updates of commit _[b2484c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b2484c712b197eb25749cd91aef6f8f1c8f7adf1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-d9934326)
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-d9934326)

<a id="3d4ef16248555d21d47f9f4aef494875-d9934326"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 181, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 268, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="e082c22528d72aeb73c0952d6d11ea99-d9934326"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 61, Column 63**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/workbooktablerow.md'.`````
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 181, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 268, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approach would be to batch the rows together in a single call rather than doing single row insertion. For best results, collect the rows to be inserted on the application side and perform single rows add operation. Experiment with the number of rows to determine the ideal number of rows to use in single API call. ' is duplicated in 'v1.0/api/table-post-rows.md(3,14)', 'v1.0/api/tablerowcollection-add.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107210604317984-13598%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A27%3A45Z&ske=2021-07-26T03%3A32%3A45Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-21T06%3A01%3A07Z&se=2021-08-21T06%3A06%3A07Z&sr=b&sp=r&sig=FX6cyX5pa9IrlTSMjUTil00peCCHEZ2gsSkwS0JAsRQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-21 06:07 UTC, opbld30 commented
Docs Build status updates of commit _[60a77aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60a77aa418e8e93f540bc557e3484351f7259cec)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-c4e26d0d)
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-c4e26d0d)

<a id="3d4ef16248555d21d47f9f4aef494875-c4e26d0d"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 181, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 268, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="e082c22528d72aeb73c0952d6d11ea99-c4e26d0d"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 61, Column 63**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/workbooktablerow.md'.`````
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 181, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 268, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approach would be to batch the rows together in a single call rather than doing single row insertion. For best results, collect the rows to be inserted on the application side and perform single rows add operation. Experiment with the number of rows to determine the ideal number of rows to use in single API call. ' is duplicated in 'v1.0/api/table-post-rows.md(3,14)', 'v1.0/api/tablerowcollection-add.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107210605315006-13598%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A35%3A03Z&ske=2021-07-26T03%3A40%3A03Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-21T06%3A02%3A46Z&se=2021-08-21T06%3A07%3A46Z&sr=b&sp=r&sig=pBkUNrWjhFdtnFTRSq1b0DN8K%2BhzUHzF1N0rNhIfNaY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-21 06:13 UTC, opbld33 commented
Docs Build status updates of commit _[6f9888f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f9888fe87c2ab4a14818b5691f3bf4a9754cd9e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-eb1cf0e8)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-eb1cf0e8)
[api-reference/v1.0/resources/table.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/table.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/table?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-2f7fe791c2705513c5d73e04d171bfed-eb1cf0e8)
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-eb1cf0e8"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 181, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 268, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-eb1cf0e8"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/toc.yml)
 - **Line 6511, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/table-post-rows.md'.`````

<a id="2f7fe791c2705513c5d73e04d171bfed-eb1cf0e8"></a>
### [api-reference/v1.0/resources/table.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/table.md)
 - **Line 24, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/table-post-rows.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107210612059572-13598%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A41%3A54Z&ske=2021-07-26T02%3A46%3A54Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-21T06%3A08%3A39Z&se=2021-08-21T06%3A13%3A39Z&sr=b&sp=r&sig=aT2k3OrjNG%2FvkI5gLu06GP5tqAX7mW3Pqd58qml%2BuQc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-21 06:34 UTC, opbld33 commented
Docs Build status updates of commit _[7cf0205](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7cf0205b01f1b12ed6ea18751b8ae323d4176510)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-84777dbb)

<a id="3d4ef16248555d21d47f9f4aef494875-84777dbb"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 181, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 268, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107210632487878-13598%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A39%3A52Z&ske=2021-07-26T02%3A44%3A52Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-21T06%3A29%3A32Z&se=2021-08-21T06%3A34%3A32Z&sr=b&sp=r&sig=vStz7FH1YQvUIrEk0dU0uW9%2FsaYD9PaVhZOUT0TeQy4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-22 03:48 UTC, Lauragra commented on api-reference/beta/api/table-post-rows.md
> +POST https://graph.microsoft.com/beta/me/drive/items/{id}/workbook/tables/{id|name}/rows
Examples are more helpful in general if you include actual values instead of placeholders for the IDs.

2021-07-22 03:49 UTC, opbld34 commented
Docs Build status updates of commit _[24ccdb3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24ccdb30ea73370a960ddc20494d6f29b710990c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107220347105968-13598%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A37%3A59Z&ske=2021-07-26T02%3A42%3A59Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-22T03%3A44%3A12Z&se=2021-08-22T03%3A49%3A12Z&sr=b&sp=r&sig=aoN0LQJh7NBOs7y6bRUGLh4POGkE55CEqjUFlV2xg0w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-22 03:53 UTC, Lauragra commented on api-reference/beta/api/table-post-rows.md
> +#### 2. Poll the URL at last response header called the location property
By this do you mean, poll the URL in the Location header in the response?

2021-07-22 03:55 UTC, opbld34 commented
Docs Build status updates of commit _[f4655e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4655e635c6d22bd5d94c6e823de6d96a917c059)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107220353523832-13598%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A27%3A45Z&ske=2021-07-26T03%3A32%3A45Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-22T03%3A50%3A28Z&se=2021-08-22T03%3A55%3A28Z&sr=b&sp=r&sig=DNmLkqTSua59E5J25aoILlEjTPjswB0pP7uBVL7BPWA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-22 04:01 UTC, Lauragra requested changes
Please take a look at the API Doctor errors related to the examples and make sure that the examples are valid. Thanks.

2021-07-22 07:49 UTC, crazygao commented on api-reference/beta/api/table-post-rows.md
> +POST https://graph.microsoft.com/beta/me/drive/items/{id}/workbook/tables/{id|name}/rows
Agree

2021-07-22 07:50 UTC, crazygao commented on api-reference/beta/api/table-post-rows.md
> +#### 2. Poll the URL at last response header called the location property
Yes, that's the point. Just the URL a line 165.

2021-07-22 07:52 UTC, crazygao commented on api-reference/beta/api/table-post-rows.md
> +GET https://graph.microsoft.com/beta/me/drive/items/{id}/workbook/tableRowOperationResult(key={id})?sessionId={id}
This url is the same with the one at line 253

2021-07-22 08:37 UTC, opbld30 commented
Docs Build status updates of commit _[ff375f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff375f7de570ec5d3ad2f7310662d3a063c46e23)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-b771286b)
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |

<a id="e082c22528d72aeb73c0952d6d11ea99-b771286b"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 61, Column 63**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/workbooktablerow.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approach would be to batch the rows together in a single call rather than doing single row insertion. For best results, collect the rows to be inserted on the application side and perform single rows add operation. Experiment with the number of rows to determine the ideal number of rows to use in single API call. ' is duplicated in 'v1.0/api/table-post-rows.md(3,14)', 'v1.0/api/tablerowcollection-add.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107220835287815-13598%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-20T23%3A05%3A54Z&ske=2021-07-27T23%3A10%3A54Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-22T08%3A32%3A00Z&se=2021-08-22T08%3A37%3A00Z&sr=b&sp=r&sig=9pnZqAWrixbh7M3ogmdTd%2BnKtU9MWoMlqCz0cxhjRt4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-29 06:17 UTC, grangeryy commented on api-reference/beta/api/table-post-rows.md
> +POST https://graph.microsoft.com/beta/me/drive/items/{id}/workbook/tables/{id|name}/rows
Done

2021-08-04 09:31 UTC, opbld30 commented
Docs Build status updates of commit _[be95a45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be95a455bbb97a828ca94e778cae5a23033f9fa6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-cd7b01c0)
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |

<a id="e082c22528d72aeb73c0952d6d11ea99-cd7b01c0"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 61, Column 63**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/workbooktablerow.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approach would be to batch the rows together in a single call rather than doing single row insertion. For best results, collect the rows to be inserted on the application side and perform single rows add operation. Experiment with the number of rows to determine the ideal number of rows to use in single API call. ' is duplicated in 'v1.0/api/table-post-rows.md(3,14)', 'v1.0/api/tablerowcollection-add.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108040929294290-13598%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=TQt3uIoE%2FiTv9Rnldv5ytbf5reIE2J0WATeeSL2ipRQ%3D&st=2021-08-04T09%3A26%3A48Z&se=2021-09-04T09%3A31%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 06:57 UTC, opbld30 commented
Docs Build status updates of commit _[2df38d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2df38d0ec278e5fffee0fdd43d2011f4d3360d12)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-0cb7ed12)
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="e082c22528d72aeb73c0952d6d11ea99-0cb7ed12"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 61, Column 63**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/workbooktablerow.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approach would be to batch the rows together in a single call rather than doing single row insertion. For best results, collect the rows to be inserted on the application side and perform single rows add operation. Experiment with the number of rows to determine the ideal number of rows to use in single API call. ' is duplicated in 'v1.0/api/table-post-rows.md(3,14)', 'v1.0/api/tablerowcollection-add.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108060656042770-13598%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=e5TxwQTdVYf%2B8XzEn8n0n5b6ffaJHCD1T2%2B999O2sH4%3D&st=2021-08-06T06%3A52%3A33Z&se=2021-09-06T06%3A57%3A33Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-09 08:01 UTC, opbld30 commented
Docs Build status updates of commit _[59f8d9e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/59f8d9ed8c10d4ed5786ce1063e9cca7a76c6ae7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-99cde500)
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="e082c22528d72aeb73c0952d6d11ea99-99cde500"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 61, Column 63**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/workbooktablerow.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approach would be to batch the rows together in a single call rather than doing single row insertion. For best results, collect the rows to be inserted on the application side and perform single rows add operation. Experiment with the number of rows to determine the ideal number of rows to use in single API call. ' is duplicated in 'v1.0/api/table-post-rows.md(3,14)', 'v1.0/api/tablerowcollection-add.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108090800027750-13598%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=OCgMn0HHYlOg0k7UVrZKQKn1n8utc7xBZqnrapQIOPU%3D&st=2021-08-09T07%3A56%3A34Z&se=2021-09-09T08%3A01%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-09 08:32 UTC, opbld32 commented
Docs Build status updates of commit _[8a97a28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a97a286d37808ca0bfdbf0bf81caa70037be47b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-eef97186)
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="e082c22528d72aeb73c0952d6d11ea99-eef97186"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 54, Column 68**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../../beta/resources/tablerow.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approach would be to batch the rows together in a single call rather than doing single row insertion. For best results, collect the rows to be inserted on the application side and perform single rows add operation. Experiment with the number of rows to determine the ideal number of rows to use in single API call. ' is duplicated in 'v1.0/api/table-post-rows.md(3,14)', 'v1.0/api/tablerowcollection-add.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108090830298279-13598%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Z240mN44Zj32JBWUG%2BwmyVL9bggKapBEFPZSgE%2FU2%2FE%3D&st=2021-08-09T08%3A27%3A01Z&se=2021-09-09T08%3A32%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-09 09:05 UTC, opbld32 commented
Docs Build status updates of commit _[e58bdf6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e58bdf6776e4e223e935923aa612e3ce26832781)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-5cd696cf)
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="e082c22528d72aeb73c0952d6d11ea99-5cd696cf"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approach would be to batch the rows together in a single call rather than doing single row insertion. For best results, collect the rows to be inserted on the application side and perform single rows add operation. Experiment with the number of rows to determine the ideal number of rows to use in single API call. ' is duplicated in 'v1.0/api/table-post-rows.md(3,14)', 'v1.0/api/tablerowcollection-add.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108090903249218-13598%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=nS7DRM7UBEypT2vrHeEWphEUWSejeiBXBy5QHdYVC2M%3D&st=2021-08-09T09%3A00%3A53Z&se=2021-09-09T09%3A05%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-10 11:21 UTC, opbld32 commented
Docs Build status updates of commit _[04354c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04354c94515ea9c6edf59de680d2efe121fb8445)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-9a7e78f1)
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/tablerowoperationresult-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/tablerowoperationresult-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowoperationresult-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="e082c22528d72aeb73c0952d6d11ea99-9a7e78f1"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approach would be to batch the rows together in a single call rather than doing single row insertion. For best results, collect the rows to be inserted on the application side and perform single rows add operation. Experiment with the number of rows to determine the ideal number of rows to use in single API call. ' is duplicated in 'v1.0/api/table-post-rows.md(3,14)', 'v1.0/api/tablerowcollection-add.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108101120132725-13598%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=T1g81PvlQtSgo60CIplYKQN%2BFnlU%2BfRutyMc5oV3TKQ%3D&st=2021-08-10T11%3A16%3A45Z&se=2021-09-10T11%3A21%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 05:25 UTC, grangeryy reviewed
Done

2021-08-13 06:53 UTC, crazygao approved these changes

2021-08-14 01:35 UTC, opbld32 commented
Docs Build status updates of commit _[dcc084e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dcc084e8dc5a201806c3471b2befa81ce3895234)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-ec4898e9)
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/tablerowoperationresult-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/tablerowoperationresult-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowoperationresult-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="e082c22528d72aeb73c0952d6d11ea99-ec4898e9"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approach would be to batch the rows together in a single call rather than doing single row insertion. For best results, collect the rows to be inserted on the application side and perform single rows add operation. Experiment with the number of rows to determine the ideal number of rows to use in single API call. ' is duplicated in 'v1.0/api/table-post-rows.md(3,14)', 'v1.0/api/tablerowcollection-add.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108140134195607-13598%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=L7XXhwwTYVD4JqXKKe9zM9I4GTxomEycnNWEEnUWzLs%3D&st=2021-08-14T01%3A30%3A40Z&se=2021-09-14T01%3A35%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-14 01:46 UTC, Lauragra commented on api-reference/beta/api/tablerowoperationresult-get.md
> +Get the async operation result for create TableRow [Get workbookOperation](./workbookoperation-get.md), after you get a `succeeded` **operationStatus** result and it indicates that you can get the re
Why does the description mention two operations - Create tableRow and Get workbookOperation? Please make the introductory sentence more clear.

2021-08-14 01:46 UTC, opbld32 commented
Docs Build status updates of commit _[a2589d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2589d57b21665abe46499ab073403e567b4ceaa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-b3df43aa)
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/tablerowoperationresult-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/tablerowoperationresult-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowoperationresult-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="e082c22528d72aeb73c0952d6d11ea99-b3df43aa"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approach would be to batch the rows together in a single call rather than doing single row insertion. For best results, collect the rows to be inserted on the application side and perform single rows add operation. Experiment with the number of rows to determine the ideal number of rows to use in single API call. ' is duplicated in 'v1.0/api/table-post-rows.md(3,14)', 'v1.0/api/tablerowcollection-add.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108140145400620-13598%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=oOw%2FVXKQWqX2TrxDDPsQqWZy3NuPwbs78XJlqW0KRuA%3D&st=2021-08-14T01%3A41%3A58Z&se=2021-09-14T01%3A46%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-14 01:48 UTC, opbld32 commented
Docs Build status updates of commit _[c287188](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c28718898f8cde301c76667b5b496fdf879d11d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-ade338a3)
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/tablerowoperationresult-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/tablerowoperationresult-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowoperationresult-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="e082c22528d72aeb73c0952d6d11ea99-ade338a3"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approach would be to batch the rows together in a single call rather than doing single row insertion. For best results, collect the rows to be inserted on the application side and perform single rows add operation. Experiment with the number of rows to determine the ideal number of rows to use in single API call. ' is duplicated in 'v1.0/api/table-post-rows.md(3,14)', 'v1.0/api/tablerowcollection-add.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108140147116048-13598%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=dayF9Ctbgme09WBaTiwwmgeELnKPYWBv3L53fPZqrv4%3D&st=2021-08-14T01%3A43%3A32Z&se=2021-09-14T01%3A48%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-14 01:54 UTC, Lauragra commented on api-reference/beta/api/tablerowoperationresult-get.md
> +|Authorization|Bearer {token}. Optional.|
Confirm that this is optional? It's generally required.

2021-08-14 01:55 UTC, Lauragra commented on api-reference/beta/api/tablerowoperationresult-get.md
> +## Function parameters
This is a CRUD operation, not a function, right? Confirm that function parameters apply here?

2021-08-14 02:54 UTC, Lauragra commented on api-reference/beta/api/tablerowoperationresult-get.md
> +If successful, this function returns a `200 OK` response code and a [workbookTableRow](../resources/workbooktablerow.md) object in the response body.
Here we're referring to this as a function but it's a CRUD operation, right?

2021-08-14 02:56 UTC, Lauragra commented on api-reference/beta/api/workbookoperation-get.md
> +GET https://graph.microsoft.com/beta/me/drive/items/{drive-item-id}/workbook/operations/{operation-id}?sessionId={id}
Do you need to mention this sessionId in a parameters section? If you update examples, you should remove the snippet links so the SDK snippets can get regenerated.

2021-08-14 03:06 UTC, opbld30 commented
Docs Build status updates of commit _[7b69e1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b69e1e91911748b025edd9abfd96951fa8e9a0e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-b8748046)
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/tablerowoperationresult-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/tablerowoperationresult-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowoperationresult-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="e082c22528d72aeb73c0952d6d11ea99-b8748046"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approach would be to batch the rows together in a single call rather than doing single row insertion. For best results, collect the rows to be inserted on the application side and perform single rows add operation. Experiment with the number of rows to determine the ideal number of rows to use in single API call. ' is duplicated in 'v1.0/api/table-post-rows.md(3,14)', 'v1.0/api/tablerowcollection-add.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108140304310003-13598%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=%2Bt3GZVPtXOVwu09wwDZJqxD4vXhnpgi8T8ReEcZgx%2BE%3D&st=2021-08-14T03%3A01%3A14Z&se=2021-09-14T03%3A06%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-14 03:08 UTC, opbld32 commented
Docs Build status updates of commit _[2a0c602](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a0c6029aebc148c0422e30d54ad2c484121e5dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/tablerowoperationresult-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/tablerowoperationresult-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowoperationresult-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108140306461576-13598%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=JUtjHM%2F0bw7i1mhNADtkvcA6qynaLv%2B6GogbwfCIDX8%3D&st=2021-08-14T03%3A03%3A06Z&se=2021-09-14T03%3A08%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-16 03:02 UTC, crazygao commented on api-reference/beta/api/tablerowoperationresult-get.md
> +|Authorization|Bearer {token}. Optional.|
Sorry, I mark the wrong item.

2021-08-16 03:03 UTC, crazygao commented on api-reference/beta/api/tablerowoperationresult-get.md
> +## Function parameters
No, this is a Function not a CRUD operation. This structure is automatically generated by the graph studio tool.

2021-08-16 03:05 UTC, crazygao commented on api-reference/beta/api/tablerowoperationresult-get.md
> +If successful, this function returns a `200 OK` response code and a [workbookTableRow](../resources/workbooktablerow.md) object in the response body.
No, this is a function, please refer to this piece of completed PR https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/4582497. I'm also author of that PR.

2021-08-16 07:25 UTC, crazygao commented on api-reference/beta/api/workbookoperation-get.md
> +GET https://graph.microsoft.com/beta/me/drive/items/{drive-item-id}/workbook/operations/{operation-id}?sessionId={id}
Sorry, can I know if there is documentations to author SDK snippets?

Actually this api usage is very limited, this is part of async operations, async operation often consist of 2-3 sequential operations. A similar published api is https://docs.microsoft.com/en-us/graph/workbook-best-practice.

This operation is returned when invoke "addTableRow" or "createSession" graph api is called asynchornouslly, the server will give users the operation url in this form, we expect the user use the URL without any truncation.

Not only this operation, the "sessionInfoResource" and "tableRowOperationResult" url also come in this form。

2021-08-16 07:29 UTC, crazygao commented on api-reference/beta/api/tablerowoperationresult-get.md
> +Get the async operation result for create TableRow [Get workbookOperation](./workbookoperation-get.md), after you get a `succeeded` **operationStatus** result and it indicates that you can get the re
Thanks. Sorry for my bad wording. This url is meaningless by itself, it is only valid when these 3 urls combine together and form an "async createTableRow" scenario.

I'll make changes

2021-08-17 06:05 UTC, crazygao commented on api-reference/beta/api/workbookoperation-get.md
> +GET https://graph.microsoft.com/beta/me/drive/items/{drive-item-id}/workbook/operations/{operation-id}?sessionId={id}
I can remove this part, but I'm afraid that automatically generated code doesn't fit to user scenario.

2021-08-17 06:12 UTC, crazygao commented on api-reference/beta/api/tablerowoperationresult-get.md
> +If successful, this function returns a `200 OK` response code and a [workbookTableRow](../resources/workbooktablerow.md) object in the response body.
And here is a documentation for design review, I put it here just for reference

2021-08-17 09:06 UTC, opbld34 commented
Docs Build status updates of commit _[60d332f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60d332f55db7cba07843601a1a811fe42687c2d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/tablerowoperationresult-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/tablerowoperationresult-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowoperationresult-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108170904525053-13598%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=T56Gm0KRWwPB0xDyqOZb6ijRGmCFA21irNlI%2FEi5ytk%3D&st=2021-08-17T09%3A01%3A25Z&se=2021-09-17T09%3A06%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-18 05:41 UTC, crazygao approved these changes

2021-08-18 05:46 UTC, crazygao requested changes

2021-08-18 05:46 UTC, crazygao commented on api-reference/v1.0/api/table-post-rows.md
> -description: "Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approa
This change is not intended. Will change in the future

2021-08-18 08:55 UTC, crazygao commented on api-reference/v1.0/api/table-post-rows.md
> -description: "Adds rows to the end of the table. Note that the API can accept multiple rows data using this API. Adding one row at a time could lead to performance degradation. The recommended approa
We are going to publish beta and v1.0 at the same time. So I will join both documentation here.

2021-08-18 09:27 UTC, opbld32 commented
Docs Build status updates of commit _[cb37a96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb37a96c31fb5c1ad19fef19f4908d4b0f61df2b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-1b97fcdc)
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-1b97fcdc)
[api-reference/beta/api/tablerowoperationresult-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/tablerowoperationresult-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowoperationresult-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/tablerowoperationresult-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowoperationresult-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowoperationresult-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/tablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/tablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tablerow?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-1b97fcdc"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="e082c22528d72aeb73c0952d6d11ea99-1b97fcdc"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 132, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108180925442848-13598%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=xFf%2FPpXeX%2F4EMFSqjft6%2FNGBbugK85ikvK0u6vyW7Sc%3D&st=2021-08-18T09%3A22%3A26Z&se=2021-09-18T09%3A27%3A26Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-18 22:37 UTC, opbld32 commented
Docs Build status updates of commit _[6a4e41d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a4e41de6067ae632e254098eb0342479bb2557f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-b4ac3c88)
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-b4ac3c88)
[api-reference/beta/api/tablerowoperationresult-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/tablerowoperationresult-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowoperationresult-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/tablerowoperationresult-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowoperationresult-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowoperationresult-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/tablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/tablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tablerow?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-b4ac3c88"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 132, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="e082c22528d72aeb73c0952d6d11ea99-b4ac3c88"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 132, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108182235505481-13598%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=e5NEsNOJImtIibRXT%2BstnTAK%2BhXWSVQUPoBS9VL%2Fqkw%3D&st=2021-08-18T22%3A32%3A13Z&se=2021-09-18T22%3A37%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-19 03:06 UTC, crazygao approved these changes

2021-08-25 02:55 UTC, Lauragra commented on api-reference/beta/api/tablerowoperationresult-get.md
> +If successful, this function returns a `200 OK` response code and a [workbookTableRow](../resources/workbooktablerow.md) object in the response body.
In that case, this topic needs to follow the guidelines for function topics. The file name should be workbook-tablerowoperationresult, and the title should be "workbook: tableRowOperationResult".

2021-08-25 09:00 UTC, crazygao commented on api-reference/beta/api/tablerowoperationresult-get.md
> +If successful, this function returns a `200 OK` response code and a [workbookTableRow](../resources/workbooktablerow.md) object in the response body.
Thanks, I changed the title and the name following previous naming conventions. I'll change them back.

2021-08-25 09:08 UTC, opbld30 commented
Docs Build status updates of commit _[ef71018](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ef710181eb8928be08c56ccbd30e3f3a58fdaf7e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-93817995)
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-93817995)
[api-reference/beta/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/tablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/tablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tablerow?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-93817995"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 132, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="e082c22528d72aeb73c0952d6d11ea99-93817995"></a>
### [api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md)
 - **Line 132, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108250906322349-13598%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=3bQ%2F6AzpddbB0MA4INVB9WpWb7mwgPgRRv0%2B3MtY9GM%3D&st=2021-08-25T09%3A03%3A12Z&se=2021-09-25T09%3A08%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-31 10:45 UTC, crazygao commented on api-reference/beta/api/workbook-tablerowoperationresult.md
> +# workbook: tableRowOperationResult
Thanks.

2021-08-31 11:01 UTC, crazygao commented on api-reference/beta/api/workbook-tablerowoperationresult.md
> +3. Issue the URL. The response to this request contains a [workbookTableRow](../resources/tablerow.md).
Got it.

2021-09-01 00:32 UTC, Lauragra commented on api-reference/beta/resources/workbooktablerow.md
> +### Manage TableRow
Please restore having one Methods table and list the operations. A global comment here: There appears to be some confusion with tableRow. The name of the resource is workbookTableRow. The file names in this PR don't appear to be using the correct resource name, can you please rename them to "workbooktablerow" for clarity/consistency and update the links as appropriate? Note that we appear to have a workbooktablerow file in /beta and a tablerow file in /v1.0, and that is causing a problem.

2021-09-01 00:33 UTC, Lauragra commented on api-reference/beta/resources/workbooktablerow.md
> +### Manage TableRow
Also note that resource names are lower camel case so they start with a lowercase letter. Please apply that globally.

2021-09-01 10:53 UTC, crazygyl commented on api-reference/beta/resources/workbooktablerow.md
> +### Manage TableRow
Yes, I thought this filename in 1.0 is intended so that I didn't make any filename changes, I'll make them "workbookTableRow" globally.

2021-09-01 11:37 UTC, crazygyl approved these changes
This is also me, I used another account and happened to comment this thread

2021-09-01 11:38 UTC, jasonjoh commented
Docs Build status updates of commit _[8150343](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81503438429d886fbc71c39ebe3d1a1ec1586047)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-730d2766)
[api-reference/beta/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbook-tablerowoperationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-cd5f3646fff4baa2794d6a1147fe8f11-730d2766)
[api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-list-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-8e11a0a097cb030317e253d25b8c02e5-730d2766)
[api-reference/v1.0/api/tablerow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-list?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-49a6fa93f13196a19d22f094d06162f9-730d2766)
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-update?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-add?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-itemat?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/table.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/table.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/table?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/tablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/tablerow.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-730d2766"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 132, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="cd5f3646fff4baa2794d6a1147fe8f11-730d2766"></a>
### [api-reference/beta/api/workbook-tablerowoperationresult.md](https [...]

2021-09-01 11:44 UTC, jasonjoh commented
Docs Build status updates of commit _[14dfd8c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14dfd8c1367547394e66eb053c117e4292ce9ee2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-3462209e)
[api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-list-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-8e11a0a097cb030317e253d25b8c02e5-3462209e)
[api-reference/v1.0/api/tablerow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-list?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-49a6fa93f13196a19d22f094d06162f9-3462209e)
[api-reference/beta/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-update?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-add?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-itemat?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/table.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/table.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/table?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/tablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/tablerow.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-3462209e"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 132, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="8e11a0a097cb030317e253d25b8c02e5-3462209e"></a>
### [api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/ [...]

2021-09-01 21:08 UTC, jasonjoh commented
Docs Build status updates of commit _[1e41ec0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e41ec0814c68617bed71938b198e3b8797f28e2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-c4c8a133)
[api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-list-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-8e11a0a097cb030317e253d25b8c02e5-c4c8a133)
[api-reference/v1.0/api/tablerow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-list?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-49a6fa93f13196a19d22f094d06162f9-c4c8a133)
[api-reference/beta/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-update?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-add?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-itemat?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/table.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/table.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/table?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/tablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/tablerow.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-c4c8a133"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 132, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="8e11a0a097cb030317e253d25b8c02e5-c4c8a133"></a>
### [api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/ [...]

2021-09-01 21:22 UTC, jasonjoh commented
Docs Build status updates of commit _[baa489a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/baa489aff0ac664c2fc2e72a67e40bff23486c6d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-427a0d46)
[api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-list-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-8e11a0a097cb030317e253d25b8c02e5-427a0d46)
[api-reference/v1.0/api/tablerow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-list?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-49a6fa93f13196a19d22f094d06162f9-427a0d46)
[api-reference/beta/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-update?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-add?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-itemat?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/table.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/table.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/table?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/tablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/tablerow.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-427a0d46"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 132, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="8e11a0a097cb030317e253d25b8c02e5-427a0d46"></a>
### [api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/ [...]

2021-09-01 22:08 UTC, jasonjoh commented
Docs Build status updates of commit _[5eae648](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5eae6485e20a0956f4e680921948d8877953b149)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-7cd5beb5)
[api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-list-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-8e11a0a097cb030317e253d25b8c02e5-7cd5beb5)
[api-reference/v1.0/api/tablerow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-list?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-49a6fa93f13196a19d22f094d06162f9-7cd5beb5)
[api-reference/beta/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-update?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-add?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-itemat?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/table.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/table.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/table?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/tablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/tablerow.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-7cd5beb5"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 132, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="8e11a0a097cb030317e253d25b8c02e5-7cd5beb5"></a>
### [api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/ [...]

2021-09-07 03:18 UTC, opbld33 commented
Docs Build status updates of commit _[80f6b1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80f6b1dcb42438c4d61fb2b0d654162ccf472a69)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-85404eba)
[api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-list-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-8e11a0a097cb030317e253d25b8c02e5-85404eba)
[api-reference/v1.0/api/tablerow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-list?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-49a6fa93f13196a19d22f094d06162f9-85404eba)
[api-reference/beta/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-update?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-add?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-itemat?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/table.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/table.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/table?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/tablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/tablerow.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-85404eba"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 132, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="8e11a0a097cb030317e253d25b8c02e5-85404eba"></a>
### [api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/ [...]

2021-09-07 16:06 UTC, opbld31 commented
Docs Build status updates of commit _[4858e3d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4858e3daed876f7ca927850f3e215cb31b1ee326)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-1cbbb4bf)
[api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-list-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-8e11a0a097cb030317e253d25b8c02e5-1cbbb4bf)
[api-reference/v1.0/api/tablerow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-list?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-49a6fa93f13196a19d22f094d06162f9-1cbbb4bf)
[api-reference/beta/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-update?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-add?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-itemat?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/table.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/table.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/table?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/tablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/tablerow.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-1cbbb4bf"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 132, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="8e11a0a097cb030317e253d25b8c02e5-1cbbb4bf"></a>
### [api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/ [...]

2021-09-15 07:58 UTC, opbld34 commented
Docs Build status updates of commit _[49ffe2e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49ffe2ea9432aa4ce5a99cb842dc952094c0e75f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-0babb769)
[api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-list-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-8e11a0a097cb030317e253d25b8c02e5-0babb769)
[api-reference/v1.0/api/tablerow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-list?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-49a6fa93f13196a19d22f094d06162f9-0babb769)
[api-reference/beta/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-update?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-add?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-itemat?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/table.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/table.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/table?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/tablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/tablerow.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-0babb769"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 132, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="8e11a0a097cb030317e253d25b8c02e5-0babb769"></a>
### [api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/ [...]

2021-09-15 08:13 UTC, opbld34 commented
Docs Build status updates of commit _[da2bce7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da2bce7fbc71e51c4d76dd88a49face1afa0ebc8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-9324f968)
[api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-list-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-8e11a0a097cb030317e253d25b8c02e5-9324f968)
[api-reference/v1.0/api/tablerow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-list?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-49a6fa93f13196a19d22f094d06162f9-9324f968)
[api-reference/beta/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-update?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-add?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-itemat?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/table.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/table.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/table?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/tablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/tablerow.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[changelog/Microsoft.Excel.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/changelog/Microsoft.Excel.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-9324f968"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md)
 - **Line 132, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="8e11a0a097cb030317e253d25b8c02e5-9324f968"></a>
### [api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/ [...]

2021-09-16 03:20 UTC, Lauragra approved these changes

2021-09-16 03:20 UTC, opbld34 commented
Docs Build status updates of commit _[1e21c2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e21c2bf7aed53e2aba87ae48263d6a14c658c17)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-3f8f0dd2)
[api-reference/v1.0/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/accessreviewscheduledefinition-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-4cf64621647649f0f48b2223f9ab6a19-3f8f0dd2)
[api-reference/v1.0/api/b2xidentityuserflow-put-apiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/b2xidentityuserflow-put-apiconnectorconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-put-apiconnectorconfiguration?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-2616c1a4575bc66b187d689dbf3da9cb-3f8f0dd2)
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-54974c7a126366e7915039e1a4dc49ee-3f8f0dd2)
[api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-list-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-8e11a0a097cb030317e253d25b8c02e5-3f8f0dd2)
[api-reference/v1.0/api/tablerow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-list?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-49a6fa93f13196a19d22f094d06162f9-3f8f0dd2)
[api-reference/beta/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-update?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-add?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-itemat?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/table.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/table.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/table?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/tablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/tablerow.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resource [...]

2021-09-16 03:22 UTC, opbld33 commented
Docs Build status updates of commit _[da181ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da181ab1fc3d7b4e853ee4d694e01ec68f42a850)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-0bde0ea1)
[api-reference/v1.0/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/accessreviewscheduledefinition-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-4cf64621647649f0f48b2223f9ab6a19-0bde0ea1)
[api-reference/v1.0/api/b2xidentityuserflow-put-apiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/b2xidentityuserflow-put-apiconnectorconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-put-apiconnectorconfiguration?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-2616c1a4575bc66b187d689dbf3da9cb-0bde0ea1)
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) | [Details](#user-content-54974c7a126366e7915039e1a4dc49ee-0bde0ea1)
[api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-list-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-8e11a0a097cb030317e253d25b8c02e5-0bde0ea1)
[api-reference/v1.0/api/tablerow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-list?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) | [Details](#user-content-49a6fa93f13196a19d22f094d06162f9-0bde0ea1)
[api-reference/beta/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/resources/workbooktablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/resources/workbooktablerow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbooktablerow?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13598) (graph-rest-beta) |
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/table-post-rows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerow-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-update?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-add?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/tablerowcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/tablerowcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-itemat?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbook-tablerowoperationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbook-tablerowoperationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-tablerowoperationresult?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/api/workbookoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookoperation-get?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/table.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/table.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/table?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/tablerow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/tablerow.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/workbookoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/grangeryy-patch-3/api-reference/v1.0/resources/workbookoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workbookoperation?view=graph-rest-1.0&branch=pr-en-us-13598) (>= graph-rest-1.0) |
[api-reference/v1.0/resource [...]

2021-09-16 03:23 UTC, merged