Adding ExternalGroup to Graph v1.0
microsoftgraph/microsoft-graph-docs pull request #13607
Opened 2021-07-21 18:44 UTC by sacampbe-msft

Creating a pull request with documentation for the new graph connectors entities going into Graph v1.0.

1. ExternalGroup resource and related API operations
2. ExternalGroup member (Identity resource) and related API operations.
3. Table of contents for v1.0 to new pages

Open issues:

- Code snippets are likely out of date

2021-07-21 18:46 UTC, opbld31 commented
Docs Build status updates of commit _[9c6ce54](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/9c6ce54d1935b309a950008d93f2fd383931e313)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :x:Error | | [Details](#user-content-60f8d19ba356c564d856e69eca80e09d-3dd5f933)
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :x:Error | | [Details](#user-content-97a2724800bc3e98dbccb0617f99902f-3dd5f933)
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :x:Error | | [Details](#user-content-f5c89d5bf8925bd83d71869b2b927dc4-3dd5f933)
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :x:Error | | [Details](#user-content-1ad6e35591aec6f5e5fa46a9bdd0601b-3dd5f933)
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :warning:Warning | | [Details](#user-content-44bb10ba153580103fbec2e75b58de64-3dd5f933)
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :warning:Warning | | [Details](#user-content-8e66e82947bcfaf84f8f4acd5ed1667a-3dd5f933)
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :warning:Warning | | [Details](#user-content-431e6cd93aee33d7437f77bcbb61ed17-3dd5f933)

<a id="60f8d19ba356c564d856e69eca80e09d-3dd5f933"></a>
### [api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md)
 - **Line 83, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroup-from-connection-csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroup-from-connection-javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroup-from-connection-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroup-from-connection-java-snippets.md'.`````

<a id="97a2724800bc3e98dbccb0617f99902f-3dd5f933"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md)
 - **Line 64, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-externalgroup-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-externalgroup-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-externalgroup-objc-snippets.md'.`````
 - **Line 76, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-externalgroup-java-snippets.md'.`````

<a id="f5c89d5bf8925bd83d71869b2b927dc4-3dd5f933"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md)
 - **Line 84, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroupmember-from--1-csharp-snippets.md'.`````
 - **Line 88, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--1-javascript-snippets.md'.`````
 - **Line 92, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroupmember-from--1-objc-snippets.md'.`````
 - **Line 96, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroupmember-from--1-java-snippets.md'.`````
 - **Line 145, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroupmember-from--2-csharp-snippets.md'.`````
 - **Line 149, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--2-javascript-snippets.md'.`````
 - **Line 153, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroupmember-from--2-objc-snippets.md'.`````
 - **Line 157, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroupmember-from--2-java-snippets.md'.`````
 - **Line 204, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroupmember-from--3-csharp-snippets.md'.`````
 - **Line 208, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--3-javascript-snippets.md'.`````
 - **Line 212, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroupmember-from--3-objc-snippets.md'.`````
 - **Line 216, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroupmember-from--3-java-snippets.md'.`````

<a id="1ad6e35591aec6f5e5fa46a9bdd0601b-3dd5f933"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md)
 - **Line 67, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-externalgroupmember-csharp-snippets.md'.`````
 - **Line 71, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-externalgroupmember-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-externalgroupmember-objc-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-externalgroupmember-java-snippets.md'.`````

<a id="44bb10ba153580103fbec2e75b58de64-3dd5f933"></a>
### [api-reference/v1.0/api/externalconnectors-external [...]

2021-07-23 12:27 UTC, opbld30 commented
Docs Build status updates of commit _[22fba5f](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/22fba5f8d3585648e7d74ae1a3692ce661b8f39a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :x:Error | | [Details](#user-content-60f8d19ba356c564d856e69eca80e09d-9adaf92c)
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :x:Error | | [Details](#user-content-97a2724800bc3e98dbccb0617f99902f-9adaf92c)
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :x:Error | | [Details](#user-content-f5c89d5bf8925bd83d71869b2b927dc4-9adaf92c)
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :x:Error | | [Details](#user-content-1ad6e35591aec6f5e5fa46a9bdd0601b-9adaf92c)
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :warning:Warning | | [Details](#user-content-44bb10ba153580103fbec2e75b58de64-9adaf92c)
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :warning:Warning | | [Details](#user-content-8e66e82947bcfaf84f8f4acd5ed1667a-9adaf92c)
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :warning:Warning | | [Details](#user-content-431e6cd93aee33d7437f77bcbb61ed17-9adaf92c)

<a id="60f8d19ba356c564d856e69eca80e09d-9adaf92c"></a>
### [api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md)
 - **Line 87, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroup-from-connection-javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroup-from-connection-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroup-from-connection-java-snippets.md'.`````

<a id="97a2724800bc3e98dbccb0617f99902f-9adaf92c"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md)
 - **Line 64, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-externalgroup-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-externalgroup-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-externalgroup-objc-snippets.md'.`````
 - **Line 76, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-externalgroup-java-snippets.md'.`````

<a id="f5c89d5bf8925bd83d71869b2b927dc4-9adaf92c"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md)
 - **Line 84, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroupmember-from--1-csharp-snippets.md'.`````
 - **Line 88, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--1-javascript-snippets.md'.`````
 - **Line 92, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroupmember-from--1-objc-snippets.md'.`````
 - **Line 96, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroupmember-from--1-java-snippets.md'.`````
 - **Line 145, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroupmember-from--2-csharp-snippets.md'.`````
 - **Line 149, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--2-javascript-snippets.md'.`````
 - **Line 153, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroupmember-from--2-objc-snippets.md'.`````
 - **Line 157, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroupmember-from--2-java-snippets.md'.`````
 - **Line 204, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroupmember-from--3-csharp-snippets.md'.`````
 - **Line 208, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--3-javascript-snippets.md'.`````
 - **Line 212, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroupmember-from--3-objc-snippets.md'.`````
 - **Line 216, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroupmember-from--3-java-snippets.md'.`````

<a id="1ad6e35591aec6f5e5fa46a9bdd0601b-9adaf92c"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md)
 - **Line 67, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-externalgroupmember-csharp-snippets.md'.`````
 - **Line 71, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-externalgroupmember-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-externalgroupmember-objc-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-externalgroupmember-java-snippets.md'.`````

<a id="44bb10ba153580103fbec2e75b58de64-9adaf92c"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md)
  [...]

2021-07-23 12:45 UTC, opbld34 commented
Docs Build status updates of commit _[0aec940](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/0aec9405ca34909471af01bb53216b5bc366047d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-23 12:58 UTC, opbld33 commented
Docs Build status updates of commit _[d33e954](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/d33e954473f003ad10fa87c8dcc4b1d1fbbdf715)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :x:Error | | [Details](#user-content-60f8d19ba356c564d856e69eca80e09d-19bd5e97)
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :x:Error | | [Details](#user-content-97a2724800bc3e98dbccb0617f99902f-19bd5e97)
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :x:Error | | [Details](#user-content-f5c89d5bf8925bd83d71869b2b927dc4-19bd5e97)
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :x:Error | | [Details](#user-content-1ad6e35591aec6f5e5fa46a9bdd0601b-19bd5e97)
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :warning:Warning | | [Details](#user-content-44bb10ba153580103fbec2e75b58de64-19bd5e97)
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :warning:Warning | | [Details](#user-content-8e66e82947bcfaf84f8f4acd5ed1667a-19bd5e97)
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :warning:Warning | | [Details](#user-content-431e6cd93aee33d7437f77bcbb61ed17-19bd5e97)

<a id="60f8d19ba356c564d856e69eca80e09d-19bd5e97"></a>
### [api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md)
 - **Line 95, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroup-from-connection-java-snippets.md'.`````

<a id="97a2724800bc3e98dbccb0617f99902f-19bd5e97"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md)
 - **Line 68, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-externalgroup-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-externalgroup-objc-snippets.md'.`````
 - **Line 76, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-externalgroup-java-snippets.md'.`````

<a id="f5c89d5bf8925bd83d71869b2b927dc4-19bd5e97"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md)
 - **Line 84, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroupmember-from--1-csharp-snippets.md'.`````
 - **Line 88, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--1-javascript-snippets.md'.`````
 - **Line 92, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroupmember-from--1-objc-snippets.md'.`````
 - **Line 96, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroupmember-from--1-java-snippets.md'.`````
 - **Line 145, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroupmember-from--2-csharp-snippets.md'.`````
 - **Line 149, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--2-javascript-snippets.md'.`````
 - **Line 153, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroupmember-from--2-objc-snippets.md'.`````
 - **Line 157, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroupmember-from--2-java-snippets.md'.`````
 - **Line 204, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroupmember-from--3-csharp-snippets.md'.`````
 - **Line 208, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--3-javascript-snippets.md'.`````
 - **Line 212, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroupmember-from--3-objc-snippets.md'.`````
 - **Line 216, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroupmember-from--3-java-snippets.md'.`````

<a id="1ad6e35591aec6f5e5fa46a9bdd0601b-19bd5e97"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md)
 - **Line 67, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-externalgroupmember-csharp-snippets.md'.`````
 - **Line 71, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-externalgroupmember-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-externalgroupmember-objc-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-externalgroupmember-java-snippets.md'.`````

<a id="44bb10ba153580103fbec2e75b58de64-19bd5e97"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod [...]

2021-07-23 13:30 UTC, opbld33 commented
Docs Build status updates of commit _[f023916](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/f02391612a2d50ddd7d60c9fda85b315f0b62108)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :x:Error | | [Details](#user-content-f5c89d5bf8925bd83d71869b2b927dc4-047c4d22)
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :warning:Warning | | [Details](#user-content-44bb10ba153580103fbec2e75b58de64-047c4d22)
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :warning:Warning | | [Details](#user-content-8e66e82947bcfaf84f8f4acd5ed1667a-047c4d22)
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :warning:Warning | | [Details](#user-content-431e6cd93aee33d7437f77bcbb61ed17-047c4d22)

<a id="f5c89d5bf8925bd83d71869b2b927dc4-047c4d22"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md)
 - **Line 88, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--1-javascript-snippets.md'.`````
 - **Line 149, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--2-javascript-snippets.md'.`````
 - **Line 208, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--3-javascript-snippets.md'.`````

<a id="44bb10ba153580103fbec2e75b58de64-047c4d22"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 49, Column 53**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-entity.md'.`````

<a id="8e66e82947bcfaf84f8f4acd5ed1667a-047c4d22"></a>
### [api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md)
 - **Line 16, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-entity.md'.`````
 - **Line 29, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/externalconnectors-externalgroup-list.md'.`````
 - **Line 30, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/externalconnectors-externalgroup-create.md'.`````
 - **Line 31, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/externalconnectors-externalgroup-get.md'.`````
 - **Line 34, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/externalconnectors-externalgroup-list-members.md'.`````

<a id="431e6cd93aee33d7437f77bcbb61ed17-047c4d22"></a>
### [api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md)
 - **Line 19, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-entity.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107231328331765-13607%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-23T09%3A01%3A59Z&ske=2021-07-30T09%3A06%3A59Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-23T13%3A25%3A01Z&se=2021-08-23T13%3A30%3A01Z&sr=b&sp=r&sig=Ue5rD7pmasBYUJivEedV6NQgBRx1dgKUZMEvDsKy9KY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-23 13:48 UTC, opbld32 commented
Docs Build status updates of commit _[3771170](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/37711707d1ad66d7fe21611273cd454685b7a22a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) | [Details](#user-content-44bb10ba153580103fbec2e75b58de64-3f18fd26)
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) | [Details](#user-content-8e66e82947bcfaf84f8f4acd5ed1667a-3f18fd26)
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) | [Details](#user-content-431e6cd93aee33d7437f77bcbb61ed17-3f18fd26)
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-externalgroup-from-connection-csharp-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/csharp/create-externalgroup-from-connection-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-externalgroupmember-from--1-csharp-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/csharp/create-externalgroupmember-from--1-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-externalgroupmember-from--2-csharp-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/csharp/create-externalgroupmember-from--2-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-externalgroupmember-from--3-csharp-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/csharp/create-externalgroupmember-from--3-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-externalgroup-csharp-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/csharp/delete-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-externalgroupmember-csharp-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/csharp/delete-externalgroupmember-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/create-externalgroup-from-connection-java-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/java/create-externalgroup-from-connection-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/create-externalgroupmember-from--1-java-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/java/create-externalgroupmember-from--1-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/create-externalgroupmember-from--2-java-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/java/create-externalgroupmember-from--2-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/create-externalgroupmember-from--3-java-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/java/ [...]

2021-07-23 22:33 UTC, opbld31 commented
Docs Build status updates of commit _[10f12ad](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/10f12ad4f6f53d782efe1fc0cef3573d2a228b99)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-externalgroup-from-connection-csharp-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/csharp/create-externalgroup-from-connection-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-externalgroupmember-from--1-csharp-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/csharp/create-externalgroupmember-from--1-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-externalgroupmember-from--2-csharp-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/csharp/create-externalgroupmember-from--2-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-externalgroupmember-from--3-csharp-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/csharp/create-externalgroupmember-from--3-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-externalgroup-csharp-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/csharp/delete-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-externalgroupmember-csharp-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/csharp/delete-externalgroupmember-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/create-externalgroup-from-connection-java-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/java/create-externalgroup-from-connection-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/create-externalgroupmember-from--1-java-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/java/create-externalgroupmember-from--1-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/create-externalgroupmember-from--2-java-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/java/create-externalgroupmember-from--2-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/create-externalgroupmember-from--3-java-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/java/create-externalgroupmember-from--3-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/delete-externalgroup-java-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/java/delete-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/delete-externalgroupmember-java-snippets.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/includes/snippets/java/delete-externalgroupmember-java-snippets.md) | :white_check_mark:S [...]

2021-08-03 21:02 UTC, opbld34 commented
Docs Build status updates of commit _[046f591](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/046f5917bf0ec4d9cc1c96d80e276ee2c2b9eafc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :x:Error | | [Details](#user-content-60f8d19ba356c564d856e69eca80e09d-b07b5b6f)
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :x:Error | | [Details](#user-content-97a2724800bc3e98dbccb0617f99902f-b07b5b6f)
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :x:Error | | [Details](#user-content-f5c89d5bf8925bd83d71869b2b927dc4-b07b5b6f)
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :x:Error | | [Details](#user-content-1ad6e35591aec6f5e5fa46a9bdd0601b-b07b5b6f)

<a id="60f8d19ba356c564d856e69eca80e09d-b07b5b6f"></a>
### [api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md)
 - **Line 83, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroup-from-connection-csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroup-from-connection-javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroup-from-connection-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroup-from-connection-java-snippets.md'.`````

<a id="97a2724800bc3e98dbccb0617f99902f-b07b5b6f"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md)
 - **Line 64, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-externalgroup-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-externalgroup-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-externalgroup-objc-snippets.md'.`````
 - **Line 76, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-externalgroup-java-snippets.md'.`````

<a id="f5c89d5bf8925bd83d71869b2b927dc4-b07b5b6f"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md)
 - **Line 84, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroupmember-from--1-csharp-snippets.md'.`````
 - **Line 88, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--1-javascript-snippets.md'.`````
 - **Line 92, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroupmember-from--1-objc-snippets.md'.`````
 - **Line 96, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroupmember-from--1-java-snippets.md'.`````
 - **Line 145, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroupmember-from--2-csharp-snippets.md'.`````
 - **Line 149, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--2-javascript-snippets.md'.`````
 - **Line 153, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroupmember-from--2-objc-snippets.md'.`````
 - **Line 157, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroupmember-from--2-java-snippets.md'.`````
 - **Line 204, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroupmember-from--3-csharp-snippets.md'.`````
 - **Line 208, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--3-javascript-snippets.md'.`````
 - **Line 212, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroupmember-from--3-objc-snippets.md'.`````
 - **Line 216, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroupmember-from--3-java-snippets.md'.`````

<a id="1ad6e35591aec6f5e5fa46a9bdd0601b-b07b5b6f"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md)
 - **Line 67, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-externalgroupmember-csharp-snippets.md'.`````
 - **Line 71, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-externalgroupmember-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-externalgroupmember-objc-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-externalgroupmember-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108032057091063-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=oMIIf4l3qjgksodqgphpQHE4TzPSFfLykIcRuashMt4%3D&st=2021-08-03T20%3A57%3A37Z&se=2021-09-03T21%3A02%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. Th [...]

2021-08-03 21:13 UTC, opbld31 commented
Docs Build status updates of commit _[f7d6c6a](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/f7d6c6a5a36e608cb0237f9acd2b8728cf62f369)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :x:Error | | [Details](#user-content-f5c89d5bf8925bd83d71869b2b927dc4-f38698ec)

<a id="f5c89d5bf8925bd83d71869b2b927dc4-f38698ec"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md)
 - **Line 84, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroupmember-from--1-csharp-snippets.md'.`````
 - **Line 88, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--1-javascript-snippets.md'.`````
 - **Line 92, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroupmember-from--1-objc-snippets.md'.`````
 - **Line 96, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroupmember-from--1-java-snippets.md'.`````
 - **Line 145, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-externalgroupmember-from--2-csharp-snippets.md'.`````
 - **Line 149, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-externalgroupmember-from--2-javascript-snippets.md'.`````
 - **Line 153, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-externalgroupmember-from--2-objc-snippets.md'.`````
 - **Line 157, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/create-externalgroupmember-from--2-java-snippets.md'.`````
 - **Line 187, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108032108334597-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=hsrcgcaQNKa8lpbAuKTSEAEKAetmvIz9Q2kkhg9xB8o%3D&st=2021-08-03T21%3A08%3A57Z&se=2021-09-03T21%3A13%3A57Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 21:30 UTC, opbld33 commented
Docs Build status updates of commit _[f79d09c](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/f79d09c02ace2041dd4c8a3dc0ec7ac914006c45)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) | [Details](#user-content-f5c89d5bf8925bd83d71869b2b927dc4-60841cc0)
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="f5c89d5bf8925bd83d71869b2b927dc4-60841cc0"></a>
### [api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md)
 - **Line 67, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 3).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108032128040542-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=eE2eMdw%2BkQz7fNLcYBg8l1JZLUUlVoUyEbkb4EvW3E4%3D&st=2021-08-03T21%3A25%3A06Z&se=2021-09-03T21%3A30%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 21:51 UTC, opbld34 commented
Docs Build status updates of commit _[6aa579c](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/6aa579c02e76c13d329caa9336ee5fb1b4a79192)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108032149494784-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=BU%2BNTwqcPpXxnIYCSeOzLFLN8s33mupjf5OQbNz8xwU%3D&st=2021-08-03T21%3A46%3A17Z&se=2021-09-03T21%3A51%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 23:55 UTC, opbld30 commented
Docs Build status updates of commit _[b156d51](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/b156d51b9eba8d296d1868292699d2e83b584fa6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108032350421850-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=8k7DDJP8H8pGh5p8HfCcbgsf9CX5tszLoStFDfuzt%2Fs%3D&st=2021-08-03T23%3A50%3A56Z&se=2021-09-03T23%3A55%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 01:11 UTC, opbld34 commented
Docs Build status updates of commit _[cfd4804](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/cfd4804e576b78d91c882d95429cec88a0af19c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108040109468535-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=pDwqf3lxv8pSlN8OWohl%2FUIf2OK251vlQW1g7BZe6hk%3D&st=2021-08-04T01%3A06%3A22Z&se=2021-09-04T01%3A11%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 14:11 UTC, opbld31 commented
Docs Build status updates of commit _[5791fb6](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/5791fb618aa061f1a7c14648cab4eea75534a0aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108041408441215-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=A6NV%2FHSbI7fYVE0LH3eroOI7zc0X4Y%2F3C579wXLICwI%3D&st=2021-08-04T14%3A06%3A18Z&se=2021-09-04T14%3A11%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 14:35 UTC, isvargasmsft commented on api-reference/v1.0/resources/externalconnectors-identity.md
> +| type           | microsoft.graph.externalConnectors.identityType | The type of identity. Possible values are: `user` or `group`  for azureActiveDirectory identities and `externalgroup` for groups i
Line 22: API Doctor is failing because this type (microsoft.graph.externalConnectors.identityType) is not defined. I tried to search in the beta metadata and it's not defined there either. 

I understand this PR's purpose is to GA externalGroup. In such case, everything in this PR should be available in beta already.

2021-08-04 17:24 UTC, sacampbe-msft commented on api-reference/v1.0/resources/externalconnectors-identity.md
> +| type           | microsoft.graph.externalConnectors.identityType | The type of identity. Possible values are: `user` or `group`  for azureActiveDirectory identities and `externalgroup` for groups i
Thanks for bringing it up as I'm not sure why this error is happening. Where is it not defined, the github repo? _microsoft.graph.externalConnectors.identityType_ is an enum field and for several published docs, enum fields are not defined but described in their usage. One example is the enum _"inferenceClassificationType"_ here https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0. 

_microsoft.graph.externalConnectors.identityType_ is used in hidden property in beta, and during our graph api review we brought up that we had two similar objects and wanted to coalesce these two into one :_microsoft.graph.externalConnectors.**identity**_ and _microsoft.graph.externalConnectors.externalGroupMember_.
They approved us using the forward looking shape in V1 today while we went through the process of deprecating it in /beta, which we currently are. Both shapes are similar, and we do support this V1 shape in Beta as the differentiating field has been made optional e.g.

POST /connections/{id}/groups/{id}/members - works for /beta and the deploying /v1.0 versions.
{
   "id":"contosoSupport",
   "type":"externalGroup"
}

/v1.0 and /beta
<EntityType Name="identity">
     <Property Name="id" Type="Edm.String" Nullable="false" />
    <Property Name="type" Type="microsoft.graph.externalConnectors.identityType" />
</EntityType>

/beta only -  _identitySource_ has been made optional and will implictly be deprecated when we switch to _identity_
 <EntityType Name="externalGroupMember"">
    <Property Name="id" Type="Edm.String" Nullable="false" />
    <Property Name="identitySource" Type="microsoft.graph.externalConnectors.identitySourceType" />
    <Property Name="type" Type="microsoft.graph.externalConnectors.externalGroupMemberType" Nullable="false" /></EntityType>

2021-08-04 20:52 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-delete.md
> +Deletes an [externalGroup](../resources/externalconnectors-externalgroup.md) object.
Lines 3 and 15: Please use imperative voice in descriptions:
Delete an externalGroup...

2021-08-04 20:54 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-delete.md
> +Deletes an [externalGroup](../resources/externalconnectors-externalgroup.md) object.
Please fix in beta as well.

2021-08-04 22:02 UTC, opbld34 commented
Docs Build status updates of commit _[7ac34ca](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/7ac34ca42304d5c485929a5da5ade20d9933730d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalConnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalConnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108042159339410-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=20%2BZ12AlVAKzD3Ng0VlkCdKZFWUdaMB4zI2UD0xCZ2w%3D&st=2021-08-04T21%3A57%3A02Z&se=2021-09-04T22%3A02%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 16:12 UTC, isvargasmsft commented
@sacampbe-msft I noticed there are some files missing:
- Get externalGroup
- List externalGroups
- externalGroupMember resource type
- Get externalGroupMember
- List externalGroupMembers

Is there a reason to leave these behind? 

Kind regards!

2021-08-05 16:33 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md
> +# [HTTP](#tab/http)
Line 65: 
Please note code snippets are generated automatically, please remove line 65 from this docs. The tool will automatically generate the tabs.

2021-08-05 16:37 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md
> +Create a new externalGroup object.
Please include a reference link for externalGroup: 
- Create a new [externalGroup] (link here ) object.

2021-08-05 16:38 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md
> +The following table shows the properties that are required when you create the [externalGroup](../resources/externalconnectors-externalgroup.md).
Lines 44 and 46:
Since the link should be provided in the first line of the article, it is ok to just mention externalGroup in **bold text**.

2021-08-05 16:47 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +# Create identity
I noticed this in the CSDL: Is there a reason to use different names for the navigation property and the resource type? Why not use externalGroupMember instead of identity? Could it be confused with [this identity](https://docs.microsoft.com/en-us/graph/api/resources/identity?view=graph-rest-1.0)?

2021-08-05 16:53 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +# Create identity
In any case, the title in line 10 should match the title in line 2. Same for the descriptions in lines 3 and 15.

If we want to be strict I'd say we use 'identity' since this is the name of the resource type. However, I think externalGroupMember is easier to discover and understand for users.

Please let me hear your thoughts.

2021-08-05 16:56 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +| type           | microsoft.graph.externalConnectors.identityType | The type of member added to the external group. Possible values are: `user`,`group`, `externalGroup`, `unknownFutureValue`. |
Line 53:
I don't think its necessary to list `unknownFutureValue` here.

2021-08-05 16:57 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +### Request
Line 64, 77, 99, 111, 132 and 144: Please use H4 for Request and Response when there are 2 or more examples.

2021-08-05 16:59 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +
Please remember to add the API Doctor code before the Request. Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor?anchor=set-up-for-api-doctor-in-an-api-topic

2021-08-05 17:01 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +  "identitySource": "azureActiveDirectory"
Please remove the identitySource property from this example since it is not available for v1.

2021-08-05 17:02 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +
Please add the API Doctor code for a request.

2021-08-05 17:03 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +
Please add the API Dr code for a request here as well.

2021-08-05 17:04 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +**Note:** The response object shown here might be shortened for readability.
Please remove this note since we are publishing the actual complete response. We try to use this note only if necessary.

2021-08-05 17:04 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +**Note:** The response object shown here might be shortened for readability.
Please remove from the other examples when applicable.

2021-08-05 17:13 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-update.md
> +## Examples
Line 61: Please change to singular (Example) when we are publishing just 1 example.

2021-08-05 17:14 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-update.md
> +Content-length: 130
Line 72: you can remove Content-length to avoid confusion.

2021-08-05 17:15 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-update.md
> +  "description": "String"
I'd appreciate if you can add a real looking String instead of the placeholder.

2021-08-05 17:16 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-update.md
> +>**Note:** The response object shown here might be shortened for readability.
Please remove this note since it does not apply in this case.

2021-08-05 18:20 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md
> +title: "Delete externalGroupMembery"
1. Same observation regarding the name of the resource type: identity vs externalGroupMember. 
2. If we decide to use the externalGroupMember, please fix the typo in the title.

2021-08-05 20:25 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md
> +# [HTTP](#tab/http)
Please remove line 56. These tabs are automatically generated.

2021-08-05 20:25 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md
> +## Examples
Line 51: Please change to singular when we are sharing just 1 example.

2021-08-05 21:28 UTC, isvargasmsft commented on api-reference/v1.0/resources/externalconnectors-externalgroup.md
> +Represents an external group. External groups (along with Azure Active Directory users and groups) are used to set permissions on **externalItems** added to a Microsoft Graph connection. Use **extern
Line 14:
1. The description in line 3 should match the very first sentence of the article. We try to make this sentence in a single paragraph and add any additional information in a subsequent paragraph. 
2. Please consider this line is used by search engines to display results, so put yourself in the shoes of someone looking in Bing. What would you look for? What is the most basic explanation of this resource type? How would you explain this resource type to someone who is just learning about the API. 
3. Please avoid using passive voice as it leads to confusion. Details [here](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=25523).
4. Please avoid using phrases like "and so on". Be specific instead. More details [here](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=29202).

For example:

Represents a non-Azure Active Directory group.

External groups determine permissions over the content in an external data source. For instance, permissions on [externalItems] (link ) in a Microsoft Graph [connection] (link ). 

Examples of external groups are business units and work teams.

2021-08-05 21:29 UTC, isvargasmsft commented on api-reference/v1.0/resources/externalconnectors-externalgroup.md
> +Represents an external group. External groups (along with Azure Active Directory users and groups) are used to set permissions on **externalItems** added to a Microsoft Graph connection. Use **extern
Please address this comment in the beta version as well.

2021-08-05 21:43 UTC, isvargasmsft commented on api-reference/v1.0/resources/externalconnectors-externalgroup.md
> +|Method|Return type|Description|
1. Is there a reason to have 2 tables for methods?
2. According to the api.md file we should have: Create, Update, Delete, Get and List.

2021-08-05 21:55 UTC, isvargasmsft commented on changelog/Microsoft.Search.json
> +              "Id": "62eaf068-e8b4-11eb-88f7-f923b9ff781d",
Please use the same ID for all items in a single changelog entry (changelist).

2021-08-05 21:57 UTC, isvargasmsft commented on changelog/Microsoft.Search.json
> +      "WorkloadArea": "",
Please use the work area here. In this case I think it is "search".

2021-08-05 22:01 UTC, isvargasmsft commented on api-reference/v1.0/resources/externalconnectors-identity.md
> +
Are we not including the methods (CRUD operations)?

2021-08-05 22:04 UTC, isvargasmsft requested changes
Hello @sacampbe-msft, 

Thank you very much for your work in this PR. 

Just a few observations:
1. According to the files we have a few docs missing (get and list).
2. Why are we not including the CRUD operations for the `identity` resource type?
3. Please clarify the decision to name `identity` instead of externalGroupMembers. Thinking about discoverability and clarity for the customers. 

Please feel free to ping me on the side if you have any questions.

Thank you very much. 

Isaac

2021-08-10 22:28 UTC, sacampbe-msft commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +# Create identity
We are onboarding another feature which requires the use of this identity shape. Reusing the externalGroupMember in that shape would be confusing so we decided to go with the generic "identity" named resource which can be used in both places and any future scenarios.

That identity shape is in our sub-namespace only, that should help us reduce confusion.

I am okay with calling it externalGroupMember, is it okay to link to the identity resource while calling it such?

` 15: Create a new  [externalGroupMember](../resources/externalconnectors-identity.md) object.`

2021-08-10 22:34 UTC, sacampbe-msft commented on api-reference/v1.0/resources/externalconnectors-identity.md
> +
Correct, we're not exposing get or list operations for the identity type at the present.

2021-08-10 22:37 UTC, sacampbe-msft commented on api-reference/v1.0/resources/externalconnectors-externalgroup.md
> +|Method|Return type|Description|
This is a typo.

We should have create,update,delete and get but not list. We'll need to add a Get page

2021-08-20 00:56 UTC, sacampbe-msft commented
Updated non-"Identity" related changes. Will make identity related changes next

2021-08-20 00:57 UTC, opbld32 commented
Docs Build status updates of commit _[eb28f7d](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/eb28f7daaafee09e1681a9535a2af45cca7fc4e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalConnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalConnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108200055514672-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Pb5njIi7kLE9oFZ6o72xiMu4bl0aA7nthGSEBS1pjA0%3D&st=2021-08-20T00%3A52%3A27Z&se=2021-09-20T00%3A57%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 03:37 UTC, angelgolfer-ms commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +Create a new externalGroup [member](../resources/externalconnectors-identity.md) object.
For line 15:
Hi @sacampbe-msft , I'd suggest:
"Create a [member](../resources/externalconnectors-identity.md) resource in an externalGroup."

- Please add a link to externalGroup.
- It's a good idea to break up nouns whenever possible for localization. After all, the new object is a member resource, and not externalGroup, so having your construction is also ambiguous.
- Please use this description in line 3 just as text, without any links or styling. We recently learned about a new feature "Recommended content" that exposes the string value of this "Description" metadata but any MD styling would just pass through, so no styling in line 3 is necessary.

2021-08-20 04:00 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/externalconnectors-identity.md
> +
Line 22:
Why is "azureActiveDirectory" expressed as such? I didn't notice it's a programmatic term in the CSDL for your API. Please use the proper branded name "Azure Active Directory (Azure AD)."

2021-08-20 04:26 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/externalconnectors-identity.md
> +| type           | microsoft.graph.externalConnectors.identityType | The type of identity. Possible values are: `user` or `group`  for azureActiveDirectory identities and `externalgroup` for groups i
@sacampbe-msft , one of the 3 API Doctor errors you have right now is in the example labelled create_aad_group_identity_from_group, which is in externalconnectors-externalgroup-post-members.md (v1.0 in your PR). The error says:
"Resource type was null or missing in response metadata, so we assume there is no response to validate."

The "response metadata" is the HTML block that's commented out before the example response. API Doctor didn't see you specify the response should have a body. To do that, add a line after line 87 there:
"@odata.type": "microsoft.graph.externalConnectors.identity"

For more info about this, see the CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor?anchor=json-element-descriptions

2021-08-20 04:31 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/externalconnectors-identity.md
> +| type           | microsoft.graph.externalConnectors.identityType | The type of identity. Possible values are: `user` or `group`  for azureActiveDirectory identities and `externalgroup` for groups i
The other 2 API Doctor errors are the same nature. Please apply the same fix to the metadata of the other 2 example responses in the same topic.

2021-08-20 17:14 UTC, opbld31 commented
Docs Build status updates of commit _[fbc9e20](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/fbc9e20cd3e5263156905b2da8821942987b7488)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalConnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalConnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201713045199-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=L4TjfjVXRD3pHu4sR64%2FiD5qmTwifFoTcJ8u%2B15pJgg%3D&st=2021-08-20T17%3A09%3A37Z&se=2021-09-20T17%3A14%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 18:57 UTC, opbld34 commented
Docs Build status updates of commit _[2a67364](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/2a67364ea345856e09915fb25a3ae92dae7153b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalConnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalConnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201855385384-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=xGbPrioq7a%2FRQ0INxik3xcE%2BdKQrtAf%2B2u9IpEEA1G0%3D&st=2021-08-20T18%3A52%3A10Z&se=2021-09-20T18%3A57%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 19:22 UTC, opbld31 commented
Docs Build status updates of commit _[c02bd29](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/c02bd2967909ceb4928a0c62122d32cb039e35fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalConnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalConnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201921191553-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=CtYX3%2FN86oQRZq%2BNyTWVlnRZ8CjZ%2BDl7DhR6Fe4MOk0%3D&st=2021-08-20T19%3A17%3A46Z&se=2021-09-20T19%3A22%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 19:22 UTC, sacampbe-msft commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +Create a new externalGroup [member](../resources/externalconnectors-identity.md) object.
Following this suggestion, should the title be updated to "Create a new member" (I prefer this)? or instead "Create externalGroup identity" or "Create identity" 

cc: @isvargasmsft

2021-08-20 19:25 UTC, sacampbe-msft commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +Create a new externalGroup [member](../resources/externalconnectors-identity.md) object.
"Create externalGroup member" also seems apt

2021-08-20 19:34 UTC, angelgolfer-ms commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +  "@odata.type": "microsoft.graph.externalConnectors.identity"
Line 69:
To clarify, you don't need to include @odata.type for the body in the example request. Only for the body in the example response. Please delete this line, to stay consistent and avoid confusion down the road. Thanks.

2021-08-20 19:45 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/externalconnectors-identity.md
> +
Line 22:
Sorry, I had not noticed there's a first mention in line 21. 
This is the full guidance for referring to Azure Active Directory: https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25369

So, first reference is in line 21, and what you have now is appropriate. Subsequent references in the same article - you can use what you specified in parentheses in line 21. So in line 22, you can just say "Azure AD".

(Such is Microsoft's referencing pattern for many branded product and service names.)

2021-08-20 20:57 UTC, opbld32 commented
Docs Build status updates of commit _[be89f10](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/be89f10ea38e2662f647e825f1305228fc6a5127)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-e7fe9e53)
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete-member.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete-member.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete-member?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalConnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalConnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-e7fe9e53"></a>
### [api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml)
 - **Line 5787, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/externalconnectors-externalgroupmember-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108202056130005-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=eQvtvTNE%2B17HBwFywkwLsd2EFRERXyXu0v9swaAV3oo%3D&st=2021-08-20T20%3A52%3A46Z&se=2021-09-20T20%3A57%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 21:06 UTC, opbld31 commented
Docs Build status updates of commit _[f8f559b](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/f8f559b1b5951f46b26072fb120c2525608039d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete-member.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete-member.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete-member?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalConnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalConnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108202104167389-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=zzBFEdL%2FpuUt9Lq4cVeQq4VkTANMmFc7jGgkGitGZCI%3D&st=2021-08-20T21%3A01%3A02Z&se=2021-09-20T21%3A06%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 21:20 UTC, opbld31 commented
Docs Build status updates of commit _[683c2a2](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/683c2a2f4313e62bf5ed14539e531cbbf01c7fda)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete-member.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete-member.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete-member?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalConnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalConnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108202118546885-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=7SWgsIEbube321NLaalZWbeXAu6cmAlIhsYsDq40Ao0%3D&st=2021-08-20T21%3A15%3A22Z&se=2021-09-20T21%3A20%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-21 02:04 UTC, angelgolfer-ms commented on api-reference/v1.0/toc.yml
> +          - name: Create external group member
Line 5766:
Please use the TOC title "Create identity for member".

Line 5768:
Please use the TOC title "Delete identity of member".

2021-08-21 02:07 UTC, angelgolfer-ms commented on api-reference/v1.0/api/externalconnectors-externalgroup-delete-member.md
> +Remove an existing [identity](../resources/externalconnectors-identity.md) resource member from an [externalGroup](../resources/externalconnectors-externalgroup.md).
Line 14:
Please use:
"Remove a member from an externalGroup by deleting the corresponding identity resource."
Please keep the links to externalGroup and identity.

I think this will work better together with the TOC titles, topic titles, and summary descriptions for the "create" and "delete" topics for external group member.

2021-08-21 02:34 UTC, angelgolfer-ms commented on api-reference/v1.0/api/externalconnectors-externalgroup-delete-member.md
> +---
Filename:
This should be externalconnectors-identity-delete.md.
The filename pattern to follow is: {sub-namespace name}-{resource name}-delete.md.

FYI, one can double-check the filename pattern by looking at the query URL (in line 33 in this case) as well:
DELETE /connections/{connectionId}/groups/{externalGroupId}/members/{identityId}

For the CRUD operations of GET, PATCH, DELETE, typically the query URL is:
https://{graph domain}/{version}/{whatever path to identify a resource collection}/{nav property for a resource collection}/{id into collection}

Given a query URL like that, one just needs to take into account that type of the second last segment {nav property for a resource collection}, append '-', append the corresponding "get", "update", or "delete", to form the filename.

For this topic in question, the type of the collection in the second last segment preceding the ID in the query URL is the identity resource type. So the filename for this operation defined in a subnamespace is {subnamespace name}-identity-delete.md.

For more info, this is the CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming

Sorry if there was any churn on the filename earlier in this review.

I would however be interested in knowing what the generator originally generated/ or would generate. I see in this PR "29 days ago" the [first build](https://github.com/microsoftgraph/microsoft-graph-docs/pull/13607#issuecomment-885651791) included a file named externalconnectors-externalgroupmember-delete.md. I guessed that was just a copy from the beta set of files, not really generated based on an internal copy of the v1 metadata? Or had a set been generated for v1 earlier but the filename was subsequently modified before the first build? Can't tell :-)

2021-08-21 02:45 UTC, angelgolfer-ms requested changes
Hi @sacampbe-msft , FYI I reviewed the filenames for this PR, and advised on TOC titles and summary description for the delete identity of group member topic. Hopefully with those updates, customers can relate the TOC titles with the topic titles and summary descriptions better.

In case you wonder, those filename patterns were set by the original owners of the first topic generator. We don't actually have maximum flexibility with filenames. If you have any questions, please ping me on Teams.

2021-08-23 15:58 UTC, opbld31 commented
Docs Build status updates of commit _[42ccea2](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/42ccea2581da6a9d58363a3778abf5f1fb3b81e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete-member.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete-member.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete-member?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalConnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalConnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108231556567239-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=LDHFFpRvlWaLV4Q89Bq4iuTGxLNQsphyFqIsRdbtp2c%3D&st=2021-08-23T15%3A53%3A23Z&se=2021-09-23T15%3A58%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-23 20:34 UTC, sacampbe-msft commented on api-reference/v1.0/api/externalconnectors-externalgroup-delete-member.md
> +---
Original doc stubs: https://github.com/microsoftgraph/microsoft-graph-docs/tree/2021-07-19-sacampbe-identity-sync-apis-3/doc-stubs/api

The original stubs had namespace-identity-operation, but I copied over the externalconnectors-externalgroup-post-members doc from beta and changed the externalconnectors-identity-delete to match that format, I've corrected this mistake now.

2021-08-23 20:35 UTC, opbld31 commented
Docs Build status updates of commit _[ecb3f31](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/ecb3f31a91fb00cd15d7985aa1b20f85f738bd07)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-identity-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-identity-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-identity-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalConnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalConnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108232034043549-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Trn0vME%2FQM%2BhKxivZ%2BIubtES5YyK04Kx2Pebce7ZJ3s%3D&st=2021-08-23T20%3A30%3A34Z&se=2021-09-23T20%3A35%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-23 21:38 UTC, angelgolfer-ms commented on api-reference/v1.0/toc.yml
> +            href: api/externalconnectors-externalgroup-delete.md
Just noticed:
Since you added the GET and PATCH operations for externalGroup, please add the 2 operations to the TOC as well.
The typical order is: list, create, get, update, delete. Ignore those operations you don't support (i.e., list).
You also need to add them to the Methods table of the externalGroup resource.

2021-08-23 21:41 UTC, angelgolfer-ms commented on api-reference/v1.0/toc.yml
> +          - name: Delete identity of member
After line 5783:
Please also add a TOC entry point for the identity resource.
The TOC title is "Identity".

2021-08-23 23:07 UTC, opbld34 commented
Docs Build status updates of commit _[6d84faa](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/6d84faa879a1d82760588d7077ea467b0a6e8fa9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-identity-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-identity-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-identity-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalConnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalConnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108232305446866-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=uxsX6VHF7yRS90R4M7gPptqhzwkA5qBWNFM8gkDPnM8%3D&st=2021-08-23T23%3A02%3A36Z&se=2021-09-23T23%3A07%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-24 13:57 UTC, opbld33 commented
Docs Build status updates of commit _[94717c7](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/94717c7396b2f1fd0b55be3d98d7e332e455a220)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-identity-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-identity-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-identity-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalConnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalConnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108241355569152-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=jEtYNXOywWqTUrELke6Fqymr3HDR0s4HShiRxu9Hunw%3D&st=2021-08-24T13%3A52%3A35Z&se=2021-09-24T13%3A57%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-24 14:41 UTC, isvargasmsft commented on api-reference/v1.0/api/externalconnectors-externalgroup-update.md
> +Content-length: 130
Previous comment: 
Line 72: you can remove Content-length to avoid confusion.

2021-08-24 14:41 UTC, isvargasmsft commented on api-reference/v1.0/resources/externalconnectors-identity.md
> +
Previous comment: Please include a section with the methods (CRUD operations).

2021-08-24 14:44 UTC, isvargasmsft commented on api-reference/v1.0/toc.yml
> +            href: api/externalconnectors-externalgroup-delete.md
Previous comment from Angela:
Since you added the GET and PATCH operations for externalGroup, please add the 2 operations to the TOC as well.
The typical order is: list, create, get, update, delete. Ignore those operations you don't support (i.e., list).
You also need to add them to the Methods table of the externalGroup resource.

2021-08-24 18:07 UTC, opbld33 commented
Docs Build status updates of commit _[0b89c79](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/0b89c79606eaded6d421b24f7786a9f7a2747a7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-identity-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-identity-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-identity-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalConnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalConnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108241805531406-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=oqo%2BWyefL0t%2FmQ%2Be4UCREC%2F7nfjMB%2BZutagazGKBs1Y%3D&st=2021-08-24T18%3A02%3A21Z&se=2021-09-24T18%3A07%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-24 18:13 UTC, sacampbe-msft commented on api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md
> +# Create identity
Resolved offline and updated accordingly: Move forward with Identity usages, not externalGroupMember. However make it clear the identity resource created maps to a member of an externalGroup

2021-08-24 18:14 UTC, sacampbe-msft commented on api-reference/v1.0/toc.yml
> +            href: api/externalconnectors-externalgroup-delete.md
Added the new methods in the TOC

2021-08-24 19:18 UTC, opbld30 commented
Docs Build status updates of commit _[a55b1b3](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/a55b1b32cb11ed563a53a3789feb548fedfde01f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-identity-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-identity-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-identity-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalConnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalConnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108241917000948-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=yiULobKKRrHjsv1tj4rUcIGW0SmKVP3hRPqFvTVeVxs%3D&st=2021-08-24T19%3A13%3A34Z&se=2021-09-24T19%3A18%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-24 19:23 UTC, isvargasmsft approved these changes
Thank you very much for your work in this PR and your patience. 

Kind regards,

Isaac Vargas

2021-08-24 19:25 UTC, isvargasmsft commented
@angelgolfer-ms please let us know if you have any additional comments. 

Warm regards, 

Isaac Vargas

2021-08-28 01:03 UTC, opbld34 commented
Docs Build status updates of commit _[79ea998](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/79ea998088568ee995767a33538feb6a0bd3a745)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-identity-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-identity-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-identity-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalconnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-13607) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108280102127985-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=tPcIm7jlzIEioqYZb8B%2B7HNbUN2FXxgwCLAhBFvoZ4M%3D&st=2021-08-28T00%3A58%3A58Z&se=2021-09-28T01%3A03%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-28 05:18 UTC, opbld32 commented
Docs Build status updates of commit _[016dae6](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/016dae670745e24924f1dbd48e1fee435fe366ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-identity-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-identity-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-identity-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalconnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-13607) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108280516306314-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=4E0fK56Zqm8y8%2FNKRm4IcM9m5Bcv6eDOwvj7NdgpKwQ%3D&st=2021-08-28T05%3A13%3A16Z&se=2021-09-28T05%3A18%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-28 05:56 UTC, angelgolfer-ms commented on api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md
> +The following table shows the properties that are required when you create the **externalGroup**.
For the purpose of this PR (showing the changes in the API shape in v1), and considering the need to let customers have some docs to look at for those changes, I'd suggest to restrict the scope creep for this PR. You can please track the necessary changes for the Request body section in other connectors API topics, and address them soon after we publish this PR.

2021-08-28 07:22 UTC, angelgolfer-ms commented on api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md
> +
Line 46:
Looks like you made the lead-in sentence update as we discussed offline in the beta topic and didn't apply it to this v1 topic. In the interest of time, I'll make that change.
Please let me know in case there's some other reason that you didn't apply the change here.

2021-08-28 07:46 UTC, angelgolfer-ms commented on api-reference/v1.0/api/externalconnectors-externalgroup-update.md
> +You can specify the following properties when updating an **externalGroup**.
Lines 45-47:
FYI I am requesting the generator owner to bring back the lead-in paragraph that was used before, which is more helpful especially for customers unfamiliar with recommended OData practices for PATCH:
"In the request body, supply the values for relevant properties that should be updated. Existing properties that are not included in the request body will maintain their previous values or be recalculated based on changes to other property values. For best performance, do not include properties that are not changing."

On the other hand, in case you see any issues with this lead-in paragraph, please let me know. Meanwhile, I am updating the lead-in text, in the interest of time, for this PR.

2021-08-28 08:30 UTC, angelgolfer-ms commented on api-reference/v1.0/toc.yml
> +          - name: Create external group
In the interest of getting this PR published and letting customers have some docs to refer to, in order to update those APIs before the API shape also changes in beta in about only a month, can you please track this as a separate pass? This is a nice-to-have for easier scanning. We should try to get this PR published tonight.

2021-08-28 08:36 UTC, opbld32 commented
Docs Build status updates of commit _[e23c738](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/e23c738994d1ec806ddd8e9a5b70c6e5aa6036b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-external-post-connections.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalitem-create.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalitem-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-create?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-identity-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-identity-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-identity-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalconnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-13607) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108280834378373-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=4NOQpN7d0wSG05M7lSrx21z%2BQA5rXki3v%2BBauTRvDxY%3D&st=2021-08-28T08%3A31%3A08Z&se=2021-09-28T08%3A36%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e6 [...]

2021-08-28 08:46 UTC, opbld30 commented
Docs Build status updates of commit _[f81a3eb](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/f81a3eb2a1afec354d079af276bcd1ee20da67e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-external-post-connections.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalitem-create.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalitem-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-create?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-identity-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-identity-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-identity-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalconnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/overview.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/concepts/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/overview?branch=pr-en-us-13607) |
[concepts/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/overview?branch=pr-en-us-13607) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108280844592471-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=s04s3jj0cF28d0ZVge9FzrA5gnioHrfFuVgOVsdsopc%3D&st=2021-08-28T08%3A41%3A40Z&se=2021-09-28T0 [...]

2021-08-28 08:58 UTC, opbld33 commented
Docs Build status updates of commit _[9ed174a](https://github.com/sacampbe-msft/microsoft-graph-docs/commits/9ed174aca41976320be0bf1577305f9ea57a7eeb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-13607) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-external-post-connections.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-external-post-connections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-external-post-connections?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalconnection-post-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-get.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalgroup-update.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-externalitem-create.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-externalitem-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-create?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-identity-delete.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/api/externalconnectors-identity-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-identity-delete?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-externalconnectors.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-externalgroup.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-groups?view=graph-rest-1.0&branch=pr-en-us-13607) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/overview.md](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/concepts/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/overview?branch=pr-en-us-13607) |
[concepts/toc.yml](https://github.com/sacampbe-msft/microsoft-graph-docs/blob/sacampbe-addIdentitySyncV1Apis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/overview?branch=pr-en-us-13607) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108280856385052-13607%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=H2rZixuEIYoEo%2B7JOI8RdvKkNl%2FY0XprStcfO7sN0Jg%3D&st=2021-08-28T08%3A53%3A21Z&se=2021-09- [...]

2021-08-28 09:06 UTC, angelgolfer-ms approved these changes
I made a few commits to wrap up the higher priority fixes I noticed, so that I can publish this PR. Please take a look at my commits, and follow up with any other fixes that have been commented but not addressed. Please let me know if you have comments or questions.

2021-08-28 09:07 UTC, merged