Introducing service principal creation policies
microsoftgraph/microsoft-graph-docs pull request #13608
Opened 2021-07-21 19:41 UTC by psignoret

2021-07-21 19:45 UTC, opbld34 commented
Docs Build status updates of commit _[1492699](https://github.com/psignoret/microsoft-graph-docs/commits/1492699d4ca672d0ecd6becc4a75cf24c173550e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceprincipalcreationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107211943433716-13608%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A35%3A03Z&ske=2021-07-26T03%3A40%3A03Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-21T19%3A40%3A21Z&se=2021-08-21T19%3A45%3A21Z&sr=b&sp=r&sig=XvwXcjhgVm1KRrf9M0ju3RWiYFzslYBUGaR2mQoBnWA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 23:27 UTC, opbld32 commented
Docs Build status updates of commit _[d64323d](https://github.com/psignoret/microsoft-graph-docs/commits/d64323d8ebd1b909dde1f09fb35a93e2b1dc9992)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-d17efc36502e6d38d29fc3cff4203da2-32f74f14)
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-6691f65cef27de05a03c70983e8e4152-32f74f14)
[api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policyroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-72702d50608248b7e512712bc1e1bed9-32f74f14)

<a id="d17efc36502e6d38d29fc3cff4203da2-32f74f14"></a>
### [api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md)
 - **Line 25, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/authorizationpolicy-list-defaultuserroleoverrides.md'.`````
 - **Line 26, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/authorizationpolicy-post-defaultuserroleoverrides.md'.`````

<a id="6691f65cef27de05a03c70983e8e4152-32f74f14"></a>
### [api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md)
 - **Line 24, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/defaultuserroleoverride-list.md'.`````
 - **Line 25, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/defaultuserroleoverride-create.md'.`````
 - **Line 26, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/defaultuserroleoverride-get.md'.`````
 - **Line 27, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/defaultuserroleoverride-update.md'.`````
 - **Line 28, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/defaultuserroleoverride-delete.md'.`````
 - **Line 33, Column 267**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'serviceprincipalcreationpolicy.md'.`````

<a id="72702d50608248b7e512712bc1e1bed9-32f74f14"></a>
### [api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policyroot.md)
 - **Line 46, Column 47**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/serviceprincipalcreationpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262325347637-13608%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T04%3A13%3A28Z&ske=2021-08-02T04%3A18%3A28Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T23%3A22%3A13Z&se=2021-08-26T23%3A27%3A13Z&sr=b&sp=r&sig=olsSZwlkqjJjYaMU0rb2NfmVQBwTQV4zE5TeX7jAoS8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 23:31 UTC, opbld34 commented
Docs Build status updates of commit _[280e47d](https://github.com/psignoret/microsoft-graph-docs/commits/280e47d3dbf743de3a3a6816d72cfb9789a936cf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-d17efc36502e6d38d29fc3cff4203da2-e3fb6210)
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-6691f65cef27de05a03c70983e8e4152-e3fb6210)
[api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policyroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-72702d50608248b7e512712bc1e1bed9-e3fb6210)

<a id="d17efc36502e6d38d29fc3cff4203da2-e3fb6210"></a>
### [api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md)
 - **Line 25, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/authorizationpolicy-list-defaultuserroleoverrides.md'.`````
 - **Line 26, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/authorizationpolicy-post-defaultuserroleoverrides.md'.`````

<a id="6691f65cef27de05a03c70983e8e4152-e3fb6210"></a>
### [api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md)
 - **Line 24, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/defaultuserroleoverride-list.md'.`````
 - **Line 25, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/defaultuserroleoverride-create.md'.`````
 - **Line 26, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/defaultuserroleoverride-get.md'.`````
 - **Line 27, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/defaultuserroleoverride-update.md'.`````
 - **Line 28, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/defaultuserroleoverride-delete.md'.`````
 - **Line 33, Column 267**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'serviceprincipalcreationpolicy.md'.`````

<a id="72702d50608248b7e512712bc1e1bed9-e3fb6210"></a>
### [api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policyroot.md)
 - **Line 46, Column 47**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/serviceprincipalcreationpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262329459269-13608%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A35%3A40Z&ske=2021-08-02T02%3A40%3A40Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T23%3A26%3A27Z&se=2021-08-26T23%3A31%3A27Z&sr=b&sp=r&sig=yURFo8o6IHZ6gExKj6HfrGKJgc10rvP022thhzqbTOQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-23 09:50 UTC, opbld31 commented
Docs Build status updates of commit _[4621435](https://github.com/psignoret/microsoft-graph-docs/commits/46214352478d28232e00e772cb02d4eaff6c3449)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-list-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-a7612547094442ccdeec6121e898cdb7-a76aae33)
[api-reference/beta/api/authorizationpolicy-post-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-post-defaultuserroleoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-post-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-d8ab5a039178ef06f6741ed821e38620-a76aae33)
[api-reference/beta/api/defaultuserroleoverride-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-79473c32092a181d4912fab6380abcf4-a76aae33)
[api-reference/beta/api/defaultuserroleoverride-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-7919a27093e48334452038a04f8f1e51-a76aae33)
[api-reference/beta/api/defaultuserroleoverride-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-12112a6dbb859fe2de8dbdef33f499f4-a76aae33)
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-34d5e32fb140d6a82a66d77f634bb571-a76aae33)
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-f62940ef32674450dfa70ada1575a58a-a76aae33)
[api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-31ccc2f71968bac961fc9b6c7c2856ba-a76aae33)
[api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-75271687769d0e1512239fe90783cd7f-a76aae33)
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-6691f65cef27de05a03c70983e8e4152-a76aae33)
[api-reference/beta/resources/serviceprincipalcreationconditionset.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationconditionset.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationconditionset?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-6247653bf75e86e626a18edc6034952f-a76aae33)
[api-reference/beta/resources/serviceprincipalcreationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-2764850beae4332e8079f5ffb5527141-a76aae33)
[api-reference/beta/api/serviceprincipalcreationpolicy-create.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-create?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list.md) | [...]

2021-08-23 11:36 UTC, opbld31 commented
Docs Build status updates of commit _[132f3c3](https://github.com/psignoret/microsoft-graph-docs/commits/132f3c37c2166447f1d80dba5fdd77bf74c94c08)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-list-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-a7612547094442ccdeec6121e898cdb7-7063c1f9)
[api-reference/beta/api/authorizationpolicy-post-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-post-defaultuserroleoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-post-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-d8ab5a039178ef06f6741ed821e38620-7063c1f9)
[api-reference/beta/api/defaultuserroleoverride-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-79473c32092a181d4912fab6380abcf4-7063c1f9)
[api-reference/beta/api/defaultuserroleoverride-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-7919a27093e48334452038a04f8f1e51-7063c1f9)
[api-reference/beta/api/defaultuserroleoverride-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-12112a6dbb859fe2de8dbdef33f499f4-7063c1f9)
[api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-31ccc2f71968bac961fc9b6c7c2856ba-7063c1f9)
[api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-75271687769d0e1512239fe90783cd7f-7063c1f9)
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-6691f65cef27de05a03c70983e8e4152-7063c1f9)
[api-reference/beta/resources/serviceprincipalcreationconditionset.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationconditionset.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationconditionset?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-6247653bf75e86e626a18edc6034952f-7063c1f9)
[api-reference/beta/api/serviceprincipalcreationpolicy-create.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-create?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-update?view=graph-rest-beta&branch=pr-en-us-13608) ( [...]

2021-08-23 11:52 UTC, opbld34 commented
Docs Build status updates of commit _[cf6a102](https://github.com/psignoret/microsoft-graph-docs/commits/cf6a1025c187fd04cbc4ee1952190a8064713d17)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-list-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-a7612547094442ccdeec6121e898cdb7-bc8a8619)
[api-reference/beta/api/authorizationpolicy-post-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-post-defaultuserroleoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-post-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-d8ab5a039178ef06f6741ed821e38620-bc8a8619)
[api-reference/beta/api/defaultuserroleoverride-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-79473c32092a181d4912fab6380abcf4-bc8a8619)
[api-reference/beta/api/defaultuserroleoverride-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-7919a27093e48334452038a04f8f1e51-bc8a8619)
[api-reference/beta/api/defaultuserroleoverride-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-12112a6dbb859fe2de8dbdef33f499f4-bc8a8619)
[api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-31ccc2f71968bac961fc9b6c7c2856ba-bc8a8619)
[api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-75271687769d0e1512239fe90783cd7f-bc8a8619)
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-6691f65cef27de05a03c70983e8e4152-bc8a8619)
[api-reference/beta/resources/serviceprincipalcreationconditionset.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationconditionset.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationconditionset?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-6247653bf75e86e626a18edc6034952f-bc8a8619)
[api-reference/beta/api/serviceprincipalcreationpolicy-create.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-create?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-update?view=graph-rest-beta&branch=pr-en-us-13608) ( [...]

2021-08-23 12:02 UTC, opbld33 commented
Docs Build status updates of commit _[6fc82f7](https://github.com/psignoret/microsoft-graph-docs/commits/6fc82f7dda4698a4d40f6fe4f3651a69c9c568d0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-list-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-a7612547094442ccdeec6121e898cdb7-2817cc40)
[api-reference/beta/api/authorizationpolicy-post-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-post-defaultuserroleoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-post-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-d8ab5a039178ef06f6741ed821e38620-2817cc40)
[api-reference/beta/api/defaultuserroleoverride-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-79473c32092a181d4912fab6380abcf4-2817cc40)
[api-reference/beta/api/defaultuserroleoverride-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-7919a27093e48334452038a04f8f1e51-2817cc40)
[api-reference/beta/api/defaultuserroleoverride-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-12112a6dbb859fe2de8dbdef33f499f4-2817cc40)
[api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-31ccc2f71968bac961fc9b6c7c2856ba-2817cc40)
[api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-75271687769d0e1512239fe90783cd7f-2817cc40)
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-6691f65cef27de05a03c70983e8e4152-2817cc40)
[api-reference/beta/api/serviceprincipalcreationpolicy-create.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-create?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-grap [...]

2021-08-23 12:09 UTC, opbld32 commented
Docs Build status updates of commit _[0d0656c](https://github.com/psignoret/microsoft-graph-docs/commits/0d0656c00be2ae0bbd46fe9e23074ae21708d33d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-list-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-a7612547094442ccdeec6121e898cdb7-5a3ad16d)
[api-reference/beta/api/authorizationpolicy-post-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-post-defaultuserroleoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-post-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-d8ab5a039178ef06f6741ed821e38620-5a3ad16d)
[api-reference/beta/api/defaultuserroleoverride-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-79473c32092a181d4912fab6380abcf4-5a3ad16d)
[api-reference/beta/api/defaultuserroleoverride-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-7919a27093e48334452038a04f8f1e51-5a3ad16d)
[api-reference/beta/api/defaultuserroleoverride-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-12112a6dbb859fe2de8dbdef33f499f4-5a3ad16d)
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-6691f65cef27de05a03c70983e8e4152-5a3ad16d)
[api-reference/beta/api/serviceprincipalcreationpolicy-create.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-create?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View [...]

2021-08-23 14:23 UTC, opbld31 commented
Docs Build status updates of commit _[86ec16c](https://github.com/psignoret/microsoft-graph-docs/commits/86ec16ce37380695051bfc99a3664e8ad0aa1ffe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/defaultuserroleoverride-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-79473c32092a181d4912fab6380abcf4-e524e2d3)
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) | [Details](#user-content-6691f65cef27de05a03c70983e8e4152-e524e2d3)
[api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-list-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-create.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-create?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationconditionset.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationconditionset?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/psignoret/microsoft-graph-do [...]

2021-08-23 14:28 UTC, opbld34 commented
Docs Build status updates of commit _[c5a69f5](https://github.com/psignoret/microsoft-graph-docs/commits/c5a69f5e9094be1da782b4c4e4fcf051dc781d0f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-list-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-create.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-create?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationconditionset.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationconditionset?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://rev [...]

2021-08-23 15:15 UTC, opbld30 commented
Docs Build status updates of commit _[1aebf82](https://github.com/psignoret/microsoft-graph-docs/commits/1aebf82731461a1339640b22250f101ded5f4a3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-list-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-create.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-create?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationconditionset.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationconditionset?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://rev [...]

2021-08-23 15:52 UTC, opbld34 commented
Docs Build status updates of commit _[627fb25](https://github.com/psignoret/microsoft-graph-docs/commits/627fb25728442478098a7c765436af64f5ac5834)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-list-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-create.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-create?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationconditionset.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationconditionset?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://rev [...]

2021-08-23 16:00 UTC, opbld32 commented
Docs Build status updates of commit _[60df191](https://github.com/psignoret/microsoft-graph-docs/commits/60df191555317ce1fb8cf67ca56859498d2b2a34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-list-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-create.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-create?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationconditionset.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationconditionset?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://rev [...]

2021-08-24 09:12 UTC, opbld33 commented
Docs Build status updates of commit _[9395681](https://github.com/psignoret/microsoft-graph-docs/commits/9395681876e8da6897b0515fbc5a31a52ba4b5d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-list-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-create.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-create?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationconditionset.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationconditionset?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://rev [...]

2021-08-24 17:11 UTC, opbld34 commented
Docs Build status updates of commit _[04cadef](https://github.com/psignoret/microsoft-graph-docs/commits/04cadef082b306443d73a8fb28326fd3c01b58fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-list-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-create.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-create?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationconditionset.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationconditionset?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationpolicy.md) | :white_check_mark:Suc [...]

2021-08-25 13:10 UTC, FaithOmbongi requested changes
Left a few comments.
- You've introduced new permissions: you should document them in the permissions reference table.
- I'll confirm two of your file names but I think they should be differently named.

2021-08-25 13:10 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalcreationpolicy-list.md
> +title: "List servicePrincipalCreationPolicies"
Let me first confirm with Laura & Angela but I think the correct file name is **policies-list-serviceprincipalcreationpolicies.md**

2021-08-31 09:05 UTC, opbld31 commented
Docs Build status updates of commit _[2f7323a](https://github.com/psignoret/microsoft-graph-docs/commits/2f7323a3413864889e5f02625312c9e4238c5844)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2bf4539c)

<a id="2bf4539c"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108310905143565-13608%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Uvz0aCDLwEdIX10sWFbhV7%2BVohpdfeQ8AGd7H%2FrZFZ8%3D&st=2021-08-31T09%3A00%3A33Z&se=2021-10-01T09%3A05%3A33Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-31 09:13 UTC, opbld30 commented
Docs Build status updates of commit _[03147c5](https://github.com/psignoret/microsoft-graph-docs/commits/03147c5209bda91f9c095567a7a95272d64c4a3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-list-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-create.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-create?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationconditionset.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationconditionset?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationpolicy.md) | :white_check_mark:Suc [...]

2021-09-01 08:45 UTC, FaithOmbongi requested changes
Just minor changes and it'll be good to go.
- Left comments for fixes to boilerplate texts in request body sections of Create and Update topics. The wrong texts were because of a bug in the stub generator.
- I confirmed the following filename changes:
     - serviceprincipalcreationpolicy-list.md > **policyroot-list-serviceprincipalcreationpolicies.md**
     - serviceprincipalcreationpolicy-create.md > **policyroot-post-serviceprincipalcreationpolicies.md**
- Left comments to change the includes and excludes topic titles to **{Operation} includes** e.g. Create includes, Delete excludes; following the [TOC and topic title guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title).
- Document the **Policy.ReadWrite.ServicePrincipalCreate** permission in the permissions reference.
- BTW, I see some new files have Abhijeet as the author. Hope this is correct?

**- ASK:** Kindly update all your localization metadata from `localization_priority: Normal` to `ms.localizationpriority: medium`. A repo-wide update is underway & your PR might be merged after it's complete.

2021-09-01 08:45 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md
> +The following table shows the properties that are required when you create the [servicePrincipalCreationConditionSet](../resources/serviceprincipalcreationconditionset.md).
Correcting the wrong stub gen boilerplate text
```suggestion
In the request body, supply a JSON representation of the [servicePrincipalCreationConditionSet](../resources/serviceprincipalcreationconditionset.md) object. You can specify the following properties when creating a [servicePrincipalCreationConditionSet](../resources/serviceprincipalcreationconditionset.md).
```

2021-09-01 08:45 UTC, FaithOmbongi commented on api-reference/beta/resources/serviceprincipalcreationconditionset.md
> +| applicationTenantIds | String collection | A list of Azure Active Directory tenant IDs for the tenant where the application is registered, or a list with the single value `all` to match with applic
```suggestion
| applicationIds | String collection | A list of **appId** values for the applications to match with, or a list with the single value `all` to match any application. Default is the single value `all`. Optional. |
|applicationPublisherIds | String collection | A list of Microsoft Partner Network (MPN) IDs for verified publishers of the application, or a list with the single value `all` to match with applications from any publisher. Default is the single value `all`. Optional.|
| applicationsFromVerifiedPublisherOnly | Boolean | Set to `true` to only match on applications with a verified publisher. Set to `false` to match on any application, even if it does not have a verified publisher. Default is `false`. Optional. |
| applicationTenantIds | String collection | A list of Azure Active Directory tenant IDs for the tenant where the application is registered, or a list with the single value `all` to match with applications registered in any tenant. A service principal representing an application registered in any of the tenants identified in this list will match the condition set. Default is the single value `all`. Optional. |
```

2021-09-01 08:45 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md
> +| applicationTenantIds | String collection | A list of Azure Active Directory tenant IDs in which the application is registered, or a list with the single value `all` to match with applications regis
Updating the table to complete the boilerplate text. Removing **id** because it's read-only.
```suggestion
| applicationIds | String collection | A list of **appId** values for the applications to match with, or a list with the single value `all` to match any application. Default is the single value `all`. Optional. |
|applicationPublisherIds | String collection | A list of Microsoft Partner Network (MPN) IDs for verified publishers of the application, or a list with the single value `all` to match with applications from any publisher. Default is the single value `all`. Optional. |
| applicationsFromVerifiedPublisherOnly | Boolean | Set to `true` to only match on applications with a verified publisher. Set to `false` to match on any application, even if it does not have a verified publisher. Default is `false`.  Optional.|
| applicationTenantIds | String collection | A list of Azure Active Directory tenant IDs in which the application is registered, or a list with the single value `all` to match with applications registered in any tenant. Default is the single value `all`. Optional. |
```

2021-09-01 08:45 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md
> +# Delete from servicePrincipalCreationPolicy includes
See comment in *-list-includes.md about the guidance
```suggestion
title: "Delete includes"
description: "Deletes an included condition set from service principal creation policy."
localization_priority: Normal
doc_type: apiPageType
ms.prod: "identity-and-sign-in"
author: "psignoret"
---

# Delete includes
```

2021-09-01 08:45 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md
> +# Delete from servicePrincipalCreationPolicy excludes
See comment in *-list-includes.md on applying the guidance
```suggestion
title: "Delete excludes"
description: "Deletes an excluded condition set from service principal creation policy."
localization_priority: Normal
doc_type: apiPageType
ms.prod: "identity-and-sign-in"
author: "psignoret"
---

# Delete excludes
```

2021-09-01 08:45 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md
> +# List servicePrincipalCreationPolicy excludes
See comment in -list-includes.md about the guidance.
```suggestion
title: "List excludes"
description: "Retrieve the condition sets that describe conditions which are excluded from the service principal creation policy."
author: "psignoret"
localization_priority: Normal
ms.prod: "identity-and-sign-in"
doc_type: apiPageType
---

# List excludes
```

2021-09-01 08:45 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md
> +# Create in servicePrincipalCreationPolicy excludes
See comment in *-list-includes.md about the guidance.
```suggestion
title: "Create excludes"
description: "Add conditions under which a service principal creation event is excluded from a service principal creation policy."
author: "psignoret"
localization_priority: Normal
ms.prod: "identity-and-sign-in"
doc_type: apiPageType
---

# Create excludes
```

2021-09-01 08:45 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +                - name: Delete from excludes
Following the guidance
```suggestion
                - name: Create includes
                  href: api/serviceprincipalcreationpolicy-post-includes.md
                - name: Delete includes
                  href: api/serviceprincipalcreationpolicy-delete-includes.md
                - name: List excludes
                  href: api/serviceprincipalcreationpolicy-list-excludes.md
                - name: Create excludes
                  href: api/serviceprincipalcreationpolicy-post-excludes.md
                - name: Delete excludes
```

2021-09-01 08:45 UTC, FaithOmbongi commented on api-reference/beta/api/serviceprincipalcreationpolicy-create.md
> +|Delegated (work or school account) | Policy.ReadWrite.ServicePrincipalCreate |
Don't forget to document **Policy.ReadWrite.ServicePrincipalCreate** in the permissions reference.

2021-09-01 08:45 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **servicePrincipalCreationPolicies** relationship to the [policies](https://docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta) sing
```suggestion
          "Description": "Added the **servicePrincipalCreationPolicies** relationship to the [policies](https://docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta) singleton.",
```

2021-09-01 08:52 UTC, FaithOmbongi requested changes
I missed one.

2021-09-01 08:52 UTC, FaithOmbongi commented on api-reference/beta/api/defaultuserroleoverride-update.md
> +|rolePermissions|[unifiedRolePermission](../resources/unifiedrolepermission.md) collection| The list of [role permissions](../resources/unifiedrolepermission.md) which indicate [users' default permis
Replacing the wrong boilerplate text provided by stub gen.
```suggestion
In the request body, supply the values for relevant properties that should be updated. Existing properties that are not included in the request body will maintain their previous values or be recalculated based on changes to other property values. For best performance, do not include properties that are not changing.

|Property|Type|Description|
|:---|:---|:---|
|isDefault|Boolean|Indicates whether the Microsoft default setting is in use. Set to `true` to remove overridden **rolePermissions** values and revert back to Microsoft's default setting. Set to `false` when overriding **rolePermissions* to customize [users default permissions](/azure/active-directory/fundamentals/users-default-permissions). Optional.|
|rolePermissions|[unifiedRolePermission](../resources/unifiedrolepermission.md) collection| The list of [role permissions](../resources/unifiedrolepermission.md) which indicate [users' default permissions](/azure/active-directory/fundamentals/users-default-permissions) in the organization, for the scenario identified by the **id** property. Adding, updating, or removing items from  the **rolePermissions** collection can be used to customize the default user permissions for that scenario. Optional. |
```

2021-09-02 13:39 UTC, jasonjoh commented
Docs Build status updates of commit _[eec36fb](https://github.com/psignoret/microsoft-graph-docs/commits/eec36fb887bcc11e4a0334dcaa76673eb202b33d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9b79ae4e)

<a id="9b79ae4e"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021334359493-13608%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=kmrWTPwDBp8dkgxKhhAgBJt65vrIndU%2Bmy42PjLRgVY%3D&st=2021-09-02T13%3A34%3A35Z&se=2021-10-03T13%3A39%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 16:33 UTC, FaithOmbongi commented
@psignoret , bumping this back in your queue because the public schema for this API is live.

2021-10-08 14:00 UTC, opbld32 commented
Docs Build status updates of commit _[8e8ddac](https://github.com/psignoret/microsoft-graph-docs/commits/8e8ddac79f386d6be10a095c67504bd30d74303d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-list-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-create.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-create?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationconditionset.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationconditionset?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationpolicy.md) | :white_check_mark:Suc [...]

2021-12-28 05:32 UTC, FaithOmbongi commented
Reopening this PR because the merge has been delayed by permissions onboarding. Pulling **main** to make it fresh.

2021-12-28 05:33 UTC, opbld31 commented
Docs Build status updates of commit _[fe8ebb0](https://github.com/psignoret/microsoft-graph-docs/commits/fe8ebb061ff261807437b048016864aa10f69fc7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-552ab1c5)

<a id="552ab1c5"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112280532081807-13608%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-28T05%3A33%3A35Z&sr=b&sp=r&sig=miDfkTsOUqLiqWm1gwRmrIOF5Yyz4ZIDy1MqQ%2FNAC8I%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-28 05:41 UTC, opbld31 commented
Docs Build status updates of commit _[bd0d245](https://github.com/psignoret/microsoft-graph-docs/commits/bd0d24525922c14d169d9a5851730d2d674e695e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/authorizationpolicy-list-defaultuserroleoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-list-defaultuserroleoverrides?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/defaultuserroleoverride-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/defaultuserroleoverride-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultuserroleoverride-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-create.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-create?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-delete.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-get?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-list.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-list?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalcreationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/api/serviceprincipalcreationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalcreationpolicy-update?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/defaultuserroleoverride.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/defaultuserroleoverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserroleoverride?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationconditionset.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalcreationconditionset?view=graph-rest-beta&branch=pr-en-us-13608) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipalcreationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-sp-create/api-reference/beta/resources/serviceprincipalcreationpolicy.md) | :white_check_mark:Suc [...]

2022-04-17 15:00 UTC, closed without merging