Update continuousaccessevaluationpolicy-update.md
microsoftgraph/microsoft-graph-docs pull request #13658
Opened 2021-07-27 23:26 UTC by lujiangfeng666

Place holder

2021-07-27 23:28 UTC, opbld34 commented
Docs Build status updates of commit _[d002ba2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d002ba2d879e2eda84908cad5fd31765a7de420f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/continuousaccessevaluationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jay-CAE/api-reference/beta/api/continuousaccessevaluationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/continuousaccessevaluationpolicy-update?view=graph-rest-beta&branch=pr-en-us-13658) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107272326439395-13658%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A39%3A48Z&ske=2021-08-02T02%3A44%3A48Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-27T23%3A23%3A21Z&se=2021-08-27T23%3A28%3A21Z&sr=b&sp=r&sig=EN7ufKC1PY4tWo2y81sHtOGPW5Xa3Uq%2BoICCg8bQwxA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 15:29 UTC, FaithOmbongi requested changes

2021-08-04 15:29 UTC, FaithOmbongi commented on api-reference/beta/api/continuousaccessevaluationpolicy-update.md
> +> This API has a [known issue](/graph/known-issues#permissions) related to permissions.
Demo

2021-08-04 15:32 UTC, FaithOmbongi approved these changes

2021-08-04 15:49 UTC, FaithOmbongi requested changes
@lujiangfeng666 , kindly confirm if Policy.Read.All is a valid permission for this operation.

2021-08-04 18:09 UTC, lujiangfeng666 commented
This is just a place holder for future changes

2021-10-04 19:33 UTC, FaithOmbongi approved these changes

2021-10-05 02:06 UTC, merged