July trains - error codes and required property
microsoftgraph/microsoft-graph-docs pull request #13703
Opened 2021-07-31 13:12 UTC by cristobal-buenrostro

This PR is related to the issues below:

https://github.com/microsoftgraph/microsoft-graph-docs/issues/13701

https://github.com/microsoftgraph/microsoft-graph-docs/issues/13702

2021-07-31 13:13 UTC, opbld30 commented
Docs Build status updates of commit _[663086a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/663086ae61b18c7c91e440fe4fe1585deaa16ef7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107311312204141-13703%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-30T06%3A08%3A35Z&ske=2021-08-06T06%3A13%3A35Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-31T13%3A08%3A52Z&se=2021-08-31T13%3A13%3A52Z&sr=b&sp=r&sig=Bn6GZJvi4uFBLSMdQHSkYJGMmbWKJF2Uue%2ButgoX8U8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 14:34 UTC, isvargasmsft commented on api-reference/beta/api/educationoutcome-update.md
> +If using **PointsGradeType** and **Points** are updated to be negative or infinite, a `400` error is returned as below.
Isn't this behavior applicable for the POST (create) operation as well? Please confirm and include if applicable.

2021-08-06 14:36 UTC, isvargasmsft commented on api-reference/beta/api/educationoutcome-update.md
> +If using **PointsGradeType** and **Points** are updated to be negative or infinite, a `400` error is returned as below.
This is one of the scenarios when we actually can use passive voice, please rephrase for clarity:

If **PointsGradeType** and **Points** are updated to a negative or infinite value, the method returns a `400` error message.

2021-08-06 14:37 UTC, isvargasmsft commented on api-reference/beta/api/educationoutcome-update.md
> +If using **PointsGradeType** and **Points** are updated to be negative or infinite, a `400` error is returned as below.
Please apply in v1 as well.

2021-08-06 14:39 UTC, isvargasmsft requested changes
Hello @cristobal-buenrostro, 

Thank you very much for your work in this PR. 
1. Please confirm whether this behavior applies to the POST operation as well. 
2. Please rephrase for clarity.

2021-08-12 16:42 UTC, opbld33 commented
Docs Build status updates of commit _[3ba3712](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ba37129c42d8e614f41fab64cab5f24c9cd611e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108121641093007-13703%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=VGCVUQcqbEcgJrwA4yFTpNNTPIjKcd4a%2FN9%2FNeRwI3Y%3D&st=2021-08-12T16%3A37%3A24Z&se=2021-09-12T16%3A42%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-12 16:47 UTC, opbld33 commented
Docs Build status updates of commit _[6648387](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6648387ae269cc02ee681ad965b17375c6b543a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108121646023708-13703%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=D1aoTHKsa0NKJUWi%2B52URRS2fsoCNwQBp1SCpizswHM%3D&st=2021-08-12T16%3A42%3A20Z&se=2021-09-12T16%3A47%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-12 16:49 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationoutcome-update.md
> +If using **PointsGradeType** and **Points** are updated to be negative or infinite, a `400` error is returned as below.
not applicable

2021-08-12 16:50 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationoutcome-update.md
> +If using **PointsGradeType** and **Points** are updated to be negative or infinite, a `400` error is returned as below.
done, changed as suggested in both

2021-08-16 16:17 UTC, isvargasmsft approved these changes

2021-08-17 01:28 UTC, opbld31 commented
Docs Build status updates of commit _[39d42e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39d42e44bbdaf10c3c29c00e0cef10c515ae731a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108170126551977-13703%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=FAFd9KRV3B2hOzC2CcZ3Y2%2B0f0smEogEnfv1t76DuBs%3D&st=2021-08-17T01%3A23%3A58Z&se=2021-09-17T01%3A28%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 01:31 UTC, opbld32 commented
Docs Build status updates of commit _[74abfb9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74abfb9ee12dfecdf55a2fbb223f6de624d5619a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108170128223763-13703%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=YS6b16z%2BPWr9L0CJZjrd3leNUA20otRwK0vYz284o6M%3D&st=2021-08-17T01%3A26%3A32Z&se=2021-09-17T01%3A31%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 01:34 UTC, opbld32 commented
Docs Build status updates of commit _[6c13e1f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c13e1ff985d4bb29e173ea9e5da352c8947eff8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108170132430227-13703%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=tzzJMgQtnkdsSaEnAWCI5DhANxxgepMfhAkgLEZgcX4%3D&st=2021-08-17T01%3A29%3A13Z&se=2021-09-17T01%3A34%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 01:35 UTC, opbld30 commented
Docs Build status updates of commit _[cf3262f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cf3262f26e8bf62ea667888ff818bb964680796d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108170133151399-13703%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=VtL6U7jihoLoMDBVWJepXcG0veAqgoemCTG%2BubnmJP0%3D&st=2021-08-17T01%3A30%3A49Z&se=2021-09-17T01%3A35%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 01:41 UTC, opbld30 commented
Docs Build status updates of commit _[64261ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64261cea2de9f6d861aceb16d7bb340d1190e28e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108170138536118-13703%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=9lAZQcCNCcVCssVagyEeG8PubSn%2BbJbGl8xpZQT7A5I%3D&st=2021-08-17T01%3A36%3A47Z&se=2021-09-17T01%3A41%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 01:43 UTC, opbld32 commented
Docs Build status updates of commit _[fd67284](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fd67284bb28535ad1bf51ecbb5ec37cadfb5a66d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/beta/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-beta&branch=pr-en-us-13703) (graph-rest-beta) |
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignmentresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/july21bugs2/api-reference/v1.0/resources/educationassignmentresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentresource?view=graph-rest-1.0&branch=pr-en-us-13703) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108170139226804-13703%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=fiqB38Iv4NU5s1TdeIv1w3j%2F83c9qbBJOKGuQUa11HQ%3D&st=2021-08-17T01%3A38%3A26Z&se=2021-09-17T01%3A43%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 01:45 UTC, merged