Update auth provider docs for JavaScript
microsoftgraph/microsoft-graph-docs pull request #13719
Opened 2021-08-02 23:41 UTC by nikithauc

2021-08-02 23:43 UTC, opbld31 commented
Docs Build status updates of commit _[251e4ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/251e4ac354fbd4ba4b0eb953c5e6f9a420ab4e58)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nikithauc/auth-providers-js/concepts/sdks/choose-authentication-providers.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-13719) | [Details](#user-content-bc201e57710acc174780333454d7410d-d579f082)

<a id="bc201e57710acc174780333454d7410d-d579f082"></a>
### [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nikithauc/auth-providers-js/concepts/sdks/choose-authentication-providers.md)
 - **Line 32, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /java/api/overview/azure/identity-readme?view=azure-java-stable. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108022341491392-13719%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=A0m3n%2BxtWacIawEgOkbPqdFdCXYzhIEk95Rb8k1gfCM%3D&st=2021-08-02T23%3A38%3A20Z&se=2021-09-02T23%3A43%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 17:37 UTC, jasonjoh requested changes

2021-08-03 17:37 UTC, jasonjoh commented on concepts/sdks/choose-authentication-providers.md
> +const { PublicClientApplication, InteractionType, AccountInfo } = require("@azure/msal-browser");
These render poorly in docs (see the View link in the Conversation tab). Basically the lines are super long and makes it so the user has to scroll the code block horizontally. Try to reduce this by changing these single-line require lines to multi-line, sort of like:

```
const { 
  PublicClientApplication, 
  InteractionType, 
  AccountInfo 
} = require("@azure/msal-browser");
```

2021-08-03 17:37 UTC, jasonjoh commented on concepts/sdks/choose-authentication-providers.md
> +or
This formatting is odd. Break this into two code blocks instead. You can add introductory text to each block.

2021-08-03 17:37 UTC, jasonjoh commented on concepts/sdks/choose-authentication-providers.md
> +const client = Client.initWithMiddleware({
The indentation on this `initWithMiddleware` function looks funky (and on all instances below).

2021-08-06 20:35 UTC, nikithauc commented on concepts/sdks/choose-authentication-providers.md
> +or
@jasonjoh can you please give us an example of how to split this?

2021-08-06 20:35 UTC, nikithauc commented on concepts/sdks/choose-authentication-providers.md
> +const { PublicClientApplication, InteractionType, AccountInfo } = require("@azure/msal-browser");
I have formatted the JS code snippets that I added in this PR

2021-08-06 20:35 UTC, opbld31 commented
Docs Build status updates of commit _[4dcc2e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4dcc2e48f8d29b1a057f18fd1cb9a644b1020639)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nikithauc/auth-providers-js/concepts/sdks/choose-authentication-providers.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-13719) | [Details](#user-content-bc201e57710acc174780333454d7410d-34c53f35)

<a id="bc201e57710acc174780333454d7410d-34c53f35"></a>
### [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nikithauc/auth-providers-js/concepts/sdks/choose-authentication-providers.md)
 - **Line 32, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /java/api/overview/azure/identity-readme?view=azure-java-stable. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108062034101160-13719%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=g%2B2kCAg5QMMLsCJvurvOrKpzflRT8rQm0ci%2Fl6ilk%2Fg%3D&st=2021-08-06T20%3A30%3A53Z&se=2021-09-06T20%3A35%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-09 18:15 UTC, opbld30 commented
Docs Build status updates of commit _[a2afc35](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2afc35099d980eb82173b5cb45fadc78104372c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nikithauc/auth-providers-js/concepts/sdks/choose-authentication-providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-13719) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108091814193865-13719%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=V0n2znZOuiFjatOW%2Foqm%2F2EL5ttfv7UoyHZh%2BUz0icU%3D&st=2021-08-09T18%3A10%3A43Z&se=2021-09-09T18%3A15%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-09 18:31 UTC, jasonjoh commented on concepts/sdks/choose-authentication-providers.md
> +or
Sure. What I'm referring to is in the middle of a code block you just have a random `or` line, which if I cut/paste this block into an IDE is going to cause an error :D. You can instead create two distinct code blocks for the two scenarios. I did something similar for .NET in this topic, under client credentials provider. See https://github.com/microsoftgraph/microsoft-graph-docs/pull/13733/files

2021-08-09 20:01 UTC, nikithauc commented on concepts/sdks/choose-authentication-providers.md
> +or
Thank you for the explanation! 
 
Please verify now

2021-08-09 20:02 UTC, opbld31 commented
Docs Build status updates of commit _[4157a2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4157a2b8adefdfc2e8b6a63d9a0c9cc10fcedeb9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nikithauc/auth-providers-js/concepts/sdks/choose-authentication-providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-13719) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108092000587258-13719%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=43nF2isTXf5Ip3w9oUhNFG5FhncoojuTWDU8PwSHCf4%3D&st=2021-08-09T19%3A57%3A20Z&se=2021-09-09T20%3A02%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-09 20:13 UTC, jasonjoh requested changes

2021-08-09 20:13 UTC, jasonjoh commented on concepts/sdks/choose-authentication-providers.md
> +```
change this line to ```javascript so that the code block gets the right syntax highlighting.

2021-08-09 20:13 UTC, jasonjoh commented on concepts/sdks/choose-authentication-providers.md
> +const credential = new AuthorizationCodeCredential(
Creating `credential` should be before creating `authProvider`

2021-08-09 20:23 UTC, nikithauc commented on concepts/sdks/choose-authentication-providers.md
> +const credential = new AuthorizationCodeCredential(
Done

2021-08-09 20:23 UTC, opbld32 commented
Docs Build status updates of commit _[033752f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/033752f546a7d7a86ae9eb07a5f80837bea3000d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nikithauc/auth-providers-js/concepts/sdks/choose-authentication-providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-13719) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108092022053453-13719%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=mWSCFSp2I80SBVUZjDBl1uKgbBh1zdvRYicmioLwoS0%3D&st=2021-08-09T20%3A18%3A49Z&se=2021-09-09T20%3A23%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-10 12:26 UTC, opbld33 commented
Docs Build status updates of commit _[70d9d25](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70d9d254944137e7a8f02d7ec22e3773e3ac5745)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nikithauc/auth-providers-js/concepts/sdks/choose-authentication-providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-13719) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108101224002879-13719%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=88XCt3JDs6zVFvjKUvZt2eDV%2BBz66wy7LobseJSXQuk%3D&st=2021-08-10T12%3A21%3A29Z&se=2021-09-10T12%3A26%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-12 20:06 UTC, nikithauc commented
@jasonjoh I have addressed you comments. Can you please review the changes?

2021-08-17 18:33 UTC, jasonjoh approved these changes

2021-08-17 18:34 UTC, opbld33 commented
Docs Build status updates of commit _[2d18060](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d18060ff06cb37eb4ec742a88243edeecd89b4e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nikithauc/auth-providers-js/concepts/sdks/choose-authentication-providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-13719) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108171833065212-13719%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=7nJnEDk72AwfNKd6FnwLyDxmcGSJDR09EWRgB0V4i%2FA%3D&st=2021-08-17T18%3A29%3A39Z&se=2021-09-17T18%3A34%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-18 01:28 UTC, merged