Move Refiner and Sort Documents from beta documents to V1 documents
microsoftgraph/microsoft-graph-docs pull request #13726
Opened 2021-08-03 11:28 UTC by yiwenwang-ms

Ready to move refiner and sort from beta endpoint to V1 endpoint, need to synchronize refiner and sort documents from beta to v1.

2021-08-03 11:30 UTC, opbld34 commented
Docs Build status updates of commit _[93e0b63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/93e0b63e8f4b9725ff48dbf4521a6fd2eb6b5d04)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/search-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) | [Details](#user-content-ba5725641f54b1ce64d702d68f006042-58090dd3)
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchrequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) | [Details](#user-content-b15c829e352851ac789aa235b9790e9b-58090dd3)
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |

<a id="ba5725641f54b1ce64d702d68f006042-58090dd3"></a>
### [api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/search-api-overview.md)
 - **Line 115, Column 343**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'sortproperty.md'.`````
 - **Line 117, Column 35**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'sortproperty.md'.`````
 - **Line 125, Column 183**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './aggregationoption.md'.`````
 - **Line 125, Column 320**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'searchBucket.md'.`````
 - **Line 129, Column 60**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'searchBucket.md'.`````
 - **Line 129, Column 192**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'searchBucket.md'.`````

<a id="b15c829e352851ac789aa235b9790e9b-58090dd3"></a>
### [api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchrequest.md)
 - **Line 26, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'aggregationOption.md'.`````
 - **Line 27, Column 291**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'searchBucket.md'.`````
 - **Line 35, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'sortProperty.md'.`````
 - **Line 24, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108031128030105-13726%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=w%2FCkuJslz7ymcATOC5sv9IxOU59diqPWghQlshBHO0o%3D&st=2021-08-03T11%3A25%3A30Z&se=2021-09-03T11%3A30%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 11:40 UTC, opbld32 commented
Docs Build status updates of commit _[72f4580](https://github.com/microsoftgraph/microsoft-graph-docs/commits/72f4580b82008155d556b05b14258aa31915312d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/aggregationoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/aggregationoption.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aggregationoption?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) | [Details](#user-content-a888463569569d7d565f4f9a14275e9e-eb8a3088)
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) | [Details](#user-content-b15c829e352851ac789aa235b9790e9b-eb8a3088)
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchbucket.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchbucket?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sortproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/sortproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sortproperty?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |

<a id="a888463569569d7d565f4f9a14275e9e-eb8a3088"></a>
### [api-reference/v1.0/resources/aggregationoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/aggregationoption.md)
 - **Line 24, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'bucketaggregationdefinition.md'.`````

<a id="b15c829e352851ac789aa235b9790e9b-eb8a3088"></a>
### [api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchrequest.md)
 - **Line 24, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108031138433065-13726%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=SRsfTKyRtdnOVZIAi%2FYE600UFTDG07u3YZ%2FwzbMm8H4%3D&st=2021-08-03T11%3A35%3A09Z&se=2021-09-03T11%3A40%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 11:46 UTC, opbld31 commented
Docs Build status updates of commit _[242f929](https://github.com/microsoftgraph/microsoft-graph-docs/commits/242f929fec5867b179111eb7e8a6e93f7aa3c13f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/aggregationoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/aggregationoption.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aggregationoption?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) | [Details](#user-content-a888463569569d7d565f4f9a14275e9e-2eec16b8)
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchbucket.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchbucket?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sortproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/sortproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sortproperty?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |

<a id="a888463569569d7d565f4f9a14275e9e-2eec16b8"></a>
### [api-reference/v1.0/resources/aggregationoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/aggregationoption.md)
 - **Line 24, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'bucketaggregationdefinition.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108031144340136-13726%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=YprVjF6O59tMRrl74o933Y8d4W7NypZQBs0vyQA%2Fcmk%3D&st=2021-08-03T11%3A41%3A55Z&se=2021-09-03T11%3A46%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 11:52 UTC, opbld30 commented
Docs Build status updates of commit _[1944a11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1944a11f177bc3fd3b0c26fefea4f03ee2a7e52a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aggregationoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/aggregationoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aggregationoption?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/bucketaggregationdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/bucketaggregationdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bucketaggregationdefinition?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/bucketaggregationrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/bucketaggregationrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bucketaggregationrange?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchbucket.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchbucket?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sortproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/sortproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sortproperty?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108031145587937-13726%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=5JlLwMFZFP0iPwH8uaC%2BMMgP21YeUtNl5KoKoyOqgF4%3D&st=2021-08-03T11%3A47%3A37Z&se=2021-09-03T11%3A52%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 01:11 UTC, ZChristine commented on api-reference/v1.0/resources/search-api-overview.md
> +|[Refine results using aggregations](#refine-results-using-aggregations)|
double check whether "**aggregations** |" will be put in the below column

2021-08-04 01:18 UTC, ZChristine approved these changes
Looking good. i leave comments that should take care for

2021-08-04 02:47 UTC, opbld33 commented
Docs Build status updates of commit _[ea3bf7d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea3bf7d36ad52195413b4cbb513c56397939302d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aggregationoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/aggregationoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aggregationoption?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/bucketaggregationdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/bucketaggregationdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bucketaggregationdefinition?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/bucketaggregationrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/bucketaggregationrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bucketaggregationrange?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchbucket.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchbucket?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sortproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/sortproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sortproperty?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108040241529234-13726%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=bJrdsGV8h%2FSK%2B%2FVeM2C95WnabBNhE%2FqQCgyEuefT44U%3D&st=2021-08-04T02%3A42%3A34Z&se=2021-09-04T02%3A47%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 02:51 UTC, yiwenwang-ms commented on api-reference/v1.0/resources/search-api-overview.md
> +|[Refine results using aggregations](#refine-results-using-aggregations)|
Thanks for your kindly review, resolved.

2021-08-11 15:17 UTC, opbld34 commented
Docs Build status updates of commit _[a1ceebb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a1ceebbcbfb6f365c9a87cd23c3e30ec0c09a706)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aggregationoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/aggregationoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aggregationoption?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/bucketaggregationdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/bucketaggregationdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bucketaggregationdefinition?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/bucketaggregationrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/bucketaggregationrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bucketaggregationrange?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchbucket.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchbucket?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sortproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/sortproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sortproperty?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108111516175976-13726%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=4IJgsy2eKwyHQxzLjjJnEREWQukKK5ijeVCudEtNUtk%3D&st=2021-08-11T15%3A12%3A40Z&se=2021-09-11T15%3A17%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-14 02:48 UTC, opbld31 commented
Docs Build status updates of commit _[e611ab4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e611ab429496212ae0c9bbcf91a3050687d77c30)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aggregationoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/aggregationoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aggregationoption?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/bucketaggregationdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/bucketaggregationdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bucketaggregationdefinition?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/bucketaggregationrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/bucketaggregationrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bucketaggregationrange?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchbucket.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchbucket?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sortproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/sortproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sortproperty?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108140247040987-13726%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=SCJcL%2FNNyPtcvqxp77v5bjrBCXQ%2BrsYQ8dnOjuU5atY%3D&st=2021-08-14T02%3A43%3A21Z&se=2021-09-14T02%3A48%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-16 05:25 UTC, opbld34 commented
Docs Build status updates of commit _[1c4a930](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c4a930cf66bfdcceebab88ef4807815d8ee9cf4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aggregationoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/aggregationoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aggregationoption?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/bucketaggregationdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/bucketaggregationdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bucketaggregationdefinition?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/bucketaggregationrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/bucketaggregationrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bucketaggregationrange?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchbucket.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchbucket?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sortproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/sortproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sortproperty?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108160523559677-13726%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=mHOrNjfn0DWatx9MkUmItdYVh%2Fw0BrJ9eooFY6VZPIA%3D&st=2021-08-16T05%3A20%3A17Z&se=2021-09-16T05%3A25%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-16 05:27 UTC, opbld34 commented
Docs Build status updates of commit _[ae3cacc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae3cacc606d71fc22d6e747fd59615126197d26c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aggregationoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/aggregationoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aggregationoption?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/bucketaggregationdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/bucketaggregationdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bucketaggregationdefinition?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/bucketaggregationrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/bucketaggregationrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bucketaggregationrange?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchbucket.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchbucket?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sortproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/sortproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sortproperty?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108160526278257-13726%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=h%2B4uHz9Dc4vdVa1DBDUaJ7mc7MgpsBnxA6XiAh3SDAg%3D&st=2021-08-16T05%3A22%3A44Z&se=2021-09-16T05%3A27%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-23 19:38 UTC, opbld31 commented
Docs Build status updates of commit _[cb59ff5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb59ff5fb2a28929becd34d4b32a2f5c6d219eb7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/aggregationoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/aggregationoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aggregationoption?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/bucketaggregationdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/bucketaggregationdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bucketaggregationdefinition?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/bucketaggregationrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/bucketaggregationrange.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bucketaggregationrange?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchbucket.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchbucket.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchbucket?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sortproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/api-reference/v1.0/resources/sortproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sortproperty?view=graph-rest-1.0&branch=pr-en-us-13726) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-03-graphSearch-moveSortAndRefinerToGA/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108231937032180-13726%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=ui99RglozStvWLKma6qO72TIBiEswNuY2adNM9ehsWc%3D&st=2021-08-23T19%3A33%3A46Z&se=2021-09-23T19%3A38%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-31 15:05 UTC, isvargasmsft commented on api-reference/v1.0/resources/aggregationoption.md
> +Specifies which aggregations should be returned alongside the search results.
Lines 3 and 14:
1. The description in these 2 lines should match. Remember this description is used by search engines to display results. 
2. If the beta topic has the same issue, please leverage this PR to fix it as well.

2021-08-31 15:07 UTC, isvargasmsft commented on api-reference/v1.0/resources/aggregationoption.md
> +|field|String|Specifies the field in the schema of the specified entity type that aggregation should be computed on. Required.|
Line 20: This description is not easy to understand for a global audience. Please consider readers that only know basic English. For instance, please [avoid passive voice](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=25523) and use simple verbs.

2021-08-31 15:11 UTC, isvargasmsft commented on api-reference/v1.0/resources/aggregationoption.md
> +|bucketDefinition|[bucketAggregationDefinition](bucketaggregationdefinition.md)|Specifies the criteria to compute an aggregation. Optional.|
Please order the properties alphabetically.

2021-08-31 15:18 UTC, isvargasmsft commented on api-reference/v1.0/api/search-query.md
Do we have a topic for the searchEntity resource type? If we don't have one, please create one.

2021-08-31 15:54 UTC, isvargasmsft commented on api-reference/v1.0/resources/bucketaggregationdefinition.md
> +Specifies details to aggregate search results.
Lines 3 and 14: 
1. Both descriptions should match. 
2. Please avoid using passive voice. 
3. Remember to make as simple as possible for search engines. 

Please check if the beta topics have the same issue.

2021-08-31 15:55 UTC, isvargasmsft commented on api-reference/v1.0/resources/bucketaggregationdefinition.md
> +|ranges|[bucketAggregationRange](bucketaggregationrange.md) collection|Specifies the manual ranges to compute the aggregations. This is only valid for non-string refiners of date or numeric type. Opt
Please arrange these properties alphabetically.

2021-08-31 16:44 UTC, isvargasmsft commented on api-reference/v1.0/resources/searchbucket.md
> +Represents a container for one or more search results that share the same value for the entity field that aggregates them.
Lines 3 and 14: Similar observation. I like the description in line 14 better.

2021-08-31 16:45 UTC, isvargasmsft commented on api-reference/v1.0/resources/searchbucket.md
> +|aggregationFilterToken|String| A token containing the encoded filter to aggregate search matches by the specific **key** value. To use the filter, pass the token as part of the **aggregationFilter**
Please order these properties alphabetically.

2021-08-31 16:50 UTC, isvargasmsft commented on api-reference/v1.0/resources/sortproperty.md
> +Represents the sort options to order search results.
Lines 3 and 14: Please rephrase to: Indicates the order to sort search results.

2021-08-31 16:56 UTC, isvargasmsft commented on changelog/Microsoft.MicrosoftSearch.json
> +          "ApiChange": "EnumType",
Line 239: Please use `Enum type`, with a space. Guidance here: https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=25523

2021-08-31 16:57 UTC, isvargasmsft commented on changelog/Microsoft.MicrosoftSearch.json
> +          "Target": "entityType"
Please clarify this entry. What are you deleting from where exactly? It is not clear.

2021-08-31 17:10 UTC, isvargasmsft commented on changelog/Microsoft.MicrosoftSearch.json
> +          "ApiChange": "ComplexType",
ApiChange values for ComplexTypes should be Resource. Please make the change in the other entries as well.

2021-08-31 17:13 UTC, isvargasmsft requested changes
Thank you very much for your work on this PR. 

Please take a look at my comments and let me know if you have any questions. 

Kind regards, 

Isaac Vargas

2021-09-06 06:00 UTC, yiwenwang-ms commented on api-reference/v1.0/resources/aggregationoption.md
> +Specifies which aggregations should be returned alongside the search results.
Hi @isvargasmsft, sorry, I lost the permission for editing the branches I created in this repo, I forked a new repo and created a new pull request for it. Please help have a look. This comment fixed in the new PR.
https://github.com/microsoftgraph/microsoft-graph-docs/pull/14159

2021-09-06 06:04 UTC, yiwenwang-ms commented on api-reference/v1.0/resources/aggregationoption.md
> +|field|String|Specifies the field in the schema of the specified entity type that aggregation should be computed on. Required.|
This line changed to: "Computes aggregation on the field while the field exists in current entity type. Required."

2021-09-06 06:05 UTC, yiwenwang-ms commented on api-reference/v1.0/resources/aggregationoption.md
> +|bucketDefinition|[bucketAggregationDefinition](bucketaggregationdefinition.md)|Specifies the criteria to compute an aggregation. Optional.|
Resolved.

2021-09-06 06:06 UTC, yiwenwang-ms commented on api-reference/v1.0/resources/aggregationoption.md
> +Specifies which aggregations should be returned alongside the search results.
Please help leave new comments in the #14159, I will abandon this PR in the future.

2021-09-06 06:09 UTC, yiwenwang-ms commented on api-reference/v1.0/api/search-query.md
Hi @isvargasmsft , little confusing about it. do you mean I need a new md file to introduce the searchEntity and link here?
Actually the detail description for these search entities were introduced in the search-api-overviw. Please refer below:
https://docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0

2021-09-06 06:09 UTC, yiwenwang-ms commented on api-reference/v1.0/resources/bucketaggregationdefinition.md
> +Specifies details to aggregate search results.
Resolved, and also make same change in beta documents

2021-09-06 06:10 UTC, yiwenwang-ms commented on api-reference/v1.0/resources/bucketaggregationrange.md
> +description: "Enables to specify some manual ranges in the aggregation request. This in only applicable to non string refiners : numeric and dates."
Resolved, and also make same change in beta documents. keep the line 14.

2021-09-06 06:10 UTC, yiwenwang-ms commented on api-reference/v1.0/resources/bucketaggregationrange.md
> +Specifies the lower and upper limit to a range for aggregating search results. Applies to only refiners of the date or numeric type.
Resolved, and also make same change in beta documents.

2021-09-06 06:11 UTC, yiwenwang-ms commented on api-reference/v1.0/resources/searchbucket.md
> +Represents a container for one or more search results that share the same value for the entity field that aggregates them.
Resolved, and also make same change in beta documents. Keep the line 14.

2021-09-06 06:11 UTC, yiwenwang-ms commented on api-reference/v1.0/resources/searchbucket.md
> +|aggregationFilterToken|String| A token containing the encoded filter to aggregate search matches by the specific **key** value. To use the filter, pass the token as part of the **aggregationFilter**
Resolved

2021-09-06 06:11 UTC, yiwenwang-ms commented on changelog/Microsoft.MicrosoftSearch.json
> +          "ApiChange": "EnumType",
Resolved

2021-09-06 06:14 UTC, yiwenwang-ms commented on changelog/Microsoft.MicrosoftSearch.json
> +          "Target": "entityType"
Actually, the change log generated by the pipeline build tools, and the unknownFutureValue is a predefined value which mapped to unknownfuturevalue.  Correct the unknownfuturevalue to unknownFutureValue directly, so the change log appeared. I removed it from our change logs.

2021-09-06 06:14 UTC, yiwenwang-ms commented on changelog/Microsoft.MicrosoftSearch.json
> +          "ApiChange": "ComplexType",
Resolved.

2021-09-06 06:15 UTC, yiwenwang-ms commented on api-reference/v1.0/resources/sortproperty.md
> +Represents the sort options to order search results.
thank you, resolved.

2021-09-12 14:51 UTC, yiwenwang-ms commented
Instead by https://github.com/microsoftgraph/microsoft-graph-docs/pull/14159

2021-09-12 14:51 UTC, closed without merging