Exposed Semantic Label For Graph Search Api V1.0
microsoftgraph/microsoft-graph-docs pull request #13749
Opened 2021-08-05 11:07 UTC by ZChristine

2021-08-05 11:09 UTC, opbld30 commented
Docs Build status updates of commit _[fac9287](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fac92879ee7032b0b6cc669d6343b41f297bc5c2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f9ed3acf)

<a id="f9ed3acf"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108051107581648-13749%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=9042rjDRv0jlHpTZAcFLpOiOueiuk5hna%2F7tcfDgnCI%3D&st=2021-08-05T11%3A04%3A18Z&se=2021-09-05T11%3A09%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 11:33 UTC, opbld34 commented
Docs Build status updates of commit _[7cb6987](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7cb6987284011b30efbf3212b1e4068bb7c6a82a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) | [Details](#user-content-b15c829e352851ac789aa235b9790e9b-62db721e)
[api-reference/v1.0/resources/resulttemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplate?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplateoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplateoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplateoption?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |

<a id="b15c829e352851ac789aa235b9790e9b-62db721e"></a>
### [api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md)
 - **Line 29, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108051131386378-13749%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=h5SJ%2F6cDoQGb%2FWPEM%2BstTQvs8TIO6Z5c7kZZMR2rrEM%3D&st=2021-08-05T11%3A28%3A50Z&se=2021-09-05T11%3A33%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 12:15 UTC, opbld32 commented
Docs Build status updates of commit _[eeb6583](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eeb65839cbfb7e8c38ca99bb92ac4da3f7bf9d6c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) | [Details](#user-content-b15c829e352851ac789aa235b9790e9b-defdd677)
[api-reference/v1.0/resources/resulttemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplate?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplateoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplateoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplateoption?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |

<a id="b15c829e352851ac789aa235b9790e9b-defdd677"></a>
### [api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md)
 - **Line 29, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108051213048346-13749%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=DD5LrZMFY6E96GLIt0EUMrkDWbp4QlKXgSNBhaBog%2Fo%3D&st=2021-08-05T12%3A10%3A33Z&se=2021-09-05T12%3A15%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 04:33 UTC, opbld32 commented
Docs Build status updates of commit _[35bcbf2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35bcbf2b3db122b858dd6ae040fe7a2cd5a1a6ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) | [Details](#user-content-b15c829e352851ac789aa235b9790e9b-149418ff)
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alterationresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alterationresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alterationresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alteredquerytoken.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alteredquerytoken.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alteredquerytoken?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplate?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplateoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplateoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplateoption?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalteration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalteration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalteration?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalterationoptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalterationoptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalterationoptions?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresultset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresultset?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |

<a id="b15c829e352851ac789aa235b9790e9b-149418ff"></a>
### [api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md)
 - **Line 29, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108110431483285-13749%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=BqixttwALj467WdNLa%2F6MaxFE%2BFOph1mQikcgpAsVMk%3D&st=2021-08-11T04%3A28%3A18Z&se=2021-09-11T04%3A33%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-12 01:06 UTC, yiwenwang-msai commented on api-reference/v1.0/resources/alterationresponse.md
> +[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]
Remove this one, and apply it to left files for v1 documents.

2021-08-12 01:45 UTC, yiwenwang-msai commented on api-reference/v1.0/resources/alterationresponse.md
> +[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]
Remove the beta notification for v1 document and apply it to changed files.

2021-08-23 09:18 UTC, opbld30 commented
Docs Build status updates of commit _[79405ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/79405cec103682111299dacda208c52abcb47f73)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) | [Details](#user-content-b15c829e352851ac789aa235b9790e9b-f986ad2e)
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alterationresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alterationresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alterationresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alteredquerytoken.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alteredquerytoken.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alteredquerytoken?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplate?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplateoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplateoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplateoption?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalteration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalteration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalteration?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalterationoptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalterationoptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalterationoptions?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresultset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresultset?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |

<a id="b15c829e352851ac789aa235b9790e9b-f986ad2e"></a>
### [api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md)
 - **Line 29, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108230916485967-13749%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=5Fvp77NBzXypajNacfHMI7IuoNt14P2iQAwcPqtzAc4%3D&st=2021-08-23T09%3A13%3A19Z&se=2021-09-23T09%3A18%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId [...]

2021-09-15 08:50 UTC, paulodero commented on changelog/Microsoft.MicrosoftSearch.json
> +        },
Please remove this entry. Should not have been generated. Fix to the generator is being applied.

2021-09-15 08:52 UTC, paulodero commented on changelog/Microsoft.MicrosoftSearch.json
> +        },
```suggestion
```
Please remove this entry. Was not supposed to be autogenerated. Fix is being applied to the generator.

2021-09-15 09:39 UTC, opbld34 commented
Docs Build status updates of commit _[9bd573f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9bd573f2ed1425cdec66c7eebf114f40565a65b2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-66bc2cfb)

<a id="66bc2cfb"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109150937551694-13749%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T09%3A39%3A13Z&sr=b&sp=r&sig=BULNy6XkBihxUwPz3HWlKCC0oaWG3te0RDyGWDZON0I%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 06:16 UTC, opbld30 commented
Docs Build status updates of commit _[61f77ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61f77ce3d17e468debe4bce04d44f6da1c503575)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) | [Details](#user-content-b15c829e352851ac789aa235b9790e9b-39d575ee)
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alterationresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alterationresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alterationresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alteredquerytoken.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alteredquerytoken.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alteredquerytoken?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplate?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplateoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplateoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplateoption?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalteration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalteration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalteration?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalterationoptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalterationoptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalterationoptions?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresultset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresultset?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |

<a id="b15c829e352851ac789aa235b9790e9b-39d575ee"></a>
### [api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md)
 - **Line 31, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109160614567388-13749%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T06%3A16%3A53Z&sr=b&sp=r&sig=qVvsIpYbHQ6NvtQ57boTJrV6iyWBZQr%2FCYjnQYAHqWk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d [...]

2021-09-22 05:41 UTC, opbld30 commented
Docs Build status updates of commit _[0a8d244](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a8d2445582b8eede5d40596548305a74f4d0caf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13749) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-0be94599)
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) | [Details](#user-content-b15c829e352851ac789aa235b9790e9b-0be94599)
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alterationresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alterationresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alterationresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alteredquerytoken.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alteredquerytoken.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alteredquerytoken?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplate?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplateoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplateoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplateoption?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalteration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalteration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalteration?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalterationoptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalterationoptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalterationoptions?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresultset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresultset?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-0be94599"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/beta/api/table-post-rows.md)
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="b15c829e352851ac789aa235b9790e9b-0be94599"></a>
### [api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md)
 - **Line 31, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C [...]

2021-09-22 05:43 UTC, opbld30 commented
Docs Build status updates of commit _[15e9f64](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15e9f6404efa9ad8b9a2f46ede2472554d0f1cd7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13749) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-84bd0284)
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) | [Details](#user-content-b15c829e352851ac789aa235b9790e9b-84bd0284)
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alterationresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alterationresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alterationresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alteredquerytoken.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alteredquerytoken.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alteredquerytoken?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplate?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplateoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplateoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplateoption?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalteration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalteration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalteration?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalterationoptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalterationoptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalterationoptions?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresultset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresultset?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-84bd0284"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/beta/api/table-post-rows.md)
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="b15c829e352851ac789aa235b9790e9b-84bd0284"></a>
### [api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md)
 - **Line 31, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C [...]

2021-09-22 05:49 UTC, opbld34 commented
Docs Build status updates of commit _[df22424](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df224241e5be5f2abf3a42585106a77a1a18e0e9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13749) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-9b4601bd)
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) | [Details](#user-content-b15c829e352851ac789aa235b9790e9b-9b4601bd)
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alterationresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alterationresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alterationresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alteredquerytoken.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alteredquerytoken.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alteredquerytoken?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplate?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplateoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplateoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplateoption?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalteration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalteration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalteration?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalterationoptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalterationoptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalterationoptions?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresultset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresultset?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-9b4601bd"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/beta/api/table-post-rows.md)
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="b15c829e352851ac789aa235b9790e9b-9b4601bd"></a>
### [api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md)
 - **Line 31, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C [...]

2021-09-22 05:51 UTC, opbld32 commented
Docs Build status updates of commit _[4458c7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4458c7fd8a8f2d6b36e9e5261069a47081bda872)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13749) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-b59ded60)
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) | [Details](#user-content-b15c829e352851ac789aa235b9790e9b-b59ded60)
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alterationresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alterationresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alterationresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alteredquerytoken.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alteredquerytoken.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alteredquerytoken?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplate?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplateoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplateoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplateoption?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalteration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalteration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalteration?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalterationoptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalterationoptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalterationoptions?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresultset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresultset?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |

<a id="3d4ef16248555d21d47f9f4aef494875-b59ded60"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/beta/api/table-post-rows.md)
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="b15c829e352851ac789aa235b9790e9b-b59ded60"></a>
### [api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md)
 - **Line 31, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C [...]

2021-11-01 20:25 UTC, JarbasHorst commented
@ZChristine, checking to see if you have any questions regarding some of the feedback I provided?

2021-12-01 15:40 UTC, ZChristine commented on api-reference/v1.0/api/search-query.md
> +|queryAlterationOptions|[searchAlterationOptions](../resources/searchalterationoptions.md)|Query alteration options formatted in a JSON blob that contains two optional flags to for spelling correctio
fix

2021-12-01 15:42 UTC, ZChristine commented on api-reference/v1.0/api/search-query.md
> +- Enable [spell corrections](/graph/search-concept-speller) in search results
fix

2021-12-06 05:58 UTC, ZChristine commented on api-reference/v1.0/resources/search-api-overview.md
> +See [Use search display layout](/graph/search-concept-display-layout) for examples.
change with "See [Use search display layout](/graph/search-concept-display-layout) for examples that show how to render search results."

2021-12-06 06:05 UTC, ZChristine commented on api-reference/v1.0/resources/search.md
> +| [query](../api/search-query.md) | [searchResponse](searchresponse.md)| Executes the query specified in the [searchRequest](../resources/searchrequest.md) |
can you elaborate more on this comment?

2021-12-06 06:41 UTC, opbld34 commented
Docs Build status updates of commit _[2cf3565](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2cf3565528cd83435732f43eed43d1bf151370d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) | [Details](#user-content-b15c829e352851ac789aa235b9790e9b-c0277b60)
[api-reference/beta/resources/alterationresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/beta/resources/alterationresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alterationresponse?view=graph-rest-beta&branch=pr-en-us-13749) (graph-rest-beta) |
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alterationresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alterationresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alterationresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/alteredquerytoken.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/alteredquerytoken.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alteredquerytoken?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplate?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/resulttemplateoption.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/resulttemplateoption.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resulttemplateoption?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalteration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalteration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalteration?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchalterationoptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchalterationoptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchalterationoptions?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresultset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchresultset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresultset?view=graph-rest-1.0&branch=pr-en-us-13749) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |

<a id="b15c829e352851ac789aa235b9790e9b-c0277b60"></a>
### [api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/tong/ExposedSemanticLabelInGraphSearchAPIV1.0/api-reference/v1.0/resources/searchrequest.md)
 - **Line 31, Column 406**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-6-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112060640119404-13749%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-06T06%3A41%3A57Z&sr=b&sp=r&sig=ztzhrnMW1nlzPn3WmZETAhCQj7mvq3DpunnolYliybk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735 [...]

2021-12-07 22:34 UTC, JarbasHorst requested changes

2021-12-07 22:34 UTC, JarbasHorst commented on api-reference/v1.0/resources/searchalterationoptions.md
> +|enableModification|Boolean|Indicates whether spelling modifications are enabled. If enabled, the user will get the search results for the corrected query **when there are no results** for the origin
For clarity, please replace "**when there are no results**" with "*in case of no results*". Also, please use italic instead of bold formatting.

2021-12-07 22:34 UTC, JarbasHorst commented on api-reference/v1.0/resources/searchalterationoptions.md
> +|enableSuggestion|Boolean|Indicates whether spelling suggestions are enabled. If enabled, the user will get the search results for the original search query and suggestions for spelling correction in
For consistency and to improve scanning, please move "enableSuggestion" to come after "enableModification".

2021-12-07 22:34 UTC, JarbasHorst commented on api-reference/v1.0/resources/searchalteration.md
> +|:-------------|:------------|:------------|
For consistency and to improve scanning, properties in the Properties table should be in alphabetical order. Please, alphabetize the list.

2021-12-07 22:34 UTC, JarbasHorst commented on api-reference/v1.0/resources/searchhit.md
> +|resultTemplateId|String|ID of the result template to render the search result. This ID must map to a display layout in the **resultTemplates** dictionary, included in the [searchresponse](searchresp
For clarity, please

- replace "to render" with "used to render"
- replace "this ID" with "The \*\*resultTemplateId\*\* property"
- add "which is" before "included"
- replace "searchresponse" with "searchResponse"
- remove "as well"

2021-12-07 22:34 UTC, JarbasHorst commented on api-reference/v1.0/resources/searchresponse.md
> +|value|[searchResultSet](searchResultSet.md) collection|Represents results from a search query, and the terms used for the query.|
Please, remove the comma.

2021-12-07 22:34 UTC, JarbasHorst commented on api-reference/v1.0/resources/searchresponse.md
> +|queryAlterationResponse|[alterationResponse](alterationResponse.md)|Provides details of query alteration response for spelling correction.|
For consistency with the alterationResponse topic, I recommend you to use "Provides information related to spelling corrections in the alteration response." as the description.

2021-12-07 22:34 UTC, JarbasHorst commented on api-reference/v1.0/resources/searchresultset.md
> +|resultTemplates|[resultTemplate](resultTemplate.md) collection|A dictionary of **resultTemplateIds** and associated values, which include the name and JSON schema of the result templates.
For compatibility, you should also add a pipe on either end of the row.

2021-12-07 22:34 UTC, JarbasHorst commented on api-reference/v1.0/resources/searchresultset.md
> +|resultTemplates|[resultTemplate](resultTemplate.md) collection|A dictionary of **resultTemplateIds** and associated values, which include the name and JSON schema of the result templates.
Please, move "resultTemplates" to come before "searchTerms".

2021-12-07 22:34 UTC, JarbasHorst commented on changelog/Microsoft.MicrosoftSearch.json
> +        {
Please, add a changelog entry for the new parameter "queryAlterationOptions" added to the search-query method. Suggested description:

- Added the \*\*queryAlterationOptions\*\* parameter to the ... method.

2021-12-17 15:19 UTC, isvargasmsft commented
Hello @ZChristine, what's the status of this PR? Do you have any questions regarding the content review?

Kind regards, 

Isaac

2022-01-05 14:25 UTC, closed without merging

2022-01-05 22:50 UTC, Lauragra commented
@ZChristine , just checking, are you planning to open a new PR to document the v1.0 APIs? Some of the appear to be live in the v1.0 schema but we don't currently have published docs for them. Thanks.