Document searchSettings for externalConnection API
microsoftgraph/microsoft-graph-docs pull request #13745
Opened 2021-08-04 23:42 UTC by emzho

We are exposing the searchSettings property for externalConnection resource. This PR will document the new properties and resources.

2021-08-04 23:44 UTC, opbld32 commented
Docs Build status updates of commit _[ed114e9](https://github.com/emzho/microsoft-graph-docs/commits/ed114e9361a971f12696730422f3ba8ed597b349)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-7ab8948c)
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-bfa8da9f0cb03ac977adccbf05e62ed8-7ab8948c)
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-41a097b9c88176e8e085b4c2cf7c3ef8-7ab8948c)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-7ab8948c"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-intune-json.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/externalconnectors-displaytemplate.md(3,14)', 'beta/resources/externalconnectors-propertyrule.md(3,14)', 'beta/resources/externalconnectors-searchsettings.md(3,14)'.`````

<a id="bfa8da9f0cb03ac977adccbf05e62ed8-7ab8948c"></a>
### [api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/externalconnectors-displaytemplate.md(3,14)', 'beta/resources/externalconnectors-propertyrule.md(3,14)', 'beta/resources/externalconnectors-searchsettings.md(3,14)'.`````

<a id="41a097b9c88176e8e085b4c2cf7c3ef8-7ab8948c"></a>
### [api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/externalconnectors-displaytemplate.md(3,14)', 'beta/resources/externalconnectors-propertyrule.md(3,14)', 'beta/resources/externalconnectors-searchsettings.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108042342256000-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=0XvamEhD%2FYDhlnGA0CMumymrTIdloYaMEFY4ahlmphc%3D&st=2021-08-04T23%3A39%3A45Z&se=2021-09-04T23%3A44%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-16 20:05 UTC, opbld30 commented
Docs Build status updates of commit _[898b1f2](https://github.com/emzho/microsoft-graph-docs/commits/898b1f247e146645cff71090587e8fd2c603aaa2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-26a23be1)
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-bfa8da9f0cb03ac977adccbf05e62ed8-26a23be1)
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-41a097b9c88176e8e085b4c2cf7c3ef8-26a23be1)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-26a23be1"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-intune-json.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/externalconnectors-displaytemplate.md(3,14)', 'beta/resources/externalconnectors-propertyrule.md(3,14)', 'beta/resources/externalconnectors-searchsettings.md(3,14)'.`````

<a id="bfa8da9f0cb03ac977adccbf05e62ed8-26a23be1"></a>
### [api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/externalconnectors-displaytemplate.md(3,14)', 'beta/resources/externalconnectors-propertyrule.md(3,14)', 'beta/resources/externalconnectors-searchsettings.md(3,14)'.`````

<a id="41a097b9c88176e8e085b4c2cf7c3ef8-26a23be1"></a>
### [api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/externalconnectors-displaytemplate.md(3,14)', 'beta/resources/externalconnectors-propertyrule.md(3,14)', 'beta/resources/externalconnectors-searchsettings.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108162003241503-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=lc3KhkcjNZSLFgyPmaGA7IuPkJa7BW3%2F7Pd3uBKmvHQ%3D&st=2021-08-16T20%3A00%3A00Z&se=2021-09-16T20%3A05%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 23:53 UTC, opbld34 commented
Docs Build status updates of commit _[a71768b](https://github.com/emzho/microsoft-graph-docs/commits/a71768bf5c687917bba8ec2a42996bb8587d96ef)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-55e68a33)
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-bfa8da9f0cb03ac977adccbf05e62ed8-55e68a33)
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-41a097b9c88176e8e085b4c2cf7c3ef8-55e68a33)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-55e68a33"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-intune-json.md'.`````
 - **Line 22, Column 142**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 142**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 24, Column 272**: **[Suggestion-[disallowed-html-tag](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'operation' isn't allowed. Disallowed HTML poses a security risk and must be replaced with approved Docs Markdown syntax.`````
 - **Line 24, Column 336**: **[Suggestion-[disallowed-html-tag](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'valuesJoinedBy' isn't allowed. Disallowed HTML poses a security risk and must be replaced with approved Docs Markdown syntax.`````

<a id="bfa8da9f0cb03ac977adccbf05e62ed8-55e68a33"></a>
### [api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/externalconnectors-propertyrule.md(3,14)', 'beta/resources/externalconnectors-searchsettings.md(3,14)'.`````

<a id="41a097b9c88176e8e085b4c2cf7c3ef8-55e68a33"></a>
### [api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/externalconnectors-propertyrule.md(3,14)', 'beta/resources/externalconnectors-searchsettings.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108202351473677-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=lOkDr47ThBn3P4%2FMUCrj%2B0Cikq16yznRNhcsReQxyvI%3D&st=2021-08-20T23%3A48%3A29Z&se=2021-09-20T23%3A53%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp [...]

2021-08-21 00:29 UTC, opbld32 commented
Docs Build status updates of commit _[4e5af52](https://github.com/emzho/microsoft-graph-docs/commits/4e5af523f1bb9400fea5c0ce4442db1a09e2eca8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-840440ce)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-840440ce"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-intune-json.md'.`````
 - **Line 22, Column 142**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 142**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 24, Column 272**: **[Suggestion-[disallowed-html-tag](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'operation' isn't allowed. Disallowed HTML poses a security risk and must be replaced with approved Docs Markdown syntax.`````
 - **Line 24, Column 336**: **[Suggestion-[disallowed-html-tag](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'valuesJoinedBy' isn't allowed. Disallowed HTML poses a security risk and must be replaced with approved Docs Markdown syntax.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108210028018268-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=8PP6qMH2oodMiWhqE%2FGAa4%2BgdDR8Cz2a2nAKM96jdII%3D&st=2021-08-21T00%3A24%3A31Z&se=2021-09-21T00%3A29%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-21 00:32 UTC, opbld32 commented
Docs Build status updates of commit _[5faf8c3](https://github.com/emzho/microsoft-graph-docs/commits/5faf8c3b62e288b64f915f2d1b172d1f05ef0bfa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-54df5d38)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-54df5d38"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-intune-json.md'.`````
 - **Line 22, Column 142**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 142**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 24, Column 272**: **[Suggestion-[disallowed-html-tag](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'operation' isn't allowed. Disallowed HTML poses a security risk and must be replaced with approved Docs Markdown syntax.`````
 - **Line 24, Column 336**: **[Suggestion-[disallowed-html-tag](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'valuesJoinedBy' isn't allowed. Disallowed HTML poses a security risk and must be replaced with approved Docs Markdown syntax.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108210030432506-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=HCxs49V8l7CI5%2BpJW6zZMPOTL%2B5Xq037H6T9CO1Zoiw%3D&st=2021-08-21T00%3A27%3A01Z&se=2021-09-21T00%3A32%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-21 00:53 UTC, opbld32 commented
Docs Build status updates of commit _[631f0af](https://github.com/emzho/microsoft-graph-docs/commits/631f0afb5190c5c9fafc53b8835b2628a4a0a189)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-c983f6ec)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-c983f6ec"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-intune-json.md'.`````
 - **Line 22, Column 142**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 142**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 24, Column 272**: **[Suggestion-[disallowed-html-tag](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'operation' isn't allowed. Disallowed HTML poses a security risk and must be replaced with approved Docs Markdown syntax.`````
 - **Line 24, Column 336**: **[Suggestion-[disallowed-html-tag](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'valuesJoinedBy' isn't allowed. Disallowed HTML poses a security risk and must be replaced with approved Docs Markdown syntax.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108210052006490-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=wIgG%2FdReewyKCLT0tkcLfAXho00LNLgytsFB8zAvb00%3D&st=2021-08-21T00%3A48%3A31Z&se=2021-09-21T00%3A53%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-21 00:56 UTC, opbld34 commented
Docs Build status updates of commit _[5bda3fb](https://github.com/emzho/microsoft-graph-docs/commits/5bda3fb4aed5732de34d430340a7fac64a21022a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-7ead8a00)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-7ead8a00"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-intune-json.md'.`````
 - **Line 22, Column 142**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 142**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108210055096406-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=NivopB6ceHQL31StZtSl%2B3Rhkr06edFHbrW6yUhq3c8%3D&st=2021-08-21T00%3A51%3A42Z&se=2021-09-21T00%3A56%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-22 22:38 UTC, emzho commented on api-reference/beta/resources/externalconnectors-externalconnection.md
> +| connectorId   |String                             |The Teams App ID or the MetaOS manifest ID.|
@judyhnguyen Can we call out that this is optional?

2021-08-22 22:41 UTC, emzho commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +|priority|Int32|An integer that determines the order of evaluation with respect to other templates. The evaluation is sequenced from least to greatest priority e.g. a priority of 4 will be evaluated
@judyhnguyen Can we make this description more succinct? Perhaps it's sufficient to say, "The integer priority of this display template. A display template with priority 1 is evaluated before that of a template of priority 4. Gaps in priority values are supported."

2021-08-22 22:45 UTC, emzho commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +|rules|[microsoft.graph.externalConnectors.propertyRule](../resources/externalconnectors-propertyrule.md) collection|These are a set of matching conditions that dictate when the template should be di
Maybe here it's also sufficient to shorten the description to something like, "Specifies additional rules for selecting this display template based on the item schema. Optional." And then developers can click on the link to read further about propertyRule object.

2021-08-22 22:47 UTC, emzho commented on api-reference/beta/resources/externalconnectors-externalconnection.md
> +| searchSettings|[microsoft.graph.externalConnectors.searchSettings](../resources/externalconnectors-searchsettings.md)|The location of all configurable settings relating to search over connector con
@judyhnguyen Are external developers aware of "searchResultTemplates" as a concept? Maybe we can leave this example out. Also, to further shorten, we could distill the description to: "The settings configuring the search experience for content in this connection, such as the display templates for search results."

2021-08-22 23:10 UTC, emzho commented on api-reference/beta/resources/externalconnectors-propertyrule.md
> +description: "Property rules are a set of matching conditions that dictate when the template should be displayed."
@judyhnguyen "set of conditions"?

2021-08-22 23:36 UTC, emzho commented on api-reference/beta/resources/externalconnectors-propertyrule.md
> +|property|String|This property from the item schema is the first operand of the entire rule expression.|
A suggestion for making documentation more clear:

operation: "This specifies the operations to be performed during evaluation of a single rule, where `property` and a string from the `values` collection are the respective operands. Possible values are: `null`, `equals`, `notEquals`, `contains`, `notContains`, `lessThan`, `greaterThan`, `startsWith`, `unknownFutureValue`. Required.
property: "The property from the [externalItem](../resources/externalconnectors-externalitem.md) schema. Required."
values: "A collection with one or many strings. The specified string(s) will be matched with the specified property using the specified operation. Required."
valuesJoinedBy: "The join operator for evaluating multiple rules. For example, if `and` is specified, then all rules must be true for the property rule to be true. Possible values are: `or`, `and`. Required."

2021-08-23 17:24 UTC, judyhnguyen commented on api-reference/beta/resources/externalconnectors-externalconnection.md
> +| connectorId   |String                             |The Teams App ID or the MetaOS manifest ID.|
I am unsure if the intention is to mandate this field or not. I think for now, we can call it optional until we have more clarity around its requirements and use cases.

2021-08-23 17:25 UTC, judyhnguyen commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +|priority|Int32|An integer that determines the order of evaluation with respect to other templates. The evaluation is sequenced from least to greatest priority e.g. a priority of 4 will be evaluated
I love your suggested alternative- that is much more clear!

2021-08-24 22:23 UTC, opbld31 commented
Docs Build status updates of commit _[de6e084](https://github.com/emzho/microsoft-graph-docs/commits/de6e084a6944ff8dc9836100073f8fab6db9e7ba)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-d35e366a)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-d35e366a"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-intune-json.md'.`````
 - **Line 22, Column 142**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 142**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108242222059233-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=TLYm6A7y%2F3Cp%2FRx3PhOziijHDEaHjhxef72S4PcxGgc%3D&st=2021-08-24T22%3A18%3A34Z&se=2021-09-24T22%3A23%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-24 22:25 UTC, opbld31 commented
Docs Build status updates of commit _[fbafd70](https://github.com/emzho/microsoft-graph-docs/commits/fbafd7086021cb409c58ba6b013a3db9e79b46de)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-af079def)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-af079def"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-intune-json.md'.`````
 - **Line 22, Column 142**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 142**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108242224167460-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=onkvmFI1fakoaYU9z6Sc4el%2BBOHBoyp4DSG0BKqshOE%3D&st=2021-08-24T22%3A20%3A47Z&se=2021-09-24T22%3A25%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-24 22:27 UTC, opbld32 commented
Docs Build status updates of commit _[fbafd70](https://github.com/emzho/microsoft-graph-docs/commits/fbafd7086021cb409c58ba6b013a3db9e79b46de)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-5fe4ffe3)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-5fe4ffe3"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-intune-json.md'.`````
 - **Line 22, Column 142**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 142**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108242224269457-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=eBhb4q2HeWBKiCmFTXLXLdd1FngUZMy%2B2%2B5QCRPl7tA%3D&st=2021-08-24T22%3A22%3A30Z&se=2021-09-24T22%3A27%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-01 17:35 UTC, jasonjoh commented
Docs Build status updates of commit _[5cb1de9](https://github.com/emzho/microsoft-graph-docs/commits/5cb1de91332e7291ecd4740124e8b08710229ab7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-0d21c662)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-0d21c662"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/externalconnectors-intune-json.md'.`````
 - **Line 22, Column 142**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 142**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109011731283883-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=OUBoS3iyOkNlwtYYXANm6Iw%2FWY3oiE6w41EGBaD7AzU%3D&st=2021-09-01T17%3A30%3A18Z&se=2021-10-02T17%3A35%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-01 19:09 UTC, jasonjoh commented
Docs Build status updates of commit _[567c315](https://github.com/emzho/microsoft-graph-docs/commits/567c315a3ad018b444f77d915b663a32de1e942b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-c1173461)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-c1173461"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109011907246832-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=%2BRmFbVO01uH43ma19KIau7YJwMOQis46iDyBFljg1iw%3D&st=2021-09-01T19%3A04%3A14Z&se=2021-10-02T19%3A09%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-01 19:53 UTC, jasonjoh commented
Docs Build status updates of commit _[c0e3f84](https://github.com/emzho/microsoft-graph-docs/commits/c0e3f84d861e577d6032ad9c4e0f9c91c4f9b589)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-6ec8f636)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-6ec8f636"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109011950125511-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=gxsmxi6wNsDezrj8hpENv3ONMUhGuDN6LpzXoR8CnlE%3D&st=2021-09-01T19%3A48%3A03Z&se=2021-10-02T19%3A53%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-01 21:13 UTC, jasonjoh commented
Docs Build status updates of commit _[32e0eee](https://github.com/emzho/microsoft-graph-docs/commits/32e0eee9ac53f883c31273f5329cc45a061dd145)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-9a5bdf40)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-9a5bdf40"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109012112056909-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=wDmsdPpaauCIzyovfmIusH1S8ZNX3bApsQOZn%2BWamWc%3D&st=2021-09-01T21%3A08%3A44Z&se=2021-10-02T21%3A13%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-10 01:50 UTC, opbld30 commented
Docs Build status updates of commit _[7031521](https://github.com/emzho/microsoft-graph-docs/commits/703152183605fb7d3114f3f2d62f5d97f061e6d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-f63e9600)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-f63e9600"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109100148369947-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=BPgc70U0la%2BWRvyduK%2BHkLwwdQRT3LvnNDpbk1tqFXQ%3D&st=2021-09-10T01%3A45%3A21Z&se=2021-10-11T01%3A50%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-10 01:55 UTC, opbld32 commented
Docs Build status updates of commit _[0d86649](https://github.com/emzho/microsoft-graph-docs/commits/0d86649d7b4297606628ef1fce337aaa92deec28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-cc441591)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-cc441591"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109100153599064-13745%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=zp5AnSl5AsHPFkQna8m%2FhxoCCFqeO5UWVxD1OH3fMbU%3D&st=2021-09-10T01%3A50%3A38Z&se=2021-10-11T01%3A55%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-10 02:36 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +A display template enables the developer to define the appearance of the content and configure conditions that dictate when the template should be displayed.
Please rephrase for simplicity:
* Enables the developer to define the appearance of the content and configure conditions that dictate when the template should be displayed.

Please apply to the description in line 3 as well.

2021-09-10 02:44 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +|priority|Int32|The integer priority of this display template. A display template with priority 1 is evaluated before that of a template of priority 4. Gaps in priority values are supported.|
Line 23, description: Please rephrase to make it simple for a global audience. As a general advice, please keep in mind readers that only understand the most basic English. Suggestion:
* Defines the priority of a display template. A display template with priority 1 is evaluated before a template with priority 4. Gaps in priority values are supported.

2021-09-10 15:43 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +|layout|[microsoft.graph.Json](../resources/intune-mam-json.md)|The definition of the content's appearance, represented by an [Adaptive Card](https://docs.microsoft.com/adaptive-cards/authoring-cards
Line 22: I'd appreciate if you can replace this absolute link with a relative link. If I am not mistaken it should be:
- /adaptive-cards/authoring-cards/getting-started.md

2021-09-10 15:55 UTC, isvargasmsft requested changes
Hello @emzho, 

Thank you very much for your work in this PR. 

Just a few suggestions. Please let me know if you have any questions and feel free to ping me on the side. 

Kind regards!

Isaac Vargas

2021-09-15 19:27 UTC, judyhnguyen commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +A display template enables the developer to define the appearance of the content and configure conditions that dictate when the template should be displayed.
Hi @isvargasmsft, I am unsure of how much simpler I can make this definition. 
A display template does 2 things: defines the appearance and creates conditions for display. 

Should I use the sentence above? Is that more simple?

2021-09-15 19:29 UTC, judyhnguyen commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +|layout|[microsoft.graph.Json](../resources/intune-mam-json.md)|The definition of the content's appearance, represented by an [Adaptive Card](https://docs.microsoft.com/adaptive-cards/authoring-cards
The page is not found when I route to that absolute link @isvargasmsft

2021-09-15 19:34 UTC, opbld31 commented
Docs Build status updates of commit _[56af262](https://github.com/emzho/microsoft-graph-docs/commits/56af262243d9c5cac2ae34a6a4018eda5d695787)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-23fc1c54)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-23fc1c54"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109151931080087-13745%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T19%3A34%3A35Z&sr=b&sp=r&sig=NoH7fIB2TzrIekQ4HTYUYli1CRWf26TPFIKQUT2A4N4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 13:53 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +A display template enables the developer to define the appearance of the content and configure conditions that dictate when the template should be displayed.
Oh, my apologies for the misunderstanding. I meant rephrase to use present tense, in other words, remove just the first 3 words and start with "Enables".

2021-09-16 13:56 UTC, opbld30 commented
Docs Build status updates of commit _[b18a023](https://github.com/emzho/microsoft-graph-docs/commits/b18a023924bbe90511d01db71511ec5b7b907a8b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-547a8449)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-547a8449"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109161353404460-13745%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T13%3A56%3A37Z&sr=b&sp=r&sig=%2FUAJp4irzwoquhW9zCLpRyzzfQ%2B8AHtC0uaUyqPUd20%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-17 19:30 UTC, judyhnguyen commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +A display template enables the developer to define the appearance of the content and configure conditions that dictate when the template should be displayed.
Got it, thank you Isaac!

2021-09-17 19:31 UTC, judyhnguyen commented
Hi @isvargasmsft, I have resolved your comments and have made changes to the PR. Thank you!

2021-09-17 19:32 UTC, opbld33 commented
Docs Build status updates of commit _[d817fd7](https://github.com/emzho/microsoft-graph-docs/commits/d817fd794d71d2f1ec65afe8dd9902623da833da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-02cff300)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-02cff300"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109171929489397-13745%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-18T19%3A32%3A59Z&sr=b&sp=r&sig=NVP%2Fl5goLZXEwckb9Zr1qhjWOtl28Spagcvk%2BaJo5DU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-20 22:21 UTC, opbld34 commented
Docs Build status updates of commit _[288b366](https://github.com/emzho/microsoft-graph-docs/commits/288b366799da2f6721f8fe9983ede4041c2e7e01)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-da9f6a1d)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-da9f6a1d"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109202220029410-13745%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-21T22%3A21%3A43Z&sr=b&sp=r&sig=NA6a9hUZgfrru%2Br%2FAt8u8v6SlQBmDSMNqjIME%2FTEcco%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-20 23:00 UTC, opbld31 commented
Docs Build status updates of commit _[1e46d79](https://github.com/emzho/microsoft-graph-docs/commits/1e46d79d2df15532eaed95928f72e4517c310dbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-b7d2247d)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-b7d2247d"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109202258310183-13745%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-21T23%3A00%3A33Z&sr=b&sp=r&sig=k%2BRJj0jcx5S9Mc2inlPTFMv5%2BQjfHyP%2BgqhVYRYmJeQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-20 23:02 UTC, opbld31 commented
Docs Build status updates of commit _[4822edf](https://github.com/emzho/microsoft-graph-docs/commits/4822edf28796b51fc55d56ba8167eb6c90dcf9b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-a16a00ac)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-a16a00ac"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109202300280563-13745%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-21T23%3A02%3A55Z&sr=b&sp=r&sig=S%2F38LT8SL9VJcsS6iEebUCcrt8vNv8HS6Hm7zzc5Ei0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-20 23:38 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-searchsettings.md
> +|searchResultTemplates|[microsoft.graph.externalConnectors.displayTemplate](../resources/externalconnectors-displaytemplate.md) collection|A search result template enables the developer to define the
Line 21, description: Please make this description match the description in its resource topic.

2021-09-21 17:01 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-externalconnection.md
> +| connectorId   |String                             |The Teams App ID or the MetaOS manifest ID. Optional.|
I didn't see this new property in the api.md, it is in the CSDL, though.  Could you please clarify?

2021-09-21 17:03 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-externalconnection.md
> +| searchSettings|[microsoft.graph.externalConnectors.searchSettings](../resources/externalconnectors-searchsettings.md)|The settings configuring the search experience for content in this connection,
I noticed there are 2 properties in api.md missing in this docs: activitySettings and complianceSettings. 

In addition, the CSDL lists ingestedItemsCount. Could you please clarify?

2021-09-21 17:05 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-externalconnection.md
>  ## Relationships
According to the api.md file, there is a new relationship called **groups**. 
According to the CSDL there is also **activities** and **quota**.

2021-09-21 17:41 UTC, emzho commented on api-reference/beta/resources/externalconnectors-externalconnection.md
> +| connectorId   |String                             |The Teams App ID or the MetaOS manifest ID. Optional.|
Please see this API.md for information about the connectorId property: https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding?path=/reviews/8796-Connection-managemetn-API/api.md&_a=preview&version=GBmaster

2021-09-21 19:18 UTC, isvargasmsft commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +|layout|[microsoft.graph.Json](../resources/intune-mam-json.md)|The definition of the content's appearance, represented by an [Adaptive Card](https://docs.microsoft.com/adaptive-cards/authoring-cards
Line 22: Is _Adaptive Card_ a registered name? If it is not, please use small caps.

2021-09-21 21:52 UTC, isvargasmsft commented on changelog/Microsoft.Search.json
> +          },
Missing in this changelog list:
activitySettings property
complianceSettings property
groups relationship

Resources:
itemIDRecorder
urlToItemResolverBase
urlMatchInfo

2021-09-21 21:53 UTC, isvargasmsft commented on changelog/Microsoft.Search.json
> +      "SubArea": ""
Missing files in this PR:
itemIDRecorder resource type
urlToItemResolverBase resource type
urlMatchInfo resource type

2021-09-21 21:53 UTC, isvargasmsft requested changes
Thank you for the work on the side. 

I left a few more comments for completeness. Please ping me on the side if you have any questions. 

Kind regards, 

Isaac

2021-09-24 20:26 UTC, judyhnguyen commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +|layout|[microsoft.graph.Json](../resources/intune-mam-json.md)|The definition of the content's appearance, represented by an [Adaptive Card](https://docs.microsoft.com/adaptive-cards/authoring-cards
What is meant by "registered name"?

2021-09-28 18:41 UTC, opbld31 commented
Docs Build status updates of commit _[5bb60fc](https://github.com/emzho/microsoft-graph-docs/commits/5bb60fc3ffe65f05795be3985a095ced41deaf02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-607497aa)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-607497aa"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109281838355927-13745%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-29T18%3A41%3A06Z&sr=b&sp=r&sig=5oRVlG8mbFReD2JT98wwzfhPRMi0Z1zgd86zRVb%2FgvE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-28 18:48 UTC, emzho commented on api-reference/beta/resources/externalconnectors-externalconnection.md
> +| searchSettings|[microsoft.graph.externalConnectors.searchSettings](../resources/externalconnectors-searchsettings.md)|The settings configuring the search experience for content in this connection,
These properties will be documented in separate PRs by other domain experts for those areas.

2021-09-28 18:48 UTC, emzho commented on api-reference/beta/resources/externalconnectors-externalconnection.md
>  ## Relationships
I will add the groups relationship -- this must have been left out in previous PRs. 

Activities and quota will be documented in separate PRs by other domain experts for those areas.

2021-09-28 18:48 UTC, emzho commented on changelog/Microsoft.Search.json
> +          },
These properties will be documented in separate PRs by other domain experts for those areas.

2021-09-28 18:49 UTC, emzho commented on changelog/Microsoft.Search.json
> +      "SubArea": ""
These properties will be documented in separate PRs by other domain experts for those areas.

2021-09-28 18:55 UTC, opbld30 commented
Docs Build status updates of commit _[e668faf](https://github.com/emzho/microsoft-graph-docs/commits/e668fafb329b65675782ed98b7fbacfd71df068b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-0df394de)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-0df394de"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109281852258661-13745%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-29T18%3A55%3A40Z&sr=b&sp=r&sig=LKwAaFsH%2Fef0BldqJn19XXieDdLQ%2B6M7tQNSCUHsMUQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-28 19:02 UTC, emzho commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +|layout|[microsoft.graph.Json](../resources/intune-mam-json.md)|The definition of the content's appearance, represented by an [Adaptive Card](https://docs.microsoft.com/adaptive-cards/authoring-cards
I believe that Adaptive Card can be capitalized. I see it capitalized as such in other Graph API docs. One example: https://docs.microsoft.com/en-us/graph/api/resources/projectrome-visualinfo?view=graph-rest-1.0

I'm not sure if it's a registered name, but it seems like it is. Can you clarify how we can determine this?

2021-09-28 23:15 UTC, isvargasmsft approved these changes

2021-09-30 03:42 UTC, opbld32 commented
Docs Build status updates of commit _[34b9d76](https://github.com/emzho/microsoft-graph-docs/commits/34b9d76102a8c7b7494762775e94de44524d703a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109300340497145-13745%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-31T03%3A42%3A38Z&sr=b&sp=r&sig=KFzwzmaQyX%2FDlyG%2FWokTgU8QZuxHHQvos3EU7kT4Ytw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-30 03:44 UTC, Lauragra commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +          "property": "itemTitle",
The JSON representation should just show the types; it should not include actual/fictitious values. So for these, you'll want to replace the values with String.

2021-09-30 03:45 UTC, Lauragra commented on api-reference/beta/resources/externalconnectors-externalconnection.md
> +| connectorId   |String                             |The Teams App ID or the MetaOS manifest ID. Optional.|
There's a reference to Meta OS here, which I believe is an internal code name? Can we remove the reference or can you please verify that we can have a public-facing reference to Meta OS?

2021-09-30 03:48 UTC, Lauragra commented on changelog/Microsoft.Search.json
> +      "ChangeList": [
I can't tell due to the large amount of updates in this file which ChangeList item is associated with the items in this PR. It should have a date of the day that we merge/publish. If you can provide the ID for the ChangeList entry I'll set the correct date when I merge. Thanks.

2021-09-30 03:48 UTC, opbld34 commented
Docs Build status updates of commit _[cd32906](https://github.com/emzho/microsoft-graph-docs/commits/cd32906e9c80434c561ce9fa9ad0d1f789adf0aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109300346317926-13745%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-31T03%3A48%3A25Z&sr=b&sp=r&sig=XiIuEBLuy%2FykVMRH35pjd7UVspN6tPH8CDi56DsCkoA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-30 03:54 UTC, opbld32 commented
Docs Build status updates of commit _[1d00a8f](https://github.com/emzho/microsoft-graph-docs/commits/1d00a8f7901a3607e8878e8ac140b5abba04de09)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-f58887b9)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-f58887b9"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109300352049208-13745%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-31T03%3A54%3A58Z&sr=b&sp=r&sig=sxUp1kAmGJgvkTe6nwNOHzJrKR8Qhf5%2FP4RAnspzs8U%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-30 19:43 UTC, judyhnguyen commented on api-reference/beta/resources/externalconnectors-externalconnection.md
> +| connectorId   |String                             |The Teams App ID or the MetaOS manifest ID. Optional.|
I removed the reference. Thank you for calling that out!

2021-09-30 19:44 UTC, opbld30 commented
Docs Build status updates of commit _[3d4945a](https://github.com/emzho/microsoft-graph-docs/commits/3d4945a2cab9f9e2dcd695b57f36c3cb11a5e3c2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-9e3ec42d)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-9e3ec42d"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109301943024272-13745%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-31T19%3A44%3A48Z&sr=b&sp=r&sig=zMOmZapl3J4Sd9VO6YhhkwS2u0aJ5xpYZN823x9nweM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-30 19:45 UTC, judyhnguyen commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +          "property": "itemTitle",
Hi @Lauragra, by that do you mean that for all of the "dummy" values should I replace with "String"? Or "String (identifier)"?

2021-10-01 01:43 UTC, Lauragra commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +          "property": "itemTitle",
Yes, just like as shown in the propertyRule resource topic.

2021-10-04 18:14 UTC, judyhnguyen commented on api-reference/beta/resources/externalconnectors-displaytemplate.md
> +          "property": "itemTitle",
Hi @Lauragra, should I replace the "layout" field which is an adaptive card with "String" as well? Additionally, should the "priority" value be replaced with 'Integer', 'Int', or 'Number'?

2021-10-04 18:15 UTC, opbld33 commented
Docs Build status updates of commit _[edb8292](https://github.com/emzho/microsoft-graph-docs/commits/edb8292e01f2a2e21aa8e8e37ee7af6efd93d94e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-f1d96df0)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-f1d96df0"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110041813134029-13745%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-04T18%3A15%3A36Z&sr=b&sp=r&sig=wrmHfw6836YwqrXU4mCOOxLkwDlqu%2BPYHciUmUaZktk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-05 02:05 UTC, Lauragra commented
@emzho , can you please reply to this comment on this PR: I can't tell due to the large amount of updates in this file which ChangeList item is associated with the items in this PR. It should have a date of the day that we merge/publish. If you can provide the ID for the ChangeList entry I'll set the correct date when I merge. Thanks.

2021-10-05 02:08 UTC, emzho commented on changelog/Microsoft.Search.json
> +      "ChangeList": [
The changelog ID for this specific PR is: f7d67d61-f565-11eb-b6a8-8203ca0139f1

2021-10-05 02:25 UTC, Lauragra approved these changes

2021-10-05 02:27 UTC, opbld32 commented
Docs Build status updates of commit _[b9d85e6](https://github.com/emzho/microsoft-graph-docs/commits/b9d85e64e9fb0d7f1aa57588d2269e4022591977)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-displaytemplate?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) | [Details](#user-content-88b7e2531aaddc6cd262b06299f500b7-6dc2edbe)
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-propertyrule.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-propertyrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-propertyrule?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-13745) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="88b7e2531aaddc6cd262b06299f500b7-6dc2edbe"></a>
### [api-reference/beta/resources/externalconnectors-displaytemplate.md](https://github.com/emzho/microsoft-graph-docs/blob/emzho-externalConnectionSearchSettings/api-reference/beta/resources/externalconnectors-displaytemplate.md)
 - **Line 22, Column 127**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 127**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110050224327045-13745%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-05T02%3A27%3A02Z&sr=b&sp=r&sig=Wgykh4wyEYtJO5N5YNQkaef5YFa%2FtOt7RqcT3P9HRmA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-06 01:32 UTC, merged