incorrect odatatype - customer issue
microsoftgraph/microsoft-graph-docs pull request #13742
Opened 2021-08-04 19:20 UTC by cristobal-buenrostro

request and response body updated accordingly to case reported by user.

https://github.com/microsoftgraph/microsoft-graph-docs/issues/13191

2021-08-04 19:22 UTC, opbld31 commented
Docs Build status updates of commit _[9d33cb8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d33cb84b663570a04575729fc092937024daec0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/odatatypeissue/api-reference/beta/api/educationsubmission-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-post-resources?view=graph-rest-beta&branch=pr-en-us-13742) (graph-rest-beta) |
[api-reference/v1.0/api/educationsubmission-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/odatatypeissue/api-reference/v1.0/api/educationsubmission-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-post-resources?view=graph-rest-1.0&branch=pr-en-us-13742) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108041920146921-13742%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=1OcmCN9f2X%2FKduAlD8p8P1%2FpKsYgP4vJKObB5q47134%3D&st=2021-08-04T19%3A17%3A29Z&se=2021-09-04T19%3A22%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 15:45 UTC, opbld30 commented
Docs Build status updates of commit _[c4e4101](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4e4101749375d055e12c52d66be18ae1542c2de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/odatatypeissue/api-reference/beta/api/educationsubmission-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-post-resources?view=graph-rest-beta&branch=pr-en-us-13742) (graph-rest-beta) |
[api-reference/v1.0/api/educationsubmission-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/odatatypeissue/api-reference/v1.0/api/educationsubmission-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-post-resources?view=graph-rest-1.0&branch=pr-en-us-13742) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108061544149823-13742%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=ELbhPkY9DfI3g5IS5SPXL8FLT0qdSVJGViU2Kl2BQtA%3D&st=2021-08-06T15%3A40%3A37Z&se=2021-09-06T15%3A45%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 15:50 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-post-resources.md
> +In the request body, supply a JSON representation of the resource, in this case [educationWordResource](../resources/educationwordresource.md) object.
I think it would be better to list or link the supported resource types. I understand you can also have educationExcelResource, right? 

In such case, let's use the Request body section to explain the behavior in general and the examples to show specific cases.

2021-08-06 15:51 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-post-resources.md
> +In the request body, supply a JSON representation of the resource, in this case [educationWordResource](../resources/educationwordresource.md) object.
Same observation for the Response section below.

2021-08-06 15:51 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-post-resources.md
>    "blockType": "ignored",
Please use the proper blocktype: request.

Follow the guidelines here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor

2021-08-06 15:52 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-post-resources.md
> +POST https://graph.microsoft.com/v1.0/education/classes/f4a941ff-9da6-4707-ba5b-0eae93cad0b4/assignments/3c77de7f-539b-49e1-9c96-1274f2f0ee3b/submissions/4af73d2b-6b9c-493f-0688-979087bed39b/resource
This is a beta topic so, the examples should be in beta as well. Please make the corrections in the request and response sections in the example.

2021-08-06 15:52 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-post-resources.md
> +        "fileUrl": "https://graph.microsoft.com/v1.0/drives/b!DPA6q59Tw0mtgmyXRUmrQRqBZTesG-lMkl1cBmvvMeUEWrOk89nKRpUEr4ZhNYBc/items/016XPCQEELISJB7NVNVBAK7V4UIF6Q27U2"
Fix to beta.

2021-08-06 15:53 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-post-resources.md
>    "blockType": "ignored",
Please use the proper blocktype: response.

2021-08-06 15:53 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-post-resources.md
> +        "fileUrl": "https://graph.microsoft.com/v1.0/drives/b!DPA6q59Tw0mtgmyXRUmrQRqBZTesG-lMkl1cBmvvMeUEWrOk89nKRpUEr4ZhNYBc/items/016XPCQEELISJB7NVNVBAK7V4UIF6Q27U2",
Please fix to beta

2021-08-06 15:53 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-post-resources.md
> +    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#education/classes('f4a941ff-9da6-4707-ba5b-0eae93cad0b4')/assignments('3c77de7f-539b-49e1-9c96-1274f2f0ee3b')/submissions('4af73d2b-6
Please fix to beta.

2021-08-06 15:59 UTC, isvargasmsft requested changes
Hello @cristobal-buenrostro , 

Thank you for your work in this PR. 

1. Let's use the Request and Response sections of the document to clarify the supported resource types in this method. If we only mention Word resources, some readers may think that only Word resources are supported. To avoid these confusions, lets link the supported types and the general behavior.
2. Please remember to use the proper blocktypes for API Doctor. 
3. Please pay attention to the version in the examples: if the topic is in beta, the examples should be consistent.

Please feel free to ping me on the side if you have any questions. 

Kind regards,

Isaac Vargas

2021-08-12 18:23 UTC, opbld34 commented
Docs Build status updates of commit _[ea5bc76](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea5bc76209219607b9c36043b2a4c5bd1b48df3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/odatatypeissue/api-reference/beta/api/educationsubmission-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-post-resources?view=graph-rest-beta&branch=pr-en-us-13742) (graph-rest-beta) |
[api-reference/v1.0/api/educationsubmission-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/odatatypeissue/api-reference/v1.0/api/educationsubmission-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-post-resources?view=graph-rest-1.0&branch=pr-en-us-13742) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108121821592052-13742%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=f%2FTHxy1KehM%2BSjq6CH6XoEiaVqz6S5IQ28efuhskwdQ%3D&st=2021-08-12T18%3A18%3A20Z&se=2021-09-12T18%3A23%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-12 21:00 UTC, opbld34 commented
Docs Build status updates of commit _[4bb8a9a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4bb8a9ae26c3dd03542f6e7dccf91262bd4c8abe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/odatatypeissue/api-reference/beta/api/educationsubmission-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-post-resources?view=graph-rest-beta&branch=pr-en-us-13742) (graph-rest-beta) |
[api-reference/v1.0/api/educationsubmission-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/odatatypeissue/api-reference/v1.0/api/educationsubmission-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-post-resources?view=graph-rest-1.0&branch=pr-en-us-13742) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108122058472357-13742%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=D9S82br%2F5ODDpRB7pTo1zL6BI4N5%2Fzz%2BpCXzNcZ8MDY%3D&st=2021-08-12T20%3A55%3A20Z&se=2021-09-12T21%3A00%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-12 21:08 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-post-resources.md
>    "blockType": "ignored",
done

2021-08-12 21:08 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-post-resources.md
> +POST https://graph.microsoft.com/v1.0/education/classes/f4a941ff-9da6-4707-ba5b-0eae93cad0b4/assignments/3c77de7f-539b-49e1-9c96-1274f2f0ee3b/submissions/4af73d2b-6b9c-493f-0688-979087bed39b/resource
done

2021-08-12 21:08 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-post-resources.md
> +        "fileUrl": "https://graph.microsoft.com/v1.0/drives/b!DPA6q59Tw0mtgmyXRUmrQRqBZTesG-lMkl1cBmvvMeUEWrOk89nKRpUEr4ZhNYBc/items/016XPCQEELISJB7NVNVBAK7V4UIF6Q27U2"
done

2021-08-12 21:08 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-post-resources.md
>    "blockType": "ignored",
done

2021-08-12 21:08 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-post-resources.md
> +        "fileUrl": "https://graph.microsoft.com/v1.0/drives/b!DPA6q59Tw0mtgmyXRUmrQRqBZTesG-lMkl1cBmvvMeUEWrOk89nKRpUEr4ZhNYBc/items/016XPCQEELISJB7NVNVBAK7V4UIF6Q27U2",
done

2021-08-12 21:09 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-post-resources.md
> +    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#education/classes('f4a941ff-9da6-4707-ba5b-0eae93cad0b4')/assignments('3c77de7f-539b-49e1-9c96-1274f2f0ee3b')/submissions('4af73d2b-6
done

2021-08-16 23:48 UTC, opbld32 commented
Docs Build status updates of commit _[d4a357a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d4a357a09163b11a89c24bff8cfc35cd58f92b29)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/odatatypeissue/api-reference/beta/api/educationsubmission-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-post-resources?view=graph-rest-beta&branch=pr-en-us-13742) (graph-rest-beta) |
[api-reference/v1.0/api/educationsubmission-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/odatatypeissue/api-reference/v1.0/api/educationsubmission-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-post-resources?view=graph-rest-1.0&branch=pr-en-us-13742) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108162346331329-13742%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=rd1sVTNlxLr6t01bGezxiGer9TPwmf375VbkrwS008k%3D&st=2021-08-16T23%3A43%3A29Z&se=2021-09-16T23%3A48%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 00:08 UTC, opbld34 commented
Docs Build status updates of commit _[9edef8f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9edef8fcc0c9c8726187e1691e558f1a82d5b1d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/odatatypeissue/api-reference/beta/api/educationsubmission-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-post-resources?view=graph-rest-beta&branch=pr-en-us-13742) (graph-rest-beta) |
[api-reference/v1.0/api/educationsubmission-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/odatatypeissue/api-reference/v1.0/api/educationsubmission-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-post-resources?view=graph-rest-1.0&branch=pr-en-us-13742) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108170000352400-13742%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=mb8qiDo9MiIzXmYLc9LjdhwBwwbcQfIj6C%2FXyKOpTWk%3D&st=2021-08-17T00%3A03%3A16Z&se=2021-09-17T00%3A08%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 00:10 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-post-resources.md
> +In the request body, supply a JSON representation of the resource, in this case [educationWordResource](../resources/educationwordresource.md) object.
done

2021-08-21 01:49 UTC, Lauragra commented
@isvargasmsft , if your comments have been addressed, can you please approve and set ready to merge?

2021-08-23 15:53 UTC, isvargasmsft approved these changes
Thank you very much!

2021-08-23 15:54 UTC, opbld31 commented
Docs Build status updates of commit _[14c3764](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14c3764ca4d14b5c55733bc517ed72c359ffd9ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/odatatypeissue/api-reference/beta/api/educationsubmission-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-post-resources?view=graph-rest-beta&branch=pr-en-us-13742) (graph-rest-beta) |
[api-reference/v1.0/api/educationsubmission-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/odatatypeissue/api-reference/v1.0/api/educationsubmission-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-post-resources?view=graph-rest-1.0&branch=pr-en-us-13742) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108231553237260-13742%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=RWJlsubNhziSB%2Bqo03PJ0BX%2Be2NnhRuz7BUETksm55U%3D&st=2021-08-23T15%3A49%3A48Z&se=2021-09-23T15%3A54%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-24 03:31 UTC, merged