Add automatically generated documents - Microsoft.Security.AttackSimulation workload
microsoftgraph/microsoft-graph-docs pull request #13789
Opened 2021-08-10 06:24 UTC by aspati

Add automatically generated documents - Microsoft.Security.AttackSimulation workload

2021-08-10 06:26 UTC, opbld32 commented
Docs Build status updates of commit _[c10d832](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c10d832c6d4e68da7730d9c63ffde6ab5abf6842)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[doc-stubs/api/attacksimulationroot-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-post-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-post-simulations.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-list-attacksimulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-list-attacksimulation.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-post-attacksimulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-post-attacksimulation.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/emailidentity.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph- [...]

2021-08-10 06:32 UTC, opbld33 commented
Docs Build status updates of commit _[8fecaf0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8fecaf0818f3225902b303b62579f9043535e21d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[doc-stubs/api/attacksimulationroot-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-post-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-post-simulations.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-list-attacksimulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-list-attacksimulation.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-post-attacksimulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-post-attacksimulation.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/emailidentity.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph- [...]

2021-08-11 10:06 UTC, opbld31 commented
Docs Build status updates of commit _[05c38c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05c38c5bc02bddb0ba5f404198c215cfc73db04c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-post-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-post-simulations.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-list-attacksimulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-list-attacksimulation.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-post-attacksimulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-post-attacksimulation.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/emailidentity.md](https://github [...]

2021-08-19 21:56 UTC, opbld33 commented
Docs Build status updates of commit _[7eeeecc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7eeeecc5051c596e40a9a975438f4e5315350285)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-post-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-post-simulations.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/attacksimulationroot-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/attacksimulationroot-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-list-attacksimulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-list-attacksimulation.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-post-attacksimulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-post-attacksimulation.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/security-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/security-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/emailidentity.md](https://github [...]

2021-08-31 05:37 UTC, opbld32 commented
Docs Build status updates of commit _[f620c82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f620c82fe9a61bfe51a991f876b7664ab081ff7e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-1bd731c67eabc000ece21b8c99dc7eba-0d02f6f4)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-0d02f6f4)
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/emailidentity.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/recommendedaction.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulation.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulationevent.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulationreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulationreport.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulationreportoverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulationreportoverview.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/trainingeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/trainingeventscontent.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/usersimulationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/usersimulationdetails.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/usersimulationeventinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/usersimulationeventinfo.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/usertrainingcontenteventinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/usertrainingcontenteventinfo.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/usertrainingeventinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/usertrainingeventinfo.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/usertrainingstatusinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/usertrainingstatusinfo.md) | :white_check_mark:Succeeded | |

<a id="1bd731c67eabc000ece21b8c99dc7eba-0d02f6f4"></a>
### [api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md)
 - **Line 26, Column 37**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/reportroot-getattacksimulationrepeatoffenders.md'.`````
 - **Line 26, Column 139**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/reportroot-getattacksimulationsimulationusercoverage.md'.`````
 - **Line 26, Column 255**: **[Warning-[file-not-found](https://review.docs.mic [...]

2021-08-31 05:57 UTC, opbld31 commented
Docs Build status updates of commit _[ee7d2d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee7d2d44d51697fb88f08863e3e6921666e634cc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-6f0b5b04)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-6f0b5b04)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-6f0b5b04)
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-1a5244cfed63970bb492f48835373392-6f0b5b04)
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-eff59c721e7a4454ecfa7c071f167632-6f0b5b04)
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-a97a98686ca2e4482e1990b115b4b210-6f0b5b04)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-6f0b5b04)
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/emailidentity.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/recommendedaction.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulation.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulationevent.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulationeventscontent.md](https://github.com/microsoftgr [...]

2021-08-31 07:20 UTC, opbld34 commented
Docs Build status updates of commit _[336d0f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/336d0f44e78e58ff1c6496d21ae3962794c4b1e0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-de7e96ce)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-de7e96ce)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-de7e96ce)
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-1a5244cfed63970bb492f48835373392-de7e96ce)
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-eff59c721e7a4454ecfa7c071f167632-de7e96ce)
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-a97a98686ca2e4482e1990b115b4b210-de7e96ce)
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/emailidentity.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/recommendedaction.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulation.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulationevent.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph [...]

2021-09-01 04:07 UTC, opbld30 commented
Docs Build status updates of commit _[a239c6e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a239c6ebf6ddc1b47919d2d0a47c974dc87a4129)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-ebfaeab9)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-ebfaeab9)
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-1a5244cfed63970bb492f48835373392-ebfaeab9)
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-eff59c721e7a4454ecfa7c071f167632-ebfaeab9)
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-a97a98686ca2e4482e1990b115b4b210-ebfaeab9)
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-49f1c7a1bd1f83d748a33eb99444defa-ebfaeab9)
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-b0eee2aa586cb0275d8eca842487e0a5-ebfaeab9)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulation-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/emailidentity.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08- [...]

2021-09-01 04:14 UTC, opbld30 commented
Docs Build status updates of commit _[0a2cb02](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a2cb027010817b1e7030d9b8e78953b92f55125)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-93f80a84)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-93f80a84)
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-1a5244cfed63970bb492f48835373392-93f80a84)
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-eff59c721e7a4454ecfa7c071f167632-93f80a84)
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-a97a98686ca2e4482e1990b115b4b210-93f80a84)
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-49f1c7a1bd1f83d748a33eb99444defa-93f80a84)
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-b0eee2aa586cb0275d8eca842487e0a5-93f80a84)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |
[doc-stubs/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/emailidentity.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/recommendedaction.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulation.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulationevent.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulationreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulationreport.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulationreportoverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulationreportoverview.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/trainingeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/trainingeventscontent.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/usersimulationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/usersimulationdetails.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/usersimulationeventinfo.md](https://github.com/m [...]

2021-09-01 04:43 UTC, opbld32 commented
Docs Build status updates of commit _[bbf1cf6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bbf1cf6cb2b77093ec5c68dd25f7bb19f13d421a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-1a5244cfed63970bb492f48835373392-099682fb)
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-eff59c721e7a4454ecfa7c071f167632-099682fb)
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-a97a98686ca2e4482e1990b115b4b210-099682fb)
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-49f1c7a1bd1f83d748a33eb99444defa-099682fb)
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-914f0b76a6e33e68195cd456e50acff7-099682fb)
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-a63a849071dbab1ef188857c082aee0a-099682fb)
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-b0eee2aa586cb0275d8eca842487e0a5-099682fb)
[api-reference/beta/resources/usertrainingstatusinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usertrainingstatusinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usertrainingstatusinfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-fcebe8af5a2585ca3241631f250e1df5-099682fb)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |
[doc-stubs/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/emailidentity.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/recommendedaction.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulation.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/simulationevent.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/simulationeve [...]

2021-09-01 05:15 UTC, opbld31 commented
Docs Build status updates of commit _[2afa521](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2afa5216a58b1b860a277ab6c6081a2a286ba09f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-eff59c721e7a4454ecfa7c071f167632-9a57ba98)
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-a97a98686ca2e4482e1990b115b4b210-9a57ba98)
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-49f1c7a1bd1f83d748a33eb99444defa-9a57ba98)
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-914f0b76a6e33e68195cd456e50acff7-9a57ba98)
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-a63a849071dbab1ef188857c082aee0a-9a57ba98)
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-b0eee2aa586cb0275d8eca842487e0a5-9a57ba98)
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-36e3a9f948f343942bbffb26a626ee8b-9a57ba98)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-9a57ba98)
[api-reference/beta/resources/usertrainingstatusinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usertrainingstatusinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usertrainingstatusinfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-fcebe8af5a2585ca3241631f250e1df5-9a57ba98)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |
[doc-stubs/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-do [...]

2021-09-01 05:29 UTC, opbld30 commented
Docs Build status updates of commit _[7160046](https://github.com/microsoftgraph/microsoft-graph-docs/commits/716004632e45c0e093bf3f51118987f7ebfdd886)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-a97a98686ca2e4482e1990b115b4b210-e018005f)
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-49f1c7a1bd1f83d748a33eb99444defa-e018005f)
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-914f0b76a6e33e68195cd456e50acff7-e018005f)
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-a63a849071dbab1ef188857c082aee0a-e018005f)
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-b0eee2aa586cb0275d8eca842487e0a5-e018005f)
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-36e3a9f948f343942bbffb26a626ee8b-e018005f)
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-45095f09a665ee5259b87e339f6536ee-e018005f)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-e018005f)
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-9b96d4d59515c7357034a7083e489069-e018005f)
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationreportoverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationreportoverview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-6859de8fa8ce25cff5a3b8e25e305f5d-e018005f)
[api-reference/beta/resources/trainingeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/trainingeventscontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/trainingeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-5deab454571004b7d2010ebfc52e41b7-e018005f)
[api-reference/beta/resources/usertrainingstatusinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usertrainingstatusinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usertrainingstatusinfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-fcebe8af5a2585ca3241631f250e1df5-e018005f)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/b [...]

2021-09-01 05:46 UTC, opbld34 commented
Docs Build status updates of commit _[ed0d300](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed0d300e96783825067bac974e6196d80868df5e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-49f1c7a1bd1f83d748a33eb99444defa-90a0aa72)
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-914f0b76a6e33e68195cd456e50acff7-90a0aa72)
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-a63a849071dbab1ef188857c082aee0a-90a0aa72)
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-b0eee2aa586cb0275d8eca842487e0a5-90a0aa72)
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-36e3a9f948f343942bbffb26a626ee8b-90a0aa72)
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-45095f09a665ee5259b87e339f6536ee-90a0aa72)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-90a0aa72)
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-9b96d4d59515c7357034a7083e489069-90a0aa72)
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationreportoverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationreportoverview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-6859de8fa8ce25cff5a3b8e25e305f5d-90a0aa72)
[api-reference/beta/resources/trainingeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/trainingeventscontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/trainingeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-5deab454571004b7d2010ebfc52e41b7-90a0aa72)
[api-reference/beta/resources/usersimulationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usersimulationdetails.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersimulationdetails?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-8634c90a1013af34c4d1ea2757d00f5e-90a0aa72)
[api-reference/beta/resources/usersimulationeventinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usersimulationeventinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersimulationeventinfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-ddbcd9875b5e7868f8f19f064ad1da5b-90a0aa72)
[api-reference/beta/resources/usertrainingeventinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usertrainingeventinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usertrainingeventinfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-4dbb107a4068da5ad943d266d4b6f7d4-90a0aa72)
[api-reference/beta/resources/usertrainingstatusinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usertrainingstatusinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usertrainingstatusinfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-fcebe8af5a2585ca3241631f250e1df5-90a0aa72)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercov [...]

2021-09-01 07:04 UTC, opbld34 commented
Docs Build status updates of commit _[dbfd3cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dbfd3cf48abdf1a36b750ea19ac63017e465ff9c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-a3182115157501d9234c4ce80b8de05f-5407df1f)
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-a63a849071dbab1ef188857c082aee0a-5407df1f)
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-36e3a9f948f343942bbffb26a626ee8b-5407df1f)
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-45095f09a665ee5259b87e339f6536ee-5407df1f)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-5407df1f)
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-1b6e01aeb1a4ba88553d8900c58493f0-5407df1f)
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-9b96d4d59515c7357034a7083e489069-5407df1f)
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationreportoverview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationreportoverview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-6859de8fa8ce25cff5a3b8e25e305f5d-5407df1f)
[api-reference/beta/resources/trainingeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/trainingeventscontent.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/trainingeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-5deab454571004b7d2010ebfc52e41b7-5407df1f)
[api-reference/beta/resources/usersimulationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usersimulationdetails.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersimulationdetails?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-8634c90a1013af34c4d1ea2757d00f5e-5407df1f)
[api-reference/beta/resources/usersimulationeventinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usersimulationeventinfo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersimulationeventinfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-ddbcd9875b5e7868f8f19f064ad1da5b-5407df1f)
[api-reference/beta/resources/usertrainingcontenteventinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usertrainingcontenteventinfo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usertrainingcontenteventinfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-fc3d83d36f6d4bd2d7dbe13558414286-5407df1f)
[api-reference/beta/resources/usertrainingeventinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usertrainingeventinfo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usertrainingeventinfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-4dbb107a4068da5ad943d266d4b6f7d4-5407df1f)
[api-reference/beta/resources/usertrainingstatusinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usertrainingstatusinfo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usertrainingstatusinfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-fcebe8af5a2585ca3241631f250e1df5-5407df1f)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta)  [...]

2021-09-01 07:39 UTC, opbld33 commented
Docs Build status updates of commit _[da4692a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da4692aa713ad0154e0b27d9da3ca40a88d51898)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-45095f09a665ee5259b87e339f6536ee-38dcc4f3)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-38dcc4f3)
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-1b6e01aeb1a4ba88553d8900c58493f0-38dcc4f3)
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-9b96d4d59515c7357034a7083e489069-38dcc4f3)
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationreportoverview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationreportoverview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-6859de8fa8ce25cff5a3b8e25e305f5d-38dcc4f3)
[api-reference/beta/resources/trainingeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/trainingeventscontent.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/trainingeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-5deab454571004b7d2010ebfc52e41b7-38dcc4f3)
[api-reference/beta/resources/usersimulationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usersimulationdetails.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersimulationdetails?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-8634c90a1013af34c4d1ea2757d00f5e-38dcc4f3)
[api-reference/beta/resources/usersimulationeventinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usersimulationeventinfo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersimulationeventinfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-ddbcd9875b5e7868f8f19f064ad1da5b-38dcc4f3)
[api-reference/beta/resources/usertrainingcontenteventinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usertrainingcontenteventinfo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usertrainingcontenteventinfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-fc3d83d36f6d4bd2d7dbe13558414286-38dcc4f3)
[api-reference/beta/resources/usertrainingeventinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usertrainingeventinfo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usertrainingeventinfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-4dbb107a4068da5ad943d266d4b6f7d4-38dcc4f3)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.micro [...]

2021-09-01 08:41 UTC, opbld33 commented
Docs Build status updates of commit _[f6ac208](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6ac208dbf7b96e3de8c98434a8fa8971fa8efb0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/ [...]

2021-09-01 08:51 UTC, opbld34 commented
Docs Build status updates of commit _[4dd5826](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4dd58263b33a71ffdd829e8d16b7a86b3aef6d98)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/ [...]

2021-09-01 08:56 UTC, opbld30 commented
Docs Build status updates of commit _[952f615](https://github.com/microsoftgraph/microsoft-graph-docs/commits/952f6157dfdcbeaf5656d443e31cdb1333107a65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/ [...]

2021-09-01 09:02 UTC, opbld32 commented
Docs Build status updates of commit _[34ec31a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34ec31af490d9fb6a42ddeb86fe346a13bcfb549)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/ [...]

2021-09-03 01:21 UTC, angelgolfer-ms commented on api-reference/beta/resources/simulationeventscontent.md
> +|compromisedRate|Double|Compromised rate of the simulation.|
Line 21:
I'd like to use this property description as an example of what I have generally observed in the property descriptions in this PR. In general, we should not use the exact same words and only those words to explain a resource, property, navigation property, or method.
In this case, would the following description be accurate:
"Actual percentage of users that fell for the simulated attack."

2021-09-04 08:13 UTC, angelgolfer-ms commented on api-reference/beta/resources/simulation.md
> +|attackTechnique|simulationAttackTechnique|Attack technique of the simulation. Possible values are: `unknown`, `credentialHarvesting`, `attachmentMalware`, `driveByUrl`, `linkInAttachment`, `linkToMa
Line 26:
FYI I updated the first part of the description to be "The social engineering technique of the attack."

This is based on existing docs here: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide#simulations

Please feel free to improve the description.

GLOBAL:
Pointing this out as an example and contrast - please avoid using just the same words in a description to explain a property, resource, or method. I will be commenting in other cases where a more helpful description is necessary.

2021-09-04 09:27 UTC, angelgolfer-ms commented on api-reference/beta/resources/simulation.md
> +|cleanupArtifacts|Boolean|Flag representing if artifacts were cleaned up in the simulation.|
Line 27:
I feel those attack types are also fundamental concepts, and we should provide some info rather than letting customers guess how they differentiate.

FYI I deleted the table for the simulationAttackType enum in enums.md, and added a table below the "Properties" table, in a level 3 section, to let us explain each type of attack. (This btw follows the conventions of documenting enums that have values worth explaining, as documented here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations?anchor=second-option%3A-in-parent-resource-topic. Please take a look to get familiarized how to document enums.)

Please take a look at the table I'm adding that has the level 3 section title "simulationAttackType values", that immediately follows this "Properties" table. Please correct where necessary.

2021-09-04 09:36 UTC, angelgolfer-ms commented on api-reference/beta/resources/simulation.md
> +|mode|simulationMode|Mode of the simulation. Possible values are: `real`, `preview`, `unknownFutureValue`.|
Line 41:
Can you further explain those values?
For example, what does "real" mean, when a simulation is assumed to be not a real attack?
What does "preview" mean? Does it mean staged?

2021-09-04 09:42 UTC, angelgolfer-ms commented on api-reference/beta/resources/simulation.md
> +|mode|simulationMode|Mode of the simulation. Possible values are: `real`, `preview`, `unknownFutureValue`.|
If it's a simple explanation, you can add 1-2 sentences before the "Possible values..." sentence.
If you need to add more than 1-2 sentences, then please follow the convention of adding a level 3 section after the "Properties" table, and adding a table with 2 columns ("Member" and "Description"), as described here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations?anchor=second-option%3A-in-parent-resource-topic

2021-09-04 09:42 UTC, angelgolfer-ms commented on api-reference/beta/resources/simulation.md
> +|trainingContentPreference|trainingContentPreference|Preference of the training content in the simulation. Possible values are: `unknown`, `microsoft`, `custom`, `noTraining`, `unknownFutureValue`.|
Line 46:
Can you provide more info?
For example, what does "microsoft" mean?
What does "noTraining" mean?

2021-09-04 09:45 UTC, angelgolfer-ms commented on api-reference/beta/resources/simulation.md
> +
Line 47:
Does "due date" mean the time by which the attack simulation training should be completed by assigned users of the tenant"?
If so, can you change the description to avoid using the same term "due date and time" which is part of the property name?

2021-09-04 10:05 UTC, angelgolfer-ms commented on api-reference/beta/api/simulation-list.md
> +| payloadId          |
Line 59:
Where does payloadId come from? I don't see that in simulation.md nor in your CSDL.

2021-09-04 10:11 UTC, angelgolfer-ms commented on api-reference/beta/api/simulation-list.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Lines 42-64:
Do I assume correctly this section was not generated but manually added (the CSDL doesn't include query parameter info)?
FYI I have reorganized the extra info you had provided in this section.

Generally, if the syntax (e.g., lines 34-38) is to show how to use a query parameter, then we should provide that syntax in the "Optional query parameters" section, and not in the "HTTP request" section.
I also added "Supports `$filter` and `$orderby`." to the description of each applicable property in simulation.md.

2021-09-04 10:22 UTC, angelgolfer-ms commented on api-reference/beta/api/simulation-list.md
> +    {
GLOBAL:
Please show real-looking values in the example response!
An example response section is meant to show customers the kind of values certain properties can return. It's different from the 'JSON representation" section.

Lines 108-132:
Please show real-looking values for properties.
Please see this topic for the kinds of values you can or cannot use in docs: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103160/Fictitious-names

2021-09-04 10:28 UTC, jasonjoh commented
Docs Build status updates of commit _[64e0f9d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64e0f9dce9fabb53a0778f9656b832f6e72ddd31)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/ [...]

2021-09-04 10:37 UTC, angelgolfer-ms commented on api-reference/beta/api/simulation-list.md
> +title: "List simulations"
Filename simulation-list.md:
Is this the filename that was generated? Can you please confirm?

I think the filename should be security-list-attacksimulation.md, according to the filenaming conventions: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming

2021-09-04 10:52 UTC, angelgolfer-ms requested changes
@aspati , FYI I reviewed a couple of files (simulation.md and simulation-list.md) in detail.
In the interest of time, I made some fixes to your content directly in the PR. Please take a look at my commit, and also comments that explain the changes. 
For some of the changes, I need you to review and make appropriate updates where necessary.

Please also see my comments that include the term "GLOBAL" - these are comments that generally apply to other topics as well, and I may not make individual comments to every topic that has a similar issue.
For example, some of the descriptions for properties are not helpful, as they use the same few words in the property names. In some cases, I specifically requested you to provide more details. In the interest of time, it would be good if you can take a look at the descriptions for other properties and methods in this PR, and make them more informative.

One more thing - you'd notice your PR right now has API Doctor errors: https://dev.azure.com/msrobots/apidoctor/_build/results?buildId=64049&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dac0b392-2308-5704-b9f7-c5b20adf012e&l=25908

The fix is:
In VS Code, please search for the line author: "gopkr" to get the 23 files in your PR that are your files.
Replace this line:
localization_priority: Normal
By this line:
ms.localizationpriority: Menium

(Correct, it's "Menium", no typo there.)

Please let me know preferably on Teams if you have any specific questions on this.

Thanks.

2021-09-06 06:45 UTC, jasonjoh commented
Docs Build status updates of commit _[0836437](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0836437e837ac2b8a3e650cf784e72c6b6baa99a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/ [...]

2021-09-06 07:47 UTC, aspati commented on api-reference/beta/api/simulation-list.md
> +title: "List simulations"
@angelgolfer-ms - There were 2 separate files generated by docs generator, security-list-attacksimulation.md and simulation-list.md. The former had API - GET /security/attackSimulation and latter - GET /security/attackSimulation/simulations. For us, only simulation-list.md is relevant so removed security-list-attacksimulation.md file from the pull request.

2021-09-06 09:03 UTC, aspati commented on api-reference/beta/api/simulation-list.md
> +| payloadId          |
Agree, it should not have been there. Thanks for fixing it.

2021-09-06 09:17 UTC, aspati commented on api-reference/beta/api/simulation-list.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
@angelgolfer-ms - Addressed the above comment

2021-09-06 09:21 UTC, aspati commented on api-reference/beta/resources/simulation.md
> +|attackTechnique|simulationAttackTechnique|Attack technique of the simulation. Possible values are: `unknown`, `credentialHarvesting`, `attachmentMalware`, `driveByUrl`, `linkInAttachment`, `linkToMa
Covered in the above comment. Resolving this one.

2021-09-06 09:22 UTC, jasonjoh commented
Docs Build status updates of commit _[77d14bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/77d14bfa2d54fa889f4a7cb9316a70007159ade1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/ [...]

2021-09-08 02:53 UTC, opbld34 commented
Docs Build status updates of commit _[7050278](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70502780a968b888553fa606c93f7193851691eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/ [...]

2021-09-08 03:14 UTC, angelgolfer-ms commented on api-reference/beta/api/simulation-list.md
> +title: "List simulations"
Do you still have the set of generated topics saved somewhere?

Now I have the CSDL side-by-side with the syntax (simulations is a nav property, not a property, of attackSimulationRoot, my mistake in my last review), I think the filename should be **attacksimulationroot-list-simulations.md**.

That, would follow the list operation filename convention in this CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming

"API (list) | Use parententityname-list-navigationpropertyname if there is a parent entity that has a relationship to the resource to be listed, and otherwise resourcename-list."



<!--EndFragment-->
</body>
</html>

 <EntityType Name="security" ags:IsMaster="false" >
                <NavigationProperty Name="attackSimulation" Type="self.attackSimulationRoot" ContainsTarget="true"/>
            </EntityType>

            <!-- /security/attackSimulation -->
            <EntityType Name="attackSimulationRoot" ags:isMaster="true" >
                <!-- /security/attackSimulation/simulations -->
                <NavigationProperty Name="simulations" Type="Collection(self.simulation)" ContainsTarget="true"/>
            </EntityType>

This query URL is:
GET  /security/attackSimulation/simulations.

2021-09-08 03:20 UTC, angelgolfer-ms commented on api-reference/beta/api/simulation-list.md
> +title: "List simulations"
So was there a file named attacksimulationroot-list-simulations.md generated?

2021-09-13 09:36 UTC, aspati commented on api-reference/beta/api/simulation-list.md
> +title: "List simulations"
@angelgolfer-ms - Yes, there was a file attacksimulationroot-list-simulations.md generated, which is exactly same as simulations-list.md. Pasting a screenshot of autogenerated files below:
![image](https://user-images.githubusercontent.com/40426435/133060912-d7baeb8f-10e5-4753-be1c-2e70514b9708.png)

2021-09-13 09:44 UTC, opbld33 commented
Docs Build status updates of commit _[4e5147b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e5147b410022a9c39179f5ec238d5f2db260f4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/ [...]

2021-09-13 15:05 UTC, opbld31 commented
Docs Build status updates of commit _[02a3e5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02a3e5f8b29dbdfee1bbe45ff08f57bf87e01b69)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/usertrainingstatusinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/usertrainingstatusinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usertrainingstatusinfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-fcebe8af5a2585ca3241631f250e1df5-8f6b9b1c)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventsc [...]

2021-09-13 15:11 UTC, opbld31 commented
Docs Build status updates of commit _[69a6ffc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/69a6ffc603124f1f7af3b2f00106dfd26088a3d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/ [...]

2021-09-13 17:06 UTC, opbld32 commented
Docs Build status updates of commit _[b797095](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b79709557e07deabcaf3802a54dc0765f898920e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/ [...]

2021-09-14 05:07 UTC, opbld30 commented
Docs Build status updates of commit _[d080386](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0803861d4cc0aead7ff20c7a5f2b8c8743ec313)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulation-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/ [...]

2021-09-16 07:43 UTC, angelgolfer-ms commented on api-reference/beta/api/simulation-list.md
> +title: "List simulations"
@aspati , based on your earlier replies here, it seems attacksimulationroot-list-simulations.md was generated with the syntax GET /security/attacksimulation/simulations.
Can you use that filename for the "list simulations" topic then? Thanks.

2021-09-16 08:16 UTC, angelgolfer-ms commented on api-reference/beta/resources/simulation.md
> +
Lines 49-132:
In general, enum tables in a parent resource topic (like here) should have a "Description" column, just wanted to be clear. Not sure if you intend to add descriptions to all these tables or some of them.
I'll note the enum members that can benefit from having some descriptions.

2021-09-16 08:16 UTC, angelgolfer-ms commented on api-reference/beta/resources/simulation.md
> +|driveByUrl|
Line 56:
It might be helpful to describe what a driveByUrl is.

2021-09-16 08:17 UTC, angelgolfer-ms commented on api-reference/beta/resources/simulation.md
> +|driveByUrl|
Just to be clear, if you add a description to one member, then please also add descriptions to the other members of the same enum.

2021-09-20 05:32 UTC, opbld34 commented
Docs Build status updates of commit _[8c4c93d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c4c93d1d68c92425ec1846af4c8d3e58c4b80f6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-bb69758f)
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-841b65353a5e7a6f12f1b49d810a6e91-bb69758f)
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation [...]

2021-09-20 05:38 UTC, opbld31 commented
Docs Build status updates of commit _[f22543d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f22543dfaf4240a1bd115d4aa9f4716899432c9f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resourc [...]

2021-09-20 05:59 UTC, opbld34 commented
Docs Build status updates of commit _[59ed362](https://github.com/microsoftgraph/microsoft-graph-docs/commits/59ed362b9dd95c8e3d4bb253c3df14b5c27893ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resourc [...]

2021-09-20 12:09 UTC, opbld31 commented
Docs Build status updates of commit _[203bb13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/203bb136a81097d35cc3142f1c3a79c41a2094e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resourc [...]

2021-09-24 03:04 UTC, opbld30 commented
Docs Build status updates of commit _[3c3cb70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c3cb70d22558042d5ab5ff2ab02bca115bfb28e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resourc [...]

2021-09-24 05:30 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Attack Simulation and Training coverage
Lines 13171-13187:
@aspati , I don't think you can include your simulation/training reports under this node "Microsoft 365 usage reports". If you look at the existing overview topic (line 13169), that set of API is "to get the information about how people in your business are using Microsoft 365 services".
Those reports also follow some common conventions, e.g., specific format (.csv). 

Do you feel strongly that the simulation reports should be exposed under the "Reports" node? 

If so, then you will have to create a new sub-node under "Reports". I'd suggest that sub-node to be called "Security reports". But IMO, it's not a must to expose them under the "Reports" node. Those reports are relevant if the customer is looking into security, and we have a "Security" top level node already.

**MY action item**:
Whether you would like a new-subnode "Security reports" under "Reports", or not exposing them under "Reports", FYI I'm going ahead to remove report.md from your PR. (That's the existing [overview topic](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13789) for the Microsoft 365 usage reports, which your reports shouldn't be part of.)

**Your action item**:
And if you decide **_not_** to include them under "Reports", please delete lines 13171-13187.

If you decide to create a "Security reports" sub-node under "Reports", then please move these lines accordingly to the new sub-node.

2021-09-24 05:35 UTC, aspati commented on api-reference/beta/toc.yml
> +        - name: Attack Simulation and Training coverage
@angelgolfer-ms , API architects asked us to include our api under reports node, so our api looks like, for eg:, /reports/getAttackSimulationTrainingUserCoverage. Hence we included 3 of our api's under reports node to be present here.

2021-09-24 05:38 UTC, opbld30 commented
Docs Build status updates of commit _[bb0dfa3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb0dfa37a350d444eb28acd32a0f0952ca201e23)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationeventscontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationeventscontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationeventscontent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationreportoverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationreportoverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationreportoverview?view=graph-rest-beta&branch=pr-en-us- [...]

2021-09-24 05:53 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Attack Simulation and Training coverage
Yes, I noticed. BUT FYI, the TOC organization does not map to the query paths in general.

I was actually going to ask you move those lines 13173-13189 to a new sub-node "Reports" under Security >> Attack simulation and training. "Reports" will be a peer node of the "Simulations" node. 

If you really want to expose these sim reports under the "Reports" top level node as well, then in addition to the above, please create a new node "Security reports" under the top level "Reports" node. That "Security reports" node will be a peer of the existing "Microsoft 365 usage reports" node.
If you do this, then please also create a brief overview for this "Security reports" node. You notice that the other peer nodes (Microsoft 365 usage reports, Azure AD activity reports, Identity and access reports) each has their own overview as well. It will also make it clear the nature of these reports, which is quite different from the other production reports.

2021-09-24 06:09 UTC, opbld31 commented
Docs Build status updates of commit _[78ff5a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78ff5a0fcdbfd59a41f2940c5401117ed6e9e6c5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-aada65d52906304776093f8573d5b778-e2eeee9b)
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) ( [...]

2021-09-24 06:18 UTC, opbld33 commented
Docs Build status updates of commit _[bc214c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc214c9deeaf3a9a771fc04b85358ffade33e445)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2021-09-24 07:02 UTC, opbld32 commented
Docs Build status updates of commit _[8b6fe73](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b6fe73308e6c88307a03a6807ce62ee3c530b67)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2021-09-24 07:07 UTC, opbld33 commented
Docs Build status updates of commit _[163e908](https://github.com/microsoftgraph/microsoft-graph-docs/commits/163e9088ce9f33648efd3348744f44ed104ba24d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2021-09-24 07:09 UTC, angelgolfer-ms commented on api-reference/beta/api/simulationreportoverview-get.md
> +GET /security/attackSimulation/simulations/{id}/report/overview
Line 33:
@aspati , according to your CSDL, the report segment here is defined as a report property of the simulation resource, and it's of the type simulationReport:

```
<Property Name="report" Type="self.simulationReport" />
```

And simulationReport is defined in your CSDL as:
```
            <ComplexType Name="simulationReport">
                <!-- /security/attackSimulation/simulations/{id}/report/overview -->
                <Property Name="overview" Type="self.simulationReportOverview" />
                <!-- /security/attackSimulation/simulations/{id}/report/simulationUsers -->
                <Property Name="simulationUsers" Type="Collection(self.userSimulationDetails)" />
            </ComplexType>
```

However, I don't see that report property in simulation.md topic, and there is no simulationreport.md topic for that complex type either.
Has something changed? Please clarify.

2021-09-24 07:17 UTC, aspati commented on api-reference/beta/toc.yml
> +        - name: Attack Simulation and Training coverage
@angelgolfer-ms , If TOC organization does not need to map to the query paths, from customer's perspective, it would be desirable to keep documentation of all attacksim api's together. Can you confirm if it is okay that we create a new sub node Reports under Security >> Attack Simulation and Training, as peer of simulations?
This would mean say for Simulations node under Security >> Attack Simulation and Training in TOC, the corresponding API for it is /security/attackSimulation/simulations.
And for Reports node under Security >> Attack Simulation and Training in TOC, the corresponding API for it is /reports/getAttackSimulationRepeatOffenders etc.
**Just want to confirm that if it is okay to deviate TOC (viz. documentation) structure from underlying api?**

2021-09-24 07:24 UTC, aspati commented on api-reference/beta/api/simulationreportoverview-get.md
> +GET /security/attackSimulation/simulations/{id}/report/overview
@angelgolfer-ms - I think this was done because report property is not returned as part of list simulations call (hidden odata type while returning). But it is a property of simulation entity. Due to the above mentioned reason of list simulations, i removed it from simulation.md also. Should it be included in simulation.md?

2021-09-24 07:35 UTC, opbld30 commented
Docs Build status updates of commit _[34cb557](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34cb55710a070f6355167295a3f57c0c09fd37a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2021-09-25 07:33 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Attack Simulation and Training coverage
Yes, it's ok.
For the TOC, we don't organize APIs based on query URL paths. We organize APIs based on functionality and discoverability.
It's fine if we want to expose these 3 reports under the "Reports" top level node and "Security" top level node.
Here, I would prioritize the latter, so that at least your customers looking at the actual APIs for simulation training can become aware of these reports. I'm taking care of this part right now.
If you'd like to expose the reports also under the "Reports" top level node, then please see my last comment in this thread and prepare a short overview for it.

2021-09-25 09:09 UTC, opbld33 commented
Docs Build status updates of commit _[6c57286](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c572865ec8e2f3f64d83836126a308789c99fec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2021-09-25 09:10 UTC, opbld33 commented
Docs Build status updates of commit _[c2ca483](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2ca4838e97cbf6a6dfb386763b20fe0aef57efe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2021-09-25 09:23 UTC, opbld32 commented
Docs Build status updates of commit _[f6b5304](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6b530484c132ff14dc91625b0a5291294d2503f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2021-09-25 09:48 UTC, opbld33 commented
Docs Build status updates of commit _[2151bbf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2151bbf7849e7198c90e15174abbfae2fad2249f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulationevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulationevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulationevent?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2021-09-27 00:39 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-api-overview.md
> +[Attack simulation and training](/microsoft-365/security/office-365-security/attack-simulator) is a Microsoft 365 service that lets customers experience a realistic attack and learn from it. Social e
Line 57:
The destination of that first link points to a topic that gives an impression it's obsolete:
"Attack Simulator as described in this article is now read-only and has been replaced by Attack simulation training in the Email & collaboration node in the Microsoft 365 Defender portal at https://security.microsoft.com. For more information, see [Get started using Attack simulation training](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide)."

I think [Simulate a phishing attack](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training?view=o365-worldwide) is more current and a better overview topic to link to. It also points to the [Get started using Attack simulation training](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide) topic.

FYI I have updated the link to such.

2021-09-27 04:29 UTC, opbld30 commented
Docs Build status updates of commit _[2b189d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b189d278171a7eb71f7d1e3a2c975048206d2ff)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-3908126d)
[api-reference/v1.0/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/v1.0/resources/report-m365defender-reports-overview.md) | :warning:Warning | | [Details](#user-content-a367250b4c1533b620a5ad28fada0613-3908126d)

<a id="0817dce4456c16725d5333633847d38f-3908126d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/toc.yml)
 - **Line 13391, Column 14**: **[Error-yaml-syntax-error]** `````While scanning a multiline plain scalar, found invalid mapping.`````

<a id="a367250b4c1533b620a5ad28fada0613-3908126d"></a>
### [api-reference/v1.0/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/v1.0/resources/report-m365defender-reports-overview.md)
 - **Line 40, Column 33**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'attacksimulationrepeatoffender.md'.`````
 - **Line 40, Column 103**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/reportroot-getattacksimulationrepeatoffenders.md'.`````
 - **Line 41, Column 59**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'attacksimulationsimulationusercoverage.md'.`````
 - **Line 41, Column 145**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/reportroot-getattacksimulationsimulationusercoverage.md'.`````
 - **Line 42, Column 49**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'attacksimulationtrainingusercoverage.md'.`````
 - **Line 42, Column 131**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/reportroot-getattacksimulationtrainingusercoverage.md'.`````
 - **Line 18, Column 1**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /microsoft-365/security/office-365-security/defender-for-office-365?view=o365-worldwide. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109270426502560-13789%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-28T04%3A29%3A10Z&sr=b&sp=r&sig=Wir7QLRP9BJ3YZehGqoKhujOhR%2BvVEcIK28jgpFEi4c%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-27 04:41 UTC, aspati commented on api-reference/beta/resources/security-api-overview.md
> +[Attack simulation and training](/microsoft-365/security/office-365-security/attack-simulator) is a Microsoft 365 service that lets customers experience a realistic attack and learn from it. Social e
Thanks @angelgolfer-ms

2021-09-27 04:42 UTC, opbld31 commented
Docs Build status updates of commit _[0d8d889](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d8d889295c7e76d9a02ea1ed442e5bf4a0c9fd0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-783855d7)
[api-reference/v1.0/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/v1.0/resources/report-m365defender-reports-overview.md) | :warning:Warning | | [Details](#user-content-a367250b4c1533b620a5ad28fada0613-783855d7)

<a id="0817dce4456c16725d5333633847d38f-783855d7"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/toc.yml)
 - **Line 13391, Column 14**: **[Error-yaml-syntax-error]** `````While scanning a multiline plain scalar, found invalid mapping.`````

<a id="a367250b4c1533b620a5ad28fada0613-783855d7"></a>
### [api-reference/v1.0/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/v1.0/resources/report-m365defender-reports-overview.md)
 - **Line 40, Column 33**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'attacksimulationrepeatoffender.md'.`````
 - **Line 40, Column 103**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/reportroot-getattacksimulationrepeatoffenders.md'.`````
 - **Line 41, Column 59**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'attacksimulationsimulationusercoverage.md'.`````
 - **Line 41, Column 145**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/reportroot-getattacksimulationsimulationusercoverage.md'.`````
 - **Line 42, Column 49**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'attacksimulationtrainingusercoverage.md'.`````
 - **Line 42, Column 131**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/reportroot-getattacksimulationtrainingusercoverage.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109270439367035-13789%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-28T04%3A42%3A14Z&sr=b&sp=r&sig=Keqv1OFOPNyf97K3HJG%2B0cooBXV4FJwrqHTGYD1aOhg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-27 04:48 UTC, opbld34 commented
Docs Build status updates of commit _[536437f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/536437f8ac67af4ee52e061602ba7fa5cd0252eb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-091e92a7)

<a id="0817dce4456c16725d5333633847d38f-091e92a7"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/toc.yml)
 - **Line 13391, Column 14**: **[Error-yaml-syntax-error]** `````While scanning a multiline plain scalar, found invalid mapping.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109270446322170-13789%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-28T04%3A48%3A05Z&sr=b&sp=r&sig=ZhQR4YhIke3rwhKVYbRea1z6YZLTVA5uo41Hm%2F5wv4A%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-27 04:55 UTC, opbld30 commented
Docs Build status updates of commit _[fda0f0b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fda0f0b6f8626a9066e355311d80e554000bb92d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-2e6725dd)
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report-m365defender-reports-overview.md) | :bulb:Suggestion | | [Details](#user-content-4a8db42bca19ccfde505aa8fce93c0e8-2e6725dd)

<a id="0817dce4456c16725d5333633847d38f-2e6725dd"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/toc.yml)
 - **Line 13391, Column 14**: **[Error-yaml-syntax-error]** `````While scanning a multiline plain scalar, found invalid mapping.`````

<a id="4a8db42bca19ccfde505aa8fce93c0e8-2e6725dd"></a>
### [api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report-m365defender-reports-overview.md)
 - **Line 24, Column 3**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/defender-for-identity/' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109270454232882-13789%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-28T04%3A55%3A47Z&sr=b&sp=r&sig=s3ob%2Fji%2FHz5mzGF9SMvLFuoBdxsf93mkjPVwYQAyUI0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-27 05:18 UTC, opbld34 commented
Docs Build status updates of commit _[8cb94ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8cb94effb3647e3e194e11844c83ffb308417b67)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report-m365defender-reports-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr- [...]

2021-09-27 05:24 UTC, opbld33 commented
Docs Build status updates of commit _[9413a2f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9413a2fbef3cfa6b30578475175af4a9dcd5b1c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report-m365defender-reports-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-4a8db42bca19ccfde505aa8fce93c0e8-22cf42cf)
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ [...]

2021-09-27 06:37 UTC, opbld31 commented
Docs Build status updates of commit _[abd590b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/abd590b57952ce88b55401a2383d11aeff3dcd90)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-9eddee48)
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report-m365defender-reports-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-4a8db42bca19ccfde505aa8fce93c0e8-9eddee48)
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [Vie [...]

2021-09-27 06:44 UTC, opbld32 commented
Docs Build status updates of commit _[3b02877](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b02877c044f338b4396d5fd2233a6d8ec9125b2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report-m365defender-reports-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-4a8db42bca19ccfde505aa8fce93c0e8-8cd0553e)
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ [...]

2021-09-27 06:54 UTC, opbld30 commented
Docs Build status updates of commit _[f6bf959](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6bf959519e7659a123381b74d70cf8ba5114606)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report-m365defender-reports-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-4a8db42bca19ccfde505aa8fce93c0e8-40714cb6)
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ [...]

2021-09-27 07:40 UTC, angelgolfer-ms commented on api-reference/beta/resources/attacksimulationrepeatoffender.md
> +Represents repeat offender user in attack simulation and training.
Line 16:
@aspati , can you use some other words to explain what an "offender user" is?

2021-09-27 07:49 UTC, angelgolfer-ms commented on api-reference/beta/resources/attacksimulationuser.md
> +|userId|String|External directory object id of a user.|
Line 23:
@aspati , what do you mean by "external directory object"? I thought this is the id property of a user resource, which inherits from directoryObject.
Do you mean this ID may not be a user ID in directoryObject?

If this is indeed the user id property, I think we can clarify this as "ID of a user in a tenant.", and add a link to the user resource. In the Graph docs, the user resource is commonly referenced; not so much the base type directoryObject resource, because directoryObject serves as a base type for a number of other significant resources in Graph. 

If this is something else, then please clarify.

2021-09-27 08:46 UTC, aspati commented on api-reference/beta/resources/attacksimulationrepeatoffender.md
> +Represents repeat offender user in attack simulation and training.
@angelgolfer-ms - Done

2021-09-27 08:49 UTC, aspati commented on api-reference/beta/resources/attacksimulationuser.md
> +|userId|String|External directory object id of a user.|
@angelgolfer-ms - Added link for user resource

2021-09-27 08:55 UTC, opbld33 commented
Docs Build status updates of commit _[048cc17](https://github.com/microsoftgraph/microsoft-graph-docs/commits/048cc171926048484a067cf72fb74c6f44ce671b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report-m365defender-reports-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr- [...]

2021-09-27 09:02 UTC, angelgolfer-ms commented on api-reference/beta/resources/report-m365defender-reports-overview.md
> +- [Microsoft Defender for Identity](/defender-for-identity/)
@aspati , for the link in line 24, I wonder if there's a bug in API Doctor. That's why I put the link back as an HTTP link. The docs platform guidance on the other hand wants authors to use a site relative link (like /defender-for-identity/).

2021-09-27 09:10 UTC, angelgolfer-ms commented on changelog/Microsoft.Security.AttackSimulation.json
> +          "Id": "86bb6c22-23cb-4ed1-9903-7d5fb8d7ca76",
Lines 258, 266, 274:
@aspati , can you change the second part of these descriptions to "... method to the reportRoot resource"?

This is a known bug in the changelog generation process.

2021-09-27 09:14 UTC, angelgolfer-ms commented on changelog/Microsoft.Security.AttackSimulation.json
> +          "Id": "86bb6c22-23cb-4ed1-9903-7d5fb8d7ca76",
Lines 237-244:
The security resource was pre-existing, so we can't say "added the security resource".

It seems like this changelist hasn't specified adding the attachSimulation navigation property to the security resource?
If that's the case, please add a changelist record for that. You can take a look at the corresponding example in the CDK topic to specify your changelist record correctly: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-examples

2021-09-27 09:16 UTC, angelgolfer-ms commented on changelog/Microsoft.Security.AttackSimulation.json
> +          "Id": "86bb6c22-23cb-4ed1-9903-7d5fb8d7ca76",
Lines 229-236:
The reportRoot resource was pre-existing, so we can't say "added the reportRoot resource". Please delete this changelist record.

2021-09-27 15:18 UTC, opbld33 commented
Docs Build status updates of commit _[9d87f63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d87f63f9e41b02fba1baa213720ebc1a47b2856)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report-m365defender-reports-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-4a8db42bca19ccfde505aa8fce93c0e8-c7bcab01)
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ [...]

2021-09-28 03:23 UTC, opbld30 commented
Docs Build status updates of commit _[ed18016](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed18016538fae49de011d5049191442ab95e9c4d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report-m365defender-reports-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-4a8db42bca19ccfde505aa8fce93c0e8-ac7b52c5)
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ [...]

2021-09-28 03:59 UTC, opbld30 commented
Docs Build status updates of commit _[bd5ebe8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd5ebe8f7e3250c680f90ac681772217f1d99b43)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report-m365defender-reports-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-4a8db42bca19ccfde505aa8fce93c0e8-276950aa)
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ [...]

2021-09-28 04:16 UTC, opbld30 commented
Docs Build status updates of commit _[8f5efb3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f5efb3b0d2c866c92b1db13507f585952da0bc0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/report-m365defender-reports-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) | [Details](#user-content-4a8db42bca19ccfde505aa8fce93c0e8-c8450a1c)
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/assignedtraininginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/assignedtraininginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedtraininginfo?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationrepeatoffender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationrepeatoffender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationrepeatoffender?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationroot?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/attacksimulationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/attacksimulationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attacksimulationuser?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/emailidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/emailidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailidentity?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/recommendedaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/recommendedaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendedaction?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-13789) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-10-aspati-astgraph-apidocs-test1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ [...]

2021-09-28 04:34 UTC, merged