added changes for malware addition in driveitem and changelogs
microsoftgraph/microsoft-graph-docs pull request #13795
Opened 2021-08-10 22:23 UTC by paagarwal123

This PR contains 3 changes:
1. Addition of malware.md file.
2. Addition of malware property in driveItem.
3. Changing the driveitem-delta.md to remove limitation on lastModifiedBy property visibility in delta API for Onedrive for Business.

2021-08-10 22:24 UTC, opbld32 commented
Docs Build status updates of commit _[bef7d72](https://github.com/paagarwal123/microsoft-graph-docs/commits/bef7d72c1edfdcb68606fb2db254806a7573fa4d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/malware.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) | [Details](#user-content-6bfb3806642df17208652048ce13fabf-7ab39d2d)
[api-reference/beta/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="6bfb3806642df17208652048ce13fabf-7ab39d2d"></a>
### [api-reference/beta/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/malware.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 10**: **[Warning-[ms-date-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Invalid date format for 'ms.date': '20/07/2021'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108102223122675-13795%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=WpHC87KeNXyRhYGlDLKqtEAeJCaoUAGCMcsDJyX3jJw%3D&st=2021-08-10T22%3A19%3A36Z&se=2021-09-10T22%3A24%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-10 22:42 UTC, opbld34 commented
Docs Build status updates of commit _[15b3112](https://github.com/paagarwal123/microsoft-graph-docs/commits/15b3112e6d0970b8a84ae3e53e80540fe7fdd7a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108102241037673-13795%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=LzaJnVwGhG3sDTowdp9MM%2B6dzq3J5V5RnYBq%2FP1moTI%3D&st=2021-08-10T22%3A37%3A36Z&se=2021-09-10T22%3A42%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-18 16:33 UTC, k-tsoi reviewed
some small changes I detected

2021-08-18 16:33 UTC, k-tsoi commented on api-reference/beta/resources/malware.md
> +| **description** | string | It is a String type. It contains the virus details for the malware facet.
I think you can remove "it is a string type."

2021-08-18 16:33 UTC, k-tsoi commented on api-reference/beta/resources/malware.md
> +For more information about the facets on a DriveItem, see [driveItem][].
DriveItem -> driveItem (Graph likes objects to be lowerCamelCase)

2021-08-20 21:00 UTC, paagarwal123 commented on api-reference/beta/resources/malware.md
> +| **description** | string | It is a String type. It contains the virus details for the malware facet.
Removed

2021-08-20 21:00 UTC, paagarwal123 commented on api-reference/beta/resources/malware.md
> +For more information about the facets on a DriveItem, see [driveItem][].
Done

2021-08-20 21:01 UTC, opbld32 commented
Docs Build status updates of commit _[76838b8](https://github.com/paagarwal123/microsoft-graph-docs/commits/76838b8f4453ef479c596dd543a59e6a3db06966)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108202059431424-13795%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=vZhArkeEixVLtIC7AgAexDSCwKRdUVzeZtdlh3H0OIs%3D&st=2021-08-20T20%3A56%3A18Z&se=2021-09-20T21%3A01%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-25 12:59 UTC, opbld30 commented
Docs Build status updates of commit _[b2e3a7c](https://github.com/paagarwal123/microsoft-graph-docs/commits/b2e3a7c758cfb6c096f4ed8c280158cb84efbf65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108251257497210-13795%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=gt3yRZ3%2BRdA3yneWNFmOEA%2Bhaz%2BUY2jHa%2BBoG2CcNvM%3D&st=2021-08-25T12%3A54%3A20Z&se=2021-09-25T12%3A59%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-31 17:46 UTC, k-tsoi approved these changes

2021-09-02 20:29 UTC, JarbasHorst requested changes

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/beta/resources/malware.md
> +## JSON representation
Please move JSON representation to come after Properties.

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/beta/resources/malware.md
> +  "description": "DOS/EICAR_Test_File"
Resource topics don't contain examples in the JSON representation. Please, add the correct type to the description property.

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/beta/resources/malware.md
> +## Remarks
We don't support non-standard H2s. Please, incorporate that information into the summary description at the beginning of the article and remove Remarks.

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/beta/resources/malware.md
> +| **description** | string | It contains the virus details for the malware facet.
Please, replace string with String.

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/beta/resources/malware.md
> +| Property        | Type   | Description
For compatibility, you should also add a pipe on either end of the row. Please, apply this change to all rows in this table.

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/v1.0/resources/driveitem.md
> +| malware              | [malware][]        | Malware metadata, if the item was detected to contain malware. Read-only.
Please, keep the list in alphabetical order. In this case, move "malware" to come after "location".

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/v1.0/resources/malware.md
> +title: "Malware"
Make sure that the title field matches the H1. In this case, the title should be:
- malware resource type

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/v1.0/resources/malware.md
> +description: "The Malware resource indicates if malware has been detected in an item"
Resource names in Microsoft Graph are lower camel case, so malware in this case should be lower case. Also, please add a period at the end of the sentence. For clarity, I recommend you to rephrase the sentence. Suggested revision:

- The malware resource indicates that a malware was detected in an item.

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/v1.0/resources/malware.md
> +# Malware resource type
Resource names in Microsoft Graph are lower camel case, so malware in this case should be lower case.

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/v1.0/resources/malware.md
> +[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]
Please, remove the beta disclaimer as this is a v1.0 article.

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/v1.0/resources/malware.md
> +The **malware** resource indicates that malware has been detected in the item.
For consistency with the description, please replace has been with was. Also, add a before malware and replace the item with an item because we aren't talking about a particular one, but any. Suggested revision:

- The \*\*malware\*\* resource indicates that a malware was detected in an item.

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/v1.0/resources/malware.md
> +In this version of the API, the presence (non-null) of the resource indicates that item contains malware, while a null (or missing) value indicates that the item is clean.
I wonder why it is important to mention "in this version of the API". Are there different versions available for customers other than beta and v1.0. Since this resource topic is already beta, I recommend you to remove this part from your sentence because it doesn't add value to the description.

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/v1.0/resources/malware.md
> +In this version of the API, the presence (non-null) of the resource indicates that item contains malware, while a null (or missing) value indicates that the item is clean.
Articles help readers and translation software identify the nouns and modifiers in a sentence. Please, add the before item. Suggested revision:

- ...indicates that the item contains...

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/v1.0/resources/malware.md
> +In this version of the API, the presence (non-null) of the resource indicates that item contains malware, while a null (or missing) value indicates that the item is clean.
While is a word that can have a different meaning (can imply time); we should use unambiguous words where possible to help readability. In this case, I recommend you to create a new sentence. Suggested revision:

- ...contains malware. A null (or missing) value indicates that the item is clean.

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/v1.0/resources/malware.md
> +## JSON representation
Please move JSON representation to come after Properties.

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/v1.0/resources/malware.md
> +  "description": "DOS/EICAR_Test_File"
Resource topics don't contain examples in the JSON representation. Please, add the correct type to the description property.

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/v1.0/resources/malware.md
> +| Property        | Type   | Description
For compatibility, you should also add a pipe on either end of the row. Please, apply this change to all rows in this table.

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/v1.0/resources/malware.md
> +| **description** | string | It contains the virus details for the malware facet.
Please, replace string with String.

2021-09-02 20:29 UTC, JarbasHorst commented on api-reference/v1.0/resources/malware.md
> +## Remarks
We don't support non-standard H2s. Please, incorporate that information into the summary description at the beginning of the article and remove Remarks.

2021-09-02 20:29 UTC, JarbasHorst commented on changelog/Microsoft.FileServices.json
> +        "ApiChange": "ComplexType",
ComplexType is not on the list of approved values for ApiChange. Please change this to "Resource".

2021-09-02 20:29 UTC, JarbasHorst commented on changelog/Microsoft.FileServices.json
> +        "Description": "Removed SharePoint and OneDrive for Business driveItem delta limitation regarding properties omitted by delta query for lastModifiedBy.",
A word ending in –ing can be a verb, a noun, or an adjective. Please, avoid using gerunds where possible; in this case, you can change "regarding" to "about". Also, please add the before SharePoint and the before delta. Suggested revision:

- Removed the SharePoint and OneDrive for Business driveItem delta limitation about properties omitted by the delta query for lastModifiedBy.

2021-09-02 20:29 UTC, JarbasHorst commented on changelog/Microsoft.FileServices.json
> +        "ApiChange": "ComplexType",
ComplexType is not on the list of approved values for ApiChange. Please change this to "Resource".

2021-09-02 20:29 UTC, JarbasHorst commented on changelog/Microsoft.FileServices.json
> +        "Description": "Removed SharePoint and OneDrive for Business driveItem delta limitation regarding properties omitted by delta query for lastModifiedBy.",
A word ending in –ing can be a verb, a noun, or an adjective. Please, avoid using gerunds where possible; in this case, you can change "regarding" to "about". Also, please add the before SharePoint and the before delta. Suggested revision:

- Removed the SharePoint and OneDrive for Business driveItem delta limitation about properties omitted by the delta query for lastModifiedBy.

2021-09-06 19:01 UTC, jasonjoh commented
Docs Build status updates of commit _[84cd8b9](https://github.com/paagarwal123/microsoft-graph-docs/commits/84cd8b95fcf82bf58de6a037fd135da37e2b9fa0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-da3a9e27)

<a id="da3a9e27"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109061901289467-13795%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=WmC%2FIPf%2BTOSJjvNCwXSTBkps%2B6wOr1NzhqmgfdasR2o%3D&st=2021-09-06T18%3A56%3A50Z&se=2021-10-07T19%3A01%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-06 19:12 UTC, paagarwal123 commented on api-reference/beta/resources/driveitem.md
> +| malware              | [malware][]        | Malware metadata, if the item was detected to contain malware. Read-only.
Done the changes

2021-09-06 19:13 UTC, jasonjoh commented
Docs Build status updates of commit _[28dd02d](https://github.com/paagarwal123/microsoft-graph-docs/commits/28dd02d354f97b62bae70d54d69a251298e5b4c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109061911578904-13795%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=qPKcjzLtpmokOKLtjLp981XxSsi27U4e1E4hyCOGvBY%3D&st=2021-09-06T19%3A08%3A39Z&se=2021-10-07T19%3A13%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-06 19:47 UTC, jasonjoh commented
Docs Build status updates of commit _[92ecf71](https://github.com/paagarwal123/microsoft-graph-docs/commits/92ecf714b8d96d4f9e0ca02c150bd6d41d748293)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109061946075713-13795%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=a1Ka66x3w%2FeyvhqOEmuCtkmGlGCZXGdfA6MBLHLH9y4%3D&st=2021-09-06T19%3A42%3A49Z&se=2021-10-07T19%3A47%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-06 20:05 UTC, jasonjoh commented
Docs Build status updates of commit _[43ffb9a](https://github.com/paagarwal123/microsoft-graph-docs/commits/43ffb9a387cd2bb2ea5ded3190bc134f0688a3b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109062003457543-13795%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=lho%2B1G4k84T8BE9jkby7mRC13H5VmvJDuV0PZ2ZZhMY%3D&st=2021-09-06T20%3A00%3A25Z&se=2021-10-07T20%3A05%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-06 20:36 UTC, JarbasHorst requested changes

2021-09-06 20:36 UTC, JarbasHorst commented on api-reference/v1.0/resources/malware.md
> +| **description** | string | It contains the virus details for the malware facet. |
Please, replace string with String.

2021-09-07 14:56 UTC, opbld33 commented
Docs Build status updates of commit _[c04b090](https://github.com/paagarwal123/microsoft-graph-docs/commits/c04b09073160b656dd00f0c2a16a2cfa6e050cf3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109071453068692-13795%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=oHMt1z7hL%2B6Y%2Fke2jzm1o2jen%2Bve0SWmU42jg%2F8thro%3D&st=2021-09-07T14%3A50%3A59Z&se=2021-10-08T14%3A55%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-07 19:16 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-09-08 03:01 UTC, Lauragra approved these changes

2021-09-08 03:01 UTC, opbld33 commented
Docs Build status updates of commit _[6e47a19](https://github.com/paagarwal123/microsoft-graph-docs/commits/6e47a192682370fff6211daff81c6abdca31cfc6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109080300158143-13795%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=jH2YQK6fr%2FpYLHRcVQv%2FIfkEvjd%2BT0asynXWBk%2FDmtU%3D&st=2021-09-08T02%3A56%3A57Z&se=2021-10-09T03%3A01%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 03:03 UTC, opbld30 commented
Docs Build status updates of commit _[97ff6b2](https://github.com/paagarwal123/microsoft-graph-docs/commits/97ff6b2c0fb4445fabaa0ba43d103e55ebe6fe0e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109080300529381-13795%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=XFOylhJ91o19aU6lnNve5kZWll5aE4iE5auCGvIQNUY%3D&st=2021-09-08T02%3A58%3A44Z&se=2021-10-09T03%3A03%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 03:06 UTC, opbld30 commented
Docs Build status updates of commit _[7eaf8ed](https://github.com/paagarwal123/microsoft-graph-docs/commits/7eaf8edefb6675acc0a127c7d6c3db4f8c039845)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109080304454177-13795%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=%2B0CUc8VJb2d8A2K1JkROKroPcWmrsZ4pmCE%2B4Brq5pY%3D&st=2021-09-08T03%3A01%3A23Z&se=2021-10-09T03%3A06%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 03:08 UTC, opbld32 commented
Docs Build status updates of commit _[7eaf8ed](https://github.com/paagarwal123/microsoft-graph-docs/commits/7eaf8edefb6675acc0a127c7d6c3db4f8c039845)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/beta/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/beta/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-beta&branch=pr-en-us-13795) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-delta.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/driveitem.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/malware.md](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/api-reference/v1.0/resources/malware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/malware?view=graph-rest-1.0&branch=pr-en-us-13795) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/paagarwal123/microsoft-graph-docs/blob/paagarwal123-malwareChange/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109080304556052-13795%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=M%2FU5a7cPoS1ZlCV%2Bc%2BhD2ViLCH8hS8LprTsA6GOygq0%3D&st=2021-09-08T03%3A03%3A04Z&se=2021-10-09T03%3A08%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 03:09 UTC, merged