Adding Schema API conceptual topic for MS Graph connectors
microsoftgraph/microsoft-graph-docs pull request #13793
Opened 2021-08-10 21:59 UTC by mecampos

2021-08-10 22:01 UTC, opbld32 commented
Docs Build status updates of commit _[e90d4ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e90d4edcc3a51af12644fcf564e75db0dcd0e37e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-connectors-schemaapi?branch=pr-en-us-13793) | [Details](#user-content-d6641161fd46c78dd4128bccd65500b6-cc4ec0d0)
[concepts/connecting-external-content-connectors-schemaapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-connectors-schemaapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-connectors-schemaapi?branch=pr-en-us-13793) |

<a id="d6641161fd46c78dd4128bccd65500b6-cc4ec0d0"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml)
 - **Line 186, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'connecting-external-content-schemaapi.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108102159143295-13793%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Oc0Xrip1mxWT3gFiHDWfA2H53HYn02nGJuf0043ynn8%3D&st=2021-08-10T21%3A56%3A10Z&se=2021-09-10T22%3A01%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-10 22:08 UTC, opbld30 commented
Docs Build status updates of commit _[d4ba32d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d4ba32d0511cfc860e1784c9d37319b28f58d4bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-connectors-schemaapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-connectors-schemaapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-connectors-schemaapi?branch=pr-en-us-13793) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-connectors-schemaapi?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108102206594060-13793%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=iCcLHo7g8iD8w7fqFrApdhT07UJnwwjQW%2BWoOkh0R1M%3D&st=2021-08-10T22%3A03%3A31Z&se=2021-09-10T22%3A08%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-13 14:21 UTC, opbld31 commented
Docs Build status updates of commit _[3436778](https://github.com/microsoftgraph/microsoft-graph-docs/commits/343677856a20c42c80287fe9cc0e2b05994886d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-connectors-schemaapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-connectors-schemaapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-connectors-schemaapi?branch=pr-en-us-13793) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-connectors-schemaapi?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108131420242266-13793%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=wC1rWrpFEGGN9gZWqCwsBZ6R1O1IOG8m33m4O9%2F7eHA%3D&st=2021-08-13T14%3A16%3A48Z&se=2021-09-13T14%3A21%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-19 18:58 UTC, tony-zhu commented on concepts/connecting-external-content-connectors-schemaapi.md
> +|SEARCH     | Makes the text content of a property searchable. Property contents are included in the full-text index.         |  If the property is title, a query for Enterprise returns answers that
Should these be Searchable, Queryable, Retrievable, Refinable to match the actual schema attributes?

2021-08-19 18:58 UTC, tony-zhu commented on concepts/connecting-external-content-connectors-schemaapi.md
> +The following updates are planned for version v0.1:
Is it v0.1 or v1.0?

2021-08-19 18:58 UTC, tony-zhu commented on concepts/connecting-external-content-connectors-schemaapi.md
> +#### Deletion of a property
Deleting a property is still in design phase. We do not want to publicly document it yet.

2021-08-19 18:58 UTC, tony-zhu commented on concepts/connecting-external-content-connectors-schemaapi.md
> +#### Addition or removal of a Refiner
Adding/removal of refiners is also in design phase. We do not want to publicly document it yet.

2021-08-19 18:58 UTC, tony-zhu commented on concepts/connecting-external-content-connectors-schemaapi.md
> +The search admin will be allowed to add specific search attributes to a property.  As already discussed in the Refiners section above, adding the refiner search attribute as a schema change will not
Other than refinable. Searchable, Queryable, Retrievable, all could be both added or removed. Reingestion is strongly recommended because there will be inconsistent behavior of backward looking and forward looking items.

2021-08-19 18:58 UTC, tony-zhu commented on concepts/connecting-external-content-connectors-schemaapi.md
> +The removal or addition of an alias on a property do not require a reingestion as it is a query only concept.  The connection admins and 1st party schema owners will be allowed to add or remove alias
We do no plan to expose Substrate recrawler in any public document yet.

It is still in design phase, we haven't made a decision of whether/how to expose it to 3rd parties.

2021-08-19 18:58 UTC, tony-zhu commented on concepts/connecting-external-content-connectors-schemaapi.md
> +The one caveat to this is that the schema owner will be unable to remove the original alias of a refinable property that was auto-created by the system.
Where does this come from?

2021-09-06 23:08 UTC, mecampos commented on concepts/connecting-external-content-connectors-schemaapi.md
> +The one caveat to this is that the schema owner will be unable to remove the original alias of a refinable property that was auto-created by the system.
This information is in the "Schema Updates Version1" doc: https://microsoft.sharepoint.com/:w:/r/teams/greenland/_layouts/15/Doc.aspx?sourcedoc=%7BFB363F65-4575-4F60-AF87-482F208ED10C%7D&file=SchemaUpdatesV1.docx&action=edit&mobileredirect=true&wdPreviousSession=fb1db167-7fd8-4205-89e4-788e53297e43&wdOrigin=TEAMS-ELECTRON.teams.undefined&share=IQFlPzb7dUVgT6-HSC8gjtEMAVd9JtLoOarWO-zaFdnZq_Y

2021-09-06 23:08 UTC, mecampos commented on concepts/connecting-external-content-connectors-schemaapi.md
> +The removal or addition of an alias on a property do not require a reingestion as it is a query only concept.  The connection admins and 1st party schema owners will be allowed to add or remove alias
This information will not be included in the updates.

2021-09-06 23:08 UTC, mecampos commented on concepts/connecting-external-content-connectors-schemaapi.md
> +#### Addition or removal of a Refiner
This information will not be included in the updates.

2021-09-06 23:08 UTC, mecampos commented on concepts/connecting-external-content-connectors-schemaapi.md
> +#### Deletion of a property
This information will not be included in the updates.

2021-09-06 23:08 UTC, mecampos commented on concepts/connecting-external-content-connectors-schemaapi.md
> +The following updates are planned for version v0.1:
v1.0

2021-09-07 04:23 UTC, opbld32 commented
Docs Build status updates of commit _[16e077c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16e077c8002841c6f5a83f4675f01aee5c853193)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) | [Details](#user-content-d6641161fd46c78dd4128bccd65500b6-1cba0c03)
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

<a id="d6641161fd46c78dd4128bccd65500b6-1cba0c03"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml)
 - **Line 186, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'connecting-external-content-connectors-schemaapi.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109070421183210-13793%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=H7vjYzcZQ2SMLZfhVfwReIPhXJEjKrmONOz%2BJsM%2FEMI%3D&st=2021-09-07T04%3A18%3A00Z&se=2021-10-08T04%3A23%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-07 09:53 UTC, opbld32 commented
Docs Build status updates of commit _[ffebd8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ffebd8a4205548e2108208d84e485640bda99ce9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109070952107504-13793%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=1LmNv2p13VJVJ%2BDud9vQMYQtR%2FHBT6JC4RYt0LJGKdU%3D&st=2021-09-07T09%3A48%3A52Z&se=2021-10-08T09%3A53%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-07 11:30 UTC, opbld33 commented
Docs Build status updates of commit _[9669526](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96695260bd1bb069f147bd60467986a59d95dcb7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109071128214731-13793%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=jvWQ7JZVx1nUpbHODHGKQ%2B7gAmmuE%2F94Aw4xr1Cd4xw%3D&st=2021-09-07T11%3A25%3A08Z&se=2021-10-08T11%3A30%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-07 11:58 UTC, mecampos commented
See "Planned schema updates" section for review.

2021-09-14 00:43 UTC, mecampos commented
09/13/2021 Checked this PR, still pending comments on updates from reviewers.

2021-09-15 21:51 UTC, judyhnguyen commented on concepts/connecting-external-content-manage-schema.md
> +### Semantic labels
Hi @mecampos, should we link back to Step 6 from https://docs.microsoft.com/en-us/microsoftsearch/configure-connector#step-6-assign-property-labels to ensure the information is aligned?

2021-09-15 21:54 UTC, judyhnguyen commented on concepts/connecting-external-content-manage-schema.md
>  ## Next steps
@mecampos Will you add the rest of "Planned Schema Updates" from https://microsoft-my.sharepoint.com/:w:/p/mecampos/EUzDbjyGOwxMnW1p45MJ7qABGNgYgE227J0XCRn9ftfDCw?e=ajFjze into this documentation? I think you should.

2021-09-15 21:55 UTC, judyhnguyen requested changes
Hi @mecampos, can we add the rest of the content from https://microsoft-my.sharepoint.com/:w:/p/mecampos/EUzDbjyGOwxMnW1p45MJ7qABGNgYgE227J0XCRn9ftfDCw?e=ajFjze into the PR? Also, can we ensure we are not being redundant or provide conflicting information about semantic labels? Thank you!

2021-09-16 20:48 UTC, judyhnguyen commented on concepts/connecting-external-content-manage-schema.md
> +### Semantic labels
@David1997sb

2021-09-16 20:48 UTC, judyhnguyen commented on concepts/connecting-external-content-manage-schema.md
>  ## Next steps
+@David1997sb

2021-09-17 21:38 UTC, opbld34 commented
Docs Build status updates of commit _[5f95413](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f95413baec80ecb713bb2caeb2fd2cb77eb132c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) | [Details](#user-content-fc9b69389d3af92b2e240782d70cd019-bc054f16)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

<a id="fc9b69389d3af92b2e240782d70cd019-bc054f16"></a>
### [concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md)
 - **Line 179, Column 174**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'result-cluster.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109172136267757-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-18T21%3A38%3A27Z&sr=b&sp=r&sig=ZO1jPoqM3nnRAklAMRZS6EiYse8b40CAlBxwRvc4H4o%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 19:53 UTC, jmslau commented on concepts/connecting-external-content-manage-schema.md
> +A recrawler could be created in substrate that can touch the backward looking items such that it triggers a reingestion.  This way the data does not have to be refed from the source.
We shouldn't use terms like "substrate" in public documentation.

2021-09-24 20:26 UTC, jmslau commented on concepts/connecting-external-content-manage-schema.md
> +### Recrawler – North Star
Why are we talking about recrawler in substrate in our public documentation?

2021-09-24 20:27 UTC, jmslau commented on concepts/connecting-external-content-manage-schema.md
> +The following updates are for version v0.1.
What is version v0.1? The Graph API only has /beta and /v1.0

2021-09-24 20:43 UTC, opbld33 commented
Docs Build status updates of commit _[0be1ce9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0be1ce9a48412c112bc5566f56384807239d3384)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) | [Details](#user-content-fc9b69389d3af92b2e240782d70cd019-e0dd27d0)
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

<a id="fc9b69389d3af92b2e240782d70cd019-e0dd27d0"></a>
### [concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md)
 - **Line 179, Column 174**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'result-cluster.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109242041501447-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T20%3A43%3A27Z&sr=b&sp=r&sig=EF1hiVlLb%2BFMB8E%2BHHiHSt65H5VADKJMzKyKuGwNa2g%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 20:46 UTC, jmslau commented on api-reference/beta/resources/externalconnectors-schema.md
> +| [Update Schema](../api/externalconnectors-externalconnection-update.md)) | [schema](externalconnectors-schema.md) | Read properties of a schema object. |
This should link to externalconnectors-schema-update.md.
The description should say "Update a schema object."

2021-09-24 20:46 UTC, jmslau commented on api-reference/beta/toc.yml
> +            href: api/externalconnectors-externalconnection-update.md
This should link to a new externalconnectors-schema-update.md.

2021-10-04 20:41 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +A recrawler could be created in substrate that can touch the backward looking items such that it triggers a reingestion.  This way the data does not have to be refed from the source.
Thank you, I removed the mention of the recrawler  in a previous version of this PR, and will remove it again from the recent updates.

2021-10-04 20:42 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +### Recrawler – North Star
Thank you, I removed the mention of the recrawler  in a previous version of this PR, and will remove it again from the recent updates.

2021-10-04 20:43 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +The following updates are for version v0.1.
Agreed, the version should be referenced as beta.

2021-10-04 20:50 UTC, mecampos commented on api-reference/beta/toc.yml
> +            href: api/externalconnectors-externalconnection-update.md
I might need more information on this. This request was submitted to create a new topic initially, but it evolved to an update to the existing topic.

2021-10-04 21:25 UTC, mecampos commented on api-reference/beta/resources/externalconnectors-schema.md
> +| [Update Schema](../api/externalconnectors-externalconnection-update.md)) | [schema](externalconnectors-schema.md) | Read properties of a schema object. |
I need more details about this comment, the API document was not part of this PR.

2021-10-04 22:27 UTC, opbld31 commented
Docs Build status updates of commit _[9b075fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b075fec90a90e734b512c6e8396e50876774611)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) | [Details](#user-content-fc9b69389d3af92b2e240782d70cd019-15b6c111)
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

<a id="fc9b69389d3af92b2e240782d70cd019-15b6c111"></a>
### [concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md)
 - **Line 178, Column 143**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'result-cluster.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110042226049643-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-04T22%3A27%3A58Z&sr=b&sp=r&sig=WbUHT9seHqLeX5HI4bu5DIUfByCWvRsgHyQ0xype1mw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-05 17:44 UTC, judyhnguyen commented on api-reference/beta/resources/externalconnectors-schema.md
> +| [Update Schema](../api/externalconnectors-externalconnection-update.md)) | [schema](externalconnectors-schema.md) | Read properties of a schema object. |
We clarified this comment this morning 👍

2021-10-05 17:47 UTC, judyhnguyen commented on api-reference/beta/toc.yml
> +            href: api/externalconnectors-externalconnection-update.md
That is alright, we can just update the "Manage Schema" page instead of creating a new topic.

2021-10-05 22:25 UTC, mecampos commented on api-reference/beta/resources/externalconnectors-schema.md
> +| [Update Schema](../api/externalconnectors-externalconnection-update.md)) | [schema](externalconnectors-schema.md) | Read properties of a schema object. |
Discussed with Judy and Arvind, indeed we are talking about adding the API doc for schema update here. I am creating an empty doc for now, for testing purposes, I'll need to gather the content for that new file, and confirm if we can include it in the same PR due to the repository restrictions.

2021-10-20 18:56 UTC, opbld33 commented
Docs Build status updates of commit _[7a6af32](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a6af329f8d1531304c71d0c8a12c9ba4d79e5f5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-147e5052)
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/update-schema-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/includes/snippets/csharp/update-schema-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/update-schema-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/includes/snippets/java/update-schema-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/update-schema-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/includes/snippets/javascript/update-schema-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/update-schema-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/includes/snippets/objc/update-schema-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

<a id="0817dce4456c16725d5333633847d38f-147e5052"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml)
 - **Line 9514, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110201853430486-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-20T18%3A56%3A07Z&sr=b&sp=r&sig=3nlSX37ZbGqWOOr%2FZLYx7cuqp91NjmoR57cMUVurbF4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-02 21:58 UTC, JarbasHorst requested changes

2021-11-02 21:58 UTC, JarbasHorst commented on api-reference/beta/api/externalconnectors-schema-update.md
> +# [C#](#tab/csharp)
New API topics that are getting added do not need to include the SDK snippet links and files. Please remove the links from the API topics and remove the snippet files from the PR. The SDK snippets get added via automation after we merge.

2021-11-02 21:58 UTC, JarbasHorst commented on api-reference/beta/api/externalconnectors-schema-update.md
> +# [HTTP](#tab/http)
As described in the comment below, please remove the HTTP H1 (line 65). So, we don't have just the one tab.

2021-11-02 21:58 UTC, JarbasHorst commented on api-reference/beta/api/externalconnectors-schema-update.md
> +localization_priority: Normal
localization_priority isn't a valid property. Since you have already added the correct property "ms.localizationpriority", please remove "localization_priority: Normal" (line 4).

2021-11-02 21:58 UTC, JarbasHorst commented on api-reference/beta/api/externalconnectors-schema-update.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Please, be specific and add to this sentence a list of OData query parameters customers can use.

2021-11-02 21:58 UTC, JarbasHorst commented on api-reference/beta/api/externalconnectors-schema-update.md
> +When registering a custom item schema, the `schema` object MUST have the `baseType` property set to `microsoft.graph.externalItem` and MUST contain the `properties` property. The `properties` object
A word ending in –ing can be a verb, a noun, or an adjective. Please, avoid using gerunds where possible; in this case, you can change "registering" to "you register".

2021-11-02 21:58 UTC, JarbasHorst commented on api-reference/beta/api/externalconnectors-schema-update.md
> +When registering a custom item schema, the `schema` object MUST have the `baseType` property set to `microsoft.graph.externalItem` and MUST contain the `properties` property. The `properties` object
For consistency, please replace the uppercase word "MUST" with \*\*must\*\*. Should the third appearance of _must_ also have bold formatting applied?

2021-11-02 21:58 UTC, JarbasHorst commented on concepts/connecting-external-content-manage-schema.md
> +A semantic label is a well known tag published by Microsoft that you can add against a property in your schema. Adding a semantic label helps various Microsoft products understand the property and pr
Please, replace "well known" with "well-known".

2021-11-02 21:58 UTC, JarbasHorst commented on concepts/connecting-external-content-manage-schema.md
> +*A search for "design" displaying results for hits against the property (`title`) and content*
Please add a period at the end of this sentence. Please, apply this change also here:

- line 54
- line 58
- line 66
- line 74

2021-11-02 21:58 UTC, JarbasHorst commented on concepts/connecting-external-content-manage-schema.md
> +Semantic Labels provide a domain independent approach of assigning properties from different content domains to a set of well-known classes. They find applications in many different content experienc
The word Labels doesn't to be capitalized. Please, replace "Labels" with "labels".

2021-11-02 21:58 UTC, JarbasHorst commented on concepts/connecting-external-content-manage-schema.md
> +Semantic Labels provide a domain independent approach of assigning properties from different content domains to a set of well-known classes. They find applications in many different content experienc
For simplicity, I recommend you to replace "many different" with "various".

2021-11-02 21:58 UTC, JarbasHorst commented on concepts/connecting-external-content-manage-schema.md
> +* Building common Knowledge Graphs (e.g. Cortex, Suggestions & QF)
"Knowledge Graphs" doesn't to be capitalized. Please, replace "Knowledge Graphs" with "knowledge graphs".

2021-11-02 21:58 UTC, JarbasHorst commented on concepts/connecting-external-content-manage-schema.md
> +* Building common Knowledge Graphs (e.g. Cortex, Suggestions & QF)
Please, avoid non-English words or phrases. In this case, please replace "e.g." with "for example,". Suggested revision:

- ...(for example, Cortex and Suggestions & QF)

2021-11-02 21:58 UTC, JarbasHorst commented on concepts/connecting-external-content-manage-schema.md
> +> It is strongly recommended to re-ingest items after an update, to bring them to te latest schema. Without re-ingestion the behavior of the items will be inconsistent.
Please, replace "te" with "the". Also, please add a comma after "Without re-ingestion". Suggested revision:

- It is strongly recommended to re-ingest items after an update, to bring them to the latest schema. Without re-ingestion, the behavior of the items will be inconsistent.

2021-11-02 21:58 UTC, JarbasHorst commented on concepts/connecting-external-content-manage-schema.md
> +You can add or remove semantic labels. Adding a semantic label can affect experiences like Working Set, Relevance, and Project Cortex. If a re-ingestion occurs, these experiences will be fixed.
For clarity and readability, I recommend you emphasize the examples. Suggested revision:

-  Adding a semantic label can affect experiences like \`Working Set\`, \`Relevance\`, and \`Project Cortex\`.

2021-11-02 21:58 UTC, JarbasHorst commented on concepts/connecting-external-content-manage-schema.md
> +This section includes information about the update capabilities for the Schema API.
For clarity, I recommend you to add a link to the corresponding schema API . Also, Schema doesn't need to be capitalized. Please, replace Schema with schema. Suggested revision:

- This section includes information about the update capabilities for the \[schema\](...) API.

2021-11-02 22:16 UTC, JarbasHorst commented
@mecampos, your PR introduces a new method that modifies the **schema** resource topic. Please, add this change to the changelog.

2021-11-17 15:36 UTC, mecampos commented on api-reference/beta/api/externalconnectors-schema-update.md
> +# [C#](#tab/csharp)
Removed links and files.

2021-11-17 15:37 UTC, mecampos commented on api-reference/beta/api/externalconnectors-schema-update.md
> +# [HTTP](#tab/http)
Removed line.

2021-11-17 15:37 UTC, mecampos commented on api-reference/beta/api/externalconnectors-schema-update.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Removed line.

2021-11-17 15:38 UTC, mecampos commented on api-reference/beta/api/externalconnectors-schema-update.md
> +localization_priority: Normal
Removed line.

2021-11-17 17:01 UTC, mecampos commented on api-reference/beta/api/externalconnectors-schema-update.md
> +When registering a custom item schema, the `schema` object MUST have the `baseType` property set to `microsoft.graph.externalItem` and MUST contain the `properties` property. The `properties` object
Updated as recommended.

2021-11-17 17:06 UTC, mecampos commented on api-reference/beta/api/externalconnectors-schema-update.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Reviewing.

2021-11-17 17:14 UTC, mecampos commented on api-reference/beta/api/externalconnectors-schema-update.md
> +When registering a custom item schema, the `schema` object MUST have the `baseType` property set to `microsoft.graph.externalItem` and MUST contain the `properties` property. The `properties` object
Updated as recommended, and used bold formatting for 3rd appearance of _must_ .

2021-11-17 17:15 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +A semantic label is a well known tag published by Microsoft that you can add against a property in your schema. Adding a semantic label helps various Microsoft products understand the property and pr
Updated as recommended.

2021-11-17 17:21 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +*A search for "design" displaying results for hits against the property (`title`) and content*
Updated as recommended.

2021-11-17 17:24 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +Semantic Labels provide a domain independent approach of assigning properties from different content domains to a set of well-known classes. They find applications in many different content experienc
Updated as recommended.

2021-11-17 17:24 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +Semantic Labels provide a domain independent approach of assigning properties from different content domains to a set of well-known classes. They find applications in many different content experienc
Updated as recommended.

2021-11-17 17:25 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +* Building common Knowledge Graphs (e.g. Cortex, Suggestions & QF)
Updated as recommended.

2021-11-17 17:25 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +* Building common Knowledge Graphs (e.g. Cortex, Suggestions & QF)
Updated as recommended.

2021-11-17 20:05 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +> It is strongly recommended to re-ingest items after an update, to bring them to te latest schema. Without re-ingestion the behavior of the items will be inconsistent.
Updated as recommended.

2021-11-17 20:07 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +You can add or remove semantic labels. Adding a semantic label can affect experiences like Working Set, Relevance, and Project Cortex. If a re-ingestion occurs, these experiences will be fixed.
Updated as recommended.

2021-11-17 20:19 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +This section includes information about the update capabilities for the Schema API.
Updated as recommended.

2021-11-17 20:57 UTC, mecampos commented on api-reference/beta/api/externalconnectors-schema-update.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Please note I am removing the "Optional query parameters" section, because I confirmed that OData is not needed in this case.
In addition to this, I am updating the following files to reflect the same change:
api reference / beta: externalconnectors-schema-get.md
api reference / v1.0: externalconnectors-schema-get.md

2021-11-17 21:33 UTC, mecampos commented
During this review I found another section that needs to be updated, I am including one more update in 3 files, in the HTTP request section: "The properties object must contain at least one property, up to a maximum of 64."  -> It should be 128 instead of 64.
api reference / beta: externalconnectors-schema-update.md
api reference / beta: externalconnectors-externalconnection-post-schema.md
api reference / v1.0: externalconnectors-schema-create.md

2021-11-17 21:38 UTC, opbld33 commented
Docs Build status updates of commit _[8c9466c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c9466c0194d37b0baa4493a74553d110983367c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111172136473211-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T21%3A38%3A51Z&sr=b&sp=r&sig=PF4%2Foypn%2FTf9M1gldfmJtxAfBk2ZO8sUiYtQAYNWBcQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 22:18 UTC, JarbasHorst requested changes

2021-11-17 22:18 UTC, JarbasHorst commented on concepts/connecting-external-content-manage-schema.md
> +* Building common knowledge graphs (for example, Cortex, Suggestions & QF)
Please don't use & in place of and in text. Suggested revision:

- ...(for example, Cortex, Suggestions, and QF)

2021-11-17 22:18 UTC, JarbasHorst commented on api-reference/beta/api/externalconnectors-externalconnection-post-schema.md
> +When registering a custom item schema, the `schema` object MUST have the `baseType` property set to `microsoft.graph.externalItem` and MUST contain the `properties` property. The `properties` object
Please, avoid using gerunds where possible; in this case, you can change "registering" to "you register". For consistency, please replace the uppercase words "MUST" with \*\*must\*\*. You might also want to apply bold formatting to the third appearance of must.

2021-11-17 22:18 UTC, JarbasHorst commented on api-reference/beta/api/externalconnectors-schema-update.md
> +When you register a custom item schema, the `schema` object **must** have the `baseType` property set to `microsoft.graph.externalItem` and must contain the `properties` property. The `properties` ob
For consistency, you might also want to apply bold formatting to the second appearance of must.

2021-11-17 22:18 UTC, JarbasHorst commented on api-reference/v1.0/api/externalconnectors-schema-create.md
> +When registering a custom item schema, the `schema` object MUST have the `baseType` property set to `microsoft.graph.externalItem` and MUST contain the `properties` property. The `properties` object
Please, avoid using gerunds where possible; in this case, you can change "registering" to "you register". For consistency, please replace the uppercase words "MUST" with \*\*must\*\*. You might also want to apply bold formatting to the third appearance of must.

2021-11-17 22:18 UTC, JarbasHorst commented on concepts/connecting-external-content-manage-schema.md
> +*A set of retrievable properties (`title`, `lastEditedBy` etc.) rendered as a result.*
Please, don't use etc. Instead be specific. Suggested revision:

- ...(for example, `title` and `lastEditedBy`)...

2021-11-17 22:18 UTC, JarbasHorst commented on concepts/connecting-external-content-manage-schema.md
> +You can assign semantic labels to your source properties on the "Assign property labels" page. Labels provide semantic meaning, and allow to integrate your connector data into Microsoft 365 experienc
For clarity, I recommend you to apply bold formatting to "Assign property labels". Suggested revision:

- ...\*\*Assign property labels\*\* page...

2021-11-17 22:19 UTC, JarbasHorst commented
@mecampos, your PR introduces a new method that modifies the schema resource topic. Please, add this change to the changelog.

2021-11-17 22:27 UTC, opbld31 commented
Docs Build status updates of commit _[1988c6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1988c6bbb31f6fcf8d01650f814a184705c30133)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111172225549321-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T22%3A27%3A33Z&sr=b&sp=r&sig=embLfAUCZAw6ldDjq2mM8NzFwDJxWXYlfJTF0wkakxg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 22:40 UTC, opbld32 commented
Docs Build status updates of commit _[d67ebb3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d67ebb39888fe632dc881ba0d0bbbca793dd5afc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111172238492669-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T22%3A40%3A29Z&sr=b&sp=r&sig=iE1OoZphoXJeOnbqKIsZCHg8Mv%2Bwyc6XwrRbaELPmqE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 22:47 UTC, opbld34 commented
Docs Build status updates of commit _[6e183d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e183d8e63c2c28666dc2e2e30a93e6172b32a8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111172246179812-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T22%3A47%3A57Z&sr=b&sp=r&sig=3r1NN5KUfqkK%2BHI4U3Cou9HUSFVg%2FVns7n7QHAaOaQI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 22:53 UTC, opbld34 commented
Docs Build status updates of commit _[9ac9346](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ac9346314e2937e2afeac0a0dd7eeee8c4e2077)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111172251378521-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T22%3A53%3A21Z&sr=b&sp=r&sig=mKqRw0rvU%2FHdfHb8oLxVVV2d3LcHEDOWKbFLPxbJoLk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 22:56 UTC, opbld34 commented
Docs Build status updates of commit _[5444b39](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5444b3906a24a317c75f133e784b62091aa94446)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111172255088278-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T22%3A56%3A58Z&sr=b&sp=r&sig=%2FFQOu22PyBGk2HMjlOkjVosltPiA%2B%2BVguN3JJkDUmU0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 01:38 UTC, opbld31 commented
Docs Build status updates of commit _[cc202c3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc202c327241bdf7ad03ab17f26475842ea4bb46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111180137150476-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-19T01%3A38%3A58Z&sr=b&sp=r&sig=jbFfaUcCmTPP1eZdsuFxAP%2BZLJDolTeBk5vEPWzQ9Oc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-19 20:19 UTC, JarbasHorst requested changes

2021-11-19 20:19 UTC, JarbasHorst commented on changelog/Microsoft.Search.json
> +          "Description": "Added the **update schema** method to the [schema](https://docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta) resource type.",
For consistency, please replace "update schema" with a link to the method. Suggested revision:

- Added the \[update\](https://docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta) method to the...

2021-11-19 20:19 UTC, JarbasHorst commented on changelog/Microsoft.Search.json
> +          "ChangedApiName": "schema",
Please, add here the name of the API element, permission, or header that is being changed. In this case, it should be update.

2021-11-19 20:19 UTC, JarbasHorst commented on changelog/Microsoft.Search.json
> +          "ApiChange": "Resource",
Please, add here the API element that is being changed. In this case, it should be "Method".

2021-11-23 21:26 UTC, mecampos commented on api-reference/beta/api/externalconnectors-externalconnection-post-schema.md
> +When registering a custom item schema, the `schema` object MUST have the `baseType` property set to `microsoft.graph.externalItem` and MUST contain the `properties` property. The `properties` object
updated

2021-11-23 21:27 UTC, mecampos commented on api-reference/beta/api/externalconnectors-schema-update.md
> +When you register a custom item schema, the `schema` object **must** have the `baseType` property set to `microsoft.graph.externalItem` and must contain the `properties` property. The `properties` ob
updated

2021-11-23 21:30 UTC, mecampos commented on api-reference/v1.0/api/externalconnectors-schema-create.md
> +When registering a custom item schema, the `schema` object MUST have the `baseType` property set to `microsoft.graph.externalItem` and MUST contain the `properties` property. The `properties` object
updated

2021-11-23 21:31 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +* Building common knowledge graphs (for example, Cortex, Suggestions & QF)
updated

2021-11-23 21:32 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +*A set of retrievable properties (`title`, `lastEditedBy` etc.) rendered as a result.*
updated

2021-11-23 21:33 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +You can assign semantic labels to your source properties on the "Assign property labels" page. Labels provide semantic meaning, and allow to integrate your connector data into Microsoft 365 experienc
updated

2021-11-23 21:34 UTC, mecampos commented on changelog/Microsoft.Search.json
> +          "Description": "Added the **update schema** method to the [schema](https://docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta) resource type.",
updated

2021-11-23 21:38 UTC, opbld31 commented
Docs Build status updates of commit _[ea5b5bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea5b5bfd2b06a9aeb7704d0976407bb3d55ce781)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111232136405023-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-24T21%3A38%3A26Z&sr=b&sp=r&sig=Jc7EK%2B%2FX%2FNltfNgrZWKO1j%2Bg4HifCD2wIQkBGMu25v4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 19:54 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-11-29 19:37 UTC, Lauragra commented on api-reference/beta/api/externalconnectors-schema-get.md
> -## Optional query parameters
Why did we remove this section? Generally Get and List operation topics include it. If the operation doesn't support query parameters, we should include this H2 section and state that the optional query parameters are not supported.

2021-11-29 20:25 UTC, opbld31 commented
Docs Build status updates of commit _[35ebaf2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35ebaf2e1410b5c70671507cccb27126b77c01b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111292023338607-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-30T20%3A25%3A23Z&sr=b&sp=r&sig=xwabKNLsOe4d3dfJc4qm9e%2FdHT6czzZWIluavpw24U4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 20:25 UTC, opbld32 commented
Docs Build status updates of commit _[35ebaf2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35ebaf2e1410b5c70671507cccb27126b77c01b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111292023441416-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-30T20%3A25%3A39Z&sr=b&sp=r&sig=g29J5D%2FGXG%2BoGukwSxPTUF%2Fx74P50AQIJFHYAK8LOLc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 20:27 UTC, opbld33 commented
Docs Build status updates of commit _[3539b44](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3539b448f7b94e7a7a28d355825b734c5f38a54f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111292025324948-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-30T20%3A27%3A23Z&sr=b&sp=r&sig=Av2Ni99Sw4ZfmUA8W0vrssVvpY%2Bch2SGMlXdWaBGPF8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 20:35 UTC, opbld31 commented
Docs Build status updates of commit _[bb7855d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb7855dd938987c6c8af96ca6a272cf52d7baea6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111292033306556-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-30T20%3A35%3A19Z&sr=b&sp=r&sig=mM0kQ%2FmMh8FHikomavMEit%2Fr2y2AEoaieMMkckXPyp0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 21:18 UTC, opbld33 commented
Docs Build status updates of commit _[c38b75d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c38b75d325df5a274bda8abd8807f1d36e19053a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111292117200529-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-30T21%3A18%3A55Z&sr=b&sp=r&sig=GUUFnEDA9sK%2F%2BwKN5Cg80mbJ3U6Sy8f36l2nkI4UhyQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 21:21 UTC, opbld34 commented
Docs Build status updates of commit _[54a198a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/54a198ad2e0b2085eacb5ad8b81264a8c5a4aa81)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111292119431386-13793%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-30T21%3A21%3A33Z&sr=b&sp=r&sig=AboaxqybAAZB4T7QJzZszdPxKqnp4RgkiXuj%2BP9bm%2Bg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 21:22 UTC, Lauragra commented on concepts/connecting-external-content-manage-schema.md
> +* Building common knowledge graphs (for example, Cortex, Suggestions, and QF)
This should be Project Cortex, right? Is Suggestions an actual feature name that should be capitalized? And what is QF - is that an acronym that needs to be spelled out?

2021-11-29 21:23 UTC, Lauragra commented on concepts/connecting-external-content-manage-schema.md
> +Adding a semantic label can affect experiences like `Working Set`, `Relevance`, and `Project Cortex`.
What are these experiences and why are we capitalizing them/styling them as inline code?

2021-12-01 16:39 UTC, mecampos commented on api-reference/beta/api/externalconnectors-schema-get.md
> -## Optional query parameters
The reason is in previous comments "_"Please note I am removing the "Optional query parameters" section, because I confirmed that OData is not needed in this case._"
I'll add this section again.

2021-12-01 17:48 UTC, Arvind-Ravi commented on api-reference/beta/api/externalconnectors-schema-get.md
> -## Optional query parameters
@mecampos - Can we add it as H2 title with the following? 

"This method does not support [OData query parameters](/graph/query-parameters)."

2021-12-01 17:49 UTC, Arvind-Ravi commented on concepts/connecting-external-content-manage-schema.md
> +* Building common knowledge graphs (for example, Cortex, Suggestions, and QF)
@mecampos - Let's change it to 

"* Building common knowledge graphs (for example, Viva Topics)"

2021-12-01 17:49 UTC, Arvind-Ravi commented on concepts/connecting-external-content-manage-schema.md
> +Adding a semantic label can affect experiences like `Working Set`, `Relevance`, and `Project Cortex`.
@mecampos - Let's change it to 

Adding a semantic label can affect experiences like `Relevance` and `Viva Topics`.

2021-12-01 18:29 UTC, mecampos commented on api-reference/beta/api/externalconnectors-schema-get.md
> -## Optional query parameters
Added the following:
"## Optional query parameters

This method does not support optional query parameters to customize the response."

2021-12-01 18:37 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +Adding a semantic label can affect experiences like `Working Set`, `Relevance`, and `Project Cortex`.
Updated as recommended.

2021-12-01 18:43 UTC, mecampos commented on concepts/connecting-external-content-manage-schema.md
> +* Building common knowledge graphs (for example, Cortex, Suggestions, and QF)
Updated as recommended

2021-12-01 18:46 UTC, opbld33 commented
Docs Build status updates of commit _[f8348b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8348b2e3f756cec58b72f5c7607c7859ce88a05)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112011844416425-13793%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T18%3A46%3A20Z&sr=b&sp=r&sig=F78JHpxKcNwiWluPVEI2EsFKX8qlIiWbQEmtEPodeVc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 19:06 UTC, Arvind-Ravi commented
@mecampos - Thanks so much for getting the changes in. @Lauragra - Do take a look and let us know if this is 'ready to merge'. Thanks!

2021-12-02 04:01 UTC, opbld34 commented
Docs Build status updates of commit _[c4f5f84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4f5f8408f5fe6d29c401427e30cdaa78af73ba6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112020359242985-13793%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T04%3A01%3A03Z&sr=b&sp=r&sig=g5h4owTeLFuV6HwrOsp%2BOCRnDz30ygzo%2BW0E9RK5JmM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 04:02 UTC, Lauragra approved these changes

2021-12-02 04:03 UTC, opbld32 commented
Docs Build status updates of commit _[7e13ed8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e13ed8d585621412f98bc91f18ccfa25f16fba9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112020400234793-13793%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T04%3A03%3A02Z&sr=b&sp=r&sig=%2FBTBmS7Rvimm%2FsHOFmx4nGlxCXG%2FSx9zDKVidHhim4M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 04:05 UTC, opbld32 commented
Docs Build status updates of commit _[dd96e4e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd96e4e8b0b2c4596d3123b720a3884cf3483d72)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-externalconnection-post-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-schema-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/api/externalconnectors-schema-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-update?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/resources/externalconnectors-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-post-schema?view=graph-rest-beta&branch=pr-en-us-13793) (graph-rest-beta) |
[api-reference/v1.0/api/externalconnectors-schema-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[api-reference/v1.0/api/externalconnectors-schema-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/api-reference/v1.0/api/externalconnectors-schema-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-schema-get?view=graph-rest-1.0&branch=pr-en-us-13793) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |
[concepts/connecting-external-content-manage-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/connecting-external-content-manage-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |
[concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/images/connectors-images/connecting-external-content-manage-items-schema-1.svg) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-schemaapi/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-manage-schema?branch=pr-en-us-13793) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112020402253961-13793%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T04%3A05%3A01Z&sr=b&sp=r&sig=DIcmzhukQxLHU4HCLXP3paufX3knD%2FyIyYk5RTCHEh4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 04:09 UTC, merged