XTAP API doc set creation
microsoftgraph/microsoft-graph-docs pull request #13821
Opened 2021-08-12 19:00 UTC by jkdouglas

2021-08-12 19:01 UTC, opbld31 commented
Docs Build status updates of commit _[028ae94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/028ae94bf4430519e5a669fa99f728357f8b5de8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-create?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-55e2af80923e872d2a175485a546b10f-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-b490441742336efd2e9295d177be4cff-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-1a96638e9b33ff1097fea4972a9aa228-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicy-list-default.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-default.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-default?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-94f514cdb650aade206f370edb720f80-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-3babbb5c47a41c3883ed4126d552b04b-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-8917a3b057dda2db00208e288a415a32-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicy-post-default.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-default.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-default?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-71e6bde1ab598d9732857461f36675ac-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-88a39a0f4704e89453ff4579be488689-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-f8cb92ee257747905280653c25e28be5-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-create?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-a540741430a310f5a28a58605133174b-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-7918b789d001c942fa8589bdddec4671-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-ebf43e3cc7f5c361f86293826152ae6d-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-list?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-f59ec43b3388c95149291b241dde9fd4-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-19b4fd2d1b2e9727fe8f18898bceedc0-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-create?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-c393544129e9a7985d2d1699a1f6df5a-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-947f864668b53baef315c5a254deec15-d05f4812)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccess [...]

2021-08-19 19:50 UTC, opbld33 commented
Docs Build status updates of commit _[cb259cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb259cf68ec3437be06cff6fc9be05b327871704)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-create?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-55e2af80923e872d2a175485a546b10f-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-b490441742336efd2e9295d177be4cff-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-1a96638e9b33ff1097fea4972a9aa228-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicy-list-default.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-default.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-default?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-94f514cdb650aade206f370edb720f80-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-3babbb5c47a41c3883ed4126d552b04b-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-8917a3b057dda2db00208e288a415a32-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicy-post-default.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-default.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-default?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-71e6bde1ab598d9732857461f36675ac-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-88a39a0f4704e89453ff4579be488689-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-f8cb92ee257747905280653c25e28be5-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-create?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-a540741430a310f5a28a58605133174b-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-7918b789d001c942fa8589bdddec4671-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-ebf43e3cc7f5c361f86293826152ae6d-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-list?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-f59ec43b3388c95149291b241dde9fd4-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-19b4fd2d1b2e9727fe8f18898bceedc0-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-create?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-c393544129e9a7985d2d1699a1f6df5a-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-947f864668b53baef315c5a254deec15-4e5065d6)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccess [...]

2021-08-23 23:53 UTC, opbld30 commented
Docs Build status updates of commit _[60fc58d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60fc58d96424f5b5ce25cb5a25c7fac742cd0d3b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-create?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-55e2af80923e872d2a175485a546b10f-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-b490441742336efd2e9295d177be4cff-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicy-list-default.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-default.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-default?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-94f514cdb650aade206f370edb720f80-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-8917a3b057dda2db00208e288a415a32-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicy-post-default.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-default.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-default?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-71e6bde1ab598d9732857461f36675ac-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-88a39a0f4704e89453ff4579be488689-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-create?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-a540741430a310f5a28a58605133174b-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-7918b789d001c942fa8589bdddec4671-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-ebf43e3cc7f5c361f86293826152ae6d-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-list?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-f59ec43b3388c95149291b241dde9fd4-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-19b4fd2d1b2e9727fe8f18898bceedc0-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-create?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-c393544129e9a7985d2d1699a1f6df5a-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-947f864668b53baef315c5a254deec15-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-list?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-40cb55cd1b36d070dc1becf228f9e51c-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-efb114500db821d325f79dc8722fbe6a-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-create?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-6f42b92f626a7069d8cdb3a6d7c3cba2-95b4b6a7)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsof [...]

2021-08-24 00:10 UTC, opbld33 commented
Docs Build status updates of commit _[8b06d17](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b06d17d2a1e6c3b11c74794a1bf347e62b9031f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-create?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-55e2af80923e872d2a175485a546b10f-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-b490441742336efd2e9295d177be4cff-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicy-list-default.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-default.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-default?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-94f514cdb650aade206f370edb720f80-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-8917a3b057dda2db00208e288a415a32-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicy-post-default.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-default.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-default?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-71e6bde1ab598d9732857461f36675ac-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-88a39a0f4704e89453ff4579be488689-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-create?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-a540741430a310f5a28a58605133174b-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-7918b789d001c942fa8589bdddec4671-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-ebf43e3cc7f5c361f86293826152ae6d-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-list?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-f59ec43b3388c95149291b241dde9fd4-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationbase-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-19b4fd2d1b2e9727fe8f18898bceedc0-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-create?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-c393544129e9a7985d2d1699a1f6df5a-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-947f864668b53baef315c5a254deec15-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-list?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-40cb55cd1b36d070dc1becf228f9e51c-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-efb114500db821d325f79dc8722fbe6a-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-create?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-6f42b92f626a7069d8cdb3a6d7c3cba2-a588d5b1)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list.md](https://github.com/microsoftgraph/microsoft- [...]

2021-08-24 15:56 UTC, opbld33 commented
Docs Build status updates of commit _[46bd4e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46bd4e81d8fa108f28e9fe68aa934ab6a9d1238e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-88a39a0f4704e89453ff4579be488689-65b08d90)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-efb114500db821d325f79dc8722fbe6a-65b08d90)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-create?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-6f42b92f626a7069d8cdb3a6d7c3cba2-65b08d90)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-list?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-62d88418542a2d2139a09b10eb583d75-65b08d90)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ [...]

2021-08-24 16:00 UTC, opbld33 commented
Docs Build status updates of commit _[d53c480](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d53c4804c9b2777327a616895e4a82aacef8a168)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-efb114500db821d325f79dc8722fbe6a-16fbea25)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/ [...]

2021-08-24 16:05 UTC, opbld34 commented
Docs Build status updates of commit _[596fb8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/596fb8e8581b69cf2be517ecaae0535c6b0ecbcd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-efb114500db821d325f79dc8722fbe6a-d5e29c34)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/ [...]

2021-08-24 16:08 UTC, opbld30 commented
Docs Build status updates of commit _[695ea5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/695ea5caf36209775f26f3d69ab2f2aa83ce8fc7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/concepts/permissions-refe [...]

2021-08-24 16:21 UTC, opbld33 commented
Docs Build status updates of commit _[2126a91](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2126a91439d540c32d7fa44e07656fbf485409b2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/concepts/permissions-refe [...]

2021-08-24 16:43 UTC, opbld31 commented
Docs Build status updates of commit _[b4ddb4d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4ddb4d9216bbd9f3d95ca607e472606c181add0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/concepts/permissions-refe [...]

2021-08-24 16:52 UTC, opbld34 commented
Docs Build status updates of commit _[22ac72a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22ac72a8c41f72f5da8ad2bbf8571815358db624)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/concepts/permissions-refe [...]

2021-08-24 16:58 UTC, opbld33 commented
Docs Build status updates of commit _[8c934eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c934eb6c34f634d4e33de6ca495a80086cd79a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/concepts/permissions-refe [...]

2021-08-24 17:11 UTC, opbld32 commented
Docs Build status updates of commit _[b7af248](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b7af248062263e81ff20d2b3c7a8540a3d54d6ed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/concepts/permissions-refe [...]

2021-08-24 17:40 UTC, opbld30 commented
Docs Build status updates of commit _[c299e82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c299e8251b4243932e8dda9059de02b65b8c9fd8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/re [...]

2021-08-24 17:46 UTC, opbld31 commented
Docs Build status updates of commit _[e4a9596](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4a9596c91a824f34e82ef8ce36829ec2b1bc733)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/re [...]

2021-08-24 18:24 UTC, opbld31 commented
Docs Build status updates of commit _[e1d740d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1d740ddd7235a2aac9eb25835efbfe07b589cc3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/re [...]

2021-08-24 23:01 UTC, opbld30 commented
Docs Build status updates of commit _[fcad5ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fcad5ca40a8a9acdcc36a6f802d46212ee2447c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/re [...]

2021-08-25 14:22 UTC, opbld33 commented
Docs Build status updates of commit _[82529ba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82529bae882e82a10d797a5fb0ee0a88fc888fc5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/re [...]

2021-08-31 21:34 UTC, opbld31 commented
Docs Build status updates of commit _[f13b2fb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f13b2fbb2e6abb196faa4a727d88afd11ce00475)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9ebc8a58)

<a id="9ebc8a58"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108312133569713-13821%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=R7xDMUmqjEFXKgEL8clnfdQ5aMVRxng%2FuIpeHRGvgtE%3D&st=2021-08-31T21%3A29%3A18Z&se=2021-10-01T21%3A34%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-07 20:26 UTC, opbld30 commented
Docs Build status updates of commit _[7f11d5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f11d5d18bc259e77b283c50b5720cac54ebe83b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cdc980cf)

<a id="cdc980cf"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109072026188107-13821%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=zyOSLa%2BY8hoYL5qeQqrP%2FCkgnoncdENih0GTjXxJXIk%3D&st=2021-09-07T20%3A21%3A31Z&se=2021-10-08T20%3A26%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-07 20:51 UTC, opbld32 commented
Docs Build status updates of commit _[dfefa59](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dfefa59763c2eac2041960c8b2f8962ed24683e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-e72fa835)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft- [...]

2021-09-09 01:27 UTC, opbld34 commented
Docs Build status updates of commit _[a4569eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a4569eb62a74d64369faa9107edba70b4699ca9b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-4b3f3f5b)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft- [...]

2021-09-09 01:31 UTC, opbld33 commented
Docs Build status updates of commit _[48c9caa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/48c9caa7bc63f603a91a09f2fe0ffe47ee96ef84)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-0ae1a93e)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft- [...]

2021-09-09 01:36 UTC, opbld34 commented
Docs Build status updates of commit _[1d7b534](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d7b534360cc3d2117d939796f3f5ecf08e2293a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-867d7091)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft- [...]

2021-09-09 10:42 UTC, FaithOmbongi requested changes
**General suggestions:**
- Document the **crossTenantAccessPolicy** relationship in [policyRoot](https://docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta)
- **GLOBAL:** Update all your ms.prod values to **identity-and-sign-in**
- **GLOBAL:** ms.localizationpriority - the values may be case-sensitive on the loc repo. Kindly use the lowercase value **medium**.
- **crossTenantAccessPolicy's methods**
    - I've left notes about the inconsistencies I see when I test out the GET and UPDATE methods. If I'm missing something, let's get together for you to guide me through both methods so that I'm able to replicate what we are putting down in the documentation.

**Proposal for an overview topic:**
- Let's have an overview topic to discuss the cross tenant access feature, its building blocks (policy, default settings, partner settings), how they intersect & relate, link to the Azure docs in the See also section etc. See an example in the [App authentication methods overview topic](https://docs.microsoft.com/en-us/graph/api/resources/applicationauthenticationmethodpolicy?view=graph-rest-beta).

**May or may not be correct**

It's possible that I'm wrong in the following suggestions because I'm referring to the CSDL in which this API is still hidden. Some of this might have changed in the CSDL PR for this release
- Missing tenantRelationshipAccessPolicyBase resource?
- Missing multiTenantCollaborationAccessPolicy resource?

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md
> +If successful, this method returns a `200 OK` response code and an updated [crossTenantAccessPolicyConfigurationDefault](../resources/crosstenantaccesspolicyconfigurationdefault.md) object in the res
Kindly verify the response code. Your example response shows it's a `204 No Content` with no response object.

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md
> +HTTP/1.1 204 No Content
Let this align with the response code declared in the Response H3 section.

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md
> +description: "Reset any changes made to the default configuration in a cross tenant access policy back to the system default."
```suggestion
description: "Reset any changes made to the default configuration in a cross-tenant access policy back to the system default."
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md
> +Reset any changes made to the default configuration in a cross tenant access policy back to the system default.
```suggestion
Reset any changes made to the default configuration in a cross-tenant access policy back to the system default.
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md
> +If successful, this action returns a `200 OK` response code and an empty response. To confirm the reset system defaults, run [Get crossTenantAccessPolicyConfigurationDefault](../api/crosstenantaccess
```suggestion
If successful, this action returns a `200 OK` response code and an empty response. To confirm the reset system defaults, run [Get crossTenantAccessPolicyConfigurationDefault](../api/crosstenantaccesspolicyconfigurationdefault-get.md) and confirm that `isSystemDefault` is set to `true`.
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md
> +description: "Read the properties and relationships of a partner specific configuration."
```suggestion
description: "Read the properties and relationships of a partner-specific configuration."
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md
> +Read the properties and relationships of a [partner specific](../resources/crosstenantaccesspolicyconfigurationpartner.md) configuration.
```suggestion
Read the properties and relationships of a [partner-specific](../resources/crosstenantaccesspolicyconfigurationpartner.md) configuration.
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md
> +|[Delete crossTenantAccessPolicyConfigurationPartner](../api/crosstenantaccesspolicyconfigurationpartner-delete.md)|None|Delete the partner specific configuration.|
```suggestion
| [List partners](../api/crosstenantaccesspolicy-list-partners.md) | [crossTenantAccessPolicyConfigurationPartner](../resources/crosstenantaccesspolicyconfigurationpartner.md) collection | Get a list of all partner-specific configurations. |
| [Create crossTenantAccessPolicyConfigurationPartner](../api/crosstenantaccesspolicy-post-partners.md) | [crossTenantAccessPolicyConfigurationPartner](../resources/crosstenantaccesspolicyconfigurationpartner.md) | Create a new partner-specific configuration. |
| [Get crossTenantAccessPolicyConfigurationPartner](../api/crosstenantaccesspolicyconfigurationpartner-get.md) | [crossTenantAccessPolicyConfigurationPartner](../resources/crosstenantaccesspolicyconfigurationpartner.md) | Read the partner-specific configuration settings. |
| [Update crossTenantAccessPolicyConfigurationPartner](../api/crosstenantaccesspolicyconfigurationpartner-update.md) | [crossTenantAccessPolicyConfigurationPartner](../resources/crosstenantaccesspolicyconfigurationpartner.md) | Update the properties of a partner-specific configuration. |
| [Delete crossTenantAccessPolicyConfigurationPartner](../api/crosstenantaccesspolicyconfigurationpartner-delete.md) | None | Delete the partner-specific configuration. |
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicy-list-partners.md
> +description: "Get a list of all partner configurations within a cross tenant access policy."
```suggestion
description: "Get a list of all partner configurations within a cross-tenant access policy."
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicy-list-partners.md
> +Get a list of all partner configurations within a cross tenant access policy.
```suggestion
Get a list of all partner configurations within a cross-tenant access policy.
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicy-post-partners.md
> +description: "Create a new partner configuration in a cross tenant access policy."
```suggestion
description: "Create a new partner configuration in a cross-tenant access policy."
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicy-post-partners.md
> +Create a new partner configuration in a cross tenant access policy.
```suggestion
Create a new partner configuration in a cross-tenant access policy.
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicy-post-partners.md
> +|inboundTrust|[crossTenantAccessPolicyInboundTrust](../resources/crosstenantaccesspolicyinboundtrust.md)|Determines the partner specific configuration for trusting other conditional access claims fro
Suggested minor fixes but correct me if I'm wrong—nullable properties aren't Required, are they? This section should list only Required properties.
```suggestion
| tenantId | String | The tenant identifier for the partner Azure Active Directory (Azure AD) organization. |
| b2bCollaborationInbound | [crossTenantAccessPolicyB2BSetting](../resources/crosstenantaccesspolicyb2bsetting.md) | Defines your partner-specific configuration for users from other organizations accessing your resources via Azure AD B2B collaboration. |
| b2bCollaborationOutbound | [crossTenantAccessPolicyB2BSetting](../resources/crosstenantaccesspolicyb2bsetting.md) | Defines your partner-specific configuration for users in your organization going outbound to access resources in another organization via Azure AD B2B collaboration. |
| b2bDirectConnectInbound | [crossTenantAccessPolicyB2BSetting](../resources/crosstenantaccesspolicyb2bsetting.md) | Defines your partner specific configuration for users from other organizations accessing your resources via Azure AD B2B Direct Connect. |
| b2bDirectConnectOutbound | [crossTenantAccessPolicyB2BSetting](../resources/crosstenantaccesspolicyb2bsetting.md) | Defines your partner-specific configuration for users in your organization going outbound to access resources in another organization via Azure AD B2B Direct Connect. |
| inboundTrust | [crossTenantAccessPolicyInboundTrust](../resources/crosstenantaccesspolicyinboundtrust.md) | Determines the partner specific configuration for trusting other conditional access claims from external Azure AD organizations. |
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicy-post-partners.md
> +>**Note:** The response object shown here might be shortened for readability.
```suggestion
The following is an example of the response.
>**Note:** The response object shown here might be shortened for readability.
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md
> +description: "Deletes a partner configuration in a cross tenant access policy."
```suggestion
description: "Deletes a partner-specific configuration in a cross-tenant access policy."
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md
> +Deletes a [partner configuration](../resources/crosstenantaccesspolicyconfigurationpartner.md) in a cross tenant access policy.
```suggestion
Deletes a [partner-specific configuration](../resources/crosstenantaccesspolicyconfigurationpartner.md) in a cross-tenant access policy.
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
> +description: "Update the properties of a partner specific configuration."
```suggestion
description: "Update the properties of a partner-specific configuration."
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
> +Update the properties of a [partner specific](../resources/crosstenantaccesspolicyconfigurationpartner.md) configuration.
```suggestion
Update the properties of a [partner-specific](../resources/crosstenantaccesspolicyconfigurationpartner.md) configuration.
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicy-update.md
> +The following table shows the properties that are required when you update the [crossTenantAccessPolicy](../resources/crosstenantaccesspolicy.md).
Text to resolve stub generator output
```suggestion
In the request body, supply *only* the values for properties that should be updated. Existing properties that are not included in the request body will maintain their previous values or be recalculated based on changes to other property values.

The following table specifies the properties that can be updated.
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
> +The following table shows the properties that are required when you update the [crossTenantAccessPolicyConfigurationPartner](../resources/crosstenantaccesspolicyconfigurationpartner.md).
Text to resolve stub generator output
```suggestion
In the request body, supply *only* the values for properties that should be updated. Existing properties that are not included in the request body will maintain their previous values or be recalculated based on changes to other property values.

The following table specifies the properties that can be updated.
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
> +|b2bDirectConnectOutbound|[crossTenantAccessPolicyB2BSetting](../resources/crosstenantaccesspolicyb2bsetting.md)|Defines your partner specific configuration for users in your organization going outbo
```suggestion
| inboundTrust | [crossTenantAccessPolicyInboundTrust](../resources/crosstenantaccesspolicyinboundtrust.md) | Determines the partner-specific configuration for trusting other conditional access claims from external Azure Active Directory (Azure AD) organizations. |
| b2bCollaborationInbound | [crossTenantAccessPolicyB2BSetting](../resources/crosstenantaccesspolicyb2bsetting.md) | Defines your partner-specific configuration for users from other organizations accessing your resources via Azure AD B2B collaboration. |
| b2bCollaborationOutbound | [crossTenantAccessPolicyB2BSetting](../resources/crosstenantaccesspolicyb2bsetting.md) | Defines your partner-specific configuration for users in your organization going outbound to access resources in another organization via Azure AD B2B collaboration. |
| b2bDirectConnectInbound | [crossTenantAccessPolicyB2BSetting](../resources/crosstenantaccesspolicyb2bsetting.md) | Defines your partner-specific configuration for users from other organizations accessing your resources via Azure AD B2B Direct Connect. |
| b2bDirectConnectOutbound | [crossTenantAccessPolicyB2BSetting](../resources/crosstenantaccesspolicyb2bsetting.md) | Defines your partner-specific configuration for users in your organization going outbound to access resources in another organization via Azure AD B2B Direct Connect. |
```

2021-09-09 10:42 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
> +If successful, this method returns a `200 OK` response code and an updated [crossTenantAccessPolicyConfigurationPartner](../resources/crosstenantaccesspolicyconfigurationpartner.md) object in the res
Mismatch in this statement vs the example response: 200 OK vs 204 No Content

2021-09-09 10:42 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        },
```suggestion
       {
         "Id": "762ccb17-76e5-41b3-b0e7-e37591f954a1",
         "ApiChange": "Resource",
         "ChangedApiName": "crossTenantAccessPolicyConfigurationDefault",
         "ChangeType": "Addition",
         "Description": "Added the [crossTenantAccessPolicyConfigurationDefault](https://docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta) resource.",
         "Target": "crossTenantAccessPolicyConfigurationDefault"
        },
        {
          "Id": "762ccb17-76e5-41b3-b0e7-e37591f954a1",
          "ApiChange": "Resource",
          "ChangedApiName": "crossTenantAccessPolicyConfigurationPartner",
          "ChangeType": "Addition",
          "Description": "Added the [crossTenantAccessPolicyConfigurationPartner](https://docs.microsoft.com/en-us/graph/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta) resource.",
          "Target": "crossTenantAccessPolicyConfigurationPartner"
        },
        {
          "Id": "762ccb17-76e5-41b3-b0e7-e37591f954a1",
          "ApiChange": "Resource",
          "ChangedApiName": "crossTenantAccessPolicyInboundTrust",
          "ChangeType": "Addition",
          "Description": "Added the [crossTenantAccessPolicyInboundTrust](https://docs.microsoft.com/en-us/graph/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta) resource.",
          "Target": "crossTenantAccessPolicyInboundTrust"
        },
        {
          "Id": "762ccb17-76e5-41b3-b0e7-e37591f954a1",
          "ApiChange": "Resource",
          "ChangedApiName": "crossTenantAccessPolicyConfigurationBase",
          "ChangeType": "Addition",
          "Description": "Added the [crossTenantAccessPolicyConfigurationBase](https://docs.microsoft.com/en-us/graph/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta) resource.",
          "Target": "crossTenantAccessPolicyConfigurationBase"
        },
```

2021-09-09 10:42 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        },
```suggestion
        {
          "Id": "762ccb17-76e5-41b3-b0e7-e37591f954a1",
          "ApiChange": "Resource",
          "ChangedApiName": "crossTenantAccessPolicyB2BSetting",
          "ChangeType": "Addition",
          "Description": "Added the [crossTenantAccessPolicyB2BSetting](https://docs.microsoft.com/en-us/graph/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta) resource.",
          "Target": "crossTenantAccessPolicyB2BSetting"
        },
        {
          "Id": "762ccb17-76e5-41b3-b0e7-e37591f954a1",
          "ApiChange": "Resource",
          "ChangedApiName": "crossTenantAccessPolicyTarget",
          "ChangeType": "Addition",
          "Description": "Added the [crossTenantAccessPolicyTarget](https://docs.microsoft.com/en-us/graph/resources/crosstenantaccesspolicytarget?view=graph-rest-beta) resource.",
          "Target": "crossTenantAccessPolicyTarget"
        },
        {
          "Id": "762ccb17-76e5-41b3-b0e7-e37591f954a1",
          "ApiChange": "Resource",
          "ChangedApiName": "crossTenantAccessPolicyTargetConfiguration",
          "ChangeType": "Addition",
          "Description": "Added the [crossTenantAccessPolicyTargetConfiguration](https://docs.microsoft.com/en-us/graph/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta) resource.",
          "Target": "crossTenantAccessPolicyTargetConfiguration"
        },
```

2021-09-09 10:42 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        }
```suggestion
        {
          "Id": "0a673359-4f88-11nbe-ae53-ed740c456b69",
          "ApiChange": "Enum type",
          "ChangedApiName": "crossTenantAccessPolicyTargetConfigurationAccessType",
          "ChangeType": "Addition",
          "Description": "Added the **crossTenantAccessPolicyTargetConfigurationType** enumeration.",
          "Target": "crossTenantAccessPolicyTargetConfigurationAccessType"
        },
        {
          "Id": "0a673359-4f88-11nbe-ae53-ed740c456b69",
          "ApiChange": "Enum type",
          "ChangedApiName": "crossTenantAccessPolicyTargetType",
          "ChangeType": "Addition",
          "Description": "Added the **crossTenantAccessPolicyTargetType** enumeration.",
          "Target": "crossTenantAccessPolicyTargetType"
        }
```

2021-09-09 10:42 UTC, FaithOmbongi commented on concepts/permissions-reference.md
> +| _Policy.ReadWrite.CrossTenantAccessPolicy_ | Read and write your organization's cross tenant access policy | Allows the app to read and write your organization's cross tenant access policy on behal
```suggestion
| _Policy.ReadWrite.CrossTenantAccessPolicy_ | Read and write your organization's cross-tenant access policy | Allows the app to read and write your organization's cross-tenant access policy on behalf of the signed-in user. | Yes | No |
```

2021-09-09 10:42 UTC, FaithOmbongi commented on concepts/permissions-reference.md
> +| _Policy.ReadWrite.CrossTenantAccessPolicy_ | Read and write your organization's cross tenant access policy | Allows the app to read and write your organization's cross tenant access policy on behal
```suggestion
| _Policy.ReadWrite.CrossTenantAccessPolicy_ | Read and write your organization's cross-tenant access policy | Allows the app to read and write your organization's cross-tenant access policy on behalf of the signed-in user. | Yes | No |
```

2021-09-09 15:33 UTC, opbld32 commented
Docs Build status updates of commit _[54c4eb3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/54c4eb3d11b268e1d86e35f896f6bcb6292bab6e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2c134ab15a8c41de2834c32f1881c6b3-34afb63a)
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-34afb63a)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/enums [...]

2021-09-13 22:38 UTC, opbld33 commented
Docs Build status updates of commit _[b38c3a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b38c3a95a3d7f743ccc684f8e651abf8ba191f3e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2c134ab15a8c41de2834c32f1881c6b3-4950a540)
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-4950a540)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/enums [...]

2021-09-13 23:45 UTC, opbld31 commented
Docs Build status updates of commit _[eb38a6a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb38a6a5c92711b4e3f541397ec1a53f382ca036)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-e574ee39)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft- [...]

2021-09-15 15:53 UTC, opbld32 commented
Docs Build status updates of commit _[fe968c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe968c7821a903646ba3793e4375d5c2977ee86a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fc0ea6c7)

<a id="fc0ea6c7"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109151553211890-13821%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T15%3A53%3A45Z&sr=b&sp=r&sig=LfYW0ywOTr4UJkYWRZguksJAJP563OND1uRHjvP2zsI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 15:58 UTC, opbld32 commented
Docs Build status updates of commit _[c674167](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c6741679dec06183659f1600320c3a4f71ef8ad6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-5febdfe1)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft- [...]

2021-09-15 22:41 UTC, opbld33 commented
Docs Build status updates of commit _[113bc7c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/113bc7c9e0cef1f2b407b74b0cc36138f2c4d430)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-831b2a92)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft- [...]

2021-09-28 21:16 UTC, opbld32 commented
Docs Build status updates of commit _[799f64e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/799f64ebfdb0f13ab1ecc9db122933dbb521452a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-aa9ac3a6)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytargetconfiguration?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft- [...]

2021-10-07 17:28 UTC, opbld33 commented
Docs Build status updates of commit _[1ead059](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ead059030e96943439a80c3b671a50bd6be3a0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-f854f433)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13821) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-f854f433)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources [...]

2021-12-07 01:03 UTC, opbld32 commented
Docs Build status updates of commit _[4dc8f32](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4dc8f32040b54755e0bf2913e82a7049b8d5ad95)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-b30ad213)
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2c134ab15a8c41de2834c32f1881c6b3-b30ad213)
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-b30ad213)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13821) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-b30ad213)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com [...]

2021-12-07 01:09 UTC, opbld33 commented
Docs Build status updates of commit _[a4baf77](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a4baf777f3fb85d483c881077d8b2125dd82f5bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-2ad6887a)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13821) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-2ad6887a)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantacce [...]

2021-12-08 23:23 UTC, opbld30 commented
Docs Build status updates of commit _[97aee51](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97aee518d4cb4a70c19dfe7bb53bc4a905c19207)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-5a0cf3cb)
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-5a0cf3cb)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13821) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-5a0cf3cb)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check [...]

2021-12-08 23:30 UTC, opbld32 commented
Docs Build status updates of commit _[310091e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/310091ea255663e51702f3e6847bb0b2bac9b7b3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-65d2608e)
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-65d2608e)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13821) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-65d2608e)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check [...]

2021-12-09 23:42 UTC, opbld33 commented
Docs Build status updates of commit _[585928a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/585928a537dcce2bc6f4087a68557c1cfd0cf56a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a31015e3)
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-a31015e3)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13821) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-a31015e3)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check [...]

2021-12-14 14:31 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +Granular controls let you determine the people, groups, and apps, both in your organization and in external organizations, that can participate in Azure AD B2B and Azure AD B2B Direct Connect collabo
Adding a minor background that led to the development/implementation of cross-tenant access settings
```suggestion
In traditional Azure AD B2B collaboration, any invited user from an organization could use their identity to access resources in external organizations. Administrators didn't have control over the user identities in their tenant that are allowed to sign in to external organizations. These limited controls made it difficult to prevent identities from your organization from being used in unauthorized ways. 

**Cross-tenant access settings** let you control and manage collaboration between users in your organization and other organizations. This collaboration is mainly through the Azure Active Directory (Azure AD) B2B and Azure AD B2B Direct Connect (future) features. The control can be on either **outbound access** (how your users collaborate with other organizations), **inbound access** (how other organizations collaborate with you), or both.

Granular controls let you determine the users, groups, and apps, both in your organization and in external organizations, that can participate in Azure AD B2B and Azure AD B2B Direct Connect collaboration. These controls are implemented through:
```

2021-12-14 14:34 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +> **Note:** By configuring B2B direct connect outbound settings, you agree to allow external organizations that you have enabled outbound settings with to access limited contact data about your users
Indicating the default settings are updatable. Changing the note to an important note because it affects data privacy.
```suggestion
+ **Default cross-tenant access settings** which set the baseline inbound and outbound access settings.
    + In Azure AD B2B collaboration, both access settings are enabled by default. This means all your users can be invited to external organizations, and all your users can invite external users.
    + In Azure AD B2B Direct Connect, both access settings are disabled by default.
    + The service default settings may be updated.
+ **Partner-specific access settings** which allow you to configure customized settings for individual organizations. For the configured organizations, this configuration takes precedence over the default settings. Therefore, while Azure AD B2B and Azure AD B2B Direct Connect might be disabled across your organization by default, you can enable these features for a specific external organization.

> [!IMPORTANT]
> 
> By configuring B2B direct connect outbound settings, you agree to allow external organizations that you have enabled outbound settings with to access limited contact data about your users. Microsoft shares this data with those organizations to help them send a request to connect with your users. Data collected by external organizations, including limited contact data, is subject to the privacy policies and practices of those organizations.
```

2021-12-14 14:38 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +Even though you have added a partner to your cross-tenant access settings, some of your default settings will still apply. For example, if you only configure `b2bCollaborationInbound` for a partner i
- Suggested minor changes
- Properties are formatted in bold. Values in code font.

```suggestion
## Default cross-tenant access settings

Default cross-tenant access settings determine your stance for inbound and outbound collaboration with all other Azure AD organizations. Any external collaboration with an organization not listed explicitly in your cross-tenant access settings will inherit these default settings. Default settings are defined using the [crossTenantAccessPolicyConfigurationDefault](../resources/crosstenantaccesspolicyconfigurationdefault.md) resource type.

By default, Azure AD assigns all Azure AD tenants a service default configuration for cross-tenant access settings. You can override these service defaults with your own configuration to suit your organization. You can confirm whether you're using the service default settings or have modified the default settings by looking at the **isServiceDefault** property returned when you query the default endpoint.

## Partner cross-tenant access settings

Partner-specific cross-tenant access settings determine your stance for inbound and outbound collaboration with a specific Azure AD organization. Any collaboration with this organization will inherit these partner-specific settings. Partner settings are defined using the [crossTenantAccessPolicyConfigurationPartner](../resources/crosstenantaccesspolicyconfigurationpartner.md) resource type.

Even though you have added a partner to your cross-tenant access settings, some of your default settings will still apply. For example, if you configure only **b2bCollaborationInbound** for a partner in your cross-tenant access settings, all other settings for that partner configuration will be inherited from the default cross-tenant access settings. When querying the partner endpoint, any property on the partner object that is `null` means that for that property, it's inheriting settings from the default policy.
```

2021-12-14 14:39 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +The cross-tenant access settings API can be used to set up multiple configurations for allowing or blocking access to and from your organization. The following table highlights scenarios, shows an ex
Translating the properties b2bSettings is a placeholder for
```suggestion
The cross-tenant access settings API can be used to set up multiple configurations for allowing or blocking access to and from your organization. The following table highlights scenarios, shows an example of the API response, and what the interpretation should be of that response. **b2bSetting** is used as a placeholder for any B2B inbound (**b2bCollaborationInbound** or **b2bDirectConnectInbound**) or outbound (**b2bCollaborationOutbound** or **b2bDirectConnectOutbound**) configuration.
```

2021-12-14 14:40 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +        "accessType": " allowed",
```suggestion
<td> Allow users in group 'g1' to access any app </td>
<td>

``` json
"b2bSetting": {
    "usersAndGroups": {
        "accessType": "allowed",
```

2021-12-14 14:41 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +<td> Users of group 'g1' can access any app. All other users not in group 'g1' are blocked. </td>
```suggestion
<td> Users in group 'g1' can access any app. All other users not in group 'g1' are blocked. </td>
```

2021-12-14 14:41 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +<td> Allow users of group 'g1' and block access to application 'a1' </td>
```suggestion
<td> Allow users in group 'g1' and block access to application 'a1' </td>
```

2021-12-14 14:42 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +<td> Block users of group 'g1' and allow access to application 'a1' only </td>
```suggestion
<td> Users in group 'g1' can't access any application. Other users not in group 'g1' have access to all applications. </td>
</tr>
<tr>
<td> Block users in group 'g1' and allow access to application 'a1' only </td>
```

2021-12-14 14:43 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +<td> Allow users of group 'g1' and limit access to only application 'a1' </td>
```suggestion
<td> Users in group 'g1' can't access any application. Any user not in group 'g1' can only access application 'a1'. </td>
</tr>
<tr>
<td> Allow users in group 'g1' to access to only application 'a1' </td>
```

2021-12-14 14:45 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +<td> Users of group 'g1' are blocked for application 'a1' only. All users, including users in group 'g1' are able to access any other application. </td>
```suggestion
<td> Users in group 'g1' are allowed access to application 'a1' only. All users, including users in group 'g1' are able to access any other application. </td>
```

2021-12-14 14:46 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +<td> Allow users of group 'g1' and limit access to only application 'a1' </td>
```suggestion
<td> Allow users of group 'g1' access to only application 'a1' </td>
```

2021-12-14 14:46 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +<td> Users in group 'g1' are only allowed to access application 'a1'. All users, including users in group 'g1' are blocked from accessing any other application. </td>
```suggestion
<td> Users in group 'g1' are only allowed to access application 'a1'. All users, including users in group 'g1', are blocked from accessing any other application. </td>
```

2022-01-05 16:49 UTC, jkdouglas commented on api-reference/beta/api/crosstenantaccesspolicy-get.md
> +GET https://graph.microsoft.com/beta/policies/crossTenantAccessPolicy
I left a note about the { } response if you've never modified XTAP before. Let me check on the 500 error you are seeing.

2022-01-05 16:52 UTC, jkdouglas commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md
> +}
This is the correct response when calling this action. It returns an empty body.

2022-01-05 16:56 UTC, jkdouglas commented on api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md
> +}
Hirsch will be adding TRv2 info at a later time.

2022-01-05 16:57 UTC, jkdouglas commented on api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md
> +
This will be documented at a later time by Hirsch.

2022-01-05 17:08 UTC, opbld31 commented
Docs Build status updates of commit _[308bb8f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/308bb8fa50ede6d98adc7e4cdae5f334f217fb88)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-15657ffa)
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-15657ffa)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-b [...]

2022-01-05 17:13 UTC, opbld32 commented
Docs Build status updates of commit _[13f9be1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13f9be10ef29bfc635961d0660926c1fd9d40817)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-834e8e08)

<a id="834e8e08"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201051712066150-13821%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T17%3A13%3A36Z&sr=b&sp=r&sig=t7QwsWj1TLSb1InUxua79jrkcPjkSEuvnEauc%2BvMsAM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-05 17:14 UTC, opbld34 commented
Docs Build status updates of commit _[1069b82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1069b824174770966013271c909b7b9818afd127)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-94d57cb9)

<a id="94d57cb9"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201051713392707-13821%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T17%3A14%3A02Z&sr=b&sp=r&sig=i9%2Ft7eifAyP0%2FbttNHPpMxkGQckzaDpHt%2FQDT29ykyM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-05 17:21 UTC, opbld32 commented
Docs Build status updates of commit _[8ca3e81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8ca3e810d3f6e4b8943acd434aa3113e0db10f3f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-53620b36)
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-2e7c4ba09bce5fd94936a74bb009f0cf-53620b36)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-b [...]

2022-01-10 10:57 UTC, opbld33 commented
Docs Build status updates of commit _[55945c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/55945c79014ea979eda247468a30be7373c4310f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bb471569)

<a id="bb471569"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201101057176327-13821%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T10%3A57%3A44Z&sr=b&sp=r&sig=%2B%2BRVaBdHodaECcP3N7Vu05pFBZ03ZksXH0Lrf6R4%2FbA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 11:03 UTC, opbld31 commented
Docs Build status updates of commit _[025221c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/025221c89074b9a20d0fe70a6dbdb5b771d59f41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/ [...]

2022-01-10 11:13 UTC, FaithOmbongi approved these changes

2022-01-10 20:31 UTC, opbld33 commented
Docs Build status updates of commit _[729ff84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/729ff84ed698eb270a2fd7cfd02546a78d119ee7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/ [...]

2022-01-11 18:44 UTC, FaithOmbongi approved these changes
Hi @jkdouglas—added 3 suggestions following the informative "troubleshooting and common errors" learning session you held today. These aren't urgent, just something to keep in mind and can be added after the docs + API go live.

2022-01-11 18:44 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +
@jkdouglas, suggestion based on something you shared at the troubleshooting and common errors session.

Proposing that we add an H2 section here for **Trust settings in cross-tenant access settings**. This is something we didn't call out.
```suggestion
## Trust settings in cross-tenant access settings
```

2022-01-11 18:44 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +
@jkdouglas, suggestion based on a discussion at the troubleshooting and common errors session.

Proposing that we add an H2 section here for **Cross-tenant access settings vs tenant restrictions**.
```suggestion
## Cross-tenant access settings vs tenant restrictions
```

2022-01-11 18:44 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicy-update.md
> +If successful, this method returns a `200 OK` response code and an updated [crossTenantAccessPolicy](../resources/crosstenantaccesspolicy.md) object in the response body.
@jkdouglas, a suggestion based on the troubleshooting and common errors session we had.
```suggestion
If successful, this method returns a `200 OK` response code and an updated [crossTenantAccessPolicy](../resources/crosstenantaccesspolicy.md) object in the response body.

The [crossTenantAccessPolicy](../resources/crosstenantaccesspolicy.md) object size is currently limited to 25kB. This method will return a `400 Bad Request` error code if the size of the policy will exceed 25kB.
```

2022-01-12 23:51 UTC, opbld31 commented
Docs Build status updates of commit _[b4a5888](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4a5888bd2faad1458de6f374cb4e3fbd42e4ab1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/ [...]

2022-01-24 18:15 UTC, opbld34 commented
Docs Build status updates of commit _[7caad9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7caad9cecd2018dbd2dbeafc1022ae327dc76434)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2a4301db)

<a id="2a4301db"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201241809140644-13821%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T18%3A14%3A59Z&sr=b&sp=r&sig=SyO1oBxT43MNdEnk22j9y4IOKI%2Flk8SyijY%2F9iO75nE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 19:01 UTC, opbld31 commented
Docs Build status updates of commit _[033fbb8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/033fbb82e3182e3f4736f6781361f958ebeb61dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-fd1ea7ec)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-01-25 22:01 UTC, opbld32 commented
Docs Build status updates of commit _[78aef51](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78aef51bef11c184737770bb71f002babe221909)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-92af65ac)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-01-27 11:16 UTC, FaithOmbongi approved these changes
Hi @jkdouglas, re-approved with minor suggestions. Just minor changes/fixes in the updates that you recently made.

2022-01-27 11:16 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +Inbound trust settings also enable you to trust devices that are compliant, or hybrid Azure AD joined in their home directories. Devices can only be managed and compliant in their home directories. Y
```suggestion
Inbound trust settings enable you to trust the MFA external users perform in their home directories. This prevents external users from having to perform MFA both in their home directories and in your directory. With inbound trust settings, you enable a seamless authentication experience for your external users and save on the MFA costs incurred by your organization.  

Inbound trust settings also enable you to trust devices that are compliant, or hybrid Azure AD joined in their home directories. With inbound trust settings in cross-tenant access settings, you can now protect access to your apps and resources by requiring that external users use compliant, or hybrid Azure AD joined devices.
```

2022-01-27 11:16 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +Cross tenant access settings outbound controls are for controlling how **your organization's accounts** are used for accessing resources in other Azure AD organizations. Tenant Restrictions is to con
```suggestion
Cross-tenant access settings outbound controls are for controlling how **your organization's accounts** are used to access resources in other Azure AD organizations. On the other hand, tenant restrictions control how your employees use **other Azure AD organization's accounts within your networks or devices**. Critically, outbound controls work all the time because they're associated with your accounts, while tenant restrictions require additional signals to be injected into the authentication requests before the controls can be enforced. This is because tenant restrictions are scoped to networks and devices, not accounts. Learn more about [tenant restrictions](/azure/active-directory/manage-apps/tenant-restrictions).
```

2022-01-27 19:03 UTC, opbld31 commented
Docs Build status updates of commit _[cc6f5ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc6f5abdd724e19a1cd668d95625ef646efba0ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-2fe5d33b)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-01-27 23:27 UTC, opbld30 commented
Docs Build status updates of commit _[6508455](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6508455e5e6631ddc7318bb7e5cb3073f990c706)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-4262d91f)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-01-28 16:01 UTC, opbld30 commented
Docs Build status updates of commit _[7ce5f04](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ce5f04d7614a352cec97cadaa63433e41f2bbe3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-860094dc)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-01-28 16:12 UTC, opbld30 commented
Docs Build status updates of commit _[81cf726](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81cf72600c59fb3cb66f2e23b2d0bf7181601fc6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-f1c9d198)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-01-28 16:18 UTC, opbld33 commented
Docs Build status updates of commit _[da254f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da254f61001082e4c8373116431d64347a2789d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-6f372bea)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-01-28 16:20 UTC, opbld34 commented
Docs Build status updates of commit _[da254f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da254f61001082e4c8373116431d64347a2789d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-52c1e085)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-01-28 16:28 UTC, opbld34 commented
Docs Build status updates of commit _[16e69b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16e69b67d8e00717a47f2c2b7516721d4b1537d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-ad3b399b)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-01-28 16:31 UTC, opbld30 commented
Docs Build status updates of commit _[a5c89f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5c89f1c71c2fbd1d2b3e98328ac8347b675da6e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-6f2fcbbc)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-01-28 16:36 UTC, opbld34 commented
Docs Build status updates of commit _[0e34653](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e3465323fe1e9c0b0e43352d4028a404f678fb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-7d91e44f)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-01-28 16:39 UTC, opbld33 commented
Docs Build status updates of commit _[a4a3cb9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a4a3cb9775ca939ac669e7f7945b20372adb731e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-1950576a)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-01-28 16:42 UTC, opbld32 commented
Docs Build status updates of commit _[2e14359](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e1435904e9f6bf18d724a5225104d1b1f94567f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-8425b062)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-01-28 16:44 UTC, opbld33 commented
Docs Build status updates of commit _[bc83c9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc83c9c0377e6c889572e1995a583a422286cf83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-e243b54c)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-01-28 18:42 UTC, opbld33 commented
Docs Build status updates of commit _[4f2cb70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f2cb70e1006acf022f01e926ff0aafe1fe3dc2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-d495382c)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-01-31 18:13 UTC, opbld32 commented
Docs Build status updates of commit _[edae4f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/edae4f8a01f4e6d3591b3e5adb02ad5bea074f34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-e1714519)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-02-04 20:02 UTC, opbld31 commented
Docs Build status updates of commit _[3a92bb5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a92bb549ecd56046ded29008f6daffc14e79da9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-ee50971c)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-02-04 23:47 UTC, opbld34 commented
Docs Build status updates of commit _[4159750](https://github.com/microsoftgraph/microsoft-graph-docs/commits/415975095e440036981d3140a42597837544a6ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-633a623c)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-02-05 01:42 UTC, Lauragra commented on api-reference/beta/api/crosstenantaccesspolicy-update.md
> +HTTP/1.1 204 No Content
I'm confused about the response here; should this example show an updated crossTenantAccessPolicy object?

2022-02-05 01:43 UTC, opbld30 commented
Docs Build status updates of commit _[7b05d54](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b05d54a86b8c3996180c8f20ea91ac929322768)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-2cc1d531)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-02-05 01:46 UTC, opbld34 commented
Docs Build status updates of commit _[6bb65f0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6bb65f0a628df29b64fcf4391776f8618cd5585a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-ddc9e8b9)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-02-05 01:47 UTC, Lauragra commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md
> +If successful, this method returns a `204 No Content` response code and an updated [crossTenantAccessPolicyConfigurationDefault](../resources/crosstenantaccesspolicyconfigurationdefault.md) object in
Is this accurate? If a no content response, there shouldn't be a response body, as shown in the example response?

2022-02-05 01:49 UTC, Lauragra commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
> +If successful, this method returns a `204 No Content` response code and an updated [crossTenantAccessPolicyConfigurationPartner](../resources/crosstenantaccesspolicyconfigurationpartner.md) object in
Does the response include the object? Please make sure that the Response section and the response example are in alignment.

2022-02-05 01:51 UTC, opbld30 commented
Docs Build status updates of commit _[e3f2c0e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3f2c0e80f592e6000a743f54f4134f77ceef740)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-3697d50e)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-02-05 01:52 UTC, Lauragra commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +**Cross-tenant access settings** let you control and manage collaboration between users in your organization and other organizations. This collaboration is mainly through the Azure Active Directory (
Is Azure AD B2B not currently available? Generally, we avoid referencing future functionality to avoid setting customer expectations that might not be delivered.

2022-02-05 02:04 UTC, Lauragra commented on api-reference/beta/resources/crosstenantaccesspolicy.md
> +| definition (deprecated) | String | The raw JSON definition of the cross-tenant access policy. **Deprecated. Do not use.**|
How is it that we have deprecated a property on a resource that we are newly introducing?

2022-02-05 02:06 UTC, Lauragra commented on api-reference/beta/resources/crosstenantaccesspolicy.md
> +# crossTenantAccessPolicy resource type
This resource isn't found in the live metadata but the other resources this PR is introducing do appear to be live. Confirm that this resource will be publicly available?

2022-02-05 02:10 UTC, Lauragra commented on api-reference/beta/resources/tenantrelationshipaccesspolicybase.md
> +# tenantRelationshipAccessPolicyBase resource type
This resource isn't listed in the changelog, and also is not currently in the live metadata. Please verify that it has been released and if so, update the changelog accordingly.

2022-02-05 02:45 UTC, jkdouglas commented on api-reference/beta/api/crosstenantaccesspolicy-update.md
> +HTTP/1.1 204 No Content
Fixed. It is a 204 but I had a typo.

2022-02-05 02:46 UTC, opbld30 commented
Docs Build status updates of commit _[e4dd01a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4dd01a5277c358e370cc707ec6f3d02190d1e34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-cbfa5ec2)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-02-05 02:48 UTC, jkdouglas commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md
> +If successful, this method returns a `204 No Content` response code and an updated [crossTenantAccessPolicyConfigurationDefault](../resources/crosstenantaccesspolicyconfigurationdefault.md) object in
The response shows a 204 no content from what I can see. Am I missing something?

2022-02-05 02:51 UTC, opbld30 commented
Docs Build status updates of commit _[d6aea63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6aea63367b450dca9b57d0a42102a00a569c520)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-006139b2)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-02-05 02:52 UTC, jkdouglas commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
> +If successful, this method returns a `204 No Content` response code and an updated [crossTenantAccessPolicyConfigurationPartner](../resources/crosstenantaccesspolicyconfigurationpartner.md) object in
Fixed. Sorry i think I missed this from the doc generator.

2022-02-05 02:54 UTC, opbld34 commented
Docs Build status updates of commit _[753a4b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/753a4b8ac655ef4135b29f2a7a7a5360391968f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-2736ea87)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-02-05 02:54 UTC, jkdouglas commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +**Cross-tenant access settings** let you control and manage collaboration between users in your organization and other organizations. This collaboration is mainly through the Azure Active Directory (
Removed that sentence.

2022-02-05 02:55 UTC, jkdouglas commented on api-reference/beta/resources/crosstenantaccesspolicy.md
> +| definition (deprecated) | String | The raw JSON definition of the cross-tenant access policy. **Deprecated. Do not use.**|
It is left over from a private preview capability and some internal partner teams have taken a dependency on it, so we cannot just remove it but wanted to highlight to customers that they should not use it.

2022-02-05 02:56 UTC, jkdouglas commented on api-reference/beta/resources/crosstenantaccesspolicy.md
> +| definition (deprecated) | String | The raw JSON definition of the cross-tenant access policy. **Deprecated. Do not use.**|
We are not planning on moving this property to the v1.0 endpoint.

2022-02-05 02:56 UTC, opbld30 commented
Docs Build status updates of commit _[d7005d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d7005d430620a9323d9c4c8e88d9ef4c5c7ce2e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-1f2f3c2c)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-02-05 03:03 UTC, opbld32 commented
Docs Build status updates of commit _[3355e68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3355e689c992e9e93b5589e8eb3bed2e526902dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-ed24f702)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-02-05 03:06 UTC, opbld31 commented
Docs Build status updates of commit _[3355e68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3355e689c992e9e93b5589e8eb3bed2e526902dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-28e53c16)
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/mic [...]

2022-02-07 06:36 UTC, opbld34 commented
Docs Build status updates of commit _[5c5df9f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c5df9fc2a1499113a5aac39e64d299576fa62f2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bdb394a8)

<a id="bdb394a8"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202070634261214-13821%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T06%3A36%3A10Z&sr=b&sp=r&sig=XyuUj6i7dnkNyirB5QkzeRg6KGhbBbxBi4YUfdCcb0k%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-07 06:48 UTC, opbld34 commented
Docs Build status updates of commit _[e090358](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e0903580af7e6fee90d98152d04790188e973376)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/ [...]

2022-02-07 17:55 UTC, jkdouglas commented on api-reference/beta/resources/crosstenantaccesspolicy.md
> +# crossTenantAccessPolicy resource type
Confirmed it was an oversight not to make this public. We will start unhiding ASAP.

2022-02-07 17:55 UTC, jkdouglas commented on api-reference/beta/resources/tenantrelationshipaccesspolicybase.md
> +# tenantRelationshipAccessPolicyBase resource type
Confirmed it was an oversight not to make this public. We will start unhiding ASAP. Added a changelog entry for this resource.

2022-02-07 17:58 UTC, opbld34 commented
Docs Build status updates of commit _[6dc1059](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6dc105928d55d60344db6cc239283f3c99352736)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/ [...]

2022-02-07 18:15 UTC, opbld34 commented
Docs Build status updates of commit _[4ef1f33](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ef1f33dc9b320436bdfd97e8a4b19b90b9b1e65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/ [...]

2022-02-07 18:17 UTC, opbld32 commented
Docs Build status updates of commit _[4ef1f33](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ef1f33dc9b320436bdfd97e8a4b19b90b9b1e65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationbase?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-13821) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytargetconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-api-docs-beta/api-reference/ [...]

2022-02-07 18:32 UTC, Lauragra approved these changes

2022-02-07 18:33 UTC, merged