Add docs related to start and stop hold music APIs
microsoftgraph/microsoft-graph-docs pull request #13822
Opened 2021-08-12 20:25 UTC by Hunterjet

2021-08-12 20:26 UTC, opbld34 commented
Docs Build status updates of commit _[20ce096](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20ce0968df001f1cda617424983d1a43fc021b0a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :x:Error | | [Details](#user-content-509863073b5f4abd7c2c863cf9c121de-906841ce)
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :x:Error | | [Details](#user-content-cf918f87f1ddb2cfbb03988a14ddef89-906841ce)

<a id="509863073b5f4abd7c2c863cf9c121de-906841ce"></a>
### [api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md)
 - **Line 87, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/participant-startholdmusic-csharp-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/participant-startholdmusic-javascript-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/participant-startholdmusic-objc-snippets.md'.`````
 - **Line 99, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/participant-startholdmusic-java-snippets.md'.`````

<a id="cf918f87f1ddb2cfbb03988a14ddef89-906841ce"></a>
### [api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md)
 - **Line 77, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/participant-stopholdmusic-csharp-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/participant-stopholdmusic-javascript-snippets.md'.`````
 - **Line 85, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/participant-stopholdmusic-objc-snippets.md'.`````
 - **Line 89, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/participant-stopholdmusic-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108122025360917-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=e02x1E3WA%2FFT8sruPDd9KZ80oewtRS2H83i4fv5a0d8%3D&st=2021-08-12T20%3A21%3A43Z&se=2021-09-12T20%3A26%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-13 01:35 UTC, opbld32 commented
Docs Build status updates of commit _[2795ce3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2795ce3ca55a3dfef88f516949e0d181b1cddf8e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :x:Error | | [Details](#user-content-509863073b5f4abd7c2c863cf9c121de-8f804ce7)
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :x:Error | | [Details](#user-content-cf918f87f1ddb2cfbb03988a14ddef89-8f804ce7)

<a id="509863073b5f4abd7c2c863cf9c121de-8f804ce7"></a>
### [api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md)
 - **Line 85, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/participant-startholdmusic-csharp-snippets.md'.`````
 - **Line 89, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/participant-startholdmusic-javascript-snippets.md'.`````
 - **Line 93, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/participant-startholdmusic-objc-snippets.md'.`````
 - **Line 97, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/participant-startholdmusic-java-snippets.md'.`````

<a id="cf918f87f1ddb2cfbb03988a14ddef89-8f804ce7"></a>
### [api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md)
 - **Line 77, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/participant-stopholdmusic-csharp-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/participant-stopholdmusic-javascript-snippets.md'.`````
 - **Line 85, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/participant-stopholdmusic-objc-snippets.md'.`````
 - **Line 89, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/participant-stopholdmusic-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108130134318791-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=HD6lTCm54qBhS5iy81IVBYmr0qv4OHkiIxBo3RuTAVo%3D&st=2021-08-13T01%3A30%3A39Z&se=2021-09-13T01%3A35%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-13 01:37 UTC, opbld31 commented
Docs Build status updates of commit _[37c6a77](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37c6a7744519493a204fffbbdd73382ea51eac1d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :x:Error | | [Details](#user-content-509863073b5f4abd7c2c863cf9c121de-d0e70ffe)
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :x:Error | | [Details](#user-content-cf918f87f1ddb2cfbb03988a14ddef89-d0e70ffe)

<a id="509863073b5f4abd7c2c863cf9c121de-d0e70ffe"></a>
### [api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md)
 - **Line 85, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/participant-startholdmusic-csharp-snippets.md'.`````
 - **Line 89, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/participant-startholdmusic-javascript-snippets.md'.`````
 - **Line 93, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/participant-startholdmusic-objc-snippets.md'.`````
 - **Line 97, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/participant-startholdmusic-java-snippets.md'.`````

<a id="cf918f87f1ddb2cfbb03988a14ddef89-d0e70ffe"></a>
### [api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md)
 - **Line 77, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/participant-stopholdmusic-csharp-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/participant-stopholdmusic-javascript-snippets.md'.`````
 - **Line 85, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/participant-stopholdmusic-objc-snippets.md'.`````
 - **Line 89, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/participant-stopholdmusic-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108130135546365-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=YEGt6sOzeuVk2RAZttwsV63qZNw9nD6KnmMaRwt5quQ%3D&st=2021-08-13T01%3A32%3A11Z&se=2021-09-13T01%3A37%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-16 20:37 UTC, opbld32 commented
Docs Build status updates of commit _[6435f70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6435f70a900a405095f7dc479bb7f29bac0d3f3a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :x:Error | | [Details](#user-content-509863073b5f4abd7c2c863cf9c121de-3114b0aa)
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :x:Error | | [Details](#user-content-cf918f87f1ddb2cfbb03988a14ddef89-3114b0aa)

<a id="509863073b5f4abd7c2c863cf9c121de-3114b0aa"></a>
### [api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md)
 - **Line 85, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/participant-startholdmusic-csharp-snippets.md'.`````
 - **Line 89, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/participant-startholdmusic-javascript-snippets.md'.`````
 - **Line 93, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/participant-startholdmusic-objc-snippets.md'.`````
 - **Line 97, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/participant-startholdmusic-java-snippets.md'.`````

<a id="cf918f87f1ddb2cfbb03988a14ddef89-3114b0aa"></a>
### [api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md)
 - **Line 75, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/participant-stopholdmusic-csharp-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/participant-stopholdmusic-javascript-snippets.md'.`````
 - **Line 83, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/participant-stopholdmusic-objc-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/participant-stopholdmusic-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108162034475891-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=7TDkPPQrCVIGO0IKT7WxG3U%2FAXZFUhEBC0y0XaSvfmk%3D&st=2021-08-16T20%3A32%3A10Z&se=2021-09-16T20%3A37%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-16 21:18 UTC, opbld34 commented
Docs Build status updates of commit _[ecaafaa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ecaafaa47eaf1ec757cf6b7db6a882fba98f137d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :x:Error | | [Details](#user-content-509863073b5f4abd7c2c863cf9c121de-4d5c85fe)
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :x:Error | | [Details](#user-content-cf918f87f1ddb2cfbb03988a14ddef89-4d5c85fe)

<a id="509863073b5f4abd7c2c863cf9c121de-4d5c85fe"></a>
### [api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md)
 - **Line 85, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/participant-startholdmusic-csharp-snippets.md'.`````
 - **Line 89, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/participant-startholdmusic-javascript-snippets.md'.`````
 - **Line 93, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/participant-startholdmusic-objc-snippets.md'.`````
 - **Line 97, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/participant-startholdmusic-java-snippets.md'.`````

<a id="cf918f87f1ddb2cfbb03988a14ddef89-4d5c85fe"></a>
### [api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md)
 - **Line 75, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/participant-stopholdmusic-csharp-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/participant-stopholdmusic-javascript-snippets.md'.`````
 - **Line 83, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/participant-stopholdmusic-objc-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/participant-stopholdmusic-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108162115469902-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=zgpNeah6thOoLuUP2NrXF1UgSXneX2hq%2BvSlK6i91K8%3D&st=2021-08-16T21%3A13%3A39Z&se=2021-09-16T21%3A18%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-16 22:11 UTC, opbld31 commented
Docs Build status updates of commit _[c13d143](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c13d143c333cb89db38fc28dbb2085f172b2403c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-stopholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/startholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/startholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/startholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/stopholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/stopholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/stopholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108162208111954-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=wulI%2FiXY8VoJoXtqEUAqW1FWMswz%2BzNswbQr%2FoYUt34%3D&st=2021-08-16T22%3A06%3A01Z&se=2021-09-16T22%3A11%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-19 01:17 UTC, opbld31 commented
Docs Build status updates of commit _[f276932](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2769329f2562c74ede019e4d7bf6fb1b1f97c50)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-stopholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/startholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/startholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/startholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/stopholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/stopholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/stopholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108190115548257-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=SeUSzwsU4DLnv7NNvsKd3pVq69S1jFrCMlaUIM3r1zc%3D&st=2021-08-19T01%3A12%3A25Z&se=2021-09-19T01%3A17%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-19 19:40 UTC, opbld34 commented
Docs Build status updates of commit _[82a47da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82a47da841ac4fa51ed1cbd694c49424d32236b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-stopholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/startholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/startholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/startholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/stopholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/stopholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/stopholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108191938596668-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=pa4vYuzjFbP9dp4ljDmsrf0N%2B%2FySRgfRg7QMFT4b7wI%3D&st=2021-08-19T19%3A35%3A28Z&se=2021-09-19T19%3A40%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-23 20:54 UTC, opbld31 commented
Docs Build status updates of commit _[a6a50a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a6a50a19a9c18c006924af26855dc631c56cf18f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-stopholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/startholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/startholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/startholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/stopholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/stopholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/stopholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108232053080396-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=5%2BeEzGfqrQliuZVrfX3iuAmNEmFgsqP0D04B10m9oQk%3D&st=2021-08-23T20%3A49%3A26Z&se=2021-09-23T20%3A54%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-24 20:25 UTC, opbld33 commented
Docs Build status updates of commit _[8f51e18](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f51e18e23134e278a87e5ceb2731f3cca64d078)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-stopholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/startholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/startholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/startholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/stopholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/stopholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/stopholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108242023382414-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=iig1V3dXvNNRDF2KP2f5QLGSjshbKAKC0QpGBtBtomo%3D&st=2021-08-24T20%3A20%3A01Z&se=2021-09-24T20%3A25%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-25 14:52 UTC, isvargasmsft commented on api-reference/beta/api/participant-startholdmusic.md
> +---
General:
1. Please include proper TOC entries for these methods under Cloud Communications > Calls > Participant, at the bottom.
2. Since startHoldMusic and stopHoldMusic resource types are entities and not complex types, please create reference topics for both and indicate that they inherit from commsOperation. 
3. Please update the participant resource type to include these new methods.

2021-08-25 15:05 UTC, isvargasmsft commented on api-reference/beta/api/participant-startholdmusic.md
> +| Application                            | For joining meetings: Calls.JoinGroupCallsasGuest.All or Calls.JoinGroupCalls.All<br/>For initiating peer-to-peer calls: Calls.Initiate.All<br/>For initiati
Please only include the permissions required to call this method, and order them from least to most privileged.

2021-08-25 15:07 UTC, isvargasmsft commented on api-reference/beta/api/participant-startholdmusic.md
> +> **Note:** The `/app` path is deprecated. Going forward, use the `/communications` path.
If the /app path is deprecated, why are we including it? This could lead to confusion.

2021-08-25 15:08 UTC, isvargasmsft commented on api-reference/beta/api/participant-startholdmusic.md
> +|clientContext|String|Unique client context string. Can have a maximum of 256 characters.|
Is this required? Please clarify whether providing a request body is required.

2021-08-25 15:18 UTC, isvargasmsft commented on api-reference/beta/api/participant-startholdmusic.md
> +---
I realized there is already a resource topic for startHoldMusic and stopHoldMusic. Please include a method section because these are not complex types, according to the CSDL. In addition, please add them to the TOC.

There are other observations and corrections required in both topics. Please include them in this PR.

2021-08-25 15:20 UTC, isvargasmsft commented on api-reference/beta/api/participant-startholdmusic.md
> +The following example shows the request.
Please rephrase to: The following is an example of a request.

2021-08-25 15:49 UTC, isvargasmsft commented on api-reference/beta/api/participant-startholdmusic.md
> +POST https://graph.microsoft.com/beta/communications/calls/e141b67c-90fd-455d-858b-b48a40b9cc8d/participants/fa1e9582-7145-4ca3-bcd8-577f561fcb6e/microsoft.graph.startHoldMusic
This request doesn't complain with the one in the HTTP section. Please clarify the method syntax.

2021-08-25 15:49 UTC, isvargasmsft commented on api-reference/beta/api/participant-startholdmusic.md
> +##### Response
Please use H3

2021-08-25 15:50 UTC, isvargasmsft commented on api-reference/beta/api/participant-startholdmusic.md
> +Location: https://graph.microsoft.com/beta/communications/calls/e141b67c-90fd-455d-858b-b48a40b9cc8d/operations/0fe0623f-d628-42ed-b4bd-8ac290072cc5
Is this line included in the actual response that customers receive? If it is not, please remove it to avoid confusion.

2021-08-25 15:51 UTC, isvargasmsft commented on api-reference/beta/api/participant-startholdmusic.md
> +##### Notification - operation completed
Please clarify the purpose of this section. Is this supposed to be a second example? Please clarify.

2021-08-30 17:07 UTC, isvargasmsft commented on api-reference/beta/api/participant-startholdmusic.md
> +Location: https://graph.microsoft.com/beta/communications/calls/e141b67c-90fd-455d-858b-b48a40b9cc8d/operations/0fe0623f-d628-42ed-b4bd-8ac290072cc5
If the response include it, then please keep it. We should keep the examples as realistic as possible.

2021-08-31 22:15 UTC, opbld31 commented
Docs Build status updates of commit _[8da5e47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8da5e475254a17f7b9905ff826031ad930a58fb6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-stopholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/participant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/participant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participant?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/startholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/startholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/startholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/stopholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/stopholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/stopholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108312213301682-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=9Y0jP8VRQvJ7AYPpGuaTQ16%2BKJVCAGtutTQj0R1LFQQ%3D&st=2021-08-31T22%3A10%3A19Z&se=2021-10-01T22%3A15%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-01 13:40 UTC, isvargasmsft commented on api-reference/beta/api/participant-stopholdmusic.md
> +|clientContext|String|Optional. Unique client context string. Can have a maximum of 256 characters.|
Request body section: My apologies, I didn't clarify my previous comment. 
1. In the api.md file, it is mentioned that this method is bound to a `microsoft.graph.participant` entity (binding parameter), which is required. 
2. The CSDL also mentions that a startHoldMusicOperation resource is required as parameter to call this action. 

That being said, please clarify which parameters are required and then list the optional ones.

2021-09-01 13:41 UTC, isvargasmsft commented on api-reference/beta/api/participant-startholdmusic.md
> +|clientContext|String|Optional. Unique client context string. Can have a maximum of 256 characters.|
Request body section: My apologies, I didn't clarify my previous comment.

1. In the api.md file, it is mentioned that this method is bound to a microsoft.graph.participant entity (binding parameter), which is required.
2. The CSDL also mentions that a startHoldMusicOperation resource is required as parameter to call this action.

That being said, please clarify which parameters are required and then list the optional ones.

2021-09-01 13:50 UTC, isvargasmsft commented on api-reference/beta/resources/startholdmusicoperation.md
> +
According to the api.md file, this resource supports CRUD operations. Please confirm if this is the case. 

If these resources support CRUD operations, then we should create topics for each operation and include the methods section in the resource topics.

2021-09-01 13:50 UTC, isvargasmsft commented on api-reference/beta/resources/startholdmusicoperation.md
> +
This comment applies to both startHoldMusicOperation and stopHoldMusicOperation resource topics.

2021-09-01 13:53 UTC, isvargasmsft commented on api-reference/beta/api/participant-startholdmusic.md
> +In the request body, provide a JSON object with the following parameters.
Please clarify how this functionality works:
* Should I create a startHoldMusicOperation resource first and then call this method using that resource as biding parameter? Or does this method create the startHoldMusicOperation resource? 

It is unclear because the CSDL mentions that the resource is a binding parameter but we are not including a topic to create the resource in the first place.

2021-09-01 13:54 UTC, isvargasmsft commented on api-reference/beta/api/participant-startholdmusic.md
> +description: "Allow the application to place a participant on hold while playing music on the background."
Description in lines 3 and 16 should match. Please copy line 14 here.

2021-09-01 13:54 UTC, isvargasmsft commented on api-reference/beta/api/participant-startholdmusic.md
> +description: "Allow the application to place a participant on hold while playing music on the background."
This comment applies to the other topics as well.

2021-09-01 15:44 UTC, isvargasmsft requested changes
Hello Jose, 

Thank you very much for addressing the comments in my first review. 

Please clarify the following:
1. According to the csdl and api.md files, the startHoldMusic methods require a startHoldMusicOperation resource. Does this mean we should create the resource before calling the method?
2. This leads me to the second question. The api.md file states that the startHoldMusicOperation resources support CRUD operations (List, Create, Get, Update and Delete). If this is the case, then please create method topics for each and add those to the method section of the resource topics and to the TOC.
3. Please make the descriptions in line 3 consistent with the descriptions in ~lines 16. 

Please ping me on the side if you have any questions. I'm here to help!

Kind regards, 

Isaac Vargas

2021-09-01 15:57 UTC, isvargasmsft commented on changelog/Microsoft.Skype.Calling.json
> +          "Target": "stopHoldMusicOperation"
1. I just noticed the actual binding parameter is participant, not startHoldMusicOperation. Please modify the target and the second part of the description to **participant**. 
2. In addition, the ApiChange should be **Method**. I'll open a bug to track these Graph Studio errors.

2021-09-01 15:58 UTC, isvargasmsft commented on changelog/Microsoft.Skype.Calling.json
> +          "ApiChange": "EntityType",
ApiChange should be Resource.

2021-09-01 15:58 UTC, isvargasmsft commented on changelog/Microsoft.Skype.Calling.json
> +          "ApiChange": "EntityType",
ApiChange should be resource.

2021-09-01 16:02 UTC, isvargasmsft commented on changelog/Microsoft.Skype.Calling.json
> +          "ApiChange": "EntityType",
Guidelines: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-properties

2021-09-01 16:02 UTC, isvargasmsft commented on changelog/Microsoft.Skype.Calling.json
> +          "Target": "stopHoldMusicOperation"
Guidelines: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-properties

2021-09-01 21:27 UTC, Hunterjet commented on api-reference/beta/api/participant-stopholdmusic.md
> +|clientContext|String|Optional. Unique client context string. Can have a maximum of 256 characters.|
This method creates and returns the startHoldMusicOperation resource.
I believe you've misread the api.md file. The parameters table doesn't only list inputs. You can see in the "kind" column that startHoldMusicOperation has been listed as "return" i.e. startHoldMusic returns a startHoldMusicOperation.
Neither startHoldMusic nor stopHoldMusic have any mandatory parameters.

2021-09-01 21:28 UTC, Hunterjet commented on api-reference/beta/api/participant-startholdmusic.md
> +|clientContext|String|Optional. Unique client context string. Can have a maximum of 256 characters.|
StartHoldMusicOperation is returned by this method. No parameters are required. Is it fine like this? I did write that the parameters are optional in their description. Should I add a note explicitly stating none are required?

2021-09-01 21:43 UTC, Hunterjet commented on api-reference/beta/resources/startholdmusicoperation.md
> +
They support GET. This feature is inherited from commsOperation. We currently have 29 Operations that inherit from commsOperation (inviteParticipantsOperation, muteParticipantOperation, playPromptOperation, recordOperation to name a few) which passed documentation review and I don't see topics for GETs on any of them, so is this really required?

2021-09-01 21:44 UTC, Hunterjet commented on api-reference/beta/api/participant-startholdmusic.md
> +In the request body, provide a JSON object with the following parameters.
This method returns a startHoldMusicOperation.

2021-09-01 21:52 UTC, jasonjoh commented
Docs Build status updates of commit _[e6c70a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e6c70a93f0ffcc7e969ad110d994443d61fc71cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-stopholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/participant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/participant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participant?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/startholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/startholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/startholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/stopholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/stopholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/stopholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109012150132503-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=mlVMG0yRowkiZreTZv%2B8GiTsBZoK2HKHZ1nd5jV4RXc%3D&st=2021-09-01T21%3A47%3A04Z&se=2021-10-02T21%3A52%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 13:39 UTC, jasonjoh commented
Docs Build status updates of commit _[b599e13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b599e13d5439daf689a5d3939e262c206112ca1e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-stopholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/participant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/participant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participant?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/startholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/startholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/startholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/stopholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/stopholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/stopholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021336254678-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=lSQMl0daBYteZgFvuUKMJ7DK7zfhqepfNZ0xl1KHgak%3D&st=2021-09-02T13%3A34%3A54Z&se=2021-10-03T13%3A39%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 13:46 UTC, jasonjoh commented
Docs Build status updates of commit _[21e89e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21e89e52bd8f900e9e12aa9a61e32955987375e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-stopholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/participant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/participant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participant?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/startholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/startholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/startholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/stopholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/stopholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/stopholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021343171937-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=8%2Fsy%2BPhrdEmGQT9vJS8FDjkq5Er87IbAQ8qt1I63Up8%3D&st=2021-09-02T13%3A41%3A49Z&se=2021-10-03T13%3A46%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 14:07 UTC, jasonjoh commented
Docs Build status updates of commit _[7b243af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b243afda7cf8a7cb01a5c5d2cbe6773eaac862c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-stopholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/participant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/participant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participant?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/startholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/startholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/startholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/stopholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/stopholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/stopholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021406254609-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=tgeHV7v16%2FAwIaa5QOwp5nsKlUojfZ3Ah5KYW0MP0LE%3D&st=2021-09-02T14%3A02%3A52Z&se=2021-10-03T14%3A07%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 14:10 UTC, isvargasmsft approved these changes
Thank you very much for the clarifications and the quick responses. 

Kind regards!

2021-09-08 02:55 UTC, opbld32 commented
Docs Build status updates of commit _[bdef739](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bdef7396157a5b975511886be42b2285d6d233d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-stopholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/participant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/participant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participant?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/startholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/startholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/startholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/stopholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/stopholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/stopholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109080253445449-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=mlXyiXMNuh1ja8LWbhxd26sNf0lfsWpS5MFw%2FPGSit4%3D&st=2021-09-08T02%3A50%3A48Z&se=2021-10-09T02%3A55%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 02:58 UTC, opbld34 commented
Docs Build status updates of commit _[51b0ab8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/51b0ab82950463a1b1d88982020b2718913c3927)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/participant-startholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-startholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/api/participant-stopholdmusic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/api/participant-stopholdmusic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-stopholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/participant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/participant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participant?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/startholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/startholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/startholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/resources/stopholdmusicoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/resources/stopholdmusicoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/stopholdmusicoperation?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-startholdmusic?view=graph-rest-beta&branch=pr-en-us-13822) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/hold-music/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109080254087634-13822%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=UqapBXO1xfOG4UxWQ3%2FPfzJm%2FlLeN6WWUKZpSLsvP18%3D&st=2021-09-08T02%3A53%3A06Z&se=2021-10-09T02%3A58%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 02:58 UTC, merged