update mgt-file-list with new attributes and options from file-upload.
microsoftgraph/microsoft-graph-docs pull request #13861
Opened 2021-08-17 19:31 UTC by aaclage

update mgt-file-list with new attributes and options from new file-upload feature.

for revision @beth-panx

2021-08-18 19:29 UTC, beth-panx requested changes
Need to change a few things. @elisenyang feel free to add your comments.

2021-08-18 19:29 UTC, beth-panx commented on concepts/toolkit/components/file-list.md
> +| Default (no identifiers or query provided) | Files.Read, Files.Read.All, Sites.Read.All, Files.ReadWrite, Files.ReadWrite.All, Sites.ReadWrite.All | `GET /me/drive/root/children` <br /> `PUT /me/dr
@aaclage I think these need to be separated to their own row. They depend on the attribute `{enable-file-upload}`.
```suggestion
| Default (no identifiers or query provided) | Files.Read, Files.Read.All, Sites.Read.All | `GET /me/drive/root/children` |
| Provide `{enable-file-upload}` | Files.Read, Files.Read.All, Sites.Read.All, Files.ReadWrite, Files.ReadWrite.All, Sites.ReadWrite.All | `GET /me/drive/root/children` <br /> `PUT /me/drive/root:/{filename}:/content` <br /> `POST /me/drive/root:/{filename}:/createUploadSession` |
```

2021-08-18 19:29 UTC, beth-panx commented on concepts/toolkit/components/file-list.md
> +| Provide `{drive-id}` AND `{item-id}` | Files.Read, Files.Read.All, Sites.Read.All, Files.ReadWrite, Files.ReadWrite.All, Sites.ReadWrite.All | `GET /drives/{drive-id}/items/{item-id}/children` <br
Similar here and below:

```suggestion
| Provide `{drive-id}` AND `{item-id}` | Files.Read, Files.Read.All, Sites.Read.All | `GET /drives/{drive-id}/items/{item-id}/children`|
| Provide `{drive-id}` AND `{item-id}` AND `{enable-file-upload}` | Files.Read, Files.Read.All, Sites.Read.All, Files.ReadWrite, Files.ReadWrite.All, Sites.ReadWrite.All | `GET /drives/{drive-id}/items/{item-id}/children` <br /> `PUT /drives/{drive-id}/items/{item-id}:/{filename}:/content` <br /> `POST /drives/{drive-id}/items/{item-id}:/{filename}:/createUploadSession` |
```

2021-08-18 19:29 UTC, beth-panx commented on concepts/toolkit/components/file-list.md
> +| max-upload-file | maxUploadFile | Number, default value are 10 files. |
```suggestion
| excluded-file-extensions | excludedFileExtensions | String array of file extensions to be excluded from file upload. Must also provide `enable-file-upload` attribute. |
| max-file-size | maxFileSize | Number to restrict upload size (KB). Must also provide `enable-file-upload` attribute. |
| max-upload-file | maxUploadFile | Number, default value are 10 files. Must also provide `enable-file-upload` attribute. |
```

2021-08-18 19:29 UTC, beth-panx commented on concepts/toolkit/components/file-list.md
> +The following example enable the file upload feature.
```suggestion
The following example enables the file upload feature.
```

2021-08-18 19:29 UTC, beth-panx commented on concepts/toolkit/components/file-list.md
> +The following example limit upload to 5 files.
```suggestion
The following example limits maximum number of files that can be uploaded to 5.
```

2021-08-18 19:29 UTC, beth-panx commented on concepts/toolkit/components/file-list.md
> +The following example limit upload file size to 10000 KB.
```suggestion
The following example limits maximum file size that can be uploaded to 10000 KB.
```

2021-08-18 19:29 UTC, beth-panx commented on concepts/toolkit/components/file-list.md
> +The following example exclude upload of files with file extensions ".doc,.pdf".
```suggestion
The following example excludes upload of files with file extensions ".doc,.pdf".
```

2021-08-18 19:39 UTC, beth-panx commented on concepts/toolkit/components/file-list.md
> +| Provide `{drive-id}` AND `{item-id}` | Files.Read, Files.Read.All, Sites.Read.All, Files.ReadWrite, Files.ReadWrite.All, Sites.ReadWrite.All | `GET /drives/{drive-id}/items/{item-id}/children` <br
Need to change the sections following this part too. :)

2021-08-18 19:42 UTC, aaclage commented
> Need to change a few things. @elisenyang feel free to add your comments.

@beth-panx working on it.

2021-08-18 20:06 UTC, aaclage commented
@beth-panx @elisenyang

API graph table updated.

2021-08-18 20:49 UTC, beth-panx approved these changes

2021-08-20 19:07 UTC, elisenyang commented on concepts/toolkit/components/file-list.md
> +| enable-file-upload | enableFileUpload | Boolean to enable or disable file upload extension, default is false.  |
```suggestion
| enable-file-upload | enableFileUpload | Boolean to enable or disable file upload functionality. The default value is `false`.  |
```

2021-08-20 19:07 UTC, elisenyang commented on concepts/toolkit/components/file-list.md
> +| excluded-file-extensions | excludedFileExtensions | String array of file extensions to be excluded from file upload. Must also provide `enable-file-upload` attribute. |
```suggestion
| excluded-file-extensions | excludedFileExtensions | String array of file extensions to be excluded from file upload. Must also set the `enable-file-upload` attribute to `true`. |
```

2021-08-20 19:07 UTC, elisenyang commented on concepts/toolkit/components/file-list.md
> +| max-file-size | maxFileSize | Number to restrict upload size (KB). Must also provide `enable-file-upload` attribute. |
```suggestion
| max-file-size | maxFileSize | A number representing the maximum file upload size (KB). Must also set the `enable-file-upload` attribute to `true`. |
```

2021-08-20 19:07 UTC, elisenyang commented on concepts/toolkit/components/file-list.md
> +| max-upload-file | maxUploadFile | Number, default value are 10 files. Must also provide `enable-file-upload` attribute. |
```suggestion
| max-upload-file | maxUploadFile | A number representing the maximum number of files allowed to be uploaded. The default value is `10` files. Must also set the `enable-file-upload` attribute to `true`. |
```

2021-08-20 19:07 UTC, elisenyang commented on concepts/toolkit/components/file-list.md
> +The following example limits maximum number of files that can be uploaded to 5.
```suggestion
The following example limits the maximum number of files that can be uploaded to 5.
```

2021-08-20 19:07 UTC, elisenyang commented on concepts/toolkit/components/file-list.md
> +The following example limits maximum file size that can be uploaded to 10000 KB.
```suggestion
The following example limits the maximum file size that can be uploaded to 10000 KB.
```

2021-08-20 19:09 UTC, elisenyang approved these changes

2021-08-20 19:09 UTC, opbld32 commented
Docs Build status updates of commit _[d882641](https://github.com/aaclage/microsoft-graph-docs/commits/d882641fb33e021ab2c63fb6fc5c92b94c7e716c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/file-list.md](https://github.com/aaclage/microsoft-graph-docs/blob/aaclage/file-list-file-upload/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-13861) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201908326342-13861%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=grYxorIXeU2rgRP9jKqpnVPOROtSiPIpSxQsDb33%2BcQ%3D&st=2021-08-20T19%3A04%3A58Z&se=2021-09-20T19%3A09%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 19:11 UTC, merged

2021-08-20 19:15 UTC, aaclage commented
@elisenyang Thanks