User-centric Teams messaging subscription documentation
microsoftgraph/microsoft-graph-docs pull request #13885
Opened 2021-08-18 20:01 UTC by eddie-lee-msft

User-centric Teams messaging subscription documentation

2021-08-18 20:02 UTC, opbld30 commented
Docs Build status updates of commit _[4de1d86](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4de1d86005869a4b797aa7d2e0ea5723e2bc2c3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-13885) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-13885) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108182001079727-13885%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=YXgUpBB2936suiD7wm0QhMI6cK0n7Gtfcsv%2FBKu7I20%3D&st=2021-08-18T19%3A57%3A44Z&se=2021-09-18T20%3A02%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-18 20:21 UTC, opbld34 commented
Docs Build status updates of commit _[2ab1105](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ab1105af7ebf72a889adc46f198415f62a9bd8e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-13885) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-13885) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108182020128645-13885%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=mevimlVJZVTYFLWp4tztQEdO7wLhoQzEUYHXso63o38%3D&st=2021-08-18T20%3A16%3A44Z&se=2021-09-18T20%3A21%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-19 04:55 UTC, RamjotSingh requested changes

2021-08-19 19:29 UTC, opbld32 commented
Docs Build status updates of commit _[9068324](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9068324bc55c246299d389eb05a1f7e28d67fd8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-13885) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-13885) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108191928140599-13885%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=mxzAxziPI%2B%2BbfQoGDCW1JuV6jDuwJKLSNgWlWPIdPek%3D&st=2021-08-19T19%3A24%3A47Z&se=2021-09-19T19%3A29%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 16:54 UTC, RamjotSingh approved these changes

2021-08-20 16:54 UTC, RamjotSingh commented on concepts/teams-changenotifications-chatmessage.md
> +> **Note:** User-level chat messaging subscriptions are currently in preview.
I believe 2 Note back to back are not liked. You can remove first Note since we mention it below.

2021-08-20 18:35 UTC, opbld34 commented
Docs Build status updates of commit _[f2cf889](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2cf88970c1dea1363e7185224a2b9b409e5d545)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-13885) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-13885) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201834104529-13885%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=XQEwb3gdhNvX%2BYC6i8fP3%2BGrHIbHtZfBDTgxdUkPATw%3D&st=2021-08-20T18%3A30%3A44Z&se=2021-09-20T18%3A35%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-27 23:26 UTC, eddie-lee-msft commented on concepts/teams-changenotifications-chatmessage.md
> +### Example 2: Subscribe to messages in all chats a user is part of in delegated mode, using the `/me/chats/getAllMessages` resource path
Actually, at the user level '/me/chats/getAllMessages' is not required. It is simply another option folks can use in addition to '/users/user-id/chats/getAllMessages' when calling in delegated mode.

2021-08-27 23:27 UTC, eddie-lee-msft commented on concepts/teams-changenotifications-chatmessage.md
> +### Example 2: Subscribe to messages in all chats a user is part of in delegated mode, using the `/me/chats/getAllMessages` resource path
What would you suggest I rephrase this to in this case, as well as in the blob from your comment above?

2021-08-30 21:00 UTC, JarbasHorst requested changes

2021-08-30 21:57 UTC, opbld30 commented
Docs Build status updates of commit _[5330721](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5330721e8348f2ef666d917617312b378e8d10e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-13885) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13885) (graph-rest-beta) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/UserScopedSubscriptionDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-13885) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108302156123573-13885%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=loqfuhsWIEFGXQFh4f002kemznrHYb4fX%2FOhIvZqS9g%3D&st=2021-08-30T21%3A52%3A53Z&se=2021-09-30T21%3A57%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-31 19:33 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-09-01 20:45 UTC, Lauragra approved these changes

2021-09-03 22:30 UTC, merged