Sign in with Apple
microsoftgraph/microsoft-graph-docs pull request #13892
Opened 2021-08-18 23:09 UTC by namkedia

Add support to Sign in with Apple resource to the identityProviderBase in v1.0

2021-08-18 23:11 UTC, opbld30 commented
Docs Build status updates of commit _[c2c5fd6](https://github.com/namkedia/microsoft-graph-docs/commits/c2c5fd6ebff82f8bd6f2b8992f79835205c5d2cb)_: 

### :warning: Validation status: warnings


For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108182309343799-13892%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=IzAjIHtrl4%2BRDb2DOU1zxgM%2BZGuicYPI%2Fe9I3fc9MIE%3D&st=2021-08-18T23%3A06%3A05Z&se=2021-09-18T23%3A11%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-18 23:14 UTC, opbld31 commented
Docs Build status updates of commit _[07f80e2](https://github.com/namkedia/microsoft-graph-docs/commits/07f80e2a7f29ff4be645cf8ce22fb166bda25506)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-a8363dce632442b3d61d6aec8f5a6d8b-b58bc58e)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |

<a id="a8363dce632442b3d61d6aec8f5a6d8b-b58bc58e"></a>
### [api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108182313294603-13892%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=3BcBx1BHk3dzEch93tng179En4KJnDnXLIqcUaAwpBI%3D&st=2021-08-18T23%3A09%3A58Z&se=2021-09-18T23%3A14%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-18 23:16 UTC, opbld34 commented
Docs Build status updates of commit _[9e77238](https://github.com/namkedia/microsoft-graph-docs/commits/9e77238b6041a729d5d24f57d8602a1d34a6cd17)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108182314027761-13892%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=wYUgl967ZebdmMbPtgtGWOVkwQffBu4kCDiNEERoJm8%3D&st=2021-08-18T23%3A11%3A46Z&se=2021-09-18T23%3A16%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-18 23:23 UTC, opbld33 commented
Docs Build status updates of commit _[9e03b75](https://github.com/namkedia/microsoft-graph-docs/commits/9e03b75fe9fad3b4b7e02ad0cd0c6e2a9065b2a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/apple/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108182322018414-13892%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=GC05Ic8xKj1jVxTCCjcmYnlMnroExyHIDbkdXK5LauQ%3D&st=2021-08-18T23%3A18%3A25Z&se=2021-09-18T23%3A23%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-17 01:42 UTC, opbld31 commented
Docs Build status updates of commit _[9d0dea5](https://github.com/namkedia/microsoft-graph-docs/commits/9d0dea574a75d3747b195e51ecb476681c8e9394)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/apple/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109170140279301-13892%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-18T01%3A42%3A00Z&sr=b&sp=r&sig=Yit9rUnJGGeXFkTi9Q9MqZu76HfvwiLdCEm4ep1J%2BNY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-08 23:32 UTC, opbld34 commented
Docs Build status updates of commit _[927d1cb](https://github.com/namkedia/microsoft-graph-docs/commits/927d1cbae2bd010fd3e4a659cf792476a05051d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/apple/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111082330400731-13892%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-09T23%3A32%3A05Z&sr=b&sp=r&sig=YaU6SoVGhHJ0vcUS6cXxiYbqfA9XwFBct63KggADE3w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-09 03:11 UTC, namkedia commented on api-reference/v1.0/resources/applemanagedidentityprovider.md
> +|[Get](../api/identityproviderbase-get.md) |appleManagedIdentityProvider |Retrieve properties of the Apple identity provider configuration.|
Ack

2021-11-09 03:14 UTC, opbld30 commented
Docs Build status updates of commit _[2b7297b](https://github.com/namkedia/microsoft-graph-docs/commits/2b7297b6fa88b101ff822bf054c3fa40ab7b5124)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/apple/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111090313072433-13892%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T03%3A14%3A27Z&sr=b&sp=r&sig=HPryVDc2snioZuy1V9bFgXKx0DPgzCHqrNpkeSdKFbw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-09 03:22 UTC, opbld33 commented
Docs Build status updates of commit _[88ff5c3](https://github.com/namkedia/microsoft-graph-docs/commits/88ff5c369287c6430ad2ca26b51abc473659a53e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/apple/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111090320165112-13892%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T03%3A21%3A59Z&sr=b&sp=r&sig=MRPTDqQ8pOg%2BujVXlwypDK7GndHDVjzlCVVRSZy66gE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-09 03:28 UTC, opbld31 commented
Docs Build status updates of commit _[90c8a51](https://github.com/namkedia/microsoft-graph-docs/commits/90c8a513732fc3963b6853b2c153f34d82ebc3ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/apple/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111090327076339-13892%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T03%3A28%3A41Z&sr=b&sp=r&sig=bKhcBApraUAbq2oRMKOo4z9ontOGnArkWOTvk%2FY7kDM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-09 17:58 UTC, FaithOmbongi requested changes
@namkedia , we're missing the references to appleManagedIdentityProvider in the Methods table of identityProviderBase resource. For example, [in the beta topic](https://docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta#methods), we mention that the return type for the Create, Get, Delete operations may also be an appleManagedIdentityProvider. I assume this is still so in the v1.0 topic?

2021-11-09 17:58 UTC, FaithOmbongi commented on api-reference/v1.0/resources/applemanagedidentityprovider.md
> +|displayName|String|The display name of the identity provider. Inherited from [identityProviderBase](../resources/identityproviderbase.md).|
Reordered the table alphabetically for easier scanning
```suggestion
|certificateData|String|The certificate data which is a long string of text from the certificate, can be null.|
|developerId|String|The Apple developer identifier. Required.|
|displayName|String|The display name of the identity provider. Inherited from [identityProviderBase](../resources/identityproviderbase.md).|
|id|String|The identifier of the identity provider. Inherited from [identityProviderBase](../resources/identityproviderbase.md). Read-only.|
|keyId|String|The Apple key identifier. Required.|
|serviceId|String|The Apple service identifier. Required.|
```

2021-11-09 17:58 UTC, FaithOmbongi commented on api-reference/v1.0/resources/applemanagedidentityprovider.md
> +ms.localizationpriority: high
Recommended loc priority for reference articles is medium
```suggestion
ms.localizationpriority: medium
```

2021-11-09 18:04 UTC, opbld33 commented
Docs Build status updates of commit _[722100e](https://github.com/namkedia/microsoft-graph-docs/commits/722100ea2d0f8a6ffad064222bc3cf9efdbc34f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/apple/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111091802318822-13892%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T18%3A04%3A19Z&sr=b&sp=r&sig=5nRgYrh97ec6Fddu9GY0qnZL2AM1BgykYVAUAR2vi1k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-09 18:06 UTC, opbld34 commented
Docs Build status updates of commit _[1b5bf44](https://github.com/namkedia/microsoft-graph-docs/commits/1b5bf44f6e1ebccd057a2b30bcfa496b66730e51)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/apple/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111091802404517-13892%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T18%3A06%3A54Z&sr=b&sp=r&sig=yv9gGFut%2Bic0oUNNZ261iQGoZcBV6eUDSxYf5Pit74c%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-09 18:22 UTC, opbld33 commented
Docs Build status updates of commit _[0766502](https://github.com/namkedia/microsoft-graph-docs/commits/0766502a30d28f7054f689c8fdd9fe30eb19e9bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/apple/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111091819112503-13892%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T18%3A22%3A11Z&sr=b&sp=r&sig=zgnCADttRpDDqYIS6sq%2Be0t3Q627XVFuiYDUhiQHwGY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-09 18:40 UTC, opbld32 commented
Docs Build status updates of commit _[d05f5fe](https://github.com/namkedia/microsoft-graph-docs/commits/d05f5fec128d71c151e60f1b066d359b1cbe43d5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identitycontainer-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-list-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-5212ded41f97c87c582f945dcaf87c89-7a0c1c93)
[api-reference/v1.0/api/identitycontainer-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-fd999e0fb1be577c6e438a73e0aaddbe-7a0c1c93)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-7a0c1c93)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-7a0c1c93)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-7a0c1c93)
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/apple/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="5212ded41f97c87c582f945dcaf87c89-7a0c1c93"></a>
### [api-reference/v1.0/api/identitycontainer-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-list-identityproviders.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List identityProviders - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/b2xidentityuserflow-list-identityproviders.md(2,8), v1.0/api/identitycontainer-list-identityproviders.md(2,8), v1.0/api/identityprovider-list.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List identityProviders' is duplicated with other articles: 'v1.0/api/b2xidentityuserflow-list-identityproviders.md(10,1), v1.0/api/identitycontainer-list-identityproviders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fd999e0fb1be577c6e438a73e0aaddbe-7a0c1c93"></a>
### [api-reference/v1.0/api/identitycontainer-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-post-identityproviders.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identitycontainer-post-identityproviders.md(2,8), v1.0/api/identityprovider-post-identityproviders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 160, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="238ebdfe5651c522a8c5efad39d95a31-7a0c1c93"></a>
### [api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-delete.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-delete.md(2,8), v1.0/api/identityprovider-delete.md(2,8)'. Titles must be unique within a docset.`````

<a id="7b145057a9cf0793deaae89442f9d04c-7a0c1c93"></a>
### [api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-get.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-get.md(2,8), v1.0/api/identityprovider-get.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 181, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="ac63d51321a8d3e821c9bc7515e29f4c-7a0c1c93"></a>
### [api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-update.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-update.md(2,8), v1.0/api/identityprovider-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 135, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduser [...]

2021-11-09 18:53 UTC, opbld30 commented
Docs Build status updates of commit _[7b08d76](https://github.com/namkedia/microsoft-graph-docs/commits/7b08d7667ca63ec4abfa29614a447e5b6091758e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identitycontainer-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-list-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-5212ded41f97c87c582f945dcaf87c89-9e531138)
[api-reference/v1.0/api/identitycontainer-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-fd999e0fb1be577c6e438a73e0aaddbe-9e531138)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-9e531138)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-9e531138)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-9e531138)
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/apple/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="5212ded41f97c87c582f945dcaf87c89-9e531138"></a>
### [api-reference/v1.0/api/identitycontainer-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-list-identityproviders.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List identityProviders - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/b2xidentityuserflow-list-identityproviders.md(2,8), v1.0/api/identitycontainer-list-identityproviders.md(2,8), v1.0/api/identityprovider-list.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List identityProviders' is duplicated with other articles: 'v1.0/api/b2xidentityuserflow-list-identityproviders.md(10,1), v1.0/api/identitycontainer-list-identityproviders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fd999e0fb1be577c6e438a73e0aaddbe-9e531138"></a>
### [api-reference/v1.0/api/identitycontainer-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-post-identityproviders.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identitycontainer-post-identityproviders.md(2,8), v1.0/api/identityprovider-post-identityproviders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 160, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="238ebdfe5651c522a8c5efad39d95a31-9e531138"></a>
### [api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-delete.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-delete.md(2,8), v1.0/api/identityprovider-delete.md(2,8)'. Titles must be unique within a docset.`````

<a id="7b145057a9cf0793deaae89442f9d04c-9e531138"></a>
### [api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-get.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-get.md(2,8), v1.0/api/identityprovider-get.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 181, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="ac63d51321a8d3e821c9bc7515e29f4c-9e531138"></a>
### [api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-update.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-update.md(2,8), v1.0/api/identityprovider-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 135, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduser [...]

2021-11-09 18:56 UTC, opbld30 commented
Docs Build status updates of commit _[c7ed22f](https://github.com/namkedia/microsoft-graph-docs/commits/c7ed22fed7afcebcc3aaafd95d96cd90e3808d64)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identitycontainer-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-list-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-5212ded41f97c87c582f945dcaf87c89-6750b467)
[api-reference/v1.0/api/identitycontainer-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-fd999e0fb1be577c6e438a73e0aaddbe-6750b467)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-6750b467)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-6750b467)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-6750b467)
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/apple/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="5212ded41f97c87c582f945dcaf87c89-6750b467"></a>
### [api-reference/v1.0/api/identitycontainer-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-list-identityproviders.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List identityProviders - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/b2xidentityuserflow-list-identityproviders.md(2,8), v1.0/api/identitycontainer-list-identityproviders.md(2,8), v1.0/api/identityprovider-list.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List identityProviders' is duplicated with other articles: 'v1.0/api/b2xidentityuserflow-list-identityproviders.md(10,1), v1.0/api/identitycontainer-list-identityproviders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fd999e0fb1be577c6e438a73e0aaddbe-6750b467"></a>
### [api-reference/v1.0/api/identitycontainer-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-post-identityproviders.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identitycontainer-post-identityproviders.md(2,8), v1.0/api/identityprovider-post-identityproviders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 160, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="238ebdfe5651c522a8c5efad39d95a31-6750b467"></a>
### [api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-delete.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-delete.md(2,8), v1.0/api/identityprovider-delete.md(2,8)'. Titles must be unique within a docset.`````

<a id="7b145057a9cf0793deaae89442f9d04c-6750b467"></a>
### [api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-get.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-get.md(2,8), v1.0/api/identityprovider-get.md(2,8)'. Titles must be unique within a docset.`````

<a id="ac63d51321a8d3e821c9bc7515e29f4c-6750b467"></a>
### [api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-update.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-update.md(2,8), v1.0/api/identityprovider-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 135, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111091854549857-13892%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T18%3A56%3A29Z&sr=b&sp=r&sig=mXJJbpZkm [...]

2021-11-09 18:59 UTC, opbld34 commented
Docs Build status updates of commit _[c52ae5a](https://github.com/namkedia/microsoft-graph-docs/commits/c52ae5a3ae67eff9283a75ea95a52c506c07ae21)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identitycontainer-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-list-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-5212ded41f97c87c582f945dcaf87c89-690af742)
[api-reference/v1.0/api/identitycontainer-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-fd999e0fb1be577c6e438a73e0aaddbe-690af742)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-690af742)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-690af742)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-690af742)
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/apple/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="5212ded41f97c87c582f945dcaf87c89-690af742"></a>
### [api-reference/v1.0/api/identitycontainer-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-list-identityproviders.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List identityProviders - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/b2xidentityuserflow-list-identityproviders.md(2,8), v1.0/api/identitycontainer-list-identityproviders.md(2,8), v1.0/api/identityprovider-list.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List identityProviders' is duplicated with other articles: 'v1.0/api/b2xidentityuserflow-list-identityproviders.md(10,1), v1.0/api/identitycontainer-list-identityproviders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fd999e0fb1be577c6e438a73e0aaddbe-690af742"></a>
### [api-reference/v1.0/api/identitycontainer-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-post-identityproviders.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identitycontainer-post-identityproviders.md(2,8), v1.0/api/identityprovider-post-identityproviders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 160, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="238ebdfe5651c522a8c5efad39d95a31-690af742"></a>
### [api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-delete.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-delete.md(2,8), v1.0/api/identityprovider-delete.md(2,8)'. Titles must be unique within a docset.`````

<a id="7b145057a9cf0793deaae89442f9d04c-690af742"></a>
### [api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-get.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-get.md(2,8), v1.0/api/identityprovider-get.md(2,8)'. Titles must be unique within a docset.`````

<a id="ac63d51321a8d3e821c9bc7515e29f4c-690af742"></a>
### [api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-update.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-update.md(2,8), v1.0/api/identityprovider-update.md(2,8)'. Titles must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111091856082707-13892%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T18%3A59%3A04Z&sr=b&sp=r&sig=d9bI6wRYirUucbnS5Fc7aYwOQrrPSBQN%2BlHYsH1ijHI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https: [...]

2021-11-09 19:02 UTC, opbld34 commented
Docs Build status updates of commit _[57d141d](https://github.com/namkedia/microsoft-graph-docs/commits/57d141d1695d71e20a9f43de994ccb70293083f3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identitycontainer-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-list-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-5212ded41f97c87c582f945dcaf87c89-85380ba8)
[api-reference/v1.0/api/identitycontainer-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-fd999e0fb1be577c6e438a73e0aaddbe-85380ba8)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-85380ba8)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-85380ba8)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-85380ba8)
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/apple/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="5212ded41f97c87c582f945dcaf87c89-85380ba8"></a>
### [api-reference/v1.0/api/identitycontainer-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-list-identityproviders.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List identityProviders - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/b2xidentityuserflow-list-identityproviders.md(2,8), v1.0/api/identitycontainer-list-identityproviders.md(2,8), v1.0/api/identityprovider-list.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List identityProviders' is duplicated with other articles: 'v1.0/api/b2xidentityuserflow-list-identityproviders.md(10,1), v1.0/api/identitycontainer-list-identityproviders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fd999e0fb1be577c6e438a73e0aaddbe-85380ba8"></a>
### [api-reference/v1.0/api/identitycontainer-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-post-identityproviders.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identitycontainer-post-identityproviders.md(2,8), v1.0/api/identityprovider-post-identityproviders.md(2,8)'. Titles must be unique within a docset.`````

<a id="238ebdfe5651c522a8c5efad39d95a31-85380ba8"></a>
### [api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-delete.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-delete.md(2,8), v1.0/api/identityprovider-delete.md(2,8)'. Titles must be unique within a docset.`````

<a id="7b145057a9cf0793deaae89442f9d04c-85380ba8"></a>
### [api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-get.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-get.md(2,8), v1.0/api/identityprovider-get.md(2,8)'. Titles must be unique within a docset.`````

<a id="ac63d51321a8d3e821c9bc7515e29f4c-85380ba8"></a>
### [api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-update.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-update.md(2,8), v1.0/api/identityprovider-update.md(2,8)'. Titles must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111091900589429-13892%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T19%3A02%3A35Z&sr=b&sp=r&sig=fzSb0Yl9frRHEmhIpgdvGni3cJ4U4JexebppRCz2Y2M%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For  [...]

2021-11-10 03:28 UTC, opbld30 commented
Docs Build status updates of commit _[f7320a0](https://github.com/namkedia/microsoft-graph-docs/commits/f7320a06b2c859168c41ccf60aed3fdfa0658d36)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identitycontainer-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-list-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-5212ded41f97c87c582f945dcaf87c89-a6943ab0)
[api-reference/v1.0/api/identitycontainer-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-fd999e0fb1be577c6e438a73e0aaddbe-a6943ab0)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-a6943ab0)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-a6943ab0)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-a6943ab0)
[api-reference/v1.0/resources/applemanagedidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/applemanagedidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applemanagedidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identitycontainer-list-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13892) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/apple/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="5212ded41f97c87c582f945dcaf87c89-a6943ab0"></a>
### [api-reference/v1.0/api/identitycontainer-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-list-identityproviders.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List identityProviders - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/b2xidentityuserflow-list-identityproviders.md(2,8), v1.0/api/identitycontainer-list-identityproviders.md(2,8), v1.0/api/identityprovider-list.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List identityProviders' is duplicated with other articles: 'v1.0/api/b2xidentityuserflow-list-identityproviders.md(10,1), v1.0/api/identitycontainer-list-identityproviders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fd999e0fb1be577c6e438a73e0aaddbe-a6943ab0"></a>
### [api-reference/v1.0/api/identitycontainer-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identitycontainer-post-identityproviders.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identitycontainer-post-identityproviders.md(2,8), v1.0/api/identityprovider-post-identityproviders.md(2,8)'. Titles must be unique within a docset.`````

<a id="238ebdfe5651c522a8c5efad39d95a31-a6943ab0"></a>
### [api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-delete.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-delete.md(2,8), v1.0/api/identityprovider-delete.md(2,8)'. Titles must be unique within a docset.`````

<a id="7b145057a9cf0793deaae89442f9d04c-a6943ab0"></a>
### [api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-get.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-get.md(2,8), v1.0/api/identityprovider-get.md(2,8)'. Titles must be unique within a docset.`````

<a id="ac63d51321a8d3e821c9bc7515e29f4c-a6943ab0"></a>
### [api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/apple/api-reference/v1.0/api/identityproviderbase-update.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-update.md(2,8), v1.0/api/identityprovider-update.md(2,8)'. Titles must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111100326208412-13892%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-11T03%3A28%3A38Z&sr=b&sp=r&sig=O%2Fq1lY%2BKG%2FrxCAkGwq7B9r1o7oeU5oXpnML4odTXA%2Bg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build rep [...]

2021-11-10 03:30 UTC, merged