Add meeting details to chat
microsoftgraph/microsoft-graph-docs pull request #13893
Opened 2021-08-18 23:13 UTC by jessiechan27

2021-08-18 23:14 UTC, opbld30 commented
Docs Build status updates of commit _[d7f204e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d7f204e1ef4cdf344f0044c30762643a7dd3681f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/teamworkonlinemeetinginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/teamworkonlinemeetinginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkonlinemeetinginfo?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/v1.0/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/v1.0/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-1.0&branch=pr-en-us-13893) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108182313278843-13893%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=JyqI95TK2WrK4HUDrQYbpGiC2LjWyGWvBCZDujORHpE%3D&st=2021-08-18T23%3A09%3A53Z&se=2021-09-18T23%3A14%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-18 23:28 UTC, opbld31 commented
Docs Build status updates of commit _[f88f23c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f88f23cccdc1c4fed7c8d7efb939031bce4fdfed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/teamworkonlinemeetinginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/teamworkonlinemeetinginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkonlinemeetinginfo?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/v1.0/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/v1.0/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-1.0&branch=pr-en-us-13893) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108182327045611-13893%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=OS8OVBUEabpoPxid2t%2Fl16%2F6kEJ%2FmH3TwfX427DQppo%3D&st=2021-08-18T23%3A23%3A55Z&se=2021-09-18T23%3A28%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-19 18:19 UTC, jessiechan27 commented on api-reference/beta/api/chat-get.md
> +    "webUrl": "https://teams.microsoft.com/l/chat/19%3Ad74fc2ed-cb0e-4288-a219-b5c71abaf2aa_8c0a1a67-50ce-4114-bb6c-da9c5dbcf6ca@unq.gbl.spaces/0?tenantId=b33cbe9f-8ebe-4f2a-912b-7e2a427f477f"
the webUrl does contain chat id within the URL, but the webUrl also contains the teams URL, tenant id and an index to a message in the chat. They're both necessary

2021-08-24 19:24 UTC, opbld32 commented
Docs Build status updates of commit _[2f5d381](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2f5d381d4b82211a74b30ea280df1bb24e5f43ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/teamworkonlinemeetinginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/teamworkonlinemeetinginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkonlinemeetinginfo?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/v1.0/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/v1.0/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-1.0&branch=pr-en-us-13893) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108241923017422-13893%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=vawdLJirg6qGIktPfZI9vG6T%2Fpmcu2gQpJZLR0vRvdA%3D&st=2021-08-24T19%3A19%3A39Z&se=2021-09-24T19%3A24%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-24 19:36 UTC, AkJo commented on api-reference/beta/api/chat-get.md
> +### Example 4: Get a meeting chat
Get the meeting details of a chat.

2021-08-24 19:38 UTC, AkJo commented on api-reference/beta/resources/chat.md
> +| tenantId| String | The tenant identifier. Read-only.|
The identifier of the tenant in which the chat was created.

2021-08-24 19:42 UTC, AkJo commented on api-reference/beta/resources/teamworkonlinemeetinginfo.md
> +- [chat](chat.md)
Isnt the casing wrong?

2021-08-24 19:48 UTC, opbld31 commented
Docs Build status updates of commit _[324eda6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/324eda60c34692ce29035eb6145ea53c54f29784)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/teamworkonlinemeetinginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/teamworkonlinemeetinginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkonlinemeetinginfo?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/v1.0/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/v1.0/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-1.0&branch=pr-en-us-13893) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108241946310784-13893%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=LQod9i1E1ccPu1avV4uCDj1s4ItBkC3rtH50UejA9dE%3D&st=2021-08-24T19%3A43%3A02Z&se=2021-09-24T19%3A48%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-31 18:54 UTC, AkJo commented on api-reference/beta/resources/chat.md
> +| onlineMeetingInfo | [teamworkOnlineMeetingInfo](../resources/teamworkonlinemeetinginfo.md) | Details of the online meeting if the chat is associated with an online meeting. Read-only.|
@Lauragra for wordsmithing.

2021-08-31 18:55 UTC, AkJo approved these changes

2021-08-31 19:00 UTC, opbld34 commented
Docs Build status updates of commit _[c9e6851](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9e68514fd975b467d937f3846330266963ad7ed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/teamworkonlinemeetinginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/teamworkonlinemeetinginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkonlinemeetinginfo?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/v1.0/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/v1.0/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-1.0&branch=pr-en-us-13893) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108311858261562-13893%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=O%2FmJwFS%2FsaJOIiGxiZHV8OVaSFAzZeE4LY%2FE0cuzCmM%3D&st=2021-08-31T18%3A55%3A06Z&se=2021-10-01T19%3A00%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-31 20:47 UTC, JarbasHorst requested changes

2021-08-31 20:47 UTC, JarbasHorst commented on api-reference/beta/resources/chat.md
> +| onlineMeetingInfo | [teamworkOnlineMeetingInfo](../resources/teamworkonlinemeetinginfo.md) | Details of the online meeting if the chat is associated with an online meeting. Read-only.|
I'm not Laura but here my suggestion:

- Represents details about an online meeting. If the chat isn't associated with an online meeting, the property is empty.

2021-08-31 20:47 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkhostedcontent.md
> -  "@odata.type": "#microsoft.graph.teamworkHostedContent",
Why do you want to remove the @odata.type property from the JSON representation?

2021-08-31 20:47 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkonlinemeetinginfo.md
> +description: "Represents details about an online Teams meeting"
For clarity, please add Teams after meeting and replace Teams with Microsoft Teams. Also, add a period at the end of the sentence. Suggested revision:

- Represents details about an online meeting in Microsoft Teams.

2021-08-31 20:47 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkonlinemeetinginfo.md
> +Represents details about an online Teams meeting.
For clarity, please add Teams after meeting and replace Teams with Microsoft Teams. Suggested revision:

- Represents details about an online meeting in Microsoft Teams.

2021-08-31 20:47 UTC, JarbasHorst commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "ApiChange": "ComplexType",
ComplexType is not on the list of approved values for ApiChange. Please change this to "Resource".

2021-08-31 20:47 UTC, JarbasHorst commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Description": "Added the **onlineMeetingInfo** property to [chat](https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta) resource.",
Articles help readers and translation software identify the nouns and modifiers in a sentence. Please, add the before chat. Suggested revision:

- ...property to the [chat]...

2021-08-31 20:47 UTC, JarbasHorst commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Description": "Added the **tenantId** property to [chat](https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta) resource.",
Articles help readers and translation software identify the nouns and modifiers in a sentence. Please, add the before chat. Suggested revision:

- ...property to the [chat]...

2021-08-31 20:47 UTC, JarbasHorst commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "Id": "1c5850b2-105c-4d50-a378-ac9bb52a36c7",
Within a changelog record, all Id properties must have the same value. Please, replace 1c5850b2-105c-4d50-a378-ac9bb52a36c7 with ef72d160-05bc-4f45-9ae9-2bdb84dd8c07

2021-08-31 20:47 UTC, JarbasHorst commented on api-reference/beta/api/chat-get.md
> +### Example 4: Get the meeting details of a chat associated with a Teams meeting
For clarity, I recommend you to add Teams after meeting and replace Teams with Microsoft Teams. Suggested revision:

- ...with a meeting in Microsoft Teams

2021-08-31 21:41 UTC, jessiechan27 commented on api-reference/beta/resources/teamworkhostedcontent.md
> -  "@odata.type": "#microsoft.graph.teamworkHostedContent",
it wasn't supposed to be there originally. I was looking at similar files and trying to make them consistent

2021-08-31 21:52 UTC, opbld34 commented
Docs Build status updates of commit _[0e3d9ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e3d9ae1a3f6008913dffd5ff8396d01ea225402)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/api/chat-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) | [Details](#user-content-3aac6cd3f7ef96a5e124ccf1b0250d1c-f04009b0)
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/teamworkonlinemeetinginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/teamworkonlinemeetinginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkonlinemeetinginfo?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/v1.0/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/v1.0/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-1.0&branch=pr-en-us-13893) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="3aac6cd3f7ef96a5e124ccf1b0250d1c-f04009b0"></a>
### [api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/api/chat-get.md)
 - **Line 2, Column 8**: **[Suggestion-title-bad-length]** `````String 'title' is too short: 8 characters. Length should be >= 10.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108312150598693-13893%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=DEq2dB0RH9syd%2FiKP49m0KC9CZZVJGet2%2Fx81aFE7XA%3D&st=2021-08-31T21%3A47%3A44Z&se=2021-10-01T21%3A52%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-01 00:20 UTC, Lauragra approved these changes

2021-09-01 00:22 UTC, opbld30 commented
Docs Build status updates of commit _[c86a97f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c86a97fc8df50116cb295d11ab8662e59ba3e1e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/api/chat-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) | [Details](#user-content-3aac6cd3f7ef96a5e124ccf1b0250d1c-20c0a1ee)
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/beta/resources/teamworkonlinemeetinginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/resources/teamworkonlinemeetinginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkonlinemeetinginfo?view=graph-rest-beta&branch=pr-en-us-13893) (graph-rest-beta) |
[api-reference/v1.0/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/v1.0/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-1.0&branch=pr-en-us-13893) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="3aac6cd3f7ef96a5e124ccf1b0250d1c-20c0a1ee"></a>
### [api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-meetinginfo/api-reference/beta/api/chat-get.md)
 - **Line 2, Column 8**: **[Suggestion-title-bad-length]** `````String 'title' is too short: 8 characters. Length should be >= 10.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109010020190210-13893%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=1Oofzm9chY%2FrnYMfegypMNlqIzbCvV6s4HiYXN8PHGY%3D&st=2021-09-01T00%3A17%3A18Z&se=2021-10-02T00%3A22%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-01 00:25 UTC, merged