Alamaral acs index
microsoftgraph/microsoft-graph-docs pull request #13910
Opened 2021-08-19 20:23 UTC by AllisonAm

2021-08-19 20:25 UTC, opbld32 commented
Docs Build status updates of commit _[10add72](https://github.com/microsoftgraph/microsoft-graph-docs/commits/10add728c67da615b15503c4ed587f1714e9f831)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-2fe3b447)
[api-reference/beta/resources/redirecturisettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/redirecturisettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/redirecturisettings?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[api-reference/beta/resources/webapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/webapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webapplication?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-2fe3b447"></a>
### [api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/application.md)
 - **Line 70, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108192023598561-13910%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=MNZZPQ%2BukYK%2Bul4rSlNEgcY88ZBZM24AWlcCua%2Fbpy0%3D&st=2021-08-19T20%3A20%3A31Z&se=2021-09-19T20%3A25%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-23 17:48 UTC, FaithOmbongi requested changes

2021-08-23 17:48 UTC, FaithOmbongi commented on api-reference/beta/resources/application.md
> +|defaultRedirectUri|string|Default redirect URI. If specified, Azure AD is going to send the token to that redirect URI if there is no explicit redirect URI in the sign-in request for SAML and OIDC f
```suggestion
|defaultRedirectUri|String|The default redirect URI. If specified and there is no explicit redirect URI in the sign-in request for SAML and OIDC flows, Azure AD sends the token to this redirect URI. Azure AD also sends the token to this default URI in SAML IdP-initiated single sign-on. The value must match one of the configured redirect URIs for the application.|
```

2021-08-23 17:48 UTC, FaithOmbongi commented on api-reference/beta/resources/redirecturisettings.md
> +ms.prod: "microsoft-identity-platform"
```suggestion
ms.prod: "applications"
```

2021-08-23 17:48 UTC, FaithOmbongi commented on api-reference/beta/resources/redirecturisettings.md
> +author: "davidmu"
```suggestion
author: "sureshja"
```

2021-08-23 17:48 UTC, FaithOmbongi commented on api-reference/beta/resources/redirecturisettings.md
> +|`index`|int|Identifies specific URI with in the redirectURIs collection in SAML SSO flows. Defaults to null. The index is unique across all the returnUris for the application.|
Confirm: Did you mean **redirectUris** instead of **returnURIs**? I can't find the property with the name returnURI in the metadata.
```suggestion
|index|Int32|Identifies the specific URI within the redirectURIs collection in SAML SSO flows. Defaults to `null`. The index is unique across all the redirectUris for the application.|
```

2021-08-23 17:48 UTC, FaithOmbongi commented on api-reference/beta/resources/redirecturisettings.md
> +```
```suggestion
``` json
{
  "@odata.type": "#microsoft.graph.redirectUriSettings",
  "uri": "String",
  "index": "Integer"
}
```
```

2021-08-23 17:48 UTC, FaithOmbongi commented on api-reference/beta/resources/redirecturisettings.md
> +-->
```suggestion
```

2021-08-23 17:48 UTC, FaithOmbongi commented on api-reference/beta/resources/webapplication.md
> +|redirectUriSettings| [redirectUriSettings](redirecturisettings.md) | Specifies the index of the URLs where user tokens are sent for sign-in. This is only valid for applications using SAML.|
```suggestion
|redirectUriSettings| [redirectUriSettings](redirecturisettings.md) collection | Specifies the index of the URLs where user tokens are sent for sign-in. This is only valid for applications using SAML.|
```

2021-08-23 17:48 UTC, FaithOmbongi commented on api-reference/beta/resources/webapplication.md
> +  "redirectUriSettings":{"@odata.type": "microsoft.graph.redirectUriSettings"}
Corrected to a collection
```suggestion
  "redirectUriSettings": [
    {
      "@odata.type": "microsoft.graph.redirectUriSettings"
    }
  ],
```

2021-08-23 17:48 UTC, FaithOmbongi commented on api-reference/beta/resources/redirecturisettings.md
> +Specifies the index of the URLs where user tokens are sent for sign-in. This is only valid for applications using SAML.
Your property description in the preceding file says that this applies to OIDC too?
```suggestion
Specifies the index of the URLs where user tokens are sent for sign-in. This is only valid for applications using SAML.
```

2021-08-23 17:48 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +    },
Same changelog id's within your ChangeList.
Kindly follow the changelog guidance.
```suggestion
         "Id": "5ac1044f-93d1-4fe7-aa57-ce514720bf27",
         "ApiChange": "Property",
         "ChangedApiName": "defaultRedirectUri",
         "ChangeType": "Addition",
         "Description": "Added the **defaultRedirectUri** property to the [application](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta) resource.",
         "Target": "application"
       },
       {
        "Id": "5ac1044f-93d1-4fe7-aa57-ce514720bf27",
        "ApiChange": "Resource",
        "ChangedApiName": "redirectUriSettings",
        "ChangeType": "Addition",
        "Description": "Added the [redirectUriSettings](https://docs.microsoft.com/en-us/graph/api/resources/redirecturisettings?view=graph-rest-beta) resource.",
        "Target": "redirectUriSettings"
       },
       {
        "Id": "5ac1044f-93d1-4fe7-aa57-ce514720bf27",
        "ApiChange": "Property",
        "ChangedApiName": "redirectUriSettings",
        "ChangeType": "Addition",
        "Description": "Added the **redirectUriSettings** property to the [webapplication](https://docs.microsoft.com/en-us/graph/api/resources/webapplication?view=graph-rest-beta) resource.",
        "Target": "webApplication"
      }
      ],
      "Id": "5ac1044f-93d1-4fe7-aa57-ce514720bf27",
      "Cloud": "prd",
      "Version": "beta",
      "CreatedDateTime": "2021-08-17T05:30:27Z",
      "WorkloadArea": "Applications",
      "SubArea": ""
    },
```

2021-08-23 17:48 UTC, FaithOmbongi commented on api-reference/beta/resources/redirecturisettings.md
> +| `uri` | String | Specifies the URI that tokens are sent to. |
```suggestion
| uri | String | Specifies the URI that tokens are sent to. |
```

2021-09-01 17:13 UTC, AllisonAm commented on api-reference/beta/resources/redirecturisettings.md
> +Specifies the index of the URLs where user tokens are sent for sign-in. This is only valid for applications using SAML.
So the default redirect URI is, but the ACS index isn't used in OIDC scenarios.

2021-09-01 17:14 UTC, jasonjoh commented
Docs Build status updates of commit _[e1082d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1082d2ef13c64560e713a590ba2dc8c701938e3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d85ceabb)

<a id="d85ceabb"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109011713575882-13910%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=rtQx6Dr4XSJcokiIE1n2eJYTfa2ipeqUqeTAQmXyLeI%3D&st=2021-09-01T17%3A09%3A22Z&se=2021-10-02T17%3A14%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 19:31 UTC, jasonjoh commented
Docs Build status updates of commit _[a2217e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2217e432cabc2d381e646fd9a2d6d0e0f2a9146)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/redirecturisettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/redirecturisettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/redirecturisettings?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) | [Details](#user-content-3c5e6a68b703ae398d7371696c90d80c-0979f8b0)
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-0979f8b0)
[api-reference/beta/resources/webapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/webapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webapplication?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="3c5e6a68b703ae398d7371696c90d80c-0979f8b0"></a>
### [api-reference/beta/resources/redirecturisettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/redirecturisettings.md)
 - **Line 36, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="ddb7235fcab3930f5792589d50914b89-0979f8b0"></a>
### [api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/application.md)
 - **Line 70, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021929497378-13910%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=HynsuqahRKGlmi3RyBikZyfghiEB0bw3FkUJnd4hqc4%3D&st=2021-09-02T19%3A26%3A27Z&se=2021-10-03T19%3A31%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 20:13 UTC, jasonjoh commented
Docs Build status updates of commit _[76b4e08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/76b4e08cfce5eba3ced7592b078fa7e5400f804a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-59c3b115)
[api-reference/beta/resources/redirecturisettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/redirecturisettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/redirecturisettings?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[api-reference/beta/resources/webapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/webapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webapplication?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-59c3b115"></a>
### [api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/application.md)
 - **Line 70, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109022010582624-13910%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=qXUs5mG61n1vFvpOC85VbxvQqYGZ%2FPBIbP0idx3rqyU%3D&st=2021-09-02T20%3A08%3A31Z&se=2021-10-03T20%3A13%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 20:15 UTC, jasonjoh commented
Docs Build status updates of commit _[01b0b75](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01b0b7527441663a5ac1d33e8743ef4ae19d340a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[api-reference/beta/resources/redirecturisettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/redirecturisettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/redirecturisettings?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[api-reference/beta/resources/webapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/webapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webapplication?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109022013347528-13910%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=5n40lInN4OlFMAkE1TN63xf3EXCqBdoav9bfWiDhY4w%3D&st=2021-09-02T20%3A10%3A35Z&se=2021-10-03T20%3A15%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 21:17 UTC, jasonjoh commented
Docs Build status updates of commit _[8c8d012](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c8d012c5182a5f32f7210d37947606610d367ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[api-reference/beta/resources/redirecturisettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/redirecturisettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/redirecturisettings?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[api-reference/beta/resources/webapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/webapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webapplication?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109022116040179-13910%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Rsk3bQdWIH6LVRw8IXPuRwlDNq%2F6f2dIkGnAxuEBsL8%3D&st=2021-09-02T21%3A12%3A48Z&se=2021-10-03T21%3A17%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 15:02 UTC, FaithOmbongi approved these changes

2021-09-21 23:47 UTC, opbld34 commented
Docs Build status updates of commit _[3901418](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39014188db86dd51ab80bc1a358c1df47bc300cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[api-reference/beta/resources/redirecturisettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/redirecturisettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/redirecturisettings?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[api-reference/beta/resources/webapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/webapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webapplication?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109212345348668-13910%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-22T23%3A47%3A42Z&sr=b&sp=r&sig=8uO1LAx2Pujxzh4%2BDuQvXS4c0HnlQb2iUWMlL8rXKgs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 00:22 UTC, opbld33 commented
Docs Build status updates of commit _[f6e4cb2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6e4cb29940f216c979e9d774cf713922fd1e333)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[api-reference/beta/resources/redirecturisettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/redirecturisettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/redirecturisettings?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[api-reference/beta/resources/webapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/api-reference/beta/resources/webapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webapplication?view=graph-rest-beta&branch=pr-en-us-13910) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-ACSIndex/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110010020113784-13910%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T00%3A22%3A01Z&sr=b&sp=r&sig=EF2tDpweFyYHeMH%2FqUxBxm69mtmwMPwN%2Bj8PI3L%2FB%2BI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 03:42 UTC, merged