[Azure AD] [ELM] added attribute resource docs
microsoftgraph/microsoft-graph-docs pull request #13931
Opened 2021-08-21 02:26 UTC by ajburnle

2021-08-21 02:28 UTC, opbld34 commented
Docs Build status updates of commit _[b6f6e99](https://github.com/ajburnle/microsoft-graph-docs/commits/b6f6e992d65a165e8cab853ff6975c93f4de426f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageattribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-c20b36a11a530da30e9e410f2e31dfa6-695db36b)
[api-reference/beta/resources/accesspackageattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageattributedestination.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-71f1caed4e51bf58ac4e5388d3435326-695db36b)
[api-reference/beta/resources/accesspackageattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageattributequestion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-2d815c85dda925c21653d5cee25c70fa-695db36b)
[api-reference/beta/resources/accesspackageattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageattributesource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-0e72e350d2995c7cc8dbe436d81a6559-695db36b)
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-dbcfdf574adba05cd196e878b72cceae-695db36b)

<a id="c20b36a11a530da30e9e410f2e31dfa6-695db36b"></a>
### [api-reference/beta/resources/accesspackageattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageattribute.md)
 - **Line 16, Column 54**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '..resources/accesspackage.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageattribute.md(3,14)', 'beta/resources/accesspackageattributesource.md(3,14)'.`````

<a id="71f1caed4e51bf58ac4e5388d3435326-695db36b"></a>
### [api-reference/beta/resources/accesspackageattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageattributedestination.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Governance'.`````

<a id="2d815c85dda925c21653d5cee25c70fa-695db36b"></a>
### [api-reference/beta/resources/accesspackageattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageattributequestion.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Governance'.`````

<a id="0e72e350d2995c7cc8dbe436d81a6559-695db36b"></a>
### [api-reference/beta/resources/accesspackageattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageattributesource.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Governance'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageattribute.md(3,14)', 'beta/resources/accesspackageattributesource.md(3,14)'.`````

<a id="dbcfdf574adba05cd196e878b72cceae-695db36b"></a>
### [api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Governance'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108210226406658-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=aHUoTiJ1%2FKvGpMCO0MTqll3VjgsmAjisWWIsgt6V7U4%3D&st=2021-08-21T02%3A23%3A34Z&se=2021-09-21T02%3A28%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-25 00:32 UTC, opbld34 commented
Docs Build status updates of commit _[be2c321](https://github.com/ajburnle/microsoft-graph-docs/commits/be2c321be1edf6aede13e6113dc43973883aa66f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-6c07a7e9)
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-f469847715c5cabc86f06b0c0a623b9a-6c07a7e9)
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-7709820e2f31c84019c49b693b7ef6b0-6c07a7e9)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-6c07a7e9)
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-dbcfdf574adba05cd196e878b72cceae-6c07a7e9)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceattributes-post](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourceattributes-post) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-6c07a7e9"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 16, Column 54**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '..resources/accesspackage.md'.`````
 - **Line 21, Column 23**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackageattributedestination.md'.`````
 - **Line 23, Column 18**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackageattributesource.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="f469847715c5cabc86f06b0c0a623b9a-6c07a7e9"></a>
### [api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Governance'.`````

<a id="7709820e2f31c84019c49b693b7ef6b0-6c07a7e9"></a>
### [api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Governance'.`````
 - **Line 18, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackageattributesource.md'.`````

<a id="051358bc4656d01c44251401d620e1c9-6c07a7e9"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Governance'.`````
 - **Line 16, Column 46**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accesspackageattribute.md'.`````
 - **Line 16, Column 198**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accesspackageattributequestion.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="dbcfdf574adba05cd196e878b72cceae-6c07a7e9"></a>
### [api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Governance'.`````
 - **Line 16, Column 144**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]* [...]

2021-09-10 23:45 UTC, opbld32 commented
Docs Build status updates of commit _[bd2b2e0](https://github.com/ajburnle/microsoft-graph-docs/commits/bd2b2e02335f7b52269edc29adaead5907895fad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-4d24494328fcf68a761c449f360709eb-b8bcec16)
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-b8bcec16)
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-f469847715c5cabc86f06b0c0a623b9a-b8bcec16)
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-7709820e2f31c84019c49b693b7ef6b0-b8bcec16)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-b8bcec16)
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-dbcfdf574adba05cd196e878b72cceae-b8bcec16)
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="4d24494328fcf68a761c449f360709eb-b8bcec16"></a>
### [api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md)
 - **Line 145, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="39ec399d6cd6d3b2c67d69060eff28a0-b8bcec16"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 16, Column 54**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '..resources/accesspackage.md'.`````
 - **Line 21, Column 23**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackageattributedestination.md'.`````
 - **Line 23, Column 18**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackageattributesource.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="f469847715c5cabc86f06b0c0a623b9a-b8bcec16"></a>
### [api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Governance'.`````

<a id="7709820e2f31c84019c49b693b7ef6b0-b8bcec16"></a>
### [api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Governance'.`````
 - **Line 18, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackageattributesource.md'.`````

<a id="051358bc4656d01c44251401d620e1c9-b8bcec16"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagere [...]

2021-09-11 00:45 UTC, NelsonBlakeN commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +    "requestType": "AdminAdd",
On second thought, let's remove this line. It isn't required, and isn't included in the other example.

2021-09-11 00:51 UTC, NelsonBlakeN commented on api-reference/beta/resources/accesspackageresourceattributedestination.md
> +description: "Child of accessPackageQuestion that is a complex type of the destination of an access package attribute."
accessPackageResourceAttributeDestination is a property of accessPackageQuestion, does that mean that it is described as a child?

2021-09-11 00:54 UTC, NelsonBlakeN commented on api-reference/beta/resources/accesspackageresourceattributedestination.md
> +A child of **accessPackageQuestion** that is a complex type of the destination of an access package attribute. The actual destination will be a subtype of this complex type. Inherits from [accessPack
Similar to the above comment, accessPackageResourceAttributeDestination doesn't inherit from accessPackageQuestion

2021-09-11 00:56 UTC, NelsonBlakeN commented on api-reference/beta/resources/accesspackageresourceattributequestion.md
> +## Example 2: Get accessPackagePolicy
Should this go in the accesspackageassignmentpolicy doc instead?

2021-09-13 22:34 UTC, opbld32 commented
Docs Build status updates of commit _[2b68d36](https://github.com/ajburnle/microsoft-graph-docs/commits/2b68d36d46e7b40ef66a1724121c37e277bc907f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-7709820e2f31c84019c49b693b7ef6b0-a354fd3c)
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-a354fd3c)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-a354fd3c)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="7709820e2f31c84019c49b693b7ef6b0-a354fd3c"></a>
### [api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Governance'.`````
 - **Line 18, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackageattributesource.md'.`````

<a id="39ec399d6cd6d3b2c67d69060eff28a0-a354fd3c"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-a354fd3c"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109132232008669-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=8v6OZbRAe23V1%2FT%2FBJZ2DCZWE%2FyLAiaJTVCT6m2hB1o%3D&st=2021-09-13T22%3A29%3A13Z&se=2021-10-14T22%3A34%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

 [...]

2021-09-14 00:12 UTC, ajburnle commented on api-reference/beta/resources/accesspackageresourceattributequestion.md
> +## Example 2: Get accessPackagePolicy
I removed this. It wasn't one of the examples in the latest note

2021-09-14 00:14 UTC, opbld30 commented
Docs Build status updates of commit _[1ef1449](https://github.com/ajburnle/microsoft-graph-docs/commits/1ef1449ddd4c0af5160435fc9834f9bd0b0a5781)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-7709820e2f31c84019c49b693b7ef6b0-1fb161fe)
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-1fb161fe)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-1fb161fe)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="7709820e2f31c84019c49b693b7ef6b0-1fb161fe"></a>
### [api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md)
 - **Line 18, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackageattributesource.md'.`````

<a id="39ec399d6cd6d3b2c67d69060eff28a0-1fb161fe"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-1fb161fe"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140012554000-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=3H4fuy0fHKrOZHzjfNSvmconSURwbanehXZowQ4SMcA%3D&st=2021-09-14T00%3A09%3A25Z&se=2021-10-15T00%3A14%3A25Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.co [...]

2021-09-14 00:18 UTC, opbld31 commented
Docs Build status updates of commit _[6984763](https://github.com/ajburnle/microsoft-graph-docs/commits/69847637d072e186fbc499dcd0099ac67b6f801a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-470e3166)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-470e3166)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-470e3166"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-470e3166"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140016189690-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=8dsibmh%2FcvL3Qm0EOLtMbWvZ9KAATUkPZSHR7vnUG68%3D&st=2021-09-14T00%3A13%3A02Z&se=2021-10-15T00%3A18%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 00:29 UTC, opbld33 commented
Docs Build status updates of commit _[6c913ef](https://github.com/ajburnle/microsoft-graph-docs/commits/6c913ef8da1866df333858669e4b49f77cd45b62)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-c54c0315)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-c54c0315)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-c54c0315"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-c54c0315"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140028130989-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=nArxK558r50dEae5ZEJjgX5ZlEts82YcuOAsZB3Kcp0%3D&st=2021-09-14T00%3A24%3A48Z&se=2021-10-15T00%3A29%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 05:59 UTC, opbld30 commented
Docs Build status updates of commit _[550d294](https://github.com/ajburnle/microsoft-graph-docs/commits/550d294565078332039654062b857f70e7b094a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-e747741d)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-e747741d)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-e747741d"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-e747741d"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140557237443-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=vD2avFW%2FW4T3MMsLhyB7jHRhC5BpX9zrOMUW56ZNniQ%3D&st=2021-09-14T05%3A54%3A06Z&se=2021-10-15T05%3A59%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 06:05 UTC, opbld34 commented
Docs Build status updates of commit _[58d3c36](https://github.com/ajburnle/microsoft-graph-docs/commits/58d3c3699f7d09cf2e2c6a23a3169c8e313737af)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-766e1c76)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-766e1c76)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-766e1c76"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-766e1c76"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140604162266-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=%2FcXlCeOp%2F0Rm9dgfK88Hhys4pn3%2FMvMeOsxJZehxOW8%3D&st=2021-09-14T06%3A00%3A54Z&se=2021-10-15T06%3A05%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 06:14 UTC, opbld33 commented
Docs Build status updates of commit _[c37dabc](https://github.com/ajburnle/microsoft-graph-docs/commits/c37dabc2f4f1c8d9330e13398f75a25832739ffe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-ad202fb2)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-ad202fb2)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-ad202fb2"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-ad202fb2"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140612541631-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=M2Ei%2BqKIW7916uiek8lbYoGbUPcx9c7Akod34urtCNE%3D&st=2021-09-14T06%3A09%3A25Z&se=2021-10-15T06%3A14%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 06:39 UTC, opbld31 commented
Docs Build status updates of commit _[0288fe3](https://github.com/ajburnle/microsoft-graph-docs/commits/0288fe352ba05a4b1c67a0565b6aa1a345002434)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-d6bc4eaf)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-d6bc4eaf)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-d6bc4eaf"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-d6bc4eaf"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140638076188-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=xRM7dpjzgFpT45PsVh0BO8GT7E19F32AZLN228%2BJax0%3D&st=2021-09-14T06%3A34%3A49Z&se=2021-10-15T06%3A39%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 06:51 UTC, opbld32 commented
Docs Build status updates of commit _[a9032d9](https://github.com/ajburnle/microsoft-graph-docs/commits/a9032d9cbc0b95644752c4daa58bbcc3d6cf5cd7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-658d7f02)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-658d7f02)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-658d7f02"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-658d7f02"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140650151601-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=ETQjv7x%2Fk%2FMXYHwYsZI%2F6MOc57mfFg8tsRRA1%2BIFprU%3D&st=2021-09-14T06%3A46%3A52Z&se=2021-10-15T06%3A51%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 07:09 UTC, opbld32 commented
Docs Build status updates of commit _[fca32d9](https://github.com/ajburnle/microsoft-graph-docs/commits/fca32d99d1974f3849a4a4319218398c542c128a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-29ab7263)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-29ab7263)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-29ab7263"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-29ab7263"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140707283993-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=ILddp3FfIPxLb7PL86ofxwonFiNduZB7P%2BBxH44TA9s%3D&st=2021-09-14T07%3A04%3A02Z&se=2021-10-15T07%3A09%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 07:12 UTC, opbld31 commented
Docs Build status updates of commit _[15acd6f](https://github.com/ajburnle/microsoft-graph-docs/commits/15acd6f12711ce4d65769c08058ccc4f3b5a523a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-1186405b)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-1186405b)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-1186405b"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-1186405b"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140710096022-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=LELqpvWcLSAM9h8MUm5WnriEyzSHEEzQg68Wt5acVSg%3D&st=2021-09-14T07%3A07%3A12Z&se=2021-10-15T07%3A12%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 08:06 UTC, opbld30 commented
Docs Build status updates of commit _[15acd6f](https://github.com/ajburnle/microsoft-graph-docs/commits/15acd6f12711ce4d65769c08058ccc4f3b5a523a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-00887800)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-00887800)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-00887800"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-00887800"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140804222834-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=0Isp2zYaVD9nSbOcHrGP%2FE4xsd6LSmhno4%2Bx7miss9Q%3D&st=2021-09-14T08%3A01%3A07Z&se=2021-10-15T08%3A06%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 08:59 UTC, opbld32 commented
Docs Build status updates of commit _[fe36b57](https://github.com/ajburnle/microsoft-graph-docs/commits/fe36b574fff581ec5e4c95117a6f1bcfb8e724b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-8989d86e)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-8989d86e)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-8989d86e"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-8989d86e"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140857408370-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=l4Spgm%2BEzbb2bOZVQY2CEMBMsk8GlBP6qqcaZ7RM6Hc%3D&st=2021-09-14T08%3A54%3A23Z&se=2021-10-15T08%3A59%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 09:01 UTC, opbld32 commented
Docs Build status updates of commit _[b180d0b](https://github.com/ajburnle/microsoft-graph-docs/commits/b180d0bd17e73d0827823f45c8d6a864776c9ac8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-4757ee70)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-4757ee70)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-4757ee70"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-4757ee70"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140858238130-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=cOxVGJS%2BJhBI9GDpZlxiiPUQ7xS6bFcUn7loBlQAe00%3D&st=2021-09-14T08%3A56%3A33Z&se=2021-10-15T09%3A01%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 09:03 UTC, opbld33 commented
Docs Build status updates of commit _[d1c118b](https://github.com/ajburnle/microsoft-graph-docs/commits/d1c118bfd92eba02606f41cd37c96d0cc9d7119a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-f1d744e1)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-f1d744e1)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-f1d744e1"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-f1d744e1"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140858429636-13931%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=SQQJTMjE9ouoCPwqM3ve2%2FBxdW8arluERsidW0Q4l8s%3D&st=2021-09-14T08%3A58%3A25Z&se=2021-10-15T09%3A03%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 13:12 UTC, opbld30 commented
Docs Build status updates of commit _[b66ed17](https://github.com/ajburnle/microsoft-graph-docs/commits/b66ed17c0f0eb87c57bc66e80a99a21ac35bdffb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-71a4304c)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-71a4304c)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-71a4304c"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-71a4304c"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109151308505765-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T13%3A12%3A26Z&sr=b&sp=r&sig=pBG%2BQR8ie8T2Mx1J2L9jg%2Bf8bQHmA15CuQ1e4g63pH4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 19:21 UTC, opbld33 commented
Docs Build status updates of commit _[1f9bd77](https://github.com/ajburnle/microsoft-graph-docs/commits/1f9bd77bf6fbc0af130108a0e4e0ca00111dd143)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-f186e83f)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-f186e83f)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-f186e83f"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-f186e83f"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109151919183749-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T19%3A21%3A54Z&sr=b&sp=r&sig=zdPkgIC7w43LLA%2B1PAtCWqarzceUZ6KN1mbOO4LvUM4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 19:30 UTC, opbld31 commented
Docs Build status updates of commit _[60c4634](https://github.com/ajburnle/microsoft-graph-docs/commits/60c4634aa2dc536f65a4f12880f3f53a0e5e963e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-efa3c9d3)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-efa3c9d3)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-efa3c9d3"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-efa3c9d3"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109151926447250-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T19%3A30%3A24Z&sr=b&sp=r&sig=StZvTeZCLzk6O22CFYAwWaSY9wmcpfG79oLWFvCeKuM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 19:33 UTC, opbld31 commented
Docs Build status updates of commit _[53260ea](https://github.com/ajburnle/microsoft-graph-docs/commits/53260ea7ef9da12bd89f6b1116482245a860748c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-afb8fd61)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-afb8fd61)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-afb8fd61"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-afb8fd61"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109151930464457-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T19%3A33%3A10Z&sr=b&sp=r&sig=qzLvAL0lIyKTpihqcnLKHl4W7PBqTx85ScZQcdk%2BEM4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 19:40 UTC, opbld34 commented
Docs Build status updates of commit _[019f220](https://github.com/ajburnle/microsoft-graph-docs/commits/019f220a2e45bd64f8006ecd3f18d5e0be5d6b92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-7e943d55)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-7e943d55)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-7e943d55"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-7e943d55"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109151937405577-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T19%3A40%3A09Z&sr=b&sp=r&sig=gEnu8yXh0lZIOTIXmIjaJzP%2FKtQyBPSQoLHMK5EWqOI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 00:12 UTC, opbld34 commented
Docs Build status updates of commit _[b341eaf](https://github.com/ajburnle/microsoft-graph-docs/commits/b341eaf99e280d076e7968f494ff04cc6cbc7893)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-116b6f53)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-116b6f53)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-116b6f53"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-116b6f53"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109160006252142-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T00%3A11%3A59Z&sr=b&sp=r&sig=yCdiY%2F%2BcPSqPg%2BRZfJoChUXlDPaYz9neMpoYnFSs%2Fd0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 00:33 UTC, opbld34 commented
Docs Build status updates of commit _[44d5997](https://github.com/ajburnle/microsoft-graph-docs/commits/44d5997b8bfa3d96bc16ac026485c60547fe197c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-120815a8)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-120815a8)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/v1.0/api/tablerow-range.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/v1.0/api/tablerow-range.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-range?view=graph-rest-1.0&branch=pr-en-us-13931) (>= graph-rest-1.0) |
[api-reference/v1.0/api/workbookpivottable-refreshall.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/v1.0/api/workbookpivottable-refreshall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/workbookpivottable-refreshall?view=graph-rest-1.0&branch=pr-en-us-13931) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-120815a8"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-120815a8"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109160031315085-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T00%3A33%3A58Z&sr=b&sp=r&sig=ltsjr1kAyawZGk9DTRDFNhaKcHaXBZeIf4Zr%2FQoHdKo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a [...]

2021-09-16 03:17 UTC, opbld30 commented
Docs Build status updates of commit _[e30af83](https://github.com/ajburnle/microsoft-graph-docs/commits/e30af83004cbd2d285f71669afc0affbfa364783)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-91329d3a)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-91329d3a)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-91329d3a"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-91329d3a"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109160315460355-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T03%3A17%3A52Z&sr=b&sp=r&sig=gO0CtDL4BPnHsCNTBqHFhJdP7RNendwDAxyISPQW8GA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 03:24 UTC, opbld34 commented
Docs Build status updates of commit _[664695e](https://github.com/ajburnle/microsoft-graph-docs/commits/664695e5d6e73e067b647ab7e586c2e479815886)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-28258b8c)
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-051358bc4656d01c44251401d620e1c9-28258b8c)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-28258b8c"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

<a id="051358bc4656d01c44251401d620e1c9-28258b8c"></a>
### [api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Used for the `accessPackageAttribute` property of an access package resource.' is duplicated in 'beta/resources/accesspackageresourceattribute.md(3,14)', 'beta/resources/accesspackageresourceattributesource.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109160321425357-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T03%3A24%3A47Z&sr=b&sp=r&sig=PlXO96M%2FLp5xkD4CJV9CxLsm1hQhWzp8V6PsO0tPRAk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 20:39 UTC, FaithOmbongi requested changes
**Review feedback:**

- Document the **attributes** property of [accessPackageResource](https://docs.microsoft.com/en-us/graph/api/resources/accessPackageResource?view=graph-rest-beta) object.
- We need better descriptions (metadata title & description body) for accesspackageuserdirectoryattributestore.md and accessrackageresourceattributedestination.md. The value/benefit/purpose of both these complex types to the overall settings of the **attributes** property should come out clearer.

_If we work backwards, how does accessPackageUserDirectoryAttributeStore define accessPackageResourceAttributeDestination's purpose which then defines the purpose of the attributeDestination property?_

- Required changes to the changelog to apply the guidance. Only 6 changelog objects are required for your PR.

2021-09-16 20:39 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +              href: resources/accesspackageuserdirectoryattributestore.md
All these are complex data types linked to the **attributes** property of [accessPackageResource](https://docs.microsoft.com/en-us/graph/api/resources/accessPackageResource?view=graph-rest-beta) object. They should be exposed in the TOC.
```suggestion
```

2021-09-16 20:39 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      "ChangeList": [
Kindly refer to the examples in the [Changelog guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog) for how to document new complex types, and the new attributes property. There aren't any new methods documented.

Your changelog should have only the following:
1. The 5 complex types you've introduced. See Example 1 in the Changelog guidance.
2. The new property added to **accessPackageResource** object. See Example 2 in the Changelog guidance.

2021-09-16 20:39 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageresourceattributedestination.md
> +description: "A complex type used for the `attributeDestination` property an access package."
This doesn't exactly define the purpose & does this complex type does. What's its value in setting the attirbuteDestination property.

2021-09-16 20:39 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageresourceattributedestination.md
> +accessPackageResourceAttributeDestination is a complex type used for the attributeDestination property of an access package. The actual destination will be a subtype of this complex type.
Same comment as in line 3.

2021-09-16 20:39 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageuserdirectoryattributestore.md
> +description: "The type of attribute source for the Azure Active Directory end system."
See my comment in the parent abstract type (accessPackageResourceAttributeDestination) topic from which this resource inherits. Also see my suggestions in the title and description body of accesspackageresourceattributesource.md and accesspackageresourceattributequestion.md topics.

Also, I think the word *source* is intended for the type (accessPackageResourceAttributeSource). This type has _store_ instead.

2021-09-16 20:39 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageresourceattributequestion.md
> +A question provided to an end user, for the purpose of obtaining an attribute value to be passed to the end system and/or request approver. 
```suggestion
Resource that defines the question provided to an end user, for the purpose of obtaining an attribute value to be passed to the end system or the request approver.
```

2021-09-16 20:39 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageresourceattributequestion.md
> +description: "A question provided to an end user, for the purpose of obtaining an attribute value to be passed to the end system and/or request approver"
```suggestion
description: "Resource that defines the question provided to an end user, for the purpose of obtaining an attribute value to be passed to the end system or the request approver."
```

2021-09-16 20:39 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageresourceattributequestion.md
> +None.
**question** property of type **accessPackageQuestion** is supported by this API.

2021-09-16 20:39 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageresourceattributesource.md
> +description: "Used for the `accessPackageAttribute` property of an access package resource."
By trying to work backward from accessPackageResourceAttributeQuestion (the resource which inherits from this object), this is how I understand this resource.
```suggestion
description: "An abstract type that exposes objects that define the properties the user configures with values that are passed to the end system or the request approver."
```

2021-09-16 20:39 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageresourceattributesource.md
> +This is the complex type of the source of an [accessPackageResourceAttribute](../resources/accesspackageresourceattribute.md) used for the attributeSource property. The actual source will be a subtyp
See my suggestion in the metadata title description.
```suggestion
An abstract type that exposes objects that define the properties the user configures with values that are passed to the end system or the request approver. It is inherited by [accessPackageResourceAttributeQuestion](../resources/accesspackageresourceattributequestion.md). 
```

2021-09-16 20:41 UTC, FaithOmbongi requested changes
@ajburnle  Left review comments

2021-09-21 00:04 UTC, maaaatthill commented on changelog/Microsoft.DirectoryServices.json
> +          "Target": "appScope"
Are these the right targets?  I see unifiedroleassignment, unifiedroledefinition, but these objects being added are not related.  I think all the targets are wrong (but I'm not an expert; maybe I'm wrong).

2021-09-21 02:51 UTC, maaaatthill commented on changelog/Microsoft.DirectoryServices.json
> +      "ChangeList": [
By the way, Ajane, I just found that there is an auto-generated changelog, which you may be able to use as at least as a starting point for these doc updates. I think you'll probably need to do some changes on top of the auto-generated changelog, but it may be nicer than what you've been doing (it has properties/etc. auto-populated).

2021-11-03 16:52 UTC, opbld32 commented
Docs Build status updates of commit _[e4232b9](https://github.com/ajburnle/microsoft-graph-docs/commits/e4232b983f8c623cb0e0d019602154df2570a4f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111031650243487-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-04T16%3A52%3A13Z&sr=b&sp=r&sig=U4qe2yvmoaPeLlfAUFJVnJpCODJpJ4Y5ok8kAjo2myg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-03 16:54 UTC, opbld31 commented
Docs Build status updates of commit _[8a7d00e](https://github.com/ajburnle/microsoft-graph-docs/commits/8a7d00e9a1ce71a494c8995c3b98d2878bf0b33a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111031652208245-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-04T16%3A54%3A58Z&sr=b&sp=r&sig=bFXwWkbOF6B4t01P2oJsu27m04U69UW2WcH2pOwz2oU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-03 16:58 UTC, ajburnle commented on api-reference/beta/resources/accesspackageresourceattributequestion.md
> +None.
@NelsonBlakeN

2021-11-03 20:17 UTC, opbld31 commented
Docs Build status updates of commit _[dc2a2f2](https://github.com/ajburnle/microsoft-graph-docs/commits/dc2a2f2d9ab400032b8c9d769b5ed1042ffaa223)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111032014259147-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-04T20%3A17%3A24Z&sr=b&sp=r&sig=MxUlc%2BlWT2UZwRdmD%2BjkILSp5In2plZw8t20IoudgPc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-03 21:00 UTC, ajburnle commented
@FaithOmbongi could you please take a look and let me know if this can move on to publishing? Thanks!

2021-11-03 22:06 UTC, opbld31 commented
Docs Build status updates of commit _[e608052](https://github.com/ajburnle/microsoft-graph-docs/commits/e6080523bfa0162b637cc9d07e78b4f1a4311741)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111032203518720-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-04T22%3A06%3A35Z&sr=b&sp=r&sig=59VxHZ6cs6qvHaC2fezyu8GPKTb4CB14%2BH5%2Bvu6UqAY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-04 06:55 UTC, FaithOmbongi commented
@ajburnle; I've self re-requested review so that the PR is visible in my inbox.

2021-11-04 07:57 UTC, ajburnle commented
> @ajburnle; I've self re-requested review so that the PR is visible in my inbox.

@FaithOmbongi thank you! please let me know if I need to change anything else

2021-11-05 09:49 UTC, FaithOmbongi requested changes
Hi @ajburnle ,

Left comments for some minor cleanup. In addition, please document the following missing pieces:
- Add the **attributes** property to the **accessPackageResource** Properties table & JSON representation. The **attributes** property is the initiator of this PR. I believe translating the CSDL, the hierarchy is as follows:

     **attributes** property on **accessPackageResource**
          .......| accessPackageResourceAttribute
          ................| accessPackageResourceAttributeDestination 
          ..........................| accesspackageuserdirectoryattributestore.md 
          ................| accessPackageResourceAttributeSource 
          ..........................| accessPackageResourceAttributeQuestion 


- Add the changelog entries for the following:
     - attributes property on **accessPackageResource** (after you document it)
     - The 5 resources in the hierarchy above as a result of the new attributes property

2021-11-05 09:49 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md
> +          }
Please remove Line 194 below. I don't think it's part of any request.

2021-11-05 09:49 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageresourceattributedestination.md
> +Currently,the only supported subtype is [accessPackageUserDirectoryAttributeStore](../resources/accesspackageuserdirectoryattributestore.md).
```suggestion
An abstract type used for the **attributeDestination** property of an access package. The actual destination will be a subtype of this complex type.

Currently, the only supported subtype is [accessPackageUserDirectoryAttributeStore](../resources/accesspackageuserdirectoryattributestore.md).  
```

2021-11-05 09:49 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageresourceattributequestion.md
> +|Question|accessPackageQuestion|The question asked in order to get the value of the attribute|
Fixing the case
```suggestion
|question|accessPackageQuestion|The question asked in order to get the value of the attribute|
```

2021-11-05 09:49 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageuserdirectoryattributestore.md
> +-->
Added the baseType
```suggestion
<!-- {
  "blockType": "resource",
  "@odata.type": "microsoft.graph.accessPackageUserDirectoryAttributeStore",
  "baseType": "microsoft.graph.accessPackageResourceAttributeDestination"
}
-->
```

2021-11-05 09:49 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Target": "accessPackageResourceAttribute"
Let's remove this entry for isEditable and isPersistedOnAssignmentRemoval, they're part of a resource. Document the resource instead.
```suggestion
```

2021-11-05 15:51 UTC, opbld30 commented
Docs Build status updates of commit _[4cbfa85](https://github.com/ajburnle/microsoft-graph-docs/commits/4cbfa8580fe1beda36485fe7b73c39b14d4bb265)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111051549054435-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-06T15%3A51%3A44Z&sr=b&sp=r&sig=nB9zD21EWOQ668tQxrVLKb11joL6sug6OeFgme9w7nk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-05 15:53 UTC, opbld34 commented
Docs Build status updates of commit _[9f626f8](https://github.com/ajburnle/microsoft-graph-docs/commits/9f626f87c083196992edcb44f7cc2bc5fba02f69)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111051550343234-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-06T15%3A53%3A24Z&sr=b&sp=r&sig=kxUfDT7ixC2w%2BuEszhig5OJM1vfGmB3AwGwLyoaQTZA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-10 10:31 UTC, opbld31 commented
Docs Build status updates of commit _[18ba826](https://github.com/ajburnle/microsoft-graph-docs/commits/18ba826d35347d779f5ef536a260a35e25736b59)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111101029430796-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-11T10%3A31%3A36Z&sr=b&sp=r&sig=etJ0CBwMPgCl2sg9DrkWlRKhkdYRwq2KCootk1vlVZU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-10 10:42 UTC, opbld33 commented
Docs Build status updates of commit _[e0c4065](https://github.com/ajburnle/microsoft-graph-docs/commits/e0c4065d8974a078c38bff5cb98ba1d9b4bbb1c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111101040123352-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-11T10%3A42%3A11Z&sr=b&sp=r&sig=OFcGpYSN9T8EGpP3HduE%2FpYcpnuqcISmSAhQ8johHhY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-10 10:51 UTC, opbld33 commented
Docs Build status updates of commit _[c706e01](https://github.com/ajburnle/microsoft-graph-docs/commits/c706e0110bf0854f4ced51b5d32a0af64baf4028)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111101049380475-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-11T10%3A51%3A25Z&sr=b&sp=r&sig=VXVsW9Q1buxybq%2FYqcR5VoRUvRMDQSee62rYdDQGXTQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-10 10:51 UTC, ajburnle commented
#feedback-addressed

2021-11-19 08:24 UTC, opbld30 commented
Docs Build status updates of commit _[74e9b25](https://github.com/ajburnle/microsoft-graph-docs/commits/74e9b251f6ed159d6032542b893d3cac392cd8df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111190822209161-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-20T08%3A24%3A14Z&sr=b&sp=r&sig=bwAotYPQIYbF5l7Jt95rus3O5X3e8sDcn3E%2BltihUn8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-19 08:32 UTC, opbld33 commented
Docs Build status updates of commit _[b0305e5](https://github.com/ajburnle/microsoft-graph-docs/commits/b0305e5e3190ba97b5619866f1beae18a6297766)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111190830368803-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-20T08%3A32%3A20Z&sr=b&sp=r&sig=rX%2FpPKteDi22wDzhutyq5FuwqTy2c75zT29A7pJtagw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 08:28 UTC, opbld34 commented
Docs Build status updates of commit _[f95d5f1](https://github.com/ajburnle/microsoft-graph-docs/commits/f95d5f1a17bff1f254dd4349587c5a5680e7f9eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200826421070-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T08%3A28%3A23Z&sr=b&sp=r&sig=nv9TMjOz4ykAA1P0sQDFNiOpZtpm2uH84NPo1OP7f5I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 09:08 UTC, opbld34 commented
Docs Build status updates of commit _[ebac890](https://github.com/ajburnle/microsoft-graph-docs/commits/ebac8906061d8ce689db7fa2fda5036669415b0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200906115366-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T09%3A08%3A00Z&sr=b&sp=r&sig=YJLmQlxSI%2FiArqWSgGMK7fPuDYvYJ2J%2BuDXooavnwmY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 09:15 UTC, opbld31 commented
Docs Build status updates of commit _[c62a214](https://github.com/ajburnle/microsoft-graph-docs/commits/c62a214ddce3a7ad82f552d88f66ad98ec7b8235)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200914149829-13931%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T09%3A15%3A52Z&sr=b&sp=r&sig=CBIZikRavzr%2Ff0EgX5djYOO92VxNE1KTdk%2BXguhMlxc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 02:14 UTC, opbld31 commented
Docs Build status updates of commit _[b509bc3](https://github.com/ajburnle/microsoft-graph-docs/commits/b509bc3a51395fca3d8df650a2ffbe227e8f2eb6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-760d78e8)

<a id="760d78e8"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040213353085-13931%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T02%3A14%3A02Z&sr=b&sp=r&sig=uKQn72EghWJMtKxGKwM5sFPTu6XXjIfytgtRfBK8AF8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 02:16 UTC, opbld30 commented
Docs Build status updates of commit _[b509bc3](https://github.com/ajburnle/microsoft-graph-docs/commits/b509bc3a51395fca3d8df650a2ffbe227e8f2eb6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5c3faedf)

<a id="5c3faedf"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040215554961-13931%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T02%3A16%3A26Z&sr=b&sp=r&sig=%2BEr9TFApQtNciJ%2Bp3tw7QWi6VtuyTbN4AHt13p2M9c0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 02:21 UTC, opbld33 commented
Docs Build status updates of commit _[5be6201](https://github.com/ajburnle/microsoft-graph-docs/commits/5be6201de8143e2d48af790817bf5ade21049569)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) | [Details](#user-content-39ec399d6cd6d3b2c67d69060eff28a0-d681b219)
[]() | :warning:Warning | | [Details](#user-content-d681b219)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="39ec399d6cd6d3b2c67d69060eff28a0-d681b219"></a>
### [api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md)
 - **Line 38, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="d681b219"></a>
###
 - **Line 0, Column 0**: **[Warning: redirected-file-not-removed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'beta/api/accesspackageassignmentpolicy-post.md' are still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040219142179-13931%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T02%3A21%3A12Z&sr=b&sp=r&sig=tr82SbCJ2XQI8jEFEVdO%2Fjp696fn182Zdc8uRfkbhkQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 02:26 UTC, opbld33 commented
Docs Build status updates of commit _[1f13134](https://github.com/ajburnle/microsoft-graph-docs/commits/1f131343aed9723334c54eea19c59844997fc8e1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-a10daf4f)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a10daf4f"></a>
###
 - **Line 0, Column 0**: **[Warning: redirected-file-not-removed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'beta/api/accesspackageassignmentpolicy-post.md' are still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040224226425-13931%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T02%3A26%3A15Z&sr=b&sp=r&sig=5ssX3%2BkUJzPvVyoV64LrjHwmODMFzkretqUZUBogri0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 02:29 UTC, opbld32 commented
Docs Build status updates of commit _[2a9ac41](https://github.com/ajburnle/microsoft-graph-docs/commits/2a9ac4170fac0fef15bf855788070a9a54003ac8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-3f6c16be)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="3f6c16be"></a>
###
 - **Line 0, Column 0**: **[Warning: redirected-file-not-removed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'beta/api/accesspackageassignmentpolicy-post.md' are still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040227198631-13931%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T02%3A29%3A28Z&sr=b&sp=r&sig=PCat49cAkDfRkjf7f%2Ba92cjUJC0gGSNqGycJNMEvT%2BA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 03:06 UTC, opbld31 commented
Docs Build status updates of commit _[0018df4](https://github.com/ajburnle/microsoft-graph-docs/commits/0018df4faa7e92ccfc24be8cfe050654034cdf0e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-b3984326)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="b3984326"></a>
###
 - **Line 0, Column 0**: **[Warning: redirected-file-not-removed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'beta/api/accesspackageassignmentpolicy-post.md' are still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040302582673-13931%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T03%3A06%3A13Z&sr=b&sp=r&sig=tcT0owOfnxOVwaKJrV87jVWhuR0qr14BKZFM0PYlx88%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 03:54 UTC, opbld33 commented
Docs Build status updates of commit _[5bc76d7](https://github.com/ajburnle/microsoft-graph-docs/commits/5bc76d70806da5f52fcc329a2956bf96b5feafbe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-12061858)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="12061858"></a>
###
 - **Line 0, Column 0**: **[Warning: redirected-file-not-removed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'beta/api/accesspackageassignmentpolicy-post.md' are still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040352030000-13931%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T03%3A53%3A59Z&sr=b&sp=r&sig=EVU74jhB3ze0A6YDu1opwVm1PA84qynCWV0ttYDf4b8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 04:01 UTC, opbld33 commented
Docs Build status updates of commit _[5bc76d7](https://github.com/ajburnle/microsoft-graph-docs/commits/5bc76d70806da5f52fcc329a2956bf96b5feafbe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-2e993fa1)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="2e993fa1"></a>
###
 - **Line 0, Column 0**: **[Warning: redirected-file-not-removed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'beta/api/accesspackageassignmentpolicy-post.md' are still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040358049066-13931%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T04%3A01%3A16Z&sr=b&sp=r&sig=pQW8l%2FD7wohK6Vizh6jUskop2dKcR94C6tpRT7W%2BguA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 04:08 UTC, opbld32 commented
Docs Build status updates of commit _[983e182](https://github.com/ajburnle/microsoft-graph-docs/commits/983e18213f4a3f0c875294bf56e149c22809370a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040404268506-13931%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T04%3A08%3A02Z&sr=b&sp=r&sig=nM0v8Wl4aTDiIFVG9A3jQNfS3hPbbQGZugLaljOCKiE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 07:46 UTC, opbld32 commented
Docs Build status updates of commit _[e7770e1](https://github.com/ajburnle/microsoft-graph-docs/commits/e7770e109731d917cb711fc4e58a214d80fb56e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201060744385662-13931%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T07%3A46%3A32Z&sr=b&sp=r&sig=hJILHB9mIcP2YhiceAdMXNwHcMJKBvbF6G68M%2BTg3cI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 07:50 UTC, opbld32 commented
Docs Build status updates of commit _[1368319](https://github.com/ajburnle/microsoft-graph-docs/commits/1368319a0b32c32f488309a1b2dd348fe8cf98ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201060748374616-13931%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T07%3A50%3A25Z&sr=b&sp=r&sig=XZO2n48EDkTPuF6o1P3AnYvxv5WcxCKxx0EUC%2FvlumI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 07:57 UTC, opbld34 commented
Docs Build status updates of commit _[1c450f3](https://github.com/ajburnle/microsoft-graph-docs/commits/1c450f30933bbdba18bc17a3546752328313b346)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201060754054295-13931%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T07%3A57%3A05Z&sr=b&sp=r&sig=fQCzjpZVV4fwb1p%2FSeOrYoMep%2FFXuqYudG8okcnpm90%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 07:59 UTC, FaithOmbongi approved these changes
Hi @ajburnle, I pushed a few commits for minor fixes before approving. I'm OK with adding this to the merge queue.

2022-01-06 08:02 UTC, opbld30 commented
Docs Build status updates of commit _[8d046b1](https://github.com/ajburnle/microsoft-graph-docs/commits/8d046b14c38583ac214fb1ac7932e290751ded24)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201060800146202-13931%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T08%3A02%3A15Z&sr=b&sp=r&sig=AFCc8nlZbKOKJO3t4Yt8Lb8nkZ6JxPujr4ghYVVdbs4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 08:04 UTC, opbld32 commented
Docs Build status updates of commit _[8d046b1](https://github.com/ajburnle/microsoft-graph-docs/commits/8d046b14c38583ac214fb1ac7932e290751ded24)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/api/accesspackagecatalog-list-accesspackageresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresources?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattribute.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattribute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattribute?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributedestination.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributedestination.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributedestination?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributequestion.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributequestion?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceattributesource.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageresourceattributesource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceattributesource?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageuserdirectoryattributestore.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/api-reference/beta/resources/accesspackageuserdirectoryattributestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageuserdirectoryattributestore?view=graph-rest-beta&branch=pr-en-us-13931) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-attributesapi/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201060800249386-13931%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T08%3A04%3A10Z&sr=b&sp=r&sig=XooFJE9KwhUf%2FPiIj5LZ5ddF004I%2F4bVYUMn4FBd%2BcI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-07 01:34 UTC, merged