Promote provisionEmail and removeEmail actions on Teams channel to v1.0
microsoftgraph/microsoft-graph-docs pull request #13982
Opened 2021-08-25 10:05 UTC by shantanu1singh

Promote provisionEmail and removeEmail actions on Teams channel to v1.0

2021-08-25 10:07 UTC, opbld32 commented
Docs Build status updates of commit _[5044955](https://github.com/shantanu1singh/microsoft-graph-docs/commits/504495545ccb53b62b41632393f75fbdd303c17e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/provisionchannelemailresult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/provisionchannelemailresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108251005455305-13982%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=pE8%2BUtQmeGz8etHhGhu%2FiNdxRd58%2BP7sWsj7JxP5UNk%3D&st=2021-08-25T10%3A02%3A31Z&se=2021-09-25T10%3A07%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-30 06:52 UTC, shantanu1singh commented on api-reference/v1.0/api/channel-provisionemail.md
> +If the channel's email is provisioned successfully, this method returns a `200 OK` response code and a [provisionChannelEmailResult](../resources/provisionChannelEmailResult.md) object in the respons
will update

2021-08-30 06:59 UTC, shantanu1singh commented on api-reference/v1.0/api/channel-removeemail.md
> +  "sampleKeys": ["893075dd-2487-4122-925f-022c42e20265", "19:561fbdbbfca848a484f0a6f00ce9dbbd@thread.tacv2"],
Looks like I didn't add the sample HTTP request. Will fix

2021-08-30 07:02 UTC, opbld31 commented
Docs Build status updates of commit _[4e18ee2](https://github.com/shantanu1singh/microsoft-graph-docs/commits/4e18ee2be5f103c8d81b69125b51dad7ef8e95db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/v1.0/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/provisionchannelemailresult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/provisionchannelemailresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108300700301548-13982%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=sfc7Npcn6o9Ey6WrOvWADFI2xwop2BUytQPnYKg9oVw%3D&st=2021-08-30T06%3A57%3A08Z&se=2021-09-30T07%3A02%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-30 13:20 UTC, isvargasmsft commented on api-reference/v1.0/api/channel-provisionemail.md
> +Microsoft Teams does not automatically provision an email address for a channel by default. To have Teams provision an email address, you can call **provisionEmail**, or through the Teams user interf
@shantanu1singh the [Microsoft Writing Style](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=36389) asks to [use contractions](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=36389):
Microsoft Teams doesn't automatically...

2021-08-30 13:25 UTC, isvargasmsft commented on api-reference/v1.0/api/channel-provisionemail.md
> +To remove a channel's provisioned email address, use the [removeEmail](channel-removeemail.md) method.
This phrase is not easy to understand for a global audience. Please rephrase to: 
* To remove the email address of a channel, use the ...

2021-08-30 13:29 UTC, isvargasmsft commented on api-reference/v1.0/api/channel-removeemail.md
> +Remove the provisioned email address of a [channel](../resources/channel.md).
Lines 3 and 14: Same observation above. This phrasing is not the best for a global audience. Remember this description is used by search engines to show results. If you need to remove the email address of a channel, how would you bing it? Please rephrase to:
Remove the email address of a channel.

2021-08-30 13:30 UTC, isvargasmsft commented on api-reference/v1.0/api/channel-removeemail.md
> +Remove the provisioned email address of a [channel](../resources/channel.md).
If the beta topic has the same description, would you mind updating it too?

2021-08-30 13:31 UTC, isvargasmsft commented on api-reference/v1.0/resources/channel.md
> +|[Provision channel email address](../api/channel-provisionemail.md) |[provisionChannelEmailResult](../resources/provisionchannelemailresult.md)| Provision email address.|
As pe our conversation on the side: Provision an email address for the channel.

2021-08-30 13:32 UTC, isvargasmsft commented on api-reference/v1.0/resources/channel.md
> +|[Remove channel email address](../api/channel-removeemail.md) | None | Remove email address.|
As per our conversation on the side: 
Remove the email address of the channel.

2021-08-30 13:37 UTC, isvargasmsft commented on api-reference/v1.0/api/channel-provisionemail.md
> +Microsoft Teams does not automatically provision an email address for a channel by default. To have Teams provision an email address, you can call **provisionEmail**, or through the Teams user interf
Please also bold the word **channel**.

2021-08-30 13:41 UTC, isvargasmsft commented on api-reference/v1.0/api/channel-provisionemail.md
> +If the channel's email is provisioned successfully, this method returns a `200 OK` response code and a [provisionChannelEmailResult](../resources/provisionChannelEmailResult.md) object in the respons
Let's rephrase for simplicity: If successful, this method returns...

2021-08-30 13:43 UTC, isvargasmsft requested changes
Thank you for your work, Shantanu. 

Please review some rephrasing suggestions and let me know if you have any questions.

Here to help!

2021-08-31 04:49 UTC, shantanu1singh commented on api-reference/v1.0/resources/channel.md
> +|[Provision channel email address](../api/channel-provisionemail.md) |[provisionChannelEmailResult](../resources/provisionchannelemailresult.md)| Provision email address.|
done

2021-08-31 04:49 UTC, shantanu1singh commented on api-reference/v1.0/resources/channel.md
> +|[Remove channel email address](../api/channel-removeemail.md) | None | Remove email address.|
done

2021-08-31 04:50 UTC, shantanu1singh commented on api-reference/v1.0/api/channel-provisionemail.md
> +To remove a channel's provisioned email address, use the [removeEmail](channel-removeemail.md) method.
done

2021-08-31 04:51 UTC, shantanu1singh commented on api-reference/v1.0/api/channel-removeemail.md
> +Remove the provisioned email address of a [channel](../resources/channel.md).
sure, done

2021-08-31 04:52 UTC, shantanu1singh commented on api-reference/v1.0/api/channel-provisionemail.md
> +If the channel's email is provisioned successfully, this method returns a `200 OK` response code and a [provisionChannelEmailResult](../resources/provisionChannelEmailResult.md) object in the respons
sure, done

2021-08-31 04:53 UTC, opbld30 commented
Docs Build status updates of commit _[c70e77c](https://github.com/shantanu1singh/microsoft-graph-docs/commits/c70e77c748ac4e3cb9841ce708dbec2c6dc0f244)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/v1.0/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/provisionchannelemailresult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/provisionchannelemailresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108310452307958-13982%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=aVZAMjpsGPJzK3T1Tj2p6PfeejhuoO7%2FssPLJfrp1ik%3D&st=2021-08-31T04%3A48%3A58Z&se=2021-10-01T04%3A53%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-01 04:21 UTC, opbld32 commented
Docs Build status updates of commit _[a0d41b0](https://github.com/shantanu1singh/microsoft-graph-docs/commits/a0d41b076ffc05c996fb29d2101a128ffab1c300)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f5487893)

<a id="f5487893"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109010421185004-13982%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=g%2BVGxJ0K1z%2B3UR1Y1hUQPT8XoTNr4zRao%2FfHiX9VGAk%3D&st=2021-09-01T04%3A16%3A50Z&se=2021-10-02T04%3A21%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-01 04:37 UTC, opbld34 commented
Docs Build status updates of commit _[e78d74c](https://github.com/shantanu1singh/microsoft-graph-docs/commits/e78d74c6e77849a9558ef12d1391d61ebc69e98a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/v1.0/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/provisionchannelemailresult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/provisionchannelemailresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109010435154993-13982%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=jB7ERSVryVoj4jLf1Fo32BSGJCqqB7CnbAPPrCNtt0Y%3D&st=2021-09-01T04%3A32%3A07Z&se=2021-10-02T04%3A37%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-01 16:39 UTC, jasonjoh commented
Docs Build status updates of commit _[2e6011d](https://github.com/shantanu1singh/microsoft-graph-docs/commits/2e6011de1226481c53f1d80d4b1e853f89dea574)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/v1.0/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/provisionchannelemailresult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/provisionchannelemailresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109011635205462-13982%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Dl9ir%2BVKXzt76WACpDda76kvj%2BUJeJ08cj0smwh82%2FY%3D&st=2021-09-01T16%3A34%3A03Z&se=2021-10-02T16%3A39%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-01 16:50 UTC, isvargasmsft approved these changes

2021-09-02 13:35 UTC, jasonjoh commented
Docs Build status updates of commit _[7cfd491](https://github.com/shantanu1singh/microsoft-graph-docs/commits/7cfd491be6951cbe2c9229d4102fda883232e6ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/v1.0/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/provisionchannelemailresult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/provisionchannelemailresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021332397984-13982%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=nIl2p9Nv1QmUTlYbTl0YyCLJdVZBSrnejTNGcQwdkyQ%3D&st=2021-09-02T13%3A30%3A24Z&se=2021-10-03T13%3A35%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 13:44 UTC, jasonjoh commented
Docs Build status updates of commit _[47a3a33](https://github.com/shantanu1singh/microsoft-graph-docs/commits/47a3a33a3ae525e2c60a7629d05f3bbad7944bca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/v1.0/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/provisionchannelemailresult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/provisionchannelemailresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021343151753-13982%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=QAsINYvxcZLGG3JvrDfSLtRSg5UFP6CwxfJgHugGsxc%3D&st=2021-09-02T13%3A39%3A45Z&se=2021-10-03T13%3A44%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-13 06:23 UTC, opbld31 commented
Docs Build status updates of commit _[70756ba](https://github.com/shantanu1singh/microsoft-graph-docs/commits/70756ba0618618f5be5133ba096d125a24d6c886)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/v1.0/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/provisionchannelemailresult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/provisionchannelemailresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109130621472106-13982%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=L8xHV%2FEeID8rra4NaH%2BCnEcZ%2BfYFfPCZEX7LiV%2Bv9ao%3D&st=2021-09-13T06%3A18%3A52Z&se=2021-10-14T06%3A23%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 01:42 UTC, opbld34 commented
Docs Build status updates of commit _[993462a](https://github.com/shantanu1singh/microsoft-graph-docs/commits/993462a657f1f9dce178bd9f0a485f38cc1b020b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/v1.0/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/provisionchannelemailresult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/provisionchannelemailresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140141175879-13982%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=8d1Pj%2BEXCC2fFHoqA4fHYpJMQOx2C3pfrx6QBzUuBGI%3D&st=2021-09-14T01%3A37%3A54Z&se=2021-10-15T01%3A42%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 01:44 UTC, opbld31 commented
Docs Build status updates of commit _[84bba97](https://github.com/shantanu1singh/microsoft-graph-docs/commits/84bba9743bfdc9eb560ead18cfdceeb4294ad851)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-13982) (graph-rest-beta) |
[api-reference/v1.0/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/provisionchannelemailresult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/resources/provisionchannelemailresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-1.0&branch=pr-en-us-13982) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shsi/channelemailv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140142196727-13982%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=pYV0aWa2VAxeFJa04%2BdkGrcjAg4z1a2I%2BZqHclVWxMw%3D&st=2021-09-14T01%3A39%3A42Z&se=2021-10-15T01%3A44%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 01:46 UTC, merged