V1.0 documentation for 'Add members in bulk to a team' API
microsoftgraph/microsoft-graph-docs pull request #14001
Opened 2021-08-26 05:33 UTC by abshar-teams

2021-09-01 12:28 UTC, abshar-teams commented on api-reference/v1.0/api/conversationmembers-add.md
> +title: "conversationMember: add"
This is the v1.0 version of the following page:
https://docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&tabs=http

2021-09-01 20:43 UTC, JarbasHorst requested changes

2021-09-01 20:43 UTC, JarbasHorst commented on api-reference/v1.0/api/conversationmembers-add.md
> +The following is the response.
For consistency, please replace "The following is the response." with "The following is an example of the response."

2021-09-01 20:43 UTC, JarbasHorst commented on api-reference/v1.0/api/conversationmembers-add.md
> +  "@odata.type": "Collection(microsoft.graph.actionResultPart)"
Please, replace "@odata.type": "Collection(microsoft.graph.actionResultPart)" with "@odata.type": "microsoft.graph.actionResultPart" and add the property: "isCollection": true.

2021-09-01 20:43 UTC, JarbasHorst commented on api-reference/v1.0/api/conversationmembers-add.md
> +# [HTTP](#tab/http)
The tabs get added via the weekly SDK snippet automation that runs on the main branch. In this case, you need to remove this HTTP H1. So, we don't have just the one tab.

2021-09-01 20:43 UTC, JarbasHorst commented on api-reference/v1.0/api/conversationmembers-add.md
> +The following is the response.
For consistency, please replace "The following is the response." with "The following is an example of the response."

2021-09-01 20:43 UTC, JarbasHorst commented on api-reference/v1.0/api/conversationmembers-add.md
> +  "@odata.type": "Collection(microsoft.graph.actionResultPart)"
Please, replace "@odata.type": "Collection(microsoft.graph.actionResultPart)" with "@odata.type": "microsoft.graph.actionResultPart" and add the property: "isCollection": true.

2021-09-01 20:43 UTC, JarbasHorst commented on api-reference/v1.0/api/conversationmembers-add.md
> +  "description": "Add members to team in bulk",
Please, 

- add a before team. 
-  add a period at the end of the sentence

Suggested revision:
- Add members to a team in bulk.

2021-09-01 20:43 UTC, JarbasHorst commented on api-reference/v1.0/resources/actionresultpart.md
> +description: "Abstract type for modeling responses of bulk operations."
Please, avoid using gerunds where possible; in this case, you can change "for modeling" to "to model".

2021-09-01 20:43 UTC, JarbasHorst commented on api-reference/v1.0/resources/actionresultpart.md
> +title: "actionResultType resource type"
Make sure that the title field matches the H1. In the title you have "actionResultType" but in the H1 "actionResultPart"

2021-09-01 20:43 UTC, JarbasHorst commented on api-reference/v1.0/resources/actionresultpart.md
> +[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]
Please, remove the beta disclaimer because this is a v1 topic.

2021-09-01 20:43 UTC, JarbasHorst commented on api-reference/v1.0/resources/actionresultpart.md
> +An abstract type that serves as a base for modeling responses of bulk operations. The **error** property is selectively populated based on whether the response represents an error.
Please, avoid using gerunds where possible; in this case, you can change "for modeling" to "to model".

2021-09-01 20:43 UTC, JarbasHorst commented on api-reference/v1.0/resources/actionresultpart.md
> +- [Add members in bulk to team](../api/conversationmembers-add.md)
Please, add a before team. Suggested revision:
- ...bulk to a team

2021-09-01 20:45 UTC, JarbasHorst commented
@abshar-teams please include your changes to the changelog.

2021-09-03 12:31 UTC, jasonjoh commented
Docs Build status updates of commit _[39e3654](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39e3654b6f481b9c8b5345975768a341b88925b3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e4c25ff3)

<a id="e4c25ff3"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031230447736-14001%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=kSAphaey6g8hbVcNTQy3Q91eZLOgNOcjIHiQPnMatAc%3D&st=2021-09-03T12%3A26%3A07Z&se=2021-10-04T12%3A31%3A07Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 17:22 UTC, jasonjoh commented
Docs Build status updates of commit _[441f24c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/441f24c06a8dd4ff23eb1bfa5cd99ff01f33900c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) | [Details](#user-content-7aed3e28d8f8f5845a62b5a5a7b902f6-269866f7)
[api-reference/beta/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/v1.0/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |

<a id="7aed3e28d8f8f5845a62b5a5a7b902f6-269866f7"></a>
### [api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/team.md)
 - **Line 75, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031721027668-14001%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=y1qL9RSNP3gJtV5RubTyJmkm68Mmf4CbuZJyyz85RTQ%3D&st=2021-09-03T17%3A17%3A41Z&se=2021-10-04T17%3A22%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 18:13 UTC, jasonjoh commented
Docs Build status updates of commit _[c526ae9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c526ae91558b39eeecd4ecea69d6fd031c9d14d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) | [Details](#user-content-7aed3e28d8f8f5845a62b5a5a7b902f6-3c890eec)
[api-reference/beta/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/v1.0/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |

<a id="7aed3e28d8f8f5845a62b5a5a7b902f6-3c890eec"></a>
### [api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/team.md)
 - **Line 75, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031812135835-14001%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=RuLEJ3%2Bh7GwRCYrsMQf%2Fxx%2FBDlhMSp2IXqk5FeQbTKQ%3D&st=2021-09-03T18%3A08%3A40Z&se=2021-10-04T18%3A13%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-06 20:07 UTC, JarbasHorst requested changes

2021-09-06 20:07 UTC, JarbasHorst commented on api-reference/v1.0/api/conversationmembers-add.md
> +The following is the example of the response.
For consistency and clarity, I recommend you to replace "the example" with "an example". "An example" means that the following example is one of the possible responses you can get which sounds more correct in this case.

Suggested revision:

- The following is an example of the response.

2021-09-06 20:07 UTC, JarbasHorst commented on api-reference/v1.0/api/conversationmembers-add.md
> +The following is the example of the response.
For consistency and clarity, I recommend you to replace "the example" with "an example". "An example" means that the following example is one of the possible responses you can get which sounds more correct in this case.

Suggested revision:

- The following is an example of the response.

2021-09-06 20:16 UTC, JarbasHorst commented
@abshar-teams your PR introduces a new resource type and a new method. Please include your changes to the changelog!!!

2021-09-07 05:56 UTC, opbld33 commented
Docs Build status updates of commit _[c589cae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c589cae7560f557efa49b1829c0466b27cf8308a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) | [Details](#user-content-7aed3e28d8f8f5845a62b5a5a7b902f6-0fb59605)
[api-reference/beta/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/v1.0/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |

<a id="7aed3e28d8f8f5845a62b5a5a7b902f6-0fb59605"></a>
### [api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/team.md)
 - **Line 75, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109070555212637-14001%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=56KaqRPtMS2orOQ%2FWBxtKLdAfv068Q37XvE51qc5qus%3D&st=2021-09-07T05%3A51%3A50Z&se=2021-10-08T05%3A56%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-07 07:19 UTC, opbld34 commented
Docs Build status updates of commit _[6bc7c4b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6bc7c4b52a3febc3ff494908a50c147d324a7873)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) | [Details](#user-content-7aed3e28d8f8f5845a62b5a5a7b902f6-119998c8)
[api-reference/beta/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/v1.0/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="7aed3e28d8f8f5845a62b5a5a7b902f6-119998c8"></a>
### [api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/team.md)
 - **Line 75, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109070718066760-14001%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=xRZoYS1amamZc%2FzM%2BsCKQrDcTEaA0O4%2FqmWzIqUyXQY%3D&st=2021-09-07T07%3A14%3A52Z&se=2021-10-08T07%3A19%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-07 20:14 UTC, JarbasHorst requested changes

2021-09-07 20:14 UTC, JarbasHorst commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "ChangedApiName": "add",
Please, replace add with team.

2021-09-07 20:14 UTC, JarbasHorst commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Description": "Added the [add](https://docs.microsoft.com/en-us/graph/api/add?view=graph-rest-1.0) method to the [add](https://docs.microsoft.com/en-us/graph/api/add?view=graph-rest-1.0) r
The description isn't correct. In this case, rephrase the sentence. Suggested revision:

- Added the \[conversationMemberAdd\]\(https://docs.microsoft.com/graph/api/conversationmembers-add?view=graph-rest-1.0) method to the \[team\]\(https://docs.microsoft.com/graph/api/resources/team?view=graph-rest-1.0) resource.

2021-09-07 20:18 UTC, JarbasHorst commented
@abshar-teams apparently, the changelog record wasn't generated correctly. I added comments to the changelog file to instruct you how to fix the content generated.

2021-09-08 02:34 UTC, opbld30 commented
Docs Build status updates of commit _[6eedede](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6eedede4d26269b24822d948b40233e4acf8cfec)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/managedtenants-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/concepts/managedtenants-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/managedtenants-concept-overview?branch=pr-en-us-14001) | [Details](#user-content-03f19db1b54af825eed2b80e6ecc9f40-4bb54ff0)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-4bb54ff0)
[api-reference/beta/api/managedtenants-tenant-resettenantonboardingstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/managedtenants-tenant-resettenantonboardingstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-tenant-resettenantonboardingstatus?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) | [Details](#user-content-4f354ea99847d0418aa1bf2b0ffb1497-4bb54ff0)
[api-reference/beta/api/managedtenants-conditionalaccesspolicycoverage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/managedtenants-conditionalaccesspolicycoverage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-conditionalaccesspolicycoverage-get?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) | [Details](#user-content-27ec0763e9b2121a922f7ba94144d1ca-4bb54ff0)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-4bb54ff0)
[api-reference/beta/api/managedtenants-managementactiontenantdeploymentstatus-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/managedtenants-managementactiontenantdeploymentstatus-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managementactiontenantdeploymentstatus-get?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) | [Details](#user-content-1f8e60608d590c49fb0f930f550dee20-4bb54ff0)
[api-reference/beta/api/managedtenants-managementactiontenantdeploymentstatus-changedeploymentstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/managedtenants-managementactiontenantdeploymentstatus-changedeploymentstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managementactiontenantdeploymentstatus-changedeploymentstatus?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) | [Details](#user-content-d23b46ae91d7aa3987447c482cd0da4d-4bb54ff0)
[api-reference/beta/api/managedtenants-manageddevicecompliancetrend-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/managedtenants-manageddevicecompliancetrend-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-manageddevicecompliancetrend-get?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) | [Details](#user-content-afa7a451d611fa6ea420f06a555ad32d-4bb54ff0)
[api-reference/beta/api/managedtenants-managementaction-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/managedtenants-managementaction-apply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managementaction-apply?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) | [Details](#user-content-c3864c9fb7eaf63883d5e3b5bce0cd71-4bb54ff0)
[api-reference/beta/api/managedtenants-tenanttag-assigntag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/managedtenants-tenanttag-assigntag.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-tenanttag-assigntag?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) | [Details](#user-content-2f045f774c0f79227636459f91f1382f-4bb54ff0)
[api-reference/beta/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/v1.0/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="03f19db1b54af825eed2b80e6ecc9f40-4bb54ff0"></a>
### [concepts/managedtenants-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/concepts/managedtenants-concept-overview.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'isaiahwilliams' is not a valid GitHub ID.`````

<a id="dae1902a11f6a9f235b35b73200aa4d9-4bb54ff0"></a>
### [api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft [...]

2021-09-08 13:10 UTC, opbld32 commented
Docs Build status updates of commit _[e317cb3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e317cb323b262c420719e431d40423c3549a7614)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/v1.0/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109081308251833-14001%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Wx6HtzCTiU3UwgFqhbjGbs5ACZH1iMBKU06H2lWjOTM%3D&st=2021-09-08T13%3A05%3A00Z&se=2021-10-09T13%3A10%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 19:17 UTC, JarbasHorst requested changes

2021-09-08 19:17 UTC, JarbasHorst commented on changelog/Microsoft.Teams.GraphSvc.json
> +        {
Please, remove this entry from the changelog record because the aadUserConversationMemberResult resource type isn't part of this PR.

2021-09-08 19:18 UTC, JarbasHorst requested changes

2021-09-08 19:18 UTC, JarbasHorst commented on changelog/Microsoft.Teams.GraphSvc.json
> +        {
Please, remove this entry from the changelog record because the aadUserConversationMemberResult resource type isn't part of this PR.

2021-09-09 11:52 UTC, opbld32 commented
Docs Build status updates of commit _[f62d5ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f62d5ffe5f91a59bba7f62b5bc5490c006eb1a62)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/v1.0/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109091151144563-14001%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=JoG2V12f5Pznftd6bgIe3o46OVTj11RA8EnLLbLAk08%3D&st=2021-09-09T11%3A47%3A56Z&se=2021-10-10T11%3A52%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-13 19:29 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-09-14 01:51 UTC, Lauragra approved these changes

2021-09-14 01:52 UTC, opbld30 commented
Docs Build status updates of commit _[5bb48da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5bb48daf2a228c0cb32ffdea2a5ab14e9ea59d58)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4a4b53df)

<a id="4a4b53df"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140151373490-14001%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=p%2FR7Kxgjy4RTj98V8KfTs5li29uMRFh899Fu0wRyhjQ%3D&st=2021-09-14T01%3A46%3A59Z&se=2021-10-15T01%3A51%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 01:55 UTC, opbld34 commented
Docs Build status updates of commit _[c9f5b50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9f5b507265370a00cbd15f61a2d4f4d6e79956d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/v1.0/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109140153149474-14001%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=cgGeq4DXyGsg40pI%2BQW%2FSdH140yTmbdW012FRvTWpYY%3D&st=2021-09-14T01%3A50%3A20Z&se=2021-10-15T01%3A55%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 02:52 UTC, Lauragra commented on api-reference/v1.0/api/conversationmembers-add.md
> +---
The file name should technically be singular, conversationMember. It's plural in beta as well though. Please fix when you get a chance.

2021-09-14 12:39 UTC, abshar-teams commented on api-reference/v1.0/api/conversationmembers-add.md
> +---
@Lauragra , we have a separate file with the name 'converstionmember-add.md' too, which is for the api which adds a single member to a team, while this api adds multiple members in a team, that's why i guess it's plural. What should be the fix in this case ?

2021-09-25 01:21 UTC, opbld31 commented
Docs Build status updates of commit _[05a2e2e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05a2e2e6f82b63909503e14bbf4bb13314b5f953)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-14001) (graph-rest-beta) |
[api-reference/v1.0/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&branch=pr-en-us-14001) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-addv1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109250120006839-14001%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-26T01%3A21%3A37Z&sr=b&sp=r&sig=iMjPLoCuHLcJ%2FxUb0id%2BmLHFaLY8pULEsFYcUnHrmNU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-25 01:38 UTC, merged