Toolkit 2.3 Release Docs
microsoftgraph/microsoft-graph-docs pull request #14008
Opened 2021-08-26 19:08 UTC by elisenyang

2021-09-03 18:10 UTC, Lauragra commented on concepts/toc.yml
> +              - name: Build a Microsoft Teams tab with Single Sign-On (SSO)
We don't need to spell out the acronym in the TOC; we can just use SSO to make the entry shorter/more scannable.

2021-09-03 18:13 UTC, Lauragra commented on concepts/toc.yml
> +              - name: Msal provider
Why are we changing this to lowercase? It's an acronym, right? It's all caps here, for example: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-overview

2021-09-03 18:16 UTC, Lauragra commented on concepts/toolkit/components/file-list.md
> +The File List component displays [a list of multiple folders and files](/graph/api/resources/onedrive) by using the file/folder name, an icon, and other properties that you specify. This component us
We should avoid using gerunds where possible, so you can change "of allowing" to "to allow" (see the writing tips: https://docs.microsoft.com/en-us/style-guide/global-communications/writing-tips). Also, One Drive should be one word, OneDrive.

2021-09-03 18:33 UTC, jasonjoh commented
Docs Build status updates of commit _[ba2ae84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba2ae848b9db0380c732259c8dcf72cb099bce09)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0070cf37)

<a id="0070cf37"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031833104311-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=2VQskKWbxOrRmep2pQAJCwJQ3lHLRIDKFs3Vzi8981E%3D&st=2021-09-03T18%3A28%3A25Z&se=2021-10-04T18%3A33%3A25Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 18:37 UTC, jasonjoh commented
Docs Build status updates of commit _[d063859](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d063859c6cada05376b7215dc02376ae39030e69)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-850738b5)

<a id="850738b5"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031837024321-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=V08Yz4H4IhrwGoGvGgBTfgVJJ3C9kw193b4zv6sDFXQ%3D&st=2021-09-03T18%3A32%3A42Z&se=2021-10-04T18%3A37%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 20:31 UTC, jasonjoh commented
Docs Build status updates of commit _[7b9803f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b9803fbc2b14012204c51543b9c0659c2f7dd54)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0e793529)

<a id="0e793529"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109032031244685-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=f9W8gXzWkcAyNrtwEZBedeu88G0se0Sy2uhcAqA7sUo%3D&st=2021-09-03T20%3A26%3A54Z&se=2021-10-04T20%3A31%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 20:32 UTC, Lauragra commented on concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md
> +- Ask a question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-toolkit.html).
FYI, we should be using Q&A now instead of SO so I updated this link.

2021-09-03 20:32 UTC, jasonjoh commented
Docs Build status updates of commit _[6dc36c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6dc36c2c47fb643c547d8cb105c1152e3956f764)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d8e66c55)

<a id="d8e66c55"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109032032337995-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=j24R%2Frgu2Zn7jK8SepcBgmULlieqwAWl4Moie24kEd4%3D&st=2021-09-03T20%3A27%3A58Z&se=2021-10-04T20%3A32%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 20:38 UTC, jasonjoh commented
Docs Build status updates of commit _[948d115](https://github.com/microsoftgraph/microsoft-graph-docs/commits/948d115c49d5f92868097c8c159976638bb6f6a0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b7c0e182)

<a id="b7c0e182"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109032037426063-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=clI3p9JjUwQ6mDrLQBB8edC%2BD9YI6kfDPl3OvWn8Lks%3D&st=2021-09-03T20%3A33%3A04Z&se=2021-10-04T20%3A38%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 20:39 UTC, jasonjoh commented
Docs Build status updates of commit _[d2b9d02](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2b9d02ed860860edeaaac184b0ee5830b0f6ed2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fafc2959)

<a id="fafc2959"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109032038584185-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=uEFWO%2BZ3uqR%2FPKz4es8P9vS%2F9cxwJ8SMGeQlh1XAJgE%3D&st=2021-09-03T20%3A34%3A13Z&se=2021-10-04T20%3A39%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 21:00 UTC, jasonjoh commented
Docs Build status updates of commit _[5a062bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a062bf8a05d6b9fa63d2775a25952294eeaa2f2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c41c763f)

<a id="c41c763f"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109032059565745-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=p22TrUp8NpOKqfzvk3VdXjVYQWtBrKLKGBC%2FnUGR%2BCQ%3D&st=2021-09-03T20%3A55%3A10Z&se=2021-10-04T21%3A00%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 21:06 UTC, jasonjoh commented
Docs Build status updates of commit _[cd66abe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd66abeb400a1607c0b357b7ba484985f20675fb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-27397260)

<a id="27397260"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109032105546517-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=6MOdfoFoOTgiz8k1YCxvF1kt3J48yx4gJpE4YnLafRc%3D&st=2021-09-03T21%3A01%3A15Z&se=2021-10-04T21%3A06%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 21:07 UTC, jasonjoh commented
Docs Build status updates of commit _[d47de32](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d47de322c3eb33d9f47c243d4a6d111e27cacbba)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-63cfa9a8)

<a id="63cfa9a8"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109032107371521-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=jylNEuXoWgxP1Xuq1TdPjaDBSBw%2B0rdXj7b0rMiANA0%3D&st=2021-09-03T21%3A02%3A57Z&se=2021-10-04T21%3A07%3A57Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 21:08 UTC, jasonjoh commented
Docs Build status updates of commit _[29ef55a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/29ef55ac240c5e0fde3080f7dfed657506753c0e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-be29d12f)

<a id="be29d12f"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109032108112216-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=tTU0p9qNp1roL2W2CRDgvp6X0QnzXi33TJJAIWmwJSw%3D&st=2021-09-03T21%3A03%3A34Z&se=2021-10-04T21%3A08%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 21:17 UTC, jasonjoh commented
Docs Build status updates of commit _[d689319](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d689319e6a461f95ca2f5d8240f1bc02c1cac58e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b2b1e8ef)

<a id="b2b1e8ef"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109032115042592-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=OONVPMvecBjqyQTiXSSu5ke7HYye2Yt6iOA4iIb61tM%3D&st=2021-09-03T21%3A12%3A08Z&se=2021-10-04T21%3A17%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 21:33 UTC, jasonjoh commented
Docs Build status updates of commit _[ca846c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ca846c58a5410d049254c73233b12c83a3969cd4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e215aaca)

<a id="e215aaca"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109032133332945-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=aMwVqfXg2AoVbcSLq2tAzwdLknVYC2AfKotHQGMEMxo%3D&st=2021-09-03T21%3A28%3A52Z&se=2021-10-04T21%3A33%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 21:35 UTC, jasonjoh commented
Docs Build status updates of commit _[7ea4245](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ea4245b122a6eeecaf07ecc9734ae77fce744e1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9b4d13be)

<a id="9b4d13be"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109032134547206-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=elgPcPCiN9fBCC80ytcGARmwvHtjDcODQ46x%2FENStKw%3D&st=2021-09-03T21%3A30%3A16Z&se=2021-10-04T21%3A35%3A16Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 21:46 UTC, jasonjoh commented
Docs Build status updates of commit _[c33094f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c33094fe3720d97670cdc097d465d8845deb8493)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/people-picker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-sso-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-angular.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-angular.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-angular?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-14008) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams-msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams-msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-14008) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109032144317176-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=4gpXdmYTBYILwmtEmHjkFDW9xWOWQCJfNknTTNGnA6w%3D&st=2021-09-03T21%3A41%3A09Z&se=2021-10-04T21%3A46%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 22:05 UTC, jasonjoh commented
Docs Build status updates of commit _[d9c7a60](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9c7a605309728bc260083e6f5e21999a63e0e8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/people-picker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-sso-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-angular.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-angular.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-angular?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-14008) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams-msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams-msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-14008) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109032203342216-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=UquS4xwxkijKyFnVbMKqlQR5pd%2Bi06z4RYs2u0k1g54%3D&st=2021-09-03T22%3A00%3A06Z&se=2021-10-04T22%3A05%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 22:05 UTC, Lauragra commented on concepts/toc.yml
> +              - name: Msal provider
I think my question here is whether the name of this provider is officially MsalProvider, or whether we should refer to it as an MSAL provider. We seem to be using two words in the TOC and one word in the content. For consistency, I think that it should be MSAL provider and MSAL2 provider in both locations, but please verify.

2021-09-03 22:06 UTC, Lauragra commented on concepts/toc.yml
> +              - name: Build a Microsoft Teams tab with Single Sign-On (SSO)
Please apply the same TOC updates to the TOC files in the /beta and /v1.0 folders since we surface the toolkit topics in those TOC as well.

2021-09-03 22:14 UTC, Lauragra requested changes
Please clarify how we refer to the various MSAL providers - i.e. one word or two word "MSAL provider". That needs to be made consistent throughout the content, in titles and TOC entries.

Please also update the TOC files in beta and v1.0 to be consistent with the concepts TOC.

2021-09-07 20:56 UTC, elisenyang commented on concepts/toc.yml
> +              - name: Build a Microsoft Teams tab with Single Sign-On (SSO)
Updated to make sure TOCs are consistent in all 3 places.

2021-09-07 20:57 UTC, opbld33 commented
Docs Build status updates of commit _[60aa663](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60aa66379886e07b3767ae6f864d4c2c4fa39b49)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-14008) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f686dcda)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-14008) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-f686dcda)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/people-picker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-sso-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-angular.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-angular.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-angular?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-14008) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams-msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams-msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-14008) |

<a id="0817dce4456c16725d5333633847d38f-f686dcda"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/beta/toc.yml)
 - **Line 165, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'toolkit/get-started/overview'.`````
 - **Line 167, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'toolkit/get-started/mgt-react'.`````
 - **Line 169, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'toolkit/get-started/mgt-spfx'.`````
 - **Line 173, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'toolkit/get-started/add-aad-app-registration'.`````
 - **Line 175, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'toolkit/get-started/build-a-web-app'.`````
 - **Line 177, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'toolkit/get-started/use-toolkit-with-react'.`````
 - **Line 179, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'toolkit/get-started/use-toolkit-with-angular'.`````
 - **Line 181, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'toolkit/get-started/build-a-sharepoint-web-part'.`````
 - **Line 183, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'toolkit/get-started/build-a-microsoft-teams-tab'.`````
 - **Line 185, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'toolkit/get-started/build-a-microsoft-teams-sso-tab'.`````
 - **Line [...]

2021-09-07 21:04 UTC, opbld31 commented
Docs Build status updates of commit _[2abfb71](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2abfb713907e296abb30e1eed0ac42b6d1619d90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-14008) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-14008) (>= graph-rest-1.0) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/people-picker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-sso-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-angular.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-angular.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-angular?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-14008) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams-msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams-msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-14008) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109072103033023-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=7jrwWPQOe5RHWMow83HwQq5MzO91VTLEfSH%2BB7zX6ko%3D&st=2021-09-07T20%3A59%3A44Z&se=2021-10-08T21%3A04%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-07 21:28 UTC, elisenyang commented on concepts/toc.yml
> +              - name: Msal provider
Thanks, I updated everywhere to MSAL provider, MSAL2 provider, and Teams MSAL2 provider

2021-09-07 21:29 UTC, opbld31 commented
Docs Build status updates of commit _[eaa5f32](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eaa5f32e7f5ac09e66249c98c36d55104c507a2f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-web-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-14008) | [Details](#user-content-503a40948b2b1e2e63e6151dc1e4bb1d-73592367)
[concepts/toolkit/get-started/use-toolkit-with-angular.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-angular.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-angular?branch=pr-en-us-14008) | [Details](#user-content-1535edd6610d86edaba987974784e107-73592367)
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-react.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-14008) | [Details](#user-content-2395b3418b59880b7dfa29c2a278b30f-73592367)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-14008) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-14008) (>= graph-rest-1.0) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/people-picker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-sso-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-14008) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams-msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams-msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-14008) |

<a id="503a40948b2b1e2e63e6151dc1e4bb1d-73592367"></a>
### [concepts/toolkit/get-started/build-a-web-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-web-app.md)
 - **Line 39, Column 126**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#migrating-from-msalprovider-to-msal2provider' in 'toolkit/providers/msal2.md', did you mean '#migrating-from-msal-provider-to-msal2-provider'?`````

<a id="1535edd6610d86edaba987974784e107-73592367"></a>
### [concepts/toolkit/get-started/use-toolkit-with-angular.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-angular.md)
 - **Line 40, Column 119**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#migrating-from-msalprovider-to-msal2provider' in 'toolkit/providers/msal2.md', did you mean '#migrating-from-msal-provider-to-msal2-provider'?`````

<a id="2395b3418b59880b7dfa29c2a278b30f-73592367"></a>
### [concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-react.md)
 - **Line 74, Column 119**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#migrating-from-msalprovider-to-msal2provider' in 'toolkit/providers/msal2.md', did you mean '#migrating-from-msal-provider-to-msal2-provider'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109072127523865-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=q9VfvDie%2FAxyP2UOeOLo%2FEZqh8%2BdBfG1T1JOCyIOoDM%3D&st=2021-09-07T21%3A24%3A32Z&se=2021-10-08T21%3A29%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub  [...]

2021-09-07 21:40 UTC, opbld33 commented
Docs Build status updates of commit _[1340478](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1340478826454c24d15688c9812c390c76a895a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-14008) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-14008) (>= graph-rest-1.0) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/people-picker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-sso-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-angular.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-angular.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-angular?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-14008) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams-msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams-msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-14008) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109072136028272-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=aRn5pcFgqqk91ChTFZCdW%2BOtdHPAjQdwcJM6kc4vbGM%3D&st=2021-09-07T21%3A35%3A02Z&se=2021-10-08T21%3A40%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 01:38 UTC, opbld33 commented
Docs Build status updates of commit _[7a7eee8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a7eee8f04c955db4f2f52c86a8422f7b30971b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-14008) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-14008) (>= graph-rest-1.0) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/people-picker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-sso-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-angular.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-angular.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-angular?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-14008) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams-msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams-msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-14008) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109080135228731-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=HDP%2B%2F3KFLk1tLlmSiH0VgM3V0PzfQB%2BSj1ynlPpawZY%3D&st=2021-09-08T01%3A33%3A36Z&se=2021-10-09T01%3A38%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 01:40 UTC, opbld30 commented
Docs Build status updates of commit _[cc2d1b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc2d1b020f4da31925de776fd315380e738e7d68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-14008) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-14008) (>= graph-rest-1.0) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/people-picker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-sso-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-angular.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-angular.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-angular?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-14008) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams-msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams-msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-14008) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109080136001830-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=I5r%2FjPu%2B5zhauE%2BBc7yXWZ6txl2xUBabZTJo2QceRLk%3D&st=2021-09-08T01%3A35%3A25Z&se=2021-10-09T01%3A40%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 01:42 UTC, opbld34 commented
Docs Build status updates of commit _[8b39a11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b39a1111bf8342ad59d2e7415a6baeb13d14d33)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-14008) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-14008) (>= graph-rest-1.0) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/people-picker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-sso-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-angular.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-angular.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-angular?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-14008) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams-msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams-msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-14008) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109080138595289-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=cf3PX9ZmsRHHapLRGe9z4qLcKJ2bhVwk1Bdqj2Sahgw%3D&st=2021-09-08T01%3A37%3A09Z&se=2021-10-09T01%3A42%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 01:43 UTC, opbld30 commented
Docs Build status updates of commit _[5d40568](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d405684fb07dc9022c1805c5dac57fd4cf12e2d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-14008) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-14008) (>= graph-rest-1.0) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/people-picker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-sso-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-angular.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-angular.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-angular?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-14008) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams-msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams-msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-14008) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109080142103631-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=jXQMCw1ZiSX01JOIzqR2aB30duJq2oB8gAK4Imyay%2BU%3D&st=2021-09-08T01%3A38%3A57Z&se=2021-10-09T01%3A43%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 02:01 UTC, opbld31 commented
Docs Build status updates of commit _[9537350](https://github.com/microsoftgraph/microsoft-graph-docs/commits/95373503d1bcb8618a58341ca3a740e2e5c27346)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-14008) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-14008) (>= graph-rest-1.0) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/people-picker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-sso-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-angular.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-angular.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-angular?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-14008) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams-msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams-msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-14008) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109080159293778-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=EvwP7AvWcphsu5k97VHcWAcpuqzCGEj%2B5tWAqVYAhEs%3D&st=2021-09-08T01%3A56%3A36Z&se=2021-10-09T02%3A01%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 02:03 UTC, opbld30 commented
Docs Build status updates of commit _[07dddb1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/07dddb1b1d925b1cf1c7763b720c251e4a048b39)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-14008) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-14008) (>= graph-rest-1.0) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/people-picker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-sso-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-angular.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-angular.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-angular?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-14008) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams-msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams-msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-14008) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109080201119191-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=XqFfTmxtmt13jtSO8%2BAXQf3sVWhK4PnlLOCVNkgCtq8%3D&st=2021-09-08T01%3A58%3A22Z&se=2021-10-09T02%3A03%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 02:05 UTC, opbld30 commented
Docs Build status updates of commit _[95abbd2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/95abbd25a3184161d2a35e0fdc0f9144d0006b53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-14008) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-14008) (>= graph-rest-1.0) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-14008) |
[concepts/toolkit/components/people-picker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-sso-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-sso-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-angular.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-angular.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-angular?branch=pr-en-us-14008) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-14008) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-14008) |
[concepts/toolkit/providers/msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams-msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams-msal2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams-msal2?branch=pr-en-us-14008) |
[concepts/toolkit/providers/teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mgt/next/concepts/toolkit/providers/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-14008) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109080202211605-14008%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=x04EEk%2FWMt96lUBctSiRgSol2u9HL9RGI1Asrf89t%2Bk%3D&st=2021-09-08T02%3A00%3A16Z&se=2021-10-09T02%3A05%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 02:12 UTC, merged