APIs to hide/unhide chat for a user
microsoftgraph/microsoft-graph-docs pull request #14012
Opened 2021-08-27 00:38 UTC by RamjotSingh

2021-08-31 21:41 UTC, JarbasHorst requested changes

2021-08-31 21:41 UTC, JarbasHorst commented on api-reference/beta/api/chat-hideforuser.md
> +description: "Hide chat for a user"
Articles help readers and translation software identify the nouns and modifiers in a sentence. For clarity, please add a before chat. Suggested revision:

- Hide a chat for a user.

2021-08-31 21:41 UTC, JarbasHorst commented on api-reference/beta/api/chat-hideforuser.md
> +Hides [chat](../resources/chat.md) for a user.
Articles help readers and translation software identify the nouns and modifiers in a sentence. For clarity, please add a before chat. Suggested revision:

- Hides a [chat]...

2021-08-31 21:41 UTC, JarbasHorst commented on api-reference/beta/api/chat-hideforuser.md
> +> **Note:** Chat will be automatically unhidden for the user if an action (like sending a message) is taken on the chat.
For clarity, I recommend you to rephrase this sentence. Suggested revision:

- A chat is automatically unhidden for a user if an action such as *Send Message* is taken at chat level.

2021-08-31 21:41 UTC, JarbasHorst commented on api-reference/beta/api/chat-hideforuser.md
> +In the request body, supply JSON representation of the parameters.
Please, add a before JSON. Suggested revision:

- ...supply a JSON...

2021-08-31 21:41 UTC, JarbasHorst commented on api-reference/beta/api/chat-hideforuser.md
> +|user|[teamworkUserIdentity](../resources/teamworkuseridentity.md)|User to hide the chat for. **In delegated, a user may only hide chat for themselves**.|
For conformity and clarity, please 

- add mode after delegated
- replace a user with users
- add a before chat

 Suggested revision:

- In delegated mode, users may only hide a chat for themselves.

2021-08-31 21:41 UTC, JarbasHorst commented on api-reference/beta/api/chat-hideforuser.md
> +|tenantId|String|Tenant id of the user.|
In regular text, please use ID as the abbreviation for identity.

2021-08-31 21:41 UTC, JarbasHorst commented on api-reference/beta/api/chat-unhideforuser.md
> +description: "Unhide chat for a user"
Please, add a period at the end of the sentence.

2021-08-31 21:41 UTC, JarbasHorst commented on api-reference/beta/api/chat-unhideforuser.md
> +description: "Unhide chat for a user"
Articles help readers and translation software identify the nouns and modifiers in a sentence. For clarity, please add a before chat. Suggested revision:

- Unhide a chat for a user.

2021-08-31 21:41 UTC, JarbasHorst commented on api-reference/beta/api/chat-unhideforuser.md
> +Unhides [chat](../resources/chat.md) for a user.
Articles help readers and translation software identify the nouns and modifiers in a sentence. For clarity, please add a before chat. Suggested revision:

- Unhide a chat for a user.

2021-08-31 21:41 UTC, JarbasHorst commented on api-reference/beta/api/chat-unhideforuser.md
> +|user|[teamworkUserIdentity](../resources/teamworkuseridentity.md)|User to unhide the chat for. **In delegated, a user may only unhide chat for themselves**.|
For conformity and clarity, please 

- add mode after delegated
- replace a user with users
- add a before chat

 Suggested revision:

- In delegated mode, users may only unhide a chat for themselves.

2021-08-31 21:41 UTC, JarbasHorst commented on api-reference/beta/api/chat-unhideforuser.md
> +|tenantId|String|Tenant id of the user.|
In regular text, please use ID as the abbreviation for identity.

2021-08-31 21:41 UTC, JarbasHorst commented on api-reference/beta/api/chat-unhideforuser.md
> +In the request body, supply JSON representation of the parameters.
Please, add a before JSON. Suggested revision:

- ...supply a JSON...

2021-08-31 21:41 UTC, JarbasHorst commented on api-reference/beta/resources/chat.md
> +|[hideForUser](../api/chat-hideforuser.md)|None|Hide chat for a user.|
For clarity and consistency, please add a before chat. Suggested revision:

- Hide a chat..

2021-08-31 21:41 UTC, JarbasHorst commented on api-reference/beta/resources/chat.md
> +|[unhideForUser](../api/chat-unhideforuser.md)|None|Unhide chat for a user.|
For clarity and consistency, please add a before chat. Suggested revision:

- Unhide a chat..

2021-09-01 19:25 UTC, JarbasHorst requested changes

2021-09-01 19:25 UTC, JarbasHorst commented on api-reference/v1.0/api/chat-post-messages.md
> +Send a new [chatMessage](../resources/chatmessage.md) in the specified [chat](../resources/chat.md). This API cannot create a new chat; you must use the [list chats](chat-list.md) method to retrieve
Please, change the sentence to conform with the Microsoft style. Suggested revision:

- This API can't create a new chat; ...chat before you can create a chat message.

2021-09-01 19:25 UTC, JarbasHorst commented on api-reference/v1.0/api/chat-post-messages.md
>  > **Note**: We don't recommend that you use this API for data migration. It does not have the throughput necessary for a typical migration.
Please, use common contractions in your articles, such as doesn't, to create a friendly, informal tone. In this case, please replace does not with doesn't

2021-09-01 19:25 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "ApiChange": "Action",
Action isn't on the list of approved values for ApiChange. Please change this to "Method".

2021-09-01 19:25 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "ApiChange": "Action",
Action isn't on the list of approved values for ApiChange. Please change this to "Method".

2021-09-01 19:25 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the **isHidden** property to [chatViewpoint](https://docs.microsoft.com/en-us/graph/api/resources/chatViewpoint?view=graph-rest-beta) resource.",
Articles help readers and translation software identify the nouns and modifiers in a sentence. Please, add the before chatViewpoint. Suggested revision:

- ...property to the [chatViewpoint]...

2021-09-01 19:25 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the [unhideForUser](https://docs.microsoft.com/en-us/graph/api/unhideForUser?view=graph-rest-beta) method to the [unhideForUser](https://docs.microsoft.com/en-us/graph
Please, replace "[unhideForUser](https://docs.microsoft.com/en-us/graph/api/unhideForUser?view=graph-rest-beta) resource" with the correct resource.

2021-09-01 19:25 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the [hideForUser](https://docs.microsoft.com/en-us/graph/api/hideForUser?view=graph-rest-beta) method to the [hideForUser](https://docs.microsoft.com/en-us/graph/api/h
Please, replace "[hideForUser](https://docs.microsoft.com/en-us/graph/api/hideForUser?view=graph-rest-beta) resource" with the correct resource.

2021-10-11 19:18 UTC, JarbasHorst commented
@RamjotSingh, checking to see if you have any questions regarding some of the feedback I provided?

2021-11-01 20:21 UTC, JarbasHorst commented
Hi @RamjotSingh, I just dropped by to see if you have any questions regarding some of the feedback I provided?

2021-11-11 18:42 UTC, opbld30 commented
Docs Build status updates of commit _[790e98f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/790e98f91e952c4dac9ed1b8af357e63f6c32cf1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14012) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111111839412055-14012%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T18%3A42%3A02Z&sr=b&sp=r&sig=BK3qnB7ccZsG3Gr9EcoJVEFnkCEZMsMXhtFCVWXv%2FBw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-14 16:29 UTC, opbld30 commented
Docs Build status updates of commit _[b33fa8f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b33fa8fa98e6a4bffb639170b23c5c66af757c19)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14012) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14012) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111141628214686-14012%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-15T16%3A29%3A47Z&sr=b&sp=r&sig=wZBi%2BfKBSMdEuw6XPw5SyB%2FYsXpe8ycRifR4LFi7HaA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-14 16:38 UTC, opbld32 commented
Docs Build status updates of commit _[21cb1df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21cb1df576b4268cf54b74f100bc99f5a12f1369)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14012) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14012) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111141637023521-14012%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-15T16%3A38%3A36Z&sr=b&sp=r&sig=Chgp9LkuwMJwIhj3d5MEwhnQEI40mdz3TivKcAMmiW4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-15 21:25 UTC, JarbasHorst commented
@RamjotSingh, please include an update to the toc.yml file in the beta folder, to surface these two new APIs in the TOC.

2021-11-15 21:28 UTC, JarbasHorst requested changes

2021-11-15 21:28 UTC, JarbasHorst commented on api-reference/beta/api/chat-hideforuser.md
> +Hides a [chat](../resources/chat.md) for a user.
The introductory sentence for API topics should start with an imperative verb. Suggested revision:

- Hide a [chat]...

2021-11-15 21:28 UTC, JarbasHorst commented on api-reference/beta/api/chat-unhideforuser.md
> +Unhides a [chat](../resources/chat.md) for a user.
The introductory sentence for API topics should start with an imperative verb. Suggested revision:

- Unhide a [chat]...

2021-11-15 21:28 UTC, JarbasHorst commented on api-reference/beta/api/chatmessage-post.md
> +| Application                            | Teamwork.Migrate.All. |
For consistency, please remove the period after Teamwork.Migrate.All. Suggested revision:

- | Application                            | Teamwork.Migrate.All |

2021-11-15 21:28 UTC, JarbasHorst commented on api-reference/beta/resources/chatviewpoint.md
> +|isHidden|Boolean|Represents if the chat is hidden for the user.|
Hi @RamjotSingh,

according to Anand, the description should be consistency. Based on his suggestion, you should either use:

- (*my favorite*) Represents if the chat is hidden for the current user.
and update the text for the next item to also have the term current user.

OR

- Represents if the chat is hidden for the calling user.

2021-11-15 21:28 UTC, JarbasHorst commented on api-reference/v1.0/api/chatmessage-post.md
> +| Application                            | Teamwork.Migrate.All. |
For consistency, please remove the period after Teamwork.Migrate.All. Suggested revision:

- | Application                            | Teamwork.Migrate.All |

2021-11-15 21:28 UTC, JarbasHorst commented on api-reference/beta/resources/chat.md
> +|[Hide a chat for user](../api/chat-hideforuser.md)|None|Hide a chat for a user.|
For consistency with other entries in this table, I recommend you to update the values in the Method column to not contain "for user" and the article. Suggested revision:

- Hide chat
- Unhide chat

I recommend you to also use these values in the TOC.

2021-11-17 03:05 UTC, opbld31 commented
Docs Build status updates of commit _[3b00252](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b00252036c08760d43bee51b17fd3d4da0d87f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14012) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14012) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111170303485488-14012%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T03%3A05%3A27Z&sr=b&sp=r&sig=k3X6kh05%2BSxQ6DU0oeUHwavBkb1cwJLmEosRCDtqj%2Fs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 21:22 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-11-20 01:58 UTC, opbld32 commented
Docs Build status updates of commit _[689138d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/689138df2e78232a3ac37bc5680ddaa5486df239)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14012) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14012) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200156099584-14012%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T01%3A58%3A06Z&sr=b&sp=r&sig=jpG9e6TCIv3HAfnkuNO%2FQMWe1aogFVDbCNq%2FpQ8RmTQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 01:59 UTC, Lauragra approved these changes

2021-11-20 02:00 UTC, opbld33 commented
Docs Build status updates of commit _[430b1df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/430b1df5ae92798162677a0d87ce85883c6ca149)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14012) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14012) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200157476225-14012%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T02%3A00%3A07Z&sr=b&sp=r&sig=JMy%2B6TpIvQEC5wQf8PkppwJWupsKjp90Kk%2Fylo%2FiER4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 02:01 UTC, opbld33 commented
Docs Build status updates of commit _[20e2be3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20e2be3588a83020b42f84681508d03a19e9e177)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-hideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-hideforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chat-unhideforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chat-unhideforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-unhideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/resources/chatviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/resources/chatviewpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatviewpoint?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-hideforuser?view=graph-rest-beta&branch=pr-en-us-14012) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14012) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14012) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-08-27-hideunhidechatapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200158401621-14012%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T02%3A01%3A41Z&sr=b&sp=r&sig=IX%2BlBhEI9dGDkzaPK1iwC2GG0T%2FAmaR%2BDSAdMZy1WjE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 02:31 UTC, merged