Updating Organizational Branding beta
microsoftgraph/microsoft-graph-docs pull request #14107
Opened 2021-09-02 00:27 UTC by AlexanderMars

2021-09-02 00:28 UTC, jasonjoh commented
Docs Build status updates of commit _[e728ea0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e728ea034d3fe716d32770adb655f806f51dbd4e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-8d3efe78)

<a id="b474f523557c213b527ea0fc6e060a09-8d3efe78"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-list.md'.`````
 - **Line 33, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-create.md'.`````
 - **Line 34, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-get.md'.`````
 - **Line 35, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-update.md'.`````
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-delete.md'.`````
 - **Line 37, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-list-localizations.md'.`````
 - **Line 37, Column 76**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandinglocalization.md'.`````
 - **Line 38, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-post-localizations.md'.`````
 - **Line 38, Column 99**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandinglocalization.md'.`````
 - **Line 62, Column 34**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/loginpagetextvisibilitysettings.md'.`````
 - **Line 71, Column 16**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandinglocalization.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109020027078152-14107%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=zXyB5xId86FFlnPrFtqaor%2Fr6hEI7MB3C8KjwkHKMq8%3D&st=2021-09-02T00%3A23%3A56Z&se=2021-10-03T00%3A28%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 00:42 UTC, jasonjoh commented
Docs Build status updates of commit _[e728ea0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e728ea034d3fe716d32770adb655f806f51dbd4e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-89524edc)

<a id="b474f523557c213b527ea0fc6e060a09-89524edc"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-list.md'.`````
 - **Line 33, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-create.md'.`````
 - **Line 34, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-get.md'.`````
 - **Line 35, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-update.md'.`````
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-delete.md'.`````
 - **Line 37, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-list-localizations.md'.`````
 - **Line 37, Column 76**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandinglocalization.md'.`````
 - **Line 38, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-post-localizations.md'.`````
 - **Line 38, Column 99**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandinglocalization.md'.`````
 - **Line 62, Column 34**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/loginpagetextvisibilitysettings.md'.`````
 - **Line 71, Column 16**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandinglocalization.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109020040459571-14107%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=watPWRQnmN10OiLG%2F7Ns6INBKg%2B4OFC0K3a5XEgza0o%3D&st=2021-09-02T00%3A37%3A40Z&se=2021-10-03T00%3A42%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 01:18 UTC, jasonjoh commented
Docs Build status updates of commit _[05eb241](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05eb24181cdf66caa363daa5392ce12ef321c3f0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-d321febb)
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-9ea1bc6aa29288de892ad53f00d53c7a-d321febb)

<a id="b474f523557c213b527ea0fc6e060a09-d321febb"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-list.md'.`````
 - **Line 33, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-create.md'.`````
 - **Line 34, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-get.md'.`````
 - **Line 35, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-update.md'.`````
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-delete.md'.`````
 - **Line 37, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-list-localizations.md'.`````
 - **Line 38, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-post-localizations.md'.`````
 - **Line 62, Column 34**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/loginpagetextvisibilitysettings.md'.`````

<a id="9ea1bc6aa29288de892ad53f00d53c7a-d321febb"></a>
### [api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-list.md'.`````
 - **Line 33, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-create.md'.`````
 - **Line 34, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-get.md'.`````
 - **Line 35, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-update.md'.`````
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109020117221815-14107%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=MWy7DYKJJOHvqSJRd7j7Xlbeo4wYGJZ65PEMznTQlUw%3D&st=2021-09-02T01%3A13%3A47Z&se=2021-10-03T01%3A18%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 01:34 UTC, jasonjoh commented
Docs Build status updates of commit _[046c8a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/046c8a201f18a64f7418771a8886e2edb1c7f9bc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-77b91d41)
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-9ea1bc6aa29288de892ad53f00d53c7a-77b91d41)
[azure-docs](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/azure-docs) | :white_check_mark:Succeeded | |

<a id="b474f523557c213b527ea0fc6e060a09-77b91d41"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-list-localizations.md'.`````
 - **Line 33, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-post-localizations.md'.`````
 - **Line 34, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-get.md'.`````
 - **Line 35, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-update.md'.`````
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-delete-localizations.md'.`````

<a id="9ea1bc6aa29288de892ad53f00d53c7a-77b91d41"></a>
### [api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-list.md'.`````
 - **Line 33, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-create.md'.`````
 - **Line 34, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-get.md'.`````
 - **Line 35, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-update.md'.`````
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109020133036284-14107%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=RK8dnBpec1LnPZiGPJNMnlENGTz77nBoBhB01bzCL%2Bs%3D&st=2021-09-02T01%3A29%3A48Z&se=2021-10-03T01%3A34%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 20:41 UTC, jasonjoh commented
Docs Build status updates of commit _[c3fee79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3fee7990a254600706b8b14baa66e53f9c473dc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-32348d97)
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-9ea1bc6aa29288de892ad53f00d53c7a-32348d97)
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[azure-docs](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/azure-docs) | :white_check_mark:Succeeded | |

<a id="b474f523557c213b527ea0fc6e060a09-32348d97"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-list-localizations.md'.`````
 - **Line 34, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-get.md'.`````
 - **Line 35, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-update.md'.`````
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-delete-localizations.md'.`````

<a id="9ea1bc6aa29288de892ad53f00d53c7a-32348d97"></a>
### [api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-list.md'.`````
 - **Line 33, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-create.md'.`````
 - **Line 34, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-get.md'.`````
 - **Line 35, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-update.md'.`````
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109022039403853-14107%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=z%2B7%2BIlPaQGLm%2FhEK7xhpeK7RWTPdKEA97qHRNR9AGKc%3D&st=2021-09-02T20%3A36%3A11Z&se=2021-10-03T20%3A41%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 21:22 UTC, jasonjoh commented
Docs Build status updates of commit _[a61f586](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a61f586addabfba221d27e3978d77385f2a2af8e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-ac621811)
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-9ea1bc6aa29288de892ad53f00d53c7a-ac621811)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[azure-docs](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/azure-docs) | :white_check_mark:Succeeded | |

<a id="b474f523557c213b527ea0fc6e060a09-ac621811"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-list-localizations.md'.`````
 - **Line 35, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-update.md'.`````
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-delete-localizations.md'.`````

<a id="9ea1bc6aa29288de892ad53f00d53c7a-ac621811"></a>
### [api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-list.md'.`````
 - **Line 33, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-create.md'.`````
 - **Line 34, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-get.md'.`````
 - **Line 35, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-update.md'.`````
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109022119359968-14107%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=VDrTzhDrWZZwMrP3qTbrTdVW43eRPrpFwQDz62EHPVI%3D&st=2021-09-02T21%3A17%3A11Z&se=2021-10-03T21%3A22%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 22:21 UTC, jasonjoh commented
Docs Build status updates of commit _[b0b4318](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0b431847d3f2dccdca2f380beabe7e87180b941)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-cd314e52)
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-9ea1bc6aa29288de892ad53f00d53c7a-cd314e52)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[azure-docs](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/azure-docs) | :white_check_mark:Succeeded | |

<a id="b474f523557c213b527ea0fc6e060a09-cd314e52"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-list-localizations.md'.`````
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-delete-localizations.md'.`````

<a id="9ea1bc6aa29288de892ad53f00d53c7a-cd314e52"></a>
### [api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-list.md'.`````
 - **Line 33, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-create.md'.`````
 - **Line 34, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-get.md'.`````
 - **Line 35, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-update.md'.`````
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109022219274668-14107%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=aKlwwl6YKXSfwY2vZr85o8kDh%2BWA3dY4WEX5%2Byu%2BDGo%3D&st=2021-09-02T22%3A16%3A22Z&se=2021-10-03T22%3A21%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 22:46 UTC, jasonjoh commented
Docs Build status updates of commit _[d048489](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0484892f08d60c0f038922013bb8402f89472f4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-c9f9239b)
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-9ea1bc6aa29288de892ad53f00d53c7a-c9f9239b)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[azure-docs](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/azure-docs) | :white_check_mark:Succeeded | |

<a id="b474f523557c213b527ea0fc6e060a09-c9f9239b"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-list-localizations.md'.`````
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-delete-localizations.md'.`````

<a id="9ea1bc6aa29288de892ad53f00d53c7a-c9f9239b"></a>
### [api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-list.md'.`````
 - **Line 33, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-create.md'.`````
 - **Line 34, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-get.md'.`````
 - **Line 35, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-update.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109022244325648-14107%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=ER37Af10uTDSHc2oY%2Bus0nbJufG8jPviV2QJQGXcFP0%3D&st=2021-09-02T22%3A41%3A15Z&se=2021-10-03T22%3A46%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 23:56 UTC, jasonjoh commented
Docs Build status updates of commit _[6b58d89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b58d89d5fd3811437994da1e08bc55911af0f66)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-e117decd)
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-9ea1bc6aa29288de892ad53f00d53c7a-e117decd)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[azure-docs](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/azure-docs) | :white_check_mark:Succeeded | |

<a id="b474f523557c213b527ea0fc6e060a09-e117decd"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-delete-localizations.md'.`````

<a id="9ea1bc6aa29288de892ad53f00d53c7a-e117decd"></a>
### [api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-list.md'.`````
 - **Line 33, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-create.md'.`````
 - **Line 34, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-get.md'.`````
 - **Line 35, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-update.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109022354440351-14107%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=X5NOfukkc4Z73w9jinPJwkT47%2Bul06LbMKfS1CNODEQ%3D&st=2021-09-02T23%3A51%3A20Z&se=2021-10-03T23%3A56%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 01:18 UTC, jasonjoh commented
Docs Build status updates of commit _[325bd00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/325bd00f9fb6afc15f2bd772aa31982b4eed737d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-8471b3d0b7d190ab11548afc3d18d494-5aea459f)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-5aea459f)
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-9ea1bc6aa29288de892ad53f00d53c7a-5aea459f)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[azure-docs](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/azure-docs) | :white_check_mark:Succeeded | |

<a id="8471b3d0b7d190ab11548afc3d18d494-5aea459f"></a>
### [api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="b474f523557c213b527ea0fc6e060a09-5aea459f"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-delete-localizations.md'.`````

<a id="9ea1bc6aa29288de892ad53f00d53c7a-5aea459f"></a>
### [api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-list.md'.`````
 - **Line 33, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandinglocalization-create.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109030116455637-14107%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=qjhnqx7H0tBZFZR5s%2BugKWjtQ9PeqUAxMo3V%2BtOAX6Y%3D&st=2021-09-03T01%3A13%3A24Z&se=2021-10-04T01%3A18%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsof [...]

2021-09-04 01:22 UTC, jasonjoh commented
Docs Build status updates of commit _[384e673](https://github.com/microsoftgraph/microsoft-graph-docs/commits/384e6738f380d37ff8fc743d09ec6cbfad0d5394)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-e4d188c4)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b474f523557c213b527ea0fc6e060a09-e4d188c4"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-delete-localizations.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109040120377071-14107%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=7twuRRGD7pYud93cXv0%2FL6MCdAdeYQVavCwxmh1DQbw%3D&st=2021-09-04T01%3A17%3A10Z&se=2021-10-05T01%3A22%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 04:05 UTC, alvarorahul commented on api-reference/beta/api/organizationalbranding-get.md
> +| Delegated (work or school account)     | Organization.Read.All, User.Read, User.Read.All, User.ReadBasic.All |
other files also have similar issue

2021-09-08 20:34 UTC, opbld31 commented
Docs Build status updates of commit _[2d2801d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d2801d8a5b27c5e0b05f7c4dde00f5c733501a7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-40e9ebbf)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b474f523557c213b527ea0fc6e060a09-40e9ebbf"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-delete-localizations.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109082032299765-14107%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=xQ6%2FV4guKJWLc3Lt4lztkKDwVRp6zCJ7ThVj1mAPWHY%3D&st=2021-09-08T20%3A29%3A52Z&se=2021-10-09T20%3A34%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 20:37 UTC, opbld32 commented
Docs Build status updates of commit _[14e143b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14e143be7ae0f15ba74e6434856ec93bf1572645)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-89fac882)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b474f523557c213b527ea0fc6e060a09-89fac882"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-delete-localizations.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109082035123845-14107%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=mcIHWIXuH3AU8m86dKGp%2BbUQlajoDsBClBVa%2F7FZfNs%3D&st=2021-09-08T20%3A32%3A02Z&se=2021-10-09T20%3A37%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 20:46 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbranding-get.md
> +| Delegated (work or school account)     | Organization.Read.All, User.Read, User.Read.All, User.ReadBasic.All |
Updated

2021-09-08 20:47 UTC, opbld31 commented
Docs Build status updates of commit _[836d393](https://github.com/microsoftgraph/microsoft-graph-docs/commits/836d3932b0d42b12c92e963f59996f0b23409b3d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-38d762ec)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b474f523557c213b527ea0fc6e060a09-38d762ec"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbranding-delete-localizations.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109082045320326-14107%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=NPppCH3Y2i548U4lpec1NutiAzyTYwD4VTcOVshzz20%3D&st=2021-09-08T20%3A42%3A11Z&se=2021-10-09T20%3A47%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 20:55 UTC, opbld34 commented
Docs Build status updates of commit _[ebd17f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ebd17f67ef243712a07be0778f17fcb85a359ac4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109082053252934-14107%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=kRCMMdHckAwWvwfWFigw%2B5CRzUbW6CWn9hpoI%2FnEZwU%3D&st=2021-09-08T20%3A50%3A02Z&se=2021-10-09T20%3A55%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 21:04 UTC, opbld30 commented
Docs Build status updates of commit _[d1a3769](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1a376975d1807d939d1e07300dd769ab8f0c862)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-e6c8be16)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-e6c8be16)
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-53221b760b874006c0148a869739927c-e6c8be16)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-e6c8be16)
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-9ea1bc6aa29288de892ad53f00d53c7a-e6c8be16)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-e6c8be16)
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-349a3b5c4343e76652123be570b41838-e6c8be16)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-e6c8be16)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |

<a id="b297769dd29b09fdec28528aefc029f0-e6c8be16"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 381**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandingproperties.md'.`````
 - **Line 48, Column 285**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandingproperties.md'.`````
 - **Line 49, Column 250**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandingproperties.md'.`````
 - **Line 50, Column 227**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandingproperties.md'.`````
 - **Line 51, Column 271**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandingproperties.md'.`````
 - **Line 52, Column 325**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandingproperties.md'.`````
 - **Line 53, Column 201**: **[Warning-[file-not-found](https://revi [...]

2021-09-08 21:46 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbranding-get.md
> +{
done + added:
squareDarkLogo
squareDarkLogoRelativeUrl

2021-09-09 00:20 UTC, opbld33 commented
Docs Build status updates of commit _[526ccf1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/526ccf1edc166bf38681e57cc1e1b341942e2a0d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ab169623)
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-349a3b5c4343e76652123be570b41838-ab169623)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-ab169623)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-ab169623"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml)
 - **Line 11522, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/organizationalbrandingproperties.md'.`````
 - **Line 11525, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/organizationalbrandingproperties-create.md'.`````
 - **Line 11527, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/organizationalbrandingproperties-get.md'.`````
 - **Line 11529, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/organizationalbrandingproperties-update.md'.`````
 - **Line 11531, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/organizationalbrandingproperties-delete.md'.`````
 - **Line 11533, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/organizationalbrandingpropertieslocalization-create.md'.`````
 - **Line 11535, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/organizationalbrandingpropertieslocalization-get.md'.`````
 - **Line 11537, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'a [...]

2021-09-09 00:44 UTC, opbld33 commented
Docs Build status updates of commit _[77a5430](https://github.com/microsoftgraph/microsoft-graph-docs/commits/77a5430678473c5178b04ee3cebe9ada3269947d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-0e8ec8f8)
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-349a3b5c4343e76652123be570b41838-0e8ec8f8)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-0e8ec8f8)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-0e8ec8f8"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml)
 - **Line 11534, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11534, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11535, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````
 - **Line 11535, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````
 - **Line 11543, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/organizationalbrandinglocalization-update.md.md'.`````

<a id="349a3b5c4343e76652123be570b41838-0e8ec8f8"></a>
### [api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md)
 - **Line 57, Column 68**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandingproperties.md'.`````
 - **Line 56, Column 98**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/active-directory-b2b-what-is-azure-ad-b2b' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 57, Column 145**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/f [...]

2021-09-09 00:49 UTC, opbld34 commented
Docs Build status updates of commit _[7bed503](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7bed503049074165ef7f17dc9ae32f0b8d71d698)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-9a0a57e6)
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-349a3b5c4343e76652123be570b41838-9a0a57e6)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-9a0a57e6)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-9a0a57e6"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml)
 - **Line 11534, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11534, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11535, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````
 - **Line 11535, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````

<a id="349a3b5c4343e76652123be570b41838-9a0a57e6"></a>
### [api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md)
 - **Line 57, Column 68**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandingproperties.md'.`````
 - **Line 56, Column 98**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/active-directory-b2b-what-is-azure-ad-b2b' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 57, Column 145**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/fundamentals/customize-branding' will be broken in isolated environments. Replace with a relative link.`````

<a id="764f51696cc127b438adea3cf6d42ccb-9a0a57e6"></a>
### [api-reference/beta/resources/organization.md](https://github.com/micr [...]

2021-09-09 20:49 UTC, FaithOmbongi requested changes
I've only reviewed the resources & TOC. I'll review the methods tomorrow.

- BTW, the organizationalBrandingProperties resource is required. In the Methods section, value is **None.**.
   -   All the properties should be as listed in the other resources except remove the text "_Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md)._"

2021-09-09 20:49 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbranding.md
> +|usernameHintText|String| String that shows as the hint in the username textbox on the sign in screen. This text must be Unicode, without links or code, and can't exceed 64 characters.|
- Proposing alphabetical ordering of the properties list.
- Removed properties that aren't in the public metadata
- Added the inheritance relationship

```suggestion
| backgroundColor | String | Color that will appear in place of the background image in low-bandwidth connections. We recommend that you use the primary color of your banner logo or your organization color. Specify this in hexadecimal format, for example, white is `#FFFFFF`. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| backgroundImage | Stream | Image that appears as the background of the sign-in page. The allowed types are PNG or JPEG not smaller than 300 KB and not larger than 1920 × 1080 pixels. A smaller image will reduce bandwidth requirements and make the page load faster. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| backgroundImageRelativeUrl | String | A relative URL for the **backgroundImage** property that is combined with a CDN base URL from the **cdnList** to provide the version served by a CDN. Read-only. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| bannerLogo | Stream | A banner version of your company logo that appears on the sign-in page. The allowed types are PNG or JPEG no larger than 36 × 245 pixels. We recommend using a transparent image with no padding around the logo. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| bannerLogoRelativeUrl | String | A relative url for the **bannerLogo** property that is combined with a CDN base URL from the **cdnList** to provide the read-only version served by a CDN. Read-only. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| cdnList | String collection | A list of base URLs for all available CDN providers that are serving the assets of the current resource. Several CDN providers are used at the same time for high availability of read requests. Read-only. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| id | String | An identifier that represents the locale specified in the ISO 639-1 standard, for example English is `en-us` or `en`. The **id** for the default /branding is always the String types `0` or `default`. Read-only. <br/><br/>**NOTE:** Multiple branding for a single locale are currently not supported. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| signInPageText | String | Text that appears at the bottom of the sign-in box. You can use this to communicate additional information, such as the phone number to your help desk or a legal statement. This text must be Unicode and not exceed 1024 characters. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| squareLogo | Stream | A square version of your company logo that appears in Windows 10 out-of-box experiences (OOBE) and when Windows Autopilot is enabled for deployment. Allowed types are PNG or JPEG no larger than 240 x 240 pixels and no more than 10 KB in size. We recommend using a transparent image with no padding around the logo. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md).|
| squareLogoRelativeUrl | String | A relative url for the **squareLogo** property that is combined with a CDN base URL from the **cdnList** to provide the version served by a CDN. Read-only. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| usernameHintText | String | String that shows as the hint in the username textbox on the sign-in screen. This text must be a Unicode, without links or code, and can't exceed 64 characters. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
```

2021-09-09 20:49 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbranding.md
> +|localizations|[organizationalBrandingLocalization](../resources/organizationalbrandinglocalization.md) collection|Add different branding based on locale|
```suggestion
| localizations | [organizationalBrandingLocalization](../resources/organizationalbrandinglocalization.md) collection | Add different branding based on a locale. |
```

2021-09-09 20:49 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbranding.md
> +  "baseType": "Microsoft.DirectoryServices.organizationalBrandingProperties",
```suggestion
  "baseType": "microsoft.graph.organizationalBrandingProperties",
```

2021-09-09 20:49 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbranding.md
>  {
Please replace the JSON object with the following:
```
{
  "@odata.type": "#microsoft.graph.organizationalBranding",
  "id": "String (identifier)",
  "backgroundColor": "String",
  "backgroundImage": "Stream",
  "backgroundImageRelativeUrl": "String",
  "bannerLogo": "Stream",
  "bannerLogoRelativeUrl": "String",
  "cdnList": [
    "String"
  ],
  "signInPageText": "String",
  "squareLogo": "Stream",
  "squareLogoRelativeUrl": "String",
  "usernameHintText": "String"
}
```

2021-09-09 20:49 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbrandinglocalization.md
> +>**Note:** Branding is exposed as a property under organization with a collection of locale-specific localizations. **organizationalBrandingProperties** is an abstract class which defines properties
```suggestion
Supports creating branding for a locale.

Inherits from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md).
```

2021-09-09 20:49 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbrandinglocalization.md
> +|usernameHintText|String| String that shows as the hint in the username textbox on the sign in screen. This text must be Unicode, without links or code, and can't exceed 64 characters.|
```suggestion
| backgroundColor | String | Color that will appear in place of the background image in low-bandwidth connections. We recommend that you use the primary color of your banner logo or your organization color. Specify this in hexadecimal format, for example, white is `#FFFFFF`. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| backgroundImage | Stream | Image that appears as the background of the sign-in page. The allowed types are PNG or JPEG not smaller than 300 KB and not larger than 1920 × 1080 pixels. A smaller image will reduce bandwidth requirements and make the page load faster. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| backgroundImageRelativeUrl | String | A relative URL for the **backgroundImage** property that is combined with a CDN base URL from the **cdnList** to provide the version served by a CDN. Read-only. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| bannerLogo | Stream | A banner version of your company logo that appears on the sign-in page. The allowed types are PNG or JPEG no larger than 36 × 245 pixels. We recommend using a transparent image with no padding around the logo. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| bannerLogoRelativeUrl | String | A relative url for the **bannerLogo** property that is combined with a CDN base URL from the **cdnList** to provide the read-only version served by a CDN. Read-only. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| cdnList | String collection | A list of base URLs for all available CDN providers that are serving the assets of the current resource. Several CDN providers are used at the same time for high availability of read requests. Read-only. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| id | String | An identifier that represents the locale specified in the ISO 639-1 standard, for example English is `en-us` or `en`. The **id** for the default /branding is always the String types `0` or `default`. Read-only. <br/><br/>**NOTE:** Multiple branding for a single locale are currently not supported. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| signInPageText | String | Text that appears at the bottom of the sign-in box. You can use this to communicate additional information, such as the phone number to your help desk or a legal statement. This text must be Unicode and not exceed 1024 characters. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| squareLogo | Stream | A square version of your company logo that appears in Windows 10 out-of-box experiences (OOBE) and when Windows Autopilot is enabled for deployment. Allowed types are PNG or JPEG no larger than 240 x 240 pixels and no more than 10 KB in size. We recommend using a transparent image with no padding around the logo. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md).|
| squareLogoRelativeUrl | String | A relative url for the **squareLogo** property that is combined with a CDN base URL from the **cdnList** to provide the version served by a CDN. Read-only. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
| usernameHintText | String | String that shows as the hint in the username textbox on the sign-in screen. This text must be a Unicode, without links or code, and can't exceed 64 characters. Inherited from [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md). |
```

2021-09-09 20:49 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +            href: api/organizationalbranding-list-localizations.md
Just verify this entry. Looks off in the Preview site.

2021-09-10 10:43 UTC, opbld33 commented
Docs Build status updates of commit _[a0db3f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0db3f54da2de7599d4af99086df1b06d0161e48)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b967f591)
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-349a3b5c4343e76652123be570b41838-b967f591)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-b967f591)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-b967f591"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml)
 - **Line 11534, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11534, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11535, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````
 - **Line 11535, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````

<a id="349a3b5c4343e76652123be570b41838-b967f591"></a>
### [api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md)
 - **Line 57, Column 68**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandingproperties.md'.`````
 - **Line 56, Column 98**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/active-directory-b2b-what-is-azure-ad-b2b' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 57, Column 145**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.m [...]

2021-09-10 11:07 UTC, opbld32 commented
Docs Build status updates of commit _[91cc76a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/91cc76aa60437ee8937c66e7cc2789200e8fd82b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-2d48e1a0)
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-349a3b5c4343e76652123be570b41838-2d48e1a0)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-2d48e1a0)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-2d48e1a0"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml)
 - **Line 11534, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11534, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11535, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````
 - **Line 11535, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````

<a id="349a3b5c4343e76652123be570b41838-2d48e1a0"></a>
### [api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md)
 - **Line 57, Column 68**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandingproperties.md'.`````
 - **Line 56, Column 98**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/active-directory-b2b-what-is-azure- [...]

2021-09-10 11:47 UTC, opbld30 commented
Docs Build status updates of commit _[32d96cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32d96cf083664a8ea13291a42f1b6ecd96066a7b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-4255d307)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-4255d307)
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-349a3b5c4343e76652123be570b41838-4255d307)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-4255d307"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml)
 - **Line 11534, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11534, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11535, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````
 - **Line 11535, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````

<a id="764f51696cc127b438adea3cf6d42ccb-4255d307"></a>
### [api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md)
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandingproperties-create.md'.`````
 - **Line 32, Column 97**: [...]

2021-09-10 12:25 UTC, FaithOmbongi requested changes
- From yesterday's feedback:
    - Document the relationship in organization + document the organizationalBrandingProperties abstract type.
- Everything with medialLink should go because it's not returned anywhere in the response objects.
- All examples in GET /branding, Both update topics need be counterchecked because of the whole PATCH vs PUT & also where Stream types are involved.

2021-09-10 12:25 UTC, FaithOmbongi commented on api-reference/beta/api/organizationalbrandinglocalization-update.md
> +### Example 4: Replace French localization with PUT
Example isn't correct if your findings are true—that PUT works on images only.

2021-09-10 12:25 UTC, FaithOmbongi commented on api-reference/beta/api/organizationalbrandinglocalization-update.md
> +```
Wrong example. According to the title, we should be updating the bannerLogo here.

2021-09-10 16:29 UTC, opbld32 commented
Docs Build status updates of commit _[9c0f26a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c0f26aaf73555a7d7c2e454c744d4cde259ec3f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-349a3b5c4343e76652123be570b41838-ff204350)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-ff204350)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="349a3b5c4343e76652123be570b41838-ff204350"></a>
### [api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md)
 - **Line 57, Column 68**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandingproperties.md'.`````
 - **Line 56, Column 98**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/active-directory-b2b-what-is-azure-ad-b2b' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 57, Column 145**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/fundamentals/customize-branding' will be broken in isolated environments. Replace with a relative link.`````

<a id="764f51696cc127b438adea3cf6d42ccb-ff204350"></a>
### [api-reference/beta/resources/organization.md] [...]

2021-09-10 19:56 UTC, opbld31 commented
Docs Build status updates of commit _[9ec4b91](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ec4b916c69bd64f478798a917fe5fb2b3e7bb28)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-349a3b5c4343e76652123be570b41838-a121d486)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-a121d486)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="349a3b5c4343e76652123be570b41838-a121d486"></a>
### [api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md)
 - **Line 57, Column 68**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandingproperties.md'.`````
 - **Line 56, Column 98**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/active-directory-b2b-what-is-azure-ad-b2b' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 57, Column 145**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/fundamentals/customize-branding' will be broken in isolated environments. Replace with a relative link.`````

<a id="764f51696cc127b438adea3cf6d42ccb-a121d486"></a>
### [api-reference/beta/resources/organization.md] [...]

2021-09-10 20:24 UTC, opbld30 commented
Docs Build status updates of commit _[3dc4aad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3dc4aadbb223f6464a55e9bded6f74915e5c7711)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-e3d4bb0c)
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-349a3b5c4343e76652123be570b41838-e3d4bb0c)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-e3d4bb0c)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b474f523557c213b527ea0fc6e060a09-e3d4bb0c"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 25, Column 67**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'organizationalbrandingproperties.md'.`````
 - **Line 29, Column 193**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'organizationalbrandingproperties.md'.`````

<a id="349a3b5c4343e76652123be570b41838-e3d4bb0c"></a>
### [api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md)
 - **Line 57, Column [...]

2021-09-10 20:30 UTC, opbld33 commented
Docs Build status updates of commit _[a5bc0f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5bc0f1863a2f07b5c7ab1ad0025cfb31986f335)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-e1219df2)
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-349a3b5c4343e76652123be570b41838-e1219df2)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-e1219df2)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b474f523557c213b527ea0fc6e060a09-e1219df2"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 25, Column 67**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'organizationalbrandingproperties.md'.`````
 - **Line 29, Column 193**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'organizationalbrandingproperties.md'.`````

<a id="349a3b5c4343e76652123be570b41838-e1219df2"></a>
### [api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md)
 - **Line 57, Column [...]

2021-09-10 20:36 UTC, opbld32 commented
Docs Build status updates of commit _[ec846d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec846d52f0e265947d7c308bb849354c6b442703)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-72ed651b)
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-349a3b5c4343e76652123be570b41838-72ed651b)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-72ed651b)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b474f523557c213b527ea0fc6e060a09-72ed651b"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 25, Column 67**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'organizationalbrandingproperties.md'.`````
 - **Line 29, Column 193**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'organizationalbrandingproperties.md'.`````
 - **Line 76, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="349a3b5c4343 [...]

2021-09-10 20:46 UTC, opbld31 commented
Docs Build status updates of commit _[429e1f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/429e1f26fdf87df0bdc49ce2dd7d058136138c9c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-312261a9)
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-349a3b5c4343e76652123be570b41838-312261a9)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-312261a9)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b474f523557c213b527ea0fc6e060a09-312261a9"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 25, Column 67**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'organizationalbrandingproperties.md'.`````
 - **Line 29, Column 193**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'organizationalbrandingproperties.md'.`````
 - **Line 47, Column 292**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationalbrandingproperties.md'.`````
 - **Line 48, Column 283**: **[Warning [...]

2021-09-10 21:01 UTC, AlexanderMars commented on api-reference/beta/resources/organizationalbranding.md
>  ## Properties
done

2021-09-10 21:02 UTC, opbld33 commented
Docs Build status updates of commit _[79815b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/79815b76e617b14d53caa5da909a1e17c5bd3277)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-35b39a48)
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-90592e6421307e4e6ae931d0003205f5-35b39a48)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-35b39a48)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b474f523557c213b527ea0fc6e060a09-35b39a48"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 74, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="90592e6421307e4e6ae931d0003205f5-35b39a48"></a>
### [api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md)
 - **Line 22, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandingproperties-list.md'.`````
 - **Line 23, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Inv [...]

2021-09-10 21:04 UTC, opbld34 commented
Docs Build status updates of commit _[f824274](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8242746c79cd5f49e374f80e1486eff19ca515a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-431e3ef3)
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-90592e6421307e4e6ae931d0003205f5-431e3ef3)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-431e3ef3)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b474f523557c213b527ea0fc6e060a09-431e3ef3"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 74, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="90592e6421307e4e6ae931d0003205f5-431e3ef3"></a>
### [api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md)
 - **Line 22, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandingproperties-list.md'.`````
 - **Line 23, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Inv [...]

2021-09-10 21:06 UTC, AlexanderMars commented on api-reference/beta/resources/organizationalbranding.md
> +  "baseType": "Microsoft.DirectoryServices.organizationalBrandingProperties",
done

2021-09-10 21:08 UTC, opbld32 commented
Docs Build status updates of commit _[a3b6166](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a3b6166326f94fa1ef7528a35a1b245036918f5a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-36f5dc23)
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-90592e6421307e4e6ae931d0003205f5-36f5dc23)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-36f5dc23)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b474f523557c213b527ea0fc6e060a09-36f5dc23"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 74, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="90592e6421307e4e6ae931d0003205f5-36f5dc23"></a>
### [api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md)
 - **Line 22, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandingproperties-list.md'.`````
 - **Line 23, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Inv [...]

2021-09-10 21:11 UTC, AlexanderMars commented on api-reference/beta/resources/organizationalbranding.md
>  {
done

2021-09-10 21:15 UTC, opbld31 commented
Docs Build status updates of commit _[1844044](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1844044bb70a8d515972bf44672602bf6ac919b1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-e050c0ca)
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-90592e6421307e4e6ae931d0003205f5-e050c0ca)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-e050c0ca)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b474f523557c213b527ea0fc6e060a09-e050c0ca"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 74, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="90592e6421307e4e6ae931d0003205f5-e050c0ca"></a>
### [api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md)
 - **Line 22, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandingproperties-list.md'.`````
 - **Line 23, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Inv [...]

2021-09-10 21:17 UTC, opbld34 commented
Docs Build status updates of commit _[68a5795](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68a5795d137ddc5ffaeede7666b245d429984143)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-a6ac2d80)
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-90592e6421307e4e6ae931d0003205f5-a6ac2d80)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-a6ac2d80)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b474f523557c213b527ea0fc6e060a09-a6ac2d80"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 74, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="90592e6421307e4e6ae931d0003205f5-a6ac2d80"></a>
### [api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md)
 - **Line 22, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandingproperties-list.md'.`````
 - **Line 23, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Inv [...]

2021-09-10 21:17 UTC, AlexanderMars commented on api-reference/beta/resources/organizationalbrandinglocalization.md
> +|usernameHintText|String| String that shows as the hint in the username textbox on the sign in screen. This text must be Unicode, without links or code, and can't exceed 64 characters.|
done

2021-09-10 21:37 UTC, AlexanderMars commented on api-reference/beta/toc.yml
> +            href: api/organizationalbranding-list-localizations.md
it looks good on my end

2021-09-10 21:40 UTC, opbld33 commented
Docs Build status updates of commit _[61d8fef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61d8fefbe330c7549b4e19a45efa783c225538df)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-05b5774e)
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-90592e6421307e4e6ae931d0003205f5-05b5774e)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-05b5774e)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b474f523557c213b527ea0fc6e060a09-05b5774e"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 74, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="90592e6421307e4e6ae931d0003205f5-05b5774e"></a>
### [api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md)
 - **Line 22, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandingproperties-list.md'.`````
 - **Line 23, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Inv [...]

2021-09-10 21:43 UTC, opbld34 commented
Docs Build status updates of commit _[ac58fe0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ac58fe0b59914203a2239e76b9421bb461b67179)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-c6977ec0)
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-90592e6421307e4e6ae931d0003205f5-c6977ec0)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-c6977ec0)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b474f523557c213b527ea0fc6e060a09-c6977ec0"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 74, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="90592e6421307e4e6ae931d0003205f5-c6977ec0"></a>
### [api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md)
 - **Line 22, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationalbrandingproperties-list.md'.`````
 - **Line 23, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Inv [...]

2021-09-10 22:10 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbranding-post-localizations.md
> +|usernameHintText|String| String that shows as the hint in the username textbox on the sign in screen. This text must be Unicode, without links or code, and can't exceed 64 characters.|
done

2021-09-10 22:11 UTC, opbld31 commented
Docs Build status updates of commit _[9fe2da4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9fe2da4c98846241a290969987e3901313270e47)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-c2d05cfa)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-c2d05cfa)
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-90592e6421307e4e6ae931d0003205f5-c2d05cfa)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-c2d05cfa)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-c2d05cfa"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````

<a id="b474f523557c213b527ea0fc6e060a09-c2d05cfa"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 74, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="90592e6421307e4e6ae931d0003205f5-c2d05cfa"></a>
### [api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md)
 - **Line 22, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/c [...]

2021-09-10 22:13 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbranding-post-localizations.md
> +
done

2021-09-10 22:16 UTC, opbld31 commented
Docs Build status updates of commit _[6399625](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63996258161b9e97f1099251f5b2faed938aa970)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-53fe0643)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-53fe0643)
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-90592e6421307e4e6ae931d0003205f5-53fe0643)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-53fe0643)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-53fe0643"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````

<a id="b474f523557c213b527ea0fc6e060a09-53fe0643"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 74, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="90592e6421307e4e6ae931d0003205f5-53fe0643"></a>
### [api-reference/beta/resources/orga [...]

2021-09-10 22:17 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbranding-post-localizations.md
> +The **mediaEditLink** specifies where the localized media is written. The mediaReadLink is null because no media has been set for the localization.
done

2021-09-10 22:22 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbranding-post-localizations.md
> +POST to branding/localizations to create both, a new localization and a default branding, if one does not already exist. The id specified in the body is the locale for the localization. If no id is s
done

2021-09-10 22:22 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbranding-list-localizations.md
> +Get the organizationalBrandingLocalization resources from the localizations navigation property.
Thanks a lot!

2021-09-10 22:24 UTC, opbld34 commented
Docs Build status updates of commit _[9046670](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9046670bcc5a42d5712a0d1f6268728b3a553aa3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-d31f3c7e)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-d31f3c7e)
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-90592e6421307e4e6ae931d0003205f5-d31f3c7e)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-d31f3c7e)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-d31f3c7e"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````

<a id="b474f523557c213b527ea0fc6e060a09-d31f3c7e"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 74, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="90592e6421307e4e6ae931d0003205f5-d31f3c7e"></a>
### [api-reference/beta/resources/orga [...]

2021-09-10 22:49 UTC, AlexanderMars commented on api-reference/beta/resources/organizationalbranding.md
>  >**Note:** Branding is exposed as a property under organization with a collection of locale-specific localizations. **organizationalBrandingProperties** is an abstract class which defines properties
done

2021-09-10 22:51 UTC, opbld32 commented
Docs Build status updates of commit _[00044a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/00044a1b949a50e421206d8e5033dfdf94f3a139)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-617b70bb)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-617b70bb)
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-90592e6421307e4e6ae931d0003205f5-617b70bb)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-617b70bb)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-617b70bb"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````

<a id="b474f523557c213b527ea0fc6e060a09-617b70bb"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 74, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="90592e6421307e4e6ae931d0003205f5-617b70bb"></a>
### [api-reference/beta/resources/orga [...]

2021-09-10 22:53 UTC, opbld33 commented
Docs Build status updates of commit _[9182cd8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9182cd8fd5514cc34036f68443d937f2aa70630e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-8e466e49)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-8e466e49)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-8e466e49)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-8e466e49"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="b474f523557c213b527ea0fc6e060a09-8e466e49"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 65, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch [...]

2021-09-10 22:56 UTC, opbld30 commented
Docs Build status updates of commit _[bfd4ec4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bfd4ec42828d72ce2caa54076b38dcd0163cb83e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-0d1549fb)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-0d1549fb)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-0d1549fb)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-0d1549fb"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="b474f523557c213b527ea0fc6e060a09-0d1549fb"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 65, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch [...]

2021-09-10 22:57 UTC, opbld34 commented
Docs Build status updates of commit _[61dd6ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61dd6eed731b393041e478976fd47b60e9af13cc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-93327df4)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-93327df4)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-93327df4)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-93327df4"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="b474f523557c213b527ea0fc6e060a09-93327df4"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md)
 - **Line 65, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch [...]

2021-09-10 22:59 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbrandinglocalization-delete.md
> +Delete a localization [organizationalBrandingLocalization](../resources/organizationalbrandinglocalization.md) object. This deletes a localized branding only. The default branding can not be deleted
done

2021-09-10 22:59 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbrandinglocalization-delete.md
>  # [HTTP](#tab/http)
done

2021-09-10 23:07 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbrandinglocalization-delete.md
>  ```http
done

2021-09-10 23:13 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbrandinglocalization-update.md
> +PATCH /organization/{organizationId}/branding/localizations/{organizationalBrandingLocalizationId}
done

2021-09-10 23:20 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbrandinglocalization-update.md
> +If successful, this method returns a `200 OK` response code and an updated [organizationalBrandingLocalization](../resources/organizationalbrandinglocalization.md) object in the response body.
done

2021-09-10 23:22 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbrandinglocalization-update.md
> +The following request updates the banner logo for the fr localization.  Using PATCH, if the specified localization does not already exist, it is created and the property is written to it.
done

2021-09-10 23:22 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbrandinglocalization-update.md
> +### Example 2: Update **bannerLogo** for the fr localization using PATCH
done

2021-09-10 23:28 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbrandinglocalization-update.md
> +### Example 1: Setting **bannerLogo** for the fr localization using PUT
It works as intended. However, API client Must support a binary data.

2021-09-10 23:30 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbranding-update.md
> +Update the properties of an [organizationalBranding](../resources/organizationalbranding.md) object.
done

2021-09-10 23:36 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbrandinglocalization-update.md
> +```
not seeing the issue

2021-09-11 00:00 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbrandinglocalization-update.md
> +### Example 4: Replace French localization with PUT
Agree. We can replace it with PATCH and update description which is an inaccurate

2021-09-11 00:04 UTC, AlexanderMars commented on api-reference/beta/api/organizationalbranding-update.md
> +|usernameHintText|String| String that shows as the hint in the username textbox on the sign in screen. This text must be Unicode, without links or code, and can't exceed 64 characters.|
done

2021-09-11 00:39 UTC, opbld31 commented
Docs Build status updates of commit _[a027d00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a027d0019544eeb90e8964236f169ca07a090d6e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-3365a08f)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-764f51696cc127b438adea3cf6d42ccb-3365a08f)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-3365a08f)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-3365a08f"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="764f51696cc127b438adea3cf6d42ccb-3365a08f"></a>
### [api-reference/beta/resources/organization.md](https://github.com/micr [...]

2021-09-11 02:57 UTC, opbld30 commented
Docs Build status updates of commit _[39c706c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39c706c61f25db206f714ea78926e0066b018d40)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-df20e63e)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-df20e63e)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-df20e63e"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="b474f523557c213b527ea0fc6e060a09-df20e63e"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/or [...]

2021-09-11 03:01 UTC, opbld31 commented
Docs Build status updates of commit _[7393bb4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7393bb4e60600671fb4ab285399fc3b6b84e25a5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-eb25013b)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-eb25013b)
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/azure-ad-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-349a3b5c4343e76652123be570b41838-eb25013b)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-eb25013b"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line [...]

2021-09-16 07:16 UTC, opbld32 commented
Docs Build status updates of commit _[6d3bbf9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d3bbf9d7eb585e818e45de0fb2f6975d7bfce68)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-e9650842)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-e9650842)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-e9650842"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="b474f523557c213b527ea0fc6e060a09-e9650842"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/or [...]

2021-09-16 10:20 UTC, opbld34 commented
Docs Build status updates of commit _[062a26b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/062a26bd257bb17d11593ba12d2446bea5e9647f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-ed693dd5)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-ed693dd5)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-ed693dd5"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="b474f523557c213b527ea0fc6e060a09-ed693dd5"></a>
### [api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/or [...]

2021-09-16 10:52 UTC, opbld32 commented
Docs Build status updates of commit _[a2cde22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2cde22a07e0b2c4d50bc8d58f1a9eed26bc927f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-5c6013dc)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-5c6013dc)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-5c6013dc"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 10:53 UTC, opbld34 commented
Docs Build status updates of commit _[acfe8d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/acfe8d8eecad13b900df6e4d4e92e8a72bc1b642)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-91b6c1cd)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-91b6c1cd)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-91b6c1cd"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 11:24 UTC, opbld33 commented
Docs Build status updates of commit _[4ffa903](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ffa9033c798db3ee2253f900a44e9a91ac5e6cd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-a53310dd)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-a53310dd)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-a53310dd"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 11:44 UTC, opbld32 commented
Docs Build status updates of commit _[8d57e02](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d57e027dc498ecca182ad1c5701379b8256b192)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-29fd7fc2)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-29fd7fc2)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-29fd7fc2"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 11:47 UTC, opbld31 commented
Docs Build status updates of commit _[56d88ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56d88ce2a8f9164142e274485ddf5a71e8d90da6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-3d4bb445)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-3d4bb445)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-3d4bb445"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 11:49 UTC, opbld33 commented
Docs Build status updates of commit _[798a143](https://github.com/microsoftgraph/microsoft-graph-docs/commits/798a143dfc3d9f23cdc43c5bd82266578300f736)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-a095fde5)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-a095fde5)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-a095fde5"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 11:59 UTC, opbld34 commented
Docs Build status updates of commit _[f774f21](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f774f218a67e482db1ff90c31a7bdce0aa3632b5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-a4d887b0)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-a4d887b0)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-a4d887b0"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 12:01 UTC, opbld33 commented
Docs Build status updates of commit _[fcfd7ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fcfd7ae42e84adb8baf2fe76e7d2b873af893bde)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-11e1518c)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-11e1518c)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-11e1518c"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 12:03 UTC, opbld32 commented
Docs Build status updates of commit _[0ce454e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ce454e19d28615682e5da7caeecb9a9ecce7f33)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-77be4221)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-77be4221)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-77be4221"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 12:12 UTC, opbld30 commented
Docs Build status updates of commit _[5aa95a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5aa95a2af8567becd0ef85c6aa291dde65fe2659)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-c5aab4cb)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-c5aab4cb)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-c5aab4cb"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 12:23 UTC, opbld31 commented
Docs Build status updates of commit _[bb10d4c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb10d4cc633c0f5aa732688a5fffaaa471bdb4f5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-ab7c8a2e)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-ab7c8a2e)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-ab7c8a2e"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 12:25 UTC, opbld34 commented
Docs Build status updates of commit _[d2ba8e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2ba8e9b189843ea8bcc9b3eadd6f7014507f30f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-4882b099)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-4882b099)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-4882b099"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 12:28 UTC, opbld33 commented
Docs Build status updates of commit _[63dca0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63dca0d33dcfaa77b4450f1ed2e35512d79b0df0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-5ff6b443)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-5ff6b443)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-5ff6b443"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 47, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 71, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 12:41 UTC, opbld30 commented
Docs Build status updates of commit _[e5cc4de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e5cc4de0eb200f2a2888b5c2e695da4b8e63ef7d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-58ca0af1)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-58ca0af1)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-58ca0af1"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 46, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 68, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 12:48 UTC, opbld32 commented
Docs Build status updates of commit _[eede13a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eede13a6be505f508bdc62b781b64ce3c3873212)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-edf6e0dd)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-edf6e0dd)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-edf6e0dd"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 46, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 68, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 12:50 UTC, opbld34 commented
Docs Build status updates of commit _[8d62982](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d629828a98a63e0a777576dd01309d6db00db45)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-a227a3e0)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-a227a3e0)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-a227a3e0"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 46, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 68, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code b [...]

2021-09-16 12:52 UTC, opbld31 commented
Docs Build status updates of commit _[a8f6356](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8f63566d08bd09d7da54caad7ef0cf9693017bf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-f62b861a)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-f62b861a)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f62b861a)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-f62b861a"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 46, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/organizationbrandinglocalization.md'.`````
 - **Line 68, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/ [...]

2021-09-16 12:54 UTC, opbld33 commented
Docs Build status updates of commit _[c13f5b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c13f5b441cb15a160ad32163edccae658ab5096e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-2e54a63a)
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b474f523557c213b527ea0fc6e060a09-2e54a63a)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-2e54a63a)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-2e54a63a"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 46, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'organizationbrandinglocalization.md'.`````
 - **Line 89, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-un [...]

2021-09-16 13:16 UTC, opbld32 commented
Docs Build status updates of commit _[8754c9e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8754c9e2f02b45976a188f1d1b01ea282c3b8ee3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) | [Details](#user-content-b297769dd29b09fdec28528aefc029f0-aab415fa)
[api-reference/beta/api/organizationalbranding-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

<a id="b297769dd29b09fdec28528aefc029f0-aab415fa"></a>
### [api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md)
 - **Line 46, Column 80**: **[Warning-[file-not-found](https://review.docs.micr [...]

2021-09-16 13:19 UTC, opbld32 commented
Docs Build status updates of commit _[96e5d42](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96e5d429c94bff9ea5e0b6912251ea0c38ae085e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109161317381070-14107%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T13%3A19%3A45Z&sr=b&sp=r&sig=3i8G6MO9p3vPFyFIKN0nRiIUEpPucXW6bLwZ%2FcW%2FQ2c%3D).

**Note:** Broken links written as relative paths are included in the abo [...]

2021-09-16 13:31 UTC, opbld30 commented
Docs Build status updates of commit _[e8a4776](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8a477608e4a7ced2b0afed0b5ee815644206df2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109161329232333-14107%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T13%3A31%3A00Z&sr=b&sp=r&sig=BjfBw9I35pbWWXZwKw6XqlZ7J9OyEdcreyJ04wXGrwQ%3D).

**Note:** Broken links written as relative paths are included in the above b [...]

2021-09-16 13:58 UTC, FaithOmbongi approved these changes

2021-09-16 14:02 UTC, opbld33 commented
Docs Build status updates of commit _[9844d0f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9844d0f2b47b50efc1db4044adbea917bc112eea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109161400332406-14107%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T14%3A02%3A10Z&sr=b&sp=r&sig=9sBb14nVy%2BSOFYcu1tnx79LY0SFF3EBzYgTpJYDbKeo%3D).

**Note:** Broken links written as relative paths are included in the above [...]

2021-09-16 14:04 UTC, opbld34 commented
Docs Build status updates of commit _[e643fcb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e643fcba069b8cf1d682ac283d63676fbd9cd3e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109161402554020-14107%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T14%3A04%3A35Z&sr=b&sp=r&sig=ceBmaWjjG6%2FJvL%2Fb6Mn3rxHTrjVqExSkjgmNocqFsyk%3D).

**Note:** Broken links written as relative paths are included in the abo [...]

2021-09-17 16:36 UTC, opbld31 commented
Docs Build status updates of commit _[139afe6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/139afe6786d4065c298caa737e22038a00efa91c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109171634122567-14107%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-18T16%3A36%3A01Z&sr=b&sp=r&sig=8lkaeEXt3ax32rPYQ%2Br2MkXRqRB5XLTAUSODW5Mp9Dw%3D).

**Note:** Broken links written as relative paths are included in the above [...]

2021-09-23 09:03 UTC, opbld31 commented
Docs Build status updates of commit _[2c2f019](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c2f01976495655c38b90029f6c28062ab07be05)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbranding-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-list-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-list-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-list-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-post-localizations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-post-localizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-post-localizations?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbranding-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-get?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandinglocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbranding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbranding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbranding?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandinglocalization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandinglocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandinglocalization?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-delete?view=graph-rest-beta&branch=pr-en-us-14107) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109230902090116-14107%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-24T09%3A03%3A58Z&sr=b&sp=r&sig=8jGrIYgpXtyVdYWpTQKh7HHt08lZGY3gzXLrIFAgm8o%3D).

**Note:** Broken links written as relative paths are included in the above b [...]

2021-09-23 18:53 UTC, FaithOmbongi commented
Hi @Lauragra , this PR is for a docs cleanup effort. I've prepared another [PR to add redirects ](https://github.com/microsoftgraph/microsoft-graph-docs/pull/14225) so that customers don't encounter broken links because of the file name changes.

2021-09-24 01:50 UTC, merged