Add cloudPcSupportedRegion resource topic
microsoftgraph/microsoft-graph-docs pull request #14111
Opened 2021-09-02 07:27 UTC by RuiHou105

2021-09-02 07:29 UTC, jasonjoh commented
Docs Build status updates of commit _[af168d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af168d6ac46cd18baf82a7466384beea0bc3f82c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109020727083936-14111%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=e8sx%2BANzrDLfqJrEi6JiGf3xriWZ6dfxzSzibox0mWM%3D&st=2021-09-02T07%3A24%3A31Z&se=2021-10-03T07%3A29%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 07:34 UTC, RuiHou105 commented
Roadmap workitem:
Feature 11024: [Devices and apps][Cloud PC] Add cloudPcSupportedRegion entity

2021-09-09 18:25 UTC, opbld33 commented
Docs Build status updates of commit _[67409eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67409eb7186c16bfc4339bca6cc0a4d601362051)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109091822508876-14111%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=WdkaIMOkrGoMNjL6Cx8YlSJyHTaUSyxYufHVEJym7UQ%3D&st=2021-09-09T18%3A20%3A31Z&se=2021-10-10T18%3A25%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 14:29 UTC, opbld30 commented
Docs Build status updates of commit _[fff239d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fff239d422999e42b23f83a228194748afea20e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109151424447769-14111%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T14%3A29%3A01Z&sr=b&sp=r&sig=FMvYlGEkg%2BEZrodgzbhYZ%2BI%2BskPhHGg5b%2FZWKdp2zqI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 17:29 UTC, isvargasmsft commented on api-reference/beta/api/virtualendpoint-list-supportedregions.md
> +List properties and relationships of the [cloudPcSupportedRegion](../resources/cloudpcsupportedregion.md) objects.
Lines 3 and 16: This line is used by search engines to display results. It is a good practice to write these descriptions in the way we would search for this topic in Bing. 
For **example**:
- List the regions available to create cloud PC connections to the specified virtualEndPoint.

2021-09-15 17:50 UTC, isvargasmsft commented on api-reference/beta/api/virtualendpoint-list-supportedregions.md
> +GET /deviceManagement/virtualEndpoint/supportedRegions
Line 38: Shouldn't we specify a particular virtualEndpoint-ID?
/deviceManagement/virtualEndpoint/ID/supportedRegions ?

2021-09-15 18:10 UTC, isvargasmsft commented on api-reference/beta/api/virtualendpoint-list-supportedregions.md
> +## Examples
Please change to singular "Example".

2021-09-15 19:21 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +Represent a supported region in which on-premises network connection can be established for Cloud PCs.
Lines 3 and 16: let's rephrase for simplicity and to active voice. For example:
Represents a region where Cloud PCs can connect to an on-premises network.
or
Represents a region where Cloud PCs can establish an on-premises network connection. 
or
Represents a region supported to establish on premises network connections for Cloud PCs.

2021-09-15 19:22 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +|[List cloudPcSupportedRegions](../api/virtualendpoint-list-cloudpcs.md)|[cloudPcSupportedRegion](../resources/cloudpcsupportedregion.md) collection|List [cloudPcSupportedRegion](../resources/cloudpc
Please make the description in this line match the description in the List topic after the comments are implemented.

2021-09-15 19:25 UTC, isvargasmsft requested changes
Excellent work in this PR @RuiHou105. Thank you very much!

Just a few suggestions for phrasing and I'd like to clarify the request syntax. 

Please feel free to ping me on the side if you have any questions. Here to help!

Isaac Vargas

2021-09-16 08:30 UTC, RuiHou105 commented on api-reference/beta/api/virtualendpoint-list-supportedregions.md
> +GET /deviceManagement/virtualEndpoint/supportedRegions
The supportedRegions is one of virtualEndpoint's navigation properties, so virtualEndpoint is used to route to supportedRegions which is a collection of entity cloudPcSupportedRegion. Thus, we don't need ID here.

2021-09-16 09:39 UTC, RuiHou105 commented on api-reference/beta/api/virtualendpoint-list-supportedregions.md
> +List properties and relationships of the [cloudPcSupportedRegion](../resources/cloudpcsupportedregion.md) objects.
Thanks for your suggestion. But one thing I want to clarify is that there is no "specified" virtualEndpoint ( you can see my another reply in your comment below). So, no need to add ID in the URL and no need to add "specified". Are you good with this one - List the supported regions available to create Cloud PC connections?

2021-09-16 09:40 UTC, RuiHou105 commented on api-reference/beta/api/virtualendpoint-list-supportedregions.md
> +## Examples
Updated. Thank you.

2021-09-16 09:44 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +Represent a supported region in which on-premises network connection can be established for Cloud PCs.
Updated to version3.

2021-09-16 09:50 UTC, opbld30 commented
Docs Build status updates of commit _[e71481d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e71481d881bf2c612c347ff21b27c74a9b14294d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109160947155827-14111%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T09%3A50%3A10Z&sr=b&sp=r&sig=Bd6FaqYjoZhEcVWl7gi4gBP4zAaYiIMTQ63SE4i6ib0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 12:21 UTC, isvargasmsft commented on api-reference/beta/api/virtualendpoint-list-supportedregions.md
> +List properties and relationships of the [cloudPcSupportedRegion](../resources/cloudpcsupportedregion.md) objects.
Thank you for the clarification. And yes: List the supported regions available to create Cloud PC connections
Thank you very much!

2021-09-16 12:23 UTC, opbld32 commented
Docs Build status updates of commit _[83eb9ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83eb9cee5559b73d1bb458e484c76c0caa1252fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109161221415016-14111%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T12%3A23%3A51Z&sr=b&sp=r&sig=mBd0oO5PXy5K3BACC%2FfwD5NZmaWbCQTFeiFzHuqbkYc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 12:42 UTC, AshleyYangSZ approved these changes

2021-09-18 03:37 UTC, RuiHou105 commented on api-reference/beta/api/virtualendpoint-list-supportedregions.md
> +List properties and relationships of the [cloudPcSupportedRegion](../resources/cloudpcsupportedregion.md) objects.
Updated. Please check.

2021-09-18 03:42 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +|[List cloudPcSupportedRegions](../api/virtualendpoint-list-cloudpcs.md)|[cloudPcSupportedRegion](../resources/cloudpcsupportedregion.md) collection|List [cloudPcSupportedRegion](../resources/cloudpc
Updated description. Please check.

2021-09-18 03:46 UTC, opbld34 commented
Docs Build status updates of commit _[7156824](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7156824db04112c86525c18bdca3bba89a215d0d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :x:Error | | [Details](#user-content-8fe9c434854094c2c94a4f035c10f3e9-d4ae557a)
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/cloudpcsupportedregion.md) | :x:Error | | [Details](#user-content-374ec5137a77d8312f16138d57ff780b-d4ae557a)

<a id="8fe9c434854094c2c94a4f035c10f3e9-d4ae557a"></a>
### [api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/api/virtualendpoint-list-supportedregions.md)
 - **Line 18, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../../includes/cloudpc-api-preview.md'.`````

<a id="374ec5137a77d8312f16138d57ff780b-d4ae557a"></a>
### [api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/cloudpcsupportedregion.md)
 - **Line 18, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../../includes/cloudpc-api-preview.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109180344217689-14111%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-19T03%3A46%3A07Z&sr=b&sp=r&sig=o0Ukv497MGpakr9%2Bq6T5kdQGQuUqVzlE5xno9UVd15o%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-18 03:50 UTC, opbld33 commented
Docs Build status updates of commit _[20d88e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20d88e8c90ec69500fca435df6550a47452d0cf7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :x:Error | | [Details](#user-content-8fe9c434854094c2c94a4f035c10f3e9-a6f3b7f7)
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/cloudpcsupportedregion.md) | :x:Error | | [Details](#user-content-374ec5137a77d8312f16138d57ff780b-a6f3b7f7)

<a id="8fe9c434854094c2c94a4f035c10f3e9-a6f3b7f7"></a>
### [api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/api/virtualendpoint-list-supportedregions.md)
 - **Line 18, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../../includes/cloudpc-api-preview.md'.`````

<a id="374ec5137a77d8312f16138d57ff780b-a6f3b7f7"></a>
### [api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/cloudpcsupportedregion.md)
 - **Line 18, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../../includes/cloudpc-api-preview.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109180349028776-14111%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-19T03%3A50%3A42Z&sr=b&sp=r&sig=IYjnJGjvs%2F%2F2TZXhpnq%2BI7BuFSe8IfBXCCyXsg8MOW0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-18 03:56 UTC, opbld30 commented
Docs Build status updates of commit _[ce27c04](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ce27c04ca0732f94b18d9a6d9f5bd1253829df49)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109180354361932-14111%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-19T03%3A56%3A13Z&sr=b&sp=r&sig=1MEVra30vP1MP8NbmIvNAHrcR2RWO9u4nyms4sxSGt4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 06:29 UTC, RuiHou105 commented
@isvargasmsft All comments resolved. Could you please take a second look at this PR? Thanks!

2021-09-27 14:47 UTC, opbld33 commented
Docs Build status updates of commit _[7e7839c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e7839c1c665cd2d48fc1e80b6c6c5d03898dc34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109271445131279-14111%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-28T14%3A47%3A04Z&sr=b&sp=r&sig=1gnx8JkSBDjzXwz9LaVL2F6aWZQdGOw9tVrMKGcL95Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-27 15:21 UTC, isvargasmsft approved these changes
Thank you very much for your work in this PR!

2021-09-29 03:28 UTC, opbld34 commented
Docs Build status updates of commit _[fe6401b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe6401be08d713808796c02edf9de7c3236c889f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109290326306151-14111%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-30T03%3A28%3A41Z&sr=b&sp=r&sig=60agyTYG0SmXSVGLGJjFRl0Chw0gpAA3hJ3%2BEzC8f9U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-29 03:30 UTC, opbld34 commented
Docs Build status updates of commit _[404b560](https://github.com/microsoftgraph/microsoft-graph-docs/commits/404b5602412de22975951ab4d6201362a34cc29f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-14111) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddSupportedRegions/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109290328475944-14111%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-30T03%3A30%3A30Z&sr=b&sp=r&sig=7Q6BHdTNUMclzCtstA1ZvVp0rzSeasvi41ZnAwyDmII%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-29 03:41 UTC, Lauragra approved these changes

2021-09-29 03:41 UTC, merged