update documents
microsoftgraph/microsoft-graph-docs pull request #14138
Opened 2021-09-03 05:19 UTC by haizeie

2021-09-03 05:21 UTC, jasonjoh commented
Docs Build status updates of commit _[c0031ac](https://github.com/haizeie/microsoft-graph-docs/commits/c0031ac07f0f4035a6cfd9d39ac4240175e2653b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog/Microsoft.O365Reporting.json](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/changelog/Microsoft.O365Reporting.json) | :white_check_mark:Succeeded | |
[concepts/reportroot-authorization.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/concepts/reportroot-authorization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/reportroot-authorization?branch=pr-en-us-14138) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109030519504936-14138%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=1Ccyr5sTCv2xLjpiZzP%2FUIpnQdkPSNcR1vmro%2FXj9as%3D&st=2021-09-03T05%3A16%3A27Z&se=2021-10-04T05%3A21%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 09:14 UTC, jasonjoh commented
Docs Build status updates of commit _[73a6f53](https://github.com/haizeie/microsoft-graph-docs/commits/73a6f538290fc73e0ad23c58012b9cc1a0825c0b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/beta/resources/report.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-14138) (graph-rest-beta) | [Details](#user-content-1bd731c67eabc000ece21b8c99dc7eba-3baaea44)
[api-reference/v1.0/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/v1.0/resources/report.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-1.0&branch=pr-en-us-14138) (>= graph-rest-1.0) | [Details](#user-content-3bc2ae538a81c4188d2060fe3264cb5f-3baaea44)
[changelog/Microsoft.O365Reporting.json](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/changelog/Microsoft.O365Reporting.json) | :white_check_mark:Succeeded | |
[concepts/reportroot-authorization.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/concepts/reportroot-authorization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/reportroot-authorization?branch=pr-en-us-14138) |

<a id="1bd731c67eabc000ece21b8c99dc7eba-3baaea44"></a>
### [api-reference/beta/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/beta/resources/report.md)
 - **Line 14, Column 299**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/activity-reports' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 299**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/activity-reports' will be broken in isolated environments. Replace with a relative link.`````

<a id="3bc2ae538a81c4188d2060fe3264cb5f-3baaea44"></a>
### [api-reference/v1.0/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/v1.0/resources/report.md)
 - **Line 12, Column 299**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/activity-reports' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 12, Column 299**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/activity-reports' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109030913040951-14138%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Ln1D%2B6KOHrpwosigZD%2FpT1Shf%2F5UrvFD%2FQgtviEG2yY%3D&st=2021-09-03T09%3A09%3A53Z&se=2021-10-04T09%3A14%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 09:40 UTC, jasonjoh commented
Docs Build status updates of commit _[c43259a](https://github.com/haizeie/microsoft-graph-docs/commits/c43259a873ab177629a03755f648f2a7d5fb49d7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/beta/resources/report.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-14138) (graph-rest-beta) | [Details](#user-content-1bd731c67eabc000ece21b8c99dc7eba-cceb069b)
[api-reference/v1.0/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/v1.0/resources/report.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-1.0&branch=pr-en-us-14138) (>= graph-rest-1.0) | [Details](#user-content-3bc2ae538a81c4188d2060fe3264cb5f-cceb069b)
[changelog/Microsoft.O365Reporting.json](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/changelog/Microsoft.O365Reporting.json) | :white_check_mark:Succeeded | |
[concepts/reportroot-authorization.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/concepts/reportroot-authorization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/reportroot-authorization?branch=pr-en-us-14138) |

<a id="1bd731c67eabc000ece21b8c99dc7eba-cceb069b"></a>
### [api-reference/beta/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/beta/resources/report.md)
 - **Line 14, Column 299**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/activity-reports' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 299**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/activity-reports' will be broken in isolated environments. Replace with a relative link.`````

<a id="3bc2ae538a81c4188d2060fe3264cb5f-cceb069b"></a>
### [api-reference/v1.0/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/v1.0/resources/report.md)
 - **Line 12, Column 299**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/activity-reports' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 12, Column 299**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/activity-reports' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109030939078000-14138%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=GH4RmUXM%2FT4dnFWz4ZLg2ZL0UGIVpYdBaPYbmFpi92w%3D&st=2021-09-03T09%3A35%3A37Z&se=2021-10-04T09%3A40%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 14:39 UTC, jasonjoh commented
Docs Build status updates of commit _[66a2d60](https://github.com/haizeie/microsoft-graph-docs/commits/66a2d608866ec4f46af97ef3be3d94b7eb03fdf6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/beta/resources/report.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-14138) (graph-rest-beta) | [Details](#user-content-1bd731c67eabc000ece21b8c99dc7eba-1f8a4166)
[api-reference/v1.0/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/v1.0/resources/report.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-1.0&branch=pr-en-us-14138) (>= graph-rest-1.0) | [Details](#user-content-3bc2ae538a81c4188d2060fe3264cb5f-1f8a4166)
[changelog/Microsoft.O365Reporting.json](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/changelog/Microsoft.O365Reporting.json) | :white_check_mark:Succeeded | |
[concepts/reportroot-authorization.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/concepts/reportroot-authorization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/reportroot-authorization?branch=pr-en-us-14138) |

<a id="1bd731c67eabc000ece21b8c99dc7eba-1f8a4166"></a>
### [api-reference/beta/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/beta/resources/report.md)
 - **Line 14, Column 299**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/admin/activity-reports/activity-reports' will be broken in isolated environments. Replace with a relative link.`````

<a id="3bc2ae538a81c4188d2060fe3264cb5f-1f8a4166"></a>
### [api-reference/v1.0/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/v1.0/resources/report.md)
 - **Line 12, Column 299**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/admin/activity-reports/activity-reports' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031438053296-14138%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=5ETS77pjtK2L5RW9a%2BVzZ9qNFd%2F3G976hoUi77a8Bs4%3D&st=2021-09-03T14%3A34%3A40Z&se=2021-10-04T14%3A39%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 19:08 UTC, jasonjoh commented
Docs Build status updates of commit _[a6bb7ae](https://github.com/haizeie/microsoft-graph-docs/commits/a6bb7ae48f238153017e804bbb8ce8005923f371)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/v1.0/resources/report.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-1.0&branch=pr-en-us-14138) (>= graph-rest-1.0) | [Details](#user-content-3bc2ae538a81c4188d2060fe3264cb5f-cc813112)
[api-reference/beta/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-14138) (graph-rest-beta) |
[changelog/Microsoft.O365Reporting.json](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/changelog/Microsoft.O365Reporting.json) | :white_check_mark:Succeeded | |
[concepts/reportroot-authorization.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/concepts/reportroot-authorization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/reportroot-authorization?branch=pr-en-us-14138) |

<a id="3bc2ae538a81c4188d2060fe3264cb5f-cc813112"></a>
### [api-reference/v1.0/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/v1.0/resources/report.md)
 - **Line 12, Column 299**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/admin/activity-reports/activity-reports' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031906502809-14138%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=3yLAnLD742T6%2FqlFWBUtDU8E%2F5IkLaiJcmYYQ3x8Wlg%3D&st=2021-09-03T19%3A03%3A26Z&se=2021-10-04T19%3A08%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 19:10 UTC, jasonjoh commented
Docs Build status updates of commit _[640fb59](https://github.com/haizeie/microsoft-graph-docs/commits/640fb596896d5cae8270f3fd03c5185c0514c5f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-14138) (graph-rest-beta) |
[api-reference/v1.0/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/v1.0/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-1.0&branch=pr-en-us-14138) (>= graph-rest-1.0) |
[changelog/Microsoft.O365Reporting.json](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/changelog/Microsoft.O365Reporting.json) | :white_check_mark:Succeeded | |
[concepts/reportroot-authorization.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/concepts/reportroot-authorization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/reportroot-authorization?branch=pr-en-us-14138) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031907249263-14138%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=IrO11zY%2Ftolm4ZixI8ilUkhyDJlTLjUoZna31ug1Wos%3D&st=2021-09-03T19%3A05%3A22Z&se=2021-10-04T19%3A10%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 19:14 UTC, Lauragra commented on concepts/reportroot-authorization.md
> +- **User delegated authorization** - Allows an app to read all service usage reports on behalf of the signed-in user. In addition to the app having been granted the required permissions, the user mus
Please verify the casing of the role names - should they all be title case, i.e. to match the admin center UI? Otherwise, please lowercase all but the product names.

2021-09-03 19:15 UTC, jasonjoh commented
Docs Build status updates of commit _[c806827](https://github.com/haizeie/microsoft-graph-docs/commits/c806827d9414bfc3a092d6e4557d79be292cc34c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-14138) (graph-rest-beta) |
[api-reference/v1.0/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/v1.0/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-1.0&branch=pr-en-us-14138) (>= graph-rest-1.0) |
[changelog/Microsoft.O365Reporting.json](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/changelog/Microsoft.O365Reporting.json) | :white_check_mark:Succeeded | |
[concepts/reportroot-authorization.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/concepts/reportroot-authorization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/reportroot-authorization?branch=pr-en-us-14138) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031913530868-14138%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=V8tR93STaKSHdZC8htIGI3BsW8p5Ait2Q%2BbcS%2BDzY94%3D&st=2021-09-03T19%3A10%3A37Z&se=2021-10-04T19%3A15%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 19:17 UTC, Lauragra commented on changelog/Microsoft.O365Reporting.json
> +          "Id": "7ebc6c52-fe03-43ed-a73b-8478651f5c23",
I don't understand these changelog entries as we are not making any updates to these APIs. The changelog is specifically for API-level changes. So far this PR includes only conceptual content updates so we don't need a changelog entry. If you need to call attention to a non-API level change, maybe a blog post is a good solution?

2021-09-03 19:18 UTC, Lauragra requested changes
Please clarify the API-level changes in the API docs or remove the changelog entries.

2021-09-04 01:37 UTC, jasonjoh commented
Docs Build status updates of commit _[99c3598](https://github.com/haizeie/microsoft-graph-docs/commits/99c3598b3a604cd0901f05a4dd474c11f1fd6094)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-14138) (graph-rest-beta) |
[api-reference/v1.0/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/v1.0/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-1.0&branch=pr-en-us-14138) (>= graph-rest-1.0) |
[changelog/Microsoft.O365Reporting.json](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/changelog/Microsoft.O365Reporting.json) | :white_check_mark:Succeeded | |
[concepts/reportroot-authorization.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/concepts/reportroot-authorization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/reportroot-authorization?branch=pr-en-us-14138) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109040135276154-14138%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=KlaufL8hhheFhUpazVGZoWsSPxqJsNKz%2FZ8FgPqtbkY%3D&st=2021-09-04T01%3A32%3A06Z&se=2021-10-05T01%3A37%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-04 01:50 UTC, jasonjoh commented
Docs Build status updates of commit _[14afabc](https://github.com/haizeie/microsoft-graph-docs/commits/14afabce3a165fe2ba46afec395e7df5f0665621)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-14138) (graph-rest-beta) |
[api-reference/v1.0/resources/report.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/api-reference/v1.0/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-1.0&branch=pr-en-us-14138) (>= graph-rest-1.0) |
[concepts/reportroot-authorization.md](https://github.com/haizeie/microsoft-graph-docs/blob/users/yuawa/update_docs/concepts/reportroot-authorization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/reportroot-authorization?branch=pr-en-us-14138) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109040148281187-14138%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=uA5kAp%2BUAQU%2B4IVgwLJ4j%2BOYPUXyMbg1m7JgVBw2lzA%3D&st=2021-09-04T01%3A45%3A08Z&se=2021-10-05T01%3A50%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-04 02:03 UTC, Lauragra approved these changes

2021-09-04 02:07 UTC, merged