Adding add token signing certificate content to v1
microsoftgraph/microsoft-graph-docs pull request #14137
Opened 2021-09-03 04:49 UTC by AllisonAm

2021-09-03 04:52 UTC, jasonjoh commented
Docs Build status updates of commit _[301e7d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/301e7d40aa48765e77988af4b73653d8ca675cc5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md) | :x:Error | | [Details](#user-content-9661e6598196eab680eaa968361e27d4-87656e48)

<a id="9661e6598196eab680eaa968361e27d4-87656e48"></a>
### [api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md)
 - **Line 71, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/serviceprincipal-addtokensigningcertificate-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/serviceprincipal-addtokensigningcertificate-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/serviceprincipal-addtokensigningcertificate-objc-snippets.md'.`````
 - **Line 83, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/serviceprincipal-addtokensigningcertificate-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109030450484578-14137%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=b%2BcCxzjZmDT8bnoWC2efDFzkwNCBSbaLSYWxlUX7USg%3D&st=2021-09-03T04%3A47%3A15Z&se=2021-10-04T04%3A52%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 14:47 UTC, jasonjoh commented
Docs Build status updates of commit _[301e7d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/301e7d40aa48765e77988af4b73653d8ca675cc5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md) | :x:Error | | [Details](#user-content-9661e6598196eab680eaa968361e27d4-287478ac)

<a id="9661e6598196eab680eaa968361e27d4-287478ac"></a>
### [api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md)
 - **Line 71, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/serviceprincipal-addtokensigningcertificate-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/serviceprincipal-addtokensigningcertificate-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/serviceprincipal-addtokensigningcertificate-objc-snippets.md'.`````
 - **Line 83, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/serviceprincipal-addtokensigningcertificate-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031446232904-14137%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=pJ98PpMMQfqEk9eAvAkT7lcz6oQC99dH0nNbh8XJTaM%3D&st=2021-09-03T14%3A42%3A37Z&se=2021-10-04T14%3A47%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 15:30 UTC, FaithOmbongi requested changes

2021-09-03 15:30 UTC, FaithOmbongi commented on api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md
> +Creates a self-signed signing certificate and returns a [selfSignedCertificate](../resources/selfsignedcertificate.md), which is the public part of the generated certificate. The self-signed signing
```suggestion
Creates a self-signed signing certificate and returns a [selfSignedCertificate](../resources/selfsignedcertificate.md) object, which is the public part of the generated certificate. The self-signed signing certificate is composed of the following objects which are added to the [servicePrincipal](../resources/serviceprincipal.md): 
+ The [keyCredentials](../resources/keycredential.md) object with the following objects:
    + A private key object with **usage** set to `Sign`.
    + A public key object with **usage** set to `Verify`.
+ The [passwordCredentials](../resources/passwordcredential.md) object. 


All the objects have the same value of **customKeyIdentifier**.
```

2021-09-03 15:30 UTC, FaithOmbongi commented on api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md
> +The **passwordCredential** is used to open the pfx/private key. Also, it's associated with the privateKey having the same **keyId**. The subject of the certificate is a constant value. It won't be af
```suggestion
The **passwordCredential** is used to open the PFX file (private key). It and the associated private key object have the same value of **keyId**. Once set during creation through the **displayName** property, the subject of the certificate cannot be updated. The **startDateTime** is set to the same time the certificate is created using the action. The **endDateTime** can be up to three years after the certificate is created.
```

2021-09-03 15:30 UTC, FaithOmbongi commented on api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md
> +| endDateTime | DateTimeOffset |The date and time when the credential expires. It can be up to 3 years from the date the certificate is created. If not supplied, the default is three years from the t
```suggestion
| endDateTime | DateTimeOffset |The date and time when the credential expires. It can be up to 3 years from the date the certificate is created. If not supplied, the default is three years from the time of creation. The timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is `2014-01-01T00:00:00Z`.|
```

2021-09-03 15:30 UTC, FaithOmbongi commented on api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md
> +# [HTTP](#tab/http)
Code snippets at auto-generated thanks to this statement `"blockType": "request"` in Line 57. Do not add this manually. See [the guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103162/Generate-code-snippets) for more.
```suggestion
```

2021-09-03 15:30 UTC, FaithOmbongi commented on api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md
> +---
Same comment about code snippets. Do not add these snippets & the closing `---` manually. See [the guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103162/Generate-code-snippets) for more.
```suggestion
```

2021-09-03 15:30 UTC, FaithOmbongi commented on api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md
> +POST https://graph.microsoft.com/beta/servicePrincipals/004375c5-6e2e-4dec-95e3-626838cb9f80/addTokenSigningCertificate
```suggestion
POST https://graph.microsoft.com/v1.0/servicePrincipals/004375c5-6e2e-4dec-95e3-626838cb9f80/addTokenSigningCertificate
```

2021-09-03 15:30 UTC, FaithOmbongi commented on api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md
> +  "@odata.context": "https://graph.microsoft.com/beta/$metadata#microsoft.graph.selfSignedCertificate",
```suggestion
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#microsoft.graph.selfSignedCertificate",
```

2021-09-03 15:30 UTC, FaithOmbongi commented on api-reference/v1.0/resources/selfsignedcertificate.md
> +author: "davidmu"
```suggestion
author: "luleonpla"
```

2021-09-03 15:30 UTC, FaithOmbongi commented on api-reference/v1.0/resources/selfsignedcertificate.md
> +|key|Binary| The value for the key credential. Should be a base-64 encoded value. |
```suggestion
|endDateTime|DateTimeOffset|The date and time at which the credential expires. The timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is `2014-01-01T00:00:00Z`.|
|keyId|Guid|The unique identifier (GUID) for the key.|
|startDateTime|DateTimeOffset|The date and time at which the credential becomes valid. The timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is `2014-01-01T00:00:00Z`. |
|type|String|The type of key credential. "AsymmetricX509Cert".|
|usage|String|A string that describes the purpose for which the key can be used. The possible value is `Verify`.|
|key|Binary| The value for the key credential. Should be a Base-64 encoded value. |
```

2021-09-03 15:30 UTC, FaithOmbongi commented on api-reference/v1.0/resources/selfsignedcertificate.md
> +}
```suggestion
``` json
{
  "@odata.type": "#microsoft.graph.selfSignedCertificate",
  "customKeyIdentifier": "String (Binary)",
  "displayName": "String",
  "endDateTime": "String (timestamp)",
  "key": "String (Binary)",
  "keyId": "Guid",
  "startDateTime": "String (timestamp)",
  "thumbprint": "String",
  "type": "String",
  "usage": "String"
}
```

2021-09-21 23:50 UTC, AllisonAm commented on api-reference/v1.0/resources/selfsignedcertificate.md
> +author: "davidmu"
I changed it to have myself as the owner since Luis is no longer in this area

2021-09-21 23:51 UTC, opbld34 commented
Docs Build status updates of commit _[18bdc6a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/18bdc6a2ae76e3606efff371fee6c0f48ac43a1d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md) | :x:Error | | [Details](#user-content-9661e6598196eab680eaa968361e27d4-972d9ade)
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/beta/api/table-post-rows.md) | :warning:Warning | | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-972d9ade)

<a id="9661e6598196eab680eaa968361e27d4-972d9ade"></a>
### [api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md)
 - **Line 71, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/serviceprincipal-addtokensigningcertificate-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/serviceprincipal-addtokensigningcertificate-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/serviceprincipal-addtokensigningcertificate-objc-snippets.md'.`````
 - **Line 83, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/serviceprincipal-addtokensigningcertificate-java-snippets.md'.`````

<a id="3d4ef16248555d21d47f9f4aef494875-972d9ade"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/beta/api/table-post-rows.md)
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109212349552618-14137%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-22T23%3A51%3A31Z&sr=b&sp=r&sig=FN1eahN5hL3ucN3WtJw%2B2fTlgw7IE1B1PzmwRKd%2F7B8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-21 23:54 UTC, opbld30 commented
Docs Build status updates of commit _[a51ced9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a51ced97b1c7f21c33138b47a3c473e470987a3a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-14137) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-4ddff75a)
[api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/selfsignedcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/selfsignedcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/selfsignedcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |

<a id="3d4ef16248555d21d47f9f4aef494875-4ddff75a"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/beta/api/table-post-rows.md)
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109212352326402-14137%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-22T23%3A54%3A15Z&sr=b&sp=r&sig=mdPdGB7M4F9WYpA5ucMnEZ1xtUF%2FdWBO2HYt6fSXavc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 07:02 UTC, opbld32 commented
Docs Build status updates of commit _[fa57c11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa57c11c0f66649932647b49ce78d686143580d8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b97b028c)

<a id="b97b028c"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109240701456740-14137%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T07%3A02%3A14Z&sr=b&sp=r&sig=KRwkZ7lf5KroWDm7o8GFd%2FpVaBD9fkQH53hbkjvcqOA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 19:00 UTC, opbld34 commented
Docs Build status updates of commit _[7c8bcc6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c8bcc60d64586e089c121e06341518b5663aa72)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/selfsignedcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/selfsignedcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/selfsignedcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109241858327974-14137%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T19%3A00%3A10Z&sr=b&sp=r&sig=MkDNkeI2FNVdL%2BKBmfWOBCSHRRGPogNm6KmnEBz4RCE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-25 00:07 UTC, opbld33 commented
Docs Build status updates of commit _[ccee9a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ccee9a70b929eb84899a05ad31a0b66a86c6973d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/selfsignedcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/selfsignedcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/selfsignedcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109250005377113-14137%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-26T00%3A07%3A26Z&sr=b&sp=r&sig=ypCsIWknLIQn1pbNJaK7RdTl0BZBu%2BIgAdF4ArEsdUw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-04 17:56 UTC, opbld31 commented
Docs Build status updates of commit _[2ccbb68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ccbb686693746f702b9d573f0f77144c8dff2bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/selfsignedcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/selfsignedcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/selfsignedcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110041751364938-14137%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-04T17%3A55%3A59Z&sr=b&sp=r&sig=tWInYzXJA6hEMDMqUbBbNwCkDm1HeviEUnVBDCdyuIM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-30 22:43 UTC, opbld31 commented
Docs Build status updates of commit _[68554d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68554d316492566be84b8307e37cfc307cebe06e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/selfsignedcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/selfsignedcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/selfsignedcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111302241334869-14137%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-31T22%3A43%3A41Z&sr=b&sp=r&sig=ngEV8aTdvHIgysvbIajyWoOAy8CWVU5ZYTRKFEm4oyI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 00:04 UTC, opbld33 commented
Docs Build status updates of commit _[367c0e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/367c0e85cc70cafa9c2c2c704f70d3876326066b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/selfsignedcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/selfsignedcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/selfsignedcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112010000512719-14137%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T00%3A04%3A39Z&sr=b&sp=r&sig=EdZkpPGNTVraDSwseQqrz1ezLb3yv4wl%2B6MLo%2BdC%2BLE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 10:02 UTC, opbld31 commented
Docs Build status updates of commit _[83d2b53](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83d2b535b8cfe065140461ac3a1d873e183faaf5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/selfsignedcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/selfsignedcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/selfsignedcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112011000352712-14137%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T10%3A02%3A24Z&sr=b&sp=r&sig=T1yAfJB5RMb8hP0xym5Y%2FKmUVepEBie9lpnb%2BdiBPWg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 10:07 UTC, FaithOmbongi commented
Hi @AllisonAm, I see this PR has been here a while since I shared the last review feedback. I haven't seen a re-request for review so just proceeding with a re-review and approval anyway.

Pushed a few commits to update the branch and assign you a doc.

2021-12-01 10:10 UTC, opbld31 commented
Docs Build status updates of commit _[ee73cf8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee73cf8939431096fa6da012e439c5bc4980ac52)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/selfsignedcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/selfsignedcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/selfsignedcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112011007466966-14137%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T10%3A10%3A18Z&sr=b&sp=r&sig=li4EryxR03fWffLQj61rkJTTi4YB%2BgYCYakVmWwgE1U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 10:12 UTC, FaithOmbongi approved these changes

2021-12-02 03:34 UTC, opbld32 commented
Docs Build status updates of commit _[cced68d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cced68dcbd639f1afbb3a14d461c82e069763023)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/selfsignedcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/selfsignedcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/selfsignedcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112020332519184-14137%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T03%3A34%3A33Z&sr=b&sp=r&sig=G07%2F7reucrGZLrJmkqpehUtgcjfHkxYjY6nfy5DyHR0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 03:34 UTC, Lauragra approved these changes

2021-12-02 03:36 UTC, opbld30 commented
Docs Build status updates of commit _[e107c55](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e107c55db26f8543e0945230efed64efbba96220)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/api/serviceprincipal-addtokensigningcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/selfsignedcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/selfsignedcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/selfsignedcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-1.0&branch=pr-en-us-14137) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/alamaral-tokensigningcert/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112020334096647-14137%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T03%3A36%3A15Z&sr=b&sp=r&sig=oPNWm5dH3DYdY1J%2FImGxX1RV9Ok2MiDV0KzjT2f7y3s%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 03:44 UTC, merged