Added second example to query by appId
microsoftgraph/microsoft-graph-docs pull request #14136
Opened 2021-09-03 03:23 UTC by merill

Common ask from customers to include examples for querying with object id and appid

2021-09-03 03:25 UTC, jasonjoh commented
Docs Build status updates of commit _[b2f9c6d](https://github.com/merill/microsoft-graph-docs/commits/b2f9c6de9aab5e46b87cda6e0a30911c9c8ea4b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-get.md](https://github.com/merill/microsoft-graph-docs/blob/patch-6/api-reference/v1.0/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-1.0&branch=pr-en-us-14136) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109030323426718-14136%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=rtsLvc%2FMOUHQohGmvi71trHtvWNkp4DLuQn74dTG1Xc%3D&st=2021-09-03T03%3A20%3A20Z&se=2021-10-04T03%3A25%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 01:39 UTC, Lauragra requested changes
Please update the topic in the /beta folder as well. Thanks.

2021-09-15 01:41 UTC, opbld31 commented
Docs Build status updates of commit _[a76c7f9](https://github.com/merill/microsoft-graph-docs/commits/a76c7f9f79b9e229c96809b4d8d4879d519a87db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-get.md](https://github.com/merill/microsoft-graph-docs/blob/patch-6/api-reference/v1.0/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-1.0&branch=pr-en-us-14136) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109150138530428-14136%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=UIgaOwp457jFB22mZ8OwNO3Xf9j7KtJMC4GC7j769yg%3D&st=2021-09-15T01%3A36%3A02Z&se=2021-10-16T01%3A41%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2023-03-16 03:21 UTC, Lauragra commented
Closing due to merge conflict and lack of response.

2023-03-16 03:21 UTC, closed without merging