tushar20 adding SharePoint Ids to Permissions
microsoftgraph/microsoft-graph-docs pull request #14151
Opened 2021-09-03 23:32 UTC by tushar20

2021-09-03 23:33 UTC, jasonjoh commented
Docs Build status updates of commit _[668a5a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/668a5a3946955e45dace5d38a50d0864a2d085b6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-2bba7bb0)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-2bba7bb0)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-2bba7bb0)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-2bba7bb0)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-2bba7bb0)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-2bba7bb0)
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |

<a id="6e691655c42681fe1dcf235bf7a77fc1-2bba7bb0"></a>
### [api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get permission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/permission-get.md(4,8), v1.0/api/site-get-permission.md(2,8)'. Titles must be unique within a docset.`````

<a id="1bdb001d03118040f8fda01d85246a05-2bba7bb0"></a>
### [api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the followi [...]

2021-09-03 23:36 UTC, k-tsoi commented on api-reference/v1.0/resources/permission.md
> +  "@deprecated.GrantedToIdentities": "string",
could probably put the deprecated message here? the string will not change depending on the request

2021-09-03 23:37 UTC, k-tsoi commented on api-reference/v1.0/resources/permission.md
>  | grantedToIdentities | Collection([IdentitySet](identityset.md)) | For link type permissions, the details of the users to whom permission was granted. Read-only.
I wonder if we should make any notes in the descriptions that the field will soon be depercated

2021-09-03 23:38 UTC, k-tsoi commented on api-reference/v1.0/resources/permission.md
>  | grantedToIdentities | Collection([IdentitySet](identityset.md)) | For link type permissions, the details of the users to whom permission was granted. Read-only.
Would be good to find out of the Graph team has an opinion on this

2021-09-03 23:39 UTC, k-tsoi commented on api-reference/v1.0/resources/permission.md
> +        "displayName": "Misty Suarez",
display name does not match

2021-09-03 23:40 UTC, k-tsoi commented on api-reference/v1.0/resources/permission.md
> +GrantedTo and GrantedToIdentities will be deprecated going forward and the response will be migrated to GrantedToV2 and GrantedToIdentitiesV2 respectively under appropriate property names.
probably should make the remarks into a bullet point list

2021-09-03 23:45 UTC, k-tsoi commented on api-reference/v1.0/api/permission-update.md
> +  "roles": [ "write" ]
change back to read to match the request above

2021-09-03 23:59 UTC, k-tsoi commented on api-reference/v1.0/resources/sharePointIdentity.md
> +The "id" property can represent either an AAD id or the SharePoint id.
it maybe worh moving this remark in the description for the Id field.

2021-09-08 19:07 UTC, opbld33 commented
Docs Build status updates of commit _[473ff34](https://github.com/microsoftgraph/microsoft-graph-docs/commits/473ff343b40b1542b5e66c444198d4ff088a3c5f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-e7c57ad6)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-e7c57ad6)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-e7c57ad6)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-e7c57ad6)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-e7c57ad6)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-e7c57ad6)
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |

<a id="6e691655c42681fe1dcf235bf7a77fc1-e7c57ad6"></a>
### [api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get permission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/permission-get.md(4,8), v1.0/api/site-get-permission.md(2,8)'. Titles must be unique within a docset.`````

<a id="1bdb001d03118040f8fda01d85246a05-e7c57ad6"></a>
### [api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the followi [...]

2021-09-08 19:12 UTC, opbld32 commented
Docs Build status updates of commit _[b79fe90](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b79fe90f51f5432b978b9fbce7c9c1cd0b68229a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-e5395d46)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-e5395d46)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-e5395d46)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-e5395d46)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-e5395d46)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-e5395d46)
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |

<a id="6e691655c42681fe1dcf235bf7a77fc1-e5395d46"></a>
### [api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get permission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/permission-get.md(4,8), v1.0/api/site-get-permission.md(2,8)'. Titles must be unique within a docset.`````

<a id="1bdb001d03118040f8fda01d85246a05-e5395d46"></a>
### [api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the followi [...]

2021-09-08 19:14 UTC, opbld32 commented
Docs Build status updates of commit _[4cab7f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4cab7f40977d958ff910372a71d586cec27c5795)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-d818eece)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-d818eece)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-d818eece)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-d818eece)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-d818eece)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-d818eece)
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |

<a id="6e691655c42681fe1dcf235bf7a77fc1-d818eece"></a>
### [api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get permission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/permission-get.md(4,8), v1.0/api/site-get-permission.md(2,8)'. Titles must be unique within a docset.`````

<a id="1bdb001d03118040f8fda01d85246a05-d818eece"></a>
### [api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the followi [...]

2021-09-08 19:16 UTC, opbld34 commented
Docs Build status updates of commit _[94a7504](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94a7504d90672a6acc592596f29ae9eb45d072e9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-6ae1e310)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-6ae1e310)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-6ae1e310)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-6ae1e310)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-6ae1e310)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-6ae1e310)
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |

<a id="6e691655c42681fe1dcf235bf7a77fc1-6ae1e310"></a>
### [api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get permission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/permission-get.md(4,8), v1.0/api/site-get-permission.md(2,8)'. Titles must be unique within a docset.`````

<a id="1bdb001d03118040f8fda01d85246a05-6ae1e310"></a>
### [api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the followi [...]

2021-09-08 19:21 UTC, opbld31 commented
Docs Build status updates of commit _[5e6bf2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e6bf2b0b23672c45406df5ec0a83c34e7285e51)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-ad456ca7)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-ad456ca7)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-ad456ca7)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-ad456ca7)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-ad456ca7)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-ad456ca7)
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |

<a id="6e691655c42681fe1dcf235bf7a77fc1-ad456ca7"></a>
### [api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get permission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/permission-get.md(4,8), v1.0/api/site-get-permission.md(2,8)'. Titles must be unique within a docset.`````

<a id="1bdb001d03118040f8fda01d85246a05-ad456ca7"></a>
### [api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the followi [...]

2021-09-08 19:25 UTC, opbld33 commented
Docs Build status updates of commit _[80c87b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80c87b73fbfcfb00638c87f9681f74d3495b1dce)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-d1fe0af4)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-d1fe0af4)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-d1fe0af4)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-d1fe0af4)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-d1fe0af4)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-d1fe0af4)
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |

<a id="6e691655c42681fe1dcf235bf7a77fc1-d1fe0af4"></a>
### [api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get permission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/permission-get.md(4,8), v1.0/api/site-get-permission.md(2,8)'. Titles must be unique within a docset.`````

<a id="1bdb001d03118040f8fda01d85246a05-d1fe0af4"></a>
### [api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the followi [...]

2021-09-08 19:45 UTC, opbld31 commented
Docs Build status updates of commit _[0e5e884](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e5e884cce6aa53625c19b3e54afe246b499241f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-ba64117f)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-ba64117f)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-ba64117f)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-ba64117f)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-ba64117f)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-ba64117f)
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |

<a id="6e691655c42681fe1dcf235bf7a77fc1-ba64117f"></a>
### [api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get permission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/permission-get.md(4,8), v1.0/api/site-get-permission.md(2,8)'. Titles must be unique within a docset.`````

<a id="1bdb001d03118040f8fda01d85246a05-ba64117f"></a>
### [api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the followi [...]

2021-09-08 21:00 UTC, opbld30 commented
Docs Build status updates of commit _[1f96875](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f96875005b3dd5bd6a8cae5a1d67a13f6aab2ad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-b52ce16f)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-b52ce16f)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-b52ce16f)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-b52ce16f)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-b52ce16f)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-b52ce16f)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-b52ce16f)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-b52ce16f)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-b52ce16f)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-b52ce16f)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-10 22:46 UTC, opbld34 commented
Docs Build status updates of commit _[1bd6bac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1bd6bacc22837512ed5dcca5256ae553b44b9531)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-6051da49)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-6051da49)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-6051da49)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-6051da49)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-6051da49)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-6051da49)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-6051da49)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-6051da49)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-6051da49)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-6051da49)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-10 23:27 UTC, opbld31 commented
Docs Build status updates of commit _[c4d0c17](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4d0c1757d2e7e043c3bd160aaad15483fd75730)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-ae165681)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-ae165681)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-ae165681)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-ae165681)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-ae165681)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-ae165681)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-ae165681)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-ae165681)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-ae165681)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-ae165681)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-21 08:03 UTC, paagarwal123 commented on api-reference/beta/resources/permission.md
> +  "grantedToIdentitiesV2": [{"@odata.type": "microsoft.graph.sharePointIdentitySet"}],
move grantedToIdentitiesV2 before grantedToV2 to maintain alphabetical order.

2021-09-21 08:07 UTC, paagarwal123 commented on api-reference/beta/resources/sharePointIdentity.md
> +title: SharePointIdentity
Make sure that the title field matches the H1. In this case, the title should be:

SharePointIdentity resource type

2021-09-21 08:08 UTC, paagarwal123 commented on api-reference/beta/resources/sharePointIdentity.md
> +The **SharePointIdentity** resource represents the SharePointIdentity of an _actor_.
Resource names in Microsoft Graph are lower camel case, so SharePointIdentity in this case should be lower case

2021-09-21 08:36 UTC, paagarwal123 requested changes

2021-09-21 08:36 UTC, paagarwal123 commented on api-reference/beta/resources/sharePointIdentity.md
> +# SharePointIdentity resource type
Please use lower camel case for resource type SharePointIdentity.
It should be sharePointIdentity.

2021-09-21 08:36 UTC, paagarwal123 commented on api-reference/beta/resources/sharePointIdentity.md
> +It extends from the **Identity** resource to provide capability to expose SharePoint specific information, for example loginName or SharePoint ids.
Make Identity resource as lower camel case

2021-09-21 08:36 UTC, paagarwal123 commented on api-reference/beta/resources/sharePointIdentity.md
> +| Property         | Type                        | Description
For compatibility, you should also add a pipe on either end of the row. Please, apply this change to all rows in this table.

2021-09-21 08:36 UTC, paagarwal123 commented on api-reference/beta/resources/sharePointIdentity.md
> +  "keywords": "sharePointIdentity,loginName, sharePointId, owner, modifier, app, user, group",
add space between sharePointIdentity and loginName

2021-09-21 08:36 UTC, paagarwal123 commented on api-reference/beta/resources/sharePointIdentitySet.md
> +title: SharePointIdentitySet
make it lower camel case and same as H1 value:
sharePointIdentitySet resource type

2021-09-21 08:36 UTC, paagarwal123 commented on api-reference/beta/resources/sharePointIdentitySet.md
> +# SharePointIdentitySet resource type
make it lower camel case

2021-09-21 08:36 UTC, paagarwal123 commented on api-reference/beta/resources/sharePointIdentitySet.md
> +description: "The SharePointIdentitySet resource is a keyed collection of SharePointIdentity and Identity resources."
make resource lower camel case

2021-09-21 08:36 UTC, paagarwal123 commented on api-reference/beta/resources/sharePointIdentitySet.md
> +The **SharePointIdentitySet** resource is a keyed collection of [sharePointIdentity](sharePointIdentity.md) resources. It extends from the **IdentitySet** resource to provide capability to expose Sha
make all the resources in lower camel case wherever applicable.
IdentitySet ->  identitySet

2021-09-21 08:36 UTC, paagarwal123 commented on api-reference/beta/resources/sharePointIdentitySet.md
> +| user        | [Identity][]           | The user associated with this action. Optional
move user after siteGroup to follow alphabetical order

2021-09-21 08:36 UTC, paagarwal123 commented on api-reference/beta/resources/sharePointIdentitySet.md
> +See [DriveItem][] for usage of **SharePointIdentitySet** resources.
change resource name to lower camel case.

2021-09-21 08:36 UTC, paagarwal123 commented on api-reference/beta/resources/sharePointIdentitySet.md
> +
Add beta disclaimer for this new resource: [!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]

2021-09-21 08:36 UTC, paagarwal123 commented on api-reference/beta/resources/sharePointIdentity.md
> +
Add beta disclaimer : [!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]

2021-09-21 08:36 UTC, paagarwal123 commented on api-reference/v1.0/resources/sharePointIdentity.md
> +| Property         | Type                        | Description
keep the elements in alphabetical order

2021-09-21 08:36 UTC, paagarwal123 commented on changelog/Microsoft.FileServices.json
> +      "Description": "This resource type will hold information of SharePoint Identity",
For addition of resource: Description can be like below:
Added the [sharePointIdentity](https://docs.microsoft.com/en-us/graph/api/resources/sharePointIdentity?view=graph-rest-beta) resource type.

2021-09-21 08:36 UTC, paagarwal123 commented on changelog/Microsoft.FileServices.json
> +      "Description": "The property is of type SharePointIdentity and will replace grantedToV2 which is being deprecated. More details can be found here(https://docs.microsoft.com/en-us/graph/api/reso
... and will replace grantedToV2 should be changes to grantedTo

2021-09-21 08:36 UTC, paagarwal123 commented on changelog/Microsoft.FileServices.json
> +      "Description": "The property is of type SharePointIdentity and will replace grantedToIdentitiesV2 which is being deprecated. More details can be found here(https://docs.microsoft.com/en-us/grap
and will replace grantedToIdentitiesV2 -> replace with grantedToIdentities

2021-09-23 21:10 UTC, opbld34 commented
Docs Build status updates of commit _[b26a371](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b26a3718642af2b891d84646795eb816d94683da)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-0d5a6b4f)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-0d5a6b4f)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-0d5a6b4f)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-0d5a6b4f)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-0d5a6b4f)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-0d5a6b4f)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-0d5a6b4f)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-0d5a6b4f)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-0d5a6b4f)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-0d5a6b4f)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-23 21:11 UTC, tushar20 commented on api-reference/beta/resources/permission.md
> +  "grantedToIdentitiesV2": [{"@odata.type": "microsoft.graph.sharePointIdentitySet"}],
Carrying forward the logical order from before

2021-09-23 21:17 UTC, opbld30 commented
Docs Build status updates of commit _[d4d9a4a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d4d9a4ab7cca2c521b3c4a490f31ff8d72d4ca19)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-63f808d0)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-63f808d0)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-63f808d0)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-63f808d0)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-63f808d0)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-63f808d0)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-63f808d0)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-63f808d0)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-63f808d0)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-63f808d0)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-23 21:21 UTC, opbld31 commented
Docs Build status updates of commit _[7d78abe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d78abedc5337074722e7b86eba0cb282c8c0532)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-409f6922)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-409f6922)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-409f6922)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-409f6922)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-409f6922)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-409f6922)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-409f6922)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-409f6922)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-409f6922)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-409f6922)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-23 21:24 UTC, opbld31 commented
Docs Build status updates of commit _[a241733](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2417333205d192319e270431237b0da46821032)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-9a8bf346)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-9a8bf346)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-9a8bf346)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-9a8bf346)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-9a8bf346)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-9a8bf346)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-9a8bf346)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-9a8bf346)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-9a8bf346)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-9a8bf346)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-23 21:26 UTC, opbld32 commented
Docs Build status updates of commit _[1396eb1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1396eb1f6297b23eee398ae5d213b86dfeb52245)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-3ac3d8dc)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-3ac3d8dc)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-3ac3d8dc)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-3ac3d8dc)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-3ac3d8dc)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-3ac3d8dc)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-3ac3d8dc)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-3ac3d8dc)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-3ac3d8dc)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-3ac3d8dc)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-23 21:28 UTC, opbld32 commented
Docs Build status updates of commit _[c98a09e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c98a09e9ee53a73a5ff218031509a4911694f9d3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-5ee9f0a3)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-5ee9f0a3)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-5ee9f0a3)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-5ee9f0a3)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-5ee9f0a3)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-5ee9f0a3)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-5ee9f0a3)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-5ee9f0a3)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-5ee9f0a3)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-5ee9f0a3)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-23 21:51 UTC, opbld32 commented
Docs Build status updates of commit _[f4cf545](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4cf54514708732b61cc78e72376d5b7279deac9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-49a7e42f)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-49a7e42f)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-49a7e42f)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-49a7e42f)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-49a7e42f)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-49a7e42f)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-49a7e42f)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-49a7e42f)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-49a7e42f)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-49a7e42f)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-23 21:53 UTC, opbld31 commented
Docs Build status updates of commit _[000440a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/000440aa7426f94c2c5464f7d7faad31423b343e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-00f5d0f2)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-00f5d0f2)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-00f5d0f2)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-00f5d0f2)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-00f5d0f2)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-00f5d0f2)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-00f5d0f2)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-00f5d0f2)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-00f5d0f2)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-00f5d0f2)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-23 21:54 UTC, opbld33 commented
Docs Build status updates of commit _[9fe8c2d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9fe8c2d38647166b480e5587d55a4e08683de1ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-c8e63a2d)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-c8e63a2d)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-c8e63a2d)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-c8e63a2d)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-c8e63a2d)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-c8e63a2d)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-c8e63a2d)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-c8e63a2d)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-c8e63a2d)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-c8e63a2d)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-23 22:05 UTC, opbld34 commented
Docs Build status updates of commit _[6e0982a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e0982a16ff14826cc0829ffba53ed0c1a0e1394)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-60fd75a0)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-60fd75a0)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-60fd75a0)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-60fd75a0)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-60fd75a0)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-60fd75a0)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-60fd75a0)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-60fd75a0)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-60fd75a0)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-60fd75a0)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-23 22:06 UTC, opbld33 commented
Docs Build status updates of commit _[9a3784d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a3784ddac5116f49925c0de1add3a990bff555a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-35c06dc0)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-35c06dc0)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-35c06dc0)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-35c06dc0)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-35c06dc0)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-35c06dc0)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-35c06dc0)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-35c06dc0)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-35c06dc0)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-35c06dc0)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-23 22:09 UTC, opbld31 commented
Docs Build status updates of commit _[c4fedee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4fedee2587ac113fcf4c593b27274359be94aff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-5c457b70)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-5c457b70)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-5c457b70)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-5c457b70)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-5c457b70)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-5c457b70)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-5c457b70)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-5c457b70)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-5c457b70)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-5c457b70)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-23 22:11 UTC, opbld32 commented
Docs Build status updates of commit _[fe85405](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe854052765683eae2af04d0e98a3479221b9ec2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-dd341184)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-dd341184)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-dd341184)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-dd341184)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-dd341184)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-dd341184)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-dd341184)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-dd341184)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-dd341184)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-dd341184)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-09-24 06:06 UTC, paagarwal123 approved these changes

2021-09-24 20:27 UTC, k-tsoi commented on api-reference/beta/resources/permission.md
> +1. OneDrive for Business and SharePoint document libraries do not return the **inheritedFrom** property.
Not sure if Graph has preferences on numbered list or  bullet list

2021-09-24 20:28 UTC, k-tsoi approved these changes

2021-11-01 20:26 UTC, JarbasHorst commented
@tushar20, checking to see if you have any questions regarding some of the feedback I provided?

2021-11-19 12:27 UTC, opbld32 commented
Docs Build status updates of commit _[d0da915](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0da91593e760b5afb17977bae35beab1d9d1245)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-45064339)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-45064339)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-45064339)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-45064339)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-45064339)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-45064339)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-45064339)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-45064339)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-45064339)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-45064339)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-11-22 22:06 UTC, JarbasHorst requested changes

2021-11-23 17:29 UTC, opbld34 commented
Docs Build status updates of commit _[c7f7d60](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c7f7d6032af8555557b3fea995ad60e580202e36)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-b52075d0c5f02272084523e90515aeb0-5cb3bef6)
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-e8273411d709ee1b9bdc38eed6111aab-5cb3bef6)
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-606a02b9ab68bcbf6e29b7550b7bbcf3-5cb3bef6)
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) | [Details](#user-content-a6be9f334f6320799a85508aa58bdaee-5cb3bef6)
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-5cb3bef6)
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-1bdb001d03118040f8fda01d85246a05-5cb3bef6)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-5cb3bef6)
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-85a882527a917505dbed679028cd2efa-5cb3bef6)
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-f6ce61a9df8c41d651655f198e8d73df-5cb3bef6)
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-4b3394a3c843e19f99422d06be8b997e-5cb3bef6)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site [...]

2021-11-23 19:36 UTC, JarbasHorst requested changes

2021-11-23 19:36 UTC, JarbasHorst commented on api-reference/beta/resources/sharePointIdentity.md
> +ms.prod: "sharePoint"
Hi @tushar20, I noticed that the API doctor shows the following message: Invalid value for 'ms.prod': 'sharePoint'. I checked internally and the ms.prod values should be provided in lowercase, and/or separated by hyphens. In this case, please replace sharePoint with sharepoint. This should fix these warning messages. Please apply this change to all ms.prod attributes in this PR that either don't have a value or the value is invalid.

2021-11-23 20:06 UTC, opbld33 commented
Docs Build status updates of commit _[24586a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24586a0a5915d839352131f87bdfe34e30600910)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-2cf8af74)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-2cf8af74)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-23 20:29 UTC, JarbasHorst commented
@Lauragra, this PR is ready for final review.

2021-11-30 00:46 UTC, Lauragra commented on api-reference/beta/api/driveitem-invite.md
> +          "displayName": "Ryan Gregg"
Please change this to an approved fictitious name, not the name of an MSFT. You can generate a list of approved fictitious names at CELAWeb.

2021-11-30 00:47 UTC, Lauragra commented on api-reference/beta/api/driveitem-list-permissions.md
> +          "displayName": "John Doe"
Please replace with an approved fictitious name.

2021-11-30 00:47 UTC, Lauragra commented on api-reference/beta/api/permission-get.md
> +      "displayName": "Ryan Gregg"
Replace name.

2021-11-30 00:47 UTC, Lauragra commented on api-reference/beta/api/permission-update.md
> +      "displayName": "Ryan Gregg"
Global: Please update this everywhere.

2021-11-30 00:56 UTC, opbld31 commented
Docs Build status updates of commit _[5122270](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5122270d63bd512941293c9ddcee6887d2603d7a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-47c39c81)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-47c39c81)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharePointIdentitySet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 01:15 UTC, opbld34 commented
Docs Build status updates of commit _[15f2f61](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15f2f614f0d09b9d364761b30678f2cb6b0e7b50)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-0dfecd1d)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-0dfecd1d)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharePointIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 01:20 UTC, opbld34 commented
Docs Build status updates of commit _[7d1b918](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d1b9183d2a9ebfdbec1588c0d190dbc8b2bc3fa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-30b03568)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-30b03568)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en- [...]

2021-11-30 01:22 UTC, opbld33 commented
Docs Build status updates of commit _[22ae06c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22ae06cc05cf63a0fa99c65fd442e06b8589277a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-b0fae2ec)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-b0fae2ec)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en- [...]

2021-11-30 01:24 UTC, opbld30 commented
Docs Build status updates of commit _[0a04c62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a04c625c70bbc067c57f6b5a46f6866a00dcc93)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-3a66b0e5)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-3a66b0e5)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharePointIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharePointIdentitySet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en- [...]

2021-11-30 01:27 UTC, opbld32 commented
Docs Build status updates of commit _[fae4e7a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fae4e7a86c0b55ef371aa96c24eabad28b1889e7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-80d5a2b4)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-80d5a2b4)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 01:29 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +  "Version": "v1.0",
This ChangeList item looks like a duplicate of the previous; you actually have two ChangeLists for v1.0 and two for beta. Please remove the duplicates.

2021-11-30 01:29 UTC, opbld32 commented
Docs Build status updates of commit _[010afb5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/010afb5c51a489f0972fe8f6425543c6553c1a26)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-84c07df4)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-84c07df4)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 01:32 UTC, opbld32 commented
Docs Build status updates of commit _[f2c613d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2c613dc2077af2b3aaf99b13941ceb0f67a1ebe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-3daffcb3)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-3daffcb3)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 18:10 UTC, tushar20 commented on changelog/Microsoft.FileServices.json
> +  "Version": "v1.0",
The target for both in v1.0 is different. One being "Files" and the other being "Sites and Lists". The same goes for beta. How do you recommend to proceed with this?

2021-11-30 18:24 UTC, opbld32 commented
Docs Build status updates of commit _[3c3e39f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c3e39fbb291191d09e617611e3a32a5b11554b0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-9a219088)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-9a219088)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 18:31 UTC, opbld34 commented
Docs Build status updates of commit _[1b215f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b215f3859adb1b03ab2306a06ed3c46b4dae9d4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-181df507)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-181df507)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 18:32 UTC, opbld32 commented
Docs Build status updates of commit _[54c50aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/54c50aa97f9e47389adb3ad3e4e3e05f34b877c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-98a8facc)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-98a8facc)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 18:34 UTC, opbld32 commented
Docs Build status updates of commit _[1bd4d6a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1bd4d6a49a0bf50ffade0aa3f40b2709e8fae2d6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-038e94f9)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-038e94f9)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 18:37 UTC, opbld31 commented
Docs Build status updates of commit _[18578e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/18578e4bf6308bb00a746cb691877cf1b211a47f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-b8c618ea)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-b8c618ea)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 18:40 UTC, opbld30 commented
Docs Build status updates of commit _[d2c9526](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2c9526ef704f8e354161438a6da80480b8c36df)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-61698363)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-61698363)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 18:42 UTC, opbld31 commented
Docs Build status updates of commit _[e278a69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e278a69dc9127807487f8376d8be7fe279b583d4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-353e036b)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-353e036b)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 18:43 UTC, opbld33 commented
Docs Build status updates of commit _[f8aad9e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8aad9ed9535c04eb04ffa8bf52be630161f43b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-153d771f)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-153d771f)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 21:22 UTC, opbld33 commented
Docs Build status updates of commit _[08f3b37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08f3b37bcd892ad6c376a5a4aca60f3be5d45826)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-496bbc82)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-496bbc82)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 21:23 UTC, Lauragra approved these changes

2021-11-30 21:23 UTC, opbld33 commented
Docs Build status updates of commit _[1ffbb5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ffbb5da3b6891e4dc1f5371d0c6808a3961c39b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-647792fd)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-647792fd)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 21:25 UTC, opbld31 commented
Docs Build status updates of commit _[89388d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89388d66af8f8e5dd33ad4e2ccf755d6cb196e74)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-6e691655c42681fe1dcf235bf7a77fc1-30848224)
[api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-get-permission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) | [Details](#user-content-5d1a2acbfb25666c9dba4ac794d3002f-30848224)
[api-reference/beta/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentity?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/beta/resources/sharepointidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/beta/resources/sharepointidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-beta&branch=pr-en-us-14151) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-invite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitem-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/driveitem-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permission-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/permission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-update?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0&branch=pr-en-us-14151) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/sharepointidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tushar20-sharePointIds-permissions/api-reference/v1.0/resources/sharepointidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2021-11-30 21:25 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +  "Version": "v1.0",
Okay, I think it's fine this way. There's a separate JSON file for Sites and lists entries but they all get combined into one on the site so it doesn't technically matter which file the ChangeList entries are in.

2021-12-01 00:35 UTC, merged