Update externalGroup API and externalItem API docs
microsoftgraph/microsoft-graph-docs pull request #14168
Opened 2021-09-06 21:46 UTC by mecampos

Update externalGroup API and externalItem API docs, based on the breaking changes blog post: https://developer.microsoft.com/en-us/graph/blogs/breaking-changes-to-the-microsoft-graph-connectors-api-beta/

2021-09-06 21:48 UTC, jasonjoh commented
Docs Build status updates of commit _[217d9d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/217d9d3f573722bff8bf243a7bb518e3202fa2f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109062146531060-14168%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=kahCTjm4sa7sGSt%2BVS%2FLxW4cOTVOTeejIHg2xq%2B768Y%3D&st=2021-09-06T21%3A43%3A30Z&se=2021-10-07T21%3A48%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-09 03:00 UTC, Lauragra approved these changes

2021-09-09 14:59 UTC, sacampbe-msft commented
Thanks for making these changes Melissa. I do have some suggestions:

1. Could you add Get ExternalGroup Member?
2. Add a note about the ExternalGroupMember being replaced by the Identity type on the relevant pages (post-members, externalGroupMember resource)

2021-09-20 22:31 UTC, opbld30 commented
Docs Build status updates of commit _[920702c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/920702c950ab114d7d6c6cfb216a37c5d07184a3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-15fefd23)
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroupmember?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-15fefd23"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml)
 - **Line 13441, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/externalconnectors-externalgroup-get.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109202229282820-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-21T22%3A31%3A17Z&sr=b&sp=r&sig=EsRTZOu8JhDzIfjTetW3k3L91U39H8xbcfPMPQJHij4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-20 22:45 UTC, opbld30 commented
Docs Build status updates of commit _[f671793](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6717938ef9514eba1b93769503ab9129cbf8418)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :x:Error | | [Details](#user-content-d147dafefd05d80fef13fb29bc046399-1dcfe574)

<a id="d147dafefd05d80fef13fb29bc046399-1dcfe574"></a>
### [api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md)
 - **Line 65, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-externalgroup-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-externalgroup-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-externalgroup-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/get-externalgroup-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109202243541515-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-21T22%3A45%3A28Z&sr=b&sp=r&sig=3QfQQDJTbUiYw0difhN74tJRotjMAUNwHzbA2KwXS9w%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-20 23:15 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-externalgroupmember.md
> -title: "externalGroupMember resource type"
The file path should also reflect the externalGroupMember -> Identity change. Please rename to api-reference/beta/resources/externalconnectors-identity.md, this will affect the links, please update those accordingly as well.

2021-09-20 23:18 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-externalgroupmember.md
> -title: "externalGroupMember resource type"
Also this file has alot of references to "IdentitySource" which is being deprecated in this change. It might be possible to just copy the contents of this file over https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/externalconnectors-identity.md

2021-09-20 23:19 UTC, sacampbe-msft commented on api-reference/beta/api/externalconnectors-externalgroup-post-members.md
> +  "type": "externalGroup",
type:group

2021-09-21 18:15 UTC, opbld32 commented
Docs Build status updates of commit _[c502184](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c502184a1764bc0e20f300426aa9b6a41bec0c07)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) | [Details](#user-content-9baae009e5c5bc26132bcf56f5d8a085-ef260d5b)
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |

<a id="9baae009e5c5bc26132bcf56f5d8a085-ef260d5b"></a>
### [api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md)
 - **Line 22, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/externalconnectors-identity-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109211813382011-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-22T18%3A15%3A28Z&sr=b&sp=r&sig=ARn1Y6MLEhjedwGMvETPPnZ44%2BnVwJu9%2FTTLi76SO%2B0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-21 18:31 UTC, opbld34 commented
Docs Build status updates of commit _[f7d44dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7d44dd030989e079d085fb8155d502c9fbbbecf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109211829526995-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-22T18%3A31%3A41Z&sr=b&sp=r&sig=INYXWCKYlfRmxJBAzGKZeGtUz1tm4B2PKJeLEu8me64%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-21 20:39 UTC, David1997sb commented on api-reference/beta/resources/externalconnectors-externalgroupmember.md
> -title: "externalGroupMember resource type"
Updated

2021-09-21 20:39 UTC, David1997sb commented on api-reference/beta/api/externalconnectors-externalgroup-post-members.md
> +  "type": "externalGroup",
Updated

2021-09-21 21:24 UTC, opbld32 commented
Docs Build status updates of commit _[fd77ece](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fd77ece55671857f54a540b2227e81d6ccb730c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-14168) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109212122324233-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-22T21%3A24%3A16Z&sr=b&sp=r&sig=ceuwoAjGRGUjUI0SSHWCg1n5qDndG0TNb5h7nKdUcSs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-21 21:42 UTC, opbld31 commented
Docs Build status updates of commit _[52b39e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52b39e0783693f220815570eda2ffa7ab9cf8a41)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-99533513)
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-14168) (>= graph-rest-1.0) |

<a id="3d4ef16248555d21d47f9f4aef494875-99533513"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/table-post-rows.md)
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109212140528197-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-22T21%3A42%3A30Z&sr=b&sp=r&sig=pKNV%2FuJaNbJaVXlCtVI0am7VOZwMtX%2FNo9F8%2Fbc2sK4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/ [...]

2021-09-21 21:56 UTC, opbld30 commented
Docs Build status updates of commit _[826245c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/826245c5dbb08eec2077f7376a743e5bcb0779fe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-bf804373)
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/v1.0/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/v1.0/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-1.0&branch=pr-en-us-14168) (>= graph-rest-1.0) |

<a id="3d4ef16248555d21d47f9f4aef494875-bf804373"></a>
### [api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/table-post-rows.md)
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109212155079608-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-22T21%3A56%3A54Z&sr=b&sp=r&sig=LCYXuawzzxbSmzSZIGWaXnDm98owPYvPvLeh%2FhFsviM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help [...]

2021-09-23 01:05 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-identity.md
> +[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]
Remove beta disclaimer

2021-09-23 01:09 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-externalgroup.md
> +| members      | [microsoft.graph.externalConnectors.externalGroupMember](../resources/externalconnectors-identity.md) collection | A member added to an **externalGroup**. You can add Azure Active Di
Also update the type from microsoft.graph.externalConnectors.externalGroupMember to microsoft.graph.externalConnectors.identity

2021-09-23 01:11 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-identity.md
> +[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]
Ignore this comment, this is /beta, it should be here.

2021-09-23 01:15 UTC, sacampbe-msft commented on api-reference/v1.0/resources/externalconnectors-identity.md
> +| type           | microsoft.graph.externalConnectors.externalGroup | The type of identity. Possible values are: `user` or `group` for Azure AD identities and `externalgroup` for groups in an externa
Revert this change, this type is identityType.

2021-09-23 01:22 UTC, sacampbe-msft commented
@angelgolfer-ms I am requesting your review on this PR, it's a followup to https://github.com/microsoftgraph/microsoft-graph-docs/pull/13607 bringing the future looking shape from V1 to /beta,

2021-09-23 17:04 UTC, opbld33 commented
Docs Build status updates of commit _[4c15ca0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c15ca0844ec823b0f748a6a66e08012c1541cf9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109231702425751-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-24T17%3A04%3A51Z&sr=b&sp=r&sig=8TTvkx8FgyjFeL%2B5QFlYnLX6rXwlr%2FkRsKH54mY4vdk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 18:26 UTC, opbld32 commented
Docs Build status updates of commit _[4184be3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4184be3b8665f0a719fe0ccfa5de91de4cc09cc0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109241824512002-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T18%3A26%3A46Z&sr=b&sp=r&sig=yZXLz6%2FhagnLfkCz148NTVzL%2BnUsuSCdd7rlpBupr3g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 18:44 UTC, opbld31 commented
Docs Build status updates of commit _[9842001](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9842001988ab0e2ccf371b0999fb67b3e1a20e61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalitem-update?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109241842152190-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T18%3A43%3A59Z&sr=b&sp=r&sig=5i4J%2BdhuRFS96pJ1uwi5UdC4Mqbh2GIfQ13cqAKtV1Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 20:35 UTC, opbld32 commented
Docs Build status updates of commit _[df44149](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df441491e1b21869465bada0fef418b623c85238)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bfaddad4)

<a id="bfaddad4"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111182034507609-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-19T20%3A35%3A12Z&sr=b&sp=r&sig=eYrEeczLtIp2D6ojVVvH9KYLi4xCdcPROzFW4u8xCm0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 20:51 UTC, opbld34 commented
Docs Build status updates of commit _[c49a618](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c49a6187cad3f083c2c8d0d1a42eb6b00d6696af)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111182047004333-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-19T20%3A51%3A16Z&sr=b&sp=r&sig=u4%2FGFXvur32WxhGLIQ7BGf1cyU0VotyACDpHUAynuvg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 21:03 UTC, opbld32 commented
Docs Build status updates of commit _[21fe027](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21fe027a44d6872c0550471e3fff6f4584ed1673)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/educationonerosterapidataprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/educationonerosterapidataprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationonerosterapidataprovider?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111182101173836-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-19T21%3A03%3A49Z&sr=b&sp=r&sig=U7Ob74ar47ZX7rvjm0rU6kkuZLK5EmzmM%2BY1DfKEB%2B0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 22:05 UTC, opbld33 commented
Docs Build status updates of commit _[9ae644a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ae644a8144f431cc68f8467b9b5de07f45336b2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/educationonerosterapidataprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/educationonerosterapidataprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationonerosterapidataprovider?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/v1.0/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/v1.0/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-1.0&branch=pr-en-us-14168) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111182203171500-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-19T22%3A05%3A10Z&sr=b&sp=r&sig=%2Bj4k6vJdKACZKS1%2FDl9DUnSIsqzldEIhV2Vy5ezod5M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 22:09 UTC, opbld30 commented
Docs Build status updates of commit _[6322479](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63224799821bf760480531f4b27a40c58908ba34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/educationonerosterapidataprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/educationonerosterapidataprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationonerosterapidataprovider?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111182207126233-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-19T22%3A09%3A27Z&sr=b&sp=r&sig=3oKOGDMQEoVm4V1EoN2fvi4hOZOYuFlFbK%2FBXtxVMHY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 22:35 UTC, opbld33 commented
Docs Build status updates of commit _[cc8355a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc8355a3e9558e609fcdc62390157ad39298148b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/educationonerosterapidataprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/educationonerosterapidataprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationonerosterapidataprovider?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111182234002488-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-19T22%3A35%3A40Z&sr=b&sp=r&sig=5lgwXZt7ez1fdciE0rLNZwg0c8nAvbh5EA6lmEeTLUQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-22 16:17 UTC, opbld32 commented
Docs Build status updates of commit _[b72416d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b72416d39c24710ec99555c4578f39f62da96ab3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/educationonerosterapidataprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/educationonerosterapidataprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationonerosterapidataprovider?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111221614162256-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-23T16%3A17%3A04Z&sr=b&sp=r&sig=6JN%2F1Sy%2F%2Fccom81PUQ3Ul6lsdYFVS05CaDJBYG1N118%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-22 16:44 UTC, opbld31 commented
Docs Build status updates of commit _[5ca91a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5ca91a2058dc262a11073183ee7875bd26b4c61e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/educationonerosterapidataprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/educationonerosterapidataprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationonerosterapidataprovider?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111221643293133-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-23T16%3A44%3A58Z&sr=b&sp=r&sig=JjYUosyuKb0DNYcHlQOFrmwBYl4B0VBajrj6dD%2Fzmvg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-23 02:04 UTC, opbld33 commented
Docs Build status updates of commit _[d0d5ac5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0d5ac5dcab4ec1ca5ba56950fb0589d2cf54540)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/java/get-externalgroup-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/javascript/get-externalgroup-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/includes/snippets/objc/get-externalgroup-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/educationonerosterapidataprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/educationonerosterapidataprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationonerosterapidataprovider?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111230203032003-14168%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-24T02%3A04%3A48Z&sr=b&sp=r&sig=AOnx9kVkNjM2QVRpduS67xxwrVzfTvdd1L7TJNu6lWc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-20 20:56 UTC, sacampbe-msft approved these changes
@mecampos could we check this in? The schema is now live

2021-12-23 21:05 UTC, isvargasmsft commented
@Lauragra more commits were pushed since the last approval. Can you take a look please?

2022-01-03 23:19 UTC, sacampbe-msft commented
> @Lauragra more commits were pushed since the last approval. Can you take a look please?

@mecampos @isvargasmsft is there anyone else who can review the latest updates and check this in?

2022-01-05 20:51 UTC, Lauragra commented on api-reference/beta/api/externalconnectors-externalgroup-get.md
> +GET https://graph.microsoft.com/v1.0/external/connections/contosohr/groups/31bea3d537902000
Please update this to use beta in the URL since this is a beta topic.

2022-01-05 20:51 UTC, Lauragra commented on api-reference/beta/api/externalconnectors-externalgroup-get.md
> +# [C#](#tab/csharp)
Please remove the snippet links, including line 54. The snippets are autogenerated as part of our weekly snippet process and the links will be inserted automatically when we merge into main.

2022-01-05 21:01 UTC, Lauragra commented on api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md
> +description: "Automatically generated file. DO NOT MODIFY"
Did you add these manually? The snippets are autogenerated via our weekly process; we don't include them in the authoring branches.

2022-01-05 21:03 UTC, Lauragra commented on api-reference/beta/resources/externalconnectors-externalgroupmember.md
> -title: "externalGroupMember resource type"
If this is a deprecation, we need to follow the deprecation process and announce in advance to give users time to update to use the new/replacement API. Is that happening? More details about deprecated APIs are in this topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103183/Deprecate-docs

2022-01-05 22:23 UTC, Lauragra commented on api-reference/beta/resources/externalconnectors-identity.md
> +title: "Identity resource type"
Resource names are lower camel case, so this should be identity in the title field and the H1.

2022-01-05 22:25 UTC, Lauragra commented on api-reference/beta/resources/externalconnectors-identity.md
> +Represents an [identity](externalconnectors-externalgroup.md) used to set permissions on external content added to Microsoft Graph.
This description isn't clear. It looks like you're using the name of the resource in the description, although the link target is to externalGroup. Is this suggested revised description accurate?

"Represents an external group member who set permissions on external content added to Microsoft Graph."

2022-01-05 22:36 UTC, Lauragra commented on api-reference/beta/resources/externalconnectors-externalgroup.md
> +|[Create member](../api/externalconnectors-externalgroup-post-members.md)|[microsoft.graph.externalConnectors.identityType](../resources/externalconnectors-identity.md)|Create a new **externalGroupMe
Is this description still accurate, if the externalGroupMember resource is deprecated/removed? Suggested revision: "Create a new member of an **externalGroup** object." If you revise, you'll want to revise the description in the method topic as well.

2022-01-05 23:01 UTC, Lauragra commented on changelog/Microsoft.Search.json
> +              "Id": "e1972a45-5986-409c-b978-9e44093bd487",
It looks like you deleted some changelog entries and replaced with others. Instead, please just add new entries to the changelog that describe the latest updates, without removing or updating past entries.

2022-01-10 15:09 UTC, mecampos commented on api-reference/beta/includes/snippets/csharp/get-externalgroup-csharp-snippets.md
> +description: "Automatically generated file. DO NOT MODIFY"
Deleted file.

2022-01-10 16:02 UTC, mecampos commented on api-reference/beta/resources/externalconnectors-identity.md
> +title: "Identity resource type"
Updated as recommended.

2022-01-10 16:04 UTC, mecampos commented on api-reference/beta/resources/externalconnectors-identity.md
> +Represents an [identity](externalconnectors-externalgroup.md) used to set permissions on external content added to Microsoft Graph.
@sacampbe-msft Please review and comment.

2022-01-10 16:05 UTC, mecampos commented on api-reference/beta/resources/externalconnectors-externalgroup.md
> +|[Create member](../api/externalconnectors-externalgroup-post-members.md)|[microsoft.graph.externalConnectors.identityType](../resources/externalconnectors-identity.md)|Create a new **externalGroupMe
@sacampbe-msft Please review and comment.

2022-01-10 17:42 UTC, opbld34 commented
Docs Build status updates of commit _[4723175](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4723175fc5e510f0c5e7b52157ebd5c1d4666be1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :x:Error | | [Details](#user-content-d147dafefd05d80fef13fb29bc046399-1c8ab626)

<a id="d147dafefd05d80fef13fb29bc046399-1c8ab626"></a>
### [api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md)
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-externalgroup-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-externalgroup-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-externalgroup-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-externalgroup-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201101741104746-14168%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T17%3A42%3A57Z&sr=b&sp=r&sig=bFLGbm4ClF1%2FLpxAzxSrUscM7uhUDnNESGSQpEB1rjQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 17:50 UTC, opbld32 commented
Docs Build status updates of commit _[3bf862d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3bf862dca0514f2c1c89ce3a5030b26140b81902)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :x:Error | | [Details](#user-content-d147dafefd05d80fef13fb29bc046399-c0f33fa3)

<a id="d147dafefd05d80fef13fb29bc046399-c0f33fa3"></a>
### [api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md)
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-externalgroup-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-externalgroup-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-externalgroup-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-externalgroup-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201101748095106-14168%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T17%3A50%3A07Z&sr=b&sp=r&sig=yzrFea2AcMKhJ14uXFLFrjubcSlwONEFeN48gCvY498%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 20:44 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-externalgroupmember.md
> -title: "externalGroupMember resource type"
@Lauragra We have shared this change with customers from August 2021 https://devblogs.microsoft.com/microsoft365dev/breaking-changes-to-the-microsoft-graph-connectors-api-beta/ and given sufficient time for api developers to update/move to our v1.0 apis.

cc: @snlraju-msft

2022-01-19 20:52 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-identity.md
> +Represents an [identity](externalconnectors-externalgroup.md) used to set permissions on external content added to Microsoft Graph.
1. [identity](externalconnectors-externalgroup.md) should be pointing to the current file identity resource [identity](../resources/externalconnectors-identity.md).
2. "Represents an external group member who set permissions on external content added to Microsoft Graph." sounds more like the member is setting permission. The existing description text seems more accurate to me as the identity is used as part of security trimming for external content added to the graph.

2022-01-19 20:53 UTC, sacampbe-msft commented on api-reference/beta/resources/externalconnectors-externalgroup.md
> +|[Create member](../api/externalconnectors-externalgroup-post-members.md)|[microsoft.graph.externalConnectors.identityType](../resources/externalconnectors-identity.md)|Create a new **externalGroupMe
I agree with the suggested revision.

2022-01-19 20:55 UTC, sacampbe-msft requested changes
@mecampos I have replied to the comments where I was mentioned. Apologies for the delay

2022-01-25 16:37 UTC, mecampos commented on api-reference/beta/resources/externalconnectors-identity.md
> +Represents an [identity](externalconnectors-externalgroup.md) used to set permissions on external content added to Microsoft Graph.
Updated link to externalconnectors-identity.md per point 1.

2022-01-25 16:38 UTC, mecampos commented on api-reference/beta/api/externalconnectors-externalgroup-get.md
> +# [C#](#tab/csharp)
updated as recommended

2022-01-25 16:39 UTC, mecampos commented on api-reference/beta/api/externalconnectors-externalgroup-get.md
> +GET https://graph.microsoft.com/v1.0/external/connections/contosohr/groups/31bea3d537902000
Updated as recommended.

2022-01-25 16:41 UTC, opbld31 commented
Docs Build status updates of commit _[3aab278](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3aab278db74b07f5ce493ddb082bd97cb5d25b18)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8053d1d7)

<a id="8053d1d7"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201251640598696-14168%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T16%3A41%3A44Z&sr=b&sp=r&sig=ZDdXN6oTEfldc2OrRk6psTPJoQJuPTHj1yGd8I9J66g%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 16:53 UTC, opbld32 commented
Docs Build status updates of commit _[e16e785](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e16e785d486249ecd5e1d95d806a3ea6ded184ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-39a325aa)
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/educationonerosterapidataprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/educationonerosterapidataprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationonerosterapidataprovider?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-39a325aa"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml)
 - **Line 13892, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/externalconnectors-externalgroupmember.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201251650478226-14168%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T16%3A53%3A28Z&sr=b&sp=r&sig=wcIxcCtHsZmJUVOcrFpgYcD0GZHlG4wIuU94rNPlKvs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 17:14 UTC, mecampos commented
file api-reference/beta/toc.yml
Line 13892, Column 19: [Warning: file-not-found - See documentation] Invalid file link: 'resources/externalconnectors-externalgroupmember.md' 

Note: the file exists in main, but it is not being copied to this branch when updating from main.

2022-01-25 17:21 UTC, opbld34 commented
Docs Build status updates of commit _[68b6d3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68b6d3aa538f72f8c0634f7e455a93d19e046a50)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-62f8223c)
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroup-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroupmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/api/externalconnectors-externalgroupmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroupmember-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/educationonerosterapidataprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/educationonerosterapidataprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationonerosterapidataprovider?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-62f8223c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/toc.yml)
 - **Line 13892, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/externalconnectors-externalgroupmember.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201251719158259-14168%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T17%3A21%3A36Z&sr=b&sp=r&sig=%2B8f4ESbOw4LTrz2nw%2FnLQX4fVZb3NvQMK%2BaA9ueogY4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 22:50 UTC, mecampos commented
@isvargasmsft @Lauragra 
Please continue with the review.

2022-02-16 16:25 UTC, sacampbe-msft approved these changes

2022-02-17 15:57 UTC, mecampos commented
@isvargasmsft   @Lauragra 
We would appreciate it if you could finalize your review, thanks.

2022-02-17 18:32 UTC, Lauragra commented on api-reference/beta/api/externalconnectors-externalgroup-post-members.md
> +description: "Create an identity object."
Global: Please rename the files to change externalgroup to identity where appropriate. Also, we missed updating the title field here, should be "Create identity".

2022-02-17 18:33 UTC, Lauragra commented on api-reference/beta/resources/externalconnectors-identity.md
> +Represents an [identity](externalconnectors-identity.md) used to set permissions on external content added to Microsoft Graph.
Please update the description field to match the summary. Also, please remove the link here since it's self-referencing.

2022-02-17 18:35 UTC, Lauragra commented on api-reference/beta/resources/externalconnectors-externalgroup.md
> +|[Create member](../api/externalconnectors-externalgroup-post-members.md)|[microsoft.graph.externalConnectors.identityType](../resources/externalconnectors-identity.md)|Create a new member of an **ex
This topic actually has the namespace line twice; please remove the second one.

2022-02-17 18:38 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: Get external group
For CRUD operations in the TOC, we can leave out the resource name for readability/scannability. So please change these to Get and Delete.

2022-02-17 18:38 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: External group member
Should we change this TOC entry to Identity, since we've changed the resource name? Otherwise it's not a clear user experience.

2022-02-17 18:39 UTC, Lauragra requested changes
Please address the last few content review comments. Thanks.

2022-04-25 19:16 UTC, sacampbe-msft commented on api-reference/beta/toc.yml
> +        - name: External group member
https://github.com/microsoftgraph/microsoft-graph-docs/blob/02c71ee13ffaf2bbd9c1f4f4a83d419656b74fde/api-reference/v1.0/toc.yml#L6232-L6239

It'd be good to be consistent with the v1.0 layout here and change the "External group member" to "Identity"

2022-04-25 23:54 UTC, sacampbe-msft commented on api-reference/beta/toc.yml
>              href: resources/externalconnectors-externalgroup.md
Hey Melissa, can you also add a page and TOC entry for updating the externalGroup?

There is already a page in v1.0 for this which could be copied.

https://docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-1.0&tabs=http

2022-05-11 03:16 UTC, mecampos commented on api-reference/beta/api/externalconnectors-externalgroup-post-members.md
> +description: "Create an identity object."
Already done

2022-05-11 03:22 UTC, mecampos commented on api-reference/beta/resources/externalconnectors-identity.md
> +Represents an [identity](externalconnectors-identity.md) used to set permissions on external content added to Microsoft Graph.
Updated description field, and self-reference.

2022-05-11 03:24 UTC, mecampos commented on api-reference/beta/resources/externalconnectors-externalgroup.md
> +|[Create member](../api/externalconnectors-externalgroup-post-members.md)|[microsoft.graph.externalConnectors.identityType](../resources/externalconnectors-identity.md)|Create a new member of an **ex
Removed second namespace line.

2022-05-11 03:26 UTC, mecampos commented on api-reference/beta/toc.yml
> +          - name: Get external group
Changed as requested.

2022-05-11 03:29 UTC, mecampos commented on api-reference/beta/toc.yml
> +        - name: External group member
Changed "External group member" to "Identity"

2022-05-11 03:40 UTC, mecampos commented on api-reference/beta/toc.yml
>              href: resources/externalconnectors-externalgroup.md
Copied file to beta/api. Added to TOC.

2022-05-11 03:42 UTC, opbld34 commented
Docs Build status updates of commit _[2c620c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c620c6e0252d41c4c81efab53ab53821ea4cd51)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-86631618)

<a id="86631618"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205110341591266-14168/BuildReport?accessString=6ebbe47cece14b1eba454e9382083d4a59d4a6957f434daa9dbc0de61d1cda88).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 04:25 UTC, opbld34 commented
Docs Build status updates of commit _[e3a245d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3a245de659300586eadae4747f3c73f6c308e60)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ff4cfb46)

<a id="ff4cfb46"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205110424026562-14168/BuildReport?accessString=c539b11c3f2ab52c8be5b46dfad7994fd8acde8ad38da5d6755eab020e92693b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 05:01 UTC, opbld33 commented
Docs Build status updates of commit _[09bf37f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09bf37feec4bf843a81eed8f4b113a4b179d541c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5b754000)

<a id="5b754000"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205110459014660-14168/BuildReport?accessString=a13dce4395b67a7679e0745524c8bfccfbcda03016f11e25b06298b0ec8c13e5).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 05:09 UTC, opbld30 commented
Docs Build status updates of commit _[7714344](https://github.com/microsoftgraph/microsoft-graph-docs/commits/771434409e7729e139a0091adc2cc61f6099a352)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-dc96ddb8)

<a id="dc96ddb8"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205110508493692-14168/BuildReport?accessString=bfe742c1b41cd68aada36ea242ae86149a43f0dba005e346c70096de4244e4dd).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 18:06 UTC, opbld33 commented
Docs Build status updates of commit _[31ee364](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31ee36452b96bddab8ea93c1687248d1d2d437be)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-1dafbdcc)
[api-reference/beta/api/externalconnectors-externalgroup-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalgroup-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-get?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-externalgroup-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-externalgroup-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-externalgroup-update?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-identity-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-identity-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-identity-delete?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/api/externalconnectors-identity-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/externalconnectors-identity-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/externalconnectors-identity-post-members?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalgroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalgroup?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalgroupmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/api-reference/beta/resources/externalconnectors-externalgroupmember.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/externalconnectors-identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-identity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-identity?view=graph-rest-beta&branch=pr-en-us-14168) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-14168) (>= graph-rest-1.0) |
[changelog/Microsoft.Search.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-extgandextiupdates/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-1dafbdcc"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 12341, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accessreviewhistorydefinition-generatedownloaduri.md'.`````
 - **Line 13894, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/externalconnectors-externalgroupmember.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205111752105331-14168/BuildReport?accessString=161fa3852950623885079c0ee903d768429b3ee6b43dc3070bdb41d4afd35588).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 19:40 UTC, mecampos commented
@isvargasmsft @Lauragra, please continue with the review.

2022-06-09 17:50 UTC, mecampos commented
No updates from content reviewers during the past month.
@Lauragra @isvargasmsft: I am now removing my assignment from this PR, please address any question regarding the content of the updates with @sacampbe-msft

2022-08-17 15:01 UTC, closed without merging