Aug Trains - Reassign Submission
microsoftgraph/microsoft-graph-docs pull request #14184
Opened 2021-09-07 23:48 UTC by cristobal-buenrostro

New endpoint to return a submission for revision;

The endpoint page was created
and concept document about assignments/submissions state transitions updated to mention the new "reassigned" state.

2021-09-07 23:49 UTC, opbld33 commented
Docs Build status updates of commit _[79447af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/79447af1f6692befbb6cedf49781c3876a85f089)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) | [Details](#user-content-e8df8c8d88135aa637508188d9f66d36-ea90cea8)
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-ea90cea8)
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="e8df8c8d88135aa637508188d9f66d36-ea90cea8"></a>
### [api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md)
 - **Line 179, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../../concepts/assignments-submissions-states-transition.md'.`````

<a id="317007a3f37485040106a636e6397ea9-ea90cea8"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 114, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109072348144905-14184%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=hCT8Fb3oNR4pivE619bdOo%2Bjm7tF2jkrcpmt43IjElw%3D&st=2021-09-07T23%3A44%3A50Z&se=2021-10-08T23%3A49%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 08:02 UTC, Chenrui-Shu commented on api-reference/beta/api/educationsubmission-reassign.md
> +description: "This action makes the grade and feedback associated with this submission available to the student."
This description is the main idea for return, reassign is designed for teachers to inform students to revisit/redo their work, and in the mean time, it has the ability to return feedback and code.

2021-09-08 08:03 UTC, Chenrui-Shu commented on api-reference/beta/api/educationsubmission-reassign.md
> +This action makes the grade and feedback associated with this submission available to the student. This will change the status of the submission to "reassigned" or "returned" depending if "prefer" pr
Change the description as stated above.

2021-09-08 08:05 UTC, Chenrui-Shu commented on api-reference/beta/api/educationsubmission-reassign.md
> +This action makes the grade and feedback associated with this submission available to the student. This will change the status of the submission to "reassigned" or "returned" depending if "prefer" pr
Please write down the whole header key-value pair: "Prefer": "include-unknown-enum-members" .

2021-09-08 08:12 UTC, Chenrui-Shu commented on concepts/assignments-submissions-states-transition.md
> +| Reassigned | Return | Returned |
We also allowed, returned -- return -- returned and reassigned -- return for revision -- reassigned

2021-09-08 08:12 UTC, Chenrui-Shu commented on api-reference/beta/api/educationsubmission-reassign.md
> +description: "This action makes the grade and feedback associated with this submission available to the student."
This description is the main idea for return, reassign is designed for teachers to inform students to revisit/redo their work, and in the mean time, it has the ability to return feedback and code.

2021-09-08 08:12 UTC, Chenrui-Shu commented on api-reference/beta/api/educationsubmission-reassign.md
> +This action makes the grade and feedback associated with this submission available to the student. This will change the status of the submission to "reassigned" or "returned" depending if "prefer" pr
Change the definition as stated above. (The first sentence)

2021-09-08 08:12 UTC, Chenrui-Shu commented on api-reference/beta/api/educationsubmission-reassign.md
> +This action makes the grade and feedback associated with this submission available to the student. This will change the status of the submission to "reassigned" or "returned" depending if "prefer" pr
Please write down the whole header key-value pair: "Prefer": "include-unknown-enum-members" . It is a header, not property.

2021-09-08 18:17 UTC, cristobal-buenrostro commented on concepts/assignments-submissions-states-transition.md
> +| Reassigned | Return | Returned |
done

2021-09-08 18:28 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +description: "This action makes the grade and feedback associated with this submission available to the student."
done

2021-09-08 18:28 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +This action makes the grade and feedback associated with this submission available to the student. This will change the status of the submission to "reassigned" or "returned" depending if "prefer" pr
done

2021-09-08 18:33 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +This action makes the grade and feedback associated with this submission available to the student. This will change the status of the submission to "reassigned" or "returned" depending if "prefer" pr
done

2021-09-08 18:36 UTC, opbld34 commented
Docs Build status updates of commit _[11087a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11087a28905dfcb2ff7e33ed75f71eef1fa63d3d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) | [Details](#user-content-e8df8c8d88135aa637508188d9f66d36-8b7e283d)
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-8b7e283d)
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="e8df8c8d88135aa637508188d9f66d36-8b7e283d"></a>
### [api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md)
 - **Line 181, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../../concepts/assignments-submissions-states-transition.md'.`````

<a id="317007a3f37485040106a636e6397ea9-8b7e283d"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109081834336465-14184%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=%2B3T7gc4EeV2sbmCn0ktLXkxxz3203OyFYshM%2ByorBUM%3D&st=2021-09-08T18%3A31%3A25Z&se=2021-10-09T18%3A36%3A25Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 18:44 UTC, opbld30 commented
Docs Build status updates of commit _[6c5e537](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c5e537fca4d7403d013798113d706ada715d144)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) | [Details](#user-content-e8df8c8d88135aa637508188d9f66d36-5fd2e39b)
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-5fd2e39b)
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="e8df8c8d88135aa637508188d9f66d36-5fd2e39b"></a>
### [api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md)
 - **Line 183, Column 3**: **[Warning-link-out-of-scope]** `````File '../concepts/assignments-submissions-states-transition.md' referenced by link '../../../concepts/assignments-submissions-states-transition.md' will not be built because it is not included in build scope.`````

<a id="317007a3f37485040106a636e6397ea9-5fd2e39b"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109081843125702-14184%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=rzVy44XGWtiS6cMQzGPhKGIegFyAifHlWQH%2FV1iulhE%3D&st=2021-09-08T18%3A39%3A58Z&se=2021-10-09T18%3A44%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 20:43 UTC, opbld30 commented
Docs Build status updates of commit _[8efeeff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8efeeff507edc45822ef70aadf9a0a0a45cf1c3f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-ecd0aa40)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-ecd0aa40"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109082041583973-14184%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=D9tpddUtaOT5Fr6l0kxPxTfL9fRQuSwTDryfwFRbdBQ%3D&st=2021-09-08T20%3A38%3A35Z&se=2021-10-09T20%3A43%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 21:13 UTC, opbld33 commented
Docs Build status updates of commit _[fc25ed3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc25ed3d4083201fe2253e179b718c2cf6e29373)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-56662630)

<a id="56662630"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109082113113509-14184%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=CQ9Jo7ikVkvw9TCxSQxRb6hcA1IMjo1XmS70ro7GHcQ%3D&st=2021-09-08T21%3A08%3A29Z&se=2021-10-09T21%3A13%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 21:21 UTC, opbld33 commented
Docs Build status updates of commit _[94c9f68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94c9f68dcc41ed6190754674a7c72a8d7581f954)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-85236f18)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-85236f18"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109082119453390-14184%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Er7Sud5vujVyOqsE2BZlpte3FxBUP%2BsAg8Qsw42Zr4Y%3D&st=2021-09-08T21%3A16%3A21Z&se=2021-10-09T21%3A21%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 21:32 UTC, opbld30 commented
Docs Build status updates of commit _[0ad814d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ad814d8ec8df98e34003323ae9fd35db4485c16)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-7aa34714)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-7aa34714"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109082131200358-14184%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=RB210%2BWqYrkVpdhZ6uUljfTHOBzWY1Q%2Bw1Jos6DbtXc%3D&st=2021-09-08T21%3A27%3A58Z&se=2021-10-09T21%3A32%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-09 19:35 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +The following is an example of the response when `prefer` is NOT provided in the request header.
done

2021-09-09 19:35 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +The following is an example of the response when `prefer` is provided in the request header.
done

2021-09-09 19:39 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +This will change the status of the submission to "reassigned" or "returned" depending if `Prefer: include-unknown-enum-members` is provided or not in the request header, and indicates that it was ret
done

2021-09-09 19:39 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +  "description": "educationSubmission: return",
done

2021-09-09 19:43 UTC, opbld34 commented
Docs Build status updates of commit _[6032079](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6032079dc41f7914eb384e3d0fc4db8e029efa4a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-b2c77157)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-b2c77157"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109091941590075-14184%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=NymNgPYW2VHcUyK8NqRZCjBPLxFlDDfVlWUBTZPRmmA%3D&st=2021-09-09T19%3A38%3A43Z&se=2021-10-10T19%3A43%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-09 20:44 UTC, Chenrui-Shu approved these changes

2021-09-14 16:04 UTC, opbld34 commented
Docs Build status updates of commit _[8b07b94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b07b94c3f8322b22e626b9d42e39de478bffc24)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-b16e2d34)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-b16e2d34"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109141602142906-14184%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=nFQK9U1IpU9f6tXv0gGvePJP4DXv2C4X6M7nPdVOYrs%3D&st=2021-09-14T15%3A59%3A17Z&se=2021-10-15T16%3A04%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 13:48 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-reassign.md
> +description: "Reassign is designed for teachers to inform students to revisit/redo their work, and in the mean time it has the ability to return feedback and code."
Please remember key aspects of the description:
1. It is used by search engines to show results. How would you Bing this method if you needed it? 
2. It should start with imperative. For example: Return an assignment to the student for review. 
3. Description in line 3 should match the very first sentence of the document (description in line 16).

2021-09-15 13:52 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-reassign.md
> +If the header `Prefer: include-unknown-enum-members` is provided, reassigned submission remains in `reassigned` status. You can refer response examples for further details.
This information does not clarify what the method does, it seems to be more about the enumeration type. Please check my comment above and keep in mind this should be a summary/introductory sentence. Any additional information should go in a subsequent paragraph. 

An example of a description is:
Return an assignment to the student with feedback for review. 

Only teachers can perform this action. (...).

2021-09-15 13:54 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-reassign.md
> +This action can only be done by the teacher.
Please [avoid using passive voice](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=25523) when necessary. In this case, please rephrase to:
* Only teachers can perform this action.

2021-09-15 13:56 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-reassign.md
> +## [HTTP](#tab/http)
Please remove line 52. These snippets are automatically generated. We should not include them manually.

2021-09-15 13:58 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-reassign.md
> +The following is an example of the response when `Prefer: include-unknown-enum-members` is NOT provided in the request header and the submission has never been returned before.
Please divide these into 2 different examples and include the header section in the request to showcase the difference. Please keep in mind developers that are just starting with the graph and need all the help from the documentation to understand how to use the API.

2021-09-15 14:01 UTC, isvargasmsft commented on changelog/Microsoft.EducationAssignment.json
> -          "Target": "educationAddToCalendarOptions"
Are you editing previous changelog entries? Please do not edit previous changelog entries, just add the new entries in a new changelist. 

Even if the new changelog entries affects a previous one, the changelog is smart enough to detect the change. If we remove previous changelog entries we are challenging the whole purpose of the changelog.

2021-09-15 14:02 UTC, isvargasmsft commented on changelog/Microsoft.EducationAssignment.json
> +          "Target": "reassign"
The target of this method is the **submission** resource type. There is no reassign resource type.

2021-09-15 14:07 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-reassign.md
> +---
Side comments:
1. Please remember to include the new method in the TOC.
2. Please remember to include the new method in the **educationSubmission** resource type topic.
3. Please include the new properties in the resource type topic as well. 
4. I understand we are adding a new enum type, please follow the guidelines to document a new enum: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations

Kind regards!

2021-09-15 14:09 UTC, isvargasmsft requested changes
Hello Cristobal, 

Thank you very much for your work in this PR. 

Please review my comments. I believe there are docs missing in this PR and there is work to do in the topic description. 

In addition, please clarify the edits in the changelog entries. We **should not** re-write previous entries.

As always, please feel free to ping me on the side if you have any questions. Here to help!

Best regards,

Isaac

2021-09-15 17:00 UTC, cristobal-buenrostro commented on changelog/Microsoft.EducationAssignment.json
> -          "Target": "educationAddToCalendarOptions"
Noup, the entries are there, but I got before a "conflicts" message and solved them, but not sure why github show them in that way =s

![image](https://user-images.githubusercontent.com/87383938/133477156-d38512e7-89b1-4c70-8600-ff35940d7514.png)

2021-09-15 19:45 UTC, opbld34 commented
Docs Build status updates of commit _[e508fce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e508fce66ad7e5675162e1923e491d4847ca1d5e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2584c490)

<a id="2584c490"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109151944514450-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T19%3A45%3A11Z&sr=b&sp=r&sig=Ow0N53XSOAxhDfTSZlUMtV9FOGSLGyoCeM4QGAOArP8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 19:49 UTC, cristobal-buenrostro commented on changelog/Microsoft.EducationAssignment.json
> +          "Target": "reassign"
done

2021-09-15 19:49 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +The following is an example of the response when `Prefer: include-unknown-enum-members` is NOT provided in the request header and the submission has never been returned before.
done

2021-09-15 19:49 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +## [HTTP](#tab/http)
done

2021-09-15 19:49 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +This action can only be done by the teacher.
done

2021-09-15 19:50 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +If the header `Prefer: include-unknown-enum-members` is provided, reassigned submission remains in `reassigned` status. You can refer response examples for further details.
done

2021-09-15 19:50 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +description: "Reassign is designed for teachers to inform students to revisit/redo their work, and in the mean time it has the ability to return feedback and code."
done

2021-09-15 20:03 UTC, opbld32 commented
Docs Build status updates of commit _[c2184a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2184a24735ee0427ccb230d0b1d041abc6b2f6a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6aa5f7c5)

<a id="6aa5f7c5"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109152003070914-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T20%3A03%3A28Z&sr=b&sp=r&sig=S94kIIrPT5F%2BBDq98QlD1Kk1m8KvuUZ2uE1wznE5jkM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 20:13 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +---
About..

#3, there are no new properties
#4, no new enum type, probably is confused because the name of the header value

2021-09-15 21:34 UTC, opbld31 commented
Docs Build status updates of commit _[2ee23c3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ee23c3ce00d8262ceaf36833026df82c0047208)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6f0c6f81)

<a id="6f0c6f81"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109152133490287-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T21%3A34%3A10Z&sr=b&sp=r&sig=yfNS4caDINhUB8Jgm6FRFLALXOjm6E8fXnW4c52UIUc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 14:31 UTC, opbld31 commented
Docs Build status updates of commit _[ae896bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae896bdf61debd652b41cac5de11b015b0702e18)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5630c207)

<a id="5630c207"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109161430541948-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T14%3A31%3A17Z&sr=b&sp=r&sig=AfibhNXM3qDjN5eazZ7NWGkGN%2B8fkg9TXO4tvBOF5QA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 15:23 UTC, opbld34 commented
Docs Build status updates of commit _[97c1454](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97c145496b30020a55f15df5008751423b0c4a75)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-5ea6297a)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-5ea6297a"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109161521260382-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T15%3A23%3A06Z&sr=b&sp=r&sig=havA85oaVA7rQoqGdaFkZQ1Pw9dshFqKyLZkigWwF%2FI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-21 23:27 UTC, opbld31 commented
Docs Build status updates of commit _[f914ea7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f914ea7a2958223da9a23859cbcc1c47357bf732)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-67c94b1a)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-67c94b1a"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109212325538741-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-22T23%3A27%3A57Z&sr=b&sp=r&sig=ldF8KCpgB4ec0KVhANBid%2FXC%2BiFTHVm5ikwhCUMo75Y%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-21 23:43 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-reassign.md
> +---
@cristobal-buenrostro, 

#3 In the changelog we are adding an entry for the **reassignedBy** property to the **educationSubmission** resource. 
#4 We are adding the `reassigned` member to the **educationSubmissionStatus** enumeration.

2021-09-22 00:16 UTC, opbld31 commented
Docs Build status updates of commit _[917934e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/917934e6cfe6e31f5b12e464b79996a1d6c196fc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-576735f6)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-576735f6"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109220014040318-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-23T00%3A16%3A09Z&sr=b&sp=r&sig=L0OHMwGM1EnJBVvfUJUeJ1at8Gc6PEWZ9bgvRugpepM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-22 00:16 UTC, isvargasmsft requested changes
Please review my comments here: https://github.com/microsoftgraph/microsoft-graph-docs/pull/14184/files#r713491684

2021-09-22 12:53 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +---
#3 , done
#4, not sure where should I add that new value. But please see the csdl file updated 
https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/5037555?_a=files

2021-09-22 12:55 UTC, opbld31 commented
Docs Build status updates of commit _[72a7c73](https://github.com/microsoftgraph/microsoft-graph-docs/commits/72a7c7397780882cb1e48301f98d42ea724c4d66)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-cb0655de)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-cb0655de"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109221253534078-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-23T12%3A55%3A38Z&sr=b&sp=r&sig=cYKpl5s3FScuW443fxXjJIf%2B7h1Bjz%2BH7ra95IENbmU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-22 16:31 UTC, sharad-sharma-msft commented on api-reference/beta/api/educationsubmission-reassign.md
> +Reassigned is a new submission status added, so it will be treated as an unknown enum member. If the header Prefer: include-unknown-enum-members is not provided, a reassigned submission will be mappe
you want to end the sentence with "respectively"

2021-09-22 16:33 UTC, sharad-sharma-msft commented on api-reference/beta/api/educationsubmission-reassign.md
> +The following example shows how to call this API.
@isvargasmsft  - shall we say API action instead of just API ?
reference: The following example shows how to call this API.

2021-09-22 16:35 UTC, sharad-sharma-msft commented on api-reference/beta/api/educationsubmission-reassign.md
> +    "@odata.context": "https://graph.microsoft.com/beta/$metadata#educationSubmission",
will response not have returnedDateTime in this case?

2021-09-22 19:20 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +Reassigned is a new submission status added, so it will be treated as an unknown enum member. If the header Prefer: include-unknown-enum-members is not provided, a reassigned submission will be mappe
done

2021-09-22 19:21 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +The following example shows how to call this API.
done

2021-09-22 19:21 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +    "@odata.context": "https://graph.microsoft.com/beta/$metadata#educationSubmission",
it is null in the response, but is populated when call GET submission

2021-09-22 19:22 UTC, opbld30 commented
Docs Build status updates of commit _[9bef155](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9bef155540b2448dbc8c5291a7b4df1061d54f94)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-bb900417)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-bb900417"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109221920472225-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-23T19%3A22%3A43Z&sr=b&sp=r&sig=%2Fmv%2Fb8P%2BOhUP3Isi5REkuXMHbzLrblFmAX1OeC8WrTY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-22 19:24 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-reassign.md
> +---
done

2021-09-22 20:07 UTC, sharad-sharma-msft approved these changes

2021-09-22 20:32 UTC, opbld30 commented
Docs Build status updates of commit _[2fd23fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2fd23fd62152bdd45b99e530b28fb3a02ba9e5de)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-48a73c2f)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-48a73c2f"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109222031083188-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-23T20%3A32%3A51Z&sr=b&sp=r&sig=u3HpGQMOl1OF3yfvZj0D8i3ZUOZ7o5iDFUSRL97wExI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-22 22:10 UTC, opbld34 commented
Docs Build status updates of commit _[d0e5d7b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0e5d7bade1381b2816188af6bc1bac35f2cacdd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-fd3592f0)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-fd3592f0"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109222208314156-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-23T22%3A10%3A30Z&sr=b&sp=r&sig=y3YxJcUALdD7dIdylEDX6j3l96sBS%2BN9Q1M%2FQ7bO5Mg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-22 22:20 UTC, isvargasmsft commented on api-reference/beta/resources/educationsubmission.md
> +|status|string| Read-Only. Possible values are: `working`, `submitted`, `released`, `returned` and `reassigned`.|
This is an evolvable enum, hence this guidelines apply: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/174164/Evolvable-enumerations?anchor=step-3%3A-add-clarification-if-one-or-more-members-follow-unknownfuturevalue

Please add the proper clarification regarding the new values after unknownFutureValue.

2021-09-22 22:21 UTC, opbld30 commented
Docs Build status updates of commit _[11d727e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11d727e9cd7932ea73b9d865a56773748585ab73)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-c1abe117)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-c1abe117"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 31, Column 25**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-get.md' referenced by link '../api-reference/beta/api/educationassignment-get.md' will not be built because it is not included in build scope.`````
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109222219152188-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-23T22%3A21%3A23Z&sr=b&sp=r&sig=c3fzsutjEBekecHTf%2FfXUtUd18bVXGuKWFrO5nP8B4g%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-22 22:27 UTC, opbld32 commented
Docs Build status updates of commit _[0e55e94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e55e94867c24184cec4d2fbf77c218d5e8b76b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-2389183f)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-2389183f"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109222225225269-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-23T22%3A27%3A04Z&sr=b&sp=r&sig=oKdXNwPV0CxnRo2Bfw17I7OlkQJcaZyHQEZjH4%2BhC%2BM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-22 22:34 UTC, opbld34 commented
Docs Build status updates of commit _[ec5ca91](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec5ca91690af1b5f7a3f47aeb2f1c4867bac76e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-3302094c)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-3302094c"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109222232515471-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-23T22%3A34%3A32Z&sr=b&sp=r&sig=jPhxMz%2FtZp0oAT8R9qhWqUQb66xcP8mlqGPr3y8zzF0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-22 22:49 UTC, opbld33 commented
Docs Build status updates of commit _[b0797f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0797f669322c99c3fb0c50aca7dda86217c4b59)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-ff0d3263)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-ff0d3263"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109222247494534-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-23T22%3A49%3A31Z&sr=b&sp=r&sig=Z4YC6jjaz9XlDTNhVwmPO7WJe4qke99NXqzXJoDjbh8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-22 22:52 UTC, cristobal-buenrostro commented on api-reference/beta/resources/educationsubmission.md
> +|status|string| Read-Only. Possible values are: `working`, `submitted`, `released`, `returned` and `reassigned`.|
done

2021-09-23 12:42 UTC, opbld32 commented
Docs Build status updates of commit _[cb3cc7d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb3cc7d27994d7e8d2253e70c40fc97c126fd0b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-6c2397fc)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-6c2397fc"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109231240552971-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-24T12%3A42%3A37Z&sr=b&sp=r&sig=X17iAwrFavyhpoLOPEiEDvWXrBhN%2BJMF2BcNO%2FJaw9E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-23 13:12 UTC, isvargasmsft commented on changelog/Microsoft.EducationAssignment.json
> +          "Target": "educationSubmission"
Why are we adding this in 2 different changelists?

2021-09-23 13:13 UTC, opbld32 commented
Docs Build status updates of commit _[06af2b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06af2b6b881f70b3850f7bf3388528335c1adc67)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-e9d00b68)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-e9d00b68"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109231311245480-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-24T13%3A13%3A02Z&sr=b&sp=r&sig=NmFLgh4%2FfhXrgijuT34%2Bjm3oq2Lt85aqAo8R%2FAOoxbc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-23 13:26 UTC, opbld32 commented
Docs Build status updates of commit _[71660cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/71660cb64b8a72ddf061c2dea078cf5ba0f1f68e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-27759048)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-27759048"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109231324440315-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-24T13%3A26%3A25Z&sr=b&sp=r&sig=ASlK7qHaPZAaYoP78KXqVKMGexSFAcbDkufsWqdNR%2BI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-23 13:26 UTC, cristobal-buenrostro commented on changelog/Microsoft.EducationAssignment.json
> +          "Target": "educationSubmission"
done, extra changelist was removed

2021-09-23 14:00 UTC, isvargasmsft approved these changes
Thank you very much for your work in this PR. 

Regards!

2021-09-24 03:48 UTC, opbld32 commented
Docs Build status updates of commit _[8fb91a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8fb91a940257dc5c16dc6d30ffbbc93e1f2a8b9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-89b1f4f6)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-89b1f4f6"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109240347244517-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T03%3A48%3A56Z&sr=b&sp=r&sig=axqGxDZLCKb6AH%2BQq6TwdaVOuadL2oOpuRuJ6Iva1tQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 03:50 UTC, opbld30 commented
Docs Build status updates of commit _[200e536](https://github.com/microsoftgraph/microsoft-graph-docs/commits/200e536abe40b4d240ea1d4c7f6d26e9d86bf7ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-32c7ba4a)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-32c7ba4a"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109240348553297-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T03%3A50%3A45Z&sr=b&sp=r&sig=Nxw3JiSqz6V4KpcQFqjfYHSi5SHTWz5r8duUIdbw8j8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 03:58 UTC, opbld34 commented
Docs Build status updates of commit _[6fe7a45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6fe7a45e53ca2e0e576651d671cbef7330a8ca7f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-0a8ccae9)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-0a8ccae9"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109240356335978-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T03%3A58%3A11Z&sr=b&sp=r&sig=643ipkh9WfT5IH8YPLwuXZcVPtVhC4Pq5%2B8Fonry1WY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 04:10 UTC, opbld30 commented
Docs Build status updates of commit _[6f8e8b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f8e8b181df88c63eef8282e86e9f446ef0b14e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) | [Details](#user-content-317007a3f37485040106a636e6397ea9-566554b8)
[api-reference/beta/api/educationsubmission-reassign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/api/educationsubmission-reassign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-reassign?view=graph-rest-beta&branch=pr-en-us-14184) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/images/states-transitions/diagram-submissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/images/states-transitions/diagram-submissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/assignments-submissions-states-transition?branch=pr-en-us-14184) |

<a id="317007a3f37485040106a636e6397ea9-566554b8"></a>
### [concepts/assignments-submissions-states-transition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-cristobalb/reassign-submission/concepts/assignments-submissions-states-transition.md)
 - **Line 116, Column 45**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/throttling' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109240409007477-14184%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T04%3A10%3A45Z&sr=b&sp=r&sig=sc2UR2%2FNWejC%2FAGRdtA4cIpLvnxx7PBi45BI1mSA9sE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 04:23 UTC, Lauragra approved these changes

2021-09-24 04:23 UTC, merged