Add incidents permissions
microsoftgraph/microsoft-graph-docs pull request #14236
Opened 2021-09-13 07:41 UTC by BenAlfasi

2021-09-13 07:43 UTC, opbld34 commented
Docs Build status updates of commit _[4e416ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e416acef1306d4019904e5f98ea1030b91e5de8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AddIncidentPermissions/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14236) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-8864d37c)

<a id="eea99bea355d0a4253064eefdbbe7005-8864d37c"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AddIncidentPermissions/concepts/permissions-reference.md)
 - **Line 2476, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109130741445202-14236%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=OfvGL4aqE1nZdNs8lxvjmGe5nbbDfsepT09EZyod%2BLY%3D&st=2021-09-13T07%3A38%3A19Z&se=2021-10-14T07%3A43%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 08:22 UTC, angelgolfer-ms commented on concepts/permissions-reference.md
> +
Lines 2478-2479:
Please delete the 5th column. The table header has 4 columns, consistent with the other tables for application permissions in the same topic.

2021-10-01 08:27 UTC, angelgolfer-ms commented on concepts/permissions-reference.md
> +---
For each of the delegated usage (lines 2489 and 2490) and application usage (lines 2494 and 2495), can you please clarify the extent of incidents that an authorized app can actually read?

For instance, is the application usage about "Read all incidents in an organization"? And what about the delegated usage?

2021-10-01 08:32 UTC, angelgolfer-ms requested changes
Hi @BenAlfasi , per your question in the related PR #13936 , yes if you can merge this PR into that one, that would be slightly better. If not, then this PR 14236 should be merged shortly before PR 13936, so that we don't get into a state that the new permissions in PR 13936 are lacking definition.

Please take a look at the couple of comments in this PR. Thanks!

2021-10-01 08:42 UTC, opbld34 commented
Docs Build status updates of commit _[248f76a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/248f76ad2c683b4dd78535a0620aa3cc09838ca4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AddIncidentPermissions/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14236) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-46897db4)

<a id="eea99bea355d0a4253064eefdbbe7005-46897db4"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AddIncidentPermissions/concepts/permissions-reference.md)
 - **Line 2478, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110010838349820-14236%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T08%3A42%3A32Z&sr=b&sp=r&sig=BiW2w9sON6ObSZp1X%2FKcUB3fTg4Ba1NOTEqUozNDoxI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-03 07:12 UTC, opbld30 commented
Docs Build status updates of commit _[5f7b3d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f7b3d94ef51d75d011726516a26d7fe43689814)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AddIncidentPermissions/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14236) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110030710217587-14236%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-03T07%3A12%3A06Z&sr=b&sp=r&sig=gyVQRXDoNlbHj%2BlnCyF86OCrO0wWH9pC%2F7V26zYbFkg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-03 07:23 UTC, closed without merging

2021-10-03 07:24 UTC, BenAlfasi commented
Merged to #13936

2021-10-05 00:59 UTC, angelgolfer-ms commented on concepts/permissions-reference.md
> +---
@BenAlfasi , not sure of your answer to my comment/question above.
Would it be appropriate to qualify where you say "incidents..." in each of the lines 2472, 2473, 2480, 2481, 2491, 2492, 2496, 2497,  you say "incidents in an organization..."?

That is, for line 2491, you say:
"Read all incidents _in an organization_ that the user is allowed to read"

Where you currently say "Read all incidents..." or "Read or write all incidents...", for delegated and application permissions, we further quality the description to say:
"Read all incidents in an organization..." or "Read or write all incidents in an organization...",

2021-10-05 07:31 UTC, BenAlfasi commented on concepts/permissions-reference.md
> +---
@angelgolfer-ms Fixed in the Incidents API PR. #13936