test revision
microsoftgraph/microsoft-graph-docs pull request #14269
Opened 2021-09-14 23:07 UTC by markwahl-msft

for testing purposes

2021-09-14 23:09 UTC, opbld31 commented
Docs Build status updates of commit _[c5b584d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c5b584da4bd0feb8ea629244f121e5402202904d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-c995f2b7d38a08a5de506a7160b21a2c-f99ce2ee)
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-80af32289f7572f1f59fd3a51442a52e-f99ce2ee)
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-e67fa86254846feaa9059a36ee662b5a-f99ce2ee)
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f6c74782195959cc97370cc22ceb40da-f99ce2ee)
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f2eba5771e491a2ac7050a9f9ff11588-f99ce2ee)
[api-reference/v1.0/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-36574f7147f789e34c37757788347aa3-f99ce2ee)
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-54fa14683e7d0e52e041bfd46c99fedc-f99ce2ee)
[api-reference/v1.0/api/accesspackageassignmentrequest-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-46c98400da86bb83dbb307e4ac95bb2e-f99ce2ee)
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-96dbe8d6c8bd55e6be86804bbfca755e-f99ce2ee)
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-9c17e9cb7ba2c27030123a474dcd0da5-f99ce2ee)
[api-reference/v1.0/api/accesspackageassignmentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-d961d21c1fe2047b78f268f05a2f7acc-f99ce2ee)
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/accesspackage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1056aa76c6f13c3a9ecefe946f8bd776-f99ce2ee)
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/accesspackageassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-779e59ce1b4d767f61a8d9b85ee29eed-f99ce2ee)
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f4d871dcc26ef03da09086aa8cf72fc7-f99ce2ee)
[api-reference/v1.0/resources/accesspackagecatalog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-c4e0a98c9091ba71db020a1ee2297f07-f99ce2ee)
[api-reference/v1.0/resources/accesspackagesubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/accesspackagesubject.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagesubject?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-b5d7791baea716e5f5c929104a4ffc6a-f99ce2ee)
[api-reference/v1.0/resources/azureactivedirectorytenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/azureactivedirectorytenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureactivedirectorytenant?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-327c24f07f1630de98d2678484a9b89f-f99ce2ee)
[api-reference/v1.0/resources/connectedorganization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/connectedorganization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources [...]

2021-09-15 00:21 UTC, opbld30 commented
Docs Build status updates of commit _[f2ef7b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2ef7b80b5365f48c28d9747dfd35f6ac070065a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-80af32289f7572f1f59fd3a51442a52e-afb4175c)
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-e67fa86254846feaa9059a36ee662b5a-afb4175c)
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f2eba5771e491a2ac7050a9f9ff11588-afb4175c)
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-96dbe8d6c8bd55e6be86804bbfca755e-afb4175c)
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/accesspackage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1056aa76c6f13c3a9ecefe946f8bd776-afb4175c)
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/accesspackageassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-779e59ce1b4d767f61a8d9b85ee29eed-afb4175c)
[api-reference/v1.0/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/accesspackageassignmentpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-6faf67f04c319470adccff7980bae394-afb4175c)
[api-reference/v1.0/resources/azureactivedirectorytenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/azureactivedirectorytenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureactivedirectorytenant?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-327c24f07f1630de98d2678484a9b89f-afb4175c)
[api-reference/v1.0/resources/domainidentitysource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/domainidentitysource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domainidentitysource?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-513053fa8db942f9f457af1360fe9431-afb4175c)
[api-reference/v1.0/resources/expirationpattern.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/expirationpattern.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/expirationpattern?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-992ddf122078b77eb250666e48a12ea4-afb4175c)
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-afb4175c)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-afb4175c)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-afb4175c)
[api-reference/v1.0/api/accesspackage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest [...]

2021-09-15 00:56 UTC, opbld33 commented
Docs Build status updates of commit _[9fcb9af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9fcb9af6c5dbeb82d2d17295a0dab5c66b65dc31)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-80af32289f7572f1f59fd3a51442a52e-2a91f9b1)
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-e67fa86254846feaa9059a36ee662b5a-2a91f9b1)
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f2eba5771e491a2ac7050a9f9ff11588-2a91f9b1)
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-96dbe8d6c8bd55e6be86804bbfca755e-2a91f9b1)
[api-reference/v1.0/api/connectedorganization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-45ef9e7323413a2ce36847ca302fc1a4-2a91f9b1)
[api-reference/v1.0/resources/expirationpattern.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/expirationpattern.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/expirationpattern?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-992ddf122078b77eb250666e48a12ea4-2a91f9b1)
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-2a91f9b1)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-2a91f9b1)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-2a91f9b1)
[api-reference/v1.0/api/accesspackage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0 [...]

2021-09-15 15:27 UTC, opbld30 commented
Docs Build status updates of commit _[7df8ec2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7df8ec2181250ff90622552e47a2a9a749f291d9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-80af32289f7572f1f59fd3a51442a52e-f08ac4a8)
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-e67fa86254846feaa9059a36ee662b5a-f08ac4a8)
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f2eba5771e491a2ac7050a9f9ff11588-f08ac4a8)
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-96dbe8d6c8bd55e6be86804bbfca755e-f08ac4a8)
[api-reference/v1.0/api/connectedorganization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-45ef9e7323413a2ce36847ca302fc1a4-f08ac4a8)
[api-reference/v1.0/resources/expirationpattern.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/expirationpattern.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/expirationpattern?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-992ddf122078b77eb250666e48a12ea4-f08ac4a8)
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-f08ac4a8)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-f08ac4a8)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-f08ac4a8)
[api-reference/v1.0/api/accesspackage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0 [...]

2021-09-15 17:45 UTC, opbld32 commented
Docs Build status updates of commit _[5758824](https://github.com/microsoftgraph/microsoft-graph-docs/commits/575882448bbcc8c3407994e5d5c36e698b646174)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-e67fa86254846feaa9059a36ee662b5a-1a002f65)
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f2eba5771e491a2ac7050a9f9ff11588-1a002f65)
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-96dbe8d6c8bd55e6be86804bbfca755e-1a002f65)
[api-reference/v1.0/resources/expirationpattern.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/expirationpattern.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/expirationpattern?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-992ddf122078b77eb250666e48a12ea4-1a002f65)
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-1a002f65)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-1a002f65)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-1a002f65)
[api-reference/v1.0/api/accesspackage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-create.md) | :white_check_mark:Succeeded | [View](https://r [...]

2021-09-15 21:36 UTC, opbld30 commented
Docs Build status updates of commit _[e5bfcb9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e5bfcb9fb88d10d8f745a3e4af1e5ecf100d48de)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-aaa3cc39)
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :warning:Warning | | [Details](#user-content-e67fa86254846feaa9059a36ee662b5a-aaa3cc39)
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :warning:Warning | | [Details](#user-content-f2eba5771e491a2ac7050a9f9ff11588-aaa3cc39)
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :warning:Warning | | [Details](#user-content-96dbe8d6c8bd55e6be86804bbfca755e-aaa3cc39)
[api-reference/v1.0/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/entitlementmanagement-root.md) | :warning:Warning | | [Details](#user-content-3f351afe4b69b7f0922dd53d3f03e12b-aaa3cc39)
[api-reference/v1.0/resources/expirationpattern.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/expirationpattern.md) | :warning:Warning | | [Details](#user-content-992ddf122078b77eb250666e48a12ea4-aaa3cc39)
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | | [Details](#user-content-f412796074681f3abc57043d75f9a933-aaa3cc39)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-aaa3cc39)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | | [Details](#user-content-26d8feff228af52dc71e94aff0815856-aaa3cc39)

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-aaa3cc39"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/toc.yml)
 - **Line 5198, Column 11**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="e67fa86254846feaa9059a36ee662b5a-aaa3cc39"></a>
### [api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md)
 - **Line 39, Column 5**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackage-accesspackagefilterbycurrentuseroptions.md'.`````

<a id="f2eba5771e491a2ac7050a9f9ff11588-aaa3cc39"></a>
### [api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md)
 - **Line 39, Column 5**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md'.`````

<a id="96dbe8d6c8bd55e6be86804bbfca755e-aaa3cc39"></a>
### [api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md)
 - **Line 39, Column 5**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md'.`````

<a id="3f351afe4b69b7f0922dd53d3f03e12b-aaa3cc39"></a>
### [api-reference/v1.0/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/entitlementmanagement-root.md)
 - **Line 24, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accesspackageassignmentresourcerole.md'.`````
 - **Line 26, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accesspackageresourcerequest.md'.`````
 - **Line 27, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accesspackageresourceenvironment.md'.`````

<a id="992ddf122078b77eb250666e48a12ea4-aaa3cc39"></a>
### [api-reference/v1.0/resources/expirationpattern.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/expirationpattern.md)
 - **Line 14, Column 377**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'requestschedule.md'.`````

<a id="f412796074681f3abc57043d75f9a933-aaa3cc39"></a>
### [api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Identifies a relationship to another user in the tenant who will be allowed as approver.' is duplicated in 'v1.0/resources/externalsponsors.md(3,14)', 'v1.0/resources/internalsponsors.md(3,14)', 'v1.0/resources/requestormanager.md(3,14)'.`````

<a id="1c66299d5aa3a0153054186f8c802977-aaa3cc39"></a>
### [api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Identifies a relationship to another user in the tenant who will be allowed as approver.' is duplicated in 'v1.0/resources/externalsponsors.md(3,14)', 'v1.0/resources/internalsponsors.md(3,14)', 'v1.0/resources/requestormanager.md(3,14)'.`````

<a id="26d8feff228af52dc71e94aff0815856-aaa3cc39"></a>
### [api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Identifies a r [...]

2021-09-15 22:08 UTC, opbld33 commented
Docs Build status updates of commit _[1e88c58](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e88c589c0db437ad6e5b79ddca1a5bbf3ddfc00)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/expirationpattern.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/expirationpattern.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/expirationpattern?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-992ddf122078b77eb250666e48a12ea4-f4bebe27)
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-f4bebe27)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-f4bebe27)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-f4bebe27)
[api-reference/v1.0/api/accesspackage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspack [...]

2021-09-15 23:55 UTC, opbld33 commented
Docs Build status updates of commit _[1775dea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1775dea37a6976250f0d889fe74acf7e5c31ef62)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/expirationpattern.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/expirationpattern.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/expirationpattern?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-992ddf122078b77eb250666e48a12ea4-316b187c)
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-316b187c)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-316b187c)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-316b187c)
[api-reference/v1.0/api/accesspackage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspack [...]

2021-09-16 21:35 UTC, opbld30 commented
Docs Build status updates of commit _[4ec7576](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ec75762842d0f59882fc5d729185d5a8bc9b935)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/expirationpattern.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/expirationpattern.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/expirationpattern?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-992ddf122078b77eb250666e48a12ea4-3fce3d53)
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-3fce3d53)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-3fce3d53)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-3fce3d53)
[api-reference/v1.0/api/accesspackage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspack [...]

2021-10-21 19:34 UTC, opbld34 commented
Docs Build status updates of commit _[21d7718](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21d7718f39b41b966fabc503fcf53d6ff61e9e74)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/expirationpattern.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/expirationpattern.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/expirationpattern?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-992ddf122078b77eb250666e48a12ea4-561b28cf)
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-561b28cf)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-561b28cf)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-561b28cf)
[api-reference/v1.0/api/accesspackage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-create?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspack [...]

2021-10-23 00:36 UTC, opbld32 commented
Docs Build status updates of commit _[feef6a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/feef6a9669770a4fff6d6f2cc6cf239ff6942072)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-22826ccc785555d46131bf70b5772eec-38bda6f9)
[api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-9ff35b039d11aa6cfc694b5558001fec-38bda6f9)
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-38bda6f9)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-38bda6f9)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-38bda6f9)
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-get.md) | :white_check_mark:Succeeded | [View](https://review.docs. [...]

2021-11-01 08:33 UTC, FaithOmbongi requested changes
Thank you @markwahl-msft for working on these docs. Most feedback is minor fixes like file name changes, a little clean up etc. The major gaps are the missing real-looking examples ((which you're already aware of) and some missing resources.

**Additional changes I couldn't document inline:**

1. Add the identityGovernance resource and its entitlementManagement relationship.
2. Add the entitlementManagement resource, its id property, and 6 r/ships.

Comment: I realize that these first ☝🏾 2 gaps are probably inherited from the beta docs which are also missing these docs. We can work on cleaning up beta docs after this PR is merged.

3. Add the entitlementManagement r/ship in roleManagement resource

4. **accessPackageCatalog & associated methods**

- accesspackagecatalog-list.md should be either entitlementmanagement-list-catalogs.md or accessPackage-list-catalog.md. If we apply the [file naming guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming). I'd recommend going with **entitlementmanagement-list-catalogs.md** because in my view, entitlementManagement resource is higher in the EM API "hierarchy" compared to accessPackage resource. This will also be consistent with **entitlementmanagement-post-catalogs.md**.

5. **accessPackage & associated methods**
- accesspackage-list.md should be **entitlementmanagement-list-accesspackages.md**.

6. **accessPackageAssignment and associated methods**
- accesspackageassignment-list.md to be **entitlementmanagement-list-assignments.md**

7. **accessPackageSubject and associated methods**

8. **connectedOrganization and associated methods**

- connectedorganization-list.md => entitlementmanagement-list-connectedorganization.md

9. **accessPackageAssignmentRequest and associated methods**
- accesspackageassignmentrequest-list.md => entitlementmanagement-list-assignmentrequests.md

10. **accessPackageAssignmentPolicy complex type**
- Is not in this batch. Please remove file reference.

11. Missing **patternedrecurrence.md** and all the downstream complex types & Enums. You've documented some of the downstream elements in the changelog.
- Note: even though you've documented that recurrence property of entitlementManagementSchedule is not in use for now, if it shows up in the schema, we must  document it.

12. **enums.md**
Please move all new enums to the top of the article.

13. **changelog**

- Please move all your entries to the top of the changelog
- For the line entries of the following objects, at a minimum, append "... and associated methods." to the description. For example, "Added the accessPackage resource and associated methods."
   - Affected objects: accessPackage, accessPackageAssignment, accessPackageAssignmentRequest, accessPackageCatalog, entitlementManagementSettings
   - Other suggestion. You can add a short single sentence to very briefly describe what each resource does. This provides a brief context without going page-by-page.
 
14. Global : 
- All examples to be real values and not return types. In your PR description, you've already highlighted this as a gap. Let's try get the real values in before we publish the docs.
- Some docs are assigned to Sarah. Just confirm if that's still correct.
- Broken links:
  -  All instances of `/graph/permissions-reference.md` in the **Permissions** tables should be `/graph/permissions-reference`

2021-11-01 08:33 UTC, FaithOmbongi commented on api-reference/v1.0/resources/groupmembers.md
> +-->
```suggestion
<!-- {
  "blockType": "resource",
  "@odata.type": "microsoft.graph.groupMembers"
  "baseType": "microsoft.graph.subjectSet"
}
-->
```

2021-11-01 08:33 UTC, FaithOmbongi commented on api-reference/v1.0/resources/requestormanager.md
> +-->
```suggestion
<!-- {
  "blockType": "resource",
  "@odata.type": "microsoft.graph.requestorManager",
  "baseType": "microsoft.graph.subjectSet"
}
-->
```

2021-11-01 08:33 UTC, FaithOmbongi commented on api-reference/v1.0/resources/singleserviceprincipal.md
> +-->
```suggestion
<!-- {
  "blockType": "resource",
  "@odata.type": "microsoft.graph.singleServicePrincipal",
  "baseType": "microsoft.graph.subjectSet"
}
-->
```

2021-11-01 08:33 UTC, FaithOmbongi commented on api-reference/v1.0/resources/singleuser.md
> +-->
```suggestion
<!-- {
  "blockType": "resource",
  "@odata.type": "microsoft.graph.singleUser",
  "baseType": "microsoft.graph.subjectSet"
}
-->
```

2021-11-01 08:33 UTC, FaithOmbongi commented on api-reference/v1.0/resources/connectedorganizationmembers.md
> +-->
```suggestion
<!-- {
  "blockType": "resource",
  "@odata.type": "microsoft.graph.connectedOrganizationMembers",
  "baseType": "microsoft.graph.subjectSet"
}
-->
```

2021-11-01 08:33 UTC, FaithOmbongi commented on api-reference/v1.0/resources/enums.md
> +|afterDuration|
Already documented in the expirationpattern.md article.
```suggestion
```

2021-11-01 08:33 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        },
Methods are catered for by the "...and associated methods." statement in the description of added resources.
```suggestion
```

2021-11-01 08:33 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        },
Same comment as above
```suggestion
```

2021-11-01 08:33 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        }
Global: Just confirm the punctuation is there for all objects.
```suggestion
        {
          "Id": "b3431682-f63b-46c0-9317-deb79df71eed",
          "ApiChange": "Resource",
          "ChangedApiName": "connectedOrganization",
          "ChangeType": "Addition",
          "Description": "Added the [connectedOrganization](https://docs.microsoft.com/graph/api/resources/connectedOrganization?view=graph-rest-1.0) resource.",
          "Target": "connectedOrganization"
        },
        {
          "Id": "b3431682-f63b-46c0-9317-deb79df71eed",
          "ApiChange": "Resource",
          "ChangedApiName": "entitlementManagement",
          "ChangeType": "Addition",
          "Description": "Added [entitlementManagement](https://docs.microsoft.com/graph/api/resources/entitlementmanagement-root?view=graph-rest-1.0) resource.",
          "Target": "entitlementManagement"
        }
```

2021-11-01 08:33 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +   },
```suggestion
      "Id": "b3431682-f63b-46c0-9317-deb79df71eed",
      "Cloud": "Prod",
      "Version": "v1.0",
      "CreatedDateTime": "2021-10-25T00:00:00.2532422Z",
      "WorkloadArea": "Identity and access",
      "SubArea": "Governance"
   },
```

2021-11-03 15:16 UTC, opbld33 commented
Docs Build status updates of commit _[98cbd04](https://github.com/microsoftgraph/microsoft-graph-docs/commits/98cbd04f0d9d8035e87c78a54821c5ac3422ca45)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/entitlementmanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-a3ba65509772494b8c8fd472fb45f1ba-8d5566bb)
[api-reference/v1.0/resources/identitygovernance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/identitygovernance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identitygovernance?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-20aa4f096a964cb679cdc0ed59877454-8d5566bb)
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-8d5566bb)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-8d5566bb)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-8d5566bb)
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-r [...]

2021-11-03 16:03 UTC, opbld34 commented
Docs Build status updates of commit _[dfe4abd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dfe4abdc6c75d459cabd796759172c7b125730eb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/entitlementmanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-a3ba65509772494b8c8fd472fb45f1ba-9dcb3c17)
[api-reference/v1.0/resources/identitygovernance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/identitygovernance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identitygovernance?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-20aa4f096a964cb679cdc0ed59877454-9dcb3c17)
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-9dcb3c17)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-9dcb3c17)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-9dcb3c17)
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-r [...]

2021-11-03 17:48 UTC, opbld30 commented
Docs Build status updates of commit _[7890485](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7890485760de9acc3bed4de61878247dbf57c7f9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-77ab45f4523d660aee5c12cfb1e93ae3-4dcfba11)
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/accesspackage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1056aa76c6f13c3a9ecefe946f8bd776-4dcfba11)
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/accesspackageassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-779e59ce1b4d767f61a8d9b85ee29eed-4dcfba11)
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f4d871dcc26ef03da09086aa8cf72fc7-4dcfba11)
[api-reference/v1.0/resources/accesspackagecatalog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/accesspackagecatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-c4e0a98c9091ba71db020a1ee2297f07-4dcfba11)
[api-reference/v1.0/resources/connectedorganization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/connectedorganization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectedorganization?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-8087ead6cfba5ff8f2f6935fb45ed483-4dcfba11)
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/entitlementmanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-a3ba65509772494b8c8fd472fb45f1ba-4dcfba11)
[api-reference/v1.0/resources/identitygovernance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/identitygovernance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identitygovernance?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-20aa4f096a964cb679cdc0ed59877454-4dcfba11)
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-4dcfba11)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-4dcfba11)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-4dcfba11)
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0 [...]

2021-11-03 18:39 UTC, opbld33 commented
Docs Build status updates of commit _[aedc44c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aedc44c3649312ffe03fc2844d34e240b062cc01)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-assignmentrequests?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-77ab45f4523d660aee5c12cfb1e93ae3-4ad1b9ea)
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-4ad1b9ea)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-4ad1b9ea)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-4ad1b9ea)
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.mic [...]

2021-11-04 23:41 UTC, opbld34 commented
Docs Build status updates of commit _[e0bbddf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e0bbddf65d722e5c4a158f12ed845d28b4bbee71)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/accesspackage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1056aa76c6f13c3a9ecefe946f8bd776-c2f45d47)
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/accesspackageassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-779e59ce1b4d767f61a8d9b85ee29eed-c2f45d47)
[api-reference/v1.0/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/entitlementmanagement-root.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-3f351afe4b69b7f0922dd53d3f03e12b-c2f45d47)
[api-reference/v1.0/resources/entitlementmanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/entitlementmanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-a3ba65509772494b8c8fd472fb45f1ba-c2f45d47)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-c2f45d47)
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-c2f45d47)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-c2f45d47)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-c2f45d47)
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-get.md) | :white_check_mark:Succ [...]

2021-11-05 00:09 UTC, opbld34 commented
Docs Build status updates of commit _[9007f6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9007f6b72393c520224dd746b713751bcea82350)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-edee18fd)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-edee18fd)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-edee18fd)
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph- [...]

2021-11-05 00:41 UTC, opbld34 commented
Docs Build status updates of commit _[e97275f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e97275f0d36713a0809f2f0b839af0329b2c3b78)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-399ba0d5)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-399ba0d5)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-399ba0d5)
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph- [...]

2021-11-05 18:05 UTC, markwahl-msft commented
@FaithOmbongi  FYI  a quick update - I've believe I've addressed your comments on the MD files with the commits into this PR this week, and will be working on the changelog file comments next.  Once I have the updated changelog in this PR then I'll double check the comments and add the review feedback addressed label.  Thanks!

2021-11-06 01:21 UTC, opbld33 commented
Docs Build status updates of commit _[751371b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/751371b86931e6d1af89b521a21cbb666969f6e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-7e72a350)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-7e72a350)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-7e72a350)
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph- [...]

2021-11-10 00:26 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackagecatalog.md
> +|displayName|String|The display name of the access package catalog.|
I'm not seeing those maximum length statements on other resource articles in v1.0, only 3 other resources had used the phrase "maximum length?  Perhaps we could address adding this hint in a later pass  -- since I assume 1000s of other articles would also need to be updated as well.

2021-11-10 00:28 UTC, markwahl-msft commented on api-reference/v1.0/api/accesspackage-filterbycurrentuser.md
> +|on|accessPackageFilterByCurrentUserOptions|The list of current user options that can be used to filter on the access packages list.|
These descriptions were copied from the beta articles which are fairly recent.  I think beta and v1.0 APIs are effectively the same so if there is a doc issue with beta let's fix it there first so we can then propogate the change from beta to 1.0.

2021-11-10 00:28 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackagesubject.md
> +
added

2021-11-10 00:30 UTC, markwahl-msft commented on api-reference/v1.0/api/entitlementmanagement-post-assignmentrequests.md
> +
I've pulled this article out of this PR as will need more work for the examples, will bring in back in a subsequent PR (probably when we add policies).

2021-11-10 00:48 UTC, opbld30 commented
Docs Build status updates of commit _[bcecf68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bcecf6867b46678cf6e92bc28eacf50c230db7ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-c680d1cb)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-c680d1cb)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-c680d1cb)
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph- [...]

2021-11-10 01:18 UTC, opbld32 commented
Docs Build status updates of commit _[7c71f2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c71f2b4cd7f0281721c0451637dacc71041eaff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-1a73c3eb)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-1a73c3eb)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-1a73c3eb)
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph- [...]

2021-11-16 17:20 UTC, opbld32 commented
Docs Build status updates of commit _[cc55502](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc55502e3acc129f4d6dce2b52632f1899135db6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-a47e18a6)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-a47e18a6)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-a47e18a6)
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph- [...]

2021-11-30 13:39 UTC, opbld34 commented
Docs Build status updates of commit _[aae5cda](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aae5cdaf3eee3d9330c1559cf4d96ff69aad844c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-49131ec7)

<a id="49131ec7"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111301338130206-14269%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-31T13%3A39%3A05Z&sr=b&sp=r&sig=Tw%2FbmaDP%2BKEK2nSH73rWNMBGmmaNYCPky34MfVcG2Mo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-30 13:41 UTC, opbld32 commented
Docs Build status updates of commit _[93ce6ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/93ce6ac099f0bc9c35f179764ab66aaeddc933d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/externalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-f412796074681f3abc57043d75f9a933-c55bf5ba)
[api-reference/v1.0/resources/internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/internalsponsors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-1c66299d5aa3a0153054186f8c802977-c55bf5ba)
[api-reference/v1.0/resources/requestormanager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/resources/requestormanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestormanager?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) | [Details](#user-content-26d8feff228af52dc71e94aff0815856-c55bf5ba)
[api-reference/v1.0/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackageassignmentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackagecatalog-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/accesspackagecatalog-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-update?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-externalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-externalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete-internalsponsors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete-internalsponsors?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-delete?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph-rest-1.0) |
[api-reference/v1.0/api/connectedorganization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mwahl-em1-a/api-reference/v1.0/api/connectedorganization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/connectedorganization-get?view=graph-rest-1.0&branch=pr-en-us-14269) (>= graph- [...]

2021-11-30 13:52 UTC, FaithOmbongi approved these changes
Thank you @markwahl-msft for your comprehensive work on this PR.

I pushed a few fixes before approving.

**Of note/for internal follow-up:** The internal and externalSponsors POST and DELETE APIs: Mapping the schema (containsTarget="true") with the [API title guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title?anchor=when-to-use-%22create%22-vs-%22add%22-and-%22delete%22-vs-%22remove%22), the titles would be "Create internalSponsors" and "Delete externalSponsors". However, this logic (looking at the operations) would also be _semantically incorrect_ and the right logic is Add/Remove as you've documented. I recommend that you update the CSDL to remove the **ContainsTarget="true"** statement ... unless this will be a breaking change?

Looking forward to the next batch of the v1.0 docs.

2021-12-01 00:38 UTC, merged