Onboarded new permission for meeting artifacts
microsoftgraph/microsoft-graph-docs pull request #14270
Opened 2021-09-15 00:30 UTC by frankpeng7

2021-09-15 00:32 UTC, opbld33 commented
Docs Build status updates of commit _[f577efe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f577efeabd20dcad41935314615412fb5d9f6723)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeetingartifact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) | [Details](#user-content-940327450b1761c6f65eda551b989137-50f3dcdc)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-50f3dcdc)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |

<a id="940327450b1761c6f65eda551b989137-50f3dcdc"></a>
### [api-reference/beta/api/onlinemeetingartifact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact.md)
 - **Line 18, Column 79**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#example-3-get-recording-of-a-live-event' in 'beta/api/onlinemeetingartifact.md'.`````
 - **Line 90, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2),(csharp, 2),(javascript, 2),(objc, 2),(java, 2).`````

<a id="0817dce4456c16725d5333633847d38f-50f3dcdc"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/toc.yml)
 - **Line 1531, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/onlinemeetingartifact-get.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109150030484206-14270%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=5biRR7tuyG7FEU7guudlGRXeNzsWjBXpZ3%2BZzoc%2FGNo%3D&st=2021-09-15T00%3A27%3A31Z&se=2021-10-16T00%3A32%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 00:39 UTC, opbld33 commented
Docs Build status updates of commit _[9767597](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97675974a365c2f801f8be83f2d91c08f9093495)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeetingartifact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) | [Details](#user-content-940327450b1761c6f65eda551b989137-9d49a9b8)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-9d49a9b8)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |

<a id="940327450b1761c6f65eda551b989137-9d49a9b8"></a>
### [api-reference/beta/api/onlinemeetingartifact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact.md)
 - **Line 102, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2),(csharp, 2),(javascript, 2),(objc, 2),(java, 2).`````

<a id="0817dce4456c16725d5333633847d38f-9d49a9b8"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/toc.yml)
 - **Line 1531, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/onlinemeetingartifact-get.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109150037552879-14270%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=FSq9Hvh%2BSiZINaUPEWrA5%2BjbkQBfaTP4lp1aUw48NPc%3D&st=2021-09-15T00%3A34%3A45Z&se=2021-10-16T00%3A39%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 00:41 UTC, opbld31 commented
Docs Build status updates of commit _[f89bead](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f89bead2621fa8aa5f661479983ea14a8e038ab9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeetingartifact-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) | [Details](#user-content-498c8b5b877e726216d33b955a723cdf-fc9d2924)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |

<a id="498c8b5b877e726216d33b955a723cdf-fc9d2924"></a>
### [api-reference/beta/api/onlinemeetingartifact-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact-get.md)
 - **Line 102, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2),(csharp, 2),(javascript, 2),(objc, 2),(java, 2).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109150039267038-14270%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=DblnWIPRNgLMUkcZJEtJoVK6nA2pcA1WHm%2FdeWwcov4%3D&st=2021-09-15T00%3A36%3A23Z&se=2021-10-16T00%3A41%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 00:52 UTC, opbld33 commented
Docs Build status updates of commit _[1c44966](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c44966c8f317f4b3952cb3b5fdd61656f03dd5b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeetingartifact-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) | [Details](#user-content-498c8b5b877e726216d33b955a723cdf-85b99d0e)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |

<a id="498c8b5b877e726216d33b955a723cdf-85b99d0e"></a>
### [api-reference/beta/api/onlinemeetingartifact-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact-get.md)
 - **Line 112, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2),(csharp, 2),(javascript, 2),(objc, 2),(java, 2).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109150050488964-14270%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=rBAxDJgAAANCIIC6TI0VNkqiPcuvkeROpaY%2BfvmHyyw%3D&st=2021-09-15T00%3A47%3A30Z&se=2021-10-16T00%3A52%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 01:01 UTC, opbld30 commented
Docs Build status updates of commit _[db068d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db068d319a3db19ac703f44b08624be3eb9f823c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/api/onlinemeetingartifact-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109150100201401-14270%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=92Vz0mMxKc%2BmpmwFQhzsXcnGYq4dwtGqDClxY%2FeClfc%3D&st=2021-09-15T00%3A56%3A56Z&se=2021-10-16T01%3A01%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 01:13 UTC, opbld32 commented
Docs Build status updates of commit _[64e5dad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64e5dad6bba3cfc86b48cb535ad26548f1d2403f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/api/onlinemeetingartifact-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109150111396798-14270%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=YhHv2eRsXSHWUtXw92VM43BW4AaimsNLqCkHg8NKGo4%3D&st=2021-09-15T01%3A08%3A22Z&se=2021-10-16T01%3A13%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 04:00 UTC, opbld32 commented
Docs Build status updates of commit _[37c3158](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37c31580610f204c12a0f9464797884aa3d2f64e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/api/onlinemeetingartifact-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109150355442630-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T04%3A00%3A12Z&sr=b&sp=r&sig=hqbhqQ4gAmZEW6ZtP1Zdl8Am%2FJasgoJ3RxYJkbyljgc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 04:11 UTC, opbld33 commented
Docs Build status updates of commit _[bad12d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bad12d91dd23a1e48f11a98e9b525302d840d29e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/api/onlinemeetingartifact-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109150409092492-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T04%3A11%3A35Z&sr=b&sp=r&sig=inPfGWS3e%2FLrbKgK0fo8G65vNurhdykH2t7LCE5bea0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 04:14 UTC, opbld31 commented
Docs Build status updates of commit _[a0f158c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0f158c7a2e7d1b88f366ba7233bd8f1885eac47)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/api/onlinemeetingartifact-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109150411234207-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T04%3A14%3A43Z&sr=b&sp=r&sig=KLxegpshASPu4MBtkojiiJeCgjCOtqliHxhoHp%2Bqjg8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 17:30 UTC, mkhribech approved these changes

2021-09-15 17:51 UTC, Lauragra approved these changes

2021-09-15 21:52 UTC, JarbasHorst requested changes

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +Meeting artifacts are content produced for the duration of an online meeting or live event. Below is a list of meeting artifacts that can be retrieved via Graph API:
We avoid using the words "above" and "below" per Microsoft style because those terms don't translate well for a global audience. Instead of below, use "following". Also, for simplicity, I recommend you to rephrase this sentence. Suggested revision:

- The following meeting artifacts can be retrieved with this API:

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +1. Attendance report of an online meeting, in the form of json response, as shown in [example 1](#example-1-get-attendance-report-of-an-online-meeting).
Please,
- replace json with JSON
- add a before JSON

Suggested revision:
- ...in the form of a JSON response...

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +2. Recordings of a live event, in the form of download link, as shown in [example 2](#example-2-get-attendee-report-of-a-live-event).
Articles help readers and translation software identify the nouns and modifiers in a sentence. Please add a before download. Suggested revision:

- ...in the form of a download link...

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +3. Attendee report of a live event, in the form of download link, as shown in [example 3](#example-3-get-recording-of-a-live-event).
Articles help readers and translation software identify the nouns and modifiers in a sentence. Please add a before download. Suggested revision:

- ...in the form of a download link...

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +| Permission type                        | Permissions                                 |
Please, replace add (from least to most privileged)  after Permissions. Suggested revision:

- Permissions (from least to most privileged)

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +| Delegated (personal Microsoft account) | Not Supported.                              |
Please, replace Supported with supported.

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +In order to use application permission for this API, tenant administrators must create an [application access policy](/graph/cloud-communication-online-meeting-application-access-policy) and grant it
For readability, please replace In order to with To. Suggested revision:

- To use application permission for this API...

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +> To keep API consistency, you may still get meeting artifacts in beta with
For simplicity and clarity, I recommend you to rephrase this sentence. Suggested revision:

- ...you can still use the following permissions until \*\*January 15, 2022\*\* to get meeting artifacts:

Note that I removed the word _beta_ because this API topic is about a beta endpoint.

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +To get the attendance report of an online meeting with delegated(`/me` path) and app(`/users/{userId}` path) permission:
Please, add a space before the open parenthesis. Also, move (`/users/{userId}` path) to be after permission. For simplicity, I recommend you to remove the appearances of path from this sentence. Suggested revision:

- To get the attendance report of an online meeting with delegated (`/me`) and app permission (`/users/{userId}`):

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +To get the attendee report of a live event with delegated(`/me` path) and app(`/users/{userId}` path) permission:
Please, add a space before the open parenthesis. Also, move (`/users/{userId}` path) to be after permission. For simplicity, I recommend you to remove the appearances of path from this sentence. Suggested revision:

- To get the attendee report of a live event with delegated (`/me`) and app permission (`/users/{userId}`):

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +To get the recordings of a live event with delegated(`/me` path) and app(`/users/{userId}` path) permission:
Please, add a space before the open parenthesis. Also, move (`/users/{userId}` path) to be after permission. For simplicity, I recommend you to remove the appearances of path from this sentence. Suggested revision:

- To get the recordings of a live event with delegated (`/me`) and app permission (`/users/{userId}`):

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +The following request uses a user token.
For clarity, I recommend you to replace app token with application permission. Suggested revision:

- The following request uses delegated permission.

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +The following request uses an app token.
For clarity, I recommend you to replace app token with application permission. Suggested revision:

- The following request uses application permission.

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +The following request uses an app token.
For clarity, I recommend you to replace app token with application permission. Suggested revision:

- The following request uses application permission.

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +The following request uses a user token.
For clarity, I recommend you to replace app token with application permission. Suggested revision:

- The following request uses delegated permission.

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +The following request uses a delegated token.
For clarity, I recommend you to replace app token with application permission. Suggested revision:

- The following request uses delegated permission.

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +The following request uses an app token.
For clarity, I recommend you to replace app token with application permission. Suggested revision:

- The following request uses application permission.

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +- If you're getting attendance report of an online meeting, this method returns a [meetingAttendanceReport](../resources/meetingAttendanceReport.md) object in the response body.
A word ending in –ing can be a verb, a noun, or an adjective. Please, avoid using gerunds where possible; in this case, you can change "getting" to "retrieve". Suggested revision:

- If you retrieve an attendance report...

2021-09-15 21:52 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +- If you're getting attendee report or recording of a live event, this method returns a `Location` header that indicates the URI to the attendee report or recording, respectively.
A word ending in –ing can be a verb, a noun, or an adjective. Please, avoid using gerunds where possible; in this case, you can change "getting" to "retrieve". Suggested revision:

- If you retrieve an attendee report...

2021-09-15 22:04 UTC, JarbasHorst commented
@frankpeng7 your PR introduces a new method, onlinemeetingartifact-get. Please, document this addition in the changelog.

2021-09-16 18:45 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +| Permission type                        | Permissions                                 |
There used to be that sentence but I removed it since there's only one permission at this moment. I think it could be confusing to developers and would prefer to add it should there be multiple permissions. Any thoughts?

2021-09-16 18:53 UTC, frankpeng7 commented
@JarbasHorst thanks for the review. I've addressed most of the comments but one (left unresolved for discussion). 

Regarding your last message: this is not a new method. I just broke relevant content out from `onlinemeeting-get.md` for better readability.

2021-09-16 18:54 UTC, opbld32 commented
Docs Build status updates of commit _[6c13124](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c1312462f05d0ff914d5c8a731e4c78442adf4f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeetingartifact-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) | [Details](#user-content-498c8b5b877e726216d33b955a723cdf-bf9d1f26)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |

<a id="498c8b5b877e726216d33b955a723cdf-bf9d1f26"></a>
### [api-reference/beta/api/onlinemeetingartifact-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact-get.md)
 - **Line 7, Column 10**: **[Warning-[ms-date-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Invalid date format for 'ms.date': '09-20-2021'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109161852320979-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T18%3A54%3A25Z&sr=b&sp=r&sig=VcbvQgqwMkN32c4rlLT7ccL%2BGJIOftVg9NqzateqiR8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 18:56 UTC, frankpeng7 commented
@JarbasHorst somehow I can't send a review request to you so hopefully you can see this

2021-09-16 19:01 UTC, opbld33 commented
Docs Build status updates of commit _[e5cb59a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e5cb59a9bbd5e9988a3b51fd6c0bd807ee51aaac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/api/onlinemeetingartifact-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109161859292983-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T19%3A01%3A24Z&sr=b&sp=r&sig=wU6Llc8j0zobb8Cmzz%2BDjyDg0H%2F7npoADxnE9EBmyLI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 19:59 UTC, JarbasHorst requested changes

2021-09-16 19:59 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +title: "Get meeting artifacts"
Make sure that the title field matches the H1. Suggested revision:

- Get meeting artifact

2021-09-16 19:59 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +| Permission type                        | Permissions                                 |
The boilerplate text needs to be consistent across the doc set. We shouldn't customize the standard boilerplate in the topics, just like we don't change or customize the H2 structure! In this case, please add (from least to most privileged) after Permissions. Suggested revision:

- Permissions (from least to most privileged)

2021-09-16 19:59 UTC, JarbasHorst commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +> To keep API consistency, you can still use the following permissions until **January 15th 2022** to get meeting artifacts:
As per Microsoft style, the following format for dates should be used: month day, year, as in July 31, 2016. Don't use ordinal numbers (such as 1st, 12th, or 23rd) to indicate a date. In this case, replace January 15th 2022 with:

- January 15, 2022

2021-09-16 20:58 UTC, opbld32 commented
Docs Build status updates of commit _[6c16eb9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c16eb950bb2930cf7b31f8d9776152850d30744)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/api/onlinemeetingartifact-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeetingartifact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeetingartifact-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109162056572397-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T20%3A58%3A42Z&sr=b&sp=r&sig=voY9eqN7FjuXhgIxlZGyLbY5g6vcAuwcXXOf8zqHmBE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 21:00 UTC, frankpeng7 commented
@JarbasHorst updated

2021-09-17 22:03 UTC, Lauragra commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +title: "Get meeting artifact"
This topic does not comply with our file naming and topic titling conventions. An "onlineMeetingArtifact" resource doesn't exist. This topic is really about doing a GET call to return a specific property, right? In which case, it would make sense to add the syntax and examples to the existing onlinemeeting-get method topic. Then you would want to surface the permissions there and indicate when they are applicable. Alternatively, if that overloads the GET operation topic, you could create a conceptual How to topic to describe how to get meeting artifacts.

2021-09-17 22:04 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Meeting artifact
This TOC structure implies that a resource known as "meetingArtifact" exists - we only surface entities and the related operations in the TOC.

2021-09-17 22:12 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +title: "Get meeting artifact"
@Lauragra the content used to be in onlinemeeting-get.md and we've been getting complaints about that topic being overloaded. It makes sense to me that onlinemeeting-get.md only contains information about how to get online meeting entity, other resources such as artifacts, since they are not online meeting and are managed by a different set of permissions, can we just make a new topic to cover them? The whole point is not to overload onlinemeeting-get topic. Overloading it and providing an extra conceptual would require more effort for customers to look for what they want

2021-09-17 22:14 UTC, frankpeng7 commented on api-reference/beta/toc.yml
> +        - name: Meeting artifact
Here are one of the example I followed that is not entity nor operations but just a general intro topic https://docs.microsoft.com/en-us/graph/api/resources/calls-api-ivr-overview?view=graph-rest-beta

2021-09-17 22:25 UTC, Lauragra commented on api-reference/beta/api/onlinemeetingartifact-get.md
> +title: "Get meeting artifact"
Yes, I get that the topic is getting overloaded. Unfortunately, this approach is not future-proof because we are looking into updating our process to generate the docs directly from the CSDL. So we need to avoid creating one-off files that are exceptions that don't technically follow the CSDL. We are also looking into different options for documenting permissions, FYI. At this point it seems like a concept topic is the most viable option.

2021-09-17 22:27 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Meeting artifact
Yes, we do have API overview topics to help set context about a set of APIs. Those are a little different than an operation topic that doesn't technically follow the CSDL, however.

2021-09-18 00:12 UTC, opbld34 commented
Docs Build status updates of commit _[993cccb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/993cccb4b01f1cb2f9d16ec24701ab618bfede34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-14270) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109180010350900-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-19T00%3A12%3A26Z&sr=b&sp=r&sig=S4pDn3rgeimxwu99OU3w7uvJ5ICTgGJORUcesFYJXGI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-18 00:30 UTC, opbld31 commented
Docs Build status updates of commit _[4ef2fa4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ef2fa42c1d416811f320a736417282f00f05e2a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-14270) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109180028581985-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-19T00%3A30%3A43Z&sr=b&sp=r&sig=j48xjMgOB%2Fi6JmcPTdTOcOX6QChBPZcwZ0QPa2y1VoA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-18 00:56 UTC, opbld30 commented
Docs Build status updates of commit _[2c4d585](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c4d585a54030457df2909079d05fa29f278b7aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-14270) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109180054378476-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-19T00%3A56%3A51Z&sr=b&sp=r&sig=zzo6Ey6qWPMQmSrdwSFKnt%2FfVDGt91j2HmFwDRN1uyQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-18 01:04 UTC, opbld31 commented
Docs Build status updates of commit _[05c01f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05c01f8ec7cb1b105dee70db8ce495a05b099e3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-14270) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109180102487893-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-19T01%3A04%3A32Z&sr=b&sp=r&sig=C9NvPWLrp0bKvex5TWNEqspnnR8qSH9ckOczPH01kPU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-18 01:13 UTC, opbld31 commented
Docs Build status updates of commit _[88e7dc1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88e7dc143af11abc687f7364957e22bbe5a47058)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-14270) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109180111276061-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-19T01%3A13%3A35Z&sr=b&sp=r&sig=50JsCHd6H37A6c5unj%2FlN4Jv%2FxozjDKLVwWxsTO8TSE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-18 01:15 UTC, opbld32 commented
Docs Build status updates of commit _[eaf6021](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eaf6021ebb3433f9a9d4c5e6353fae806d3b06d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-14270) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109180112589694-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-19T01%3A15%3A38Z&sr=b&sp=r&sig=yF6dRfzNcGmcucU93F4Z%2Bgh%2F%2BonSMaT2DDcXvZf1Se0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-18 01:21 UTC, Lauragra commented on concepts/cloud-communications-online-meeting-artifacts.md
> +# Online meeting artifacts and permissions
Do you only want this topic to be accessible via a link in the Get onlineMeeting topic, or do you want to surface it in the TOC?

2021-09-18 01:26 UTC, frankpeng7 commented on concepts/cloud-communications-online-meeting-artifacts.md
> +# Online meeting artifacts and permissions
I wasn't able to locate the learn section in toc. Could you help add it?

2021-09-18 01:33 UTC, opbld33 commented
Docs Build status updates of commit _[1c6fb49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c6fb49e73d30acac8b73d3c642169b0e214e695)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-14270) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-14270) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109180132032073-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-19T01%3A33%3A42Z&sr=b&sp=r&sig=TomUJyjdRs4qfA9lTuxAn1IeiYULPGIyWv%2FCe%2BHYUFs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-21 01:38 UTC, opbld33 commented
Docs Build status updates of commit _[66e6c01](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66e6c012f093be3445b796acb31451484534c6cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-14270) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-14270) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109210136393631-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-22T01%3A38%3A23Z&sr=b&sp=r&sig=FWJfHdq2zvzwW%2FHTeoINfFPk2OfUHwSWBN4ocpjmoHA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-21 02:25 UTC, opbld32 commented
Docs Build status updates of commit _[e69afbd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e69afbd62a9820b4f8f642fd51e56f4f7e599657)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-14270) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-14270) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109210223400836-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-22T02%3A25%3A30Z&sr=b&sp=r&sig=NnsCGP7GVxAzqWhmjwW2IeeIyOTu7FJDLdk6%2B8xTcCw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-21 02:27 UTC, opbld34 commented
Docs Build status updates of commit _[a7eeb25](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a7eeb258e5579ee29a64ee73373be90c4c74d414)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-14270) (graph-rest-beta) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-14270) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/online-meeting-attendance-report-app-permission/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-14270) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109210224137483-14270%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-22T02%3A27%3A37Z&sr=b&sp=r&sig=ulIV%2BN3nM9ZMWD3%2Bseav7E9wdfjGhYcCzMO%2FbsMHG5U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-22 00:09 UTC, frankpeng7 commented
Hi @Lauragra please help merge this PR. Thanks!

2021-09-23 04:12 UTC, merged