Tutorial: access review of assignments to privileged roles
microsoftgraph/microsoft-graph-docs pull request #14283
Opened 2021-09-15 20:02 UTC by FaithOmbongi

2021-09-15 20:06 UTC, opbld30 commented
Docs Build status updates of commit _[c63c866](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c63c8666814d70d950228736ae64ac5bc6306e2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-14283) (graph-rest-beta) |
[api-reference/v1.0/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/api-reference/v1.0/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-1.0&branch=pr-en-us-14283) (>= graph-rest-1.0) |
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109152002164223-14283%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T20%3A06%3A57Z&sr=b&sp=r&sig=XlWszaQQujxdmsvnobY%2BW4%2B5DU3BJ%2BWo98v6BJxk04U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 20:09 UTC, opbld34 commented
Docs Build status updates of commit _[d885d49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d885d495cb84018e886745333ef94492a4a5a375)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-14283) (graph-rest-beta) |
[api-reference/v1.0/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/api-reference/v1.0/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-1.0&branch=pr-en-us-14283) (>= graph-rest-1.0) |
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109152003133639-14283%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T20%3A09%3A31Z&sr=b&sp=r&sig=q2wc9ifMI8Y8nayKOGfDs%2FAoj3L82G4R%2FUlICrJib0E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 17:35 UTC, opbld30 commented
Docs Build status updates of commit _[92f68cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92f68cd59b58856791d630584e78b28460c548ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) | [Details](#user-content-8097d0a19aa5a626e9285ca274cac197-9ea49436)

<a id="8097d0a19aa5a626e9285ca274cac197-9ea49436"></a>
### [concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md)
 - **Line 659, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /microsoft-365/compliance/privileged-access-management-overview?view=o365-worldwide. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111241732467989-14283%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T17%3A35%3A36Z&sr=b&sp=r&sig=h3Y4wqqPmlnfTeGSCLSiOK9VoolTo70yHiF%2Fu2aQj0U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 18:19 UTC, opbld32 commented
Docs Build status updates of commit _[29ed79f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/29ed79f6f0e775769f63515f0807de8d08f10370)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) | [Details](#user-content-8097d0a19aa5a626e9285ca274cac197-09e32505)

<a id="8097d0a19aa5a626e9285ca274cac197-09e32505"></a>
### [concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md)
 - **Line 659, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /microsoft-365/compliance/privileged-access-management-overview?view=o365-worldwide. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111241817336774-14283%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T18%3A19%3A34Z&sr=b&sp=r&sig=e5VHVC0t%2FzONxXlbt9MsK5cM40A7z2f20K1MULCJgnw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 18:41 UTC, opbld31 commented
Docs Build status updates of commit _[243328c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/243328c142443f7c7e38eef0134c99f77367ec87)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) | [Details](#user-content-8097d0a19aa5a626e9285ca274cac197-55410c05)

<a id="8097d0a19aa5a626e9285ca274cac197-55410c05"></a>
### [concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md)
 - **Line 659, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /microsoft-365/compliance/privileged-access-management-overview?view=o365-worldwide. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111241839066671-14283%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T18%3A41%3A14Z&sr=b&sp=r&sig=a5KXjzkTO36n2ETdHwy9C1cn8TrrMnCB9EzhxXFoZ0g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-30 20:14 UTC, isabelleatmsft requested changes
couple of minor changes needed, but overall looks great and will be super valuable to customers!

2021-12-30 20:14 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-roleassignments.md
> +You can now record or submit your decisions for the access review instances.
```suggestion
As the reviewer, you can now submit your decisions for the access review instance.
```

2021-12-30 20:14 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-roleassignments.md
> +As an admin, after the **status** of the accessReviewInstance is set to `Completed`, you can apply the access review decisions.
```suggestion
As an admin, after the 3 day duration has passed and the **status** of the accessReviewInstance is set to `Completed`, you can apply the access review decisions.
```

2021-12-30 20:14 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-roleassignments.md
> ++ The applyResult is New meaning the decisions haven't yet been applied. You must manually apply the decisions.
But didn't we just apply the decisions in the step above?

2021-12-30 20:14 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-roleassignments.md
> +Contoso's auditors also want to review the access review history for the last quarter. In this example, you'll generate an access review history report for all acecssReviewScheduleDefinitions scoped
```suggestion
Contoso's auditors also want to review the access review history for the last quarter. In this example, you'll generate an access review history report for all accessReviewScheduleDefinitions scoped to directory role assignments (roleAssignmentScheduleInstances). In this query, the **decisions** property is empty and therefore defaults to include all decisions in the history report.
```

2021-12-30 20:14 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-roleassignments.md
> +<!---
i think we should definitely include this part

2022-01-17 10:49 UTC, opbld34 commented
Docs Build status updates of commit _[4c1a228](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c1a228c28d15d3319e71f2468787f5170a12a11)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bc83d8f5)
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :bulb:Suggestion | | [Details](#user-content-8097d0a19aa5a626e9285ca274cac197-bc83d8f5)

<a id="bc83d8f5"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

<a id="8097d0a19aa5a626e9285ca274cac197-bc83d8f5"></a>
### [concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md)
 - **Line 659, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /microsoft-365/compliance/privileged-access-management-overview?view=o365-worldwide. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201171046114713-14283%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T10%3A49%3A45Z&sr=b&sp=r&sig=4SUxN71wt5MjUDTIT%2Ftx10PN3RvTmlkPkhHbMmCpTcY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-17 10:52 UTC, opbld31 commented
Docs Build status updates of commit _[ae1baac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae1baac7a16fdc5699ae74110c431c61ae80348d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) | [Details](#user-content-8097d0a19aa5a626e9285ca274cac197-62c53780)

<a id="8097d0a19aa5a626e9285ca274cac197-62c53780"></a>
### [concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md)
 - **Line 648, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /microsoft-365/compliance/privileged-access-management-overview?view=o365-worldwide. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201171049053926-14283%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T10%3A52%3A37Z&sr=b&sp=r&sig=x9TFJZcW5GKAfQMMBI6bczpvU7F4AKrVOxhI5lIPHqs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-17 10:59 UTC, opbld31 commented
Docs Build status updates of commit _[63a21ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63a21edf138b7de6a1fc28dbe3744a2fab07a801)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) | [Details](#user-content-8097d0a19aa5a626e9285ca274cac197-5af4bf0a)

<a id="8097d0a19aa5a626e9285ca274cac197-5af4bf0a"></a>
### [concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md)
 - **Line 643, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /microsoft-365/compliance/privileged-access-management-overview?view=o365-worldwide. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201171052187023-14283%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T10%3A59%3A44Z&sr=b&sp=r&sig=uCv891hLLOF7BcO3wQ8Ray5lOWb73k1wqhC92S%2FfkIw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-17 11:01 UTC, opbld34 commented
Docs Build status updates of commit _[e3a0feb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3a0febf843b67773217d9fcc254ae38d8ce6b33)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) | [Details](#user-content-8097d0a19aa5a626e9285ca274cac197-45d1a908)

<a id="8097d0a19aa5a626e9285ca274cac197-45d1a908"></a>
### [concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md)
 - **Line 643, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /microsoft-365/compliance/privileged-access-management-overview?view=o365-worldwide. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201171054026151-14283%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T11%3A01%3A44Z&sr=b&sp=r&sig=CRd%2FnEXKNy52GM6VwhZWM2NDieNvo9TtVWSMPnFQaow%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-17 11:08 UTC, opbld32 commented
Docs Build status updates of commit _[da26a3e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da26a3e100fdb4276c8e539831bcbb25936e527b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) | [Details](#user-content-8097d0a19aa5a626e9285ca274cac197-70dda82a)

<a id="8097d0a19aa5a626e9285ca274cac197-70dda82a"></a>
### [concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md)
 - **Line 643, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /microsoft-365/compliance/privileged-access-management-overview?view=o365-worldwide. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201171101151583-14283%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T11%3A08%3A52Z&sr=b&sp=r&sig=ieYN0D0EKfcAk8yb5b1mZ%2BBqYzmT8H5J6Vb%2FmUtzbck%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 08:20 UTC, FaithOmbongi commented on concepts/tutorial-accessreviews-roleassignments.md
> ++ The user in the Global Administrator role is the fallback reviewer. If the reviewers haven't recorded decisions when the review instance nears expiry, the fallback reviewer is notified of the pendi
Well noted. Applied the change. Though I'll ping you offline to understand this better.

2022-01-18 08:44 UTC, FaithOmbongi commented on concepts/tutorial-accessreviews-roleassignments.md
> ++ `77f8b7b6-1119-4a86-b4c3-e7d68e990424` with the value of the global administrator's user identifier.
On it locally.

2022-01-18 08:49 UTC, opbld33 commented
Docs Build status updates of commit _[5454618](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5454618a10d28a7b159040fd7bd5185b24750747)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201180845387257-14283%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T08%3A49%3A04Z&sr=b&sp=r&sig=69%2BgOZ0hte8YtZqOYdoJ48Lu17xwH8dVwfSeSxc2X%2B0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 09:37 UTC, FaithOmbongi commented on concepts/tutorial-accessreviews-roleassignments.md
> ++ The applyResult is New meaning the decisions haven't yet been applied. You must manually apply the decisions.
Q: Good catch. Hadn't run the query for applying decisions for Adele.

2022-01-18 09:39 UTC, FaithOmbongi commented on concepts/tutorial-accessreviews-roleassignments.md
> +<!---
I think it best that we use the recent changes thanks to Levi's PR? Let me retest.

2022-01-18 09:51 UTC, opbld32 commented
Docs Build status updates of commit _[7b06776](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b06776b040e53419ee85dfd06b0278b42d475f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201180949287362-14283%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T09%3A51%3A27Z&sr=b&sp=r&sig=GMnIYMEEqNTyKgnZaR6pWDfnmu6atgpmUjfK%2B0O8e78%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-22 10:38 UTC, opbld34 commented
Docs Build status updates of commit _[977f629](https://github.com/microsoftgraph/microsoft-graph-docs/commits/977f629c802f3846a8ce1c6cdd020cd824c442f4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202221035229599-14283%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-25T10%3A38%3A27Z&sr=b&sp=r&sig=GIyd77Bkw3%2FqIR%2BI3bL6GhZzYCMWKsCc9odRDQxjURU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 15:36 UTC, isabelleatmsft approved these changes
Looks great! Approving with a couple small comments

2022-02-23 15:36 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-roleassignments.md
> ++ Sign in to [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) as a user in an Identity Governance Administrator role.
```suggestion
+ Sign in to [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) as a user in a Privileged Role Administrator role.
```

2022-02-23 15:36 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-roleassignments.md
> ++ Principals assigned to a privileged role that is the scope of your access review. To assign privileged roles, see [Tutorial: Use the Privileged Identity Management (PIM) API to assign Azure AD role
```suggestion
+ Principals assigned to a privileged role. These assignments will be the scope of your access review. To assign privileged roles, see [Tutorial: Use the Privileged Identity Management (PIM) API to assign Azure AD roles](/graph/tutorial-assign-azureadroles).
```

2022-02-23 15:36 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-roleassignments.md
> +        ],
bump @shubhamguptacal !

2022-02-23 15:36 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-roleassignments.md
> ++ The reviewedBy object contains your details as the reviewer
Also add that the deny result on Adele as applied, so the appliedBy property is filled on her decision

2022-02-24 13:26 UTC, opbld31 commented
Docs Build status updates of commit _[3ff34f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ff34f3961b47911e247399758a3681e2d71319c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202241324072734-14283%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-27T13%3A26%3A06Z&sr=b&sp=r&sig=fDqxNKV1iLjzpjr324OwSKKzFbxY8c%2FpCCfmwCfdYOg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-02 20:25 UTC, opbld30 commented
Docs Build status updates of commit _[03211f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03211f678e9a8f894f21797c9fc92925ba203e9e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/images/tutorial-accessreviews-api/settings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/images/tutorial-accessreviews-api/settings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) |
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) |
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-securitygroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-14283) |
[concepts/tutorial-assign-azureadroles.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-assign-azureadroles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-assign-azureadroles?branch=pr-en-us-14283) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203022023235028-14283%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-02T20%3A25%3A23Z&sr=b&sp=r&sig=tMP%2Bl94Bip4MotJ3USlyXrDAjT8U8ZdazEoGAM8YHbI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-02 20:34 UTC, opbld32 commented
Docs Build status updates of commit _[d3e4503](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d3e4503340434aa8a92f5ce7ce302ac48d914f4e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/images/tutorial-accessreviews-api/settings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/images/tutorial-accessreviews-api/settings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) |
[concepts/tutorial-accessreviews-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-roleassignments?branch=pr-en-us-14283) |
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-accessreviews-securitygroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-14283) |
[concepts/tutorial-assign-azureadroles.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/tutorial-accessreviews-roleassignments/concepts/tutorial-assign-azureadroles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-assign-azureadroles?branch=pr-en-us-14283) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203022030560933-14283%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-02T20%3A34%3A56Z&sr=b&sp=r&sig=xMw%2BTMyf8TfygSy05ts0SJr7JRMX3QLF7pxEsPABqTs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-03 03:33 UTC, merged