[CloudPC]Add gallery image entity and related APIs
microsoftgraph/microsoft-graph-docs pull request #14396
Opened 2021-09-28 05:41 UTC by AshleyYangSZ

2021-09-28 05:43 UTC, opbld31 commented
Docs Build status updates of commit _[ddaa3a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ddaa3a95fa7a4462ed39a48886ee2dcb7d0a45d4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) | [Details](#user-content-fb9b1ae52b424abad85fa02944f63146-a3de33de)
[api-reference/beta/api/cloudpcgalleryimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcgalleryimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcgalleryimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) | [Details](#user-content-7ab982015c2365f3d51dfce313603d86-a3de33de)
[api-reference/beta/resources/cloudpcgalleryimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcgalleryimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcgalleryimage?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) | [Details](#user-content-cbb94fd272de0ab8e36c00e37a7fa72d-a3de33de)
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) | [Details](#user-content-47beb7c54cf5f18c080f8250b2ae0491-a3de33de)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-galleryimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-galleryimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-galleryimages?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="fb9b1ae52b424abad85fa02944f63146-a3de33de"></a>
### [api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcdeviceimage-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get cloudPcDeviceImage' is duplicated with other articles: 'beta/api/cloudpcdeviceimage-get.md(10,1), beta/api/cloudpcgalleryimage-get.md(10,1)'. First level headings must be unique within a docset.`````

<a id="7ab982015c2365f3d51dfce313603d86-a3de33de"></a>
### [api-reference/beta/api/cloudpcgalleryimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcgalleryimage-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get cloudPcDeviceImage' is duplicated with other articles: 'beta/api/cloudpcdeviceimage-get.md(10,1), beta/api/cloudpcgalleryimage-get.md(10,1)'. First level headings must be unique within a docset.`````

<a id="cbb94fd272de0ab8e36c00e37a7fa72d-a3de33de"></a>
### [api-reference/beta/resources/cloudpcgalleryimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcgalleryimage.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'cloudPcDeviceImage resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/cloudpcdeviceimage.md(2,8), beta/resources/cloudpcgalleryimage.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcDeviceImage resource type' is duplicated with other articles: 'beta/resources/cloudpcdeviceimage.md(10,1), beta/resources/cloudpcgalleryimage.md(10,1)'. First level headings must be unique within a docset.`````

<a id="47beb7c54cf5f18c080f8250b2ae0491-a3de33de"></a>
### [api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcdeviceimage.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'cloudPcDeviceImage resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/cloudpcdeviceimage.md(2,8), beta/resources/cloudpcgalleryimage.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcDeviceImage resource type' is duplicated with other articles: 'beta/resources/cloudpcdeviceimage.md(10,1), beta/resources/cloudpcgalleryimage.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opb [...]

2021-09-29 03:48 UTC, opbld33 commented
Docs Build status updates of commit _[085947c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/085947cbc5d58b6427d4e6bbee1c83a79098b4af)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-792ba8e6)

<a id="792ba8e6"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109290346121744-14396%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-30T03%3A48%3A12Z&sr=b&sp=r&sig=cD5XhAs2Yxn4i5Lk%2FokFxCzpZQFqzU%2FgA2eoHXZDicY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-29 03:50 UTC, opbld31 commented
Docs Build status updates of commit _[a445080](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a445080120528f01eac25e1d9acc8baed960e124)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) | [Details](#user-content-fb9b1ae52b424abad85fa02944f63146-e083b15e)
[api-reference/beta/api/cloudpcgalleryimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcgalleryimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcgalleryimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) | [Details](#user-content-7ab982015c2365f3d51dfce313603d86-e083b15e)
[api-reference/beta/resources/cloudpcgalleryimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcgalleryimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcgalleryimage?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) | [Details](#user-content-cbb94fd272de0ab8e36c00e37a7fa72d-e083b15e)
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) | [Details](#user-content-47beb7c54cf5f18c080f8250b2ae0491-e083b15e)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-galleryimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-galleryimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-galleryimages?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="fb9b1ae52b424abad85fa02944f63146-e083b15e"></a>
### [api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcdeviceimage-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get cloudPcDeviceImage' is duplicated with other articles: 'beta/api/cloudpcdeviceimage-get.md(10,1), beta/api/cloudpcgalleryimage-get.md(10,1)'. First level headings must be unique within a docset.`````

<a id="7ab982015c2365f3d51dfce313603d86-e083b15e"></a>
### [api-reference/beta/api/cloudpcgalleryimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcgalleryimage-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get cloudPcDeviceImage' is duplicated with other articles: 'beta/api/cloudpcdeviceimage-get.md(10,1), beta/api/cloudpcgalleryimage-get.md(10,1)'. First level headings must be unique within a docset.`````

<a id="cbb94fd272de0ab8e36c00e37a7fa72d-e083b15e"></a>
### [api-reference/beta/resources/cloudpcgalleryimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcgalleryimage.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'cloudPcDeviceImage resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/cloudpcdeviceimage.md(2,8), beta/resources/cloudpcgalleryimage.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcDeviceImage resource type' is duplicated with other articles: 'beta/resources/cloudpcdeviceimage.md(10,1), beta/resources/cloudpcgalleryimage.md(10,1)'. First level headings must be unique within a docset.`````

<a id="47beb7c54cf5f18c080f8250b2ae0491-e083b15e"></a>
### [api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcdeviceimage.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'cloudPcDeviceImage resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/cloudpcdeviceimage.md(2,8), beta/resources/cloudpcgalleryimage.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcDeviceImage resource type' is duplicated with other articles: 'beta/resources/cloudpcdeviceimage.md(10,1), beta/resources/cloudpcgalleryimage.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opb [...]

2021-09-29 08:41 UTC, opbld34 commented
Docs Build status updates of commit _[7411e8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7411e8e49f3132a1efe650b1826343c3019bd40e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) | [Details](#user-content-fb9b1ae52b424abad85fa02944f63146-94660c7c)
[api-reference/beta/api/cloudpcgalleryimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcgalleryimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcgalleryimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) | [Details](#user-content-7ab982015c2365f3d51dfce313603d86-94660c7c)
[api-reference/beta/resources/cloudpcgalleryimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcgalleryimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcgalleryimage?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) | [Details](#user-content-cbb94fd272de0ab8e36c00e37a7fa72d-94660c7c)
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) | [Details](#user-content-47beb7c54cf5f18c080f8250b2ae0491-94660c7c)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-galleryimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-galleryimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-galleryimages?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="fb9b1ae52b424abad85fa02944f63146-94660c7c"></a>
### [api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcdeviceimage-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get cloudPcDeviceImage' is duplicated with other articles: 'beta/api/cloudpcdeviceimage-get.md(10,1), beta/api/cloudpcgalleryimage-get.md(10,1)'. First level headings must be unique within a docset.`````

<a id="7ab982015c2365f3d51dfce313603d86-94660c7c"></a>
### [api-reference/beta/api/cloudpcgalleryimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcgalleryimage-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get cloudPcDeviceImage' is duplicated with other articles: 'beta/api/cloudpcdeviceimage-get.md(10,1), beta/api/cloudpcgalleryimage-get.md(10,1)'. First level headings must be unique within a docset.`````

<a id="cbb94fd272de0ab8e36c00e37a7fa72d-94660c7c"></a>
### [api-reference/beta/resources/cloudpcgalleryimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcgalleryimage.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'cloudPcDeviceImage resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/cloudpcdeviceimage.md(2,8), beta/resources/cloudpcgalleryimage.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcDeviceImage resource type' is duplicated with other articles: 'beta/resources/cloudpcdeviceimage.md(10,1), beta/resources/cloudpcgalleryimage.md(10,1)'. First level headings must be unique within a docset.`````

<a id="47beb7c54cf5f18c080f8250b2ae0491-94660c7c"></a>
### [api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcdeviceimage.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'cloudPcDeviceImage resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/cloudpcdeviceimage.md(2,8), beta/resources/cloudpcgalleryimage.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcDeviceImage resource type' is duplicated with other articles: 'beta/resources/cloudpcdeviceimage.md(10,1), beta/resources/cloudpcgalleryimage.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opb [...]

2021-09-29 08:49 UTC, opbld31 commented
Docs Build status updates of commit _[246231d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/246231d06a5eb92f244933d2d96a5e4b041a9ed4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcgalleryimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcgalleryimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcgalleryimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-galleryimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-galleryimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-galleryimages?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcgalleryimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcgalleryimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcgalleryimage?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109290846583937-14396%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-30T08%3A49%3A26Z&sr=b&sp=r&sig=n%2FI5IJWHlsGCXJgl7k6eC7ydH3ExcAXVCRKRwQunpeQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-29 08:54 UTC, opbld31 commented
Docs Build status updates of commit _[53a6905](https://github.com/microsoftgraph/microsoft-graph-docs/commits/53a6905f71de29f8fb83e52904066647928a755e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcgalleryimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcgalleryimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcgalleryimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-galleryimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-galleryimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-galleryimages?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcgalleryimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcgalleryimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcgalleryimage?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109290852483190-14396%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-30T08%3A54%3A40Z&sr=b&sp=r&sig=RowsqbJ5MdTWMz22kGNW6tfvJfImWjHMfZcTug357xM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-02 08:27 UTC, opbld34 commented
Docs Build status updates of commit _[1d9e2c3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d9e2c3019901a2a17b76840a7669e329f1e65e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcgalleryimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcgalleryimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcgalleryimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-galleryimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-galleryimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-galleryimages?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcgalleryimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcgalleryimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcgalleryimage?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111020825317719-14396%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-03T08%3A27%3A38Z&sr=b&sp=r&sig=pP5Dc%2FKCK0Zh043w8m3wjxmLicIzEDu9BiMiBCXxyKA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-02 08:29 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpcgalleryimage.md
> +Represents the gallery image resource on Cloud PC.
Updated the description. Please help review again.

2021-11-02 08:57 UTC, opbld33 commented
Docs Build status updates of commit _[ad3ef39](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad3ef39c3e9574f6dc6da1bc64a563dc06344e46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcgalleryimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcgalleryimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcgalleryimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-galleryimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-galleryimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-galleryimages?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcgalleryimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcgalleryimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcgalleryimage?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111020854224339-14396%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-03T08%3A57%3A09Z&sr=b&sp=r&sig=ZKxrC5CENwe30dhIaS9J9ABAWMNnC2FoIFsfJsg%2BmxU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-02 20:44 UTC, JarbasHorst requested changes

2021-11-02 20:44 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcgalleryimage.md
> +|publisher|String|The publisher name of the gallery image. This value will be passed to Azure to get image resource. Read-only.|
Please, add "the" before image. Suggested revision:

- ...to Azure to get the image resource...

2021-11-02 20:44 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcgalleryimage.md
> +|offer|String|The offer name of the gallery image. This value will be passed to Azure to get image resource. Read-only.|
Please, add "the" before image. Suggested revision:

- ...to Azure to get the image resource...

2021-11-02 20:44 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcgalleryimage.md
> +|sku|String|The SKU name of the gallery image. This value will be passed to Azure to get image resource. Read-only.|
Please, add "the" before image. Suggested revision:

- ...to Azure to get the image resource...

2021-11-02 20:44 UTC, JarbasHorst commented on api-reference/beta/api/virtualendpoint-list-galleryimages.md
> +title: "List cloudPcGalleryImages"
Please, update the title field to be "List galleryImages". Please, check [this ](https://github.com/microsoftgraph/microsoft-graph-docs/pull/14396#discussion_r733099140)comment for more details. Suggested revision:

- title: "List galleryImages"

2021-11-02 20:44 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcgalleryimage.md
> +description: "Represents the gallery image resource of current organization."
Please, add "the" before current organization.

2021-11-02 20:44 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcgalleryimage.md
> +Represents the gallery image resource of current organization which can be used to provision a Cloud PC.
Please, add "the" before current organization.

2021-11-04 21:28 UTC, opbld30 commented
Docs Build status updates of commit _[3543020](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3543020b584cfbcaffa68bae423a79c1ce49e414)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcgalleryimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcgalleryimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcgalleryimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-galleryimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-galleryimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-galleryimages?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcgalleryimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcgalleryimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcgalleryimage?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111042125420173-14396%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-05T21%3A28%3A08Z&sr=b&sp=r&sig=SkLBP2gqtgZ7ToH03gfLLeXyeM3I9PaCgKfOsHA17AY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-04 21:33 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-11-05 23:00 UTC, Lauragra approved these changes

2021-11-06 00:49 UTC, opbld34 commented
Docs Build status updates of commit _[74cd32f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74cd32f8be6d2cf91e9fff09169c8335f48d739a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcgalleryimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcgalleryimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcgalleryimage-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-galleryimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-galleryimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-galleryimages?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcgalleryimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/cloudpcgalleryimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcgalleryimage?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-14396) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/galleryImage/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111060048107159-14396%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-07T00%3A49%3A36Z&sr=b&sp=r&sig=RKBKQCNgDlIvFpyoE90tFblw%2BK0bLQIw53HbxarXNrE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-06 01:00 UTC, merged