Address DriveItemVersion ordering and current version feedback
microsoftgraph/microsoft-graph-docs pull request #14430
Opened 2021-09-29 21:07 UTC by chackman

Clarify default ordering - newest to oldest version
Explicitly state that `orderBy` is not supported
Add example for `current` version

#5313

2021-09-29 21:10 UTC, opbld32 commented
Docs Build status updates of commit _[ea68a19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea68a19bc8f7bacb9266583594978a1813fb8ffa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/api/driveitem-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-versions?view=graph-rest-beta&branch=pr-en-us-14430) (graph-rest-beta) |
[api-reference/beta/api/driveitemversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/api/driveitemversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-beta&branch=pr-en-us-14430) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/api/driveitem-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-versions?view=graph-rest-1.0&branch=pr-en-us-14430) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitemversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/api/driveitemversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-1.0&branch=pr-en-us-14430) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109292107494039-14430%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-30T21%3A10%3A05Z&sr=b&sp=r&sig=E%2F%2Ba4YofJKugiGNR%2BR0A%2B7qsMu%2FOmRv5L6jp8hWF77k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-02 00:12 UTC, opbld30 commented
Docs Build status updates of commit _[8d8a4c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d8a4c7c7936bf60972d4bc2c68011e3bb9e16db)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitemversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/api/driveitemversion-get.md) | :x:Error | | [Details](#user-content-d8bf966f2e4fc03fcbf390df987e4de2-7b713ff5)
[api-reference/v1.0/api/driveitemversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/api/driveitemversion-get.md) | :x:Error | | [Details](#user-content-66a49ce40335db566a925c937864464b-7b713ff5)

<a id="d8bf966f2e4fc03fcbf390df987e4de2-7b713ff5"></a>
### [api-reference/beta/api/driveitemversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/api/driveitemversion-get.md)
 - **Line 116, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-current-version-csharp-snippets.md'.`````
 - **Line 120, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-current-version-javascript-snippets.md'.`````
 - **Line 124, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-current-version-objc-snippets.md'.`````
 - **Line 128, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/get-current-version-java-snippets.md'.`````

<a id="66a49ce40335db566a925c937864464b-7b713ff5"></a>
### [api-reference/v1.0/api/driveitemversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/api/driveitemversion-get.md)
 - **Line 114, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-current-version-csharp-snippets.md'.`````
 - **Line 118, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-current-version-javascript-snippets.md'.`````
 - **Line 122, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-current-version-objc-snippets.md'.`````
 - **Line 126, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/get-current-version-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110020005522735-14430%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-02T00%3A12%3A48Z&sr=b&sp=r&sig=lGZPw8t0nd1VWS7N3prOihr7VC5nDrUwmGc2Waxk3Pg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-02 00:27 UTC, opbld34 commented
Docs Build status updates of commit _[58b8eeb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58b8eeb04a8eb2fc7ee167bcf2de16148407eb04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/api/driveitem-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-versions?view=graph-rest-beta&branch=pr-en-us-14430) (graph-rest-beta) |
[api-reference/beta/api/driveitemversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/api/driveitemversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-beta&branch=pr-en-us-14430) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-current-version-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/includes/snippets/csharp/get-current-version-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-beta&branch=pr-en-us-14430) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-current-version-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/includes/snippets/java/get-current-version-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-beta&branch=pr-en-us-14430) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-current-version-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/includes/snippets/javascript/get-current-version-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-beta&branch=pr-en-us-14430) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-current-version-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/includes/snippets/objc/get-current-version-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-beta&branch=pr-en-us-14430) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/api/driveitem-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-versions?view=graph-rest-1.0&branch=pr-en-us-14430) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitemversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/api/driveitemversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-1.0&branch=pr-en-us-14430) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-current-version-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/includes/snippets/csharp/get-current-version-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-1.0&branch=pr-en-us-14430) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-current-version-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/includes/snippets/java/get-current-version-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-1.0&branch=pr-en-us-14430) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-current-version-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/includes/snippets/javascript/get-current-version-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-1.0&branch=pr-en-us-14430) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-current-version-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/includes/snippets/objc/get-current-version-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-1.0&branch=pr-en-us-14430) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110020025305609-14430%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-02T00%3A27%3A06Z&sr=b&sp=r&sig=J8ohEr%2FF0LhgBJwUHaZKtpbYN7u4%2FIWf6SrBzrmIoMU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-03 17:16 UTC, isvargasmsft commented on api-reference/beta/api/driveitemversion-get.md
> +        "displayName": "Ryan Gregg"
Please use CELA approved fictitious names. Guidance here: https://microsoft.sharepoint.com/sites/CELAWeb-Copyrights-Trademarks-And-Patents/SitePages/trademarks-fictitious-names.aspx

2021-11-03 17:37 UTC, isvargasmsft commented on api-reference/beta/api/driveitemversion-get.md
> +## Example (Current version)
Examples section starting in line 46:
Please use the proper structure:
H2 Examples
H3 Example 1: Description
H4 Request
H4 Response
H3 Example 2: Description
H4 Request 
H4 Response

etc

2021-11-03 17:38 UTC, isvargasmsft commented on api-reference/v1.0/api/driveitemversion-get.md
> +        "displayName": "Ryan Gregg"
Please use CELA approved fictitious names: https://microsoft.sharepoint.com/sites/CELAWeb-Copyrights-Trademarks-And-Patents/SitePages/trademarks-fictitious-names.aspx

2021-11-03 17:39 UTC, isvargasmsft commented on api-reference/v1.0/api/driveitemversion-get.md
> +## Example (Current version)
Examples section, similar observation above: please use the proper structure.

2021-11-03 17:40 UTC, isvargasmsft commented on api-reference/beta/includes/snippets/csharp/get-current-version-csharp-snippets.md
> +---
I understand these snippets are automatically generated. Are you adding them manually?

2021-11-03 17:42 UTC, isvargasmsft requested changes
Hello Chris, 

Thank you very much for addressing this issues in the docs. 

My comments:
1. Please use CELA approved fictitious names in your examples.
2. Please use the proper heading and title structure for the Examples section. 
3. Please clarify if you are manually adding the snippets. They should be automatically generated. 

Please feel free to ping me on the side if you have any questions. 

Here to help, 

Isaac Vargas

2021-11-04 17:21 UTC, chackman commented on api-reference/beta/includes/snippets/csharp/get-current-version-csharp-snippets.md
> +---
Yes, because if I didn't add them manually, the build fails. How do I generate them?

2021-11-04 21:47 UTC, isvargasmsft commented on api-reference/beta/includes/snippets/csharp/get-current-version-csharp-snippets.md
> +---
You were receiving an error because you manually added the references to those files in the examples. To generated the snippets just remove the sections that I'll indicate and please delete these files.

2021-11-04 21:47 UTC, isvargasmsft commented on api-reference/beta/api/driveitemversion-get.md
> +# [HTTP](#tab/http)
Line 109: please remove this line. This is automatically generated when the docs are published.

2021-11-04 21:48 UTC, isvargasmsft commented on api-reference/beta/api/driveitemversion-get.md
> +```msgraph-interactive
Line 112: Please change `msgraph-interactive` for `http`

2021-11-04 21:48 UTC, isvargasmsft commented on api-reference/beta/api/driveitemversion-get.md
> +---
Lines 115 to 131: please remove these lines.

2021-11-04 21:49 UTC, isvargasmsft commented on api-reference/beta/includes/snippets/csharp/get-current-version-csharp-snippets.md
> +---
Please remove these files if you manually added them.

2021-11-04 21:49 UTC, isvargasmsft commented on api-reference/beta/api/driveitemversion-get.md
> +---
Apply these comments to all files in this PR where applicable.

2021-11-04 21:50 UTC, isvargasmsft commented on api-reference/beta/includes/snippets/csharp/get-current-version-csharp-snippets.md
> +---
Guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103162/Generate-code-snippets

2021-11-04 21:50 UTC, isvargasmsft commented on api-reference/beta/api/driveitemversion-get.md
> +# [HTTP](#tab/http)
Guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103162/Generate-code-snippets

2021-11-04 21:51 UTC, isvargasmsft commented
@chackman guidance on code snippets here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103162/Generate-code-snippets

Please remove all the indicated lines.

2021-11-09 05:48 UTC, opbld30 commented
Docs Build status updates of commit _[8bf0678](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8bf0678fcf09e8d42259c2f4c41128f4f141a70c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/api/driveitem-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-versions?view=graph-rest-beta&branch=pr-en-us-14430) (graph-rest-beta) |
[api-reference/beta/api/driveitemversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/api/driveitemversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-beta&branch=pr-en-us-14430) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/api/driveitem-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-versions?view=graph-rest-1.0&branch=pr-en-us-14430) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitemversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/api/driveitemversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-1.0&branch=pr-en-us-14430) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111090547004364-14430%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T05%3A48%3A26Z&sr=b&sp=r&sig=JkYzIUlEfQDpZh%2BB602GVEIlSLcoPDYCb5LhAG7rqOk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-10 15:19 UTC, isvargasmsft approved these changes

2021-11-11 04:17 UTC, opbld30 commented
Docs Build status updates of commit _[85c5008](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85c500889b5fd0316ab21e605c56ab347864bff4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/api/driveitem-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-versions?view=graph-rest-beta&branch=pr-en-us-14430) (graph-rest-beta) |
[api-reference/beta/api/driveitemversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/api/driveitemversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-beta&branch=pr-en-us-14430) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/api/driveitem-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-versions?view=graph-rest-1.0&branch=pr-en-us-14430) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitemversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/api/driveitemversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-1.0&branch=pr-en-us-14430) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111110416157175-14430%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T04%3A17%3A57Z&sr=b&sp=r&sig=ZuzMjsoalKOVhMmZFoYziSNSbWZtBGZZ9Vc2EFtEeJg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-11 04:22 UTC, opbld30 commented
Docs Build status updates of commit _[d09d689](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d09d68915dba5b117987fc406cf13ce73a89c769)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/api/driveitem-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-versions?view=graph-rest-beta&branch=pr-en-us-14430) (graph-rest-beta) |
[api-reference/beta/api/driveitemversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/beta/api/driveitemversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-beta&branch=pr-en-us-14430) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/api/driveitem-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-list-versions?view=graph-rest-1.0&branch=pr-en-us-14430) (>= graph-rest-1.0) |
[api-reference/v1.0/api/driveitemversion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/chackman/driveItemVersionFixes/api-reference/v1.0/api/driveitemversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitemversion-get?view=graph-rest-1.0&branch=pr-en-us-14430) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111110420560764-14430%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T04%3A22%3A27Z&sr=b&sp=r&sig=6ziQGGNH%2B624nO6VarQ76w5VptTAOLmsE2C86ax1rP8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-11 04:27 UTC, merged