Document timestamp delta tokens.
microsoftgraph/microsoft-graph-docs pull request #14432
Opened 2021-09-29 21:46 UTC by ocreeva

Document timestamp delta tokens.

2021-09-29 21:47 UTC, opbld34 commented
Docs Build status updates of commit _[6c7c9f0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c7c9f0de1caf0bbdd20be93803673eea746eceb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c8d5f18b)

<a id="c8d5f18b"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109292146529108-14432%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-30T21%3A47%3A13Z&sr=b&sp=r&sig=g1e5aUgnTUE9A0jiiDlYjbw%2BRoFGGwvcgJV%2Bi67s4iQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-29 21:57 UTC, chackman approved these changes

2021-09-29 21:57 UTC, opbld30 commented
Docs Build status updates of commit _[aaa298b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aaa298bb778bc92cdc9bd3662439013677d27a08)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-14432) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/v1.0/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-14432) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109292154290285-14432%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-30T21%3A57%3A31Z&sr=b&sp=r&sig=9WoMTGL7BULXj4dbl1DIW2U70HUACd0PDrIx7dW%2Fq0w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-08 19:27 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-delta.md
> +title: "driveItem: delta"
title in line 10 must match with this one. Please edit line 10 as well.

2021-11-08 19:52 UTC, isvargasmsft requested changes
Hello @chackman , 

Thank you very much for taking ownership of this PR and for your work. 

Please apply my comments in all documents in this PR where applicable. 

Feel free to ping me if you have any questions. 

Here to help, 

Isaac Vargas

2021-11-08 19:52 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-delta.md
>  description: "This method allows your app to track changes to a drive and its children over time."
This description is used by search engines to display results. Please revise to:
Track changes in a drive item and its children over time.

2021-11-08 19:52 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-delta.md
> +### Example (Initial Request)
Could you please use the proper structure:
H3 Example 1: Description
H4 Request
H4 Response

2021-11-08 19:52 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-delta.md
> +# [Java](#tab/java)
Please remove these snippets and the manually created files for them. These snippets are automatically generated.

2021-11-08 19:52 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-delta.md
> +```msgraph-interactive
Please remove msgraph-interactive and replace by http

2021-11-08 19:52 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-delta.md
> +# [HTTP](#tab/http)
Line 294: please remove this line, the snippets are automatically generated.

2021-11-08 19:52 UTC, isvargasmsft commented on api-reference/beta/includes/snippets/csharp/get-delta-timestamp-csharp-snippets.md
> +description: "Automatically generated file. DO NOT MODIFY"
Please remove this file. These snippets are automatically generated. If you find an error in the generation, please report it to the proper team so they can improve the tool.

2021-11-08 19:52 UTC, isvargasmsft commented on changelog/Microsoft.FileServices.json
> +            "ApiChange": "Method",
Please clarify if this is a change in an existing functionality or a new functionality:
Use "Change" if the update affects existing functionality, to call out to developers that they need to update existing apps.
Use "Addition" for new API elements (e.g., resources, methods, enums, enum values, permissions), and for new functionality or permission introduced to existing API elements.

Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-properties

2021-11-08 19:52 UTC, isvargasmsft commented on changelog/Microsoft.FileServices.json
> +            "ChangedApiName": "driveItem",
ChangedAPIName should be **delta**, as it is the element being changed.

2021-11-09 05:08 UTC, opbld31 commented
Docs Build status updates of commit _[d930dbb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d930dbb9fd8e8f114460a36a737ab9be6beba975)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-14432) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-delta-timestamp-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/beta/includes/snippets/csharp/get-delta-timestamp-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-14432) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-delta-timestamp-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/beta/includes/snippets/java/get-delta-timestamp-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-14432) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-delta-timestamp-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/beta/includes/snippets/javascript/get-delta-timestamp-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-14432) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/get-delta-timestamp-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/beta/includes/snippets/objc/get-delta-timestamp-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-14432) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/v1.0/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-14432) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-delta-timestamp-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/v1.0/includes/snippets/csharp/get-delta-timestamp-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-14432) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-delta-timestamp-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/v1.0/includes/snippets/java/get-delta-timestamp-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-14432) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-delta-timestamp-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/v1.0/includes/snippets/javascript/get-delta-timestamp-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-14432) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-delta-timestamp-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/v1.0/includes/snippets/objc/get-delta-timestamp-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-14432) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111090506059063-14432%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T05%3A08%3A09Z&sr=b&sp=r&sig=HijTQ2fHeoKSBmJGlZSMwdyCSaYhxhRT0AHv%2BdGvH%2Bw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-09 05:28 UTC, opbld32 commented
Docs Build status updates of commit _[42a108c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42a108c8070e66d317deb03d30b2cf7e8d7d0ac8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-14432) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/v1.0/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-14432) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111090526221945-14432%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T05%3A27%3A59Z&sr=b&sp=r&sig=%2FkCJxO2wjqwJrYibR%2Bl%2FQ2tB%2BRAeDn%2B0FmAQPQO6uNI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-09 16:47 UTC, opbld32 commented
Docs Build status updates of commit _[3e3da79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e3da791f5e27e0a287af86e5b4b2cdadbc4c252)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-14432) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/v1.0/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-14432) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111091644097637-14432%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T16%3A47%3A12Z&sr=b&sp=r&sig=nuoTCroPFxiEU8E9%2FwN7cfJHhTcWL0O3jUNsnmYMTlY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-09 16:51 UTC, isvargasmsft approved these changes

2021-11-10 03:34 UTC, opbld33 commented
Docs Build status updates of commit _[5bebf02](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5bebf02773b5f81175cf89ef276c25d51bd66ae2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/beta/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-14432) (graph-rest-beta) |
[api-reference/v1.0/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/api-reference/v1.0/api/driveitem-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&branch=pr-en-us-14432) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/brperrin/timestampDelta/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111100333040147-14432%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-11T03%3A34%3A52Z&sr=b&sp=r&sig=pH9EQuWTtd1RgM6QrE11bV2XA1rNvp1an7p43g%2BArT0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-10 03:38 UTC, merged