2021 09 29 mahage ediscovery docs and meta
microsoftgraph/microsoft-graph-docs pull request #14448
Opened 2021-10-01 00:55 UTC by mahage-msft

2021-10-01 00:57 UTC, opbld30 commented
Docs Build status updates of commit _[ef68f27](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ef68f270e9837ac30e97fe22a5b31a0a23cc7afa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) | [Details](#user-content-683320c15bf925d5b1c9602c47caac34-936bdb01)
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) | [Details](#user-content-cc019cc5beb0b402404a505384fa9ea6-936bdb01)
[api-reference/beta/api/ediscovery-file-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-file-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-file-get?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |

<a id="683320c15bf925d5b1c9602c47caac34-936bdb01"></a>
### [api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md)
 - **Line 21, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/ediscovery-file-list.md'.`````
 - **Line 22, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/ediscovery-file-create.md'.`````
 - **Line 24, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/ediscovery-file-update.md'.`````
 - **Line 25, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/ediscovery-file-delete.md'.`````
 - **Line 31, Column 69**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 32, Column 82**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 33, Column 71**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 35, Column 87**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 37, Column 244**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 39, Column 77**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 40, Column 69**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 77**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery' will be broken in isolated environments. Replace with a relative link.`````

<a id="cc019cc5beb0b402404a505384fa9ea6-936bdb01"></a>
### [api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md)
 - **Line 18, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/ediscovery-entity.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110010055388199-14448%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T00%3A57%3A19Z&sr=b&sp=r&sig=nF1gRPk3dJGdKuBw%2BEhxcSM%2F%2BII0smHAscRKVFC [...]

2021-10-01 01:15 UTC, opbld31 commented
Docs Build status updates of commit _[448fad2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/448fad21f15969d80a2008e3872cec1d29eab446)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) | [Details](#user-content-683320c15bf925d5b1c9602c47caac34-d97c2815)
[api-reference/beta/api/ediscovery-file-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-file-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-file-get?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |

<a id="683320c15bf925d5b1c9602c47caac34-d97c2815"></a>
### [api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md)
 - **Line 21, Column 58**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/ediscovery-reviewset-list-files.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110010114070120-14448%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T01%3A15%3A46Z&sr=b&sp=r&sig=3UD%2BGjWKYnWjRcWwqtnGwPKCrzKcpVa6t2CkR6yBo9g%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 01:33 UTC, opbld32 commented
Docs Build status updates of commit _[ce053c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ce053c538807990de1a2c59afef99bc6cbb9e264)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-file-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-file-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-file-get?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110010131482947-14448%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T01%3A33%3A24Z&sr=b&sp=r&sig=zteDMNIML9gT2cXccDD5xmg84mCuPa%2FbbmJcdXpk7J0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-04 15:04 UTC, opbld33 commented
Docs Build status updates of commit _[f52b642](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f52b6425d7d6195c7d47dc15fa7061328e5f20ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-file-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-file-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-file-get?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110041502508349-14448%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-04T15%3A04%3A43Z&sr=b&sp=r&sig=FpEDJg3EVqIqyFHnW%2BbVJUy9kI6KgK5C6nWaMFao8Qo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-04 22:00 UTC, opbld31 commented
Docs Build status updates of commit _[9752934](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9752934e5ff7b54cdef0dbce935bf890f4c48a83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-file-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-file-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-file-get?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110042158033520-14448%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-04T22%3A00%3A05Z&sr=b&sp=r&sig=AkYlqF9yXt0fYpgeQPdZuSxoAue9SmpcqtMda%2FMoZgs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-04 22:05 UTC, opbld33 commented
Docs Build status updates of commit _[14ab6f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14ab6f85fd52a0e9d5f5713445fd89a66a7e2038)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-file-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-file-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-file-get?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110042204221592-14448%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-04T22%3A05%3A58Z&sr=b&sp=r&sig=Q1zpt1Zx7r3LY48mjcK34OMZSiOre5GtXVLtSkP5qDU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-06 05:27 UTC, opbld32 commented
Docs Build status updates of commit _[993fe96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/993fe96dbd5f11cde811f6f269916d31f788dbb5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110060526099622-14448%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-06T05%3A27%3A42Z&sr=b&sp=r&sig=ERLfe7giNObURkKyjBSgt5F02kirj%2BQTjbBkmrWneu0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-06 16:14 UTC, opbld33 commented
Docs Build status updates of commit _[d9fa15a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9fa15a5c0bb30627ab77cde25b09a56b711360c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110061613051092-14448%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-06T16%3A14%3A44Z&sr=b&sp=r&sig=lVmwDEpo5Jcn%2Bs0fALhpAj82S3dfbtrFtqwkS3h7GIU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-16 22:06 UTC, JarbasHorst requested changes

2021-11-16 22:06 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-reviewsetquery.md
> +| [export](../api/ediscovery-reviewsetquery-export.md)|None| Exports the results of the **reviewSetQuery** - This method is similar to the [review set export](../api/ediscovery-reviewset-export.md)|
Please, add a period at the end of the sentence. Also, please update row 29.

2021-11-17 20:58 UTC, JarbasHorst requested changes

2021-11-17 20:58 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-file.md
> +|:----|-----------|
GLOBAL: Please, apply this change to all lines in the Description column.

Please, add a period at the end of the sentence.

2021-11-17 20:58 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-file.md
> +| ocrProcessingTimeout          | Timeout while ocrProcessing of the file                               |
For clarity, I recommend you to spell out the acronym. Suggested revision:

- ...while OCR (Optical Character Recognition) processing...

2021-11-17 20:58 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-file.md
> +| ocrFileSizeExceedsLimit       | File size is not in limits for ocr processing                         |
For consistency, please replace "ocr" with "OCR".

2021-11-17 20:58 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-file.md
> +## Relationships
@mahage-msft please verify this comment.

2021-11-17 20:58 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-reviewsetquery.md
> +| [export](../api/ediscovery-reviewsetquery-export.md)|None| Exports the results of the **reviewSetQuery** - This method is similar to the [review set export](../api/ediscovery-reviewset-export.md)|
For consistency, please replace the - with a period. Suggested revision:

- ...**reviewSetQuery**. This...

2021-11-17 20:58 UTC, JarbasHorst commented on changelog/Microsoft.Compliance.Ediscovery.json
> +			"Id": "ec38b495-2154-11ec-bd5a-a13d1ed8c60f",
Within a changelog record, all Id properties must have the same value.

2021-11-23 22:11 UTC, opbld34 commented
Docs Build status updates of commit _[8ffa1b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8ffa1b11c6a0c3e293215ac8400f1aaa437b1ad9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c2d59834)

<a id="c2d59834"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111232206017284-14448%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-24T22%3A11%3A07Z&sr=b&sp=r&sig=K40QWo4uimdmkYfH7fWL0dV8CZA1v2jgnRpWzRh3xAM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-23 22:20 UTC, opbld30 commented
Docs Build status updates of commit _[fea42c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fea42c05bbd9905b0e5134dc6b0f705459da757e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[changelog/Microsoft.Compliance.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/changelog/Microsoft.Compliance.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111232219028386-14448%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-24T22%3A20%3A49Z&sr=b&sp=r&sig=1oCrvTT4Yr0w4XYE%2FbwySfVa5IfuIpsmRYMVmHlLy9o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-23 22:26 UTC, mahage-msft commented on changelog/Microsoft.Compliance.Ediscovery.json
> +			"Id": "ec38b495-2154-11ec-bd5a-a13d1ed8c60f",
What's different here? They are all ec38b495-2154-11ec-bd5a-a13d1ed8c60f, right?

2021-11-23 23:28 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewset-get-file.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
I don't have a list of these and honestly, not sure how to document. This verbiage is the standard verbiage provided by stub generator. Can you provide an example of where these are specified? Or provide more generic verbiage I can use instead?

2021-11-23 23:28 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewset-list-files.md
> +Get the file resources from the files navigation property.
Fixed

2021-11-23 23:30 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewset-list-files.md
> +  "@odata.type": "Collection(microsoft.graph.ediscovery.file)"
fixed.

2021-11-23 23:30 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewsetquery-export.md
> +In the request body, supply JSON representation of the parameters.
fixed.

2021-11-23 23:32 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewsetquery-export.md
> +|azureBlobContainer|String|When exporting to your own Azure storage account, this is the container URL.|
Fixed. -> below example too

2021-11-23 23:32 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewsetquery-export.md
> +|description|String|Description of the export|
Fixed.

2021-11-23 23:33 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewsetquery-export.md
> +|Parameter|Type|Description|
fixed.

2021-11-23 23:34 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewsetquery-run.md
> +/compliance/ediscovery/cases/{caseId}}/reviewSets/{reviewSetId}/queries/{reviewSetQueryId}/run
Yeah, good catch. Looks like I started to fill this out and then just didn't get around to it.

2021-11-23 23:38 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +description: "Object that contains metadata for electronically stored information"
Fixed... in both places.

2021-11-23 23:40 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +|date|DateTimeOffset                                | See `date` at [Document metadata fields in Advanced eDiscovery](/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery)|
fixed.

2021-11-23 23:41 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +|otherProperties|[microsoft.graph.ediscovery.stringValueDictionary](../resources/ediscovery-stringvaluedictionary.md)| Bag of additional properties of the file like to, from, Bcc, created date, etc.
fixed.

2021-11-23 23:46 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +| ocrProcessingTimeout          | Timeout while ocrProcessing of the file                               |
Fixed.

2021-11-23 23:46 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +|:----|-----------|
Fixed.

2021-11-23 23:47 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +| ocrFileSizeExceedsLimit       | File size is not in limits for ocr processing                         |
fixed.

2021-11-23 23:59 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +## Relationships
Fixed.

2021-11-24 00:00 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-reviewset.md
> +| [List files](../api/ediscovery-reviewset-list-files.md)|[microsoft.graph.ediscovery.file](../resources/ediscovery-file.md) collection|Get the file resources from the files navigation property.|
fixed.

2021-11-24 00:06 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-reviewset.md
> +|files|[microsoft.graph.ediscovery.file](../resources/ediscovery-file.md) collection|**TODO: Add Description**|
Good catch, thanks. updated the description for row 47 as well.

2021-11-24 00:07 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-reviewsetquery.md
> +| [export](../api/ediscovery-reviewsetquery-export.md)|None| Exports the results of the **reviewSetQuery** - This method is similar to the [review set export](../api/ediscovery-reviewset-export.md)|
fixed.

2021-11-24 00:08 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-reviewsetquery.md
> +| [export](../api/ediscovery-reviewsetquery-export.md)|None| Exports the results of the **reviewSetQuery** - This method is similar to the [review set export](../api/ediscovery-reviewset-export.md)|
fixed.

2021-11-24 00:22 UTC, opbld32 commented
Docs Build status updates of commit _[81d61d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81d61d4a939fc752936d720ac757f96905049732)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[changelog/Microsoft.Compliance.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/changelog/Microsoft.Compliance.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111240020470547-14448%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T00%3A22%3A20Z&sr=b&sp=r&sig=CNZd0Z60knNaCxWJSCeBwDbd0fdEe9WC%2B4FCJSAJKVY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 21:24 UTC, JarbasHorst commented on api-reference/beta/api/ediscovery-reviewset-get-file.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
As a customer, I'd like to know what OData query parameters I can use. For example, "This method supports the $select and $expand OData query parameters to help customize the response." If you don't have this information, then we should keep the default text provided by the stub generator.

2021-11-24 22:07 UTC, JarbasHorst requested changes

2021-11-24 22:07 UTC, JarbasHorst commented on api-reference/beta/api/ediscovery-reviewsetquery-export.md
> +|azureBlobToken|String|When you export to your own Azure storage account, SAS token for the container URL.|
For clarity, I recommend you to add "this is the " before "SAS token".

2021-11-30 22:23 UTC, JarbasHorst requested changes

2021-11-30 22:23 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-stringvaluedictionary.md
> +## Properties
Thanks for sharing the CSDL. According to the CSDL, stringValueDictionary is a complex type that doesn't have any properties. In this case, please remove the table and just put None.

2021-11-30 22:30 UTC, JarbasHorst requested changes

2021-11-30 22:30 UTC, JarbasHorst commented on api-reference/beta/api/ediscovery-reviewset-list-files.md
> +Get the **file** resources from the files navigation property.
Please, replace **file** with a reference link: \[file\](../resources/ediscovery-file.md)

2021-12-01 00:09 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewset-get-file.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
OK, leaving "standard text" there for now. This is something I would like to revisit across the board for all get/list operations. Our support is very minimal right now at best.

2021-12-01 00:11 UTC, mahage-msft commented on changelog/Microsoft.Compliance.Ediscovery.json
> +			"Id": "ec38b495-2154-11ec-bd5a-a13d1ed8c60f",
Fixed. So much for reading the first and last couple of characters to verify a guid is the same :S. That's certainly the first time I've ever been fooled using that technique. Thanks for the catch.

2021-12-01 00:15 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-stringvaluedictionary.md
> +## Properties
fixed.

2021-12-01 00:16 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewsetquery-run.md
> +  "@odata.type": "Collection(microsoft.graph.ediscovery.file)"
fixed.

2021-12-01 00:16 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewsetquery-run.md
> +GET /compliance/ediscovery/cases/{caseId}}/reviewSets/{reviewSetId}/queries/{reviewSetQueryId}/run
fixed.

2021-12-01 00:17 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewsetquery-export.md
> +|outputName|String|Name of the export. Required.|
fixed.

2021-12-01 00:18 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewsetquery-export.md
> +|azureBlobToken|String|When you export to your own Azure storage account, SAS token for the container URL.|
fixed.

2021-12-01 00:18 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewset-list-files.md
> +Get the **file** resources from the files navigation property.
fixed.

2021-12-01 00:18 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewset-list-files.md
> +Get the **file** resources from the files navigation property.
fixed.

2021-12-01 00:20 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +|otherProperties|[microsoft.graph.ediscovery.stringValueDictionary](../resources/ediscovery-stringvaluedictionary.md)| Bag of additional properties of the file like **to**, **from**, **Bcc**, **creat
fixed.

2021-12-01 16:07 UTC, opbld30 commented
Docs Build status updates of commit _[11e899f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11e899f196c3809907992eece1e64bec3ebab5d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[changelog/Microsoft.Compliance.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/changelog/Microsoft.Compliance.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112011605557217-14448%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T16%3A07%3A28Z&sr=b&sp=r&sig=9Tx1z87J9pyaf4wuLIa9tadvEijGnT%2F5UNIoPvalpOM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 17:29 UTC, opbld34 commented
Docs Build status updates of commit _[fd2f9f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fd2f9f50e072ef5b0eab75085be514ee54502a24)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[changelog/Microsoft.Compliance.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/changelog/Microsoft.Compliance.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112011727307055-14448%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T17%3A29%3A23Z&sr=b&sp=r&sig=x2IQiK4Rbyp%2FQfq%2BAqHsNVeCPxzaN2cOhfSpBUoAY9k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 20:28 UTC, JarbasHorst commented on changelog/Microsoft.Compliance.Ediscovery.json
> +			"Id": "ec38b495-2154-11ec-bd5a-a13d1ed8c60f",
I know exactly what you are talking about 😀

2021-12-01 22:18 UTC, JarbasHorst requested changes

2021-12-01 22:18 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-file.md
> +|date|DateTimeOffset                                | See `date` at [Document metadata fields in Advanced eDiscovery](/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery).|
Instead of using cross-references in the description, can you please provide a description instead of just a cross reference?

2021-12-01 22:18 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-file.md
> +|name|String                                        | File name or subject in case of email. |
Please, add articles before the nouns. Suggested revision:

- The file name or the subject in case of an email.

2021-12-01 22:18 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-file.md
> +|custodians|[microsoft.graph.ediscovery.custodian](../resources/ediscovery-custodian.md) collection| Returns a list of case **custodian** objects for this **file**.|
Please, replace **custodian** with the reference link for custodian. Please, do the same also for **tag**.

2021-12-01 22:18 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-reviewset.md
>  | [addToReviewSet](../api/ediscovery-reviewset-addtoreviewset.md)|None|Add data from a **sourceCollection** to a **reviewset**.|
Please, replace "[addToReviewSet]" with "[Add to review set]"

2021-12-01 22:18 UTC, JarbasHorst commented on api-reference/beta/toc.yml
> +          - name: addToReviewSet
Please, replace "addToReviewSet" with "Add to review set"

2021-12-01 22:18 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-reviewsetquery.md
> +| [export](../api/ediscovery-reviewsetquery-export.md)|None| Exports the results of the **reviewSetQuery**. This method is similar to the [review set export](../api/ediscovery-reviewset-export.md).|
For consistency, please replace [review set export] with [reviewSet: export]

2021-12-01 22:49 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewset-list-files.md
> +If successful, this method returns a `200 OK` response code and a collection of [file](../resources/file.md) objects in the response body.
Fixed.

2021-12-01 22:49 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewsetquery-run.md
> +If successful, this function returns a `200 OK` response code and a [microsoft.graph.ediscovery.file](../resources/ediscovery-file.md) collection in the response body.
Fixed.

2021-12-01 23:17 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +|name|String                                        | File name or subject in case of email. |
fixed.

2021-12-01 23:18 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +|otherProperties|[microsoft.graph.ediscovery.stringValueDictionary](../resources/ediscovery-stringvaluedictionary.md)| Bag of additional properties of the file like **to**, **from**, **Bcc**, **creat
fixed.

2021-12-01 23:20 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +|date|DateTimeOffset                                | See `date` at [Document metadata fields in Advanced eDiscovery](/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery).|
These fields are a bit of a moving target with the descirptions because many of them are calculated fields that we update on a regular basis. I would rather leave as is for now so we have a single master list. Does that seem reasonable?

2021-12-02 02:44 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +| unknownError                  | Status of processing comes as null/empty.                                  |
Fixed, changed the wording a bit too.

2021-12-02 02:48 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-reviewset.md
>  | [addToReviewSet](../api/ediscovery-reviewset-addtoreviewset.md)|None|Add data from a **sourceCollection** to a **reviewset**.|
Fixed. Should export on line 28 be capatilized?

2021-12-02 02:54 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +| invalidField                  | Failure in creating unique fileId hash for file from nativeFilePath.       |
fixed.

2021-12-02 02:55 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +| fileSizeIsZero                | File size is zero or negative.                                             |
fixed.

2021-12-02 02:56 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +| fileSizeIsTooLarge            | File size is larger than the limit.                                        |
fixed.

2021-12-02 02:56 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +| fileBodyIsTooLong             | Text in the document exceeds the maximum length.                           |
fixed.

2021-12-02 02:57 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +| malformedFile                 | File is malformed.                                                         |
fixed.

2021-12-02 02:58 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +| protectedFile                 | Email is rights protected or document is encrypted.                        |
fixed.

2021-12-02 02:58 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +| extractionException           | Extracting embedded documents failure.                                     |
fixed.

2021-12-02 02:59 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +| ocrProcessingTimeout          | Timeout while OCR (Optical Character Recognition) processing of the file.  |
fixed.

2021-12-02 02:59 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +| noReviewSetSummaryGenerated   | Failure was encountered while generating review set summary.               |
fixed.

2021-12-02 03:00 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +| ocrFileSizeExceedsLimit       | File size is not in limits for OCR processing.                             |
fixed.

2021-12-02 03:02 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +|custodians|[microsoft.graph.ediscovery.custodian](../resources/ediscovery-custodian.md) collection| Returns a list of case **custodian** objects for this **file**.|
I don't follow your suggestion here. Are you saying to replace custodian with the same reference link that's in the Type column? So it would look like this?

|[custodian](../resources/ediscovery-custodian.md)|[microsoft.graph.ediscovery.custodian](../resources/ediscovery-custodian.md) collection| Returns a list of case **custodian** objects for this **file**.|

IF so, that seems redundant and I don't seem to recall ever doing that before.

2021-12-02 03:07 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-reviewsetquery.md
> +| [export](../api/ediscovery-reviewsetquery-export.md)|None| Exports the results of the **reviewSetQuery**. This method is similar to the [review set export](../api/ediscovery-reviewset-export.md).|
fixed.

2021-12-02 03:07 UTC, mahage-msft commented on api-reference/beta/toc.yml
> +          - name: run
fixed.

2021-12-02 03:08 UTC, mahage-msft commented on api-reference/beta/toc.yml
> +          - name: export
fixed.

2021-12-02 03:08 UTC, mahage-msft commented on api-reference/beta/toc.yml
> +          - name: addToReviewSet
fixed.

2021-12-02 21:04 UTC, opbld30 commented
Docs Build status updates of commit _[c85f750](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c85f7501b727c6cb406cb251f67f6dee5fdc0874)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[changelog/Microsoft.Compliance.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/changelog/Microsoft.Compliance.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112022102317657-14448%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T21%3A04%3A28Z&sr=b&sp=r&sig=8P%2FgnwWBAmqU6If9qCkn0aebae0u7ABOzP0YTaFP8vw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 21:23 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-file.md
> +| protectedFile                 | The email is rights protected or the document is encrypted.                |
Please, add either before rights. Suggested revision:

- The email is either rights protected or the document is encrypted.

2021-12-02 21:23 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-file.md
> +| invalidField                  | An error occurred during the creation of the unique **fileId** hash for the **file** from the **nativeFilePath** |
Please, add a period at the end of this sentence.

2021-12-02 21:23 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-file.md
> +|custodians|[microsoft.graph.ediscovery.custodian](../resources/ediscovery-custodian.md) collection| Returns a list of case **custodian** objects for this **file**.|
You are completely right! No changes needed in this case.

2021-12-02 21:23 UTC, JarbasHorst commented on api-reference/beta/toc.yml
> +          - name: export
Please, replace "export" with "Export".

2021-12-02 21:23 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-reviewset.md
>  | [addToReviewSet](../api/ediscovery-reviewset-addtoreviewset.md)|None|Add data from a **sourceCollection** to a **reviewset**.|
Yes, please.

2021-12-02 21:48 UTC, mahage-msft commented on api-reference/beta/toc.yml
> +          - name: export
fixed

2021-12-02 21:48 UTC, JarbasHorst requested changes

2021-12-02 21:48 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-reviewset.md
> +| [Add to review set](../api/ediscovery-reviewset-addtoreviewset.md)|None|Add data from a **sourceCollection** to a **reviewset**.|
Please, replace "reviewset" with "reviewSet"

2021-12-02 21:48 UTC, JarbasHorst commented on api-reference/beta/api/ediscovery-reviewsetquery-export.md
> +|exportStructure|[microsoft.graph.ediscovery.exportFileStructure](../resources/ediscovery-caseexportoperation.md#exportfilestructure-values)|Options that control file structure and packaging of the e
Please, add "the" before structure.

2021-12-02 21:48 UTC, JarbasHorst commented on api-reference/beta/api/ediscovery-reviewsetquery-export.md
> +>**Note:** The response object shown here might be shortened for readability.
Please, remove this sentence because the response body doesn't contain any value. I assume the API will always return an empty response body, right?

2021-12-02 21:48 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-file.md
> +|id|String                                          | File unique identifier. |
Please, replace "File unique identifier." with "The unique identifier for the file."

2021-12-02 21:48 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-reviewset.md
>  Represents static set of electronically stored information collected for use in a litigation, investigation, or regulatory request.
Please, add "the" before static. Please, apply this change also to line 3.

2021-12-02 21:48 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-reviewset.md
>  | [export](../api/ediscovery-reviewset-export.md) | None | Initiate an export of data from the **reviewset**. |
lease, replace "reviewset" with "reviewSet"

2021-12-02 21:48 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-reviewsetquery.md
>  | [applyTags](../api/ediscovery-reviewsetquery-applytags.md)|None|Apply tags to documents that match the specified query.|
Please, replace "applyTags" with "Apply tags"

2021-12-02 21:48 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-reviewsetquery.md
> +| [export](../api/ediscovery-reviewsetquery-export.md)|None| Exports the results of the **reviewSetQuery**. This method is similar to the [reviewSet: export](../api/ediscovery-reviewset-export.md).|
Please, capitalize export and run (line 29).

2021-12-02 21:48 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-file.md
> +|:---|:---|:---|
Please, apply bold formatting to all references to the file resource type.

2021-12-02 21:48 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +| invalidField                  | An error occurred during the creation of the unique **fileId** hash for the **file** from the **nativeFilePath** |
fixed.

2021-12-02 21:48 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +|custodians|[microsoft.graph.ediscovery.custodian](../resources/ediscovery-custodian.md) collection| Returns a list of case **custodian** objects for this **file**.|
Thanks!

2021-12-02 21:49 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md
> +Start the process of adding a collection from Microsoft 365 services to a review set. After the operation is created, you can get the status of the operation by retrieving the `Location` parameter fr
fixed.

2021-12-02 21:50 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-reviewsetquery.md
>  | [applyTags](../api/ediscovery-reviewsetquery-applytags.md)|None|Apply tags to documents that match the specified query.|
fixed.

2021-12-02 21:50 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-reviewsetquery.md
> +| [export](../api/ediscovery-reviewsetquery-export.md)|None| Exports the results of the **reviewSetQuery**. This method is similar to the [reviewSet: export](../api/ediscovery-reviewset-export.md).|
fixed.

2021-12-02 21:51 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +| protectedFile                 | The email is rights protected or the document is encrypted.                |
fixed.

2021-12-02 21:53 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +|:---|:---|:---|
Not following...

Do you mean "See **date** at" insetad of "See `date` at"

2021-12-02 21:53 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +|id|String                                          | File unique identifier. |
fixed.

2021-12-02 21:54 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +|:---|:---|:---|
Bahhhh, that didn't render very well.  Maybe this works.

Do you mean "See \*\*date\*\* at" insetad of "See \`date\` at"

2021-12-02 21:56 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-reviewset.md
>  | [export](../api/ediscovery-reviewset-export.md) | None | Initiate an export of data from the **reviewset**. |
fixed. Should Export be capatilized here even though it's a method and it's lower case?

2021-12-02 21:57 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-reviewset.md
> +| [Add to review set](../api/ediscovery-reviewset-addtoreviewset.md)|None|Add data from a **sourceCollection** to a **reviewset**.|
fixed.

2021-12-02 22:00 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-reviewset.md
>  Represents static set of electronically stored information collected for use in a litigation, investigation, or regulatory request.
fixed.

2021-12-02 22:00 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-reviewset.md
>  | [export](../api/ediscovery-reviewset-export.md) | None | Initiate an export of data from the **reviewset**. |
Fixed.

2021-12-03 17:00 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewsetquery-export.md
> +>**Note:** The response object shown here might be shortened for readability.
Fixed.

2021-12-03 17:01 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewsetquery-export.md
> +|exportStructure|[microsoft.graph.ediscovery.exportFileStructure](../resources/ediscovery-caseexportoperation.md#exportfilestructure-values)|Options that control file structure and packaging of the e
Fixed, but I put 'the' before file, not structure. Pretty sure that's correct.

2021-12-03 20:58 UTC, JarbasHorst commented on api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md
> +Start the process of adding a collection from Microsoft 365 services to a review set. After the operation is created, you can get the status of the operation by retrieving the `Location` parameter fr
Hi @mahage-msft, thanks for addressing part of the issue. Can you please replace "addToReviewsetOperation" with "addToReviewSetOperation"?

2021-12-03 21:24 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-reviewset.md
>  | [export](../api/ediscovery-reviewset-export.md) | None | Initiate an export of data from the **reviewset**. |
Yes, it should be capitalized here. In general, we use here friendly names.

2021-12-03 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-reviewsetquery.md
> +| [run](../api/ediscovery-reviewsetquery-run.md)|[microsoft.graph.ediscovery.file](../resources/ediscovery-file.md) collection| Executes a *reviewSetQuery**.|
Please, replace "run" with "Run"

2021-12-03 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-file.md
> +|:---|:---|:---|
Lines 29 and 33: Please, apply bold formatting to file. Suggested revision:

- The content stream of the original \*\*file\*\*.
- The unique identifier for the \*\*file\*\*.

2021-12-03 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-reviewsetquery.md
> +| [export](../api/ediscovery-reviewsetquery-export.md)|None| Exports the results of the **reviewSetQuery**. This method is similar to the [reviewSet: export](../api/ediscovery-reviewset-export.md).|
Hi @mahage-msft, here you should still capitalize run (line 29).

2021-12-03 21:50 UTC, JarbasHorst requested changes

2021-12-03 21:50 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-file.md
> +|date|DateTimeOffset                                | See `date` at [Document metadata fields in Advanced eDiscovery](/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery).|
Ideally, you should describe the property. It is important to make it clear for users that it's not just a cross-reference for more information but it's where they need to go to get the definition of the property. For simplicity and considering these fields are calculated fields, what about a description like: The calculated date. However, if you still want to use a cross-reference, then please use: "Calculated value. For a definition of this property, see [link]." In general, please apply this change to all descriptions that contain a cross-reference.

2021-12-07 19:31 UTC, opbld34 commented
Docs Build status updates of commit _[2faee23](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2faee235d2ef020a5128b9795af3d957947eb773)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[changelog/Microsoft.Compliance.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/changelog/Microsoft.Compliance.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112071929107657-14448%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T19%3A31%3A38Z&sr=b&sp=r&sig=XwpUIvcDRYgvIm5ppx0gzpo6xahBD4r6gqOkfJIjdyY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-07 22:56 UTC, JarbasHorst requested changes

2021-12-07 22:56 UTC, JarbasHorst commented on api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md
> +Start the process of adding a collection from Microsoft 365 services to a review set. After the operation is created, you can get the status of the operation by retrieving the `Location` parameter fr
Please, replace "addToReviewsetOperation" with "addToReviewSetOperation".

2021-12-07 22:56 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-file.md
> +|:---|:---|:---|
GLOBAL: Please, apply this change to all descriptions that contain cross-reference.

For consistency, clarity, and readability, we introduce the subject before we provide the link. In this case, I recommend: 

- For more details on the definition of this property, see [link].

For example,

- The date associated with the file. For more details on the definition of this property, see [Document metadata fields in Advanced eDiscovery](/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery).

2021-12-07 22:56 UTC, JarbasHorst commented on api-reference/beta/resources/ediscovery-reviewsetquery.md
> +| [run](../api/ediscovery-reviewsetquery-run.md)|[microsoft.graph.ediscovery.file](../resources/ediscovery-file.md) collection| Executes a *reviewSetQuery**.|
Please, replace "[run]" with "[Run]".

2021-12-07 23:34 UTC, mahage-msft commented on api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md
> +Start the process of adding a collection from Microsoft 365 services to a review set. After the operation is created, you can get the status of the operation by retrieving the `Location` parameter fr
fixed.

2021-12-07 23:36 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-file.md
> +|:---|:---|:---|
fixed.

2021-12-07 23:37 UTC, mahage-msft commented on api-reference/beta/resources/ediscovery-reviewsetquery.md
> +| [run](../api/ediscovery-reviewsetquery-run.md)|[microsoft.graph.ediscovery.file](../resources/ediscovery-file.md) collection| Executes a *reviewSetQuery**.|
fixed.

2021-12-07 23:40 UTC, opbld31 commented
Docs Build status updates of commit _[96fefb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96fefb66ea4e373312fa5237ce0491b0fbd126e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[changelog/Microsoft.Compliance.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/changelog/Microsoft.Compliance.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112072338121343-14448%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T23%3A40%3A02Z&sr=b&sp=r&sig=HlMKcvAlDBbqBnXs5Rh5%2FSLukqTb4ei9XScAiDnfL0E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-08 21:47 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-12-08 23:28 UTC, opbld31 commented
Docs Build status updates of commit _[3039180](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30391805cb95a0c17542a82c1dfe95a2f986963e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-df4c0323)
[api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[changelog/Microsoft.Compliance.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/changelog/Microsoft.Compliance.Ediscovery.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-df4c0323"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml)
 - **Line 9652, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112082327108810-14448%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-08T23%3A28%3A52Z&sr=b&sp=r&sig=FKm%2Fg77v3vRspBc1owHOkZPXOb9b5KTmjiJpIo%2BVrqA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-08 23:29 UTC, opbld32 commented
Docs Build status updates of commit _[3039180](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30391805cb95a0c17542a82c1dfe95a2f986963e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-87a73e3d)
[api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[changelog/Microsoft.Compliance.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/changelog/Microsoft.Compliance.Ediscovery.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-87a73e3d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml)
 - **Line 9652, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112082327212536-14448%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-08T23%3A29%3A08Z&sr=b&sp=r&sig=agwqoRNZALNFg70%2F%2Fq4xQ4s0YsK0elugX2gSMwFrrk0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-08 23:48 UTC, Lauragra approved these changes

2021-12-08 23:50 UTC, opbld34 commented
Docs Build status updates of commit _[f5f3c31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5f3c31c98d59b3e79a7b1e240feb2a349aec051)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-af1cb5b2)
[api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[changelog/Microsoft.Compliance.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/changelog/Microsoft.Compliance.Ediscovery.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-af1cb5b2"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml)
 - **Line 9652, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112082348293423-14448%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-08T23%3A50%3A03Z&sr=b&sp=r&sig=5UzCZXs%2FttHPiBFfS%2F0U5tCtZKrq0MznaQK4PiL6d0I%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-08 23:52 UTC, opbld33 commented
Docs Build status updates of commit _[f5f3c31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5f3c31c98d59b3e79a7b1e240feb2a349aec051)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-4204a461)
[api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[changelog/Microsoft.Compliance.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/changelog/Microsoft.Compliance.Ediscovery.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-4204a461"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml)
 - **Line 9652, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112082348398626-14448%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-08T23%3A52%3A18Z&sr=b&sp=r&sig=J54anOBLX6RRjthFZyDHgEti1La18QJBgK0mcfX8d3c%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-07 22:29 UTC, opbld33 commented
Docs Build status updates of commit _[1d9b5cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d9b5cd181baa6e0962bee3a8ea21f11d7561b38)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-noncustodialdatasource-list-datasource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-noncustodialdatasource-list-datasource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-noncustodialdatasource-list-datasource?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-noncustodialdatasource-list-datasource?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[changelog/Microsoft.Compliance.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/changelog/Microsoft.Compliance.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201072226562586-14448%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-07T22%3A29%3A03Z&sr=b&sp=r&sig=QVJvs%2B5y8B6TE0Lr3A7DXA24X9XlaXHz9FZvNltj7nA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-04 23:05 UTC, Lauragra commented
@mahage-msft , after we resolve the merge conflict on this PR, are we ready to merge, or do we need more updates? The schema for this PR has already been released.

2022-03-04 23:10 UTC, opbld34 commented
Docs Build status updates of commit _[9969751](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9969751853f286ba077d8ddba29a2a841a0edcbd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-noncustodialdatasource-list-datasource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-noncustodialdatasource-list-datasource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-noncustodialdatasource-list-datasource?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-noncustodialdatasource-list-datasource?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[changelog/Microsoft.Compliance.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/changelog/Microsoft.Compliance.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203042308441577-14448%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T23%3A10%3A47Z&sr=b&sp=r&sig=LOxXeYQA%2FvCO6hFbOYbVytZ6UoLiWeS5nirWycdWTzI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-04 23:14 UTC, opbld34 commented
Docs Build status updates of commit _[0f4629c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f4629c6738974c5910e44ecf184f8c7924b0c2b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscovery-noncustodialdatasource-list-datasource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-noncustodialdatasource-list-datasource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-noncustodialdatasource-list-datasource?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-addtoreviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-addtoreviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-get-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewset-list-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewset-list-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewset-list-files?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-export.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-export.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-export?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/api/ediscovery-reviewsetquery-run.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/api/ediscovery-reviewsetquery-run.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-reviewsetquery-run?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-caseexportoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-caseexportoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-caseexportoperation?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-file?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewset?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-reviewsetquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-reviewsetquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-reviewsetquery?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/resources/ediscovery-stringvaluedictionary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/resources/ediscovery-stringvaluedictionary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/ediscovery-stringvaluedictionary?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-noncustodialdatasource-list-datasource?view=graph-rest-beta&branch=pr-en-us-14448) (graph-rest-beta) |
[changelog/Microsoft.Compliance.Ediscovery.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-mahage-eDiscovery-docsAndMeta/changelog/Microsoft.Compliance.Ediscovery.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203042312087581-14448%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T23%3A14%3A08Z&sr=b&sp=r&sig=1hJxFKIvJ3lij%2FRWVr4rx2zKK3pCzTTjaHtXPaPAGjY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 04:32 UTC, closed without merging