2021 09 29 mark chat read unread for user
microsoftgraph/microsoft-graph-docs pull request #14447
Opened 2021-10-01 00:09 UTC by sweta-thapliyal

2021-10-01 00:11 UTC, opbld33 commented
Docs Build status updates of commit _[b0341d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0341d89121e292587241b1ffc5b7f34e2fd659a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110010009232893-14447%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T00%3A11%3A23Z&sr=b&sp=r&sig=%2FeA1fjorreQllvowdug%2BSdrL2SUJj3ejOcPHwH9oOmw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 17:06 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-markchatreadforuser.md
> +title: "chat: markChatReadForUser"
'Mark chat as read' as the title?

2021-10-01 17:20 UTC, eddie-lee-msft requested changes

2021-10-01 17:20 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-markchatreadforuser.md
> +Marks [chat](../resources/chat.md) as Read for a user.
not sure if 'Read' needs capitalization

2021-10-01 17:20 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-markchatreadforuser.md
> +POST /chats/{chatsId}/markChatReadForUser
'chatsId' should be 'chat-id'

fix this here and elsewhere

2021-10-01 17:20 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-markchatreadforuser.md
> +|user|[teamworkUserIdentity](../resources/teamworkuseridentity.md)|**TODO: Add Description**|
pls add descriptions to the parameters

2021-10-01 17:20 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-markchatreadforuser.md
> +  "user": {
example seems incomplete?

2021-10-01 17:20 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-markchatunreadforuser.md
> +title: "chat: markChatUnreadForUser"
'Mark chat as unread' maybe?

2021-10-01 17:20 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-markchatunreadforuser.md
> +POST /chats/{chatsId}/markChatUnreadForUser
chat-id

2021-10-01 17:20 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-markchatunreadforuser.md
> +|user|[teamworkUserIdentity](../resources/teamworkuseridentity.md)|User to hide the chat for. **In delegated, a user may only hide chat for themselves**.|
Description here seems off?

2021-10-01 17:20 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-markchatunreadforuser.md
> +> **Note:** lastMessageReadDateTime is optional in request. If not mentioned, the last message would be marked as Unread.
in *the* request.

uncapitalize 'Unread'

2021-10-01 17:20 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-markchatunreadforuser.md
> +    "@odata.type": "microsoft.graph.teamworkUserIdentity"
here also example seems incomplete. shouldn't id of user be present?

2021-10-01 17:20 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-markchatreadforuser.md
> +``` http
For all your examples could you please add actual sample values instead of "String" or "String (timestamp)"?

2021-10-01 17:20 UTC, eddie-lee-msft commented on changelog/Microsoft.Teams.Core.json
> +      "ChangeList": [
I believe the correct file to put these in is 'Microsoft.Teams.GraphSvc.json'

2021-10-01 17:20 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-markchatreadforuser.md
> +title: "chat: markChatReadForUser"
Please add the two new pages in the toc.yml. can be found under 'api-reference\beta'

2021-10-19 21:17 UTC, JarbasHorst commented
@sweta-thapliyal your PR introduces two new methods (chat-markchatreadforuser and chat-markchatunreadforuser) that should be surfaced from the [chat ](https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta) resource topic. Please, add both methods to the **Chat management** section and include these changes to this PR. Suggested revision:

|  Method       |  Return Type  | Description| 
|:---------------|:--------|:----------|
| **Chat management** |||
|...|...|...|
|[Get chat between user and app](../api/userscopeteamsappinstallation-get-chat.md) | [chat](chat.md)| Get one-on-one chat between user and the app |
|Mark chat as read| ...| Mark chat as read for a user |
|Mark chat as unread | ...| Mark chat as unread for a user |
|...|...|...|

2021-10-21 16:39 UTC, opbld31 commented
Docs Build status updates of commit _[8c31a2c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c31a2c0111829363f1526523c6723f6c3b174ab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d90a7b3a)
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-d90a7b3a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/toc.yml)
 - **Line 9514, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110211637406696-14447%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-21T16%3A39%3A18Z&sr=b&sp=r&sig=2Za%2Bv1Yp0kzAVEWVETZhbZxe9GBGYWFKyYOqVKPsdG8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-21 22:55 UTC, opbld33 commented
Docs Build status updates of commit _[909e16d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/909e16dfce12d1bd3b0c6698b6c61ad55ce69c4b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ef115d23)
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-ef115d23"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/toc.yml)
 - **Line 9514, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110212252433291-14447%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-21T22%3A55%3A40Z&sr=b&sp=r&sig=9ytxxnDgCserrVY5f7UJym4X0w8puvQatnCwsYQcFYY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-05 01:56 UTC, opbld34 commented
Docs Build status updates of commit _[ea42fb3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea42fb3ba3764b0e6f617facd3bccd31e9908e74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111050154066968-14447%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-06T01%3A56%3A33Z&sr=b&sp=r&sig=phscfk7dGGQRKOu5DjaU3oGc6jUIkHLdpGyrH9KJTRw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-05 01:58 UTC, Lauragra approved these changes

2021-11-05 01:58 UTC, opbld30 commented
Docs Build status updates of commit _[c78d9b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c78d9b89ab6544e1dcb605ed1416a3fda23ddd5e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111050155520028-14447%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-06T01%3A58%3A33Z&sr=b&sp=r&sig=RuKVHjuf4KPydsY5RJJ7NFhHp6cEcpXAwknKw0KChvA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-05 02:05 UTC, opbld31 commented
Docs Build status updates of commit _[3734469](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3734469a2d08417b2b4f1d589c39cec8017e1e14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-markchatreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/api/chat-markchatreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[api-reference/beta/api/chat-markchatunreadforuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/api/chat-markchatunreadforuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatunreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-markchatreadforuser?view=graph-rest-beta&branch=pr-en-us-14447) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-09-29-MarkChatReadUnreadForUser/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111050157008676-14447%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-06T02%3A05%3A09Z&sr=b&sp=r&sig=ZupXHfk76BdM3EOH0O10NRy3NTbXkNvrKefzGUEJ8%2Bg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-05 02:06 UTC, merged