Azure AD sign in logs updates Q1
microsoftgraph/microsoft-graph-docs pull request #14465
Opened 2021-10-02 08:06 UTC by besiler

- Service principal updates for CA
- Incoming token type
- Protocol type
- Risk event type deprecation
- Authentication strength
- Home tenant ID and name

2021-10-02 08:08 UTC, opbld32 commented
Docs Build status updates of commit _[355415b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/355415b7d22263326a60ecde3f3a7d68d37035fb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/audituseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/audituseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audituseridentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) | [Details](#user-content-af43a61789e4ebb9b8f1cb4d6528c79b-1920b96f)
[api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrength?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) | [Details](#user-content-593f138ad55787861ebc9236c87c3d8a-1920b96f)
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[changelog-stubs/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog-stubs/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="af43a61789e4ebb9b8f1cb4d6528c79b-1920b96f"></a>
### [api-reference/beta/resources/audituseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/audituseridentity.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/audituseridentity.md(3,14)', 'beta/resources/authenticationstrength.md(3,14)'.`````

<a id="593f138ad55787861ebc9236c87c3d8a-1920b96f"></a>
### [api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/audituseridentity.md(3,14)', 'beta/resources/authenticationstrength.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110020806326998-14465%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-02T08%3A08%3A14Z&sr=b&sp=r&sig=eVRO58xbXufAf9e2HMYQ0sQpn14%2FuT8fl3dP5jxFoUY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a [...]

2021-10-02 08:15 UTC, opbld30 commented
Docs Build status updates of commit _[0e42cd3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e42cd37d4c2ce62599652d8d2981052b5de151a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrength?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) | [Details](#user-content-593f138ad55787861ebc9236c87c3d8a-0e10a5b0)
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/audituseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/audituseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audituseridentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[changelog-stubs/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog-stubs/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="593f138ad55787861ebc9236c87c3d8a-0e10a5b0"></a>
### [api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'besiler**' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110020814156000-14465%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-02T08%3A15%3A57Z&sr=b&sp=r&sig=hYdx4aI9KqduK%2F25HUoHm10bZ8hHki1Phv%2Fcp9BXn%2F0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-02 08:23 UTC, opbld32 commented
Docs Build status updates of commit _[20ed33c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20ed33cb7f9ace2d17cdadfaabbcb0e2bf1f146c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrength?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) | [Details](#user-content-593f138ad55787861ebc9236c87c3d8a-976069ae)
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/audituseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/audituseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audituseridentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="593f138ad55787861ebc9236c87c3d8a-976069ae"></a>
### [api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'besiler**' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110020822031820-14465%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-02T08%3A23%3A44Z&sr=b&sp=r&sig=Q9MTId5pVbHFlZiVOEICl7LgoSoattxRvEbLbBTF7OI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-02 08:33 UTC, opbld33 commented
Docs Build status updates of commit _[4c8d36f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c8d36fd3353728a328b02a2b38f628cdd3aeb0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/audituseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/audituseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audituseridentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrength?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskuseractivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskuseractivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskuseractivity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110020831371326-14465%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-02T08%3A32%3A59Z&sr=b&sp=r&sig=1uVNqHV80cdc3TuP0r832xBbmNupEZ%2BrNNBDI3QctMo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-02 08:49 UTC, opbld31 commented
Docs Build status updates of commit _[74e8ef2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74e8ef24a2706813725551487f40d9916848193c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/audituseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/audituseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audituseridentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrength?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskuseractivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskuseractivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskuseractivity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110020848100248-14465%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-02T08%3A49%3A45Z&sr=b&sp=r&sig=gwaikn4OHSpvp5y09NgwOn1n%2BJHEZT%2BA%2B1U%2FBqbfVdg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-02 08:51 UTC, besiler commented
The API doctor beta is finding some links to the deprecated riskeventtype property we removed

2021-10-03 16:52 UTC, besiler commented
> The API doctor beta is finding some links to the deprecated riskeventtype property we removed

I looked in riskdetection.md and riskyuser.md and couldn't find links to the deprecated riskeventtype property

![image](https://user-images.githubusercontent.com/69605773/135763657-86c3dae2-376c-45a9-a63d-75850bcc5ee5.png)

2021-10-06 09:51 UTC, FaithOmbongi requested changes
@besiler: Feedback
- Will you also be merging in the [FY21 Q4](https://github.com/microsoftgraph/microsoft-graph-docs/pull/13361) updates into this PR? Because otherwise, we'll have incomplete documentation.
- Update the user property in [auditActivityInitiator](https://docs.microsoft.com/en-us/graph/api/resources/auditactivityinitiator?view=graph-rest-beta) to be of type auditUserIdentity (the new complex type you've introduced in this PR).
   - Also add a Changelog entry for this as follows:
   
        {
            "Id": "add-GUID-here",
            "ApiChange": "Property",
            "ChangedApiName": "user",
            "ChangeType": "Change",
            "Description": "Changed the type of the **user** property from **userIdentity** to [auditUserIdentity](https://docs.microsoft.com/en-us/graph/api/resources/audituseridentity?view=graph-rest-beta).",
            "Target": "auditActivityInitiator"
        }
   
- Regarding deprecation: Kindly ensure that the there is appropriate annotation in the Schema regarding the properties you are deprecating. This will ensure that the properties are removed from response objects when the time comes.
   - In the docs, we can't delete deprecated properties until they are first removed from the response objects and the schema. We can only mark them as [deprecated ](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103183/Deprecate-docs?anchor=deprecate-content-for-a-property-or-relationship)as per the guidance.

2021-10-06 09:51 UTC, FaithOmbongi commented on api-reference/beta/resources/audituseridentity.md
> +The identity of a user, along with information about their home tenant.
```suggestion
An open type that represents  details of the identity of a user along with information about their home tenant.
```

2021-10-06 09:51 UTC, FaithOmbongi commented on api-reference/beta/resources/audituseridentity.md
> +|homeTenantName|String|For user sign ins, the ID of the tenant that the user is a member of. Only populated in cases where Azure AD has recorded affirmative consent from the home tenant to show tenan
```suggestion
|homeTenantId|String|For user sign ins, the identifier of the tenant that the user is a member of.|
|homeTenantName|String|For user sign ins, the identifier of the tenant that the user is a member of. Only populated in cases where the home tenant has provided affirmative consent to Azure AD to show the tenant content.|
```

2021-10-06 09:51 UTC, FaithOmbongi commented on api-reference/beta/resources/audituseridentity.md
> +  "@odata.type": "microsoft.graph.auditUserIdentity"
```suggestion
  "blockType": "resource",
  "@odata.type": "microsoft.graph.auditUserIdentity",
  "baseType": "microsoft.graph.userIdentity",
```

2021-10-06 09:51 UTC, FaithOmbongi commented on api-reference/beta/resources/audituseridentity.md
> +description: "The identity of a user, along with information about their home tenant."
```suggestion
description: "An open type that represents  details of the identity of a user along with information about their home tenant."
```

2021-10-06 09:51 UTC, FaithOmbongi commented on api-reference/beta/resources/authenticationstrength.md
> +|authenticationStrengthId|String|*ID of the authentication strength.|
```suggestion
|authenticationStrengthId|String|Identifier of the authentication strength.|
```

2021-10-06 09:51 UTC, FaithOmbongi commented on api-reference/beta/api/signin-get.md
> -  "alternateSignInName": "testaccount2@contoso.com",
Same comment I made in the resource article. This property is still being returned in the response object.

2021-10-06 09:51 UTC, FaithOmbongi commented on api-reference/beta/api/signin-get.md
> -  "riskEventTypes": [],
Same comment I made in the resource article. This property is still being returned in the response object.

2021-10-06 09:51 UTC, FaithOmbongi commented on api-reference/beta/api/signin-list.md
> -      "riskEventTypes": [],
Same comment I made in the resource article. This property is still being returned in the response object.

2021-10-06 09:51 UTC, FaithOmbongi commented on api-reference/beta/api/signin-list.md
> -      "alternateSignInName": "testaccount2.contoso.com",
Same comment I made in the resource article. This property is still being returned in the response object.

2021-10-06 09:51 UTC, FaithOmbongi commented on api-reference/beta/api/signin-list.md
> -      "riskEventTypes":[],
Same comment I made in the resource article. This property is still being returned in the response object.

2021-10-06 09:51 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +        },
Conflict (one object is removing another is adding) and wrong entries here - **homeTenantId** is a property of signIn
```suggestion
          "Id": "bd257a22-af29-466e-9b3d-1386183e61bf",
          "ApiChange": "Property",
          "ChangedApiName": "homeTenantId",
          "ChangeType": "Addition",
          "Description": "Added the **homeTenantId** property to the [signIn](https://docs.microsoft.com/en-us/graph/api/resources/signIn?view=graph-rest-beta) resource.",
          "Target": "signIn"
        },
```

2021-10-06 09:51 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +        },
Conflict here.

2021-10-06 09:51 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +        },
Conflict here.

2021-10-06 09:51 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +        },
Conflict and wrong entries?
```suggestion
        {
          "Id": "bd257a22-af29-466e-9b3d-1386183e61bf",
          "ApiChange": "String",
          "ChangedApiName": "tokenIssuerType",
          "ChangeType": "Deletion",
          "Description": "Removed the **tokenIssuerType** resource type",
          "Target": "signIn"
        },
        {
          "Id": "bd257a22-af29-466e-9b3d-1386183e61bf",
          "ApiChange": "Property",
          "ChangedApiName": "tokenIssuerType",
          "ChangeType": "Addition",
          "Description": "Added the **tokenIssuerType** property to the [signIn](https://docs.microsoft.com/en-us/graph/api/resources/signIn?view=graph-rest-beta) resource.",
          "Target": "signIn"
        },
```

2021-10-06 09:51 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +      "WorkloadArea": "Reports and audit",
```suggestion
      "WorkloadArea": "Reports",
```

2021-12-11 00:37 UTC, opbld31 commented
Docs Build status updates of commit _[d6f4ca5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6f4ca544df19f1ffcb58a39f869e3a854a9c107)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6ba11bcf)

<a id="6ba11bcf"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112110036541683-14465%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-11T00%3A37%3A19Z&sr=b&sp=r&sig=ihPUpcexWdoecMBCpUe%2B4GeVJhk1V1m8ahJGI8X3Vrk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-22 03:19 UTC, opbld33 commented
Docs Build status updates of commit _[d1f48b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1f48b70159165bfce2cd548c5f2d543d894f9df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/audituseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/audituseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audituseridentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrength?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskuseractivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskuseractivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskuseractivity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112220317525949-14465%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-22T03%3A19%3A39Z&sr=b&sp=r&sig=c5pZlnMLYYqrGhyBZhafn8dVfTSB7g9YcvY08a1zajs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-22 03:42 UTC, besiler commented on api-reference/beta/resources/signin.md
> -|riskEventTypes|riskEventType collection|The list of risk event types associated with the sign-in. Possible values: `unlikelyTravel`, `anonymizedIPAddress`, `maliciousIPAddress`, `unfamiliarFeatures`
The property is no longer returned in the response, so I'd like to not have it documented here. What is the metadata that has the property? I don't see it in the CSDL for AAD.Reporting

2021-12-22 03:48 UTC, besiler commented on changelog/Microsoft.AAD.Reporting.json
> +        },
Not sure why the docs tool generated both these change log entries - hopefully it's OK if I just delete both?

2021-12-22 03:49 UTC, besiler commented on api-reference/beta/resources/signin.md
> -|riskEventTypes|riskEventType collection|The list of risk event types associated with the sign-in. Possible values: `unlikelyTravel`, `anonymizedIPAddress`, `maliciousIPAddress`, `unfamiliarFeatures`
I can ask the engg team to mark the property deprected in any metadata as necessary - the ISP team kicked off the deprecation process for this field about two years ago, so hopefully they've handled this already and we just have a few small items to clean up

2021-12-22 03:54 UTC, opbld34 commented
Docs Build status updates of commit _[d3ba4b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d3ba4b54e01032790682ab07d16493fc377d1a91)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/auditactivityinitiator.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/auditactivityinitiator.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/auditactivityinitiator?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/audituseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/audituseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audituseridentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrength?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskuseractivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskuseractivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskuseractivity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112220352412705-14465%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-22T03%3A54%3A33Z&sr=b&sp=r&sig=AuS6jG7MDQ%2BnYKKdCjvXZ1i%2B6P%2Bj3BsFBHiIBB7%2FOu0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-22 04:05 UTC, opbld31 commented
Docs Build status updates of commit _[050a81c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/050a81ce8f8217ca5e3272da05c687937d30e0fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/auditactivityinitiator.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/auditactivityinitiator.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/auditactivityinitiator?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/audituseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/audituseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audituseridentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrength?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskuseractivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskuseractivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskuseractivity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112220404057042-14465%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-22T04%3A05%3A52Z&sr=b&sp=r&sig=ZG0axL5hHmZYO6Lqpwy%2FqgCS3ZL%2FtuKDvsoOnwZhj0w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-22 04:12 UTC, besiler commented on api-reference/beta/resources/signin.md
> -|riskEventTypes|riskEventType collection|The list of risk event types associated with the sign-in. Possible values: `unlikelyTravel`, `anonymizedIPAddress`, `maliciousIPAddress`, `unfamiliarFeatures`
I think these comments might have come from before they merged the PR that got rid of riskEventTypes

2021-12-22 04:13 UTC, besiler commented on changelog/Microsoft.AAD.Reporting.json
> +        },
Deleted both since they were contradictory and I didn't make any changes to resourceTenantId in this PR

2021-12-22 04:15 UTC, opbld33 commented
Docs Build status updates of commit _[f243596](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f243596f767f233d21bc4cff8cfc199ab10e4422)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/auditactivityinitiator.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/auditactivityinitiator.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/auditactivityinitiator?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/audituseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/audituseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audituseridentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrength?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskuseractivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskuseractivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskuseractivity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112220413550800-14465%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-22T04%3A15%3A43Z&sr=b&sp=r&sig=4JNXeIBSffSGn6yNaEjyc3AEQInZVJsp%2B2IRVV9JQGA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-22 04:16 UTC, besiler commented
@FaithOmbongi  I think this one should be good to go now. Marking as feedback provided

2021-12-22 07:05 UTC, FaithOmbongi commented
@besiler, added this to my re-review queue.

2021-12-28 14:46 UTC, opbld34 commented
Docs Build status updates of commit _[1cc275a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1cc275adcaa7bf9f27b61360cc5c633aa68d1f7e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/reportroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reportroot?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) | [Details](#user-content-36aca899975750795ed56a0b002db749-3a772911)
[api-reference/beta/resources/intune-shared-reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/intune-shared-reportroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-shared-reportroot?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) | [Details](#user-content-1458b97eb1a46fbe5904762547b565d0-3a772911)
[api-reference/beta/api/applicationsignindetailedsummary-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/applicationsignindetailedsummary-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/applicationsignindetailedsummary-get?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getazureadapplicationsigninsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/reportroot-getazureadapplicationsigninsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getazureadapplicationsigninsummary?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-applicationsignindetailedsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/reportroot-list-applicationsignindetailedsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-applicationsignindetailedsummary?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/applicationsignindetailedsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/applicationsignindetailedsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationsignindetailedsummary?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/applicationsigninsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/applicationsigninsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationsigninsummary?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/auditactivityinitiator.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/auditactivityinitiator.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/auditactivityinitiator?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/audituseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/audituseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audituseridentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrength?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskuseractivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskuseractivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskuseractivity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/usercredentialusagedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/usercredentialusagedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usercredentialusagedetails?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/applicationsignindetailedsummary-get?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[redirects/.openpublishing.redirection.1221.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/redirects/.openpublishing.redirection.1221.json) | :white_check_mark:Succeeded | |

<a id="36aca899975750795ed56a0b002db749-3a772911"></a>
### [api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/reportroot.md)
 - **Line 2, Column 8 [...]

2021-12-28 14:53 UTC, opbld33 commented
Docs Build status updates of commit _[08c1645](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08c16459dfa49793bc0d6228b40fee48c058a0db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/auditactivityinitiator.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/auditactivityinitiator.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/auditactivityinitiator?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/audituseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/audituseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audituseridentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrength?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskuseractivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskuseractivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskuseractivity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112281451341195-14465%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-28T14%3A53%3A44Z&sr=b&sp=r&sig=YQtdy7IXZ1VFKzBR44ZVGC%2BfOTueNl3RQvHx61wskrk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-28 19:10 UTC, opbld32 commented
Docs Build status updates of commit _[fac946e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fac946e980919054efdb12654a55bf7400da1edc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getazureadapplicationsigninsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/reportroot-getazureadapplicationsigninsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getazureadapplicationsigninsummary?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appidentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/auditactivityinitiator.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/auditactivityinitiator.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/auditactivityinitiator?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/audituseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/audituseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audituseridentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrength?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskuseractivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskuseractivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskuseractivity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112281907363659-14465%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-28T19%3A10%3A35Z&sr=b&sp=r&sig=KR8hLRbqOI3B1zbb0xJSUjtkJRIMy81F6fGw2FgcK9I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-28 19:15 UTC, FaithOmbongi approved these changes

2021-12-28 19:17 UTC, opbld34 commented
Docs Build status updates of commit _[a58b2ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a58b2cec671bef1e26800cdfbe0cf403fac429c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getazureadapplicationsigninsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/reportroot-getazureadapplicationsigninsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getazureadapplicationsigninsummary?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appidentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/auditactivityinitiator.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/auditactivityinitiator.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/auditactivityinitiator?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/audituseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/audituseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audituseridentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrength?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskuseractivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskuseractivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskuseractivity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112281915222366-14465%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-28T19%3A17%3A09Z&sr=b&sp=r&sig=tdkzVJtNBFM%2Bp1Fk%2BKifQL61VkJknVOFSPiXVHwKkpI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-28 19:20 UTC, opbld31 commented
Docs Build status updates of commit _[678a433](https://github.com/microsoftgraph/microsoft-graph-docs/commits/678a433de3080373df911253b7ff4a995dd4038e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appidentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/auditactivityinitiator.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/auditactivityinitiator.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/auditactivityinitiator?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/audituseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/audituseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audituseridentity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/authenticationstrength.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/authenticationstrength.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrength?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/riskuseractivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/riskuseractivity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskuseractivity?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-14465) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-01-besiler-quarterlyOct2021/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112281918147324-14465%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-28T19%3A20%3A07Z&sr=b&sp=r&sig=PkzpiymLHWuOpRLq1T%2BIggJDplyokdPRJQ5BISdiwnE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-28 22:07 UTC, merged