m365certupdates to permissiongrantpolicy
microsoftgraph/microsoft-graph-docs pull request #14545
Opened 2021-10-08 05:23 UTC by arpitha-dhanapathi

PR:9114

2021-10-08 05:25 UTC, opbld32 commented
Docs Build status updates of commit _[6d84760](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d84760742ad384144d2dc2c42cd4802c32480a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110080523414899-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-08T05%3A25%3A19Z&sr=b&sp=r&sig=jU0D4%2FROe5kfJ8ceQULcal0xbSJhd2DTfX5IAUS5APE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-08 07:52 UTC, psignoret submitted a review, later dismissed
Looks good! I think the only thing that's missing is the changelog update and a couple minor suggestions below.

2021-11-03 20:53 UTC, arpitha-dhanapathi commented
@psignoret  - could you please review and signoff? Thanks.

2021-11-03 22:41 UTC, opbld31 commented
Docs Build status updates of commit _[2d69824](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d698241aee3b664d7261f21aa13a140e5f511e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111032239127480-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-04T22%3A41%3A50Z&sr=b&sp=r&sig=qikpZiqVketgd4y7Vx52T6ykcvuXr7UHnu8IkBaG148%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-04 21:45 UTC, opbld34 commented
Docs Build status updates of commit _[c3aa915](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3aa915709f904145545c99fe97cac88326aad7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111042143327482-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-05T21%3A45%3A33Z&sr=b&sp=r&sig=edA%2F%2BcfvsWfEBSLoemLRSvd0dAneomH90Pdm%2FBdsL4k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-04 23:12 UTC, opbld34 commented
Docs Build status updates of commit _[506623a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/506623a71c27c8851fd8dac08d47275ddf27d22b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111042310541578-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-05T23%3A12%3A53Z&sr=b&sp=r&sig=scmCTZmorcmpoakZ26SVguDfohJl1oDnTZPMMxzmc3E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-05 17:44 UTC, arpitha-dhanapathi reviewed
Made the changes

2021-11-05 17:47 UTC, arpitha-dhanapathi reviewed
reviewed and submitted changes

2021-11-05 17:54 UTC, opbld30 commented
Docs Build status updates of commit _[3c9c73f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c9c73f5055b9cc7a28cf9ca557d51d0f0504a9d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111051747193904-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-06T17%3A54%3A09Z&sr=b&sp=r&sig=Lz22otkViID7CO%2FG0A6fZxEjqxLMo0crUB9JSYM%2BUtI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-05 17:57 UTC, opbld31 commented
Docs Build status updates of commit _[bf79d28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf79d28c62b15462897ec8d4ab45458fe987e211)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111051751148498-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-06T17%3A57%3A01Z&sr=b&sp=r&sig=7q%2FQfJD9chTiXfZ0tNrhl6uMlOogui2txzmAnW98KkA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-05 18:03 UTC, arpitha-dhanapathi reviewed
reviewed and updated

2021-11-09 22:09 UTC, JarbasHorst requested changes

2021-11-09 22:09 UTC, JarbasHorst commented on api-reference/beta/resources/permissiongrantconditionset.md
> +    "clientApplicationsFromVerifiedPublisherOnly": false,
For consistency, the JSON representation should not contain examples. Please, replace "false" in both cases with "Boolean".

2021-11-09 22:09 UTC, JarbasHorst commented on api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md
> +The following is an example of the request to retrieve the **excludes** condition sets of the built-in permission grant policy `microsoft-application-admin`. This permission grant policy includes all
Before using acronyms, I recommend you to spell out the words first followed by the acronym in parentheses. In this case, you don't need an acronym, so I recommend you to only spell out AD. Suggested revision:

- ...permissions for Azure Active Directory Graph.

2021-11-09 22:09 UTC, JarbasHorst commented on changelog/Microsoft.DirectoryServices.json
> +      {
Your PR doesn't include this change. Please remove this entire changelog record.

2021-11-09 22:09 UTC, JarbasHorst commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **certifiedClientApplicationsOnly** property to [permissionGrantConditionSet](https://docs.microsoft.com/en-us/graph/api/resources/permissionGrantConditionSet?view
Please, add "the" before "[permissionGrantConditionSet]".

2021-11-09 23:27 UTC, arpitha-dhanapathi commented on api-reference/beta/api/permissiongrantpolicy-post-includes.md
> +### [HTTP](#tab/http)
the tabs (eg., (#tab/http)) weren't added separately by me. They were in the docs for the first example, which I copied over to create the second example. Should all of these be still removed?

2021-11-09 23:45 UTC, opbld31 commented
Docs Build status updates of commit _[dbd615e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dbd615e21902af58e8d5e46ee4829e64ca54e851)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111092343367002-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T23%3A45%3A18Z&sr=b&sp=r&sig=jeqA7KfMuCO4KNmY8WXfis%2BDvQc%2BhrPEjqhvBHWdxOA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-09 23:46 UTC, opbld31 commented
Docs Build status updates of commit _[5dba6b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5dba6b95e20975c4e6ac740f0e2a0e4f110063c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111092343479160-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T23%3A46%3A43Z&sr=b&sp=r&sig=UaB8GQ3MCxffaycoFv5tGtcbQTJRRoaeTJIk59QvrKk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-09 23:55 UTC, opbld31 commented
Docs Build status updates of commit _[6555cd2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6555cd21a29f9a227d46deb635d0fed5490cad4d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111092352446945-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T23%3A55%3A33Z&sr=b&sp=r&sig=GUcl5a%2FPls8BJtqFc5YluNkm%2B6WIIHlehuHuEhLbxXs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-10 21:22 UTC, JarbasHorst commented on changelog/Microsoft.DirectoryServices.json
> +      {
After some investigation with @arpitha-dhanapathi, we figured out that her PR introduces a JSON code that is well-formatted. GitHub understands this as a change and displays this changelog record as an addition.

For comparison, here the same changelog record from the main branch:


![MicrosoftTeams-image (21)](https://user-images.githubusercontent.com/26866873/141195408-a380e1ff-1ea6-41da-8fbc-829bb5da8974.png)

2021-11-10 21:51 UTC, opbld31 commented
Docs Build status updates of commit _[725c9a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/725c9a30b72853f97c0ef7d5c515077a64fd2fbe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111102149274171-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-11T21%3A51%3A11Z&sr=b&sp=r&sig=79xMxvlO73VXd2CRsDzm1EDiuIpUe5%2Bd2aNSDyWlYGI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-10 22:04 UTC, opbld31 commented
Docs Build status updates of commit _[7c7f436](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c7f436f79b0484181a901d08c0a19633bda858c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111102203093712-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-11T22%3A04%3A48Z&sr=b&sp=r&sig=8sopSc4wZ86BcBH2jHTkJQcKxrOak3le1k6lXDe6ZqU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-10 22:07 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-11-10 22:15 UTC, JarbasHorst requested changes

2021-11-10 22:15 UTC, JarbasHorst commented on api-reference/beta/api/permissiongrantpolicy-post-includes.md
> +POST https://graph.microsoft.com/beta/policies/permissionGrantPolicies/{id}/includes
Please, replace the {id} placeholder with a real example. Please, apply this change also to HTTP request in Example 1.

2021-11-10 22:15 UTC, JarbasHorst commented on api-reference/beta/api/permissiongrantpolicy-list-excludes.md
> +The following is an example of the request to retrieve the **excludes** condition sets of the built-in permission grant policy `microsoft-application-admin`. This permission grant policy includes all
Please, replace "Direcotry" with "Directory".

2021-11-10 22:33 UTC, opbld31 commented
Docs Build status updates of commit _[1910c89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1910c8990c52d1dc3b2f6bd3719a1b93c2af788d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111102231280492-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-11T22%3A33%3A18Z&sr=b&sp=r&sig=Uwr7iyutBnJURermsor%2FLem%2F%2F2F2dVMSBIVTWYCJt8M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-10 23:55 UTC, opbld32 commented
Docs Build status updates of commit _[9c04969](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c04969dc3179e99b99ec12b3b479bee12275a4d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111102354141438-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-11T23%3A55%3A54Z&sr=b&sp=r&sig=kPy0bfxDQ1LNKfoFD1fXGqYqyCr6kKnrtKiJJK26h7s%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-11 21:44 UTC, opbld30 commented
Docs Build status updates of commit _[00a8e2f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/00a8e2f34ecd042ecd99bebdc5095907f22bd30f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111112142383633-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T21%3A44%3A19Z&sr=b&sp=r&sig=zAn0yOQ8SqgJ263W8uBAszWFsBnOLQRIxntLHe%2FA79s%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-11 23:35 UTC, opbld32 commented
Docs Build status updates of commit _[0bc8475](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0bc84752845cc2d02402954d49fc45e557625fe1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111112333265286-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T23%3A35%3A14Z&sr=b&sp=r&sig=GkayJJ5q7YmJYtjmOP2xJuRUIuSg1pBVMD3j%2BdraB%2Bo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 00:04 UTC, opbld32 commented
Docs Build status updates of commit _[fcf80e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fcf80e4a256ce55899f719d32339872ac67a5bfd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111120002299217-14545%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T00%3A04%3A33Z&sr=b&sp=r&sig=xdO4Hxhu9PHTtC%2BsFg2%2F5hr2KJKp%2BXE3sMsA%2BqXnAZQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 14:48 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-11-12 23:01 UTC, arpitha-dhanapathi reviewed
updated with all suggestions

2021-11-12 23:03 UTC, arpitha-dhanapathi reviewed
Reviewed and updated

2021-11-12 23:06 UTC, arpitha-dhanapathi commented
@Lauragra  - content review is complete by Jarba. Should I mark it as 'ready to merge'?

2021-11-12 23:47 UTC, Lauragra commented
> @Lauragra - content review is complete by Jarba. Should I mark it as 'ready to merge'?

Yes, please set ready to merge when the schema is released and the APIs are available to users.

2021-11-12 23:49 UTC, Lauragra approved these changes

2021-12-02 03:40 UTC, opbld34 commented
Docs Build status updates of commit _[cb9f4a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb9f4a88f5bb5c5fdd82291aa03a3dedbf884d77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/permissiongrantpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-get?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-excludes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/beta/resources/permissiongrantconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/beta/resources/permissiongrantconditionset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/permissiongrantconditionset?view=graph-rest-beta&branch=pr-en-us-14545) (graph-rest-beta) |
[api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-list-excludes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-list-excludes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[api-reference/v1.0/api/permissiongrantpolicy-post-includes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/api-reference/v1.0/api/permissiongrantpolicy-post-includes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/permissiongrantpolicy-post-includes?view=graph-rest-1.0&branch=pr-en-us-14545) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-m365certupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112020338004705-14545%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T03%3A40%3A20Z&sr=b&sp=r&sig=JYD9qVfIxXka2PXBbxMmpK2SejLx67vyY1UbgxieIlA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 03:45 UTC, merged