add api and resource pages for findTenantInformation
microsoftgraph/microsoft-graph-docs pull request #14559
Opened 2021-10-08 22:00 UTC by adimitui

2021-10-08 22:03 UTC, opbld33 commented
Docs Build status updates of commit _[7cc93ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7cc93ab41f74eb7ca12ed138937eb7453954d24f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-list-members.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-list-scopedrolemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-list-scopedrolemembers.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-post-administrativeunits.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-post-members.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-post-scopedrolemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-post-scopedrolemembers.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/allowedvalue-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/allowedvalue-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/allowedvalue-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/allowedvalue-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/allowedvalue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/allowedvalue-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/allowedvalue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/allowedvalue-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/allowedvalue-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/allowedvalue-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-appmanagementpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-appmanagementpolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-claimsmappingpolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-extensionproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-extensionproperties.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-homerealmdiscoverypolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-homerealmdiscoverypolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-memberof.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-owners.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-tokenissuancepolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-tokenissuancepolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-tokenlifetimepolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-applications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-post-applications.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-appmanagementpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-post-appmanagementpolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-post-claimsmappingpolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-extensionproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-post-extensionproperties.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-homerealmdiscoverypolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-post-homerealmdiscoverypolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-post-memberof.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-post-owners.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-tokenissuancepolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application- [...]

2021-10-15 13:49 UTC, mmcadamsms commented
Workload wiring PR is at: https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/5188288

2022-01-19 23:39 UTC, opbld34 commented
Docs Build status updates of commit _[7cc93ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7cc93ab41f74eb7ca12ed138937eb7453954d24f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-list-members.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-list-scopedrolemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-list-scopedrolemembers.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-post-administrativeunits.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-post-members.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-post-scopedrolemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-post-scopedrolemembers.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/administrativeunit-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/allowedvalue-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/allowedvalue-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/allowedvalue-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/allowedvalue-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/allowedvalue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/allowedvalue-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/allowedvalue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/allowedvalue-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/allowedvalue-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/allowedvalue-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-appmanagementpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-appmanagementpolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-claimsmappingpolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-extensionproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-extensionproperties.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-homerealmdiscoverypolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-homerealmdiscoverypolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-memberof.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-owners.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-tokenissuancepolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-tokenissuancepolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list-tokenlifetimepolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-applications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-post-applications.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-appmanagementpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-post-appmanagementpolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-post-claimsmappingpolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-extensionproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-post-extensionproperties.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-homerealmdiscoverypolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-post-homerealmdiscoverypolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-post-memberof.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application-post-owners.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-post-tokenissuancepolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/doc-stubs/api/application- [...]

2022-01-26 22:10 UTC, opbld31 commented
Docs Build status updates of commit _[4e59588](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e59588b17141ecfe81c5e9cf16d2dbcfe35671b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-699fbe70)

<a id="699fbe70"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262209499142-14559%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T22%3A10%3A54Z&sr=b&sp=r&sig=SHKRnzjFiQ5Flo712Uz0M7mR41Z5sSilVSRtRhP47p0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 13:29 UTC, opbld34 commented
Docs Build status updates of commit _[a3d3dd5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a3d3dd5ae901963637de832a85e81470c70826f7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5f83e893)

<a id="5f83e893"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202031328200514-14559%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-06T13%3A29%3A51Z&sr=b&sp=r&sig=fRuKj8aFgLkMJHIiG9I%2BFavC0HTgNw0Jy6wRD2Yndbg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 06:00 UTC, opbld33 commented
Docs Build status updates of commit _[a126d17](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a126d171681df0d24fc6928aa935e6fb6e577303)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantrelationships-findtenantinformationbydomainname.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationships-findtenantinformationbydomainname.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationships-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationships-findtenantinformationbytenantid?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/resources/tenantinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantinformation?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/resources/tenantrelationships.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantrelationships?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationships-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices-append.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/changelog/Microsoft.DirectoryServices-append.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202040558260395-14559%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T06%3A00%3A33Z&sr=b&sp=r&sig=VQEO6dyvFp57PlHAjocn2q6XhmCGV%2B9AtDne0B4TEGY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 17:08 UTC, FaithOmbongi requested changes
Thank you @adimitui for your work on this PR. I've requested for minor changes and the following:
- File name fix: tenantrelationships.md => **tenantrelationship.md** (singular)
- I see you're introducing a new permission, `CrossTenantInformation.ReadBasic.All`. Please document it in the permissions reference and add a changelog for the permission.
- Please delete the changelog/Microsoft.DirectoryServices-append.json file from your branch. The correct changelog file where you'll add your changelog record should be the existing file named **changelog/Microsoft.DirectoryServices.json**
- Please add the changelog (starting from Line 3 of the changelog/Microsoft.DirectoryServices.json file), you can copy it from your CSDL PR. It should have 3 objects. I suggest the following enhanced descriptions for the two resources.
  - Added the [tenantRelationship](link) resource type and related methods. This resource exposes the methods that can be used to retrieve basic identification information about Azure AD tenants.
   - Added the [tenantInformation](link) resource type. This complex type exposes the basic properties used to identify an Azure AD tenant.
   

The other third object is for the new permission. Please see the permissions reference for guidance.

**NOTE:** I see that the `CrossTenantInformation.ReadBasic.All` permission is still currently under the final deployment phase. Please set this PR to ready to merge only after the permission has been deployed and is visible on the Azure portal.

Q: I see 3 versions of the tenantRelationship entity:
Verion 1: Is in the public metadata as per the screenshot. It has a managedTenants r/ship.
<img width="704" alt="image" src="https://user-images.githubusercontent.com/14026935/152571252-d63d6154-d921-4c68-8da7-0668fd442d4f.png">
Version 2 is in the PPE environment and is named tenantRelationshipRoot and has no r/ships
Version 3 is in the Prod environment CSDL and it has multiTenantCollaboration and multiTenantCollaborationAdmissions r/ships

Could you reach out internally to shed light on which is the accurate

2022-02-04 17:36 UTC, FaithOmbongi commented on api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md
> +Given a tenant ID, search for a tenant and read its [tenantInformation](../resources/tenantInformation.md).
Suggestion to cross-link to the cross-tenant access policy API.
```suggestion
Given a tenant ID, search for a tenant and read its [tenantInformation](../resources/tenantInformation.md). You can use this API to validate tenant information and use their **tenantId** to [configure cross-tenant B2B collaboration settings between you and the tenant](crosstenantaccesspolicyconfigurationpartner.md).
```

2022-02-04 17:37 UTC, FaithOmbongi commented on api-reference/beta/api/tenantrelationships-findtenantinformationbydomainname.md
> +Given a domain name, search for a tenant and read its [tenantInformation](../resources/tenantInformation.md).
Suggestion to cross-link to the cross-tenant access policy API
```suggestion
Given a domain name, search for a tenant and read its [tenantInformation](../resources/tenantInformation.md). You can use this API to validate tenant information and use their **tenantId** to [configure cross-tenant B2B collaboration settings between you and the tenant](crosstenantaccesspolicyconfigurationpartner.md).
```

2022-02-14 09:47 UTC, adimitui commented on api-reference/beta/resources/tenantrelationships.md
> +---
Changed to **tenantRelationshipRoot** to match the PPE CSDL

2022-02-14 09:47 UTC, adimitui commented on api-reference/beta/resources/tenantrelationships.md
> +description: "Represents how external tenants interact with your tenant."
Great suggestion!

2022-02-14 09:49 UTC, adimitui commented on api-reference/beta/resources/tenantrelationships.md
> +Represents how external tenants interact with your tenant.
Great suggestion to make the **tenantInformation** complex type more discoverable

2022-02-14 09:52 UTC, adimitui commented on api-reference/beta/resources/tenantrelationships.md
> +}
I've changed everything to **tenantRelationshipRoot**. I've also updated the findTenantInformation API pages to reference the **tenantRelationshipRoot** rather than **tenantRelationships**.

I believe the **tenantRelationship** entity was a different entity created during a past PR for an M365 Lighthouse scenario where customers wanted the ability to list out all the managed tenants that a partner was managing. This is not the same entity that we're dealing with for the B2B Connect project.

2022-02-14 09:53 UTC, adimitui commented on api-reference/beta/toc.yml
> +              href: api/tenantrelationships-findtenantinformationbytenantid.md
Great suggestion! As recommended, I've removed the complex type

2022-02-14 09:54 UTC, adimitui commented on api-reference/beta/api/tenantrelationships-findtenantinformationbydomainname.md
> +title: "findTenantInformationByDomainName"
Modified to include **tenantRelationshipRoot**

2022-02-14 09:54 UTC, adimitui commented on api-reference/beta/api/tenantrelationships-findtenantinformationbydomainname.md
> +# findTenantInformationByDomainName
Modified to include **tenantRelationshipRoot**

2022-02-14 09:55 UTC, adimitui commented on api-reference/beta/api/tenantrelationships-findtenantinformationbydomainname.md
> +Given a domain name, search for a tenant and read its [tenantInformation](../resources/tenantInformation.md).
Great suggestion. Changed!

2022-02-14 09:55 UTC, adimitui commented on api-reference/beta/api/tenantrelationships-findtenantinformationbydomainname.md
> +None.
Changed!

2022-02-14 09:56 UTC, adimitui commented on api-reference/beta/api/tenantrelationships-findtenantinformationbydomainname.md
> +  "name": "get_tenantrelationshiproot"
Changed to **_tenantrelationshiprootthis._findtenantinformationbydomainname**

2022-02-14 09:57 UTC, adimitui commented on api-reference/beta/api/tenantrelationships-findtenantinformationbydomainname.md
> +  "@odata.type": "Microsoft.DirectoryServices.tenantRelationshipRoot"
Changed!

2022-02-14 09:58 UTC, adimitui commented on api-reference/beta/api/tenantrelationships-findtenantinformationbydomainname.md
> +}
Changed!

2022-02-14 09:58 UTC, adimitui commented on api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md
> +title: "findTenantInformationByTenantId"
Changed to include **tenantRelationshipRoot**

2022-02-14 09:58 UTC, adimitui commented on api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md
> +# findTenantInformationByTenantId
Changed to include **tenantRelationshipRoot**

2022-02-14 09:58 UTC, adimitui commented on api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md
> +Given a tenant ID, search for a tenant and read its [tenantInformation](../resources/tenantInformation.md).
Great suggestion! Changed

2022-02-14 09:58 UTC, adimitui commented on api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md
> +None.
Changed!

2022-02-14 09:59 UTC, adimitui commented on api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md
> +  "name": "get_tenantrelationshiproot"
Changed to **tenantrelationshipROOTthis.findtenantinformationbytenantid**

2022-02-14 09:59 UTC, adimitui commented on api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md
> +GET https://graph.microsoft.com/beta/tenantRelationships/findTenantInformationByTenantId(tenantId='tenant-id-value')
Changed!

2022-02-14 09:59 UTC, adimitui commented on api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md
> +  "@odata.type": "Microsoft.DirectoryServices.tenantRelationshipRoot"
Changed!

2022-02-14 10:00 UTC, adimitui commented on api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md
> +}
Changed!

2022-02-14 10:00 UTC, adimitui commented on api-reference/beta/resources/tenantinformation.md
> +description: "Information about your tenant that can be displayed to users from external tenants, without the external tenants needing to form a relationship with your tenant."
Changed!

2022-02-14 10:01 UTC, adimitui commented on api-reference/beta/resources/tenantinformation.md
> +|tenantId|String|ID of your tenant.|
Changed!

2022-02-14 10:01 UTC, adimitui commented on api-reference/beta/resources/tenantinformation.md
> +  "@odata.type": "microsoft.graph.tenantRelationshipRoot",
Changed!

2022-02-14 10:02 UTC, adimitui commented on api-reference/beta/resources/tenantrelationships.md
> +# tenantRelationships resource type
Changed to **tenantRelationshipRoot**

2022-02-14 10:10 UTC, opbld30 commented
Docs Build status updates of commit _[b8e84c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8e84c7cfe94b1ea3ec36011216f4ea6bb3cefe5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2c323bb1)

<a id="2c323bb1"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202141009565410-14559%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T10%3A10%3A35Z&sr=b&sp=r&sig=mgaIlhuOMkCxI5YjpfPnceeuLoKy%2BzQL%2FyWvqZxCcAo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 10:14 UTC, opbld32 commented
Docs Build status updates of commit _[f39d2c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f39d2c2cf432968d728947933aee2755cd04b45e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bf51bbb7)

<a id="bf51bbb7"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202141014250262-14559%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T10%3A14%3A51Z&sr=b&sp=r&sig=YQx5rYUUF9vAVoDyy8W4X2FQGafJadKW6uTB%2FrNTWKE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 10:36 UTC, opbld32 commented
Docs Build status updates of commit _[dd045ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd045ed203723ba8eecf49d37711a4f7a4199127)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-23acda9c)

<a id="23acda9c"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202141035235326-14559%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T10%3A35%3A59Z&sr=b&sp=r&sig=tdSoG3tGtEBXgriyeUzZhp1t%2FWXIXMkaJSg714A%2FA24%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 20:41 UTC, FaithOmbongi requested changes
Hi @adimitui, a few minor changes:
- Left over file name changes: Because you've changed tenantRelationship resource name to **tenantRelationshipRoot** , the file name prefixes for the two functions should now be **tenantrelationshiproot-findtenantinformationbytenantid.md** and **tenantrelationshiproot-findtenantinformationbytenantid.md** - All lowercase.
- I'm worried about your changelogs (plus the one in the shared user profiles PR). Let's investigate why.

The major gap is the missing permissions. I shared some requirements for this internally.

2022-02-16 20:41 UTC, FaithOmbongi commented on api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md
> +---
File name changes because it's now tenantrelationshiproot

2022-02-16 20:41 UTC, FaithOmbongi commented on api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md
> +Given a tenant ID, search for a tenant and read its [tenantInformation](../resources/tenantInformation.md). You can use this API to validate tenant information and use their **tenantId** to [configur
Just a side note for future action: We'll also link to the shared user profiles API as another scenario that may be supported by this function. I think given that this API will be merged before the shared user profiles one, we can come back to it and add that info later.

2022-02-16 20:41 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +            href: api/tenantrelationships-findtenantinformationbytenantid.md
To reflect the file name changes
```suggestion
          href: resources/tenantrelationshiproot.md
          items:
          - name: Find by domain name
            href: api/tenantrelationshiproot-findtenantinformationbydomainname.md
          - name: Find by tenant ID
            href: api/tenantrelationshiproot-findtenantinformationbytenantid.md
```

2022-03-04 00:45 UTC, opbld30 commented
Docs Build status updates of commit _[efb4790](https://github.com/microsoftgraph/microsoft-graph-docs/commits/efb479079e599b6af0620a5518a0dcbd2ff64c57)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a73ea287)

<a id="a73ea287"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203040044538510-14559%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T00%3A45%3A28Z&sr=b&sp=r&sig=WPfJS8Uwkf7yhHprvAKffgZ9C3%2F%2FeNuBtC8MGrsXijE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-07 18:36 UTC, opbld31 commented
Docs Build status updates of commit _[12119a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12119a1350816c300f43768edca180c47d0b1e31)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b77c67e1)

<a id="b77c67e1"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203071836064389-14559%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-07T18%3A36%3A44Z&sr=b&sp=r&sig=eS%2BByYjgaw%2B30ebqbcFf031KWwEFfwF5Ui0LnaSCw8c%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-07 18:43 UTC, opbld34 commented
Docs Build status updates of commit _[cd6c19e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd6c19e7b6c887e7553dc5bf4bce2e84e698cb69)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantrelationships-findtenantinformationbydomainname.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationships-findtenantinformationbydomainname.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationships-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationships-findtenantinformationbytenantid?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/resources/tenantinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantinformation?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantrelationshiproot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/resources/tenantrelationshiproot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantrelationshiproot?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203071841207613-14559%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-07T18%3A43%3A32Z&sr=b&sp=r&sig=ASye%2BE3LNaCMKEwOznr69gcBjAS%2FS5W0MFUs0fhRzYI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-07 18:46 UTC, opbld34 commented
Docs Build status updates of commit _[f14bf62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f14bf624fd767f500754c9c7e854f348605905c2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationships-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8ab4057b)
[api-reference/beta/api/tenantrelationships-findtenantinformationbydomainname.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationships-findtenantinformationbydomainname.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationships-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationships-findtenantinformationbytenantid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationships-findtenantinformationbytenantid?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/resources/tenantinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantinformation?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantrelationshiproot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/resources/tenantrelationshiproot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantrelationshiproot?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-8ab4057b"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/toc.yml)
 - **Line 11563, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/tenantrelationships.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203071844032296-14559%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-07T18%3A46%3A40Z&sr=b&sp=r&sig=G0Vg6mKjWcv14BWQAA7dUPYkUYVqZOOyJr3v4jTgGsc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-07 18:54 UTC, FaithOmbongi requested changes
Hi @adimitui ,

Bumping up the pending fixes from the last review:
- Most file names need fixing. All instances of tenantrelationships should now be tenantrelationshiproot as per your previous initial confirmation - change required in the Methods table, file names, and TOC
- Fix TOC links to new file names
- Document the new permission in the [permissions reference](https://docs.microsoft.com/en-us/graph/permissions-reference) doc. You can add a section called "**Tenant information permissions**".

2022-03-14 12:46 UTC, opbld30 commented
Docs Build status updates of commit _[220bd09](https://github.com/microsoftgraph/microsoft-graph-docs/commits/220bd09d8dd3eaeb54c9d717877c9b5baa53ee3f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationshiproot-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d876f0a3)
[api-reference/beta/api/tenantrelationshiproot-findtenantinformationbydomainname.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationshiproot-findtenantinformationbydomainname.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationshiproot-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationshiproot-findtenantinformationbytenantid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationshiproot-findtenantinformationbytenantid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationshiproot-findtenantinformationbytenantid?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/resources/tenantinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantinformation?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantrelationshiproot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/resources/tenantrelationshiproot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantrelationshiproot?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-d876f0a3"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/toc.yml)
 - **Line 11607, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/tenantrelationships.md'.`````
 - **Line 11610, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/tenantrelationships-findtenantinformationbydomainname.md'.`````
 - **Line 11612, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/tenantrelationships-findtenantinformationbytenantid.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203141244239414-14559%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-14T12%3A46%3A35Z&sr=b&sp=r&sig=3Fbvf2WsWdbbkYLEmo3DEC9kVM%2F959CTJmss0GIPXhs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-14 13:24 UTC, opbld34 commented
Docs Build status updates of commit _[20ae244](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20ae24489c6afa1503d4721ba1d2d759b7df8d84)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantrelationshiproot-findtenantinformationbydomainname.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationshiproot-findtenantinformationbydomainname.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationshiproot-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationshiproot-findtenantinformationbytenantid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationshiproot-findtenantinformationbytenantid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationshiproot-findtenantinformationbytenantid?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/resources/tenantinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantinformation?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantrelationshiproot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/resources/tenantrelationshiproot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantrelationshiproot?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationshiproot-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14559) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203141322491993-14559%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-14T13%3A24%3A51Z&sr=b&sp=r&sig=5oA9fXaQik1m3VNaESwDwvfIt0EviqUHgEwNgj3zbfM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-16 09:30 UTC, opbld30 commented
Docs Build status updates of commit _[dcb189e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dcb189e5a6a2bd36d1a82a5e7ed07451a2ab6f68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantrelationshiproot-findtenantinformationbydomainname.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationshiproot-findtenantinformationbydomainname.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationshiproot-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationshiproot-findtenantinformationbytenantid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationshiproot-findtenantinformationbytenantid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationshiproot-findtenantinformationbytenantid?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/resources/tenantinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantinformation?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantrelationshiproot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/resources/tenantrelationshiproot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantrelationshiproot?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationshiproot-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14559) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203160928544275-14559%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-16T09%3A30%3A51Z&sr=b&sp=r&sig=6PXNG8zmbDZvewC7CnJzsrfr7EfSArYf3mXtbTQ0fIo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-16 09:38 UTC, FaithOmbongi reviewed
Hi @adimitui, LGTM!
It's ready for approval but I'll hold off the approval and content review complete label until the schema is released. This is because we had the issue with tenantRelationship being defined 3 separate ways through 3 different schema update PRs. This hold-off will help us confirm that the schema that's published is as per these docs and ensure in-sync docs and schema.

Otherwise, no more changes are required in this PR.

2022-04-14 20:28 UTC, CelesteDG commented
Tagging @adimitui

2022-06-08 02:00 UTC, jkdouglas commented
@FaithOmbongi - can we publish this PR? The MS Graph schema for this api is public.

2022-06-08 02:03 UTC, opbld31 commented
Docs Build status updates of commit _[2d3c2fb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d3c2fbf4b0d0a46312c6ac563473acd2bd4f7c1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-e10f00f8)

<a id="0817dce4456c16725d5333633847d38f-e10f00f8"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 11868, Column 11**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206080201359064-14559/BuildReport?accessString=bc8f76693bfa8cb5d89c7bd57f879eed1d18f083290e71c58d0b641f2a9e25cd).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-08 02:10 UTC, opbld32 commented
Docs Build status updates of commit _[f051f85](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f051f853e325d70d5c94baef8a70bc9b2e910557)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantrelationshiproot-findtenantinformationbydomainname.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantrelationshiproot-findtenantinformationbydomainname.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationshiproot-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationshiproot-findtenantinformationbytenantid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantrelationshiproot-findtenantinformationbytenantid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationshiproot-findtenantinformationbytenantid?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantinformation?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantrelationshiproot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tenantrelationshiproot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantrelationshiproot?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationshiproot-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14559) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206080207385495-14559/BuildReport?accessString=c2da1ee1bb29fbf48dbf4ca60d57671bf183b7dfc61f04371e32c6de527c4926).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-08 06:58 UTC, FaithOmbongi commented
Hi @jkdouglas - I see the schema that's public still differs from this PR. I raised this concern during the initial PR review and subsequent re-review and there was an expectation that there's a different schema in the release pipeline that would map to this PR. Let me check in with you internally to discuss this.

2022-06-30 00:17 UTC, opbld32 commented
Docs Build status updates of commit _[b3d7b17](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3d7b17f6e023d7774c938e380ed1105f93dd58a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fca50ef6)

<a id="fca50ef6"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206300016319667-14559/BuildReport?accessString=854e3b2a52ae6729e8754d1df39fffe69cad6e0b2193329dc2bd82f982534acb).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 14:38 UTC, opbld31 commented
Docs Build status updates of commit _[d75cbbd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d75cbbddacec760bc880e332a1e71de7098af990)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-659b1392)

<a id="659b1392"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207211436298180-14559/BuildReport?accessString=b6ba91e9ca50b5b599b696acb9836c62eb12a7d81cb25c0d7a794ced5e46a14b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 14:43 UTC, opbld31 commented
Docs Build status updates of commit _[d02b2b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d02b2b3995f71f37139ae649756f97b1b9175308)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantrelationship-findtenantinformationbydomainname.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationship-findtenantinformationbydomainname.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-findtenantinformationbytenantid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationship-findtenantinformationbytenantid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-findtenantinformationbytenantid?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/resources/tenantinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantinformation?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14559) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207211440348188-14559/BuildReport?accessString=2834fe53041e2d48ef5251ed556ec6808309133c66628b862061ba055e406450).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 15:06 UTC, opbld34 commented
Docs Build status updates of commit _[2766a36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2766a3609913e89e9509f36f5c9468503e3e0954)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantrelationship-findtenantinformationbydomainname.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationship-findtenantinformationbydomainname.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-findtenantinformationbytenantid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationship-findtenantinformationbytenantid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-findtenantinformationbytenantid?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/resources/tenantinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantinformation?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14559) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207211504572776-14559/BuildReport?accessString=36438af643fa517749ecb5938006014d73d26951165d4737b903a408f81b55d5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 15:08 UTC, FaithOmbongi approved these changes

2022-07-21 15:11 UTC, opbld33 commented
Docs Build status updates of commit _[08c6000](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08c60005b4de78bca90245b37d75744ce5ee6b72)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/tenantrelationship-findtenantinformationbydomainname.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationship-findtenantinformationbydomainname.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/api/tenantrelationship-findtenantinformationbytenantid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/api/tenantrelationship-findtenantinformationbytenantid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-findtenantinformationbytenantid?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/resources/tenantinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/resources/tenantinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantinformation?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantrelationship-findtenantinformationbydomainname?view=graph-rest-beta&branch=pr-en-us-14559) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-08-adimitui-find-tenant-info/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14559) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207211507280738-14559/BuildReport?accessString=1462dd849fe07cc092498711815762333469a44224d9015a050b2b7571058e7a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 22:19 UTC, merged