Convert Exchange and Microsoft Teams usage reports APIs to weak type
microsoftgraph/microsoft-graph-docs pull request #14672
Opened 2021-10-20 07:19 UTC by kszb

2021-10-20 07:21 UTC, opbld31 commented
Docs Build status updates of commit _[2bb8ebd](https://github.com/kszb/microsoft-graph-docs/commits/2bb8ebd12fe6a608c9ed84893b91157aa2466bf2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getemailactivitycounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivitycounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivitycounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailactivityusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivityusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailactivityuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivityuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageappsusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageappsusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageappsusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageversionsusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageversionsusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageversionsusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagedetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagedetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagemailboxcounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagemailboxcounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagemailboxcounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagequotastatusmailboxcounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagequotastatusmailboxcounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagequotastatusmailboxcounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagestorage.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagestorage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagestorage?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagedistributiontotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagedistributiontotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagedistributiontotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagedistributionusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagedistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagedistributionusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagetotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagetotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagetotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusageusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusageusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusageusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusageuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitycounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitycounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivitycounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitydistributiontotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitydistributiontotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivitydistributiontotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitydistributionusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitydistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsus [...]

2021-10-20 08:19 UTC, opbld34 commented
Docs Build status updates of commit _[784ee00](https://github.com/kszb/microsoft-graph-docs/commits/784ee00b816afdea8bbbd33e03f9a295f1a89b69)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getemailactivitycounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivitycounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivitycounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailactivityusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivityusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailactivityuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivityuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageappsusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageappsusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageappsusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageversionsusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageversionsusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageversionsusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagedetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagedetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagemailboxcounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagemailboxcounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagemailboxcounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagequotastatusmailboxcounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagequotastatusmailboxcounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagequotastatusmailboxcounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagestorage.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagestorage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagestorage?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagedistributiontotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagedistributiontotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagedistributiontotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagedistributionusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagedistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagedistributionusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagetotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagetotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagetotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusageusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusageusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusageusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusageuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitycounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitycounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivitycounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitydistributiontotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitydistributiontotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivitydistributiontotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitydistributionusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitydistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsus [...]

2021-11-08 21:51 UTC, JarbasHorst requested changes

2021-11-08 21:51 UTC, JarbasHorst commented on changelog/Microsoft.O365Reporting.json
> +		  "Description": "Update JSON return type of [getemailactivityuserdetail](https://docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityuserdetail?view=graph-rest-beta) API to stream.",
GLOBAL: Please update the value of the "Description" property for all method entries in the changelog.

Please,

- replace Update with Updated
- add "the" before JSON return type
- add "the" before the API name, for example, "the [getEmailActivityUserDetail]"
- note that entity names in Microsoft Graph are lower camel case, so getemailactivityuserdetail in this case should be getEmailActivityUserDetail

Suggested revision,

- Updated the JSON return type of the [getEmailActivityUserDetail](https://docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityuserdetail?view=graph-rest-beta) API to stream.

2021-11-09 06:10 UTC, opbld34 commented
Docs Build status updates of commit _[24f1617](https://github.com/kszb/microsoft-graph-docs/commits/24f1617eb9ae91dd1a36041aca32b7ae5257dbe2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getemailactivitycounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivitycounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivitycounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailactivityusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivityusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailactivityuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivityuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageappsusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageappsusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageappsusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageversionsusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageversionsusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageversionsusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagedetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagedetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagemailboxcounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagemailboxcounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagemailboxcounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagequotastatusmailboxcounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagequotastatusmailboxcounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagequotastatusmailboxcounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagestorage.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagestorage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagestorage?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagedistributiontotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagedistributiontotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagedistributiontotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagedistributionusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagedistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagedistributionusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagetotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagetotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagetotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusageusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusageusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusageusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusageuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitycounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitycounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivitycounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitydistributiontotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitydistributiontotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivitydistributiontotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitydistributionusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitydistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsus [...]

2021-11-09 06:25 UTC, kszb commented on changelog/Microsoft.O365Reporting.json
> +		  "Description": "Update JSON return type of [getemailactivityuserdetail](https://docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityuserdetail?view=graph-rest-beta) API to stream.",
Updated.

2021-11-09 20:41 UTC, JarbasHorst requested changes

2021-11-09 20:41 UTC, JarbasHorst commented on changelog/Microsoft.O365Reporting.json
> +		  "ChangedApiName": "getemailactivityuserdetail",
GLOBAL: Please update the values of the "ChangedApiName" and "Target" properties for all method entries in the changelog. 

Currently, we don't show the values of the properties ChangedApiName and Target in the UI but that can change in the future. Hence, please fix these values to be lower camel case, for example, getemailactivityuserdetail in this case should be getEmailActivityUserDetail. Suggested revision:

```json
"ChangedApiName": "getEmailActivityUserDetail",
...
"Target": "getEmailActivityUserDetail"
```

2021-11-15 06:48 UTC, kszb commented on changelog/Microsoft.O365Reporting.json
> +		  "ChangedApiName": "getemailactivityuserdetail",
Fixed

2021-11-15 06:48 UTC, opbld34 commented
Docs Build status updates of commit _[5719210](https://github.com/kszb/microsoft-graph-docs/commits/5719210a098b7c51bc9938670a6c729461a25a40)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getemailactivitycounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivitycounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivitycounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailactivityusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivityusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailactivityuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivityuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageappsusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageappsusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageappsusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageversionsusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageversionsusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageversionsusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagedetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagedetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagemailboxcounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagemailboxcounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagemailboxcounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagequotastatusmailboxcounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagequotastatusmailboxcounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagequotastatusmailboxcounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagestorage.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagestorage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagestorage?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagedistributiontotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagedistributiontotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagedistributiontotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagedistributionusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagedistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagedistributionusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagetotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagetotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagetotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusageusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusageusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusageusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusageuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitycounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitycounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivitycounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitydistributiontotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitydistributiontotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivitydistributiontotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitydistributionusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitydistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsus [...]

2021-11-15 20:30 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-11-17 03:05 UTC, Lauragra approved these changes

2021-11-17 03:07 UTC, opbld34 commented
Docs Build status updates of commit _[0b90845](https://github.com/kszb/microsoft-graph-docs/commits/0b90845b4864aa77650ec7b90e15c1777b8a467c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getemailactivitycounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivitycounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivitycounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailactivityusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivityusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailactivityuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivityuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageappsusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageappsusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageappsusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageversionsusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageversionsusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageversionsusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagedetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagedetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagemailboxcounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagemailboxcounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagemailboxcounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagequotastatusmailboxcounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagequotastatusmailboxcounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagequotastatusmailboxcounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagestorage.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagestorage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagestorage?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagedistributiontotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagedistributiontotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagedistributiontotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagedistributionusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagedistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagedistributionusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagetotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagetotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagetotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusageusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusageusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusageusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusageuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitycounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitycounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivitycounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitydistributiontotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitydistributiontotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivitydistributiontotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitydistributionusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitydistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsus [...]

2021-11-17 03:09 UTC, opbld31 commented
Docs Build status updates of commit _[0b90845](https://github.com/kszb/microsoft-graph-docs/commits/0b90845b4864aa77650ec7b90e15c1777b8a467c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getemailactivitycounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivitycounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivitycounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailactivityusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivityusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailactivityuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailactivityuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageappsusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageappsusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageappsusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getemailappusageversionsusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getemailappusageversionsusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getemailappusageversionsusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagedetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagedetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagemailboxcounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagemailboxcounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagemailboxcounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagequotastatusmailboxcounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagequotastatusmailboxcounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagequotastatusmailboxcounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getmailboxusagestorage.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getmailboxusagestorage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagestorage?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagedistributiontotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagedistributiontotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagedistributiontotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagedistributionusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagedistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagedistributionusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusagetotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusagetotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusagetotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusageusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusageusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusageusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsdeviceusageuserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusageuserdetail?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitycounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitycounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivitycounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitydistributiontotalusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitydistributiontotalusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivitydistributiontotalusercounts?view=graph-rest-beta&branch=pr-en-us-14672) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getteamsuseractivitydistributionusercounts.md](https://github.com/kszb/microsoft-graph-docs/blob/o365reporting_weaktype0/api-reference/beta/api/reportroot-getteamsuseractivitydistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getteamsus [...]

2021-11-17 03:11 UTC, merged