[Azure AD roles] Devices In AU support [beta]
microsoftgraph/microsoft-graph-docs pull request #14685
Opened 2021-10-20 23:57 UTC by DougKirschner

2021-10-21 00:00 UTC, opbld31 commented
Docs Build status updates of commit _[0216888](https://github.com/microsoftgraph/microsoft-graph-docs/commits/021688804be9276e33ee41c31289a425f25d4009)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-6860a8fd)
[api-reference/beta/api/administrativeunit-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-list-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-6860a8fd"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/toc.yml)
 - **Line 9514, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110202357564423-14685%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-21T00%3A00%3A23Z&sr=b&sp=r&sig=xdGoi7C%2FVazw9N2SSUArRVopsJr8%2B41WKxhbYGGD93k%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-21 00:02 UTC, opbld32 commented
Docs Build status updates of commit _[80307c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80307c17ca7c231ff94c2ae2578881fec16241ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-db28247b)
[api-reference/beta/api/administrativeunit-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-list-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-db28247b"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/toc.yml)
 - **Line 9514, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110210000152704-14685%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-21T00%3A02%3A40Z&sr=b&sp=r&sig=gs7iTRDGxTvDJx8YUrzn0ms%2BZGn8ImiNLG%2BdRhADu78%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-01 05:35 UTC, FaithOmbongi requested changes
My apologies @DougKirschner , this slipped from my mind.

- Shared a proposed change for the changelog.
- Also, update the [administrativeUnit](https://docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta) resource and add references to devices in the opening line, description of methods, and description of relationships.
- Add a reference to administrativeUnits in the [device](https://docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta) resource: List memberOf description in the methods table, and the memberOf relationship.

2021-11-01 05:35 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      },
Proposed change
```suggestion
      {
        "Id": "e34aceeb-8c4b-430a-ab0e-521201013853",
        "ApiChange": "Method",
        "ChangedApiName": "memberOf",
        "ChangeType": "Addition",
        "Description": "Added `administrativeUnit` as a supported return type of the [List memberOf](https://docs.microsoft.com/en-us/graph/api/device-list-memberOf?view=graph-rest-beta) method of the device resource.",
        "Target": "memberOf"
      },
```

2021-11-01 05:35 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      }
Proposed change. Replacing with a single object to cover all CRUD methods.
```suggestion
      {
        "Id": "e34aceeb-8c4b-430a-ab0e-521201013853",
        "ApiChange": "Method",
        "ChangedApiName": "device",
        "ChangeType": "Addition",
        "Description": "Added `device` as a supported resource type of the [Get member](https://docs.microsoft.com/en-us/graph/api/administrativeunit-get-members), [List members](https://docs.microsoft.com/en-us/graph/api/administrativeunit-list-members?view=graph-rest-beta), [Add member](https://docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta), and [Remove member](https://docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta) methods of the [administrativeUnit](https://docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta) resource.",
        "Target": "administrativeUnit"
      }
```

2021-11-03 05:28 UTC, opbld30 commented
Docs Build status updates of commit _[a581a07](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a581a07dc73e0e53fb14a8441e88b5806229818f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-list-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-list-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) | [Details](#user-content-b5cc897614182d0e26e831feb3c67343-39fe6f12)
[api-reference/beta/api/administrativeunit-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="b5cc897614182d0e26e831feb3c67343-39fe6f12"></a>
### [api-reference/beta/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-list-members.md)
 - **Line 38, Column 51**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/query-parameters' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 38, Column 51**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/query-parameters' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111030526279302-14685%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-04T05%3A28%3A28Z&sr=b&sp=r&sig=VgwjErCAvEAwNU7l826agvW58Wl6CVHe69llhRcckKY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-03 05:30 UTC, opbld34 commented
Docs Build status updates of commit _[f803848](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8038481279ea4fe12729d356d79bc67333d047a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-list-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-list-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) | [Details](#user-content-b5cc897614182d0e26e831feb3c67343-3fbea08f)
[api-reference/beta/api/administrativeunit-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="b5cc897614182d0e26e831feb3c67343-3fbea08f"></a>
### [api-reference/beta/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-list-members.md)
 - **Line 38, Column 51**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/query-parameters' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 38, Column 51**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/query-parameters' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111030526431686-14685%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-04T05%3A30%3A09Z&sr=b&sp=r&sig=%2B33V%2BnHNaj5Q30EyVROYbH6svSrDjc4WVFQCzFe2Bus%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-03 05:45 UTC, opbld34 commented
Docs Build status updates of commit _[6da4e0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6da4e0da041a00d89000166f8fa2354644524092)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-list-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-list-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) | [Details](#user-content-b5cc897614182d0e26e831feb3c67343-c578c792)
[api-reference/beta/api/administrativeunit-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="b5cc897614182d0e26e831feb3c67343-c578c792"></a>
### [api-reference/beta/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-list-members.md)
 - **Line 38, Column 51**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/query-parameters' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 38, Column 51**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/query-parameters' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111030542518712-14685%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-04T05%3A45%3A00Z&sr=b&sp=r&sig=ycsh1VJqO%2FcAg2jkVuzXTwuB%2FAVVz%2BA5pR24vvIDBxQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-03 19:04 UTC, FaithOmbongi commented
@DougKirschner pushed a few commits to clean up other areas in docs & update the changelog date.

2021-11-03 19:05 UTC, FaithOmbongi approved these changes

2021-11-04 03:44 UTC, DougKirschner commented
Hi @FaithOmbongi putting this one back to "do not merge" so we can release simultaneously with the other device documents in a few weeks.  While the API is technically done, we can time the release so that the Azure AD portal UX rolls out along side the API docs.

2021-11-04 06:32 UTC, FaithOmbongi commented
@DougKirschner This is well noted.

2022-01-23 20:52 UTC, opbld34 commented
Docs Build status updates of commit _[3d6b67f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d6b67f36e22289bf659cae76b4fe1a1e3070a8d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) | [Details](#user-content-587d07eace2c4d640a05d29494f64382-4f588934)
[api-reference/beta/api/administrativeunit-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-list-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="587d07eace2c4d640a05d29494f64382-4f588934"></a>
### [api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-post-members.md)
 - **Line 152, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201232049493326-14685%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-23T20%3A52%3A11Z&sr=b&sp=r&sig=iDvUr7FWVu2Lbz7ca5AojoZsjXGNExADyF%2BUmlLKCXI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 08:28 UTC, opbld31 commented
Docs Build status updates of commit _[2c9cc07](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c9cc0734f8df5000ad613d31adb62f625643281)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) | [Details](#user-content-587d07eace2c4d640a05d29494f64382-fe5dda33)
[api-reference/beta/api/administrativeunit-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-list-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="587d07eace2c4d640a05d29494f64382-fe5dda33"></a>
### [api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-post-members.md)
 - **Line 152, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201250826206449-14685%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T08%3A28%3A31Z&sr=b&sp=r&sig=lTxnCIH8ty7v6ub15SiuQCaqnqvXwWlexOklFqqN%2Bn8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 23:36 UTC, DougKirschner commented
@FaithOmbongi  Ready to release this update as the rest of the feature is now rolling out.

2022-02-17 04:19 UTC, opbld32 commented
Docs Build status updates of commit _[660fcc1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/660fcc145a0e1d1925809d099dd01218f6832960)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) | [Details](#user-content-587d07eace2c4d640a05d29494f64382-7c457dd4)
[api-reference/beta/api/administrativeunit-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-list-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-beta&branch=pr-en-us-14685) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="587d07eace2c4d640a05d29494f64382-7c457dd4"></a>
### [api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dokirsch-audocupdates-deviceausupport/api-reference/beta/api/administrativeunit-post-members.md)
 - **Line 152, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202170417256839-14685%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-20T04%3A19%3A31Z&sr=b&sp=r&sig=Gq5pTGBnswPdFF%2BPZdwssZz%2FUWCU0Nku6QoaY4TRx3Y%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 04:30 UTC, merged