GA of educationUser.relatedContacts
microsoftgraph/microsoft-graph-docs pull request #14696
Opened 2021-10-21 18:48 UTC by mlafleur

2021-11-11 21:10 UTC, JarbasHorst requested changes

2021-11-11 21:10 UTC, JarbasHorst commented on api-reference/v1.0/resources/educationuser.md
>  > When using Delegated permission scopes, Graph will only return a limited set of properties: `id`, `primaryRole`, `accountEnabled`, `displayName`, `givenName`, `surname`, `userPrincipalName`, `userT
Please, avoid using gerunds where possible; in this case, you can change "corresponding" to "that corresponds". Suggested revision:

- The directory user that corresponds to this user.

2021-11-11 21:10 UTC, JarbasHorst commented on api-reference/v1.0/resources/educationuser.md
>  | onPremisesInfo       | [educationOnPremisesInfo](../resources/educationonpremisesinfo.md) | Additional information used to associate the Azure AD user with its Active Directory counterpart.
Before using acronyms, I recommend you to spell out the words first followed by the acronym in parentheses. Suggested revision:

- ...to associate the Azure Active Directory (AD) user with its AD counterpart.

2021-11-11 21:10 UTC, JarbasHorst commented on api-reference/v1.0/resources/relatedcontact.md
>  | Property      | Type                  | Description                                                                                                                               |
For consistency and to improve scanning, properties in the Properties table should be in alphabetical order. Please, alphabetize the list.

2021-11-11 21:10 UTC, JarbasHorst commented on api-reference/v1.0/resources/relatedcontact.md
>    "mobilePhone": "String",
An enum in a JSON representation should be displayed as String. Please, replace "contactRelationship" with "String".

2022-02-19 20:55 UTC, opbld31 commented
Docs Build status updates of commit _[230b2c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/230b2c2cfd2ccaae3ec4710c6b1a95266b63d7c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/educationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/api-reference/v1.0/resources/educationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationuser?view=graph-rest-1.0&branch=pr-en-us-14696) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/relatedcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/api-reference/v1.0/resources/relatedcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/relatedcontact?view=graph-rest-1.0&branch=pr-en-us-14696) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationRosteringAPIs.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/changelog/Microsoft.EducationRosteringAPIs.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202192053470877-14696%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-22T20%3A55%3A53Z&sr=b&sp=r&sig=hlTN%2B0gFqiweIJt1hFaW6HNnK7fo2VyopTl21Nx9PuM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-21 21:54 UTC, JarbasHorst commented on api-reference/v1.0/resources/educationuser.md
> +| id                   | String                                                             | Object identifier. Inherited from [entity](../resources/entity.md)
Please, add a period at the end of this description.

2022-02-21 21:54 UTC, JarbasHorst commented on api-reference/v1.0/resources/educationuser.md
> +| middleName           | String                                                             | The middle name of user.
Please, add "the" before "user".

2022-02-21 21:54 UTC, JarbasHorst commented on api-reference/v1.0/resources/educationuser.md
> +| preferredLanguage    | String                                                             | The preferred language for the user. Should follow ISO 639-1 Code; for example, "en-US".
1) Code doesn't need to be capitalized. Please, replace "Code" with "code".

2) For consistency, please add backticks to en-US => ...code; for example, \`en-US\`.

2022-02-21 21:54 UTC, JarbasHorst commented on api-reference/v1.0/resources/educationuser.md
>  ms.prod: "education"
1. For consistency with our resource topics, I recommend you to start the description with "Represents..." (line 14). In general, the description of resource topics shouldn't start with an imperative verb because the implied subject in resource topics is the resource. 

2. We apply bold formatting to property names; please update the formatting of id, primaryRole, student, and teacher.

2022-02-21 21:54 UTC, JarbasHorst commented on api-reference/v1.0/resources/relatedcontact.md
>  doc_type: resourcePageType
1. For consistency with our resource topics, I recommend you to start the description with "Represents..." (line 14). In general, the description of resource topics shouldn't start with an imperative verb because the implied subject in resource topics is the resource.

2022-02-21 21:54 UTC, JarbasHorst commented on api-reference/v1.0/resources/educationuser.md
> +| mail                 | String                                                             | The SMTP address for the user; for example, jeff@contoso.onmicrosoft.com. Read-Only. Supports `$filter`.
Please, apply backticks to jeff@contoso.onmicrosoft.com.

2022-02-21 21:54 UTC, JarbasHorst commented on api-reference/v1.0/resources/educationuser.md
> +| mailingAddress       | [physicalAddress](../resources/physicaladdress.md)                 | Mail address of user.
Please add "the" before "mail" and "user" => The mail address of the user.

2022-02-21 21:54 UTC, JarbasHorst commented on api-reference/v1.0/resources/educationuser.md
> +| relatedContacts      | [relatedContact] collection                                        | Related records related to the user. Read-only.
For clarity, please replace "related to" with "associated with" => Related records associated with the user...

2022-02-21 21:54 UTC, JarbasHorst commented on api-reference/v1.0/resources/educationuser.md
> +| showInAddressList    | Boolean                                                            | `True` if the Outlook Global Address List should contain this user otherwise, `false`. If not set, this w
Please, add a semicolon after "user" => ...contain this user; otherwise, `false`.

2022-02-21 21:54 UTC, JarbasHorst commented on api-reference/v1.0/resources/educationuser.md
> +| usageLocation        | String                                                             | A two-letter country code (ISO standard 3166). Required for users who will be assigned licenses due to a
For consistency, please add backticks to "US", "JP", and "GB". => ...Examples include: \`US\`, \`JP\`, and \`GB\`. Not...

2022-02-21 21:54 UTC, JarbasHorst commented on api-reference/v1.0/resources/educationuser.md
> +| userType             | String                                                             | A string value that can be used to classify user types in your directory, such as "Member" and "Guest". S
For consistency, please add backticks to "Member" and "Guest". => ...directory, such as \`Member\` and \`Guest\`.

2022-02-21 21:54 UTC, JarbasHorst commented on api-reference/v1.0/resources/educationuser.md
> +| assignments   | [educationAssignment](../resources/educationassignment.md) collection | Assignments belonging to the user.                |
Please, replace "belonging" with "that belongs"

2022-02-21 21:54 UTC, JarbasHorst commented on api-reference/v1.0/resources/relatedcontact.md
>  | relationship  | `contactRelationship` | Relationship to the user. Possible values are `parent`, `relative`, `aide`, `doctor`, `guardian`, `child`, `other`, `unknownFutureValue`. |
For consistency, please add a colon after "are" => ...Possible values are: `parent`...

2022-02-21 21:54 UTC, JarbasHorst commented on api-reference/v1.0/resources/relatedcontact.md
>    "accessConsent": true
1) Please, replace "true" with "Boolean".

2) Please show the properties here in alphabetical order.

2022-02-21 21:54 UTC, JarbasHorst commented on api-reference/v1.0/resources/educationuser.md
> +description: "Represetns a user in the system. This is an education-specific variant of the user with the same `id` that Microsoft Graph will return from the non-education-specific `/users` endpoint.
We don't apply any additional formatting to this description. For consistency, please remove the backticks from  `id`  and  `/users`.

2022-03-29 00:49 UTC, opbld33 commented
Docs Build status updates of commit _[94749c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94749c5b09c5626cad8c860215a63243c2db658f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/educationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/api-reference/v1.0/resources/educationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationuser?view=graph-rest-1.0&branch=pr-en-us-14696) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/relatedcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/api-reference/v1.0/resources/relatedcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/relatedcontact?view=graph-rest-1.0&branch=pr-en-us-14696) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationRosteringAPIs.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/changelog/Microsoft.EducationRosteringAPIs.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203290047550612-14696%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T00%3A49%3A55Z&sr=b&sp=r&sig=g5nLpLJ3uJ%2FV4FLU%2F6UGDZjfvn47FsA31NnQNMEQ5C0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 01:44 UTC, Lauragra commented on changelog/Microsoft.EducationRosteringAPIs.json
> +          "Description": "Added the [relatedContact](https://docs.microsoft.com/en-us/graph/api/resources/relatedContact?view=graph-rest-1.0) resource type.",
It looks like relatedContact and educationUser already exist in /v1.0 and this PR is making modifications to the existing topics. Please update the Changelog entry to reflect the API changes.

2022-03-30 01:48 UTC, opbld33 commented
Docs Build status updates of commit _[3ea2874](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ea28740fd9db994a62cf1730debd09b7b2e7851)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/educationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/api-reference/v1.0/resources/educationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationuser?view=graph-rest-1.0&branch=pr-en-us-14696) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/relatedcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/api-reference/v1.0/resources/relatedcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/relatedcontact?view=graph-rest-1.0&branch=pr-en-us-14696) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationRosteringAPIs.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/changelog/Microsoft.EducationRosteringAPIs.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203300146379796-14696%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T01%3A48%3A30Z&sr=b&sp=r&sig=k%2BlE7oXO%2FhaVnJwR0eYogkTnfol%2BaXOnk9zRPOOmeJY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 22:25 UTC, opbld32 commented
Docs Build status updates of commit _[f579940](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f57994038efa0447eebe2239a343ec6b51f8f8b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/educationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/api-reference/v1.0/resources/educationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationuser?view=graph-rest-1.0&branch=pr-en-us-14696) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/relatedcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/api-reference/v1.0/resources/relatedcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/relatedcontact?view=graph-rest-1.0&branch=pr-en-us-14696) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.EducationRosteringAPIs.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/changelog/Microsoft.EducationRosteringAPIs.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203302223566861-14696%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T22%3A25%3A29Z&sr=b&sp=r&sig=rJVz%2FMgw%2FeDygygiQuByxIyJ8OhHoCZVAvjDY6dd9pc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 03:01 UTC, Lauragra approved these changes

2022-03-31 03:03 UTC, opbld30 commented
Docs Build status updates of commit _[118c9ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/118c9ce6220320247c33bc79f8cece872f4b9bb9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/educationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/api-reference/v1.0/resources/educationuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationuser?view=graph-rest-1.0&branch=pr-en-us-14696) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/relatedcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/api-reference/v1.0/resources/relatedcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/relatedcontact?view=graph-rest-1.0&branch=pr-en-us-14696) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.EducationRosteringAPIs.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/contact-ga/changelog/Microsoft.EducationRosteringAPIs.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203310300129320-14696%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T03%3A03%3A32Z&sr=b&sp=r&sig=mWm%2FDrzZgjJRlHyAVsqW5vGX6biGBT3ZgcXs%2F46BcCY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 03:12 UTC, merged