removing managed tenant risky user docs
microsoftgraph/microsoft-graph-docs pull request #14701
Opened 2021-10-21 21:11 UTC by RaajGovind

2021-10-21 21:13 UTC, opbld32 commented
Docs Build status updates of commit _[9f2e972](https://github.com/RaajGovind/microsoft-graph-docs/commits/9f2e972dc533e82f7d3ecfd18dd551c5d75889ff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-14701) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-dcf736e6)
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-managedtenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-14701) (graph-rest-beta) | [Details](#user-content-617005ddd0b7559153cab0fc983cdd81-dcf736e6)
[api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/api/managedtenants-riskyuser-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/managedtenants-riskyuser.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-riskyuser.md) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-dcf736e6"></a>
### [api-reference/beta/toc.yml](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/toc.yml)
 - **Line 9514, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

<a id="617005ddd0b7559153cab0fc983cdd81-dcf736e6"></a>
### [api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-managedtenant.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'isaiahwilliams' is not a valid GitHub ID.`````
 - **Line 39, Column 13**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/managedtenants-riskyuser.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110212112003035-14701%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-21T21%3A13%3A54Z&sr=b&sp=r&sig=xeRM3RaoZhB8vutBIvVj8VfRf2HIQAWmkfdK9ERj5JE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-21 21:20 UTC, opbld30 commented
Docs Build status updates of commit _[deea370](https://github.com/RaajGovind/microsoft-graph-docs/commits/deea3707b75fb77b198bd440679632f215629377)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-managedtenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-14701) (graph-rest-beta) | [Details](#user-content-617005ddd0b7559153cab0fc983cdd81-babbe076)
[api-reference/beta/toc.yml](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-14701) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-babbe076)
[api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/api/managedtenants-riskyuser-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/managedtenants-riskyuser.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-riskyuser.md) | :white_check_mark:Succeeded | |

<a id="617005ddd0b7559153cab0fc983cdd81-babbe076"></a>
### [api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-managedtenant.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'isaiahwilliams' is not a valid GitHub ID.`````

<a id="0817dce4456c16725d5333633847d38f-babbe076"></a>
### [api-reference/beta/toc.yml](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/toc.yml)
 - **Line 9514, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110212118240189-14701%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-21T21%3A20%3A42Z&sr=b&sp=r&sig=9bFrb2bI9K%2BNEQzgJ8I%2FiK8ZsTGszgXWOQud9zZ2TsM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 14:47 UTC, idwilliams approved these changes

2021-11-17 20:20 UTC, opbld34 commented
Docs Build status updates of commit _[1286e97](https://github.com/RaajGovind/microsoft-graph-docs/commits/1286e9731b15dcd227c0eebf15aee66d63036c5c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-managedtenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-14701) (graph-rest-beta) | [Details](#user-content-617005ddd0b7559153cab0fc983cdd81-92b600eb)
[api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/api/managedtenants-riskyuser-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/managedtenants-riskyuser.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-riskyuser.md) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-14701) (graph-rest-beta) |

<a id="617005ddd0b7559153cab0fc983cdd81-92b600eb"></a>
### [api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-managedtenant.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'isaiahwilliams' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111172018425876-14701%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T20%3A20%3A18Z&sr=b&sp=r&sig=76vvDAusP%2FgIMc4ETI1yniv%2BMcRDj28j84pefGY5%2F%2Fw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 20:21 UTC, idwilliams commented
@Lauragra the conflicts have been resolved. Please let us know if there are other items that need to be resolved.

2021-11-17 20:50 UTC, Lauragra requested changes
Please add changelog entries for the deleted APIs. Thanks.

2021-11-17 22:24 UTC, opbld30 commented
Docs Build status updates of commit _[9855e9c](https://github.com/RaajGovind/microsoft-graph-docs/commits/9855e9c9c4db9b7ba19209e07c6f0fedb15db61d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-managedtenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-14701) (graph-rest-beta) | [Details](#user-content-617005ddd0b7559153cab0fc983cdd81-d8a96aa6)
[api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/api/managedtenants-riskyuser-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/managedtenants-riskyuser.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-riskyuser.md) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-14701) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

<a id="617005ddd0b7559153cab0fc983cdd81-d8a96aa6"></a>
### [api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-managedtenant.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'isaiahwilliams' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111172222321337-14701%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T22%3A24%3A10Z&sr=b&sp=r&sig=CeaHvpOBjVx9ol%2BwnISPe8xuglK%2BgKHCURaKNnYaoF4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 23:06 UTC, RaajGovind commented
> Please add changelog entries for the deleted APIs. Thanks.

Done, thanks!

2021-11-17 23:08 UTC, opbld34 commented
Docs Build status updates of commit _[9855e9c](https://github.com/RaajGovind/microsoft-graph-docs/commits/9855e9c9c4db9b7ba19209e07c6f0fedb15db61d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-managedtenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-14701) (graph-rest-beta) | [Details](#user-content-617005ddd0b7559153cab0fc983cdd81-bf8df157)
[api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/api/managedtenants-riskyuser-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/managedtenants-riskyuser.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-riskyuser.md) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-14701) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

<a id="617005ddd0b7559153cab0fc983cdd81-bf8df157"></a>
### [api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-managedtenant.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'isaiahwilliams' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111172306546846-14701%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T23%3A08%3A31Z&sr=b&sp=r&sig=wqrvzdtuSnefF6soj7CT531rHV93ADU9cGEGRS7HUiI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 04:18 UTC, Lauragra commented on changelog/Microsoft.MultiTenantPlatform.json
> -    "changelog": [
I'm not sure why we have a large number of deletions and additions here. I think all we need is a ChangeList entry to mention that the resource was deleted. Thanks.

2021-11-18 04:30 UTC, idwilliams commented on changelog/Microsoft.MultiTenantPlatform.json
> -    "changelog": [
@Lauragra this is a good catch. Looking through the change, I am not certain why so many items are flagged as deletions. That might have been caused by formatting update that was done in Visual Studio before the file was shared to be included in the request. I have verified the only real change is the addition of the change list entry for the entity type and navigation property.

2021-11-18 04:34 UTC, Lauragra approved these changes

2021-11-18 04:35 UTC, opbld32 commented
Docs Build status updates of commit _[2594e0d](https://github.com/RaajGovind/microsoft-graph-docs/commits/2594e0d8ebbaefd640845e57bf71b039330f81aa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-managedtenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-14701) (graph-rest-beta) | [Details](#user-content-617005ddd0b7559153cab0fc983cdd81-3b77266f)
[api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/api/managedtenants-riskyuser-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/managedtenants-riskyuser.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-riskyuser.md) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-14701) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

<a id="617005ddd0b7559153cab0fc983cdd81-3b77266f"></a>
### [api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/RaajGovind/microsoft-graph-docs/blob/ragovind-riskyuserdelete/api-reference/beta/resources/managedtenants-managedtenant.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'isaiahwilliams' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111180433367829-14701%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-19T04%3A35%3A23Z&sr=b&sp=r&sig=X%2FHxjlPEL85bt9P9%2BZxI0iLTOYiIHZKWg5nPmdt2vS4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 04:37 UTC, merged