Adding List Teams API documentation
microsoftgraph/microsoft-graph-docs pull request #14728
Opened 2021-10-25 14:38 UTC by akhilkohlimicrosoft

2021-11-10 08:06 UTC, opbld33 commented
Docs Build status updates of commit _[6333b82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6333b82577f202f34c6f890c16a2c2e8855369db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/api/teams-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/v1.0/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/v1.0/api/teams-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-1.0&branch=pr-en-us-14728) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-14728) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-1.0&branch=pr-en-us-14728) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111100804331713-14728%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-11T08%3A06%3A22Z&sr=b&sp=r&sig=QXdH3EP2kPnHlW5L%2FZRyZBWpOSCzgnpmgLtprFLBIL8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-15 11:36 UTC, opbld30 commented
Docs Build status updates of commit _[6e560a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e560a57be28598ab96150d4058fe81135489a95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/api/teams-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111151134240970-14728%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-16T11%3A36%3A11Z&sr=b&sp=r&sig=eIsd%2F8vc8A16qb3kE0sE%2Bh0LCCeAfcXBXnXjFXJVLFc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 06:13 UTC, opbld34 commented
Docs Build status updates of commit _[78af5bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78af5bdcd1cf4511dc220c48b73f312c52c171ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/api/teams-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111170612011044-14728%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T06%3A13%3A57Z&sr=b&sp=r&sig=VPkEVUoBSH765AFF5rkfhXPu2oKb47pdxhEwCFw7AGo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 21:58 UTC, opbld34 commented
Docs Build status updates of commit _[5028df2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5028df2237fb8d65f24f4605fd02e146cc28ab59)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/api/teams-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111172156268601-14728%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T21%3A58%3A03Z&sr=b&sp=r&sig=MEAz68DsZXoM%2BFQIU84NdpDFl2ydhcLzXnrafreV5TI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 16:56 UTC, isvargasmsft commented on api-reference/beta/api/teams-list.md
> +Get list of all [teams](../resources/team.md) in an organization.
Description in lines 3 and 16: Please rephrase to:
List all [teams] (link here) in an organization.

2021-11-18 16:58 UTC, isvargasmsft commented on api-reference/beta/api/teams-list.md
> +# List Teams
Title in lines 2 and 10: please use small caps for teams:
**List teams**

2021-11-18 17:08 UTC, isvargasmsft commented on api-reference/beta/api/teams-list.md
> +# [HTTP](#tab/http)
Line 61: Please delete this line. Snippets are automatically generated. Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103162/Generate-code-snippets

2021-11-18 17:09 UTC, isvargasmsft commented on api-reference/beta/api/teams-list.md
> +```msgraph-interactive
Line 66: please replace **msgraph-interactive** for **http**.

2021-11-18 17:09 UTC, isvargasmsft commented on api-reference/beta/api/teams-list.md
> +### Response
Line 71: Please use H4 Response:

#### Response

2021-11-18 17:10 UTC, isvargasmsft commented on api-reference/beta/api/teams-list.md
> +The following example shows the response.
Line 74: Please rephrase to:
The following is an example of a response.

2021-11-18 17:14 UTC, isvargasmsft commented on api-reference/beta/api/teams-list.md
> +  "@odata.type": "microsoft.graph.group",
Line 78: In line 48 we state that this method return a collection of team objects. However, we are telling API Doctor that this return a collection of groups. 

Can you please clarify?

2021-11-18 17:17 UTC, isvargasmsft commented on api-reference/beta/api/teams-list.md
> +# [HTTP](#tab/http)
Please apply to other instances in this PR.

2021-11-18 17:17 UTC, isvargasmsft commented on api-reference/beta/api/teams-list.md
> +```msgraph-interactive
Please apply to other files and instances in this PR

2021-11-18 17:18 UTC, isvargasmsft commented on api-reference/beta/api/teams-list.md
> +### Response
H4 please

2021-11-18 17:20 UTC, isvargasmsft commented on api-reference/beta/api/teams-list.md
> +The following example shows the response.
Please rephrase to: The following is an example of a response.

2021-11-18 17:21 UTC, isvargasmsft commented on api-reference/beta/toc.yml
> +        - name: Get list of teams in an organization
Please rephrase to: List all teams in an organization

2021-11-18 20:42 UTC, isvargasmsft commented on api-reference/beta/toc.yml
> +        - name: Get list of teams in an organization
Missing in this PR:
Changelog entry for the new operation (list teams)

2021-11-18 20:44 UTC, isvargasmsft requested changes
Hello Akhil, 

Thank you very much for your work in this PR. 

Please add the proper changelog entry for the new operation, and please review a few comments on structure and phrasing. 

Feel free to ping me on the side if you have any questions. 

Kind regards, 

Isaac Vargas

2021-11-23 06:58 UTC, akhilkohlimicrosoft commented on api-reference/beta/api/teams-list.md
> +This method supports the  `$filter`, `$select`, `$top`, `$skiptoken`, `$count` [OData query parameters](/graph/query-parameters) to help customize the response.
Added property / value. Please check if this is fine. Thanks

2021-11-23 06:59 UTC, opbld34 commented
Docs Build status updates of commit _[1c422a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c422a1f24f42aa73789a50237faf80eb9ff36d9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/api/teams-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) | [Details](#user-content-4f8c5ccde4e6c4a5b7de8cb6267e3255-865dc303)
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="4f8c5ccde4e6c4a5b7de8cb6267e3255-865dc303"></a>
### [api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/api/teams-list.md)
 - **Line 35, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111230656475560-14728%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-24T06%3A59%3A42Z&sr=b&sp=r&sig=JW5ur8AhuLA7HZKYFQUUNxpfpPTVEEnXZbQuLwuIdjI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-23 07:09 UTC, akhilkohlimicrosoft commented on api-reference/beta/api/teams-list.md
> +This method supports the  `$filter`, `$select`, `$top`, `$skiptoken`, `$count` [OData query parameters](/graph/query-parameters) to help customize the response.
I have provided a link to OData Query parameters which explains the property supported for each query parameter. Please let me know if this works. Thanks

2021-11-23 07:09 UTC, opbld30 commented
Docs Build status updates of commit _[82ae312](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82ae312fd17a4c5924c4e5eb72f5d578b76effaa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/api/teams-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111230707203453-14728%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-24T07%3A09%3A46Z&sr=b&sp=r&sig=DsVsj0tyzOqobhxbzh6uec2NHsBy0Qv%2BRjg8Vgz7Dbk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-23 07:17 UTC, opbld32 commented
Docs Build status updates of commit _[f4c4ab4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4c4ab47376b68283cca5a0c28f6d598662e4cfd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/api/teams-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) | [Details](#user-content-4f8c5ccde4e6c4a5b7de8cb6267e3255-6ff88dc9)
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="4f8c5ccde4e6c4a5b7de8cb6267e3255-6ff88dc9"></a>
### [api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/api/teams-list.md)
 - **Line 112, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111230715449586-14728%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-24T07%3A17%3A18Z&sr=b&sp=r&sig=9ddAubev72dYJucs5qMo8vuljNPHlM7TjP3PN3oQq%2Bg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-23 07:21 UTC, opbld32 commented
Docs Build status updates of commit _[d0780b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0780b332ab99998ad4d4fec8c54144901154c9c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/api/teams-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111230719501558-14728%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-24T07%3A21%3A19Z&sr=b&sp=r&sig=q43yJDo3vwR01Bi1HQFVlMFEQtDk4DPZaIpyqVi3iXk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-23 15:07 UTC, opbld33 commented
Docs Build status updates of commit _[dd5da06](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd5da06a0824cf07b2d0318e076d4965178b119c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/api/teams-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111231504382166-14728%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-24T15%3A07%3A23Z&sr=b&sp=r&sig=IjeYlxrQYoqyCuiB0iIZl25teg%2Fxbj%2B%2Fb9iukyPpDk8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-23 15:20 UTC, isvargasmsft approved these changes

2021-11-30 02:18 UTC, opbld34 commented
Docs Build status updates of commit _[648cbec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/648cbec61eacf7a07be0eb3e89cf05fac14dafc6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/api/teams-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111300216280580-14728%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-31T02%3A18%3A26Z&sr=b&sp=r&sig=v%2BI0aG6s14ne3zTCFLXP%2BSWh2T1ItSC7Abegl7O37iU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-30 02:19 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: List all teams in an organization
This is the wrong location in the TOC to surface this API. This is the Teamwork node under Users; we should only surface user-related APIs here. Please move this TOC entry to the Teamwork node, under Team.

2021-12-10 09:55 UTC, opbld30 commented
Docs Build status updates of commit _[7a58490](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a5849002bd9ed800c33cc90e8f9d33720719b3a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-64d04542)

<a id="64d04542"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112100955305596-14728%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-10T09%3A55%3A53Z&sr=b&sp=r&sig=jqS4jhnC8lHoYcjRd2IYv3apZeU963jmGW%2F5uWiCHp8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-10 10:28 UTC, opbld34 commented
Docs Build status updates of commit _[4705405](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4705405387a7a4bd83769b4facfd29f1288e94d1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0d0013f5)

<a id="0d0013f5"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112101027335888-14728%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-10T10%3A28%3A09Z&sr=b&sp=r&sig=37ZvzNGk%2FQBb9wGXxzzfqYitK6ae2AK5dj7thBmxkpM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-10 10:53 UTC, opbld32 commented
Docs Build status updates of commit _[8a0bf7c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a0bf7c3e2f830179a8a06c688538ad4f2e01668)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-c3f7884e)
[api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/api/teams-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-c3f7884e"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/toc.yml)
 - **Line 9642, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112101051099262-14728%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-10T10%3A53%3A14Z&sr=b&sp=r&sig=fnPD2tOgBBR11EsiP%2FKpu1OuT1siRgN%2FCS5tZyWIsaU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-10 10:56 UTC, opbld32 commented
Docs Build status updates of commit _[b0b5d33](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0b5d33f524ef229f540c0c5a7ba2c8d97a53eb6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-2d4d4c3a)
[api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/api/teams-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-2d4d4c3a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/toc.yml)
 - **Line 9642, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112101055085983-14728%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-10T10%3A56%3A50Z&sr=b&sp=r&sig=57FmlZd4UKvSHHVpy%2BiM%2BVs93VwDjbkpU5f5ZyJkzL0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-10 21:41 UTC, isvargasmsft approved these changes

2021-12-13 22:33 UTC, opbld34 commented
Docs Build status updates of commit _[362b290](https://github.com/microsoftgraph/microsoft-graph-docs/commits/362b29098f54563b338c317534287e01d9d499e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/api/teams-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&branch=pr-en-us-14728) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/akhil/listteams/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112132230231579-14728%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-13T22%3A33%3A16Z&sr=b&sp=r&sig=umzMHiL%2FlKC1v61Aq49NrhD%2B2A1ef7%2BZFl1G7Sgzob4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-13 22:33 UTC, merged