Minor updates to Access Review Beta
microsoftgraph/microsoft-graph-docs pull request #14738
Opened 2021-10-25 22:31 UTC by shubhamguptacal

Super minor updates to Access Review Beta to include configuration and surfacing up of insights

Schema update PR: 5258874

2021-11-02 23:25 UTC, opbld32 commented
Docs Build status updates of commit _[ab30cd1](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/ab30cd1068f4ebbc4b2cab374e1bcbc72eb25d34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userlastsigninrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/usersigninInsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/usersigninInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersignininsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111022324102720-14738%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-03T23%3A25%3A48Z&sr=b&sp=r&sig=PBoLyu26S1fvAUg8Wu4tF6mVNhfAKIia2qbNIJoDl5g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-02 23:27 UTC, opbld32 commented
Docs Build status updates of commit _[8fd107e](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/8fd107edcb961208f38ffbce44091eca14eadde4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userlastsigninrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/usersigninInsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/usersigninInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersignininsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111022325123994-14738%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-03T23%3A27%3A39Z&sr=b&sp=r&sig=F8wrx8LmImGolRqWAfM607jhhhuGfGrD4f%2FP%2FnbjjPo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-02 23:27 UTC, isabelleatmsft commented on api-reference/beta/resources/enums.md
> +|unknownFutureValue|
@shubhamguptacal is the unknownFutureValue supposed to be there?

2021-11-02 23:30 UTC, opbld32 commented
Docs Build status updates of commit _[13ba833](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/13ba833dc124303e99df17848501e4113a0156fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userlastsigninrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/usersigninInsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/usersigninInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersignininsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111022326281185-14738%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-03T23%3A30%3A10Z&sr=b&sp=r&sig=GMlfyxW3xzwBdrcG9sMFW7tmwEmaL1ABwIlcuM6ySk4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-23 19:07 UTC, shubhamguptacal commented on api-reference/beta/resources/enums.md
> +|unknownFutureValue|
Yes, this is standard for all enums

2021-11-24 18:44 UTC, opbld31 commented
Docs Build status updates of commit _[2959e58](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/2959e5809bd090f97f21cb875b03203eba976b7f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userlastsigninrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/usersigninInsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/usersigninInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersignininsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111241842467316-14738%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T18%3A44%3A24Z&sr=b&sp=r&sig=WGZ%2FhSZWx7K1EDIxlKVlP9wq6E%2Bo9jyVY1MM9z5rwQg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 18:49 UTC, opbld33 commented
Docs Build status updates of commit _[6a72702](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/6a7270266d5c698e51297575413b46e2f2629895)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userlastsigninrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/usersigninInsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/usersigninInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersignininsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111241847404244-14738%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T18%3A49%3A15Z&sr=b&sp=r&sig=ZBL0st2PsB6e9FKSNDEd6xBihc0f%2BU3ieUvUI0jAjYI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 18:50 UTC, isabelleatmsft approved these changes

2021-11-24 18:51 UTC, opbld34 commented
Docs Build status updates of commit _[165ae18](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/165ae18844d8f2783d8a3617f27ea84848a05af1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userlastsigninrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/usersigninInsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/usersigninInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersignininsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111241848340178-14738%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T18%3A51%3A05Z&sr=b&sp=r&sig=2PM3fs0aGDI4HEU9hN0YsaCWfOitVtE7rlOfRMGhq8s%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 10:51 UTC, FaithOmbongi requested changes
@shubhamguptacal , left review comments here and there. Also,

- I notice that the instance relationship in accessReviewInstanceDecisionItem has never been published to the public metadata. Please look into this.
- Please move the enums and the changelog to first in their respective files
- For the **author** field, please change to Isabelle's alias. According to the guidance, "Use the GitHub name of the owner of the documentation for the workload. The owner is responsible for ensuring that external PRs are reviewed and approved and is assigned issues filed on the Docs site. ". The author must also be included in the Microsoft Graph contacts list.

2021-11-29 10:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewrecommendationinsightsetting.md
> +  "@odata.type": "microsoft.graph.accessreviewrecommendationinsightsetting"
```suggestion
  "blockType": "resource",
  "@odata.type": "microsoft.graph.accessReviewRecommendationInsightSetting"
```

2021-11-29 10:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewrecommendationinsightsetting.md
> +  "@odata.type": "#microsoft.graph.accessreviewrecommendationinsightsetting",
```suggestion
  "@odata.type": "#microsoft.graph.accessReviewRecommendationInsightSetting",
```

2021-11-29 10:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewrecommendationinsightsetting.md
> +description: "In the Azure AD access reviews feature, the `accessreviewrecommendationinsightsetting` represents the settings associated with an insight included in the review."
```suggestion
description: "In the Azure AD access reviews, the accessReviewRecommendationInsightSetting represents the settings associated with an insight provided for an access review."
```

2021-11-29 10:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewschedulesettings.md
> +| recommendationInsightSettings|[accessReviewRecommendationInsightSetting](../resources/accessReviewRecommendationInsightSetting.md) collection | Optional field. Describes the types of insights that
Too "early" for the statement on the supported derived type. That'll be in the accessReviewRecommendationInsightSetting resource description.
```suggestion
| recommendationInsightSettings|[accessReviewRecommendationInsightSetting](../resources/accessReviewRecommendationInsightSetting.md) collection | Optional. Describes the types of insights that aid reviewers to make access review decisions. |
```

2021-11-29 10:51 UTC, FaithOmbongi commented on api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md
> +The **userlastsignInrecommendationinsightsetting** allows you to configure last sign-in as an insight to aid reviewer decision-making for an [accessReviewScheduleDefinition](accessreviewscheduledefin
```suggestion
The **userLastSignInRecommendationInsightSetting** allows you to configure the last sign-in date and time of a user as an insight to aid the reviewers to make decisions for an [accessReviewScheduleDefinition](accessreviewscheduledefinition.md) object.

Inherits from [accessReviewRecommendationInsightSetting](accessReviewRecommendationInsightSetting.md).
```

2021-11-29 10:51 UTC, FaithOmbongi commented on api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md
> +# userlastsignInrecommendationinsightsetting resource type
Same case as in the schema
```suggestion
title: "userLastSignInRecommendationInsightSetting resource type"
description: "In the Azure AD access reviews, the userLastSignInRecommendationInsightSetting represents the settings associated with the insight that is based on the last sign-in date and time of the user, and that is used to aid reviewers to make decisions."
author: "shubhamguptacal"
ms.localizationpriority: medium
ms.prod: "governance"
doc_type: resourcePageType
---

# userlastsignInrecommendationinsightsetting resource type
```

2021-11-29 10:51 UTC, FaithOmbongi commented on api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md
> +| recommendationLookBackDuration | Duration| Optional field. Indicates the time period of inactivity (with respect to the start date of the review instance) that recommendations will be configured fr
Alphabetically order properties in the table
```suggestion
| recommendationLookBackDuration | Duration | Optional. Indicates the time period of inactivity (with respect to the start date of the review instance) that recommendations will be configured from. The recommendation will be to `deny` if the user is inactive during the look-back duration. For reviews of groups and Azure AD roles, any duration is accepted. For reviews of applications, 30 days is the maximum duration. If not specified, the duration is 30 days. |
| signInScope | userSignInRecommendationScope | Indicates whether inactivity is calculated based on the user's inactivity in the tenant or in the application. The possible values are `tenant`, `application`, `unknownFutureValue`. `application` is only relevant when the access review is a review of an assignment to an application. |
```

2021-11-29 10:51 UTC, FaithOmbongi commented on api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md
> +  "@odata.type": "microsoft.graph.userlastsignInrecommendationinsightsetting"
```suggestion
  "blockType": "resource",
  "@odata.type": "microsoft.graph.userLastSignInRecommendationInsightSetting",
  "baseType": "microsoft.graph.accessReviewRecommendationInsightSetting"
```

2021-11-29 10:51 UTC, FaithOmbongi commented on api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md
> +  "signInScope": "microsoft.graph.userSignInRecommendationScope"
The cause of one of the API doctor errors
```suggestion
  "signInScope": "String"
```

2021-11-29 10:51 UTC, FaithOmbongi commented on api-reference/beta/resources/governanceinsight.md
> +title: "governanceinsight resource type"
```suggestion
title: "governanceInsight resource type"
```

2021-11-29 10:51 UTC, FaithOmbongi commented on api-reference/beta/resources/governanceinsight.md
> +# governanceinsight resource type
```suggestion
# governanceInsight resource type
```

2021-11-29 10:51 UTC, FaithOmbongi commented on api-reference/beta/resources/enums.md
> +
Please move this entry to first in the file

2021-11-29 10:51 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewschedulesettings.md
> +  ],
```suggestion
  ]
```

2021-11-29 10:51 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +              "Description": "Added the **recommendationInsightSettings** property to [accessReviewScheduleSettings](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewScheduleSettings?
```suggestion
              "Description": "Added the **recommendationInsightSettings** property to [accessReviewScheduleSettings](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewScheduleSettings?view=graph-rest-beta) resource. Use this property to configure insights that aid reviewers of an access review to make decisions.",
```

2021-11-29 10:51 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +              "Description": "Added the **insights** relationship to [accessReviewInstanceDecisionItem](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewInstanceDecisionItem?view=grap
```suggestion
              "Description": "Added the **insights** navigation property to the [accessReviewInstanceDecisionItem](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewInstanceDecisionItem?view=graph-rest-beta) resource.",
```

2021-11-29 10:51 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +              "Description": "Added the [userLastSignInRecommendationInsightSetting](https://docs.microsoft.com/en-us/graph/api/resources/userLastSignInRecommendationInsightSetting?view=graph-rest-be
```suggestion
              "Description": "Added the [userLastSignInRecommendationInsightSetting](https://docs.microsoft.com/en-us/graph/api/resources/userLastSignInRecommendationInsightSetting?view=graph-rest-beta) resource type. Use this type to configure insight settings based on the user's last sign-in date and time into a tenant or application.",
```

2021-11-29 10:51 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +              "Description": "Added the [accessReviewRecommendationInsightSetting](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewRecommendationInsightSetting?view=graph-rest-beta)
```suggestion
              "Description": "Added the [accessReviewRecommendationInsightSetting](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewRecommendationInsightSetting?view=graph-rest-beta) resource type. This is an abstract type that exposes resources for configuring the type of insights to provide to reviewers and access review decision-makers.",
```

2021-11-29 10:51 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +              "Description": "Added the [governanceInsight](https://docs.microsoft.com/en-us/graph/api/resources/governanceInsight?view=graph-rest-beta) resource",
```suggestion
              "Description": "Added the [governanceInsight](https://docs.microsoft.com/en-us/graph/api/resources/governanceInsight?view=graph-rest-beta) resource. This is an abstract type that exposes resources for configuring the type of insights to provide to decision-makers in an accessReviewDecisionItem.",
```

2021-11-29 10:51 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +              "Description": "Added the [userSignInInsight](https://docs.microsoft.com/en-us/graph/api/resources/userSignInInsight?view=graph-rest-beta) resource",
```suggestion
              "Description": "Added the [userSignInInsight](https://docs.microsoft.com/en-us/graph/api/resources/userSignInInsight?view=graph-rest-beta) resource. Use this type to configure insights for an **accessReviewDecisionItem** based on the user's last sign-in date and time.",
```

2021-11-29 10:51 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "SubArea": ""
```suggestion
          "WorkloadArea": "Identity and access",
          "SubArea": "Governance"
```

2021-12-30 20:59 UTC, opbld33 commented
Docs Build status updates of commit _[ae007ef](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/ae007ef3f913d99e9c3b3a467c9041556767f7cd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8fe25dfa)

<a id="8fe25dfa"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112302058472944-14738%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-30T20%3A59%3A16Z&sr=b&sp=r&sig=%2FOJOEXBikos6jXtKs0lcR%2Bug4kXLvQq4%2BrXXZyT7QfY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 00:49 UTC, opbld31 commented
Docs Build status updates of commit _[d06bfe9](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/d06bfe9e68bd2591fe7b7a4feebaf05b06bb1de8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fcd50a73)

<a id="fcd50a73"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040049098738-14738%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T00%3A49%3A36Z&sr=b&sp=r&sig=ZGXGT8aNfW5Ut%2BjgB4hD5QrJ8udijdh7YP2ywK0APbU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 00:55 UTC, opbld30 commented
Docs Build status updates of commit _[b4c92c9](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/b4c92c99847594711de9e723a2c233b98a40eab2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fe3b68f8)

<a id="fe3b68f8"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040054545503-14738%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T00%3A55%3A19Z&sr=b&sp=r&sig=cPMiRAN3%2FCqsiohboP4OZb%2FISoVMTuY44SoKkEOBwIs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 00:59 UTC, opbld32 commented
Docs Build status updates of commit _[72453ff](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/72453ffa480810251dc2ffe73b0b7bb18d4784cb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3b85ac84)

<a id="3b85ac84"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040058125016-14738%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T00%3A58%3A59Z&sr=b&sp=r&sig=w%2FId6KHvDrApTXn0VnLiA%2B9kEdYgh4ooRHnDYDLzeeY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 11:10 UTC, opbld30 commented
Docs Build status updates of commit _[d6d804f](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/d6d804fba7262d5195f934f01f6b9a289aa0fcca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userlastsigninrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/usersigninInsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/usersigninInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersignininsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201061108239526-14738%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T11%3A10%3A26Z&sr=b&sp=r&sig=9HLyPP7XGbyk6nPQRSe%2BEH4sPHtUIO%2FD8rcq4YzqGs8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 11:14 UTC, opbld33 commented
Docs Build status updates of commit _[897988c](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/897988c81bb9d78f82b2f47e9c8bcda90faa4a80)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userlastsigninrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/usersigninInsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/usersigninInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersignininsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201061113116276-14738%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T11%3A14%3A58Z&sr=b&sp=r&sig=TgDm%2FL9tUOZ6RsgqPzjwu0i0zihBPaIpgAQsQAAobow%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 11:20 UTC, opbld34 commented
Docs Build status updates of commit _[4bde71f](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/4bde71f11692c530bbe306ca1663161fbc6c3dee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userlastsigninrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/usersigninInsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/usersigninInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersignininsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201061118363976-14738%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T11%3A20%3A26Z&sr=b&sp=r&sig=0ukh7gbOPIXiPXHKRXFWr%2B4mZBedd1uOic1%2BAB3z2%2B8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 11:22 UTC, opbld31 commented
Docs Build status updates of commit _[ec96363](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/ec96363e0e4094fab3c4b5149307d810da70f487)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userlastsigninrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/usersigninInsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/usersigninInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersignininsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201061120049287-14738%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T11%3A22%3A28Z&sr=b&sp=r&sig=r48BSlRnAnW681GPuynxoD2pdupcqQuP7dpECI0dkY0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-06 11:44 UTC, FaithOmbongi approved these changes

2022-01-20 04:25 UTC, opbld32 commented
Docs Build status updates of commit _[e546ffb](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/e546ffb99ae35fcef545773a42df734fd91a47b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitem.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userlastsigninrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[api-reference/beta/resources/usersigninInsight.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/usersigninInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersignininsight?view=graph-rest-beta&branch=pr-en-us-14738) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200423215103-14738%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T04%3A25%3A34Z&sr=b&sp=r&sig=7W%2BVhkQzQzc%2FGlKnq2DAmphxVsYDEQP1C5k9SvqoSrM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 04:28 UTC, merged