Add Security Incidents & Alert_v2 APIs
microsoftgraph/microsoft-graph-docs pull request #14745
Opened 2021-10-26 15:19 UTC by BenAlfasi

2021-11-25 15:31 UTC, opbld32 commented
Docs Build status updates of commit _[4c896a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c896a4125191c6194b9ced503c62c33b0145356)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-82940ca1f972037093c95b4e31d578c8-b8ff39f7)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-get-alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b8ff39f7)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-b8ff39f7)
[api-reference/beta/api/security-get-alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-get-alert_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-get-alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-get-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-get-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-get-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |

<a id="82940ca1f972037093c95b4e31d578c8-b8ff39f7"></a>
### [api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md)
 - **Line 33, Column 9**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#alertStatus_v2-values' in 'beta/resources/alert_v2.md', did you mean '#alertstatus_v2-values'?`````
 - **Line 34, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#alertSeverity_v2-values' in 'beta/resources/alert_v2.md', did you mean '#alertseverity_v2-values'?`````
 - **Line 35, Column 17**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#alertClassification_v2-values' in 'beta/resources/alert_v2.md', did you mean '#alertclassification_v2-values'?`````
 - **Line 36, Column 16**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#alertDetermination_v2-values' in 'beta/resources/alert_v2.md', did you mean '#alertdetermination_v2-values'?`````
 - **Line 37, Column 16**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#serviceSource-values' in 'beta/resources/alert_v2.md', did you mean '#servicesource-values'?`````

<a id="0817dce4456c16725d5333633847d38f-b8ff39f7"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml)
 - **Line 13743, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-list-alert_v2.md'.`````

<a id="eea99bea355d0a4253064eefdbbe7005-b8ff39f7"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md)
 - **Line 2132, Column 1**: **[Warning: duplicate-h2s - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Teams app installation permissions''. Each second level heading (H2) in an article must be unique.`````
 - **Line 2269, Column 1**: **[Warning: duplicate-h2s - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Teams app installation permissions''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111251529239964-14745%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-26T15%3A31%3A05Z&sr=b&sp=r&sig=ozYjtESgALFy%2BDzMalrSUDG4KH%2FdiYUaKtfCUrT6PLw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when extern [...]

2021-12-02 23:01 UTC, opbld31 commented
Docs Build status updates of commit _[ee30a89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee30a892e1cb300c06115f81ecfe4a3c9926afdd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-82940ca1f972037093c95b4e31d578c8-3739fdc1)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-get-alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-3739fdc1)
[api-reference/beta/api/security-get-alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-get-alert_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-get-alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-get-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-get-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-get-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

<a id="82940ca1f972037093c95b4e31d578c8-3739fdc1"></a>
### [api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md)
 - **Line 33, Column 9**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#alertStatus_v2-values' in 'beta/resources/alert_v2.md', did you mean '#alertstatus_v2-values'?`````
 - **Line 34, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#alertSeverity_v2-values' in 'beta/resources/alert_v2.md', did you mean '#alertseverity_v2-values'?`````
 - **Line 35, Column 17**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#alertClassification_v2-values' in 'beta/resources/alert_v2.md', did you mean '#alertclassification_v2-values'?`````
 - **Line 36, Column 16**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#alertDetermination_v2-values' in 'beta/resources/alert_v2.md', did you mean '#alertdetermination_v2-values'?`````
 - **Line 37, Column 16**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#serviceSource-values' in 'beta/resources/alert_v2.md', did you mean '#servicesource-values'?`````

<a id="0817dce4456c16725d5333633847d38f-3739fdc1"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml)
 - **Line 13762, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-list-alert_v2.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112022259397969-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T23%3A01%3A16Z&sr=b&sp=r&sig=qimK9hJs%2Fnrf25mc7wcY9ba4EduLxF0W3VOc8TfTbFo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-05 12:46 UTC, opbld30 commented
Docs Build status updates of commit _[f7fd9fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7fd9feda7e720282bca888117d7fd479c627bc5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-82940ca1f972037093c95b4e31d578c8-1361bd28)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-get-alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-1361bd28)
[api-reference/beta/api/security-get-alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-get-alert_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-get-alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-get-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-get-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-get-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alertcomment_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alertcomment_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alertcomment_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

<a id="82940ca1f972037093c95b4e31d578c8-1361bd28"></a>
### [api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md)
 - **Line 33, Column 9**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#alertStatus_v2-values' in 'beta/resources/alert_v2.md', did you mean '#alertstatus_v2-values'?`````
 - **Line 34, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#alertSeverity_v2-values' in 'beta/resources/alert_v2.md', did you mean '#alertseverity_v2-values'?`````
 - **Line 35, Column 17**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#alertClassification_v2-values' in 'beta/resources/alert_v2.md', did you mean '#alertclassification_v2-values'?`````
 - **Line 36, Column 16**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#alertDetermination_v2-values' in 'beta/resources/alert_v2.md', did you mean '#alertdetermination_v2-values'?`````
 - **Line 37, Column 16**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#serviceSource-values' in 'beta/resources/alert_v2.md', did you mean '#servicesource-values'?`````

<a id="0817dce4456c16725d5333633847d38f-1361bd28"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml)
 - **Line 13762, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-list-alert_v2.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112051244148009-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-05T12%3A46%3A06Z&sr=b&sp=r&sig=x6Ze%2FlkFbNdtUYOrytuz3pygfD%2BZ%2BX4rV8sZZ3iznfs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-05 14:59 UTC, opbld31 commented
Docs Build status updates of commit _[bc4c330](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc4c33083acdb73eef5677d724f0cb53111c898c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-get-alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-43f5cfc3)
[api-reference/beta/api/security-get-alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-get-alert_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-get-alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-get-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-get-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-get-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alertcomment_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alertcomment_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alertcomment_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

<a id="0817dce4456c16725d5333633847d38f-43f5cfc3"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml)
 - **Line 13762, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-list-alert_v2.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112051457453734-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-05T14%3A59%3A17Z&sr=b&sp=r&sig=pt%2BKxF6xpdysOWREAzVRXuTVMQU8nBaU%2FArZVqoPi3c%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 21:15 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-api-overview.md
> +The [incident](incident.md) resource and its APIs allow you to sort through incidents to create an informed cyber security response. It exposes a collection of incidents that were flagged in your net
@BenAlfasi , in the paragraph in line 75, since you point customers to the incident resource, please also roll in alert_v2 and have a link to alert_v2.md. In general, the API overview topic should link to the main resources at appropriate places.

2021-12-06 21:18 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-api-overview.md
> +The [incident](incident.md) resource and its APIs allow you to sort through incidents to create an informed cyber security response. It exposes a collection of incidents that were flagged in your net
I also think when we publish the docs for alert_v2, we should also appropriately set expectations for what's happening to the pre-existing alert resource and its API. This same API overview talks about Alerts in its former full glory. Not providing any indication that that API is being deprecated will be confusing to some customers.

FYI deprecate docs guidance: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103183/Deprecate-docs

2021-12-09 22:05 UTC, angelgolfer-ms commented on api-reference/beta/api/security-get-incident.md
> +---
GLOBAL for this PR:
@BenAlfasi , hey, I noticed the filenames for the incident API (which we reviewed in PR 13936) changed :-O
FYI filenames in the docs repo should follow the same filenaming guidance. The main reason is we do use a generator to generate stub topics, and possibly topics with more content in the future, so the generator needs to be able to insert links which depend on filenames following a consistent naming mechanism.
For example, this GET operation should follow {resource name}-get.md.
As for the filename prefix - that should apply only if the corresponding resource, method, or enum is in a subnamespace. 
You might notice there are some existing files that break this rule, and no, they should not have and comes the time that the generator can generate topics with more content, then all these files will have to be renamed, links forwarded...
CDK topic for you reference: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming

Please do the similar file renaming for other files in this PR. I'll try to comment too, but just in case.

2021-12-10 08:38 UTC, angelgolfer-ms commented on api-reference/beta/resources/security.md
>  |securityactions|[securityAction](../resources/securityaction.md)|Actions that respond to alerts to block malicious activities.|
@BenAlfasi , thanks for the correction in line 32.
Please delete line 33.

2021-12-10 08:49 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
>          href: resources/securityaction.md
@BenAlfasi , please remove line 13691 to fix the odd repetition of the securityAction resource in the TOC. 
FYI the repetition is caused by OPS (the publishing system) repeating any TOC parent node that has an href defined as the first child node. This treatment was meant to disallow any TOC parent node to be associated with a topic; before, clicking a parent TOC node can open a topic. The treatment went into effect after the Graph TOC was already very built out, so there are many pre-existing parts of the TOC that still have a parent TOC node associated with a topic.

2021-12-10 09:06 UTC, angelgolfer-ms commented on api-reference/beta/resources/alert_v2.md
> +  "@odata.type": "microsoft.graph.incident",
Line 136:
Please change this line to define the odata.type as "microsoft.graph.alert_v2".

2021-12-10 09:09 UTC, angelgolfer-ms commented on api-reference/beta/api/security-list-alerts_v2.md
> +``` json
Line 94:
Please change that from json to http.

Between the current lines 94 and 95:
Please also add the response code, response header, and an empty line, before you start the curly open bracket for the response body. Like:

```http
HTTP/1.1 200 OK
Content-type: application/json

2021-12-10 09:13 UTC, angelgolfer-ms commented on api-reference/beta/resources/alert_v2.md
> +  "@odata.type": "microsoft.graph.incident",
This would fix a couple of your current API Doctor errors.

2021-12-10 09:15 UTC, angelgolfer-ms commented on api-reference/beta/api/security-list-incidents.md
> +{
Between lines 97 and 98:
Please add an empty line. API Doctor looks for that to determine the beginning of the response body.

2021-12-10 09:25 UTC, angelgolfer-ms commented on api-reference/beta/api/security-list-incidents.md
> +
Since there are 2 examples in this "Examples" section, please take a look at user-list-messages.md in the beta reference to label each example like the following (correct description where necessary please):

### Example 1: List all incidents in a security attack on an organization without alerts details
#### Request
...
#### Response
...

### Example 2: List all incidents in a security attack on an organization and include alerts details for each incident
#### Request
...
#### Response
...

2021-12-10 09:31 UTC, angelgolfer-ms commented on api-reference/beta/api/security-get-incident.md
> +``` json
Line 71:
Please change this from json to http.

Before line 72:
Please add a line for the response code, another line for response header, and **then an empty line**, before the open curly bracket in line 72, like the following:

HTTP/1.1 200 OK
Content-type: application/json

2021-12-10 09:32 UTC, angelgolfer-ms commented on api-reference/beta/api/security-get-incident.md
> +``` json
This will fix one of your API Doctor errors.

2021-12-10 09:33 UTC, angelgolfer-ms commented on api-reference/beta/api/security-get-alert_v2.md
> +``` json
Line 72:
Please change this from json to http.

Before line 73:
Please add a line for the response code, another line for response header, and then an empty line, before the open curly bracket in line 73, like the following:

HTTP/1.1 200 OK
Content-type: application/json

2021-12-10 09:35 UTC, angelgolfer-ms commented on api-reference/beta/resources/alert_v2.md
> +
Line 55:
For the type, please add the word "collection".
This would fix one of your API Doctor errors.

2021-12-10 09:37 UTC, angelgolfer-ms commented on api-reference/beta/resources/security.md
>  |securityactions|[securityAction](../resources/securityaction.md)|Actions that respond to alerts to block malicious activities.|
Hopefully deleting line 33 will fix one of the API Doctor errors.

2021-12-10 09:42 UTC, angelgolfer-ms commented on api-reference/beta/resources/incident.md
> +
Line 17:
In this API reference topic (as opposed to if this was a conceptual or overview topic), it would be appropriate and helpful to add a link to the first mention of "alert", particularly because there are the old alert resource and the new alert_v2 resource, and you guys are not planning to clarify the story right now.

Because alert_v2 is an alert instance (singular), technically the link text and link destination in a context like this should be clear. So I'd suggest rephrasing the first sentence as:
"An incident in Microsoft 365 Defender is a collection of correlated [alert](alert_v2.md) instances and associated metadata..."

2021-12-10 09:44 UTC, angelgolfer-ms commented on api-reference/beta/resources/incident.md
> +
GLOBAL:
If you run into other similar contexts where you refer to an alert or alerts for the first time in a topic, it would be helpful to provide a link to better define the actual resource.

2021-12-10 09:47 UTC, angelgolfer-ms commented on api-reference/beta/api/security-get-alert_v2.md
> +---
Per our filenaming guidance, please rename this file as alert_v2-get.md.
Please see the CDK topic, [File naming](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming), for more details.

2021-12-10 09:49 UTC, angelgolfer-ms commented on api-reference/beta/api/security-get-incident.md
> +---
So please rename this file as incident-get.md.

2021-12-10 09:51 UTC, angelgolfer-ms commented on api-reference/beta/api/security-list-alerts_v2.md
> +---
Just to be clear: This filename is appropriate - here "security" is the security resource which defines alerts_v2 as a nav property. So the filename follows the filenaming guidance for list operation topics.

2021-12-10 09:52 UTC, angelgolfer-ms commented on api-reference/beta/api/security-list-incidents.md
> +---
Just to be clear: This filename is appropriate - here "security" is the security resource which defines incidents as a nav property. So the filename follows the filenaming guidance for list operation topics.

2021-12-10 10:04 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-api-overview.md
>  | **Secure scores**|||
After line 125:
Can you please add a table row for "List incidents and include alerts details", and mirror that as the second example in the list incidents topic where you do $expand on the alerts_v2 nav property?
I hope that would help make it clearer there's this newer type of alerts. Otherwise, in this table, what's noticeable is the older list alerts use case. Where appropriate, we should at least present them in the same context, like in this table, just so customers become aware.

2021-12-10 10:08 UTC, angelgolfer-ms requested changes
@BenAlfasi , I have made a first pass of this PR. There are a few API Doctor errors at this point, so hopefully my comments can help you quickly get over those errors so that you can add other content improvements and get a successful build.

As I will be OOF after this week, @isvargasmsft will follow up on the review of this PR. Meanwhile, if you have any questions in the next day, please comment here or ping me on Teams (better). Thanks.

2021-12-29 13:23 UTC, opbld30 commented
Docs Build status updates of commit _[06f37f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06f37f49c39fbc659a8471ebe70cc397fe547979)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-17b8753a)
[api-reference/beta/api/alert_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/alert_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-get-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-get-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-get-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alertcomment_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alertcomment_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alertcomment_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

<a id="0817dce4456c16725d5333633847d38f-17b8753a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml)
 - **Line 13926, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-list-alert_v2.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112291321064141-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-29T13%3A23%3A49Z&sr=b&sp=r&sig=0CdjOAr7rNZZHr%2BPAegTJkD%2ByZeufjVrR84hA7hIGTg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-29 15:12 UTC, opbld33 commented
Docs Build status updates of commit _[3621ebd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3621ebd0709c6ddc801c7dec7f4c3be92c2a902a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-86ba777f)
[api-reference/beta/api/alert_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/alert_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alertcomment_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alertcomment_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alertcomment_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

<a id="0817dce4456c16725d5333633847d38f-86ba777f"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml)
 - **Line 13925, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-list-alert_v2.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112291509180366-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-29T15%3A12%3A04Z&sr=b&sp=r&sig=TCoQ5BAUueR%2FYoKawRPW7eUpH0zNN1BeUsWJTFtbhPw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-02 08:23 UTC, opbld30 commented
Docs Build status updates of commit _[e6adc68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e6adc68b81dc77e122bb814a0f241646f7daefe2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-4d649f25)
[api-reference/beta/api/alert_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/alert_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alertcomment_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alertcomment_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alertcomment_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

<a id="0817dce4456c16725d5333633847d38f-4d649f25"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml)
 - **Line 12488, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````
 - **Line 13930, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-list-alert_v2.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201020820536095-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-02T08%3A23%3A42Z&sr=b&sp=r&sig=WdJSchMGgBza%2BJiH0MNEdp8uTaJSf2g08aVfkXzy%2FpU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-02 09:14 UTC, opbld34 commented
Docs Build status updates of commit _[4402a11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4402a11924579fc388086abd54976dd214ccbd6e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-0d65214d)
[api-reference/beta/api/alert_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/alert_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alertcomment_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alertcomment_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alertcomment_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

<a id="0817dce4456c16725d5333633847d38f-0d65214d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml)
 - **Line 12488, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````
 - **Line 13930, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-list-alert_v2.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201020912045664-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-02T09%3A14%3A10Z&sr=b&sp=r&sig=EWnx%2BFkBh9MBi429WMXOcVsnFWgFqICHCBLuxQKmLYw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-03 22:14 UTC, isvargasmsft commented on api-reference/beta/api/alert_v2-get.md
> +      }
There is a ']' missing to close the comments section in this example, causing API Doctor to fail.

2022-01-03 22:21 UTC, isvargasmsft commented on api-reference/beta/api/security-list-alerts_v2.md
> +    }
Similar as above, there is a ] missing to close the comments block.

2022-01-04 09:56 UTC, opbld34 commented
Docs Build status updates of commit _[4f24d71](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f24d713a361cf6083ddf6ac41be60f09717a052)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d1a7562a)
[api-reference/beta/api/alert_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/alert_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alertcomment_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alertcomment_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alertcomment_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

<a id="0817dce4456c16725d5333633847d38f-d1a7562a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml)
 - **Line 12505, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````
 - **Line 13947, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-list-alert_v2.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040953513930-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T09%3A56%3A29Z&sr=b&sp=r&sig=8H451ScwA90ixI12098YqOsg952bC4JrvEAbP%2FnWZqY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 09:59 UTC, opbld34 commented
Docs Build status updates of commit _[14f1f5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14f1f5be5c21e8e55e9643508070d4918e9e6533)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-084d7a38)
[api-reference/beta/api/alert_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/alert_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alertcomment_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alertcomment_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alertcomment_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

<a id="0817dce4456c16725d5333633847d38f-084d7a38"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml)
 - **Line 12505, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````
 - **Line 13947, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-list-alert_v2.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201040954258856-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T09%3A59%3A29Z&sr=b&sp=r&sig=78bCAvY39%2BnBZha%2BPCbV90u47eqqR8LwJLfW9%2BSO%2Ft0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 15:37 UTC, opbld32 commented
Docs Build status updates of commit _[b215d83](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b215d8364ca70e2fd8b28e461b4085c54b6b1c94)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-cc4ad48c)
[api-reference/beta/api/alert_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/alert_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alertcomment_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alertcomment_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alertcomment_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

<a id="0817dce4456c16725d5333633847d38f-cc4ad48c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml)
 - **Line 12505, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````
 - **Line 13947, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-list-alert_v2.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201041534517708-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T15%3A37%3A56Z&sr=b&sp=r&sig=9ABY1r0WiYiso2dzuhRW28C7IFQGJLhNDLiYLuYpmC4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 15:53 UTC, opbld30 commented
Docs Build status updates of commit _[61c49c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61c49c923094680e692e45e09a38b31d76f6263c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ef517da9)
[api-reference/beta/api/alert_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/alert_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alertcomment_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alertcomment_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alertcomment_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

<a id="0817dce4456c16725d5333633847d38f-ef517da9"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml)
 - **Line 12505, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````
 - **Line 13947, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-list-alert_v2.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201041546052070-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T15%3A53%3A09Z&sr=b&sp=r&sig=aUfurS8ejjCQ8dEUC4cTs9w%2Fwa2vf3PQtAs0TTmKDyA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 15:56 UTC, opbld32 commented
Docs Build status updates of commit _[0f2e4ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f2e4ce65cb6e12d5acdcbf2abe3a880b17a8289)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-9622ba92)
[api-reference/beta/api/alert_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/alert_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alertcomment_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alertcomment_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alertcomment_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

<a id="0817dce4456c16725d5333633847d38f-9622ba92"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml)
 - **Line 12505, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/entitlementmanagement-post-accesspackageassignmentrequests'.`````
 - **Line 13947, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/security-list-alert_v2.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201041554309136-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T15%3A56%3A28Z&sr=b&sp=r&sig=ZIabJ9ss%2BhHKHP%2FosEwDWeltzgXSgAbjp7hnaFOq76s%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 16:17 UTC, opbld34 commented
Docs Build status updates of commit _[0e8e29a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e8e29a385b0cd2a4d91f5403c0c7f6342f88169)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/alert_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/alert_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alertcomment_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alertcomment_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alertcomment_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/alert_v2-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201041609343899-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T16%3A16%3A59Z&sr=b&sp=r&sig=JVQ7ETLgMjj%2FEin2gBf7ZDrX9Wonlhv8mqsowEZq3FU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-23 15:02 UTC, opbld31 commented
Docs Build status updates of commit _[addc237](https://github.com/microsoftgraph/microsoft-graph-docs/commits/addc2374d4b0b7fba26f6c4b7cedaf9fafac5e1e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-089cfc8047ff65aaf0bb5cd0252b62a9-8b69ee56)
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-a7af94eb297701b37758251401086343-8b69ee56)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-8b69ee56)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

<a id="089cfc8047ff65aaf0bb5cd0252b62a9-8b69ee56"></a>
### [api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md)
 - **Line 16, Column 49**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/incident.md'.`````
 - **Line 48, Column 68**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/incident.md'.`````

<a id="a7af94eb297701b37758251401086343-8b69ee56"></a>
### [api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md)
 - **Line 16, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/incident.md'.`````
 - **Line 71, Column 81**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/incident.md'.`````

<a id="e8cef8e3f29f398137f53b89179d8528-8b69ee56"></a>
### [api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md)
 - **Line 63, Column 360**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'alert_v2.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201231500139826-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-23T15%3A02%3A53Z&sr=b&sp=r&sig=LLCmZFAE5o8ZaR%2BhcDvI3r9u%2FV8588KWJPfHT2UZlMM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question i [...]

2022-01-23 20:24 UTC, opbld34 commented
Docs Build status updates of commit _[90582d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/90582d332fdc9812a77478d15ba1399c4c298aa4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-a7af94eb297701b37758251401086343-d77c7ab7)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-d77c7ab7)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

<a id="a7af94eb297701b37758251401086343-d77c7ab7"></a>
### [api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md)
 - **Line 16, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/incident.md'.`````
 - **Line 71, Column 81**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/incident.md'.`````

<a id="e8cef8e3f29f398137f53b89179d8528-d77c7ab7"></a>
### [api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md)
 - **Line 63, Column 360**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'alert_v2.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201232021396842-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-23T20%3A24%3A06Z&sr=b&sp=r&sig=ueYf4UMpdUHZ5xFCT5vi5k2buF%2FKdmik1sLj%2BdcQxZo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-23 20:26 UTC, opbld33 commented
Docs Build status updates of commit _[32a3608](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32a360827fd4760e5da84f1d0d75b794e3ec9504)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201232023274693-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-23T20%3A26%3A27Z&sr=b&sp=r&sig=8uqDBnXyGX%2FH2msnBnagT5e4ZhXyqNIQMnkVI%2Fg0urw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-05 04:59 UTC, opbld30 commented
Docs Build status updates of commit _[270915d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/270915d5989bac46eb89741836b09fbb632159cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202050455569581-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-08T04%3A59%3A05Z&sr=b&sp=r&sig=2vIeEeui4oyV4y%2F8SiKXwc%2BlT0P1MFRv1dKEEwTmUpU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-05 05:36 UTC, angelgolfer-ms commented on api-reference/beta/api/security-incident-get.md
> +  "@odata.type": "microsoft.graph.incident"
Line 68:
To fix this API Doctor error (https://dev.azure.com/msrobots/apidoctor/_build/results?buildId=76116&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dac0b392-2308-5704-b9f7-c5b20adf012e&l=61032):
"Error: get_incident:
      Unable to locate a definition for resource type: microsoft.graph.incident"

please change the type name in this line to microsoft.graph.security.incident (which is defined in line 69 of security-incident.md).

2022-02-05 05:41 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +```
At the end of this file which defines a bunch of enums in your subnamespace, you need to add the following lines:

```
<!--
{
  "type": "#page.annotation",
  "namespace": "microsoft.graph.security"
}
-->
```

See the top of the CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211748/Enums-in-subnamespaces.

2022-02-05 05:49 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +
Line 55:
FYI for properties or nav properties that are defined in a subnamespace, the "Type" column in their respective table must show the fully qualified type name. In the case of line 55, the "Type" column should have the link text microsoft.graph.security.alertComment instead of just alertComment.

See CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211759/OData-subnamespace?anchor=fully-qualify-a-type-name-in-definitions 

Making this change would fix this API Doctor error: https://dev.azure.com/msrobots/apidoctor/_build/results?buildId=76116&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dac0b392-2308-5704-b9f7-c5b20adf012e&l=61038

"Error: microsoft.graph.security.alert/comments:
      Referenced type microsoft.graph.alertComment is not defined in the doc set! Potential suggestion: microsoft.graph.security.alertComment
"

2022-02-05 05:52 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +```
Adding these lines would fix the API Doctor error: https://dev.azure.com/msrobots/apidoctor/_build/results?buildId=76116&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dac0b392-2308-5704-b9f7-c5b20adf012e&l=61035

" Error: microsoft.graph.security.alert/classification:
      Referenced type microsoft.graph.alertClassification is not defined in the doc set! Potential suggestion: microsoft.graph.security.alertClassification"

2022-02-05 05:55 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +```
Similarly, adding these lines would fix the two other API Doctor errors pertaining to the 2 enums alertDetermination and serviceSource defined in security-alert.md.

2022-02-05 05:59 UTC, angelgolfer-ms commented on api-reference/beta/resources/security.md
> +|incidents | [incident](security-incident.md) collection | A collection of incidents in Microsoft 365 Defender, each of which is a set of correlated alerts and associated metadata that reflects the s
Line 29:
In the "Type" column, you need to change the link text to the fully qualified type name, i.e., microsoft.graph.security.incident, not just incident.
Please see the CDK topic:  https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211759/OData-subnamespace?anchor=fully-qualify-a-type-name-in-definitions

2022-02-05 06:02 UTC, angelgolfer-ms commented on api-reference/beta/resources/security.md
> +|secureScores | [secureScore](securescores.md) collection | Measurements of tenants’ security posture to help protect them from threats. |
Line 30:
Please do the similar - since here you're referring to your alert resource in the subnamespace, you need to fully qualify the type name in the "Type" column, i.e., change the link text in the "Type" column to microsoft.graph.security.alert.

You didn't get an API Doctor error for this one because API Doctor assumed (mistook) you to be referring to the old alert resource in the default namespace.

2022-02-05 06:05 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-incident.md
> +```
After line 98:
At the end of this file which defines an enum incidentStatus in your subnamespace, you need to add the following lines:

<!--
{
  "type": "#page.annotation",
  "namespace": "microsoft.graph.security"
}
-->
See the top of the CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211748/Enums-in-subnamespaces.

2022-02-05 06:20 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-incident.md
> +
FYI, in a "Properties" table, where the "Type" column refers to an enum or type that is defined in a subnamespace, the "Type" value needs to be fully qualified. 

Please see the CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211759/OData-subnamespace?anchor=fully-qualify-a-type-name-in-definitions

So for the properties in the above Properties table, if the property type is defined in a subnamespace, including an enum type, please fully qualify the type name.

Also, for lines 35, 38, 43, 44, because the types are enum types defined in a resource file (security-alert.md and security-incident.md), please provide a corresponding link in the "Type" column.

2022-02-05 06:22 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-incident.md
> +|classification|alertClassification|The specification for the incident. Possible values are: `unknown`, `falsePositive`, `truePositive`, `benignPositive`, `unknownFutureValue`.|
Line 35: 
I thought the live beta metadata already exposes these changes?
Anyway, can you confirm if you need to add benignPositive to the metadata?
You have that enum member here but not in the metadata right now.

2022-02-05 06:24 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-incident.md
> +|alerts|[alert](security-alert.md) collection|The list of related alerts. Supports `$expand`.|
Line 62:
Please fully qualify the type name in the "Type" column, since you're referring to the alert resource in a subnamespace.
Right now API Doctor is assuming you're referring to the alert resource in the default namespace.

2022-02-05 06:28 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +
Lines 33-37:
Please do the similar for the "Type" column - fully qualify the name of the enum type.

2022-02-05 06:31 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +
Lines 23-24:
Please make sure the "Return type" column specifies the fully qualified type name of microsoft.graph.security.alert, not just alert, in the link text.

See the CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211759/OData-subnamespace?anchor=fully-qualify-a-type-name-in-definitions

2022-02-05 06:32 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-incident.md
> +
Lines 25-26:
Please make sure the "Return type" column specifies the fully qualified type name of microsoft.graph.security.incident, not just incident, in the link text.

See the CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211759/OData-subnamespace?anchor=fully-qualify-a-type-name-in-definitions

2022-02-05 06:38 UTC, angelgolfer-ms commented on api-reference/beta/resources/security.md
> +|secureScores | [secureScore](securescores.md) collection | Measurements of tenants’ security posture to help protect them from threats. |
Please also move line 30 to after line 27. The properties in a Properties table should be in alphabetical order.
As a heads-up, when your alerts API docs are published, at the same time, content related to the old alert entity should be appropriately marked as deprecated (per the [Deprecate docs](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211775/Deprecate-docs) topic).
In this context of the Properties table, the "Relationship" column of line 27 should look like this:
alerts (deprecated)

2022-02-05 06:45 UTC, angelgolfer-ms commented on api-reference/beta/resources/security.md
>  ms.localizationpriority: medium
Line 4:
BTW, can you please discuss with your PM, that by the time your alerts API docs are published, the "author" field of some of these topics, including this topic, should also finally be updated. The current value of "preetikr" has been out of date. 

This is important because when customers open GitHub issues, those issues get automatically assigned to the GitHub name in the "author" field for response. There are currently 2 issues assigned to preetikr, who I understand doesn't work in this area anymore.

2022-02-05 08:30 UTC, angelgolfer-ms commented on concepts/permissions-reference.md
> +
Line 194-223:
Can you add this content to the existing H2 subsection for security permissions: https://docs.microsoft.com/en-us/graph/permissions-reference#security-permissions

You won't need a subsection title "Alerts_v2 permissions" anymore.

Please follow alphabetical order when inserting the content for your SecurityAlert.* permissions. Where the existing security-related permissions don't follow alphabetical order, please help sort them by alphabetical order as well.

2022-02-05 08:53 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
>                href: api/reportroot-getattacksimulationtrainingusercoverage.md
If not taking into account the old alert resource, and just considering what you're adding for the new alerts API, would it be appropriate and inclusive to refer to the APIs for your new alert and incident resources as the "alerts API"?

If you confirm yes, then instead of having "Incidents" and its list and get actions in lines 14004-14011, with "Incidents" (line 14004) being a peer of "Alerts (preview)" in line 14012, I would suggest having "Alerts (preview)" (note plural) be the parent node label with 2 children nodes "Alert" and "Incident". Their corresponding supported CRUD operations follow.
To plug in the alerts API into the TOC,

2022-02-05 09:00 UTC, angelgolfer-ms commented on concepts/permissions-reference.md
> +## Incidents permissions
Lines 1165-1195:
Can you please integrate the new alerts API and incidents API as peers under the "security permissions" section, make sure to order those permissions  alphabetically? Thanks.

2022-02-05 09:09 UTC, angelgolfer-ms requested changes
@BenAlfasi , can you please take a look at my comments and address them? 
After you address them I'll take another look. 

Thanks.

2022-02-14 14:33 UTC, BenAlfasi commented on api-reference/beta/resources/security.md
>  ms.localizationpriority: medium
Can I set the new PM alias? (michash)

2022-02-14 14:40 UTC, BenAlfasi commented on api-reference/beta/toc.yml
>                href: api/reportroot-getattacksimulationtrainingusercoverage.md
We don't think its a good idea to put the Alert & Incidents under "Alerts" title..

2022-02-21 15:25 UTC, opbld32 commented
Docs Build status updates of commit _[531ba93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/531ba935dba982d3bd739a9c15cbdac45bfd5f67)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202211518448151-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-24T15%3A25%3A25Z&sr=b&sp=r&sig=DLUyII8Yw%2BcT5eg%2BnL0U975%2FL4vPIM%2BqT%2B3ZfvM3riE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-22 12:13 UTC, BenAlfasi commented on api-reference/beta/resources/security.md
>  ms.localizationpriority: medium
@angelgolfer-ms ?

2022-02-22 12:54 UTC, opbld33 commented
Docs Build status updates of commit _[3b9ffa6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b9ffa66c9c3d8f24972a0c9753de68ef3ba9309)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202221251232251-14745%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-25T12%3A54%3A40Z&sr=b&sp=r&sig=gb3walAP03yToJC5SOJsf%2BZ%2FSm4ZadYvOfEF608kJHk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-08 04:15 UTC, angelgolfer-ms commented on api-reference/beta/resources/security.md
>  ms.localizationpriority: medium
@BenAlfasi , yes, if that's the GitHub name that you guys decided, please set that author value for all the topics your team owns. Sorry for the tardiness in responding, it's been more than a bit busy.

2022-03-08 04:25 UTC, angelgolfer-ms commented on api-reference/beta/resources/security.md
> +|alerts (deprecated)|[alert](../resources/alert.md) collection|Notifications for suspicious or potential security issues in a customer’s tenant.|
Line 27:
Marking the published alert resource here as "deprecated" is the first step to clarifying why there are two "alerts" nav property. We need to accompany this with more details like we talked about before, or else existing customers would be unpleasantly surprised and place a lot of support calls. We should continue this conversation offline.

2022-04-20 19:33 UTC, opbld32 commented
Docs Build status updates of commit _[6743feb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6743feb906c245fcceaea092106973f4f6f6c7b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204201929427095-14745%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T19%3A33%3A10Z&sr=b&sp=r&sig=qW7ioDAb0WHh%2FA8kulEktEzC4mseka0bTTZBaRrfves%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-14 02:45 UTC, opbld33 commented
Docs Build status updates of commit _[c2e6130](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2e613087a1baa9bd6ecacaf68b574d13193844b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[changelog/Microsoft.M365.Defender.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/changelog/Microsoft.M365.Defender.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14745) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205140243264120-14745/BuildReport?accessString=072887229e5adb73028bf7d95f8ed98dfbc2d7625e5a37eef5f55bb86465c36e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-07 12:37 UTC, opbld31 commented
Docs Build status updates of commit _[4dae0c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4dae0c5e2bd19d7cc8af254d3604e75f8f2822d0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-alertevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e53f4a3ef4072c58d3c2a3e9687abc5d-1d305863)
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-deviceevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-828f0b724563bd4f854382e02082bb04-1d305863)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-1d305863)
[api-reference/beta/resources/security-mailboxevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-mailboxevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-mailboxevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-2db9c0fc1701e767807e6aef6a4aef88-1d305863)
[api-reference/beta/resources/security-mailclusterevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-mailclusterevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-mailclusterevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-2a8b86e5afe472cec6d57240b9412fb4-1d305863)
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-1d305863)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-oauthapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-oauthappli [...]

2022-06-21 06:40 UTC, opbld31 commented
Docs Build status updates of commit _[62d8231](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62d82311ece31b0bbe396d4efebfc43d34e603ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e53f4a3ef4072c58d3c2a3e9687abc5d-88a499d0)
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-828f0b724563bd4f854382e02082bb04-88a499d0)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-88a499d0)
[api-reference/beta/resources/security-mailboxevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-mailboxevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-mailboxevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-2db9c0fc1701e767807e6aef6a4aef88-88a499d0)
[api-reference/beta/resources/security-mailclusterevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-mailclusterevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-mailclusterevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-2a8b86e5afe472cec6d57240b9412fb4-88a499d0)
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-88a499d0)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentAp [...]

2022-06-30 07:04 UTC, opbld32 commented
Docs Build status updates of commit _[23497f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23497f25e264fec315946b07f42cef08cd622004)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-68368e5f)
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e53f4a3ef4072c58d3c2a3e9687abc5d-68368e5f)
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-828f0b724563bd4f854382e02082bb04-68368e5f)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-68368e5f)
[api-reference/beta/resources/security-mailboxevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-mailboxevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-mailboxevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-2db9c0fc1701e767807e6aef6a4aef88-68368e5f)
[api-reference/beta/resources/security-mailclusterevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-mailclusterevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-mailclusterevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-2a8b86e5afe472cec6d57240b9412fb4-68368e5f)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resourc [...]

2022-06-30 07:07 UTC, BenAlfasi commented on api-reference/beta/resources/security.md
>  ms.localizationpriority: medium
@angelgolfer-ms  - Michael is out. I want to add Naama here, what she needs to do in order to get a GitHub name?

2022-06-30 07:31 UTC, opbld34 commented
Docs Build status updates of commit _[6aaf11f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6aaf11f1379f6ca9ac5d402c8b59ecb52c39c552)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-b663e826)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-b663e826)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b663e826)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-mailboxevidence.md](https: [...]

2022-06-30 07:51 UTC, opbld31 commented
Docs Build status updates of commit _[8e76c30](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e76c307730d13a63037b25427b3f1c4d7a69150)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-73003cb8)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-73003cb8)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-mailboxevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-mailboxevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-mailboxevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-mailcl [...]

2022-06-30 07:55 UTC, opbld30 commented
Docs Build status updates of commit _[8a49116](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a4911643019d06223a37e3a771dc2f7f309c09f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-eeb2b070)
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e53f4a3ef4072c58d3c2a3e9687abc5d-eeb2b070)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-eeb2b070)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-mailboxevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-mailboxevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-mailboxevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-re [...]

2022-06-30 08:45 UTC, opbld33 commented
Docs Build status updates of commit _[6a0b387](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a0b387beaab5410a14ed2198ee2e121be60b3cf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-53a36e1720796127250c68a18df8d969-8b17d18d)
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-8b17d18d)
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e53f4a3ef4072c58d3c2a3e9687abc5d-8b17d18d)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-8b17d18d)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch= [...]

2022-06-30 09:13 UTC, opbld34 commented
Docs Build status updates of commit _[85fc3ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85fc3eec94e436f7dce7d4a6c9bdc2964d9c628d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-0792e753)
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e53f4a3ef4072c58d3c2a3e9687abc5d-0792e753)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-0792e753)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resourc [...]

2022-07-09 04:45 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +
Lines 134-151:
FYI, I am going to make some edits to the descriptions. I'll call out the ones that I updated but am not sure and would like you to confirm, and also ones that I think would be good if you can directly make clarifications to the descriptions.

2022-07-09 04:51 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +| cloudAppSecurity               | Cloud App Security.                                          |
Line 144:
Why is "Cloud App Security" in title case? Is that a Microsoft service? I searched using Bing and don't see a Microsoft product or service by that name.
Do you mean Microsoft Defender for Cloud Apps, or do you mean a generic term "Cloud app security" which should be sentence case?
FYI, see the Microsoft Cloud + AI Style Guide for capitalization: https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25357

2022-07-09 05:06 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +| unknownFutureValue             | unknownFutureValue for evolvable enums pattern.              |
Line 151:
FYI, for evolvable enums that you decide to document with descriptions, all unknownFutureValue enum members should  have the same description "Evolvable enumeration sentinel value. Do not use."
See CDK topic:  https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations?anchor=step-2%3A-add-clarification-if-unknownfuturevalue-is-the-last-defined-member

2022-07-09 05:23 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +### detectionSource values
Line 125:
Is that app governance add-on for Microsoft Defender for Cloud Apps?
If so, can you change the description to "App governance add-on for Microsoft Defender for Cloud Apps."

For now, I changed that description to "App governance."  I didn't find "Microsoft App Governance" as a service or product name when I did a search on Bing.

2022-07-09 05:37 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +title: "alert_v2 resource type"
Lines 2 and 11:
FYI we can't change the topic title to alert_v2 when the name of the resource is indeed alert. 
Doing so would be confusing to customers; we have set up the expectations for customers with our topic title rules.(That's why I have been requesting you or your team to create some content to differentiate the two alert resources.)

FYI I am changing the lines back to using the actual resource name alert.
(We can ignore the build warning about the same topic title as the other alert resource topic for now.)

2022-07-09 05:41 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
Line 23:
The topic title for "list" operations follows the rule "List {nav property name}".
See the CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title

FYI I am changing that topic title in this file and in the security-list-alerts.md topic as "List alerts_v2".

2022-07-09 05:46 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
Line 23:
As for the filename for list operations:
The filename pattern is {parententityname}-list-{navigationpropertyname}.md. See the CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211751/File-naming

Please change the filename to security-list-alerts_v2.md, and fix links to that file.

If Graph Studio generated the filename security-list-alerts.md, then please file a bug. See where to file bugs: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211778/Graph-doc-stub-generator-tool?anchor=questions-or-concerns

2022-07-09 07:16 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
>  |alertWebUrl|String|URL for the alert page in Microsoft 365 Defender portal.|
Line 47:
Can you confirm the incidentWebUrl is really the URL for the alert page? If that's true, then aren't alertWebUrl and incidentWebUrl always the same?
If that's not true, please update the description for incidentWebUrl.

2022-07-09 07:28 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
>  |firstActivityDateTime|DateTimeOffset|The earliest activity associated with the alert.|
Line 49:
FYI I am changing the description of the threatDisplayName property to be "The threat associated with this alert.". That is, changing "The thread..." to "The threat..."

2022-07-11 07:45 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-api-overview.md
> +-Microsoft Dala Loss Prevention
Line 72:
Is this Microsoft Purview Data Loss Prevention (https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-learn-about-dlp?view=o365-worldwide)?
If so, please update line 72 as such. That's the only microsoft-related search result on the first page when I looked for "Microsoft Data Loss Prevention" on Bing. 
(Then Azure, Exchange each has its DLP.)

2022-07-11 21:02 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alertevidence.md
> +| unknownFutureValue           | unknownFutureValue for evolvable enums pattern.                      |
Line 37 and GLOBAL:
FYI, there is a default description we use for unknownFutureValue - "Evolvable enumeration sentinel value. Do not use.".
I have updated the description for each unknownFutureValue in this topic. Please see if there are other topics that need updating and do the replacement. Thanks.
CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations?anchor=step-2%3A-add-clarification-if-unknownfuturevalue-is-the-last-defined-member

2022-07-13 01:30 UTC, opbld30 commented
Docs Build status updates of commit _[a603122](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a6031223990ed02ef3af708cd2d8c58804b28976)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-076ae656)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-mailboxevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta [...]

2022-07-13 01:32 UTC, opbld31 commented
Docs Build status updates of commit _[47cb14d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/47cb14dac0d32296d834557b1cba560e5f406f86)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-83ef461a)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-incident.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-incident?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-ipevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-ipevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-ipevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-mailboxevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta [...]

2022-07-13 01:58 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alertevidence.md
> +|remediationStatus|evidenceRemediationStatus|Status of the remediation action taken. The possible values are: `none`, `remediated`, `prevented`, `blocked`, `notFound`, `active`, `pendingApproval`, `d
FYI I fixed lines 23 and 25 for you by adding a link to the corresponding H3 section that define the enum.
For line 27, looks like that's an oversight. The following are your choices:

(A) Per the CDK topic I referred to above - if the descriptions of the members of evidenceAlert enum are meaningful, then you can follow what you have done in this topic for the other enums. 

(B) If the _descriptions_ of the members are intuitive and don't need to be documented explicitly, then you should create a new file enums_security.md and just include a table column of the members without their descriptions. That enums_security.md file is not meant to be customer-facing, but to serve API Doctor. This is in the CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211748/Enums-in-subnamespaces?anchor=first-option%3A-in-a-general-enums-file-for-that-subnamespace


For now, FYI, to get rid of this API Doctor error so that the OPS build can succeed and I can see my updates on the
staging site, I am just going to use the approach (A). Can you PLEASE make sure you either persist (A) and add the descriptions for the enum members, OR delete the table I add for (A) and follow (B)?

Thanks.

2022-07-13 02:07 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-deviceevidence.md
> +|Property|Type|Description|
Lines in the range 24 to 38:
FYI I am fixing some pre-existing API Doctor errors you incurred for the properties that are of enum type. That's so I can build successfully and see my doc updates on the staging site.

2022-07-13 02:47 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-fileevidence.md
> +|detectionStatus|detectionStatus|The status of the detection.The possible values are: `detected`, `blocked`, `prevented`, `unknownFutureValue`.|
Line 25:
FYI there's an API Doctor error for the type in this line because the enum is not defined anywhere in the docs.
Since the enum detectionStatus is shared by the fileEvidence and processEvidence resources, AND looks like to me the enum members are somewhat self-explanatory, I took the liberty to document detectionStatus in a non-customer-facing enum file for the security namespace, enums-security.md (I created that file because no one had used this approach to document enums defined in the security subnamespace yet.)

FYI this follows this CDK guidance: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations?anchor=step-1%3A-document-the-basics

If in case it turns out there are details to some of the enum members that you'd like to make customer-facing, then you'd have to change the approach and document it I suppose in perhaps alertevidence.md, the common base type file shared by the two resources fileEvidence and processEvidence. That would be this approach in step (b) in the CDK section:  https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations?anchor=step-2%3A-add-clarification-if-unknownfuturevalue-is-the-last-defined-member

2022-07-13 02:48 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-processEvidence.md
> +|detectionStatus|detectionStatus|The status of the detection.The possible values are: `detected`, `blocked`, `prevented`, `unknownFutureValue`.|
Line 24:
FYI there's an API Doctor error for the type in this line because the enum is not defined anywhere in the docs.
Since the enum detectionStatus is shared by the fileEvidence and processEvidence resources, AND looks like to me the enum members are somewhat self-explanatory, I took the liberty to document detectionStatus in a non-customer-facing enum file for the security namespace, enums-security.md (I created that file because no one had used this approach to document enums defined in the security subnamespace yet.)

FYI this follows this CDK guidance: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations?anchor=step-1%3A-document-the-basics

If in case it turns out there are details to some of the enum members that you'd like to make customer-facing, then you'd have to change the approach and document the enum in perhaps alertevidence.md, the common base type file shared by the two resources fileEvidence and processEvidence. That would be this approach in step (b) in the CDK section: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations?anchor=step-2%3A-add-clarification-if-unknownfuturevalue-is-the-last-defined-member

2022-07-13 02:51 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-vmmetadata.md
> +|cloudProvider|vmCloudProvider|The cloud provider hosting the virtual machine.The possible values are: `unknown`, `azure`, `unknownFutureValue`.|
Line 22:
There's an API Doctor error for not linking the type vmCloudProvider to the H3 section. I added the link to work toward 0 API Doctor errors to let the build succeed, stage my updates, and continue with my review.

2022-07-13 02:57 UTC, angelgolfer-ms commented on api-reference/beta/api/security-alert-update.md
> +{
Between lines 93 and 94:
FYI there's an API Doctor error because it's depending on parsing an empty line to know the beginning of the response body. I have fixed this error on your behalf to let the build succeed.
In case you wonder what the [error message](https://dev.azure.com/msrobots/apidoctor/_build/results?buildId=89656&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dac0b392-2308-5704-b9f7-c5b20adf012e&l=96461) looks like:

Error: update_alert_v2:
      Exception while parsing HTTP response
      Response contains an invalid header definition: '{'. Missing whitespace between the headers and body?

2022-07-13 03:28 UTC, angelgolfer-ms commented on api-reference/beta/api/security-incident-update.md
> +  "truncated": true
Lines 88-89:
FYI there was an API Doctor error because this section typically should include a response type, a line like this:

`"@odata.type": "microsoft.graph.security.incident",`

I added that line to get rid of this error so to let the build succeed and let me see my updates on the staging site. It would also facilitate your incorporating other review feedback as well.

2022-07-13 05:14 UTC, opbld30 commented
Docs Build status updates of commit _[891940e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/891940e88273c3f620e363b3391fd940ecdff95d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-87164100)
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e53f4a3ef4072c58d3c2a3e9687abc5d-87164100)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-87164100)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/securi [...]

2022-07-13 05:32 UTC, opbld32 commented
Docs Build status updates of commit _[825ee1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/825ee1b0ec38275be50528bf9d97f7457a7f611b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-94e278ac)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-94e278ac)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/micros [...]

2022-07-13 05:43 UTC, opbld31 commented
Docs Build status updates of commit _[98be633](https://github.com/microsoftgraph/microsoft-graph-docs/commits/98be633146b0851652d5f41fc40e3ee4e9b8538e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-4d7ee6d2)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-4d7ee6d2)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/micros [...]

2022-07-27 07:30 UTC, opbld32 commented
Docs Build status updates of commit _[5612d5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5612d5de532aeea69b794381f57794e3932d05cb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-a44536bc)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-a44536bc)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-incident.md](https://github.com/microsoftgraph/micros [...]

2022-07-27 08:43 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +| microsoftDataLossPrevention  | Microsoft Data Loss Prevention                 |
Line 127:
FYI I'm changing the description to "Microsoft Purview Data Loss Prevention". Saw that in Naama's email reply on 7/27.

2022-07-28 01:53 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alertevidence.md
> +
Line 17:
FYI I'm rephrasing this description to put evidence as the subject:
"Evidence related to an alert."

2022-07-28 01:54 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alertevidence.md
> +`unknown`, `suspicious`, `malicious`, `noThreatsFound`, `unknownFutureValue`.
Line 99:
FYI I'm cleaning up this stray/ leftover line likely from copying and pasting.

2022-07-28 08:39 UTC, opbld32 commented
Docs Build status updates of commit _[b7dc475](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b7dc4759a47f263d55acda9f8c0fe8154fabcd23)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-fd39db8a)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-fd39db8a)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-fd39db8a)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/securi [...]

2022-07-28 08:41 UTC, opbld34 commented
Docs Build status updates of commit _[8c1f883](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c1f88312f5232cba4edab7f7be17d7d7ffccc47)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-a5549f08)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-a5549f08)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-a5549f08)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/securi [...]

2022-07-28 08:49 UTC, opbld32 commented
Docs Build status updates of commit _[c061187](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c061187f01344148c61cd25241468f5868359c70)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-62b65558)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-62b65558)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-62b65558)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/securi [...]

2022-07-28 21:07 UTC, opbld31 commented
Docs Build status updates of commit _[f814310](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8143102e6036a0da0e152b94d9486f1229c0ba6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-9db2abaa)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-9db2abaa)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-9db2abaa)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/securi [...]

2022-07-28 23:14 UTC, opbld33 commented
Docs Build status updates of commit _[e925621](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e9256213869e8c01c49e391a2c373746506e01d9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-1cc2abe3)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-1cc2abe3)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-1cc2abe3)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/securi [...]

2022-07-28 23:57 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +Represents potential security issues within a customer's tenant that Microsoft 365 Defender has identified.
Line 17:
This question is about the phrase "... that Microsoft 365 Defender has identified".

@BenAlfasi , in those cases where the source of the alert is not a service in Microsoft 365 Defender, like Microsoft Purview DLP, the security provider that identified the alert would not be Microsoft 365 Defender, is that right?

If that's the case, please change that phrase to something like  "... that a security provider which is part of or integrated with Microsoft 365 Defender identified."

2022-07-29 00:22 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +When a threat is detected, alerts are created in the system for an analyst to investigate. Alerts with the same attack techniques or attributed to the same attacker are aggregated into an entity call
Line 19:
Can we use active voice for the first 2 sentences?  In general, for doc writing, we avoid using passive voice as it masks out the subject making who-does-what unclear.

For example, would it be correct to change the first 2 sentences and form the following paragraph:
When detecting a threat, a security provider creates an alert in the system. Microsoft 365 Defender pulls this alert data from the security provider, and consumes the alert data to return valuable clues in an **alert** resource about any related attack, impacted assets, and associated [evidence](security-alertevidence.md). It automatically correlates other alerts with the same attack techniques or the same attacker into an [incident](security-incident.md) to provide a broader context of an attack. Aggregating alerts in this manner makes it easy for analysts to collectively investigate and respond to threats.

2022-07-29 00:27 UTC, angelgolfer-ms commented on api-reference/beta/api/security-alert-get.md
> +# Get alert_v2
Line 11:
FYI I changed the topic title to "Get alert". 
The topic title pattern is "Get {resource name}". Please see the CDK section: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title?anchor=toc-and-topic-titles

2022-07-29 00:44 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
>  |assignedTo|String|Owner of the incident, or null if no owner is assigned.|
Line 45:
Is that "owner of the incident" or "owner of the alert"?
If it's (always) the former, then is it true that no matter whether Microsoft 365 Defender identifies _other_ alerts to form an incident or not, a single alert can still form an incident and therefore this assignedTo property is applicable?

2022-07-29 00:48 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
>  |firstActivityDateTime|DateTimeOffset|The earliest activity associated with the alert.|
Line 52:
Is the createdDateTime property the time when the security provider product created the alert, not the time that Microsoft 365 Defender created this **alert** resource?

2022-07-29 00:50 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
>  |firstActivityDateTime|DateTimeOffset|The earliest activity associated with the alert.|
Similar question for each of lastUpdateDateTime and resolvedDateTime - would that be the **alert** resource in these cases, or the alert that the security provider created in their product?

2022-07-29 00:56 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +| smartScreen                    | Smart Screen.                                                |
Line 137:
Am I assuming correctly this is Microsoft Defender SmartScreen - https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview?
FYI I am changing the description to "Microsoft Defender SmartScreen". Please correct of it's wrong.

2022-07-29 01:01 UTC, opbld31 commented
Docs Build status updates of commit _[6c2296b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c2296bb77e96573906e449913ebfe66cb6db898)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-eddff3bf)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-eddff3bf)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-eddff3bf)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-fileevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-fileevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/securi [...]

2022-07-29 07:56 UTC, opbld30 commented
Docs Build status updates of commit _[527b234](https://github.com/microsoftgraph/microsoft-graph-docs/commits/527b234f7592b5569f31712a0c27f653676e0714)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-f99497fc)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-f99497fc)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-f99497fc)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/micr [...]

2022-07-30 00:27 UTC, opbld30 commented
Docs Build status updates of commit _[aa21b69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa21b697212e83efa761a881aabe9817b21a2b95)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-8526cafa)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-8526cafa)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-8526cafa)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/micr [...]

2022-07-30 00:50 UTC, opbld30 commented
Docs Build status updates of commit _[d136d7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d136d7f481928c6041caca9fe80991f7bdf6f9b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-d4ecb037)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-d4ecb037)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-d4ecb037)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/micr [...]

2022-07-30 01:06 UTC, angelgolfer-ms commented on api-reference/beta/api/security-list-alerts.md
> +# List alerts_v2
Line 16:
I'm trying to make this generated description a bit more helpful than just describing what a typical list operation does regardless of the feature or resource :-). FYI I'm making the following minor changes in the first 2 sentences. Please let me know and correct the description if it overlooks something:

Get a list of [alert](../resources/security-alert.md) resources that have been created to track suspicious activities in an organization.
This operation lets you filter and sort through alerts to create an informed cyber security response...

2022-07-30 01:23 UTC, angelgolfer-ms commented on api-reference/beta/api/security-alert-get.md
> +Retrieve the properties and relationships of an [alert](../resources/security-alert.md) object.
Line 16:
@BenAlfasi , is this using the id property (since there are 2 ID kind of properties, id and providerAlertId)?
FYI I have changed the description to be unambiguous to say "... by specifying a value for the **id** property."

Please update the description if that's incorrect.

2022-07-30 01:28 UTC, angelgolfer-ms commented on api-reference/beta/api/security-alert-get.md
> +```
Line 59, 78, 79:
Is the ID specified in the segment after /alerts_v2/ supposed to match the id property in the example response (line 78)?

Please adjust the example, or if that's actually correct, then please clarify in the description (line 16) what to specify in the query request.

2022-07-30 01:31 UTC, angelgolfer-ms commented on api-reference/beta/api/security-alert-get.md
> +```
Also, please note that for all example requests that entail some sort of an ID indexing into a collection, we need to specify that ID value in a sampleKeys property.
FYI I'm adding that on your behalf for this example, assuming that the value to use in the example request remains da637578995287051192_756343937.
If you change that value in the example request, please make sure to update the sampleKeys property as well.

2022-07-30 01:37 UTC, angelgolfer-ms commented on api-reference/beta/api/security-alert-update.md
> +
Line 16, 64, 69:
FYI I made a couple of updates to this description similar to the GET operation - I specified to use the id property. 
I also specified a real-looking ID value in the example request that matches the id value in the example response, and added that to the sampleKeys property.
If that's incorrect, please adjust accordingly in these places.
Also please make sure

2022-07-30 01:42 UTC, angelgolfer-ms commented on api-reference/beta/api/security-incident-get.md
> +  "blockType": "request",
Line 59:
FYI I replaced the placeholder ID in curly brackets by 2972395, to match the id property in the example response.
I also added the sampleKeys property for the example request.

For more info, see https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211782/Set-up-for-API-Doctor-validation?anchor=id-values-in-example-requests

2022-07-30 01:44 UTC, angelgolfer-ms commented on api-reference/beta/api/security-incident-get.md
> +  "blockType": "request",
FYI, I did the same for the example in security-incident-update.md.
If using the id property value in the request is incorrect, please adjust.

2022-07-30 01:59 UTC, angelgolfer-ms commented on api-reference/beta/api/security-list-incidents.md
> +Get a list of the [incident](../resources/security-incident.md) objects and their properties.
Lines 16, 17:
Since the description basically is the same as that for security-list-alerts.md, FYI I proactively updated the description here to relate incidents with alerts, just so customers didn't think that there's a mixup and they end of seeing almost the same descriptions for the 2 list operations.

2022-07-30 02:03 UTC, opbld31 commented
Docs Build status updates of commit _[c28c994](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c28c99470959c63a2dc2e88a1fa8bef3b342866d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-4bb7bd3a)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-4bb7bd3a)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-4bb7bd3a)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/micr [...]

2022-07-30 06:55 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-incident.md
> +
Line 27:
FYI I added the PATCH operation to the Methods table on your behalf, since security-incident-update.md exists.

2022-07-30 07:05 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +
Line 28:
FYI I added the PATCH operation to the Methods table on your behalf, since security-alert-update.md exists.

2022-07-30 07:53 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +|serviceSource|[microsoft.graph.security.serviceSource](#servicesource-values)|The service or product that created this alert. Possible values are: `microsoftDefenderForEndpoint`, `microsoftDefenderF
Lines 38 and 39:
How can we make the descriptions not repeat the name of the properties but instead clarify what these 2 properties mean?
I'm making some guesses here, but wonder if you can come up with something more accurate or helpful.
For classification, can we say:
"Specifies whether the alert represents a true threat."
For determination, can we say:
"Specifies the result of the investigation, whether the alert represents a true attack and if so, the nature of the attack."

I didn't update these descriptions because I'm not very sure what I'm overlooking. 
Can you please make adjustments where necessary and update the descriptions for these 2 properties?

2022-07-30 08:10 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          - name: User Evidence
Lines 14851-14878 (i.e. all the derived types):
Can you please organize this part of the TOC to go alphabetically? 
You can leave the base type (14849-14850) at the top of this part of the TOC though.

2022-07-30 08:15 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alertevidence.md
> +
Insert new paragraph after line 18:
Please list the inherited types here. Something like:
"This is the base type of {list and link to each of the derived types}."

2022-07-30 08:29 UTC, opbld34 commented
Docs Build status updates of commit _[f8a9538](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8a9538a3acda3f6cd8cefd4bba3957336b9123c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-8ad94a30)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-8ad94a30)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-8ad94a30)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/micr [...]

2022-08-04 07:06 UTC, opbld32 commented
Docs Build status updates of commit _[7bfec47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7bfec473bf4c1f57ba3ec5569948975b12a8c874)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-13d3c9c9)

<a id="13d3c9c9"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208040706121294-14745/BuildReport?accessString=4f67d3ed57aa530bd98ecb7c3e4a8c7fddcb8a27d35f5b9cab8dde665d77002a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 23:25 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          - name: User evidence
Lines 14814-14841:
@BenAlfasi , can you please reorder these derived types in alphabetical order?

2022-08-04 23:30 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alertevidence.md
> +
Also, FYI usually we expose only entities and their methods in the TOC and not complex types. I see that in some cases like evidence which I perceive as one important aspect of these new alerts, we would want to expose evidence types in the TOC as well. For that reason, I added a paragraph to illustrate the usefulness with a hypothetical example. Can you please take a look at that paragraph, and supplement or correct it where appropriate?

2022-08-04 23:57 UTC, opbld32 commented
Docs Build status updates of commit _[9acaafd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9acaafd4c09e4c830bf815580d773441763f5fab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-e93c3545)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-e93c3545)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-e93c3545)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-e93c3545)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-gr [...]

2022-08-05 00:59 UTC, opbld33 commented
Docs Build status updates of commit _[ba16a2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba16a2b371e358420f6489fbaf4bbe951f02a88e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-bb500ac6)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-bb500ac6)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-bb500ac6)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-bb500ac6)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-gr [...]

2022-08-05 01:43 UTC, opbld33 commented
Docs Build status updates of commit _[81e1350](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81e1350fad28089516989223f6beabc80fc9175a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-d86545ac)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-d86545ac)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-d86545ac)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/micr [...]

2022-08-05 01:53 UTC, opbld34 commented
Docs Build status updates of commit _[1afd894](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1afd894aa658bc2f0c2255081848da9ac91f612b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-0c84b7dc)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-0c84b7dc)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-0c84b7dc)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/micr [...]

2022-08-05 02:08 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-analyzedmessageevidence.md
> +|antiSpamDirection|String|Direction of the email relative to your network: Inbound, Outbound, Intra-org.|
@BenAlfasi , are "Inbound, Outbound, Intra-org" the possible string values, even though we're not exposing an enum for them? Do they start with upper case letters?
To document the supported string values, please use this sentence structure, enclose the strings in tick marks, and make sure to reflect the appropriate upper or lower case:
"Possible values: `Inbound`, `Outbound`, `Intra-org`."

2022-08-05 02:11 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-analyzedmessageevidence.md
> +|antiSpamDirection|String|Direction of the email relative to your network: Inbound, Outbound, Intra-org.|
Please apply the same treatment to line 27 as well.

2022-08-05 02:21 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-deviceevidence.md
> +|deviceDnsName|String|The FQDN (Fully Qualified Domain Name) for the device.|
Line 26 and GLOBAL:
FYI for a majority of acronyms, Microsoft Writing Style Guide doesn't want us to use the acronym on first mention, but instead require us to first spell out the full name and then put the acronym in parentheses.
For cut out the review iterations and overall review time, I have made these adjustments on your behalf. Also, often the full names do not have to be capitalized, and following the capitalization guidelines, we don't capitalize the full names.

2022-08-05 02:38 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-deviceevidence.md
> +|rbacGroupId|Int32|RBAC (Role Based Access Control) device group id.|
Lines 34-35:
Usually to reduce ambiguity for localization, we don't want to have 3 or more nouns in a row.
For these 2 RBAC-related properties, is it correct to reorganize the description as, say for rbacGroupId, "The ID of the role-based access control (RBAC) device group"?
Or is it "The group ID of the role-based access control (RBAC) device"?

Please adjust if necessary. I updated these 2 descriptions to follow the first pattern.

2022-08-05 02:43 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-vmmetadata.md
> +
The case, spelling, and a boilerplate sentence are pretty messed up here. 
To reduce turnaround, FYI I'm fixing them on your behalf. Normally, authors are their own editors :-)

2022-08-05 02:51 UTC, opbld32 commented
Docs Build status updates of commit _[2ae4610](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ae461070bdbba45b0120ccae25f53f86989f406)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-8f567722)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-8f567722)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-8f567722)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/micr [...]

2022-08-05 06:06 UTC, opbld31 commented
Docs Build status updates of commit _[688a403](https://github.com/microsoftgraph/microsoft-graph-docs/commits/688a403cffe875deda01fe4a031599ff0994eb4c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-be67c60a6da3d9d1138a3231d10208a2-c6d58950)
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-c6d58950)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-c6d58950)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-c6d58950)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/securit [...]

2022-08-05 06:08 UTC, opbld33 commented
Docs Build status updates of commit _[6f247a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f247a1826b7c24979518328770c5bb73b7db7b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-be67c60a6da3d9d1138a3231d10208a2-aed77352)
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-aed77352)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-aed77352)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-aed77352)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/securit [...]

2022-08-05 06:16 UTC, opbld34 commented
Docs Build status updates of commit _[0841c9e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0841c9ef91d66a4fa0e12b0abc78874e4b56ac99)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-f06e9af5)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-f06e9af5)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-f06e9af5)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/micr [...]

2022-08-05 06:27 UTC, opbld31 commented
Docs Build status updates of commit _[2365b12](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2365b1296248de97297ff3c8b59292abaf2648af)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-b5113cb8)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-b5113cb8)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-b5113cb8)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/micr [...]

2022-08-05 07:07 UTC, angelgolfer-ms requested changes
Hi @BenAlfasi , I made and noted as comments a few direct updates to your PR, that are either for your info, or require you to confirm and adjust where necessary. I also commented areas where you should please address.  Thanks!

2022-08-09 06:53 UTC, opbld31 commented
Docs Build status updates of commit _[9d16c1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d16c1e16c96b41de11acdb410dafa07bfdebabc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-3d74b15d)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-3d74b15d)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-3d74b15d)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/micr [...]

2022-08-10 04:02 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-alert.md
> +|id|String|Unique identifier to represent the **alert** resource.|
@BenAlfasi , can you please organize the table rows by alphabetical order of the property names?
That's to allow customers to scan and discover properties more quickly, and for consistency.

2022-08-10 04:04 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-emailsender.md
> +|Property|Type|Description|
Lines 22-24, and GLOBAL:
Please organize properties by alphabetical order, and end descriptions with a period.
Please make sure the Properties tables in other topics follow the same.

2022-08-15 13:55 UTC, BenAlfasi commented on api-reference/beta/resources/security-alertevidence.md
> +
Looks great! Ty!

2022-08-15 14:14 UTC, BenAlfasi commented on api-reference/beta/resources/security-vmmetadata.md
> +
TY!

2022-08-15 14:14 UTC, BenAlfasi commented on api-reference/beta/toc.yml
> +          - name: User evidence
done

2022-08-15 14:23 UTC, opbld33 commented
Docs Build status updates of commit _[a8d38c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8d38c8cb1a793c6108185d14b42af939ae6a350)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-9cbf7db3)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-9cbf7db3)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-9cbf7db3)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/micr [...]

2022-08-15 14:37 UTC, BenAlfasi commented on api-reference/beta/resources/security-alert.md
> +|serviceSource|[microsoft.graph.security.serviceSource](#servicesource-values)|The service or product that created this alert. Possible values are: `microsoftDefenderForEndpoint`, `microsoftDefenderF
took your great suggestion :)

2022-08-15 14:39 UTC, BenAlfasi commented on api-reference/beta/resources/security-alert.md
>  |firstActivityDateTime|DateTimeOffset|The earliest activity associated with the alert.|
its Microsoft 365 Defender created time, thanks! updating.

2022-08-15 14:40 UTC, BenAlfasi commented on api-reference/beta/resources/security-alert.md
> +### detectionSource values
It shouldn't be related to cloud apps. lets leave it as is.

2022-08-15 14:43 UTC, BenAlfasi commented on api-reference/beta/resources/security-alert.md
> +
ok :)

2022-08-15 14:50 UTC, BenAlfasi commented on api-reference/beta/resources/security-deviceevidence.md
> +|Property|Type|Description|
ty!

2022-08-15 14:55 UTC, opbld32 commented
Docs Build status updates of commit _[6607c4e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6607c4e374b047d4383805703b18591613732dcb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-8f602c88)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-8f602c88)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-8f602c88)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftg [...]

2022-08-15 15:18 UTC, opbld32 commented
Docs Build status updates of commit _[1280c0a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1280c0a83bf17ebfb26d38e10333f6bb05ca23cd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-d7fe522f)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-d7fe522f)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-d7fe522f)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftg [...]

2022-08-17 04:14 UTC, angelgolfer-ms commented on api-reference/beta/resources/security-analyzedmessageevidence.md
>  |networkMessageId|String|Unique identifier for the email, generated by Microsoft 365.|
For lines 24, 26, 27:
@BenAlfasi , can you confirm if those possible values for the 3 properties must start with an upper case letter?
In Microsoft Graph, string constants should use camel case (with the first letter of the string a lower case letter).

2022-08-17 06:32 UTC, angelgolfer-ms commented on concepts/permissions-reference.md
> +
Hm, it looks like you kept this as a separate H2 section.
@BenAlfasi , FYI I am going to move your permissions and examples to the existing H2 subsection for security permissions: https://docs.microsoft.com/en-us/graph/permissions-reference#security-permissions

We are actually planning to reduce the number of H2 sections in this very long topic, and make the H2 section headings map more closely to how customers would refer to the higher level functionality (e.g., security) rather than by the actual permission prefix (e.g., channel vs channel member vs channel settings, etc.).

2022-08-17 06:55 UTC, opbld32 commented
Docs Build status updates of commit _[fca4b14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fca4b14112ee09dda317f73f2da562364a8158ad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-2e529227)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-2e529227)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-2e529227)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftg [...]

2022-08-17 06:57 UTC, opbld32 commented
Docs Build status updates of commit _[81de190](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81de1904ca081379f5dbb2543e198ad77c58d60b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-ded8d4b1)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-ded8d4b1)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-ded8d4b1)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftg [...]

2022-08-17 07:23 UTC, opbld30 commented
Docs Build status updates of commit _[23e7b6c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23e7b6c55f5636ee8d121d81ae729b5c55d19502)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-95ad5b7b)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-95ad5b7b)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-95ad5b7b)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftg [...]

2022-08-17 12:09 UTC, BenAlfasi commented on api-reference/beta/resources/security-alert.md
>  |alertWebUrl|String|URL for the alert page in Microsoft 365 Defender portal.|
changed to 'incident'. thanks!

2022-08-17 12:11 UTC, BenAlfasi commented on api-reference/beta/resources/security-alert.md
>  |assignedTo|String|Owner of the incident, or null if no owner is assigned.|
owner of the alert. changed, thanks!

2022-08-17 12:18 UTC, opbld30 commented
Docs Build status updates of commit _[891c824](https://github.com/microsoftgraph/microsoft-graph-docs/commits/891c824f32e57d635e8864d09966396f69cd6958)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-312fe48f)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-312fe48f)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-312fe48f)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftg [...]

2022-08-17 12:19 UTC, BenAlfasi commented on api-reference/beta/resources/security-analyzedmessageevidence.md
>  |networkMessageId|String|Unique identifier for the email, generated by Microsoft 365.|
I confirm those values (actually i just fixed couple of those). 
We store it in Pascal case.. can we keep it as is or we will need to change our backend?

2022-08-17 12:20 UTC, opbld30 commented
Docs Build status updates of commit _[aaab076](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aaab076be1bf20b6d16b0103d42ca67382db6a1f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/intune-devices-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e454842b573f1afe0552fa5b195367bc-b4193998)
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-b4193998)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-b4193998)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftg [...]

2022-08-18 01:31 UTC, angelgolfer-ms approved these changes
Thanks, @BenAlfasi , for making the necessary fixes. They look good. 
We can follow up on the Pascal case issues for the 3 properties of analyzedMessageEvidence when we get confirmation of the current practice.

2022-08-18 01:47 UTC, opbld30 commented
Docs Build status updates of commit _[68a5fed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68a5fed86594377ccbc4df441c865354017d5f07)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-loggedonuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-loggedonuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-loggedonuser?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-f2cae4f1111ee77b5e365cb84eb0cea1-9a7f30d9)
[api-reference/beta/resources/security-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) | [Details](#user-content-e8cef8e3f29f398137f53b89179d8528-9a7f30d9)
[api-reference/beta/api/security-alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-alert-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-alert-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-alert-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-get?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-incident-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-incident-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-incident-update?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-alerts_v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-alerts_v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/api/security-list-incidents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/api/security-list-incidents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-list-incidents?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/includes/alerts-callout-two-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/includes/alerts-callout-two-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alert?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertcomment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertcomment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertcomment?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-alertevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-alertevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-alertevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-analyzedmessageevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-analyzedmessageevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-analyzedmessageevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-cloudapplicationevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-cloudapplicationevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-cloudapplicationevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-deviceevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-deviceevidence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-deviceevidence?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-emailsender.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-emailsender.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-emailsender?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-filedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/resources/security-filedetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-filedetails?view=graph-rest-beta&branch=pr-en-us-14745) (graph-rest-beta) |
[api-reference/beta/resources/security-fileevidence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenAlfasi-AddIncidentApi2/api-reference/beta/ [...]

2022-08-18 01:50 UTC, merged