Teams - Promote system message events for Messaging APIs to v1.0
microsoftgraph/microsoft-graph-docs pull request #14759
Opened 2021-10-27 13:51 UTC by harshnat

This PR is to add support for system message events for Teams Messaging APIs to v1.

Doc PR for beta - https://github.com/microsoftgraph/microsoft-graph-docs/pull/13085/files

2021-11-03 21:32 UTC, JarbasHorst requested changes

2021-11-03 21:32 UTC, JarbasHorst commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +**visibleHistoryStartDateTime** property for [conversationMember](conversationmember.md) and the **membersAddedEventMessageDetail** message might have different values. [conversationMember](conversat
Please, add the before "initiator's visible history time". Suggested revision:

- ...time for the member based on the initiator's visible history time.

2021-11-03 21:32 UTC, JarbasHorst commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +> **Note**: For a chat, when the selected share history time for members is earlier than the initator's visible history time, the
Is "share history time" an UI element that a user can select? Please, clarify this sentence.

2021-11-03 21:32 UTC, JarbasHorst commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +|visibleHistoryStartDateTime|DateTimeOffset|The timestamp denoting how far back a conversation's history is shared with the conversation members.|
A word ending in –ing can be a verb, a noun, or an adjective. Please, avoid using gerunds where possible; in this case, you can change "denoting" to "that denotes".

2021-11-03 21:32 UTC, JarbasHorst commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +The **visibleHistoryStartDateTime** property for a members added event in a channel is always set to `0001-01-01T00:00:00Z`, which indicates that all history is shared.
For clarity, please replace "a members added event in a channel" with "an event about members added to a channel". Suggested revision:

- The \*\*visibleHistoryStartDateTime\*\* property for an event about members added to a channel is...

2021-11-03 21:45 UTC, JarbasHorst requested changes

2021-11-03 21:45 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamsappinstalledeventmessagedetail.md
> +Represents the details of an event message about teamsApp installed.
GLOBAL: Please apply this change to all appearances of teamsApp in this resource topic, except the description property in the top.

- We apply bold formatting to resource names; please update the formatting of teamsApp.

2021-11-03 21:45 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamsappremovedeventmessagedetail.md
> +Represents the details of an event message about teamsApp removed.
GLOBAL: Please apply this change to all appearances of teamsApp in this resource topic, except the description property in the top.

- We apply bold formatting to resource names; please update the formatting of teamsApp.

2021-11-03 21:45 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamsappupgradedeventmessagedetail.md
> +Represents the details of an event message about teamsApp upgraded.
GLOBAL: Please apply this change to all appearances of teamsApp in this resource topic, except the description property in the top.

- We apply bold formatting to resource names; please update the formatting of teamsApp.

2021-11-04 20:17 UTC, JarbasHorst requested changes

2021-11-04 20:17 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the **eventDetail** property to [chatMessage](https://docs.microsoft.com/en-us/graph/api/resources/chatMessage?view=graph-rest-1.0) resource.",
Please, add "the" before "chatMessage". Suggested revision:

- ...property to the [chatMessage]...

2021-11-04 21:14 UTC, JarbasHorst commented
Hi @harshnat, I checked the [System Messages](https://docs.microsoft.com/en-us/graph/system-messages) concept topic and noticed that all links to the chatMessage resource topic refers to the beta version. Should that be changed, now that you are promoting the system message events for Messaging APIs to v1.0?

2021-11-08 11:08 UTC, harshnat commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +**visibleHistoryStartDateTime** property for [conversationMember](conversationmember.md) and the **membersAddedEventMessageDetail** message might have different values. [conversationMember](conversat
Updated

2021-11-08 11:08 UTC, harshnat commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +> **Note**: For a chat, when the selected share history time for members is earlier than the initator's visible history time, the
Yes, there is an option to select chat history in Teams UI while adding a member to a chat. This can also be set using this API https://docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&tabs=http#examples.

2021-11-08 11:09 UTC, harshnat commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +|visibleHistoryStartDateTime|DateTimeOffset|The timestamp denoting how far back a conversation's history is shared with the conversation members.|
Updated

2021-11-08 11:09 UTC, harshnat commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +The **visibleHistoryStartDateTime** property for a members added event in a channel is always set to `0001-01-01T00:00:00Z`, which indicates that all history is shared.
Updated

2021-11-08 11:10 UTC, harshnat commented on api-reference/v1.0/resources/teamsappinstalledeventmessagedetail.md
> +Represents the details of an event message about teamsApp installed.
Updated

2021-11-08 11:10 UTC, harshnat commented on api-reference/v1.0/resources/teamsappremovedeventmessagedetail.md
> +Represents the details of an event message about teamsApp removed.
Updated

2021-11-08 11:10 UTC, harshnat commented on api-reference/v1.0/resources/teamsappupgradedeventmessagedetail.md
> +Represents the details of an event message about teamsApp upgraded.
Updated

2021-11-08 11:10 UTC, opbld33 commented
Docs Build status updates of commit _[5d86d17](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d86d174c8268d2524d1e0201b41b1056c0524ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelrenamedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelsetasfavoritebydefaulteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetai [...]

2021-11-08 11:12 UTC, harshnat commented
> Hi @harshnat, I checked the [System Messages](https://docs.microsoft.com/en-us/graph/system-messages) concept topic and noticed that all links to the chatMessage resource topic refers to the beta version. Should that be changed, now that you are promoting the system message events for Messaging APIs to v1.0?

@JarbasHorst updated all the links to the chatMessage resource v1.

2021-11-08 11:12 UTC, opbld31 commented
Docs Build status updates of commit _[2a97c48](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a97c48ea991467d250c4bab55fc92908bbd3c60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelrenamedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelsetasfavoritebydefaulteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetai [...]

2021-11-08 11:19 UTC, harshnat commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the **eventDetail** property to [chatMessage](https://docs.microsoft.com/en-us/graph/api/resources/chatMessage?view=graph-rest-1.0) resource.",
Updated

2021-11-08 11:19 UTC, opbld34 commented
Docs Build status updates of commit _[9fe3a0b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9fe3a0bdcda2a4e197965208bfe0229f11a203f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelrenamedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelsetasfavoritebydefaulteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetai [...]

2021-11-08 21:05 UTC, JarbasHorst requested changes

2021-11-08 21:05 UTC, JarbasHorst commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +> **Note**: For a chat, when the selected share history time for members is earlier than the initator's visible history time, the
For clarity, I recommend you to rephrase this sentence. Suggested revision:

- The \*\*visibleHistoryStartDateTime\*\* property for a \[conversationMember\](conversationmember.md) and the \*\*membersAddedEventMessageDetail\*\* message might have different values if the selected \*\*shareHistoryTime\*\* value for members in a chat is earlier than the initiator’s visible history time.

2021-11-09 12:41 UTC, opbld31 commented
Docs Build status updates of commit _[0ea91d7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ea91d7a455b89239ee09ca83cb9a07c65bb4c28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelrenamedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelsetasfavoritebydefaulteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetai [...]

2021-11-09 12:42 UTC, harshnat commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +> **Note**: For a chat, when the selected share history time for members is earlier than the initator's visible history time, the
Updated

2021-11-09 20:44 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-11-16 10:33 UTC, opbld30 commented
Docs Build status updates of commit _[84e684e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84e684eeb07990e06360843339cfb5c71a24fb6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelrenamedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelsetasfavoritebydefaulteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetai [...]

2021-11-18 04:17 UTC, harshnat commented
@Lauragra the PR has been reviewed by @JarbasHorst and ready for final review. Can you please help reviewing this.

2021-11-25 17:08 UTC, isvargasmsft commented
Reviewing

2021-11-25 17:18 UTC, isvargasmsft commented on api-reference/v1.0/resources/teamsappinstalledeventmessagedetail.md
> +Represents the details of an event message about **teamsApp** installed.
Line 14: Are you reference to the teamsApp resource type? https://docs.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-1.0

If so, please include the link in the first mention.

2021-11-25 17:19 UTC, isvargasmsft commented on api-reference/v1.0/resources/teamsappinstalledeventmessagedetail.md
> +Represents the details of an event message about **teamsApp** installed.
Same for eventMessage.

2021-11-25 17:36 UTC, isvargasmsft commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +Represents the details of an event message about members added.
Please add the due reference link to the first mention of eventMessage and members.

2021-11-25 17:37 UTC, isvargasmsft commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +This message is generated when members are added to a chat, a channel, or a team.
Please bold members and add reference link to chat, channel and team.

2021-11-25 17:37 UTC, opbld33 commented
Docs Build status updates of commit _[4e2d6ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e2d6ae43178a138827e1b39f6e47104d05fde44)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelrenamedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelsetasfavoritebydefaulteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetai [...]

2021-11-25 17:37 UTC, isvargasmsft commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +The **visibleHistoryStartDateTime** property for an event about members added to a channel is always set to `0001-01-01T00:00:00Z`, which indicates that all history is shared.
Please bold mentions of members, event, channel.

2021-11-25 18:35 UTC, isvargasmsft commented on api-reference/v1.0/resources/teamsappremovedeventmessagedetail.md
> +Represents the details of an event message about **teamsApp** removed.
Please add reference links in first mentions of eventMessage and teamsApp.

2021-11-25 18:53 UTC, isvargasmsft commented on api-reference/v1.0/resources/membersdeletedeventmessagedetail.md
> +Represents the details of an event message about members deleted.
Reference links in lines 14 and 15. 

Bold subsequent mentions.

2021-11-25 19:03 UTC, opbld33 commented
Docs Build status updates of commit _[57b4570](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57b457034e314d6211a6ae2b539fe27a01f65753)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelrenamedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelsetasfavoritebydefaulteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetai [...]

2021-11-25 19:06 UTC, opbld31 commented
Docs Build status updates of commit _[6020916](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6020916a7ec38f758e7176229b5663c4939c7111)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelrenamedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelsetasfavoritebydefaulteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetai [...]

2021-11-25 19:55 UTC, isvargasmsft requested changes
Hello Harshna and Akhil, 

Thank you very much for your work in this PR. 

Just few details: Please remember to add a link reference in the first mention of a resource type in a topic, and bold all subsequent mentions. 

Please apply in every topic where applicable.

Kind regards,

Isaac

2021-11-25 19:56 UTC, isvargasmsft commented on api-reference/v1.0/resources/membersdeletedeventmessagedetail.md
> +Represents the details of an event message about members deleted.
Please apply these suggestions in every topic where applicable. Several topics have this same issue.

2021-11-29 10:47 UTC, harshnat commented on api-reference/v1.0/resources/membersdeletedeventmessagedetail.md
> +Represents the details of an event message about members deleted.
Updated all topics

2021-11-29 10:47 UTC, opbld33 commented
Docs Build status updates of commit _[2b94caa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b94caac58e8300f6f6a11b16259e04a3997d61e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelrenamedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelsetasfavoritebydefaulteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetai [...]

2021-11-29 10:48 UTC, harshnat commented on api-reference/v1.0/resources/teamsappremovedeventmessagedetail.md
> +Represents the details of an event message about **teamsApp** removed.
event message mentioned in all these topics does not refer to the eventMessage resource.
Added link for teamsApp.

2021-11-29 10:50 UTC, harshnat commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +The **visibleHistoryStartDateTime** property for an event about members added to a channel is always set to `0001-01-01T00:00:00Z`, which indicates that all history is shared.
event mentioned in all these topics does not refer to event.md resource.
Updated to bold for members and channel.

2021-11-29 10:53 UTC, harshnat commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +Represents the details of an event message about members added.
Added link for members.
event message does not refer to eventMessage resource.

2021-11-29 10:55 UTC, harshnat commented on api-reference/v1.0/resources/membersaddedeventmessagedetail.md
> +This message is generated when members are added to a chat, a channel, or a team.
Updated

2021-11-29 10:56 UTC, harshnat commented on api-reference/v1.0/resources/teamsappinstalledeventmessagedetail.md
> +Represents the details of an event message about **teamsApp** installed.
Added link for teamsApp.
event message does not refer to eventMessage resource.

2021-11-29 10:56 UTC, opbld34 commented
Docs Build status updates of commit _[cea1254](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cea12546358539ef5c8dea791914807fe0dbce49)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelrenamedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelsetasfavoritebydefaulteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetai [...]

2021-11-29 11:03 UTC, opbld30 commented
Docs Build status updates of commit _[2388a62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2388a62317a47a5d901c9b0cbe424c0ffa109cdf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelrenamedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelsetasfavoritebydefaulteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelunsetasfavoritebydefaulteventmessagedetai [...]

2021-11-30 08:41 UTC, opbld31 commented
Docs Build status updates of commit _[8d08905](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d08905a72b31f854bf404a3c881e14e4f3ec371)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-14759) (graph-rest-beta) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelrenamedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/ch [...]

2021-11-30 08:48 UTC, opbld32 commented
Docs Build status updates of commit _[9c9bf14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c9bf14b4f63d1ea63089e93239f2ba2a5df3ceb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-14759) (graph-rest-beta) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelrenamedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelsetasfavoritebydefaulteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/ch [...]

2021-11-30 14:24 UTC, opbld32 commented
Docs Build status updates of commit _[de6e851](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de6e8517ea751414bc4dfde2f64faa5341d09158)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-14759) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-14759) (graph-rest-beta) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https [...]

2021-11-30 14:27 UTC, isvargasmsft approved these changes

2021-12-04 01:45 UTC, opbld30 commented
Docs Build status updates of commit _[a78c3e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a78c3e77d206195dbed045e62475a3f8121c2476)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-14759) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-14759) (graph-rest-beta) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https [...]

2021-12-04 01:47 UTC, Lauragra commented on api-reference/includes/teams-subscription-notes.md
> +> [!NOTE]
This includes file now basically includes three notes in a row. I suggest that we format this as regular text rather than a note. As an aside, is it expected that we have two identical notes in this include file?

2021-12-06 09:23 UTC, opbld31 commented
Docs Build status updates of commit _[1591175](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15911751aa4b7e859cee4d0e6e314ef42cbfaf24)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3d5783bf)

<a id="3d5783bf"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112060923137395-14759%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-06T09%3A23%3A54Z&sr=b&sp=r&sig=gPZG8kETMlhFZK7tNVReDSw17UD6Q9%2FzZE6B0d%2FlRcw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 09:42 UTC, opbld33 commented
Docs Build status updates of commit _[332ba18](https://github.com/microsoftgraph/microsoft-graph-docs/commits/332ba18a0b6f9442240dca7a4e75767b72021b60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-14759) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-14759) (graph-rest-beta) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-14759) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/htharayani/GA-Control-Messages/api-reference/v1.0/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https [...]

2021-12-06 09:42 UTC, harshnat commented on api-reference/includes/teams-subscription-notes.md
> +> [!NOTE]
Adding as regular text now instead of note.

2021-12-07 01:05 UTC, merged