Create shareduserprofile.md
microsoftgraph/microsoft-graph-docs pull request #14772
Opened 2021-10-28 15:29 UTC by adimitui

added resource page for sharedUserProfile

Schema update PR: 5282485

2021-10-29 18:51 UTC, opbld33 commented
Docs Build status updates of commit _[1e39720](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e397203c365750d38e09bafbfddd74f59bc6f5a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/shareduserprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/shareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-e1b18767e1aa68330e0fe1f79401e622-8da02594)
[api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userprofilesharedwithexternaltenant?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-3e5e32194242b246ef5ae0351322ab7b-8da02594)

<a id="e1b18767e1aa68330e0fe1f79401e622-8da02594"></a>
### [api-reference/beta/resources/shareduserprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofile.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/sharedUserProfile-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/sharedUserProfile-get.md'.`````

<a id="3e5e32194242b246ef5ae0351322ab7b-8da02594"></a>
### [api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/userprofilesharedwithexternaltenant-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/userprofilesharedwithexternaltenant-get.md'.`````
 - **Line 34, Column 27**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/multitenantcollaboration.md'.`````
 - **Line 35, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/multitenantcollaborationadmission.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110291849438411-14772%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-29T18%3A51%3A18Z&sr=b&sp=r&sig=mWoRCTHGWt1Gp7gBvd2g1Q0G%2FBD8RWnRaLciQMap2jo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-29 19:03 UTC, opbld32 commented
Docs Build status updates of commit _[bd2b0bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd2b0bd8262be152a1645ef6bbf50ff82ec31e9b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-5dc803a7)
[api-reference/beta/resources/shareduserprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/shareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-e1b18767e1aa68330e0fe1f79401e622-5dc803a7)
[api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userprofilesharedwithexternaltenant?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-3e5e32194242b246ef5ae0351322ab7b-5dc803a7)

<a id="57ed27efb6c7c91778f8070a06b3a5f7-5dc803a7"></a>
### [api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md)
 - **Line 46, Column 28**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/inboundshareduserprofiles.md'.`````
 - **Line 47, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/outboundshareduserprofiles.md'.`````

<a id="e1b18767e1aa68330e0fe1f79401e622-5dc803a7"></a>
### [api-reference/beta/resources/shareduserprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofile.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/sharedUserProfile-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/sharedUserProfile-get.md'.`````

<a id="3e5e32194242b246ef5ae0351322ab7b-5dc803a7"></a>
### [api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/userprofilesharedwithexternaltenant-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/userprofilesharedwithexternaltenant-get.md'.`````
 - **Line 34, Column 27**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/multitenantcollaboration.md'.`````
 - **Line 35, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/multitenantcollaborationadmission.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110291901582237-14772%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-29T19%3A03%3A36Z&sr=b&sp=r&sig=JYIpYtpNLORuEt3%2BjL9qAlgmAYZt%2FADx4sSH9KRzONs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-29 19:22 UTC, opbld34 commented
Docs Build status updates of commit _[80b6344](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80b634427dc3f54f27c3a07cc035a35a55f5bf76)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-d603b18b)
[api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-df7b8e5b402b073c5f7d37ec179adcec-d603b18b)
[api-reference/beta/resources/shareduserprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/shareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-e1b18767e1aa68330e0fe1f79401e622-d603b18b)
[api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userprofilesharedwithexternaltenant?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-3e5e32194242b246ef5ae0351322ab7b-d603b18b)

<a id="57ed27efb6c7c91778f8070a06b3a5f7-d603b18b"></a>
### [api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md)
 - **Line 46, Column 28**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/inboundshareduserprofiles.md'.`````
 - **Line 47, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/outboundshareduserprofiles.md'.`````

<a id="df7b8e5b402b073c5f7d37ec179adcec-d603b18b"></a>
### [api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'sharedUserProfile resource type' is duplicated with other articles: 'beta/resources/inboundSharedUserProfile.md(10,1), beta/resources/shareduserprofile.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/sharedUserProfile-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/sharedUserProfile-get.md'.`````

<a id="e1b18767e1aa68330e0fe1f79401e622-d603b18b"></a>
### [api-reference/beta/resources/shareduserprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofile.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'sharedUserProfile resource type' is duplicated with other articles: 'beta/resources/inboundSharedUserProfile.md(10,1), beta/resources/shareduserprofile.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/sharedUserProfile-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/sharedUserProfile-get.md'.`````

<a id="3e5e32194242b246ef5ae0351322ab7b-d603b18b"></a>
### [api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/userprofilesharedwithexternaltenant-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/userprofilesharedwithexternaltenant-get.md'.`````
 - **Line 34, Column 27**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/multitenantcollaboration.md'.`````
 - **Line 35, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/multitenantcollaborationadmission.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110291915409011-14772%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-29T19%3A22%3A42Z&sr=b&sp=r&sig=ZZ7cBw7HZPTWXuYD%2B%2Bz3zAx4WG4Rz4nMcpGPxiErNg4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post y [...]

2021-10-29 19:25 UTC, opbld30 commented
Docs Build status updates of commit _[d7339ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d7339eee49cda4a49383b531a2eb71a4272b33db)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-91c0a66f)
[api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-df7b8e5b402b073c5f7d37ec179adcec-91c0a66f)
[api-reference/beta/resources/shareduserprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/shareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-e1b18767e1aa68330e0fe1f79401e622-91c0a66f)
[api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userprofilesharedwithexternaltenant?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-3e5e32194242b246ef5ae0351322ab7b-91c0a66f)

<a id="57ed27efb6c7c91778f8070a06b3a5f7-91c0a66f"></a>
### [api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md)
 - **Line 46, Column 28**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/inboundshareduserprofiles.md'.`````
 - **Line 47, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/outboundshareduserprofiles.md'.`````

<a id="df7b8e5b402b073c5f7d37ec179adcec-91c0a66f"></a>
### [api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-get.md'.`````

<a id="e1b18767e1aa68330e0fe1f79401e622-91c0a66f"></a>
### [api-reference/beta/resources/shareduserprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofile.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/sharedUserProfile-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/sharedUserProfile-get.md'.`````

<a id="3e5e32194242b246ef5ae0351322ab7b-91c0a66f"></a>
### [api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/userprofilesharedwithexternaltenant-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/userprofilesharedwithexternaltenant-get.md'.`````
 - **Line 34, Column 27**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/multitenantcollaboration.md'.`````
 - **Line 35, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/multitenantcollaborationadmission.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110291923470697-14772%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-29T19%3A25%3A30Z&sr=b&sp=r&sig=JY%2FDElrAjRgXU5BFhGYTb3BFBN0ASw4ZJGfspdi%2FRgQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-29 19:46 UTC, opbld32 commented
Docs Build status updates of commit _[c1e3f46](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1e3f460a5617270bf5b7ccba780daae20934f79)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/shareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/shareduserprofile-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/shareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-b543f416fd1e3edae6fc2e0cf5f7b0ef-7386c1de)
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-7386c1de)
[api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-df7b8e5b402b073c5f7d37ec179adcec-7386c1de)
[api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/outboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-a034eedb422992e2c3ab837d20a65a99-7386c1de)
[api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userprofilesharedwithexternaltenant?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-3e5e32194242b246ef5ae0351322ab7b-7386c1de)
[api-reference/beta/api/shareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/shareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/shareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/shareduserprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/shareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |

<a id="b543f416fd1e3edae6fc2e0cf5f7b0ef-7386c1de"></a>
### [api-reference/beta/api/shareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/shareduserprofile-get.md)
 - **Line 15, Column 44**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/tenantreference.md'.`````
 - **Line 49, Column 67**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/tenantreference.md'.`````

<a id="57ed27efb6c7c91778f8070a06b3a5f7-7386c1de"></a>
### [api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md)
 - **Line 46, Column 28**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/inboundshareduserprofiles.md'.`````
 - **Line 47, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/outboundshareduserprofiles.md'.`````

<a id="df7b8e5b402b073c5f7d37ec179adcec-7386c1de"></a>
### [api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-get.md'.`````

<a id="a034eedb422992e2c3ab837d20a65a99-7386c1de"></a>
### [api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outboundSharedUserProfile-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outboundSharedUserProfile-get.md'.`````

<a id="3e5e32194242b246ef5ae0351322ab7b-7386c1de"></a>
### [api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/userprofilesharedwithexternaltenant-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/userprofilesharedwithexternaltenant-get.md'.`````
 - **Line 34, Column 27**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/multitenantcollaboration.md'.`````
 - **Line 35, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/multitenantcollaborationadmission.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110291944524039-14772%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-29T19%3A46%3A54Z&sr=b&sp=r&sig=nBUYjC1H0VvnBs463oS%2Fm46OHRRRu9xRT99iy%2FnKuyA%3D).

If you see build warnings/errors with permission i [...]

2021-10-29 19:52 UTC, opbld33 commented
Docs Build status updates of commit _[514b221](https://github.com/microsoftgraph/microsoft-graph-docs/commits/514b2216397afd4e6ec0238df4c3128af896314f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/shareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/shareduserprofile-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/shareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-b543f416fd1e3edae6fc2e0cf5f7b0ef-0d149477)
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-0d149477)
[api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-df7b8e5b402b073c5f7d37ec179adcec-0d149477)
[api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/outboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-a034eedb422992e2c3ab837d20a65a99-0d149477)
[api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userprofilesharedwithexternaltenant?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-3e5e32194242b246ef5ae0351322ab7b-0d149477)
[api-reference/beta/api/shareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/shareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/shareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/shareduserprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/shareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |

<a id="b543f416fd1e3edae6fc2e0cf5f7b0ef-0d149477"></a>
### [api-reference/beta/api/shareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/shareduserprofile-get.md)
 - **Line 49, Column 67**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/tenantreference.md'.`````

<a id="57ed27efb6c7c91778f8070a06b3a5f7-0d149477"></a>
### [api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md)
 - **Line 46, Column 28**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/inboundshareduserprofiles.md'.`````
 - **Line 47, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/outboundshareduserprofiles.md'.`````

<a id="df7b8e5b402b073c5f7d37ec179adcec-0d149477"></a>
### [api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-get.md'.`````

<a id="a034eedb422992e2c3ab837d20a65a99-0d149477"></a>
### [api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outboundSharedUserProfile-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outboundSharedUserProfile-get.md'.`````

<a id="3e5e32194242b246ef5ae0351322ab7b-0d149477"></a>
### [api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/userprofilesharedwithexternaltenant-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/userprofilesharedwithexternaltenant-get.md'.`````
 - **Line 34, Column 27**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/multitenantcollaboration.md'.`````
 - **Line 35, Column 37**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/multitenantcollaborationadmission.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110291950418404-14772%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-29T19%3A52%3A35Z&sr=b&sp=r&sig=wjhwI6k5UamNvELEzoyUQOawj%2B4DC06l1ZUIdkfs2kA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your Git [...]

2021-10-29 20:00 UTC, opbld34 commented
Docs Build status updates of commit _[b7fc868](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b7fc8689121942a09145f46ecd817baef80f20d9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/shareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/shareduserprofile-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/shareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-b543f416fd1e3edae6fc2e0cf5f7b0ef-4edcc647)
[api-reference/beta/api/userprofilesharedwithexternaltenant-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/userprofilesharedwithexternaltenant-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userprofilesharedwithexternaltenant-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-708ac04c77d5d0ea07a909eae7aaae39-4edcc647)
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-4edcc647)
[api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-df7b8e5b402b073c5f7d37ec179adcec-4edcc647)
[api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/outboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-a034eedb422992e2c3ab837d20a65a99-4edcc647)
[api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userprofilesharedwithexternaltenant?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-3e5e32194242b246ef5ae0351322ab7b-4edcc647)
[api-reference/beta/api/shareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/shareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/shareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/userprofilesharedwithexternaltenant-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/userprofilesharedwithexternaltenant-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userprofilesharedwithexternaltenant-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/shareduserprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/shareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |

<a id="b543f416fd1e3edae6fc2e0cf5f7b0ef-4edcc647"></a>
### [api-reference/beta/api/shareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/shareduserprofile-get.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get sharedUserProfile' is duplicated with other articles: 'beta/api/shareduserprofile-get.md(10,1), beta/api/userprofilesharedwithexternaltenant-get.md(10,1)'. First level headings must be unique within a docset.`````

<a id="708ac04c77d5d0ea07a909eae7aaae39-4edcc647"></a>
### [api-reference/beta/api/userprofilesharedwithexternaltenant-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/userprofilesharedwithexternaltenant-get.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get sharedUserProfile' is duplicated with other articles: 'beta/api/shareduserprofile-get.md(10,1), beta/api/userprofilesharedwithexternaltenant-get.md(10,1)'. First level headings must be unique within a docset.`````

<a id="57ed27efb6c7c91778f8070a06b3a5f7-4edcc647"></a>
### [api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md)
 - **Line 46, Column 28**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/inboundshareduserprofiles.md'.`````
 - **Line 47, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/outboundshareduserprofiles.md'.`````

<a id="df7b8e5b402b073c5f7d37ec179adcec-4edcc647"></a>
### [api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-get.md'.`````

<a id="a034eedb422992e2c3ab837d20a65a99-4edcc647"></a>
### [api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md)
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outboundSharedUserProfile-list.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outboundSharedUserProfile-get.md'.`````

<a id="3e5e32194242b246ef5ae0351322ab7b-4edcc647"></a>
### [api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/micro [...]

2021-10-29 20:08 UTC, opbld30 commented
Docs Build status updates of commit _[f65e29a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f65e29a719ada6313debad550b05cf110e93513d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-74c7ea7e51ef22642e85c4c55c42b534-65863920)
[api-reference/beta/api/shareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/shareduserprofile-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/shareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-b543f416fd1e3edae6fc2e0cf5f7b0ef-65863920)
[api-reference/beta/api/userprofilesharedwithexternaltenant-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/userprofilesharedwithexternaltenant-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userprofilesharedwithexternaltenant-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-708ac04c77d5d0ea07a909eae7aaae39-65863920)
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-65863920)
[api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/outboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-a034eedb422992e2c3ab837d20a65a99-65863920)
[api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userprofilesharedwithexternaltenant?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-3e5e32194242b246ef5ae0351322ab7b-65863920)
[api-reference/beta/api/inboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-55d844707e9f7444ea0f567d479a51e4-65863920)
[api-reference/beta/api/shareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/shareduserprofile-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/shareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-353cd4d2bd3e4a5a19f53f2d416807d5-65863920)
[api-reference/beta/api/userprofilesharedwithexternaltenant-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/userprofilesharedwithexternaltenant-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userprofilesharedwithexternaltenant-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/shareduserprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/shareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |

<a id="74c7ea7e51ef22642e85c4c55c42b534-65863920"></a>
### [api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get sharedUserProfile' is duplicated with other articles: 'beta/api/inboundshareduserprofile-get.md(10,1), beta/api/shareduserprofile-get.md(10,1), beta/api/userprofilesharedwithexternaltenant-get.md(10,1)'. First level headings must be unique within a docset.`````

<a id="b543f416fd1e3edae6fc2e0cf5f7b0ef-65863920"></a>
### [api-reference/beta/api/shareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/shareduserprofile-get.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get sharedUserProfile' is duplicated with other articles: 'beta/api/inboundshareduserprofile-get.md(10,1), beta/api/shareduserprofile-get.md(10,1), beta/api/userprofilesharedwithexternaltenant-get.md(10,1)'. First level headings must be unique within a docset.`````

<a id="708ac04c77d5d0ea07a909eae7aaae39-65863920"></a>
### [api-reference/beta/api/userprofilesharedwithexternaltenant-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/userprofilesharedwithexternaltenant-get.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get sharedUserProfile' is duplicated with other articles: 'beta/api/inboundshareduserprofile-get.md(10,1), beta/api/shareduserprofile-get.md(10,1), beta/api/userprofilesharedwithexternaltenant-get.md(10,1)'. First level headings must be unique within a docset.`````

<a id="57ed27efb6c7c91778f8070a06b3a5f7-65863920"></a>
### [api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md)
 - **Line 46, Column 28**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/inboundshareduserprofiles.md'.`````
 - **Line 47, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/outboundsharedus [...]

2021-10-29 20:31 UTC, opbld31 commented
Docs Build status updates of commit _[f11601f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f11601f6459164832143a8190f2c27556839dc20)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/shareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/shareduserprofile-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/shareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-b543f416fd1e3edae6fc2e0cf5f7b0ef-5a255471)
[api-reference/beta/api/userprofilesharedwithexternaltenant-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/userprofilesharedwithexternaltenant-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userprofilesharedwithexternaltenant-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-708ac04c77d5d0ea07a909eae7aaae39-5a255471)
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-5a255471)
[api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userprofilesharedwithexternaltenant?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-3e5e32194242b246ef5ae0351322ab7b-5a255471)
[api-reference/beta/api/inboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-55d844707e9f7444ea0f567d479a51e4-5a255471)
[api-reference/beta/api/shareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/shareduserprofile-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/shareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-353cd4d2bd3e4a5a19f53f2d416807d5-5a255471)
[api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/userprofilesharedwithexternaltenant-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/userprofilesharedwithexternaltenant-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userprofilesharedwithexternaltenant-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/outboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/shareduserprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/shareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |

<a id="b543f416fd1e3edae6fc2e0cf5f7b0ef-5a255471"></a>
### [api-reference/beta/api/shareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/shareduserprofile-get.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get sharedUserProfile' is duplicated with other articles: 'beta/api/shareduserprofile-get.md(10,1), beta/api/userprofilesharedwithexternaltenant-get.md(10,1)'. First level headings must be unique within a docset.`````

<a id="708ac04c77d5d0ea07a909eae7aaae39-5a255471"></a>
### [api-reference/beta/api/userprofilesharedwithexternaltenant-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/userprofilesharedwithexternaltenant-get.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get sharedUserProfile' is duplicated with other articles: 'beta/api/shareduserprofile-get.md(10,1), beta/api/userprofilesharedwithexternaltenant-get.md(10,1)'. First level headings must be unique within a docset.`````

<a id="57ed27efb6c7c91778f8070a06b3a5f7-5a255471"></a>
### [api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md)
 - **Line 46, Column 28**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/inboundshareduserprofiles.md'.`````
 - **Line 47, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/outboundshareduserprofiles.md'.`````

<a id="3e5e32194242b246ef5ae0351322ab7b-5a255471"></a>
### [api-reference/beta/resources/userprofileshar [...]

2021-10-29 20:33 UTC, opbld33 commented
Docs Build status updates of commit _[29ebe6e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/29ebe6ed85681ab98b304100759bbfb8403b3528)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-74c7ea7e51ef22642e85c4c55c42b534-a07f2e99)
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-a07f2e99)
[api-reference/beta/api/inboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/outboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |

<a id="74c7ea7e51ef22642e85c4c55c42b534-a07f2e99"></a>
### [api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md)
 - **Line 49, Column 67**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/userProfileSharedWithExternalTenant.md'.`````

<a id="57ed27efb6c7c91778f8070a06b3a5f7-a07f2e99"></a>
### [api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md)
 - **Line 46, Column 28**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/inboundshareduserprofiles.md'.`````
 - **Line 47, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/outboundshareduserprofiles.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110292030110745-14772%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-29T20%3A33%3A34Z&sr=b&sp=r&sig=DW5JP%2B1Ij%2Fp8GjTFMJM3GnGW6XMmVzMloKAJcEiv9DQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-04 16:51 UTC, opbld34 commented
Docs Build status updates of commit _[ff4412d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff4412d7b180ac21e802dddee4233c203ad0df66)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-065358ad)
[api-reference/beta/resources/shareduserprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/shareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-e1b18767e1aa68330e0fe1f79401e622-065358ad)
[api-reference/beta/resources/userprofilesharedwithexternaltenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/userprofilesharedwithexternaltenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userprofilesharedwithexternaltenant?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-3e5e32194242b246ef5ae0351322ab7b-065358ad)
[api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/inboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/outboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/doc-stubs/api/administrativeunit-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/doc-stubs/api/administrativeunit-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/doc-stubs/api/administrativeunit-list-members.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-list-scopedrolemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/doc-stubs/api/administrativeunit-list-scopedrolemembers.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/doc-stubs/api/administrativeunit-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/doc-stubs/api/administrativeunit-post-administrativeunits.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/doc-stubs/api/administrativeunit-post-members.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-post-scopedrolemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/doc-stubs/api/administrativeunit-post-scopedrolemembers.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/doc-stubs/api/administrativeunit-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/allowedvalue-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/doc-stubs/api/allowedvalue-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/allowedvalue-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/doc-stubs/api/allowedvalue-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/allowedvalue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/doc-stubs/api/allowedvalue-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/allowedvalue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/doc-stubs/api/allowedvalue-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/allowedvalue-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/doc-stubs/api/allowedvalue-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/doc-stubs/api/application-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/d [...]

2021-11-04 20:17 UTC, kakagapo requested changes

2021-11-04 20:17 UTC, kakagapo commented on api-reference/beta/api/outboundshareduserprofile-list.md
> +            "@odata.type": "#Microsoft.DirectoryServices.inboundSharedUserProfiles",
This is the response corresponding to the inboundSharedUserProfiles type. Can you please fix it ?

2021-11-04 20:17 UTC, kakagapo commented on api-reference/beta/resources/outboundSharedUserProfile.md
> +| externalTenantId | String | ID of the external tenant with user profile access. |
The schema for this type was changed. Now there is a navigation property that points to TenantReference entities.

2021-11-04 20:17 UTC, kakagapo commented on api-reference/beta/resources/outboundSharedUserProfile.md
> +  "externalTenantId":"62bfb458-9474-4c44-896b-b30942d055f0"
This has to be fixed.

2021-11-04 20:17 UTC, kakagapo commented on api-reference/beta/resources/shareduserprofile.md
> +# sharedUserProfile resource type
This file has to be removed. There is nothing named sharedUserProfile

2021-11-04 20:17 UTC, kakagapo commented on api-reference/beta/resources/userprofilesharedwithexternaltenant.md
> +# userProfileSharedWithExternalTenant resource type
This file has to be removed too.

2021-11-04 20:17 UTC, kakagapo commented on doc-stubs/api/administrativeunit-delete.md
> +# Delete administrativeUnit
Lots of files here are not related to this change. Maybe we can remove them?

2021-11-19 23:48 UTC, opbld33 commented
Docs Build status updates of commit _[3e04518](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e0451834f54bbf76989d80b5d75b621d9fd5854)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-10cc5f10)

<a id="10cc5f10"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111192348252977-14772%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-20T23%3A48%3A52Z&sr=b&sp=r&sig=yaS0YKT8o%2FCshXruPg9wLPho0XT%2FTZqZ792H1XF%2BF3A%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 00:10 UTC, opbld30 commented
Docs Build status updates of commit _[3e6a161](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e6a16104b376a97de462cf84fbc268e0e82bb3e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b8557372)

<a id="b8557372"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200009406580-14772%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T00%3A10%3A08Z&sr=b&sp=r&sig=Si9vNwHIY0NeFifWe99uA2gI%2FOJ9sjYg9af8LCXnm30%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 00:16 UTC, opbld32 commented
Docs Build status updates of commit _[fc3d974](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc3d9749d0ce852e32df3f2ed4e5b1ce1d4167fa)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e40a05a8)

<a id="e40a05a8"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200015241338-14772%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T00%3A15%3A59Z&sr=b&sp=r&sig=7JGIAjG6RYIK9hS%2F3j4RgbGrmm1gwC1MVorQ5VIsmCo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 00:18 UTC, opbld31 commented
Docs Build status updates of commit _[85800d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85800d901ddfa9bfc94c1c3d623ba6b86f1e69d2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-20a823bb)

<a id="20a823bb"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200018259129-14772%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T00%3A18%3A53Z&sr=b&sp=r&sig=Il%2BUL01%2FUvCyZO3dD%2BzBaJcEk%2BW4gPTLhEFvElEcPNA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-03 23:00 UTC, opbld34 commented
Docs Build status updates of commit _[55d5cb2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/55d5cb2f0e79a7847964d624bce77e9f881fab7f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0a49a234)

<a id="0a49a234"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112032259485007-14772%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-03T23%3A00%3A24Z&sr=b&sp=r&sig=YQC1zl9RxXJeW5I%2BL%2BewNyjsEeIzqZ8t2tnytyxWVIE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-08 16:01 UTC, pawaitengineer reviewed
`doc-stubs` and `changelog-stubs` do not need to be checked in as is.

2021-12-09 01:09 UTC, opbld33 commented
Docs Build status updates of commit _[b458388](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b458388d74d2137c407a2ad9955cb457a0a470ab)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-43fb8b4b)

<a id="43fb8b4b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112090109247050-14772%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T01%3A09%3A45Z&sr=b&sp=r&sig=y%2BFmAGRhUE3N7TBPuxhqZhiJbZ3hZjBfBn5YoI53500%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 22:54 UTC, opbld31 commented
Docs Build status updates of commit _[6e443e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e443e57f03cfff3242ce7c55a2fcbd45c1b1c4a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a7f85aec)

<a id="a7f85aec"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201192253401200-14772%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T22%3A54%3A18Z&sr=b&sp=r&sig=Yiw%2BL3hH97QMd%2Fp57%2BIVy3g9DBwMU89zb4XavumNQ4k%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 23:08 UTC, opbld33 commented
Docs Build status updates of commit _[58333e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58333e036e14353140e8ca7651229cb9a784bcf8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-956ff7a2)

<a id="956ff7a2"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201192308142611-14772%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T23%3A08%3A48Z&sr=b&sp=r&sig=u04a0sIsF8R5i8hSskZ8OseDqtzmFGD2LVjK9Qq4Dvk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 22:18 UTC, adimitui commented on api-reference/beta/api/outboundshareduserprofile-list.md
> +            "@odata.type": "#Microsoft.DirectoryServices.inboundSharedUserProfiles",
Fixed to "#Microsoft.DirectoryServices.outboundSharedUserProfiles"

2022-01-26 22:20 UTC, adimitui commented on api-reference/beta/resources/shareduserprofile.md
> +# sharedUserProfile resource type
Removed file

2022-01-26 22:20 UTC, adimitui commented on doc-stubs/api/administrativeunit-delete.md
> +# Delete administrativeUnit
Removed entire doc-stubs and changelog-stubs folders

2022-01-26 22:20 UTC, adimitui commented on api-reference/beta/resources/userprofilesharedwithexternaltenant.md
> +# userProfileSharedWithExternalTenant resource type
Removed

2022-01-26 22:48 UTC, adimitui commented on api-reference/beta/resources/outboundSharedUserProfile.md
> +| externalTenantId | String | ID of the external tenant with user profile access. |
Added navigation property that points to tenantReference entity

2022-01-26 22:50 UTC, adimitui commented on api-reference/beta/resources/outboundSharedUserProfile.md
> +  "externalTenantId":"62bfb458-9474-4c44-896b-b30942d055f0"
fixed sample json output to consist of userId, userPrincipalName, and externalTenantId

2022-01-26 22:55 UTC, opbld32 commented
Docs Build status updates of commit _[e9164b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e9164b81d45008c4c353a2489f8b11c55ec4708f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ef4b1202)

<a id="ef4b1202"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262254312847-14772%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T22%3A55%3A06Z&sr=b&sp=r&sig=T4ZuhJi%2Bf23fhyy2Ar67OBl66P%2BZJduhfVC4YPMsQTs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 22:55 UTC, adimitui commented
@pawaitengineer: Performed requested changes, including removing doc-stubs and changelog-stubs folder. The content is ready for a re-review

2022-01-26 22:59 UTC, opbld31 commented
Docs Build status updates of commit _[f7624cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7624cb4b3d9e5686cb2430c71bd36d3f73ba469)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-32e28792)

<a id="32e28792"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201262259034236-14772%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T22%3A59%3A38Z&sr=b&sp=r&sig=SvnFP0%2FHqihFhZjm2Gqq4uk7qIaHshbimql74%2BEchOs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 12:41 UTC, opbld32 commented
Docs Build status updates of commit _[fd1f2f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fd1f2f80e4e34b10d3f6bb4601d03ae3646ae56a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-74c7ea7e51ef22642e85c4c55c42b534-74eb05d2)
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-74eb05d2)
[api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-df7b8e5b402b073c5f7d37ec179adcec-74eb05d2)
[api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/outboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-a034eedb422992e2c3ab837d20a65a99-74eb05d2)
[api-reference/beta/api/inboundshareduserprofile-exportpersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-exportpersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-exportpersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/inboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/inboundshareduserprofile-removepersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-removepersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-removepersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-removepersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-removepersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-removepersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/tenantreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/tenantreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantreference?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-exportpersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices-append.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/changelog/Microsoft.DirectoryServices-append.json) | :white_check_mark:Succeeded | |

<a id="74c7ea7e51ef22642e85c4c55c42b534-74eb05d2"></a>
### [api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md)
 - **Line 49, Column 67**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/userProfileSharedWithExternalTenant.md'.`````

<a id="57ed27efb6c7c91778f8070a06b3a5f7-74eb05d2"></a>
### [api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md)
 - **Line 48, Column 28**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/inboundshareduserprofiles.md'.`````
 - **Line 49, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/outboundshareduserprofiles.md'.`````

<a id="df7b8e5b402b073c5f7d37ec179adcec-74eb05d2"></a>
### [api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-remove.md'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-export.md'.`````

<a id="a034eedb422992e2c3ab837d20a65a99-74eb05d2"></a>
### [api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/val [...]

2022-02-03 13:25 UTC, opbld32 commented
Docs Build status updates of commit _[df3db3e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df3db3e71131bae123b5319f7c5500ad0b03a804)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-74c7ea7e51ef22642e85c4c55c42b534-d70980e1)
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-d70980e1)
[api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-df7b8e5b402b073c5f7d37ec179adcec-d70980e1)
[api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/outboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-a034eedb422992e2c3ab837d20a65a99-d70980e1)
[api-reference/beta/api/inboundshareduserprofile-exportpersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-exportpersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-exportpersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/inboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/inboundshareduserprofile-removepersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-removepersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-removepersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-removepersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-removepersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-removepersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/tenantreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/tenantreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantreference?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-exportpersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices-append.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/changelog/Microsoft.DirectoryServices-append.json) | :white_check_mark:Succeeded | |

<a id="74c7ea7e51ef22642e85c4c55c42b534-d70980e1"></a>
### [api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md)
 - **Line 49, Column 67**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/userProfileSharedWithExternalTenant.md'.`````

<a id="57ed27efb6c7c91778f8070a06b3a5f7-d70980e1"></a>
### [api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md)
 - **Line 48, Column 28**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/inboundshareduserprofiles.md'.`````
 - **Line 49, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/outboundshareduserprofiles.md'.`````

<a id="df7b8e5b402b073c5f7d37ec179adcec-d70980e1"></a>
### [api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-remove.md'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-export.md'.`````

<a id="a034eedb422992e2c3ab837d20a65a99-d70980e1"></a>
### [api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/val [...]

2022-02-03 13:35 UTC, opbld30 commented
Docs Build status updates of commit _[6ba47d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ba47d2f1285cb9d5f30b9d31b0e69be60c9322a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-74c7ea7e51ef22642e85c4c55c42b534-ba505084)
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-ba505084)
[api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-df7b8e5b402b073c5f7d37ec179adcec-ba505084)
[api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/outboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-a034eedb422992e2c3ab837d20a65a99-ba505084)
[api-reference/beta/api/inboundshareduserprofile-exportpersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-exportpersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-exportpersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/inboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/inboundshareduserprofile-removepersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-removepersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-removepersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-removepersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-removepersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-removepersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/tenantreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/tenantreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantreference?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-exportpersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices-append.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/changelog/Microsoft.DirectoryServices-append.json) | :white_check_mark:Succeeded | |

<a id="74c7ea7e51ef22642e85c4c55c42b534-ba505084"></a>
### [api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md)
 - **Line 49, Column 67**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/userProfileSharedWithExternalTenant.md'.`````

<a id="57ed27efb6c7c91778f8070a06b3a5f7-ba505084"></a>
### [api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md)
 - **Line 48, Column 28**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/inboundshareduserprofiles.md'.`````
 - **Line 49, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/outboundshareduserprofiles.md'.`````

<a id="df7b8e5b402b073c5f7d37ec179adcec-ba505084"></a>
### [api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-remove.md'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-export.md'.`````

<a id="a034eedb422992e2c3ab837d20a65a99-ba505084"></a>
### [api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/val [...]

2022-02-09 17:16 UTC, FaithOmbongi requested changes
Thank you @adimitui for your work on this PR. I've left suggestions inline plus the following:
- **GLOBAL:** Please change all file names to lower case
- **MISSING DOCS:** Please add the docs for the 3 methods + 1 action supported by the tenantReference resource type. Then surface tenantReference and its methods in the TOC.
- Q: Does inboundSharedUserProfiles support the following actions - checkMemberObjects, checkMemberGroups, getMemberObjects, and getMemberGroups? If yes, we'll need to include the required references in the resepctive docs. 
- Please document the two new permissions, CrossTenantUserProfileSharing.Read, CrossTenantUserProfileSharing.Read.All, to the permissions reference table (I think under cross tenant access permissions is OK) and add a changelog object for each.
- I'm having a bit of trouble understanding who calls the exportPersonalData action. Left a Q for you on the action's page.
- Let's group all these APIs into a single sub-node in the TOC. You can call it "Cross-tenant shared user profiles". I think this will help with discoverability for all XTA-related APIs. Please feel free to suggest otherwise or share if this is a misrepresentation.


I'll ping you internally to work on an overview article for this API.

2022-02-09 18:14 UTC, opbld30 commented
Docs Build status updates of commit _[0040c4e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0040c4ea8bd82f0059dfa116521b32deff12017b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-74c7ea7e51ef22642e85c4c55c42b534-862e1c73)
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-862e1c73)
[api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-df7b8e5b402b073c5f7d37ec179adcec-862e1c73)
[api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/outboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-a034eedb422992e2c3ab837d20a65a99-862e1c73)
[api-reference/beta/api/inboundshareduserprofile-exportpersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-exportpersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-exportpersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/inboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/inboundshareduserprofile-removepersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-removepersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-removepersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-removepersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-removepersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-removepersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/tenantreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/tenantreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantreference?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-exportpersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |

<a id="74c7ea7e51ef22642e85c4c55c42b534-862e1c73"></a>
### [api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md)
 - **Line 49, Column 67**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/userProfileSharedWithExternalTenant.md'.`````

<a id="57ed27efb6c7c91778f8070a06b3a5f7-862e1c73"></a>
### [api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md)
 - **Line 48, Column 28**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/inboundshareduserprofiles.md'.`````
 - **Line 49, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/outboundshareduserprofiles.md'.`````

<a id="df7b8e5b402b073c5f7d37ec179adcec-862e1c73"></a>
### [api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-remove.md'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-export.md'.`````

<a id="a034eedb422992e2c3ab837d20a65a99-862e1c73"></a>
### [api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outboundSharedUserProfile-remove.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/202 [...]

2022-02-16 09:31 UTC, opbld34 commented
Docs Build status updates of commit _[12725f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12725f24a59002ee506ba597f6620e7083c36423)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-74c7ea7e51ef22642e85c4c55c42b534-922b6c8c)
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-922b6c8c)
[api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-df7b8e5b402b073c5f7d37ec179adcec-922b6c8c)
[api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/outboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-a034eedb422992e2c3ab837d20a65a99-922b6c8c)
[api-reference/beta/resources/shareduserprofiles-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofiles-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/shareduserprofiles-overview?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-717ca2eefd221af6e987a2a4d95b066e-922b6c8c)
[api-reference/beta/api/inboundshareduserprofile-exportpersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-exportpersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-exportpersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/inboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/inboundshareduserprofile-removepersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-removepersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-removepersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-removepersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-removepersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-removepersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/tenantreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/tenantreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantreference?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-exportpersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |

<a id="74c7ea7e51ef22642e85c4c55c42b534-922b6c8c"></a>
### [api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md)
 - **Line 49, Column 67**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/userProfileSharedWithExternalTenant.md'.`````

<a id="57ed27efb6c7c91778f8070a06b3a5f7-922b6c8c"></a>
### [api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md)
 - **Line 48, Column 28**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/inboundshareduserprofiles.md'.`````
 - **Line 49, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/outboundshareduserprofiles.md'.`````

<a id="df7b8e5b402b073c5f7d37ec179adcec-922b6c8c"></a>
### [api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-remove.md'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-export.md'.`````

<a id="a034eedb422992e2c3ab837d20a65a99-922b6c8c"></a>
### [api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs [...]

2022-02-16 09:37 UTC, opbld32 commented
Docs Build status updates of commit _[06eeb0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06eeb0d0528073767d6911e377e597ed33b2fc57)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-74c7ea7e51ef22642e85c4c55c42b534-3060fbac)
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-57ed27efb6c7c91778f8070a06b3a5f7-3060fbac)
[api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-df7b8e5b402b073c5f7d37ec179adcec-3060fbac)
[api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/outboundSharedUserProfile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/outboundshareduserprofile?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-a034eedb422992e2c3ab837d20a65a99-3060fbac)
[api-reference/beta/resources/shareduserprofiles-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/shareduserprofiles-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/shareduserprofiles-overview?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) | [Details](#user-content-717ca2eefd221af6e987a2a4d95b066e-3060fbac)
[api-reference/beta/api/inboundshareduserprofile-exportpersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-exportpersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-exportpersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/inboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/inboundshareduserprofile-removepersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-removepersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-removepersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-get?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-list?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/api/outboundshareduserprofile-removepersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/outboundshareduserprofile-removepersonaldata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/outboundshareduserprofile-removepersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/resources/tenantreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/tenantreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantreference?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inboundshareduserprofile-exportpersonaldata?view=graph-rest-beta&branch=pr-en-us-14772) (graph-rest-beta) |

<a id="74c7ea7e51ef22642e85c4c55c42b534-3060fbac"></a>
### [api-reference/beta/api/inboundshareduserprofile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/api/inboundshareduserprofile-get.md)
 - **Line 49, Column 67**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/userProfileSharedWithExternalTenant.md'.`````

<a id="57ed27efb6c7c91778f8070a06b3a5f7-3060fbac"></a>
### [api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/directory.md)
 - **Line 48, Column 28**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/inboundshareduserprofiles.md'.`````
 - **Line 49, Column 29**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/outboundshareduserprofiles.md'.`````

<a id="df7b8e5b402b073c5f7d37ec179adcec-3060fbac"></a>
### [api-reference/beta/resources/inboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-27-adimitui-traversal-store-api/api-reference/beta/resources/inboundSharedUserProfile.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-remove.md'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/inboundSharedUserProfile-export.md'.`````

<a id="a034eedb422992e2c3ab837d20a65a99-3060fbac"></a>
### [api-reference/beta/resources/outboundSharedUserProfile.md](https://github.com/microsoftgraph/microsoft-graph-docs [...]

2023-03-17 09:28 UTC, FaithOmbongi commented
The API docs work has been taken over via #20553 . Removing the changes requested label and closing this PR to avoid unactionable notifications.

2023-03-17 09:28 UTC, closed without merging