2021 10 16 sseth m365 records management
microsoftgraph/microsoft-graph-docs pull request #14805
Opened 2021-11-02 01:13 UTC by samriddhiseth

2021-11-02 01:15 UTC, opbld30 commented
Docs Build status updates of commit _[44aadab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/44aadabc15dc45e16810b61c4fad6bfd261e25ff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-1e0c275d450d612d62f2231b8efe944d-ce1d9410)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-a2d62ab9f6b459f69fc3afc55dd2e493-ce1d9410)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-35d420330e368ed33d8897df21adf107-ce1d9410)
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-562522898370fa38b3a61fe580bb73a5-ce1d9410)
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0df772b87317bc32e0eec0ff73ff4547-ce1d9410)
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-062bdc35cf04300e49da1a95f6e09d5e-ce1d9410)
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-d4640b14c6f1b9e21c1ede42d38e9673-ce1d9410)
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-2da6cc1f580124691e231007dda03a50-ce1d9410)
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-c87ff59cdc31dde2127cd9ab8e1d489f-ce1d9410)
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-ce1d9410)
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-7f2755df6bc41479865ec6f46885a550-ce1d9410)
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-dc2edce33e521a8db361b03959d7c385-ce1d9410)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-ce1d9410)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-ce1d9410)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-ce1d9410)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmana [...]

2021-11-02 20:56 UTC, opbld32 commented
Docs Build status updates of commit _[7feb363](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7feb36305d5666e81cb43ceb86bbc375450a33f0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-1e0c275d450d612d62f2231b8efe944d-4ea7393f)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-a2d62ab9f6b459f69fc3afc55dd2e493-4ea7393f)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-35d420330e368ed33d8897df21adf107-4ea7393f)
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-562522898370fa38b3a61fe580bb73a5-4ea7393f)
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0df772b87317bc32e0eec0ff73ff4547-4ea7393f)
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-062bdc35cf04300e49da1a95f6e09d5e-4ea7393f)
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-d4640b14c6f1b9e21c1ede42d38e9673-4ea7393f)
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-2da6cc1f580124691e231007dda03a50-4ea7393f)
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-c87ff59cdc31dde2127cd9ab8e1d489f-4ea7393f)
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-4ea7393f)
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-7f2755df6bc41479865ec6f46885a550-4ea7393f)
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-dc2edce33e521a8db361b03959d7c385-4ea7393f)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-4ea7393f)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-4ea7393f)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-4ea7393f)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmana [...]

2021-11-04 12:27 UTC, opbld30 commented
Docs Build status updates of commit _[bcecd31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bcecd3177b2ae2eb9a20d2aefe39f3f07130b81f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-1e0c275d450d612d62f2231b8efe944d-b4d7ee36)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-a2d62ab9f6b459f69fc3afc55dd2e493-b4d7ee36)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-35d420330e368ed33d8897df21adf107-b4d7ee36)
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0df772b87317bc32e0eec0ff73ff4547-b4d7ee36)
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-062bdc35cf04300e49da1a95f6e09d5e-b4d7ee36)
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-d4640b14c6f1b9e21c1ede42d38e9673-b4d7ee36)
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-2da6cc1f580124691e231007dda03a50-b4d7ee36)
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-c87ff59cdc31dde2127cd9ab8e1d489f-b4d7ee36)
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-b4d7ee36)
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-7f2755df6bc41479865ec6f46885a550-b4d7ee36)
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-dc2edce33e521a8db361b03959d7c385-b4d7ee36)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-b4d7ee36)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-b4d7ee36)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-b4d7ee36)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-b4d7ee36)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805)  [...]

2021-11-04 12:44 UTC, opbld33 commented
Docs Build status updates of commit _[daf46b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/daf46b4d30ec08ebf03cb740c225c945b6199e82)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-a2d62ab9f6b459f69fc3afc55dd2e493-6dd46682)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-35d420330e368ed33d8897df21adf107-6dd46682)
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0df772b87317bc32e0eec0ff73ff4547-6dd46682)
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-062bdc35cf04300e49da1a95f6e09d5e-6dd46682)
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-d4640b14c6f1b9e21c1ede42d38e9673-6dd46682)
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-2da6cc1f580124691e231007dda03a50-6dd46682)
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-c87ff59cdc31dde2127cd9ab8e1d489f-6dd46682)
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-6dd46682)
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-7f2755df6bc41479865ec6f46885a550-6dd46682)
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-dc2edce33e521a8db361b03959d7c385-6dd46682)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-6dd46682)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-6dd46682)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-6dd46682)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-6dd46682)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-6dd46682)
[concepts/compliance-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/concepts/compliance-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/compliance-concept-overview?branch=pr-en-us-14805) | [Details](#user-content-299b5ea2606eecb490f1521f66bf366f-6dd46682)
[api-reference/beta/resources/recordsmanagement-retentio [...]

2021-11-04 12:58 UTC, opbld33 commented
Docs Build status updates of commit _[3323941](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3323941965648865664313bdc408799633cbb948)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0df772b87317bc32e0eec0ff73ff4547-9cac3fca)
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-062bdc35cf04300e49da1a95f6e09d5e-9cac3fca)
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-d4640b14c6f1b9e21c1ede42d38e9673-9cac3fca)
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-2da6cc1f580124691e231007dda03a50-9cac3fca)
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-c87ff59cdc31dde2127cd9ab8e1d489f-9cac3fca)
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-9cac3fca)
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-7f2755df6bc41479865ec6f46885a550-9cac3fca)
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-dc2edce33e521a8db361b03959d7c385-9cac3fca)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-9cac3fca)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-9cac3fca)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-9cac3fca)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-9cac3fca)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-9cac3fca)
[concepts/compliance-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/concepts/compliance-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/compliance-concept-overview?branch=pr-en-us-14805) | [Details](#user-content-299b5ea2606eecb490f1521f66bf366f-9cac3fca)
[api-reference/beta/resources/recordsmanagement-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventstatus.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventstatus?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ffa41686eb5bf307132490de422aa574-9cac3fca)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/bl [...]

2021-11-04 13:15 UTC, opbld31 commented
Docs Build status updates of commit _[0995642](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0995642f7fb97ba5b22e1faa151374ae772abfcf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0df772b87317bc32e0eec0ff73ff4547-049e7abf)
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-062bdc35cf04300e49da1a95f6e09d5e-049e7abf)
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-2da6cc1f580124691e231007dda03a50-049e7abf)
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-049e7abf)
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-7f2755df6bc41479865ec6f46885a550-049e7abf)
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-dc2edce33e521a8db361b03959d7c385-049e7abf)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-049e7abf)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-049e7abf)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-049e7abf)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-049e7abf)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-049e7abf)
[concepts/compliance-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/concepts/compliance-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/compliance-concept-overview?branch=pr-en-us-14805) | [Details](#user-content-299b5ea2606eecb490f1521f66bf366f-049e7abf)
[api-reference/beta/resources/recordsmanagement-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventstatus.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventstatus?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ffa41686eb5bf307132490de422aa574-049e7abf)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference [...]

2021-11-04 13:29 UTC, opbld33 commented
Docs Build status updates of commit _[49fded2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49fded222310d0eb806f5b0b15dda79949d1745d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0df772b87317bc32e0eec0ff73ff4547-a1d3c4b2)
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-062bdc35cf04300e49da1a95f6e09d5e-a1d3c4b2)
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-2da6cc1f580124691e231007dda03a50-a1d3c4b2)
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-a1d3c4b2)
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-7f2755df6bc41479865ec6f46885a550-a1d3c4b2)
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-dc2edce33e521a8db361b03959d7c385-a1d3c4b2)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-a1d3c4b2)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-a1d3c4b2)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-a1d3c4b2)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-a1d3c4b2)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a1d3c4b2)
[concepts/compliance-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/concepts/compliance-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/compliance-concept-overview?branch=pr-en-us-14805) | [Details](#user-content-299b5ea2606eecb490f1521f66bf366f-a1d3c4b2)
[api-reference/beta/resources/recordsmanagement-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventstatus.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventstatus?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ffa41686eb5bf307132490de422aa574-a1d3c4b2)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference [...]

2021-11-04 13:43 UTC, opbld34 commented
Docs Build status updates of commit _[59eddbf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/59eddbfc5f95317cc4d950fc8e48eb2d3b2df384)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-335fdec0)
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-7f2755df6bc41479865ec6f46885a550-335fdec0)
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-dc2edce33e521a8db361b03959d7c385-335fdec0)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-335fdec0)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-335fdec0)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-335fdec0)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-335fdec0)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-335fdec0)
[concepts/compliance-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/concepts/compliance-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/compliance-concept-overview?branch=pr-en-us-14805) | [Details](#user-content-299b5ea2606eecb490f1521f66bf366f-335fdec0)
[api-reference/beta/resources/recordsmanagement-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventstatus.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventstatus?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ffa41686eb5bf307132490de422aa574-335fdec0)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentio [...]

2021-11-05 13:38 UTC, opbld33 commented
Docs Build status updates of commit _[2bd8873](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2bd887397e56e3601dd6f37daee8db46ce01060e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-594e1d10)
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-7f2755df6bc41479865ec6f46885a550-594e1d10)
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-dc2edce33e521a8db361b03959d7c385-594e1d10)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-594e1d10)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-594e1d10)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-594e1d10)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-594e1d10)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-594e1d10)
[concepts/compliance-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/concepts/compliance-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/compliance-concept-overview?branch=pr-en-us-14805) | [Details](#user-content-299b5ea2606eecb490f1521f66bf366f-594e1d10)
[api-reference/beta/resources/recordsmanagement-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventstatus.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventstatus?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ffa41686eb5bf307132490de422aa574-594e1d10)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentio [...]

2021-11-05 13:49 UTC, opbld33 commented
Docs Build status updates of commit _[8fc261f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8fc261f70690a460608820d587f28fba12337c66)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0df772b87317bc32e0eec0ff73ff4547-8077d4e6)
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-062bdc35cf04300e49da1a95f6e09d5e-8077d4e6)
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-2da6cc1f580124691e231007dda03a50-8077d4e6)
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-8077d4e6)
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-7f2755df6bc41479865ec6f46885a550-8077d4e6)
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-dc2edce33e521a8db361b03959d7c385-8077d4e6)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-8077d4e6)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-8077d4e6)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-8077d4e6)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-8077d4e6)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8077d4e6)
[concepts/compliance-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/concepts/compliance-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/compliance-concept-overview?branch=pr-en-us-14805) | [Details](#user-content-299b5ea2606eecb490f1521f66bf366f-8077d4e6)
[api-reference/beta/resources/recordsmanagement-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventstatus.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventstatus?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ffa41686eb5bf307132490de422aa574-8077d4e6)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference [...]

2021-11-05 17:55 UTC, opbld32 commented
Docs Build status updates of commit _[a418a5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a418a5c75e01b613467f568e41c379b4f064c8ce)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0df772b87317bc32e0eec0ff73ff4547-b3205326)
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-062bdc35cf04300e49da1a95f6e09d5e-b3205326)
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-2da6cc1f580124691e231007dda03a50-b3205326)
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-b3205326)
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-7f2755df6bc41479865ec6f46885a550-b3205326)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-b3205326)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-b3205326)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-b3205326)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-b3205326)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b3205326)
[concepts/compliance-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/concepts/compliance-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/compliance-concept-overview?branch=pr-en-us-14805) | [Details](#user-content-299b5ea2606eecb490f1521f66bf366f-b3205326)
[api-reference/beta/resources/recordsmanagement-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventstatus.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventstatus?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ffa41686eb5bf307132490de422aa574-b3205326)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-reten [...]

2022-01-06 20:10 UTC, samriddhiseth commented
Pending error fixes.

2022-01-13 19:15 UTC, opbld32 commented
Docs Build status updates of commit _[ab2d1d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab2d1d2fccdb72220619e233a7fc3f7d641d80a4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0df772b87317bc32e0eec0ff73ff4547-f8a47484)
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-062bdc35cf04300e49da1a95f6e09d5e-f8a47484)
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-2da6cc1f580124691e231007dda03a50-f8a47484)
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-f8a47484)
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-7f2755df6bc41479865ec6f46885a550-f8a47484)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-f8a47484)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-f8a47484)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-f8a47484)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-f8a47484)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f8a47484)
[concepts/compliance-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/concepts/compliance-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/compliance-concept-overview?branch=pr-en-us-14805) | [Details](#user-content-299b5ea2606eecb490f1521f66bf366f-f8a47484)
[api-reference/beta/resources/recordsmanagement-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventstatus.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventstatus?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ffa41686eb5bf307132490de422aa574-f8a47484)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-reten [...]

2022-01-13 21:21 UTC, opbld32 commented
Docs Build status updates of commit _[f85b099](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f85b0990ea89a2123251ea6d35497a5da98ce751)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0df772b87317bc32e0eec0ff73ff4547-c1125399)
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-062bdc35cf04300e49da1a95f6e09d5e-c1125399)
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-2da6cc1f580124691e231007dda03a50-c1125399)
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-c1125399)
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-7f2755df6bc41479865ec6f46885a550-c1125399)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-c1125399)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-c1125399)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-c1125399)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-c1125399)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-c1125399)
[concepts/compliance-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/concepts/compliance-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/compliance-concept-overview?branch=pr-en-us-14805) | [Details](#user-content-299b5ea2606eecb490f1521f66bf366f-c1125399)
[api-reference/beta/resources/recordsmanagement-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventstatus.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventstatus?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ffa41686eb5bf307132490de422aa574-c1125399)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-reten [...]

2022-01-13 22:31 UTC, opbld32 commented
Docs Build status updates of commit _[9294e0e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9294e0e720bd41ee52fa8086650414dc01439209)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-2bcc8e45)
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-7f2755df6bc41479865ec6f46885a550-2bcc8e45)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-2bcc8e45)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-2bcc8e45)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-2bcc8e45)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-2bcc8e45)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-2bcc8e45)
[concepts/compliance-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/concepts/compliance-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/compliance-concept-overview?branch=pr-en-us-14805) | [Details](#user-content-299b5ea2606eecb490f1521f66bf366f-2bcc8e45)
[api-reference/beta/resources/recordsmanagement-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventstatus.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventstatus?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ffa41686eb5bf307132490de422aa574-2bcc8e45)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=grap [...]

2022-01-14 21:12 UTC, opbld31 commented
Docs Build status updates of commit _[84df9b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84df9b3c06d5130e56aa04b246a7202fcadec6f6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-7abcb416)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-7abcb416)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-7abcb416)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-7abcb416)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-7abcb416)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-7abcb416)
[concepts/compliance-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/concepts/compliance-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/compliance-concept-overview?branch=pr-en-us-14805) | [Details](#user-content-299b5ea2606eecb490f1521f66bf366f-7abcb416)
[api-reference/beta/resources/recordsmanagement-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventstatus.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventstatus?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ffa41686eb5bf307132490de422aa574-7abcb416)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/ [...]

2022-01-26 22:06 UTC, opbld30 commented
Docs Build status updates of commit _[b186141](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b186141ab8b11b65486e7f1a64539d13c4023d71)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-f7d216f3)
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-4402c7a8d00a3399ed9937d579d552a3-f7d216f3)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-f7d216f3)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-f7d216f3)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-f7d216f3)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f7d216f3)
[concepts/compliance-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/concepts/compliance-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/compliance-concept-overview?branch=pr-en-us-14805) | [Details](#user-content-299b5ea2606eecb490f1521f66bf366f-f7d216f3)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-delete.md](https://github. [...]

2022-02-01 00:30 UTC, opbld32 commented
Docs Build status updates of commit _[fe84704](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe84704d31a2a55806cbc6f579d91f56992066c2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/recordsmanagement-RMoverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-RMoverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-rmoverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-f05fe84ed23b2c4d5efe727b80f4a6b1-18e37a11)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-18e37a11)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-18e37a11)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-18e37a11)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-18e37a11)
[concepts/compliance-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/concepts/compliance-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/compliance-concept-overview?branch=pr-en-us-14805) | [Details](#user-content-299b5ea2606eecb490f1521f66bf366f-18e37a11)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M [...]

2022-02-01 01:17 UTC, opbld33 commented
Docs Build status updates of commit _[0c17418](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c17418200ad2833e5fd4985cf20015dcfe838f9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/recordsmanagement-RMoverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-RMoverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-rmoverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-f05fe84ed23b2c4d5efe727b80f4a6b1-5e1a1282)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-5e1a1282)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-5e1a1282)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-5e1a1282)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftg [...]

2022-02-02 19:50 UTC, opbld32 commented
Docs Build status updates of commit _[4094689](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4094689078aac3c44ab45b6f9bd3640e6352d5da)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/recordsmanagement-RMoverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-RMoverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-rmoverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-f05fe84ed23b2c4d5efe727b80f4a6b1-ff2e6c66)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-ff2e6c66)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-ff2e6c66)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-ff2e6c66)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftg [...]

2022-02-02 19:54 UTC, opbld33 commented
Docs Build status updates of commit _[5f93a65](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f93a6526479750b4aa01e3abd05b70cde5018d9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/recordsmanagement-RMoverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-RMoverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-rmoverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-f05fe84ed23b2c4d5efe727b80f4a6b1-88cd7141)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-88cd7141)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-88cd7141)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-88cd7141)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftg [...]

2022-02-22 20:29 UTC, opbld34 commented
Docs Build status updates of commit _[c31b3d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c31b3d08d22e6d09ceda2e18ba6e579a0ab3585c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-ad237ed5)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-ad237ed5)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-ad237ed5)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-Reco [...]

2022-02-22 20:57 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionevent.md
> +|id|String|Id of the Event Inherited from [entity](../resources/recordsmanagement-entity.md).|
@sseth-msft API doctor failed several times. I did not find the topic "records management-entity". However, I did find [](https://docs.microsoft.com/en-us/graph/api/resources/entity?view=graph-rest-beta ). Please verify.

2022-02-22 20:58 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentioneventtype.md
> +|id|String|Id of the EventType Inherited from [entity](../resources/recordsmanagement-entity.md).|
@sseth-msft[](https://docs.microsoft.com/en-us/graph/api/resources/entity?view=graph-rest-beta) API doctor failed several times. I did not find the topic "records management-entity". However, I did find . Please verify.

2022-02-22 21:03 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +|id|String|Id of the label Inherited from [entity](../resources/recordsmanagement-entity.md).|
@sseth-msft API doctor failed several times. I did not find the topic "records management-entity". However, I did find https://docs.microsoft.com/en-us/graph/api/resources/entity?view=graph-rest-beta. Please verify.

2022-02-22 21:04 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionevent.md
> +|id|String|Id of the Event Inherited from [entity](../resources/recordsmanagement-entity.md).|
@sseth-msft API doctor failed several times. I did not find the topic "records management-entity". However, I did find https://docs.microsoft.com/en-us/graph/api/resources/entity?view=graph-rest-beta. Please verify.

2022-02-24 18:51 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +description: "A retentionLabel allows a user to retain or delete content and configure additional settings and actions"
I suggest either of the two suggestions below: 
1. Represents how customers can manage their data, whether and for long to retain or delete it. 
2. Represents settings for customers to manage their data, whether and for long to retain or delete it.

2022-02-24 18:52 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +**TODO: Add Description**
Please use the description from line 3 here.

2022-02-24 18:57 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +|[List retentionEventType](../api/recordsmanagement-retentioneventtype-list.md)|[microsoft.graph.recordsManagement.retentionEventType](../resources/recordsmanagement-retentioneventtype.md) collection
This operation should not be in the retentionLabel resource topic. 
It seems that you should add a resource topic for recordsManagementRoot and include this operation in its respective methods table. Please review and confirm.

2022-02-24 18:57 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +|[Add retentionEventType](../api/recordsmanagement-recordsmanagementroot-post-eventtypes.md)|[microsoft.graph.recordsManagement.retentionEventType](../resources/recordsmanagement-retentioneventtype.m
This operation should not be in the retentionLabel resource topic. 
It seems that you should add a resource topic for recordsManagementRoot and include this operation in its respective methods table. Please review and confirm.

2022-02-24 19:23 UTC, opbld31 commented
Docs Build status updates of commit _[c11bf2c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c11bf2c44cc3c61736cb8c149891a3a5714202e2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-d6fe1281)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-d6fe1281)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-d6fe1281)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-Reco [...]

2022-02-28 18:36 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +|actionAfterRetentionPeriod|actionAfterRetentionPeriod|Specifies the action of a document that has been labeled with this label after the retention period. The possible values are: `none`, `delete`,
Please edit the description, my suggestion is: Specifies the action to be applied on a document with this label after the retention period. The possible values are: `none`, `delete`, `startDispositionReview`, `unknownFutureValue`.|

2022-02-28 18:59 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +|behaviorDuringRetentionPeriod|behaviorDuringRetentionPeriod|Specifies the behaviour of a document that has been labeled with this label during the retention period. The possible values are: `doNotRe
Please edit this description. My suggestion is: Specifies how the behavior of a document with this label should be during the retention period.

2022-02-28 19:22 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +|createdBy|[microsoft.graph.identitySet](/graph/api/resources/identityset)|The user who created the entity|
GLOBAL COMMENT (I will not be entering a comment on every instance, but please review all the files as this comment applies to all of them).
Every sentence should end with a period.

2022-02-28 21:29 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +|createdDateTime|DateTimeOffset|The date time when the entity was created|
Please edit this description, my suggestion is: Represents the date and time in which the entity is created.

2022-02-28 21:50 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +|descriptionForAdmins|String|Optional information about the label for the Admin|
Please edit this description, my suggestion is: This is an optional property that provides the label information for the admin.

2022-02-28 21:53 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +|descriptionForUsers|String|Optional information about the label for the User|
Please edit this description.

2022-02-28 21:55 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +|displayName|String|Unique string defining the name of the label|
Please edit this description. My suggestion is: Unique string that defines a label name.

2022-03-03 19:27 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +|dispositionReviewStages|[microsoft.graph.recordsManagement.dispositionReviewStage](../resources/recordsmanagement-dispositionreviewstage.md) collection|A multi stage collection of reviewers that wil
Please clarify the purpose of this property.

2022-03-03 19:28 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +|id|String|Id of the label Inherited from [entity](../resources/recordsmanagement-entity.md).|
GLOBAL COMMENT (I will not be entering a comment on every instance, but please review all the files as this comment applies to all of them).
Every sentence should end with a period.
Please edit this description, my suggestion is: Represents the user who created the entity.

2022-03-03 19:31 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md
> +description: "**Provides details about the reviewer and the review stage for a label set for a disposition review**"
Please consider this description: Represents the reviewers to approve at each stage of the disposition process of a document.

2022-03-03 19:32 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md
> +description: "**Provides details about the reviewer and the review stage for a label set for a disposition review**"
GLOBAL COMMENT (I will not be entering a comment on every instance, but please review all the files as this comment applies to all of them).
Why are some descriptions in bold? Please clarify.

2022-03-03 19:33 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md
> +For content that has a label set for a disposition review at the end of a retetnion period, the 'dispositionReviewStage' resource type can be used to retrieve details about the reviewer and review st
Please use the description from line 3.

2022-03-03 19:35 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-RMoverview.md
> +---
GLOBAL COMMENT (I will not be entering a comment on every instance, but please review all the files as this comment applies to all of them).
Filenames should all be in lowercase.

2022-03-10 02:55 UTC, opbld30 commented
Docs Build status updates of commit _[1724518](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1724518bc00cc5f29d625991146ea967eb3ed8e8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-85381072)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-85381072)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.co [...]

2022-03-10 02:57 UTC, opbld31 commented
Docs Build status updates of commit _[14279f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14279f610fba600ee6aaa37ed1a6f35b0208137f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-a6ef2a51)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a6ef2a51)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.co [...]

2022-03-10 03:35 UTC, opbld32 commented
Docs Build status updates of commit _[42a2aa5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42a2aa5fe0866a4102ab8b59dd3721cb9ce5ff95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rec [...]

2022-03-10 18:59 UTC, opbld30 commented
Docs Build status updates of commit _[6d84091](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d840911f13d02d7797cbd3a44a927937ca376e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rec [...]

2022-03-10 22:42 UTC, isvargasmsft commented
Hello @sseth-msft, 

What is the status of this PR? If you intent this PR to be reviewed and merged, would you be so kind to move it from Draft to Open?

Kind regards, 

Isaac

2022-03-14 20:01 UTC, Danielabom commented on api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md
> +|displayName|String|**Name of the event**Optional.|
Global comment:
Please address the feedback in every single file. Use period (to separate a sentence from the word "optional").
Please unbold descriptions.

2022-03-14 20:08 UTC, Danielabom commented on api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md
> +---
I did not find a resource topic for recordsManagementRoot, only for the operations. Please check.

2022-03-14 20:10 UTC, Danielabom commented on api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md
> +|messagesQuery|String|**Specifies the keywords that are used to scope Exchange content for the compliance retention event.** Optional.|
Please explain a little more what the purpose of the property is. We might need to edit the current description.

2022-03-14 20:12 UTC, Danielabom commented on api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md
> +|filesQuery|String|**Specifies one or more the Property:Value pairs that you've specified in the properties (also known as Columns) of SharePoint and OneDrive for Business documents to scope the comp
This description must be reviewed. Please explain a little more what the purpose of the property is

2022-03-14 20:20 UTC, Danielabom commented on api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md
> +---
I did not find a resource topic for recordsManagementRoot, only for the operations. Please check.

2022-03-14 20:21 UTC, Danielabom commented on api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md
> +---
I did not find a resource topic for recordsManagementRoot, only for the operations. Please check.

2022-03-14 20:24 UTC, Danielabom commented on api-reference/beta/api/recordsmanagement-retentionevent-get.md
> +This method supports some of the OData query parameters to help customize the response. For example, to retrieve the navigation property for labels,use $expand=labels. For general information, see [O
We recommend listing the OData query parameters supported.

2022-03-14 20:41 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md
> +|reviewers|String collection|A collection of reviewers at each stage|
Please make sure to end each description with a period.

2022-03-14 20:44 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-retentionevent.md
> +description: "Allows a user to manage labels where start of the retention period is based on when a specific type of event occurs"
Please elaborate on the purpose of the resource to create a more detailed description.

2022-03-14 20:45 UTC, Danielabom commented on api-reference/beta/resources/recordsmanagement-rm-overview.md
> +---
Please follow the file naming guidelines: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211751/File-naming

2022-03-14 20:46 UTC, Danielabom requested changes
Hi Samriddhi, please review the comments and reach out if you have any questions.

2022-03-18 23:19 UTC, opbld33 commented
Docs Build status updates of commit _[dacb39e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dacb39ed8b164ee902a7710258bc86a9b237b2a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/recordsmanagement-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rec [...]

2022-03-24 20:25 UTC, sseth-msft commented on api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md
> +|messagesQuery|String|**Specifies the keywords that are used to scope Exchange content for the compliance retention event.** Optional.|
When an event is triggered for an event-based label, keyword from the "messageQuery" fields are used to identify which files in Exchange should the label be applied to, ie scope of the label for that particular event trigger.

2022-03-24 20:29 UTC, sseth-msft commented on api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md
> +|filesQuery|String|**Specifies one or more the Property:Value pairs that you've specified in the properties (also known as Columns) of SharePoint and OneDrive for Business documents to scope the comp
When an event is triggered for an event-based label, asset IDs from the "filesQuery" fields are used to identify which files in SharePoint should the label be applied to, ie scope of the label for that particular event trigger.

2022-03-24 20:31 UTC, sseth-msft commented on api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md
> +---
Not clear what is required, do we have to add the root file? It is not required for us so we didnt add it.

2022-03-24 20:31 UTC, sseth-msft commented on api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md
> +---
Not clear what is required, do we have to add the root file? It is not required for us so we didnt add it.

2022-03-24 20:34 UTC, sseth-msft commented on api-reference/beta/api/recordsmanagement-retentionevent-get.md
> +This method supports some of the OData query parameters to help customize the response. For example, to retrieve the navigation property for labels,use $expand=labels. For general information, see [O
'$expand=labels' is the only applicable Odata parameter for this entity. Please let us know if anything else has to be added.

2022-04-12 00:17 UTC, opbld30 commented
Docs Build status updates of commit _[6898336](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68983364f0e6f25363d0bfe0d0decc66c14617e5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-3b063208)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-3b063208)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/recordsmanagement-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.co [...]

2022-04-13 19:17 UTC, opbld31 commented
Docs Build status updates of commit _[a22b793](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a22b79323fa2dc936f01758c12b574aaf781f500)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-9492915f2cf6397c5b6bdcbf9ea0e657-f787a7a6)
[api-reference/beta/resources/recordsmanagement-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81e4ea78678bfd3c967b2f65f6fbd9d6-f787a7a6)
[api-reference/beta/resources/recordsmanagement-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-72433b814c3c11b272b54dab6aa3984e-f787a7a6)
[api-reference/beta/resources/recordsmanagement-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/recordsmanagement-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recordsmanagement-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-031cdc9d3890271aa011f7fdbf84f887-f787a7a6)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f787a7a6)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/b [...]

2022-04-13 20:00 UTC, opbld30 commented
Docs Build status updates of commit _[cc2b247](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc2b247c531807ae7814ebb7dc495469b2f06a8a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-events?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-1e0c275d450d612d62f2231b8efe944d-7afc9cb1)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-a2d62ab9f6b459f69fc3afc55dd2e493-7afc9cb1)
[api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-35d420330e368ed33d8897df21adf107-7afc9cb1)
[api-reference/beta/api/recordsmanagement-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-562522898370fa38b3a61fe580bb73a5-7afc9cb1)
[api-reference/beta/api/recordsmanagement-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-dc26a62b288c0d8b89f0ed1d2624ae31-7afc9cb1)
[api-reference/beta/api/recordsmanagement-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionevent-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0df772b87317bc32e0eec0ff73ff4547-7afc9cb1)
[api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-7d051d23ba2a6e230d9ffc985a07afbb-7afc9cb1)
[api-reference/beta/api/recordsmanagement-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-81f5a3e8e043d04f1f959b4917bd9b2f-7afc9cb1)
[api-reference/beta/api/recordsmanagement-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-062bdc35cf04300e49da1a95f6e09d5e-7afc9cb1)
[api-reference/beta/api/recordsmanagement-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentioneventtype-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-d4640b14c6f1b9e21c1ede42d38e9673-7afc9cb1)
[api-reference/beta/api/recordsmanagement-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-f9c6a35ccab9843c5a30cfc972d7239e-7afc9cb1)
[api-reference/beta/api/recordsmanagement-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-e8130939b0a3fe1787bee9c34819feed-7afc9cb1)
[api-reference/beta/api/recordsmanagement-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-2da6cc1f580124691e231007dda03a50-7afc9cb1)
[api-reference/beta/api/recordsmanagement-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/recordsmanagement-retentionlabel-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recordsmanagement-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-c87ff59cdc31dde2127cd9ab8e1d489f-7afc9cb1)
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-recordsManagement-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-50bca6ffa4966386f9db49effc9c867e-7afc9cb1)
[api-reference/beta/resources/security-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionevent?view [...]

2022-04-13 22:23 UTC, sseth-msft commented on api-reference/beta/api/recordsmanagement-retentionevent-get.md
> +This method supports some of the OData query parameters to help customize the response. For example, to retrieve the navigation property for labels,use $expand=labels. For general information, see [O
No, this is all for now. Will update changes if we have any.

2022-04-13 22:23 UTC, opbld31 commented
Docs Build status updates of commit _[9da739e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9da739ecb177baf9dd3459fab928f13754186862)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-e1b9363f363efad3c79eba866e4bd53b-92670ac8)
[api-reference/beta/resources/security-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-122a2db46aae07429dcf2db49af5f136-92670ac8)
[api-reference/beta/resources/security-retentioneventtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-retentioneventtype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentioneventtype?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-25d0de9015eb1b1c6a9ebe34f44e555a-92670ac8)
[api-reference/beta/resources/security-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ce00fdc4717418796484ed7b95b5d414-92670ac8)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-92670ac8)
[api-reference/beta/api/security-recordsmanagementroot-post-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-recordsmanagementroot-post-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-recordsmanagementroot-post-labels?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-triggertypesroot-post-eventtypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-triggertypesroot-post-eventtypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-triggertypesroot-post-eventtypes?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-triiggersroot-post-retentionevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-triiggersroot-post-retentionevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-triiggersroot-post-retentionevents?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsMan [...]

2022-04-13 22:24 UTC, sseth-msft commented on api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-eventtypes.md
> +---
renamed the file, this one does not exist.

2022-04-13 22:24 UTC, sseth-msft commented on api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-labels.md
> +---
renamed the file, this one does not exist.

2022-04-13 22:25 UTC, sseth-msft commented on api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md
> +|filesQuery|String|**Specifies one or more the Property:Value pairs that you've specified in the properties (also known as Columns) of SharePoint and OneDrive for Business documents to scope the comp
do you have any suggestions for this one? @Danielabom

2022-04-13 22:25 UTC, sseth-msft commented on api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md
> +|messagesQuery|String|**Specifies the keywords that are used to scope Exchange content for the compliance retention event.** Optional.|
@Danielabom please suggest

2022-04-13 22:26 UTC, sseth-msft commented on api-reference/beta/api/recordsmanagement-recordsmanagementroot-post-events.md
> +---
file renamed

2022-04-13 22:51 UTC, opbld30 commented
Docs Build status updates of commit _[df37d66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df37d660c0d06a254e81eafc90f38bd43a9fa0b8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-122a2db46aae07429dcf2db49af5f136-c7c87aec)
[api-reference/beta/resources/security-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ce00fdc4717418796484ed7b95b5d414-c7c87aec)
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
 [...]

2022-05-31 19:57 UTC, opbld30 commented
Docs Build status updates of commit _[4ef9df1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ef9df130cd40f1ef44574bdf82d221cb7834471)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-122a2db46aae07429dcf2db49af5f136-0aa222d5)
[api-reference/beta/resources/security-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ce00fdc4717418796484ed7b95b5d414-0aa222d5)
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2022-05-31 20:19 UTC, opbld34 commented
Docs Build status updates of commit _[ae7d02c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae7d02c954581070bea7511f38c4e680d2056a6b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-122a2db46aae07429dcf2db49af5f136-b61fd8ce)
[api-reference/beta/resources/security-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ce00fdc4717418796484ed7b95b5d414-b61fd8ce)
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2022-06-06 21:46 UTC, opbld32 commented
Docs Build status updates of commit _[63da2a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63da2a355cb847e2f3426712690db6645c12dca9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentioneventstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentioneventstatus?view=graph-rest-beta&b [...]

2022-06-06 22:14 UTC, opbld32 commented
Docs Build status updates of commit _[069d259](https://github.com/microsoftgraph/microsoft-graph-docs/commits/069d259af2aa349a2ab7258376b20a3d3662ca0f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentioneventstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentioneventstatus?view=graph-rest-beta&b [...]

2022-06-07 16:32 UTC, millicentachieng commented on api-reference/beta/api/security-retentionlabel-update.md
> +  "truncated": true
You need to specify the response type here e.g. `
```suggestion
  "truncated": true,
  "@odata.type": "microsoft.graph.security.retentionLabel"
```

2022-06-07 16:33 UTC, millicentachieng commented on api-reference/beta/api/security-retentioneventtype-update.md
> +  "truncated": true
Add response type
```suggestion
  "truncated": true,
   "@odata.type": "microsoft.graph.security.retentionEventType"
```

2022-06-07 16:38 UTC, millicentachieng commented on api-reference/beta/resources/security-retentionlabel.md
> +|eventType|[retentionEventType](../resources/security-retentioneventtype.md)|Optional value that specifies the event that will start the retention period for labels that use this event type.|
```suggestion
|eventType|[microsoft.graph.security.retentionEventType](../resources/security-retentioneventtype.md)|Optional value that specifies the event that will start the retention period for labels that use this event type.|
```

2022-06-07 18:01 UTC, sseth-msft commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +|[List retentionEventType](../api/recordsmanagement-retentioneventtype-list.md)|[microsoft.graph.recordsManagement.retentionEventType](../resources/recordsmanagement-retentioneventtype.md) collection
Hi @Danielabom , there is a seaprate page for eventtype with all the operatios, however, since it is related to label (also defined under relationship), its added here. guide me if these need to be removed?

2022-06-07 18:11 UTC, opbld31 commented
Docs Build status updates of commit _[65bad3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65bad3a96bd20a4c1eafeb0db670f1005303a530)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentioneventstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentioneventstatus?view=graph-rest-beta&b [...]

2022-06-07 18:15 UTC, opbld34 commented
Docs Build status updates of commit _[b9de547](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9de547bddb0fdef117ade2f2146751eb3a3b33d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentioneventstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentioneventstatus?view=graph-rest-beta&b [...]

2022-06-07 18:19 UTC, opbld32 commented
Docs Build status updates of commit _[322fed0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/322fed062d67aca6a6c4d23bdad9181de9bb5b62)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentioneventstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentioneventstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentioneventstatus?view=graph-rest-beta&b [...]

2022-06-07 23:58 UTC, opbld30 commented
Docs Build status updates of commit _[88ca0f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88ca0f10ff3fdee10d66ba089d5a4852814fd455)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ccffafda609d7f962951eb0da7b251b3-dfe39bd2)
[api-reference/beta/resources/security-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-122a2db46aae07429dcf2db49af5f136-dfe39bd2)
[api-reference/beta/resources/security-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ce00fdc4717418796484ed7b95b5d414-dfe39bd2)
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventQueries](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-eventQueries) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) [...]

2022-06-08 21:26 UTC, opbld34 commented
Docs Build status updates of commit _[8e98248](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e982481be08669e23b1b2faea7324f4f1d59ea8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-1037bac2089dbaaebf271fd411dc4b43-cbf7d773)
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-f3eef9d6a3b0bb6ea2cd6d71a14f64de-cbf7d773)
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-60cae416535d005301bacef039cd4cfc-cbf7d773)
[api-reference/beta/resources/security-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-122a2db46aae07429dcf2db49af5f136-cbf7d773)
[api-reference/beta/resources/security-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ce00fdc4717418796484ed7b95b5d414-cbf7d773)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-cbf7d773)
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventQueries](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365- [...]

2022-06-08 23:39 UTC, opbld33 commented
Docs Build status updates of commit _[efc2bad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/efc2bad8305864a53aca6a17c912a018e8a46964)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-1037bac2089dbaaebf271fd411dc4b43-e1671a9f)
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-f3eef9d6a3b0bb6ea2cd6d71a14f64de-e1671a9f)
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-60cae416535d005301bacef039cd4cfc-e1671a9f)
[api-reference/beta/resources/security-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-122a2db46aae07429dcf2db49af5f136-e1671a9f)
[api-reference/beta/resources/security-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ce00fdc4717418796484ed7b95b5d414-e1671a9f)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-e1671a9f)
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventQueries](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365- [...]

2022-06-08 23:42 UTC, opbld30 commented
Docs Build status updates of commit _[4ce1888](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ce1888c45581487ac73e7d13a585aa467ae89db)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-1037bac2089dbaaebf271fd411dc4b43-6c533bd0)
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-f3eef9d6a3b0bb6ea2cd6d71a14f64de-6c533bd0)
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-60cae416535d005301bacef039cd4cfc-6c533bd0)
[api-reference/beta/resources/security-retentionevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionevent?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-122a2db46aae07429dcf2db49af5f136-6c533bd0)
[api-reference/beta/resources/security-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ce00fdc4717418796484ed7b95b5d414-6c533bd0)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-6c533bd0)
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventQueries](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365- [...]

2022-06-09 01:30 UTC, Lauragra commented on api-reference/beta/resources/security-eventQueries
> +title: "eventQuery resource type"
This file is missing the .md extension; please fix.

2022-06-09 01:31 UTC, Lauragra commented on api-reference/beta/resources/security-retentionDuration
> +title: "retentionDuration resource type"
This file is missing the .md extension; please fix. Also note that file names should be all lowercase, so please change the D to d.

2022-06-09 14:56 UTC, opbld31 commented
Docs Build status updates of commit _[f887b41](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f887b41764141adc8f9763d61bcca4bd555a3f32)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-f3eef9d6a3b0bb6ea2cd6d71a14f64de-990f6273)
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-60cae416535d005301bacef039cd4cfc-990f6273)
[api-reference/beta/resources/security-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ce00fdc4717418796484ed7b95b5d414-990f6273)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-990f6273)
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https:// [...]

2022-06-09 15:38 UTC, opbld30 commented
Docs Build status updates of commit _[16c9199](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16c91993eba4aead837ae5dd8053492d76205474)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-f3eef9d6a3b0bb6ea2cd6d71a14f64de-18574cde)
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-60cae416535d005301bacef039cd4cfc-18574cde)
[api-reference/beta/resources/security-retentionlabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionlabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionlabel?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-ce00fdc4717418796484ed7b95b5d414-18574cde)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-18574cde)
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https:// [...]

2022-06-09 17:16 UTC, opbld33 commented
Docs Build status updates of commit _[72c9de6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/72c9de69c39df3dc86fd16407ca61665886d1c3d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-retentiondurationforever.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentiondurationforever.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentiondurationforever?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-d99e209a8302957b61d3f0655cde6141-164dfa73)
[api-reference/beta/resources/security-retentiondurationindays.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentiondurationindays.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentiondurationindays?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-66d94f0471322b030f2143ba3e22649d-164dfa73)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-164dfa73)
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://rev [...]

2022-06-09 17:21 UTC, opbld32 commented
Docs Build status updates of commit _[3eb09f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3eb09f4223aafe1d6d18e2006f318ef85adfdf5c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-retentiondurationforever.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentiondurationforever.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentiondurationforever?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-d99e209a8302957b61d3f0655cde6141-1b14abcc)
[api-reference/beta/resources/security-retentiondurationindays.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentiondurationindays.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentiondurationindays?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-66d94f0471322b030f2143ba3e22649d-1b14abcc)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-1b14abcc)
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://rev [...]

2022-06-09 17:25 UTC, opbld34 commented
Docs Build status updates of commit _[fb29187](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb29187e457295c36b40a71eb765d2c792a1a0ae)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-retentiondurationforever.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentiondurationforever.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentiondurationforever?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-d99e209a8302957b61d3f0655cde6141-d7eac048)
[api-reference/beta/resources/security-retentiondurationindays.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentiondurationindays.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentiondurationindays?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-66d94f0471322b030f2143ba3e22649d-d7eac048)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d7eac048)
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://rev [...]

2022-06-09 17:34 UTC, opbld30 commented
Docs Build status updates of commit _[51966a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/51966a212e4f12af645d75caba1e41c4aab5a472)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-retentiondurationforever.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentiondurationforever.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentiondurationforever?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-d99e209a8302957b61d3f0655cde6141-839e4231)
[api-reference/beta/resources/security-retentiondurationindays.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentiondurationindays.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentiondurationindays?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-66d94f0471322b030f2143ba3e22649d-839e4231)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-839e4231)
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://rev [...]

2022-06-09 17:52 UTC, opbld34 commented
Docs Build status updates of commit _[85e0b14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85e0b14d5ff20e8c6fcac6bac8c18ff6f3da439b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/security-retentiondurationforever.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentiondurationforever.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentiondurationforever?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-d99e209a8302957b61d3f0655cde6141-92527611)
[api-reference/beta/resources/security-retentiondurationindays.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentiondurationindays.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentiondurationindays?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-66d94f0471322b030f2143ba3e22649d-92527611)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-92527611)
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://rev [...]

2022-06-09 18:47 UTC, sseth-msft commented on api-reference/beta/resources/recordsmanagement-retentionlabel.md
> +|dispositionReviewStages|[microsoft.graph.recordsManagement.dispositionReviewStage](../resources/recordsmanagement-dispositionreviewstage.md) collection|A multi stage collection of reviewers that wil
modified

2022-06-09 18:50 UTC, sseth-msft commented on api-reference/beta/resources/recordsmanagement-dispositionreviewstage.md
> +For content that has a label set for a disposition review at the end of a retetnion period, the 'dispositionReviewStage' resource type can be used to retrieve details about the reviewer and review st
modified

2022-06-09 19:07 UTC, sseth-msft commented on api-reference/beta/resources/recordsmanagement-retentionevent.md
> +description: "Allows a user to manage labels where start of the retention period is based on when a specific type of event occurs"
modified

2022-06-09 21:17 UTC, sseth-msft commented on api-reference/beta/resources/recordsmanagement-eventpropagationresult.md
> +description: "For event-based retention, this attribute can provide the status of event propogation after it is created."
modified.

2022-06-09 21:34 UTC, opbld31 commented
Docs Build status updates of commit _[7183169](https://github.com/microsoftgraph/microsoft-graph-docs/commits/71831695e18a91e522eeb17f24131a1b38a67388)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-21b0ce30)
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-be [...]

2022-06-09 23:52 UTC, opbld30 commented
Docs Build status updates of commit _[e2d6007](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2d60077a58cac19b239aaa3fced942aaa5f3948)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-10 03:03 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-delete.md
> +Deletes a [retentionEvent](../resources/security-retentionevent.md) object.
For method topics, we use an imperative verb, so please change "Deletes" to "Delete" here.

2022-06-10 03:06 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-post.md
> +|Delegated (work or school account)|recordsManagement.ReadWrite.All|
It doesn't look like this permission is documented in the Permissions reference topic (https://docs.microsoft.com/en-us/graph/permissions-reference); please add that. Please also note that permission names are initial capped and change all occurrences to RecordsManagement.ReadWrite.All.

2022-06-10 03:07 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-delete.md
> +|Delegated (work or school account)|recordsManagement.ReadWrite.All|
It doesn't look like this permission is documented in the Permissions reference topic (https://docs.microsoft.com/en-us/graph/permissions-reference); please add that. Please also note that permission names are initial capped and change all occurrences to RecordsManagement.ReadWrite.All.

2022-06-10 03:07 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-delete.md
> +|Delegated (personal Microsoft account)|Not supported|
The "Not supported" phrase should end with a period.

2022-06-10 03:07 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-delete.md
> +>**Note:** The response object shown here might be shortened for readability.
Please remove this Note when there is no response body.

2022-06-10 03:08 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-delete.md
> +DELETE https://graph.microsoft.com/beta/security/triggers/retentionEvents/{retentionEventId}
It's helpful to use real-looking IDs in examples instead of placeholders; please update the examples if possible.

2022-06-10 03:12 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-get.md
> +This method supports some of the OData query parameters to help customize the response. For example, to retrieve the navigation property for labels,use $expand=labels. For general information, see [O
You're missing a space between labels, and use. Also, we use inline code formatting for parameters, so please format like this; `$expand=labels`. The standard boilerplate text is to say "some of the OData query parameters"; it's helpful if you can be more specific where possible. For example, which parameters in addition to $expand are supported? Are all of them supported?

Also, I'm not seeing a labels nav property on the retentionEvent resource type; please verify that example?

2022-06-10 17:02 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-list.md
> +This method supports some of the OData query parameters to help customize the response. For example, to retrieve the navigation property for labels,use $expand=labels. For general information, see [O
Same comments here about this section as for the GET operation topic.

2022-06-10 17:03 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-list.md
> +      "displayName": "String",
Global: For a better user experience of the content, please update all examples to include actual fictitious values instead of placeholders.

2022-06-10 18:09 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-post.md
> +You can specify the following properties when creating a retentionEvent.
When we use a resource name, we apply bold formatting; please format references to resources in text as bold, i.e. **retentionEvent**. Also, suggested revision to make this sentence more clear: "Specify the following properties when you create a **retentionEvent**."

2022-06-10 18:12 UTC, Lauragra commented on api-reference/beta/resources/security-eventpropagationresult.md
> +Represents the success status of a created event and additional information about the targetted locations.
Please correct the typo - "targeted". Actually, this description doesn't seem accurate because the status can also be "failed", for example. Suggested revision: "Represents the status of an event creation request and additional information about the event."

2022-06-10 18:15 UTC, Lauragra commented on api-reference/beta/resources/security-eventpropagationresult.md
> +|status|eventPropagationStatus|Is the event completed. The possible values are: `none`, `inProcessing`, `failed`, `success`.|
Suggested revision: "Indicates the status of the event creation request."

2022-06-10 18:16 UTC, Lauragra commented on api-reference/beta/resources/security-eventpropagationresult.md
> +|statusInformation|String|Additional infroamtion about the status.|
Is this description sufficiently clear? Would this be accurate: "Additional information about the status of the event creation request." Also, please fix the typo, should be "information".

2022-06-10 18:17 UTC, Lauragra commented on api-reference/beta/resources/security-eventpropagationresult.md
> +|serviceName|String|Workload being targetted by the event.|
Targetted is misspelled here too. For globalization/voice, let's try to avoid warlike metaphors. Suggested revision: "The name of the service associated with the event."

2022-06-10 18:18 UTC, Lauragra commented on api-reference/beta/resources/security-eventpropagationresult.md
> +|location|String|Specific location in the workload.|
This description also isn't super clear; suggested revision: "The location of the service associated with the event."

2022-06-10 18:24 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-post.md
> +|eventPropagationResult|[microsoft.graph.security.eventPropagationResult](../resources/security-eventpropagationresult.md)|Status and errors of the Event Sync.|
This description doesn't match the description of the eventPropagationResult resource type. Suggested revision: "The status of the event creation request." Also, is this something that can be specified on creation? It seems like it only returns the results of the request....

2022-06-10 18:27 UTC, Lauragra commented on api-reference/beta/resources/security-eventqueries.md
> +Specifies property value pairs: the workload type (SPO. ODB, EXO) and identification for an item to scope the retention event.
This description doesn't seem sufficiently clear. Would this be accurate: "Represents the service and identification information associated with a retention event." Also note that we don't form acronyms of trademarked product names, so if you want to list the possible values, you will need to spell them out - SharePoint Online, OneDrive for Business, Exchange Online.

2022-06-10 18:28 UTC, Lauragra commented on api-reference/beta/resources/security-eventqueries.md
> +|queryType|queryType|Defines the workload scope for the label- 'files' for SPO and ODB and 'messages' for EXO.The possible values are: `files`, `messages`, `unknownFutureValue`.|
It's not clear here what label you're referring to; can you please clarify this description? Would it be "Represents the type of query associated with an event."?

2022-06-10 18:29 UTC, Lauragra commented on api-reference/beta/resources/security-eventqueries.md
> +|query|String|Specifies scope for label items- Asset ID for SPO and ODB, keywords for exchange.|
Please clarify this description too, what are the label items that you're referring to? And update the references to the product names. Exchange needs to be capitalized.

2022-06-10 19:39 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-post.md
> +|eventQueries|[microsoft.graph.security.eventQueries](../resources/security-eventqueries.md) collection| Specifies property value pairs: the workload type (SPO. ODB, EXO) and identification for an it
Please see my comment on the eventQueries resource topic and adjust the description here to be more clear as well.

2022-06-10 19:41 UTC, Lauragra commented on api-reference/beta/resources/security-retentionevent.md
> +|id|String|Represents the user who created the [entity](/graph/api/resources/entity).|
This description appears to be the same as the description of the createdBy property - can you please double check?

2022-06-10 19:43 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-post.md
> +|lastModifiedBy|[microsoft.graph.identitySet](/graph/api/resources/identityset)|The latest user who modified the entity.|
Please be sure to double-check that these are all properties that can/should be specified on creation; modifications seem like they would require the event to already have been created?

2022-06-10 19:43 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-post.md
> +|id|String|Represents the user who created the [entity](/graph/api/resources/entity).|
Double-check this description per my comment on the resource topic.

2022-06-10 19:44 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-post.md
> +|retentionEventStatus|[microsoft.graph.security.retentionEventStatus](../resources/security-retentioneventstatus.md) collection|Specifies the number of processed documents per workload.|
This description doesn't match the description in the retentionEventStatus resource topic - please clarify.

2022-06-10 20:17 UTC, Lauragra commented on api-reference/beta/api/security-retentioneventtype-delete.md
> +Deletes a [retentionEventType](../resources/security-retentioneventtype.md) object.
Change Deletes to Delete.

2022-06-10 21:08 UTC, Lauragra commented on api-reference/beta/api/security-retentioneventtype-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Global: For GET and LIST operation topics that include this section, please be more specific about which query parameters are supported, if possible.

2022-06-10 21:09 UTC, Lauragra commented on api-reference/beta/api/security-retentioneventtype-post.md
> +Create a new retentionEventType object.
Please make the first occurrence of a resource name a link to that resource topic.

2022-06-10 21:10 UTC, Lauragra commented on api-reference/beta/api/security-retentioneventtype-post.md
> +|description|String|Optional information about the event type. Optional.|
Suggest removing the first occurrence of Optional here to remove redundancy. "Information about the event type. Optional." would be sufficient.

2022-06-10 21:19 UTC, Lauragra commented on api-reference/beta/resources/security-retentioneventtype.md
> +For more information, read [Start retention when an event occurs](/microsoft-365/compliance/event-driven-retention).
For voice and consistency, please rephrase as: "For details, see [Start retention when an event occurs](/microsoft-365/compliance/event-driven-retention)."

2022-06-10 21:20 UTC, Lauragra commented on api-reference/beta/resources/security-retentioneventtype.md
> +When an event is created, it is associated to a specific event type. The creation of this event then triggers all retention labels which have the same event type chosen in the label wizard. Only cont
This is not a clear description of the resource type. Would a clear description here be: "Represents the type associated with a retention event." 

In general, I'm not sure that the flow described here is completely clear. Here is a suggestion:
"When a retention event is created, a specific event type is associated with it, and this event type is applied as a label. Only content with that retention label applied will be retained for the specified retention period."

2022-06-10 21:21 UTC, Lauragra commented on api-reference/beta/api/security-retentioneventtype-post.md
> +|createdBy|[microsoft.graph.identitySet](/graph/api/resources/identityset)|The user who created the entity. Optional.|
Is it okay to use the generic word "entity" here, or would it be better to be more specific, i.e. "The user who created the retention event type." This comment applies globally to the descriptions that refer to "entity".

2022-06-10 21:21 UTC, Lauragra commented on api-reference/beta/api/security-retentioneventtype-post.md
> +|lastModifiedDateTime|DateTimeOffset|The latest date time when the entity was modified. Optional.|
Please verify that modified is relevant when it's a CREATE operation.

2022-06-10 21:24 UTC, Lauragra commented on api-reference/beta/api/security-retentioneventtype-update.md
> +|description|String|Optional information about the event type. Optional.|
Remove the first Optional here.

2022-06-10 21:24 UTC, Lauragra commented on api-reference/beta/api/security-retentioneventtype-update.md
> +|createdBy|[microsoft.graph.identitySet](/graph/api/resources/identityset)|The user who created the entity. Optional.|
Please see my comment in the previous topic about the use of the generic "entity" and update accordingly here as well.

2022-06-10 21:26 UTC, Lauragra commented on api-reference/beta/api/security-retentioneventtype-update.md
> +# [HTTP](#tab/http)
Please remove line 63. This line is added via automation when the SDK snippets are generated.

2022-06-10 21:26 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-delete.md
> +Deletes a [retentionLabel](../resources/security-retentionlabel.md) object.
Change Deletes to Delete.

2022-06-10 21:38 UTC, Lauragra commented on api-reference/beta/resources/security-retentionlabel.md
> +|eventType|[microsoft.graph.security.retentionEventType](../resources/security-retentioneventtype.md)|Optional value that specifies the event that will start the retention period for labels that use
This description is not clear. Suggested revision: "Represents the type associated with a retention event."

2022-06-10 21:48 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-list.md
> +This method supports some of the OData query parameters to help customize the response.  For example, to retrieve the navigation property for event type, use $expand=eventtype. For general informatio
Please revise the second sentence as follows: "For example, to retrieve the **eventType** property, you can use the `$expand` parameter: `$expand=eventtype`.

2022-06-10 21:53 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-post.md
> +You can specify the following properties when creating a retentionLabel.
Revise as: "Specify the following properties when you create a **retentionLabel**."

2022-06-10 21:55 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-post.md
> +|behaviorDuringRetentionPeriod|behaviorDuringRetentionPeriod|Specifies how the behavior of a document with this label should be during the retention period. The possible values are: `doNotRetain`, `r
Suggested revision for this property description: "Specifies the action to take on a document with this label applied during the retention period. The possible values...".

2022-06-10 22:03 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-post.md
> +|createdBy|[microsoft.graph.identitySet](/graph/api/resources/identityset)|Represents the user who created the entity.|
Same comment here about whether the reference to entity is specific enough.

2022-06-10 22:04 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-post.md
> +|descriptionForAdmins|String|This is an optional property that provides the label information for the admin.|
Suggested revision: Provides label information for the admin. Optional.

2022-06-10 22:04 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-post.md
> +|descriptionForUsers|String|This is an optional property that provides the label information for the user.|
Suggested revision: Provides label information for the user. Optional.

2022-06-10 22:09 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-post.md
> +|dispositionReviewStages|[microsoft.graph.security.dispositionReviewStage](../resources/security-dispositionreviewstage.md) collection|A multi stage collection of reviewers who will be notified for a
Suggested revision: "A multi-stage collection of reviewers who will be notified to determine whether a document must be deleted or retained."

I'm not sure that the phrase "multi-stage collection of reviewers" is clear. If accurate, you might rephrase as: "Review stages during which reviewers are notified to determine whether a document must be deleted or retained." I'm basing that suggestion on the property name - that it's about the review stages, rather than the reviewers.

2022-06-10 22:09 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-post.md
> +|id|String|Id of the label Inherited from [entity](/graph/api/resources/entity).|
ID is an abbreviation and should be capped. Please also add a period after label.

2022-06-10 22:10 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-post.md
> +|isInUse|Boolean|Specifies if the label is currently being used.|
Please change "if" to "whether".

2022-06-10 22:11 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-post.md
> +|lastModifiedBy|[microsoft.graph.identitySet](/graph/api/resources/identityset)|The latest user who modified the entity.|
Slight revision for clarity: "The user who last modified the entity." (You might change entity to retention label.)

2022-06-10 22:11 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-post.md
> +|retentionTrigger|retentionTrigger|Specifies if the retention duration is calculated from the content creation date, labeled date, or last modification date. The possible values are: `dateLabeled`, `
Please change "if" to "whether".

2022-06-10 22:12 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-post.md
> +|defaultRecordBehavior|defaultRecordBehavior|Specifies the locked or unlocked state of a record label when it is created.The possible values are: `startLocked`, `startUnlocked`, `unknownFutureValue`.
Please add a space after the period.

2022-06-10 22:13 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-post.md
> +|labelToBeApplied|String|Specifies the replacement label to be automatically applied once the retention period of the current label is completed. |
Suggested revision for clarity/Microsoft voice: "Specifies the replacement label to be applied automatically after the retention period of the current label ends."

2022-06-10 22:14 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-post.md
> +The following is an example of the response
Add a period here.

2022-06-10 22:19 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-update.md
> +|behaviorDuringRetentionPeriod|behaviorDuringRetentionPeriod|Specifies how the behavior of a document with this label should be during the retention period. The possible values are: `doNotRetain`, `r
Suggested revision for this property description: "Specifies the action to take on a document with this label applied during the retention period. The possible values...".

2022-06-10 22:19 UTC, Lauragra commented on api-reference/beta/api/security-retentionlabel-update.md
> +|createdBy|[microsoft.graph.identitySet](/graph/api/resources/identityset)|Represents the user who created the entity.|
Please reference my comments on the properties table in the previous topic and apply the same updates here.

2022-06-10 22:20 UTC, Lauragra commented on api-reference/beta/resources/complianceapioverview.md
> +## Records Management (Preview)
We use sentence case for headings, so please update this to "Records management (preview)".

2022-06-10 22:25 UTC, Lauragra commented on api-reference/beta/resources/complianceapioverview.md
> +Records Management solution in M365 provides the capability to manage regulatory, legal, and business-critical records across corporate data. It helps organizations manage retention and deletion of d
Please revise as follows:
Records management in Microsoft 365 provides the ability to manage regulatory, legal, and business-critical records across corporate data. It helps organizations manage retention and deletion of data to meet their legal obligations and compliance regulations, and increases efficiency by enabling the regular disposition of items that no longer have to be retained. 

For more details, see [Microsoft 365 records management](/microsoft-365/compliance/records-management).

2022-06-10 22:26 UTC, Lauragra commented on api-reference/beta/resources/security-dispositionreviewstage.md
> +To read more about disposition of data, see [Disposition of content](/microsoft-365/compliance/disposition).
For consistency and to be more concise, revise as: "For details, see [Disposition of content](/microsoft-365/compliance/disposition)."

2022-06-10 22:28 UTC, Lauragra commented on api-reference/beta/resources/security-dispositionreviewstage.md
> +|[Create dispositionReviewStage](../api/security-retentionlabel-post.md)|[microsoft.graph.security.dispositionReviewStage](../resources/security-dispositionreviewstage.md)|Create a new [dispositionRe
These two method topics don't exist; these are links to method topics for retention labels. Are we missing these two method topics in this PR?

2022-06-10 22:30 UTC, Lauragra commented on api-reference/beta/resources/security-dispositionreviewstage.md
> +Represents a multi-level review process where the reviewers approve at each stage of the disposition to delete or further retain the content item.
It's not clear from this description whether approval means to delete or retain. Would it be accurate to revise as: "Represents a multi-level review process where the reviewers indicate at each stage of the disposition whether to delete or further retain the content item."

2022-06-10 22:30 UTC, Lauragra commented on api-reference/beta/resources/security-dispositionreviewstage.md
> +|id|String|Unique ID for each stage|
Global: Please ensure that all descriptions end with periods.

2022-06-11 00:14 UTC, Lauragra commented on api-reference/beta/resources/security-dispositionreviewstage.md
> +  "@odata.type": "#microsoft.graph.security.dispositionReviewStage",
Global: Please show the properties in the JSON representation in alphabetical order. The properties in the Properties tables should also be alphabetized.

2022-06-11 00:19 UTC, Lauragra commented on api-reference/beta/resources/complianceapioverview.md
> +Records Management solution in M365 provides the capability to manage regulatory, legal, and business-critical records across corporate data. It helps organizations manage retention and deletion of d
Please also add a sentence about the subnamespace:
The records management API is defined in the OData subnamespace, microsoft.graph.security.

2022-06-11 00:22 UTC, Lauragra commented on api-reference/beta/api/security-retentionevent-get.md
> +If successful, this method returns a `200 OK` response code and a [retentionEvent](../resources/security-retentionevent.md) object in the response body.
Global: Per the guidance for APIs that are defined in a subnamespace, we fully qualify the type in the Response section. So for methods that return a type, please include the namespace. In this example, replace retentionEvent with microsoft.graph.security.retentionEvent.

2022-06-11 00:24 UTC, Lauragra commented on api-reference/beta/resources/security-enums.md
> +title: "Enum values"
Per the guidance for enums in subnamespaces, please change the file name to enums-security.md.

2022-06-11 00:27 UTC, Lauragra commented on api-reference/beta/resources/security-enums.md
> +
Please add the following annotation to the end of the enums topic:

<!--
{
  "type": "#page.annotation",
  "namespace": "microsoft.graph.security"
}
-->

2022-06-11 00:29 UTC, Lauragra commented on api-reference/beta/resources/security-enums.md
> +# Enum values for Microsoft Graph M365 Records management
Let's make this title more generic and follow the pattern for the other subnamespaces - "Security enum values".

2022-06-11 00:46 UTC, Lauragra commented on api-reference/beta/resources/security-dispositionreviewstage.md
> +|stageNumber|Int32|Execution sequence number for each stage|
Please replace the word "Execution". It might be clear enough to just use this for the description: "The sequence number for each stage of the disposition review."

2022-06-11 00:55 UTC, Lauragra commented on api-reference/beta/resources/security-recordsManagement-overview.md
> +# Use the Microsoft Graph Records Management API
Please lowercase Records Management here.

2022-06-11 00:56 UTC, Lauragra commented on api-reference/beta/resources/security-recordsManagement-overview.md
> +description: "The Microsoft 365 subject rights request API provides functionality for organizations to automate repetitive tasks and integrate with their existing subject rights request tools to buil
Please update this description to accurately reflect the content.

2022-06-11 01:00 UTC, Lauragra commented on api-reference/beta/resources/security-recordsManagement-overview.md
> +The Microsoft Graph APIs for records management provide functionality to automate repetitive tasks and help customers to run operations on record management solution entities in Microsoft 365 Complia
This is a bit of a run-on sentence. I suggest we make it two separate sentences:

The Microsoft Graph APIs for records management enable the automation of repetitive tasks to help organizations meet industry regulations more efficiently. Use these APIs to help your customers run record management solutions on their data in Microsoft 365.

It's not clear to me how the Microsoft 365 Compliance Center is related, so please update the suggested text as needed.

2022-06-11 01:01 UTC, Lauragra commented on api-reference/beta/resources/security-retentionduration.md
> +description: "Represents how long content will be retained before it can be deleted"
Please add a period at the end of the description.

2022-06-11 01:01 UTC, Lauragra commented on api-reference/beta/resources/security-retentionduration.md
> +Represents how long a item will be retained before it can be deleted. This is an abstract type.
For correct grammar, change "a item" to "an item"

2022-06-11 01:04 UTC, Lauragra commented on api-reference/beta/resources/security-retentionduration.md
> +[retentionDurationForever](../resources/security-retentiondurationforever.md) and [retnetionDurationInDays](../resources/security-retentiondurationindays.md) are the two resourceTypes that inherit fr
Suggested revision:
The **retentionDuration** resource is the base type for the [retentionDurationForever](../resources/security-retentiondurationforever.md) and [retnetionDurationInDays](../resources/security-retentiondurationindays.md) resource types.

2022-06-11 02:05 UTC, Lauragra commented on api-reference/beta/resources/security-retentiondurationforever.md
> +|Property|Type|Description|
remove the table header when there are no properties to list.

2022-06-11 02:06 UTC, Lauragra commented on api-reference/beta/resources/security-retentiondurationforever.md
> +Represents that content will be retained permanentlyand not be allowed to be deleted.
It would be more clear to revise this to say: "Indicates that content will be retained permanently and will not be deleted." Also note the missing space between permanently and and.

2022-06-11 02:08 UTC, Lauragra commented on api-reference/beta/resources/security-retentiondurationindays.md
> +|days|Int32|Specifies the time period in days for a retention label.|
It's not entirely clear how a retention label is related to the retention duration. Would this revision be accurate?
Specifies the time period in days for which a retention label is applied to a content item.

2022-06-11 02:14 UTC, Lauragra commented on api-reference/beta/resources/security-retentionlabel.md
> +Represents how customers can manage their data, whether and for how long to retain or delete it.
Would it be more clear to revise this as follows:
Represents whether and for how long customers retain data.

2022-06-11 02:15 UTC, Lauragra commented on api-reference/beta/resources/security-retentionlabel.md
> +|actionAfterRetentionPeriod|actionAfterRetentionPeriod| Specifies the action to be applied on a document with this label after the retention period. The possible values are: `none`, `delete`, `startD
Please apply the comments I made on the CREATE operation topic to the descriptions here as well.

2022-06-11 02:16 UTC, Lauragra commented on api-reference/beta/resources/security-recordsManagement-overview.md
> +title: "Use the Microsoft Graph Records Management API"
Please make the file name all lowercase.

2022-06-11 02:20 UTC, Lauragra commented on api-reference/beta/resources/security-retentionevent.md
> +|[Add retentionEventType](../api/security-retentioneventtype-post.md)|[microsoft.graph.security.retentionEventType](../resources/security-retentioneventtype.md)|Add eventType by adding the relevant o
In the file we refer to this as Create, not Add; please make sure that they're consistent.

2022-06-11 02:23 UTC, Lauragra commented on api-reference/beta/resources/security-retentionevent.md
> +|[Delete retentionEvent](../api/security-retentionevent-delete.md)|None|Deletes a [retentionEvent](../resources/security-retentionevent.md) object.|
Please make sure that the descriptions for these methods match the descriptions in the method topic. For example, here you'll want to change Deletes to Delete. The descriptions for the following two methods don't match the descriptions in the topics.

2022-06-11 02:24 UTC, Lauragra commented on api-reference/beta/resources/security-retentionevent.md
> +|createdBy|[microsoft.graph.identitySet](/graph/api/resources/identityset)|The user who created the entity.|
Please reference my comments on the CREATE operation topic and provide the same updates here.

2022-06-11 02:26 UTC, Lauragra commented on api-reference/beta/resources/security-retentioneventstatus.md
> +For event-based retention, this attribute provides the status of event propogation to the targetted locations after the event has been created.
Suggested revision:
For event-based retention, provides the status of the propagation of the event to the specified locations after the event has been created.

2022-06-11 02:27 UTC, Lauragra commented on api-reference/beta/resources/security-retentioneventstatus.md
> +|status|eventStatusType|The Status of the distribution. The possible values are: `pending`, `error`, `success`, `notAvaliable`.|
Please lowercase Status.

2022-06-11 02:28 UTC, Lauragra commented on api-reference/beta/resources/security-retentioneventtype.md
> +|[Delete retentionEventType](../api/security-retentioneventtype-delete.md)|None|Deletes a [retentionEventType](../resources/security-retentioneventtype.md) object.|
Change Deletes to Delete.

2022-06-11 02:29 UTC, Lauragra commented on concepts/compliance-concept-overview.md
> +## Records Management (Preview)
Change to "Records management (preview)".

2022-06-11 02:32 UTC, Lauragra commented on concepts/compliance-concept-overview.md
> +The records management solution is used by organization in large volumes to utilize its various capabilities in pretecting, labelling, retatining or deleting their data. The Microsoft Graph APIs for
Revise as:
The records management solution is used by organizations in large volumes to protect, label, retain, or delete their data. The Microsoft Graph APIs for records management allow organizations to manage labels and label-associated functionalities more efficiently, automate the repetitive tasks, and equip customers with flexible options.

2022-06-11 02:36 UTC, opbld33 commented
Docs Build status updates of commit _[6550c18](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6550c18d312b6b498c8d32e1d8201c03e7007068)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-enums?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-11 02:40 UTC, Lauragra commented on api-reference/beta/resources/security-recordsManagement-overview.md
> +| Label | [microsoft.graph.security-retentionlabel](security-retentionlabel.md) | Contains retention settings and action at the end of a period that be applied to an individual item. |
Where there are hyphens (-) in the Type column, they should be periods.

2022-06-11 02:47 UTC, Lauragra commented on api-reference/beta/toc.yml
> +      - name: Records Management (preview)
Please use sentence case, so make management lowercase.

2022-06-11 02:47 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Event Types
Lowercase Types here.

2022-06-13 23:40 UTC, sseth-msft commented on api-reference/beta/api/security-retentionevent-delete.md
> +Deletes a [retentionEvent](../resources/security-retentionevent.md) object.
done

2022-06-15 20:47 UTC, sseth-msft commented on api-reference/beta/resources/security-eventpropagationresult.md
> +|status|eventPropagationStatus|Is the event completed. The possible values are: `none`, `inProcessing`, `failed`, `success`.|
the order is as per priority/importance of property to the customer, alphabetically might not be the best for the properties they need most times. I feel it should remain this for the same reason, thoughts?  @Lauragra

2022-06-15 22:25 UTC, sseth-msft commented on api-reference/beta/api/security-retentioneventtype-post.md
> +|createdBy|[microsoft.graph.identitySet](/graph/api/resources/identityset)|The user who created the entity. Optional.|
removed createdBy since it cannot be specified during a post operation @Lauragra , is that okay?

2022-06-15 22:41 UTC, sseth-msft commented on api-reference/beta/api/security-retentionlabel-post.md
> +|createdBy|[microsoft.graph.identitySet](/graph/api/resources/identityset)|Represents the user who created the entity.|
removed created in post , @Lauragra is that okay?

2022-06-15 23:11 UTC, sseth-msft commented on api-reference/beta/resources/security-dispositionreviewstage.md
> +|[Create dispositionReviewStage](../api/security-retentionlabel-post.md)|[microsoft.graph.security.dispositionReviewStage](../resources/security-dispositionreviewstage.md)|Create a new [dispositionRe
As of now, disposition review entity can only be created and updated through retention labels and its endpoints. Please confirm if I can resolve @Lauragra

2022-06-15 23:27 UTC, sseth-msft commented on api-reference/beta/resources/security-recordsManagement-overview.md
> +# Use the Microsoft Graph Records Management API
it is similar to SharePoint Online or Exchange Online, hence needs to be capitalized @Lauragra , please confirms so I can resolve

2022-06-16 00:00 UTC, sseth-msft commented on api-reference/beta/resources/security-retentionlabel.md
> +Represents how customers can manage their data, whether and for how long to retain or delete it.
there is more to a retention label than just retaining, it could also be deleting at the end. Additionally, the content could have different restrictions based on the type of retention label. Please confirm if it can be resolved @Lauragra

2022-06-16 00:05 UTC, sseth-msft commented on concepts/compliance-concept-overview.md
> +## Records Management (Preview)
Records Management is similar to SharePoint Online, a product. @Lauragra , confirm to resolve

2022-06-16 00:36 UTC, sseth-msft commented on api-reference/beta/resources/security-recordsManagement-overview.md
> +| Label | [microsoft.graph.security-retentionlabel](security-retentionlabel.md) | Contains retention settings and action at the end of a period that be applied to an individual item. |
done

2022-06-16 00:53 UTC, opbld34 commented
Docs Build status updates of commit _[ad9e4d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad9e4d42c83059abf1de8c6d9c4a61c40575928b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-16 01:50 UTC, opbld32 commented
Docs Build status updates of commit _[8929934](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89299346b1ce78c12f22c18bfd1e37fa57c5e218)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-16 16:15 UTC, isvargasmsft commented on api-reference/beta/api/security-retentionlabel-post.md
> +|actionAfterRetentionPeriod|actionAfterRetentionPeriod| Specifies the action to take on a document with this label applied during the retention period. The possible values are: `none`, `delete`, `sta
Please remember to add the subnamespace to the enum name when referring to it in the docs. 
```suggestion
|actionAfterRetentionPeriod|security.actionAfterRetentionPeriod| Specifies the action to take on a document with this label applied during the retention period. The possible values are: `none`, `delete`, `startDispositionReview`, `unknownFutureValue`. |
```

2022-06-16 16:28 UTC, Danielabom commented on api-reference/beta/api/security-retentionlabel-post.md
> +|retentionTrigger|retentionTrigger|Specifies whether the retention duration is calculated from the content creation date, labeled date, or last modification date. The possible values are: `dateLabele
Please review the enums. If they belong to a subnamespace, you must add the subnamespace to the enum name when referring to it in the docs.
```suggestion
|retentionTrigger|security.retentionTrigger|Specifies whether the retention duration is calculated from the content creation date, labeled date, or last modification date. The possible values are: `dateLabeled`, `dateCreated`, `dateModified`, `dateOfEvent`, `unknownFutureValue`. |
```

2022-06-16 16:32 UTC, Danielabom commented on api-reference/beta/resources/security-eventqueries.md
> +|queryType|queryType|Represents the type of query associated with an event. 'files' for SPO and ODB and 'messages' for EXO.The possible values are: `files`, `messages`, `unknownFutureValue`.|
Please review the enums. If they belong to a subnamespace, you must add the subnamespace to the enum name when referring to it in the docs.
```suggestion
|queryType|security.queryType|Represents the type of query associated with an event. 'files' for SPO and ODB and 'messages' for EXO. The possible values are: `files`, `messages`, `unknownFutureValue`.|
```

2022-06-16 16:33 UTC, Lauragra commented on concepts/compliance-concept-overview.md
> +### Overview
Please remove this Overview H3 heading.

2022-06-16 17:31 UTC, opbld33 commented
Docs Build status updates of commit _[c1c7ab2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1c7ab294b02c4e7fc5421182cf2e72d2e6aadf0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-16 17:34 UTC, Lauragra commented on api-reference/beta/resources/security-eventpropagationresult.md
> +|status|eventPropagationStatus|Indicates the status of the event creation request. The possible values are: `none`, `inProcessing`, `failed`, `success`.|
Global: For all properties that are of type enum, the enum should be listed as microsoft.graph.security.<enumName>. For details, see: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211748/Enums-in-subnamespaces?anchor=examples

2022-06-16 17:35 UTC, opbld34 commented
Docs Build status updates of commit _[7fdfec6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7fdfec6aec5ad7ccadd1f614a024813b8ca6337f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-16 22:29 UTC, opbld31 commented
Docs Build status updates of commit _[614c0aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/614c0aa1fdc6f891ab42437eec902c5a37b433c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-18 00:57 UTC, opbld30 commented
Docs Build status updates of commit _[5a79389](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a79389073d0664e249dcb75eb3a7cc51e251f07)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-18 00:59 UTC, opbld34 commented
Docs Build status updates of commit _[e8c1462](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8c14626754f626d00ec39119cc25fb044ac3159)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-18 01:02 UTC, Lauragra commented on api-reference/beta/resources/security-dispositionreviewstage.md
> +|[Create dispositionReviewStage](../api/security-retentionlabel-post.md)|[microsoft.graph.security.dispositionReviewStage](../resources/security-dispositionreviewstage.md)|Create a new [dispositionRe
You'll need to update these to be Create and Update retentionLabel, and update the descriptions accordingly.

2022-06-18 01:02 UTC, opbld30 commented
Docs Build status updates of commit _[c725169](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c725169721317bf61db893d77763d5620c71dadf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsManagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsManagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-18 01:05 UTC, opbld30 commented
Docs Build status updates of commit _[188d62b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/188d62be5428d0fe2248662ff6df7e07d45c2e7d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-18 01:10 UTC, opbld32 commented
Docs Build status updates of commit _[f8b95e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8b95e670a2e7245208a091a976f28fdff22a6a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-18 01:13 UTC, opbld34 commented
Docs Build status updates of commit _[2f3af47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2f3af475191705ce6a4bfaa83700a22040778bf0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-18 01:15 UTC, opbld32 commented
Docs Build status updates of commit _[2056488](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2056488fd288e84ab2734c81a3d28248258c85aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-20 19:56 UTC, Lauragra commented on api-reference/beta/resources/security-retentionlabel.md
> +Represents how customers can manage their data, whether and for how long to retain or delete it.
Perhaps this is what you mean:
Represents how customers can manage their data, including whether and for how long to retain or delete it.

2022-06-20 19:57 UTC, Lauragra commented on api-reference/beta/toc.yml
> +      - name: Records Management (preview)
Per discussion, this should be a common noun unless specifically in the context of Microsoft Purview Records Management. We don't expose product names in the TOC, so we should treat this as Records management, common noun.

2022-06-20 20:16 UTC, Lauragra commented on api-reference/beta/resources/security-retentioneventtype.md
> +When a retention event is created, it is associated with a specific event type which in turn is associated with a retention label. When a retention event is created, only content with that retention
Suggested revision for this description - note that we generally begin the summary description for a resource type with a third-person verb:
Represents a single group for the same type of retention events.

When a [retention event](../resources/security-retentionevent.md) is created, it is associated with a specific event type, which in turn is associated with a [retention label](../resources/security-retentionlabel.md). Only content with that retention label applied will be retained for the specified retention period.

2022-06-20 20:27 UTC, opbld30 commented
Docs Build status updates of commit _[76771c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/76771c52f16c777cac9809dd57f9ec1cb9d51722)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-20 22:58 UTC, opbld32 commented
Docs Build status updates of commit _[1ed0e22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ed0e22a81196f21d606d75cb4569a6e7623fb26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-20 23:37 UTC, opbld33 commented
Docs Build status updates of commit _[27fa9c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27fa9c86f81a85e0e9bef8c0d5ccc184c3baab27)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-recordsmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-recordsmanagement-overview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta&branch=pr-en-us- [...]

2022-06-20 23:39 UTC, Lauragra commented on api-reference/beta/resources/security-dispositionreviewstage.md
> +|[Create retentionLabel](../api/security-retentionlabel-post.md)|[microsoft.graph.security.retentionLabel](../resources/security-retentionlabel.md)|When creating a new [retentionLabel](../resources/s
Please use the descriptions for the methods that appear in the method topic, for clarity/consistency. This information about the dispositionReviewStage is not clearly explained in the method topic. Please explain there. Users can then get to that information by following the link to the method topic.

2022-06-24 04:51 UTC, opbld31 commented
Docs Build status updates of commit _[b08f114](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b08f11464b26adf0d6f48f8bbb15c32d1283004b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsmanagement-overview.md](https://github.co [...]

2022-06-24 04:59 UTC, opbld31 commented
Docs Build status updates of commit _[e104a2e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e104a2e586d00d0ec864c59756b77653293e7632)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsmanagement-overview.md](https://github.co [...]

2022-06-24 05:01 UTC, opbld34 commented
Docs Build status updates of commit _[0a5e9d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a5e9d6a17c3235190c26c1c72ab3533c8c9d889)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsmanagement-overview.md](https://github.co [...]

2022-06-24 05:03 UTC, opbld30 commented
Docs Build status updates of commit _[b5c6fe0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5c6fe04fef424d3da3028de617e888e87d3d279)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsmanagement-overview.md](https://github.co [...]

2022-06-24 05:06 UTC, opbld33 commented
Docs Build status updates of commit _[42cf8f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42cf8f4bcf4fb86f4798541142387291ac2eb83c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsmanagement-overview.md](https://github.co [...]

2022-06-24 05:07 UTC, merged

2022-06-24 05:08 UTC, opbld30 commented
Docs Build status updates of commit _[f509a7e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f509a7ed445a6b55c1856b1c284547a1532e08af)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/security-retentionevent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionevent-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentioneventtype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentioneventtype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentioneventtype-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-delete?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-get?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-list?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-post?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/api/security-retentionlabel-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/complianceapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/complianceapioverview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/enums-security.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/enums-security.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-security?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-dispositionreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-dispositionreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-dispositionreviewstage?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventpropagationresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-eventpropagationresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventpropagationresult?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-eventqueries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-10-16-sseth-M365-RecordsManagement/api-reference/beta/resources/security-eventqueries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-eventqueries?view=graph-rest-beta&branch=pr-en-us-14805) (graph-rest-beta) |
[api-reference/beta/resources/security-recordsmanagement-overview.md](https://github.co [...]

2022-07-13 03:54 UTC, angelgolfer-ms commented on api-reference/beta/resources/enums-security.md
> +doc_type: enumTypes
Line 7:
Post-publishing comment, in case anyone wonders in the future - the doc_type value should be enumPageType, not enumTypes.

@sseth-msft , do you recall if this line was generated with the value enumTypes?

CC @Lauragra to follow up if this is a Graph Studio generation bug.