[Cloud PC] Update description for Cloud PCs service plans
microsoftgraph/microsoft-graph-docs pull request #14808
Opened 2021-11-02 07:29 UTC by RuiHou105

2021-11-02 07:31 UTC, opbld34 commented
Docs Build status updates of commit _[be4b8df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be4b8df9549e0b3bb02d4f06a046749a2daaf9a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-serviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/updateServicePlans/api-reference/beta/api/virtualendpoint-list-serviceplans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-serviceplans?view=graph-rest-beta&branch=pr-en-us-14808) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/updateServicePlans/api-reference/beta/resources/cloudpcserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcserviceplan?view=graph-rest-beta&branch=pr-en-us-14808) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111020729475173-14808%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-03T07%3A31%3A42Z&sr=b&sp=r&sig=yZsIN7UGhtu0ncciiGp7CFNg%2B9Mw%2FSTNlVRIrdYjOBE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-02 07:32 UTC, RuiHou105 commented
**Roadmap workitem:**

Feature 11533: [Devices and apps][Cloud PC] Update description for Cloud PCs service plans

2021-11-11 03:18 UTC, AshleyYangSZ approved these changes

2021-11-12 15:50 UTC, isvargasmsft approved these changes

2021-11-16 09:10 UTC, opbld33 commented
Docs Build status updates of commit _[73f142f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73f142fa7c96efc7a6414714f747396dd38f5cd5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-serviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/updateServicePlans/api-reference/beta/api/virtualendpoint-list-serviceplans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-serviceplans?view=graph-rest-beta&branch=pr-en-us-14808) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/updateServicePlans/api-reference/beta/resources/cloudpcserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcserviceplan?view=graph-rest-beta&branch=pr-en-us-14808) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111160908392109-14808%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-17T09%3A10%3A16Z&sr=b&sp=r&sig=2TWjgVN9%2Fw1rh9G3nkRn1O3QeVfRNC7SzNC%2BtSdwJ7o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-16 09:10 UTC, angelgolfer-ms approved these changes
Hi @RuiHou105 , thanks for following up on these topics. I made some minor grammar fixes. Please take a look and let me know if you see any problems. Otherwise the PR is good to publish.

2021-11-16 09:13 UTC, opbld31 commented
Docs Build status updates of commit _[12e1f0b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12e1f0bfb0144607d25af50ea51e57ff97868620)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-serviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/updateServicePlans/api-reference/beta/api/virtualendpoint-list-serviceplans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-serviceplans?view=graph-rest-beta&branch=pr-en-us-14808) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/updateServicePlans/api-reference/beta/resources/cloudpcserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcserviceplan?view=graph-rest-beta&branch=pr-en-us-14808) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111160911049178-14808%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-17T09%3A13%3A33Z&sr=b&sp=r&sig=%2Fa3kz0M1eTw32wVRfqX7IbJMy%2FtoILeRYNI493jpKuQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-16 09:48 UTC, angelgolfer-ms commented on api-reference/beta/api/virtualendpoint-list-serviceplans.md
On second thought, @RuiHou105 , when you say "currently available service plans", do you actually mean the plans listed on the marketing page?
I think letting customers see what an actual service plan is like helps make this API clearer.
Can you add the sentence that I suggested in our earlier email thread, in a separate paragraph after line 16:

"For examples of currently available service plans, see [Windows 365 compare plans and pricing](https://www.microsoft.com/en-us/windows-365/business/compare-plans-pricing). Currently, Microsoft Graph API is available for Windows 365 Enterprise."

Remember to update this paragraph when Windows 365 Business support the Microsoft Graph API as well.

2021-11-16 09:54 UTC, angelgolfer-ms requested changes
@RuiHou105 , I suggest adding a link to the page that currently lists service plans, to help customers understand what a service plan for a Cloud PC is like, since virtual PCs is a relatively new service for some customers.

2021-11-16 09:54 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpcserviceplan.md
@RuiHou105 , I suggest to add the similar info about service plans to this topic as well. I found looking at info for a service plan helpful to understand this API.
So, after line 17, can you add a new paragraph:

"For examples of currently available service plans, see [Windows 365 compare plans and pricing](https://www.microsoft.com/en-us/windows-365/business/compare-plans-pricing). Currently, Microsoft Graph API is available for Windows 365 Enterprise."

2021-11-17 03:12 UTC, RuiHou105 commented on api-reference/beta/api/virtualendpoint-list-serviceplans.md
Hi @angelgolfer-ms , yes the "currently available service plans" means the plans that are listed on the page and the tenant can buy for Cloud PCs.

I've added the sentence. Could you please help check whether the URL is correct? Thanks.

2021-11-17 03:14 UTC, opbld32 commented
Docs Build status updates of commit _[888976e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/888976e7ed518eecb9c79c7783d6206c60f8c4ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-serviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/updateServicePlans/api-reference/beta/api/virtualendpoint-list-serviceplans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-serviceplans?view=graph-rest-beta&branch=pr-en-us-14808) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/updateServicePlans/api-reference/beta/resources/cloudpcserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcserviceplan?view=graph-rest-beta&branch=pr-en-us-14808) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111170312176699-14808%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T03%3A14%3A25Z&sr=b&sp=r&sig=jy5z2mgb6oOMZYReCn5ZIJnRx1IN%2Fz6PPy4bZfVWnko%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 06:25 UTC, opbld33 commented
Docs Build status updates of commit _[6e99b27](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e99b277e25aebcfaf61c19d8ddd9188ff8f5d4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-serviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/updateServicePlans/api-reference/beta/api/virtualendpoint-list-serviceplans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-serviceplans?view=graph-rest-beta&branch=pr-en-us-14808) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/updateServicePlans/api-reference/beta/resources/cloudpcserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcserviceplan?view=graph-rest-beta&branch=pr-en-us-14808) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111180623241440-14808%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-19T06%3A25%3A46Z&sr=b&sp=r&sig=hbS%2F4lIXfHKcsmo%2BXIEcHw%2BBe7UJQAKYh4DvGkhWqLI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 06:28 UTC, angelgolfer-ms commented on api-reference/beta/api/virtualendpoint-list-serviceplans.md
Thanks!
FYI I removed the language tag (en-us) segment in the HTTP link to the marketing site, for localization reasons. Please see this [topic](https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master#locale-codes-in-external-links).

2021-11-18 06:32 UTC, opbld32 commented
Docs Build status updates of commit _[2b20833](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b208332db6ea1508cf912393dfaf565827603ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-serviceplans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/updateServicePlans/api-reference/beta/api/virtualendpoint-list-serviceplans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-serviceplans?view=graph-rest-beta&branch=pr-en-us-14808) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/updateServicePlans/api-reference/beta/resources/cloudpcserviceplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcserviceplan?view=graph-rest-beta&branch=pr-en-us-14808) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111180630016441-14808%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-19T06%3A32%3A02Z&sr=b&sp=r&sig=BNA0SO%2Bjp7Vwwpc67pkc5ocZcbfkfWnB7ezFpG246IA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 08:33 UTC, merged