Add information for Go preview SDK
microsoftgraph/microsoft-graph-docs pull request #14828
Opened 2021-11-03 20:18 UTC by jasonjoh

Also removed references to deprecated .NET auth library

Fixes #14719 
Fixes #14579 
Fixes #14469 
Fixes #14401 
Fixes #14252 
Fixes #13707
Fixes #11456 
Fixes #10497 
Fixes #10464 
Fixes #9602

2021-11-03 20:20 UTC, opbld31 commented
Docs Build status updates of commit _[72f132a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/72f132a060f87a999df1b143f0b8f93942f8205f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/choose-authentication-providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-14828) |
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-14828) |
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/customize-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-14828) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-14828) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-14828) |
[concepts/sdks/use-beta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/use-beta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/use-beta?branch=pr-en-us-14828) |
[includes/go-sdk-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/includes/go-sdk-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-14828) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111032018462489-14828%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-04T20%3A20%3A50Z&sr=b&sp=r&sig=q3ZNSBdLu5fBRTLNofSRxYeCpUo5xIBCl24EsV%2FHvQ4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-03 20:28 UTC, opbld32 commented
Docs Build status updates of commit _[e48f621](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e48f6217c024632fd9c5ff076c09243517f8a752)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/choose-authentication-providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-14828) |
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-14828) |
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/customize-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-14828) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-14828) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-14828) |
[concepts/sdks/use-beta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/use-beta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/use-beta?branch=pr-en-us-14828) |
[includes/go-sdk-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/includes/go-sdk-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-14828) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111032025540878-14828%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-04T20%3A28%3A32Z&sr=b&sp=r&sig=nyXP5Mzy93Ebwq1s7mLVjNDFhsR%2B9UBYBKqc4AMzujk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-04 12:13 UTC, baywet requested changes
thanks a lot for taking this on, a few minor things.

2021-11-04 12:13 UTC, baywet commented on concepts/sdks/create-client.md
> +/var scopes = new[] { "User.Read" };
```suggestion
var scopes = new[] { "User.Read" };
```

2021-11-04 12:13 UTC, baywet commented on concepts/sdks/sdk-installation.md
> +go get github.com/microsoftgraph/msgraph-sdk-go
```suggestion
go get -u github.com/microsoftgraph/msgraph-sdk-go
```

2021-11-05 18:57 UTC, opbld33 commented
Docs Build status updates of commit _[fdd1e97](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fdd1e9799cc442c23094e6d7c739bb6b0849516a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/choose-authentication-providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-14828) |
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-14828) |
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/customize-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-14828) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-14828) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-14828) |
[concepts/sdks/use-beta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/use-beta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/use-beta?branch=pr-en-us-14828) |
[includes/go-sdk-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/includes/go-sdk-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-14828) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111051855533193-14828%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-06T18%3A57%3A34Z&sr=b&sp=r&sig=KW%2FqkYN3bF64avMHPH4KvBvvbLXUFgcyYD1LasbFUzw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-05 19:00 UTC, opbld33 commented
Docs Build status updates of commit _[e383184](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3831848fa0ee62290ce8a82c2ce37e0c6f98335)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/choose-authentication-providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-14828) |
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-14828) |
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/customize-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-14828) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-14828) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-14828) |
[concepts/sdks/use-beta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/use-beta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/use-beta?branch=pr-en-us-14828) |
[includes/go-sdk-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/includes/go-sdk-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-14828) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111051855584819-14828%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-06T19%3A00%3A04Z&sr=b&sp=r&sig=XfQe6N8jGjU2wvj9wX9R9j%2F%2FWJC9TW6z%2F6Jxbnz8hjI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-09 17:12 UTC, baywet approved these changes

2021-11-09 19:08 UTC, opbld34 commented
Docs Build status updates of commit _[5063964](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50639648d4566e8e1d44dcb2c07f401c5ca9c7b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/choose-authentication-providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-14828) |
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-14828) |
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/customize-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-14828) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-14828) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-14828) |
[concepts/sdks/use-beta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/use-beta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/use-beta?branch=pr-en-us-14828) |
[includes/go-sdk-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/includes/go-sdk-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-14828) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111091907097535-14828%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-10T19%3A08%3A44Z&sr=b&sp=r&sig=WETi2Qk4N4YnROlCfN9Gi1FCgv2LC6ZFw4kFRyFmwek%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-11 05:07 UTC, opbld30 commented
Docs Build status updates of commit _[5d5dea9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d5dea95b0e2b613f7734f1138138f4b406df89c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/choose-authentication-providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-14828) |
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-14828) |
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/customize-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-14828) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-14828) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-14828) |
[concepts/sdks/use-beta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/use-beta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/use-beta?branch=pr-en-us-14828) |
[includes/go-sdk-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/includes/go-sdk-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-14828) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111110505219712-14828%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T05%3A07%3A01Z&sr=b&sp=r&sig=2C1ZwiRfFLVKjFukhPSaQzf5yvtrwjMFQhhjKazEPdA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-11 05:07 UTC, Lauragra approved these changes

2021-11-11 12:10 UTC, baywet approved these changes

2021-11-12 20:43 UTC, opbld31 commented
Docs Build status updates of commit _[f5d7345](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5d734587674e95c2a4cb07ce0db39c04c536470)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/choose-authentication-providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-14828) |
[concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/create-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-client?branch=pr-en-us-14828) |
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/customize-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-14828) |
[concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/sdk-installation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdk-installation?branch=pr-en-us-14828) |
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-14828) |
[concepts/sdks/use-beta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/use-beta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/use-beta?branch=pr-en-us-14828) |
[includes/go-sdk-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/includes/go-sdk-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?branch=pr-en-us-14828) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111122041233819-14828%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T20%3A43%3A00Z&sr=b&sp=r&sig=UYGrwQRFngPE%2FiULyKkGjz1jmqS1UpK5ERVKyxKx1vc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 22:57 UTC, merged