Added sourceImageNotGeneralized member to cloudPcDeviceImageStatusDetails
microsoftgraph/microsoft-graph-docs pull request #14836
Opened 2021-11-04 06:52 UTC by RuiHou105

**Roadmap workitem:** 

Feature 11550: [Devices and apps][Cloud PC] Add sourceImageNotGeneralized member to cloudPcDeviceImageStatusDetails

2021-11-04 06:53 UTC, opbld34 commented
Docs Build status updates of commit _[a565034](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a565034c475594787a5f6e24caf14cbc37048b53)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/api-reference/beta/resources/cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14836) (graph-rest-beta) | [Details](#user-content-47beb7c54cf5f18c080f8250b2ae0491-953ade15)
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="47beb7c54cf5f18c080f8250b2ae0491-953ade15"></a>
### [api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/api-reference/beta/resources/cloudpcdeviceimage.md)
 - **Line 59, Column 138**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/virtual-machines/generalize' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 59, Column 138**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/virtual-machines/generalize' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111040652169636-14836%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-05T06%3A53%3A54Z&sr=b&sp=r&sig=ejMqu127WKPWRBBi31Fnk5GUzpFMugw6nSEvJd5w7WE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-04 06:56 UTC, RuiHou105 commented
**Roadmap workitem:** 

Feature 11550: [Devices and apps][Cloud PC] Add sourceImageNotGeneralized member to cloudPcDeviceImageStatusDetails

2021-11-11 03:47 UTC, AshleyYangSZ commented
Could you help address the warning of the link?

2021-11-11 03:47 UTC, AshleyYangSZ approved these changes

2021-11-17 06:55 UTC, RuiHou105 commented
@JarbasHorst  could you please help review this PR?

2021-11-17 06:55 UTC, opbld30 commented
Docs Build status updates of commit _[856f0e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/856f0e56454e3846b4caf0b407be39aa7ecaa84a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/api-reference/beta/resources/cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14836) (graph-rest-beta) | [Details](#user-content-47beb7c54cf5f18c080f8250b2ae0491-629db513)
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="47beb7c54cf5f18c080f8250b2ae0491-629db513"></a>
### [api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/api-reference/beta/resources/cloudpcdeviceimage.md)
 - **Line 59, Column 138**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/virtual-machines/generalize' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 59, Column 138**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/virtual-machines/generalize' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111170653334726-14836%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T06%3A55%3A18Z&sr=b&sp=r&sig=8TKEUlNC3RHQ3quNG9xUzP4ualHAqRQF4xcmkNQOTPc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 07:21 UTC, opbld31 commented
Docs Build status updates of commit _[7db6b99](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7db6b99ca3b3b25f8a6a24321a8eef376678bb7f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14836) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111170719034531-14836%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T07%3A21%3A50Z&sr=b&sp=r&sig=kVbJXPKCCckvuyQgVKkoWqqnP4%2BqNfnRerL97UL%2FHz0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 07:35 UTC, opbld30 commented
Docs Build status updates of commit _[9531d19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9531d19828c8db27186f5c6136a478ade110fbd5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/api-reference/beta/resources/cloudpcdeviceimage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14836) (graph-rest-beta) | [Details](#user-content-47beb7c54cf5f18c080f8250b2ae0491-9499c89a)
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="47beb7c54cf5f18c080f8250b2ae0491-9499c89a"></a>
### [api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/api-reference/beta/resources/cloudpcdeviceimage.md)
 - **Line 59, Column 138**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/virtual-machines/generalize?view=graph-rest-beta&preserve-view=true' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111170734121642-14836%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T07%3A35%3A50Z&sr=b&sp=r&sig=XyRFRGU1VM0pwsODUJGnmS3OzzB%2F%2BLMWKmsWO32N754%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 08:24 UTC, opbld32 commented
Docs Build status updates of commit _[b2c91ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b2c91ee46475770c53a1d6dc4b6c7c0d16cc9fde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14836) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111170822480156-14836%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T08%3A24%3A29Z&sr=b&sp=r&sig=zl%2BhFK3juloxSntpHhamdUMlM197JCA3nK0yUJI%2FJww%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-19 20:49 UTC, JarbasHorst requested changes

2021-11-19 20:49 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +|sourceImageNotGeneralized|The uploaded image hasn’t been generalized. Re-upload the image after running the sysprep/generalize command. [Learn more](/azure/virtual-machines/generalize?view=graph-res
In general, don’t hyphenate words beginning with re- unless it’s necessary to avoid confusion. In this case, please replace "re-upload" with "reupload".

2021-11-19 20:49 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +|unknownFutureValue|Unknown future status details (Reserved, not used right now).|
For consistency and clarity, please use "Evolvable enumeration sentinel value. Do not use." as the description of the unknownFutureValue enum member.

2021-11-19 20:49 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +|sourceImageNotGeneralized|The uploaded image hasn’t been generalized. Re-upload the image after running the sysprep/generalize command. [Learn more](/azure/virtual-machines/generalize?view=graph-res
Please give some context before providing a link. Suggested revision:

To learn more, see \[Remove machine specific information by generalizing a VM before creating an image\](/azure/virtual-machines/generalize).

I checked the link and this part "?view=graph-rest-beta&preserve-view=true" isn't required.

2021-11-19 20:49 UTC, JarbasHorst commented on changelog/Microsoft.CloudManagedDesktop.json
> +                {
Since users cannot use "unknownFutureValue", I don't think this is relevant. Please, consider removing this changelog entry.

2021-11-22 06:09 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +|unknownFutureValue|Unknown future status details (Reserved, not used right now).|
@JarbasHorst  Updated. Please check when you got time. Thanks.

2021-11-22 06:13 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                {
Removed unused part.

2021-11-22 06:16 UTC, opbld30 commented
Docs Build status updates of commit _[5bb1b69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5bb1b69d97889e0e9c75adf8f0574c7df0c99bcd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14836) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111220614267554-14836%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-23T06%3A16%3A46Z&sr=b&sp=r&sig=8RiZcDPWkCu95hNpOhqdbpH2zlgUab%2FsyAqUsw8LWU4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-22 06:20 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +|sourceImageNotGeneralized|The uploaded image hasn’t been generalized. Re-upload the image after running the sysprep/generalize command. [Learn more](/azure/virtual-machines/generalize?view=graph-res
@JarbasHorst  Updated. But I have one question, actually I am not sure when we need to add "?view=graph-rest-beta&preserve-view=true" and when should not add this tag?

2021-11-22 22:15 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-11-23 18:26 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +|sourceImageNotGeneralized|The uploaded image hasn’t been generalized. Re-upload the image after running the sysprep/generalize command. [Learn more](/azure/virtual-machines/generalize?view=graph-res
Hi @RuiHou105, I will reply in Teams.

2021-12-02 03:27 UTC, opbld30 commented
Docs Build status updates of commit _[3ee6ec7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ee6ec740d08dee1c5b7e389fb1ec10e5160623d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14836) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addSourceImageNotGeneralized/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112020325446608-14836%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T03%3A27%3A29Z&sr=b&sp=r&sig=7LIoj6%2BXQsuhzuuce%2FPXuUiMkRtPq0cUsakNM6lx%2Bwk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 17:06 UTC, Lauragra approved these changes

2021-12-07 01:00 UTC, merged