Added new error types to cloudPcOnPremisesConnectionHealthCheckErrorType
microsoftgraph/microsoft-graph-docs pull request #14835
Opened 2021-11-04 06:26 UTC by RuiHou105

**Roadmap workitem:** 

Feature 11549: [Devices and apps][Cloud PC] Add new error types to cloudPcOnpremisesConnectionHealthCheckErrorType

2021-11-04 06:29 UTC, opbld34 commented
Docs Build status updates of commit _[62de647](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62de647181d13645ba319846a6e7ecdba6dcb7e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addErrorTypes/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-14835) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addErrorTypes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111040626531292-14835%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-05T06%3A29%3A17Z&sr=b&sp=r&sig=1xu7Ai%2FirkhMw%2B1tzhBiQutnYjKlGezK%2FthPjrEfe0o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-11 03:45 UTC, AshleyYangSZ approved these changes

2021-11-11 03:45 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|adJoinCheckAccountLockedOrDisabled|The active domain join check failed because the domain join user account is currently locked out or disabled. Please ensure the domain join user account is unlocke
Do you know the what's the meaning of 'active' here? I think the 'active' may be not needed.

2021-11-17 06:27 UTC, opbld30 commented
Docs Build status updates of commit _[978b5c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/978b5c2febca8ee5593693f51774dfee0376e6b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addErrorTypes/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-14835) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addErrorTypes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111170625113334-14835%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T06%3A27%3A24Z&sr=b&sp=r&sig=BzBRM1R1YfvhM%2FFXR%2FuV0AwVdUKf4kG52QRz%2BxQgyHU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 06:36 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|adJoinCheckAccountLockedOrDisabled|The active domain join check failed because the domain join user account is currently locked out or disabled. Please ensure the domain join user account is unlocke
@AshleyYangSZ  I have checked with developers. Actually the health check here is about "active directory domain join check".  Please refer to [this](https://publib.boulder.ibm.com/tividd/td/ITAME/GC32-0844-00/en_US/HTML/am39_install48.htm). 
So how about updating descriptions of all adJoinCheck..... to "The active directory domain join check failed......"?


![image](https://user-images.githubusercontent.com/77313233/142147121-38a5ab42-5067-4788-bf9b-24dd9145214a.png)

2021-11-17 06:43 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|adJoinCheckAccountLockedOrDisabled|The active domain join check failed because the domain join user account is currently locked out or disabled. Please ensure the domain join user account is unlocke
Updated description to "The domain join check failed..."

2021-11-17 06:43 UTC, RuiHou105 commented
@JarbasHorst  could you please help review it? Thanks!

2021-11-17 06:43 UTC, opbld34 commented
Docs Build status updates of commit _[06541bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06541bffd5bd45787851090c59f6bde5c1f77040)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addErrorTypes/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-14835) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addErrorTypes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111170641504373-14835%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T06%3A43%3A37Z&sr=b&sp=r&sig=5ZX3nWOy7G8ZGf3V7UQQXcxJDImAn61THItIClPHWl8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-19 20:03 UTC, JarbasHorst requested changes

2021-11-19 20:49 UTC, JarbasHorst requested changes

2021-11-19 20:49 UTC, JarbasHorst commented on changelog/Microsoft.CloudManagedDesktop.json
> +                {
Since users cannot use "unknownFutureValue", I don't think this is relevant. Please, consider removing this changelog entry.

2021-11-22 05:21 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|unknownFutureValue|Unknown future status (reserved, not used right now).|
Updated.

2021-11-22 05:27 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|adJoinCheckAccountQuotaExceeded|The domain join check failed because the domain join user has exceeded maximum domain joins. Please make sure the domain join is allowed and the ms-DS-MachineAccountQ
Updated. Please check.

2021-11-22 05:29 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckVNetInvalid|Selected Azure virtual network is invalid. Please make sure the virtual network is available and healthy. Alternatively, update this on-premises network connecti
@JarbasHorst  Comments resolved. Could you please take a second look when you got time? Thanks!

2021-11-22 05:47 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckResourceGroupInvalid|Selected Azure resource group is invalid or not found. Please make sure the selected Azure resource group is available to provision resources. Alternati
Updated.

2021-11-22 05:54 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckResourceGroupLockedForDelete|Selected resource group or its parent scope has been locked for delete action. It may use up the IP addresses. Please remove the lock and try ag
It describes the reason for this error. Do I need to rephrase the sentence like "... for delete actions. It may be because the IP addresses are used up....."?

2021-11-22 05:56 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckResourceGroupLockedForReadonly|Selected resource group is locked and cannot be modified for provisioning. Please remove this lock to ensure provisioning succeeds.|
Updated. Thanks!

2021-11-22 05:59 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckVNetBeingMoved|Selected Azure virtual network is being moved. Please ensure your virtual network is not changing or being moved and try again. Alternatively, update this on-
Updated.

2021-11-22 06:06 UTC, opbld32 commented
Docs Build status updates of commit _[61c2225](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61c222557e8ae8426366f6aa7c51945323f0a398)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addErrorTypes/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-14835) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addErrorTypes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111220604250539-14835%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-23T06%3A06%3A25Z&sr=b&sp=r&sig=b%2BpTiHt59lB2VGas%2FhlfDTjtyKD9ntmE69GVj9SkUbI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-22 06:26 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckSubnetDelegationFailed|Selected Azure virtual network has subnet delegation which is blocking the creation of Nic. Please ask your Azure virtual network owner to modify thei
Updated. Please check again. Thanks!

2021-11-22 06:27 UTC, opbld32 commented
Docs Build status updates of commit _[5a79dbf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a79dbf363d0032c4692c613e32aad6c07ed82e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addErrorTypes/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-14835) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addErrorTypes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111220625477783-14835%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-23T06%3A27%3A19Z&sr=b&sp=r&sig=afu3wdhZzcJNRUjN2y7fgzJHi1sAFkYvIBBSD%2BjWYc4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-23 20:14 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckResourceGroupLockedForReadonly|The selected resource group is locked and can't be modified for provisioning. Please remove this lock to allow provisioning to succeeds.|
Please, replace succeeds with succeed.

2021-11-23 20:14 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckResourceGroupLockedForDelete|Selected resource group or its parent scope has been locked for delete action. It may use up the IP addresses. Please remove the lock and try ag
Hi @RuiHou105, thanks for clarifying. In this case, I recommend you to replace the current sentence with your suggestion: "It may be because the IP addresses are used up".

2021-11-23 20:21 UTC, JarbasHorst requested changes

2021-11-23 20:21 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckSubnetDelegationFailed|The selected Azure virtual network has subnet delegation which blocks the creation of network interface (Nic). Please ask your Azure virtual network o
For clarity, please specify whether this is a (any) or the (a specific) network interface. For example, ...which blocks the creation of a network interface...

2021-11-24 07:33 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckResourceGroupLockedForDelete|Selected resource group or its parent scope has been locked for delete action. It may use up the IP addresses. Please remove the lock and try ag
@JarbasHorst  Thanks. Already updated.

2021-11-24 07:35 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckSubnetDelegationFailed|The selected Azure virtual network has subnet delegation which blocks the creation of network interface (Nic). Please ask your Azure virtual network o
Updated. Thanks.

2021-11-24 20:08 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-11-30 01:38 UTC, Lauragra approved these changes

2021-12-01 00:43 UTC, opbld30 commented
Docs Build status updates of commit _[aabeb5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aabeb5f8b763f0752b459b5516bf2ccf2621487d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addErrorTypes/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-14835) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addErrorTypes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112010041476671-14835%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T00%3A43%3A51Z&sr=b&sp=r&sig=xfBQaJzFSy2r4Pfc7hB64tFstsIwcC%2FTSOCk6CO0LXI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 00:45 UTC, merged