Add properties expirationDate & osStatus to cloudPcDeviceImage
microsoftgraph/microsoft-graph-docs pull request #14837
Opened 2021-11-04 07:23 UTC by RuiHou105

2021-11-04 07:25 UTC, opbld32 commented
Docs Build status updates of commit _[8c1e25f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c1e25f0f70d2d48a5a8fd6813cbe3a3cc60b793)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addPropertiesToDeviceImage/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14837) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addPropertiesToDeviceImage/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111040723090378-14837%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-05T07%3A25%3A26Z&sr=b&sp=r&sig=e5eOEXKfRBlpGcZqOei9jt52gaYq4dh0l9BCR3Ia9L8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-04 07:27 UTC, RuiHou105 commented
**Roadmap workitem:** 

Feature 11551: [Devices and apps][Cloud PC] Add properties expirationDate & osStatus to cloudPcDeviceImage

2021-11-11 03:48 UTC, AshleyYangSZ approved these changes

2021-11-17 07:00 UTC, opbld30 commented
Docs Build status updates of commit _[4d40a95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d40a95c3c24bd22cb8b6718d21bde44428ddc63)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addPropertiesToDeviceImage/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14837) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addPropertiesToDeviceImage/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111170659094578-14837%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T07%3A00%3A51Z&sr=b&sp=r&sig=%2BbnLu%2F%2BV44AiHX3tVr51kK3Ld4%2FHHixXC3CKpvojP%2F4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 07:01 UTC, RuiHou105 commented
Hi @JarbasHorst  Kindly review this PR. Thanks ahead!

2021-11-23 15:54 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +|osStatus|cloudPcDeviceImageOsStatus|The OS status of this image. Possible values are: `supported`, `supportedWithWarning`.|
Please order the properties table alphabetically.

2021-11-23 15:57 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +
Could you please document the new enum in the enums file?
Guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/174164/Evolvable-enumerations

2021-11-23 15:59 UTC, isvargasmsft requested changes
Hello Rui, 

Thank you very much for your work in this PR. 

Please add the new enum to the enums file accordingly. 

Kind regards, 

Isaac Vargas

2021-11-29 07:23 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +|osStatus|cloudPcDeviceImageOsStatus|The OS status of this image. Possible values are: `supported`, `supportedWithWarning`.|
@isvargasmsft  Updated. Please take a second look when you got time. Thanks!

2021-11-29 07:35 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +
Updated. Please check.

2021-11-29 07:39 UTC, opbld33 commented
Docs Build status updates of commit _[db900df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db900dff3e870de7369a7c588f0e143bfa964db8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addPropertiesToDeviceImage/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14837) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addPropertiesToDeviceImage/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111290737034085-14837%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-30T07%3A39%3A44Z&sr=b&sp=r&sig=GmyrRDRrwQqLs%2FPwQ39LmHqUsq28ETXruq5PScQ5Lqc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 14:59 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +
Why are we documenting these enums in this resource topic instead of the enums.md file? 

Is there a reason?

2021-12-01 15:00 UTC, isvargasmsft requested changes
Please clarify if there is a reason to document the enums in the resource topic instead of using the **resources/enums.md** file

2021-12-02 03:46 UTC, opbld31 commented
Docs Build status updates of commit _[49d6f8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49d6f8eccd4a977bb170661c3cddb3883645e4f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addPropertiesToDeviceImage/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14837) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addPropertiesToDeviceImage/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112020343408250-14837%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T03%3A45%3A59Z&sr=b&sp=r&sig=VYnwnMyp1ggrFS%2FhbY5nbaulScOLK51RYuTsX2dUxo4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 03:54 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +
@isvargasmsft  sorry I misunderstood your meaning in your last comment. Actually for all other enumerations of Cloud PC, we directly put them into the corresponding resource topic, not into the enum.md file. 

So  is "To put all enums into the enum.md file" a new graph docs convention?  Or we did wrong at the beginning? If so, maybe I need to put all Cloud PC related enums into enum.md file. 

@AshleyYangSZ , @Lauragra  Any thoughts? Thanks!

2021-12-06 09:33 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +
Hi @isvargasmsft , after reading this [wiki ](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations) about enumeration in public doc, I see there are three options to place the enum. Here I chose the second option which is customer-facing and I think it can give customers a straightforward understanding. How do you think?

![doc](https://user-images.githubusercontent.com/77313233/144822185-70053bc4-d5da-47b4-968a-94d8a37e9641.jpg)

2021-12-07 07:13 UTC, opbld31 commented
Docs Build status updates of commit _[6b556a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b556a6a557de6feb2ef7342d2547b3ca6415fcd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addPropertiesToDeviceImage/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14837) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addPropertiesToDeviceImage/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112070711553871-14837%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T07%3A13%3A46Z&sr=b&sp=r&sig=bUBNRRVdJMorqOTF2OsGoH9TLqrDoiqczw%2FAShY7Gb0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-08 18:15 UTC, isvargasmsft approved these changes

2021-12-14 03:18 UTC, RuiHou105 commented
Hi @Lauragra  This PR needs your final review. Thanks!

2021-12-14 03:19 UTC, opbld33 commented
Docs Build status updates of commit _[6bf75ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6bf75ad825867913867dfae8f7eb02f5e1a68c98)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addPropertiesToDeviceImage/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-14837) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addPropertiesToDeviceImage/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112140317242867-14837%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-14T03%3A19%3A32Z&sr=b&sp=r&sig=UWN4UPX6XmVThxnXijwSQHPiuUAOfr8NzFV%2F4dKK3DA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-14 07:11 UTC, JarbasHorst commented
@RuiHou105 the content review work is complete on this PR. When the updates in this PR are ready for external customers to use, please replace the **do not merge** label with **ready to merge**.

2021-12-16 22:50 UTC, isvargasmsft commented
@RuiHou105 whats the status of this PR? Is it ready to merge yet?

2021-12-17 03:07 UTC, RuiHou105 commented
Hi @JarbasHorst , @isvargasmsft , this PR is ready to merge and I've added the "Ready to merge" tag. Please help merge it. Thanks!

2021-12-18 00:07 UTC, merged