Add properties and new APIs to cloudPC entity
microsoftgraph/microsoft-graph-docs pull request #14840
Opened 2021-11-04 08:49 UTC by RuiHou105

2021-11-04 08:51 UTC, RuiHou105 commented
**Roadmap workitem:** 

Feature 11552: [Devices and apps][Cloud PC] Add properties and new APIs to cloudPC entity

2021-11-04 08:51 UTC, opbld31 commented
Docs Build status updates of commit _[83501c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83501c7726c88120938037ba71b3f29b58fd24bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcloginresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpcloginresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcloginresult?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111040849563023-14840%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-05T08%3A51%3A38Z&sr=b&sp=r&sig=pSpeRYivwLZvcXy%2Bfu3tKa0%2FrIv3ZtCZiKzGsIdYYfU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-11 03:52 UTC, AshleyYangSZ approved these changes

2021-11-17 07:11 UTC, opbld31 commented
Docs Build status updates of commit _[3a6e782](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a6e7828a12763ec9db0fb7c27256e8b8c4d2d9b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcloginresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpcloginresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcloginresult?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111170710043180-14840%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T07%3A11%3A43Z&sr=b&sp=r&sig=2LeJ02YyK%2Fy7TtrMltIhTIO8GO%2F10MaAyjH5iTfzxPA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 07:32 UTC, opbld31 commented
Docs Build status updates of commit _[b8c1f95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8c1f95ad86da02defa7e963afedc29256572a64)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcloginresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpcloginresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcloginresult?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111170730436210-14840%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T07%3A32%3A26Z&sr=b&sp=r&sig=dwVRS2w5C4M5eo2JtMiokWPDIzW3WF9M2MZWIxTTU9k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 07:35 UTC, RuiHou105 commented
@JarbasHorst  Hope you can help review this PR when you got time. Thanks!

2021-11-24 21:12 UTC, JarbasHorst requested changes

2021-11-24 21:12 UTC, JarbasHorst commented on api-reference/beta/api/cloudpc-reboot.md
> +description: "Reboot for a specific Cloud PC."
For clarity and simplicity, I recommend you to remove "for" from the sentence. An introductory sentence in an API topic should start with an imperative verb and shortly explain what you can do with the API. In this case, (You can) reboot a specific Cloud PC.

Please, apply this change also to line 16.

2021-11-24 21:12 UTC, JarbasHorst commented on api-reference/beta/api/cloudpc-rename.md
> +description: "Rename for a specific Cloud PC. Update the Cloud PC entity displayName."
For clarity and simplicity, I recommend you to remove "for" from the sentence.

Please, apply this change also to line 16.

2021-11-24 21:12 UTC, JarbasHorst commented on api-reference/beta/api/cloudpc-troubleshoot.md
> +description: "Troubleshoot for a specific Cloud PC. Check the Cloud PC and SessionHost health status."
For clarity and simplicity, I recommend you to remove "for" from the sentence.

Please, apply this change also to line 16.

2021-11-29 07:50 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-reboot.md
> +POST https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/cloudPCs/{cloudPCId}/reboot
Hi @JarbasHorst , do you mean to use a  real Cloud PC ID such as 831dd62e-cfa1-4d49-a3b4-58d4e9920f8e? But I suppose this POST request is as a URL link model so we'd better use a place holder? How do you think?

2021-11-29 07:52 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-rename.md
> +Rename for a specific Cloud PC. Update the Cloud PC entity displayName.
Updated. Thanks.

2021-11-29 07:54 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-rename.md
> +|displayName|String|The Cloud PC new display name.|
Updated.

2021-11-29 08:08 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-reboot.md
> +POST https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/cloudPCs/{cloudPCId}/reboot
After investigation, as this is the **API example**, so we can use a real Cloud PC ID in the request URL link. Thanks @JarbasHorst !

2021-11-29 08:20 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcloginresult.md
> +description: "The details of the Cloud PC login results."
Updated.

2021-11-29 08:22 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-reboot.md
> +description: "Reboot for a specific Cloud PC."
Updated.

2021-11-29 08:25 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcloginresult.md
> +  "time": "String (timestamp)",
Removed extra comma.

2021-11-29 08:29 UTC, opbld31 commented
Docs Build status updates of commit _[9f1d913](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f1d913ae0ca91930a55932ea1526796ade2efd0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcloginresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpcloginresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcloginresult?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111290827173619-14840%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-30T08%3A29%3A19Z&sr=b&sp=r&sig=5qWTVBHKSY9RqyVxJJXUSGN59nl3jatOR36ZKHPvzOc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 09:00 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
>  |id|String|Unique identifier for the Cloud PC. Read-only.|
Updated.

2021-11-29 09:01 UTC, opbld31 commented
Docs Build status updates of commit _[27a2b55](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27a2b55e80c84ada0ce8cec865d85189d2e11656)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcloginresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpcloginresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcloginresult?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111290900102514-14840%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-30T09%3A01%3A55Z&sr=b&sp=r&sig=cfqDYUQPcR0HlEO5pvkMeSuvSYyrYzEAdd9l0%2BnCY1A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 20:43 UTC, JarbasHorst commented on api-reference/beta/api/cloudpc-reboot.md
> +POST https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/cloudPCs/{cloudPCId}/reboot
Hi @RuiHou105,

as a person consuming this API topic, it would be very helpful to have a "real" (GUID shouldn't be a real one, just something similar) example, so I can quickly understand the request.

2021-11-29 21:14 UTC, JarbasHorst requested changes

2021-11-29 21:14 UTC, JarbasHorst commented on api-reference/beta/api/cloudpc-rename.md
> +description: "Rename a specific Cloud PC. Update the Cloud PC entity displayName."
For consistency with the description in line 16, I recommend you to replace this last sentence with: "Update the displayName for the Cloud PC entity."

2021-11-29 21:14 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpc.md
>  |[Reprovision cloudPC remote action](../api/manageddevice-reprovisioncloudpc.md)|None|Reprovision a Cloud PC with Intune managed device id.|
In regular text, please use ID as the abbreviation for identity. Suggested revision:

- ...managed device ID

2021-12-02 06:20 UTC, opbld32 commented
Docs Build status updates of commit _[5c8f3e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c8f3e92cf9866e54386259859354594cfa8efac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcloginresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpcloginresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcloginresult?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112020617361660-14840%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T06%3A20%3A04Z&sr=b&sp=r&sig=G8x6%2B%2FRK5wWW%2BKV0pymmhkltcVAo2RY4MTCxSZHhyds%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 06:22 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|lastRemoteActionResult|[cloudPcRemoteActionResult](../resources/cloudpcremoteactionresult.md)|The last remote action result of the Cloud PC. Now supported remote actions include: rename, reboot, rep
Added.

2021-12-02 06:30 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
>  |[Reprovision cloudPC remote action](../api/manageddevice-reprovisioncloudpc.md)|None|Reprovision a Cloud PC with Intune managed device id.|
Updated.

2021-12-02 06:34 UTC, opbld32 commented
Docs Build status updates of commit _[a13b158](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a13b1588170b886a873f876ba43dad09bd7aa591)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcloginresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpcloginresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcloginresult?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112020632084255-14840%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T06%3A34%3A00Z&sr=b&sp=r&sig=xcjGnkxX9ZXHnuCPN%2Bjul%2BtTwy1UJJQWrdpjnatcvVQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 21:09 UTC, JarbasHorst requested changes

2021-12-02 21:09 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpc.md
> +|lastRemoteActionResult|[cloudPcRemoteActionResult](../resources/cloudpcremoteactionresult.md)|The last remote action result of the Cloud PC. Now supported remote actions include: rename, reboot, rep
For clarity, I recommend you to be specific. In this case, you should replace include with are and provide the list of remote actions that are supported. If I understand it correctly, the property "lastRemoteActionResult" will have one of these values, right? For example, `"lastRemoteActionResult": "reboot"`. In this case, I recommend you to use backticks to highlight the remote actions supported. Suggested revision:

- The supported remote actions are: \`Rename\`, \`Reboot\`, \`Reprovision\`, and \`Troubleshoot\`.

Should `Resize` also be included in this list? Also, should the property actionName in the resize topic now contain also Rename, Reboot, and Troubleshoot? https://docs.microsoft.com/en-us/graph/api/resources/cloudpcremoteactionresult

2021-12-02 21:09 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpc.md
> +|onPremisesConnectionName|String|The on-premises connection that is applied during provisioning of Cloud PCs.|
Please, add "the" before provisioning. Please, apply this change also to line 50.

2021-12-03 20:51 UTC, JarbasHorst requested changes

2021-12-03 20:51 UTC, JarbasHorst commented on api-reference/beta/api/cloudpc-rename.md
> +Rename a specific Cloud PC. Update the **displayName** for the Cloud PC entity.
For clarity, please start the second sentence with "Use this API to...". Please, apply this change also to line 3. Suggested revision:

- Use this API to update the \*\*displayName\*\* for the Cloud PC entity.

2021-12-03 20:51 UTC, JarbasHorst commented on api-reference/beta/api/cloudpc-troubleshoot.md
> +Troubleshoot a specific Cloud PC. Check the Cloud PC and the Session Host health status.
For clarity, please start the second sentence with "Use this API to...". Should Session Host be really capitalized? I would revise the second sentence as:

- Use this API to check the health status of the Cloud PC and the session host.

Please, apply this change also to line 3.

2021-12-03 20:51 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpc.md
>  |Property|Type|Description|
GLOBAL: Please apply this change to all descriptions in this table that contain "Cloud PC's".

Please, in general we should avoid forming the possessive of something that isn't a person. In this case, please reconstruct the sentence to contain "of the Cloud PC" instead of "the Could PC's". For example, "The Azure Active Directory (Azure AD) device ID of the Cloud PC." or "The display name of the Cloud PC.".

2021-12-03 20:51 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpc.md
> +|[Rename](../api/cloudpc-rename.md)|None|Rename for a specific [cloudPC](../resources/cloudpc.md) object. Update the Cloud PC entity displayName.|
For clarity, please start the second sentence with "Use this API to...". Please, remove "for" before "a". Also, please apply bold formatting to displayName. Suggested revision:

- Rename a specific \[cloudPC\](../resources/cloudpc.md) object. Use this API to update the \*\*displayName\*\* for the Cloud PC entity.

2021-12-03 20:51 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpc.md
> +|[Reboot](../api/cloudpc-reboot.md)|None|Reboot for a specific [cloudPC](../resources/cloudpc.md) object.|
For consistency, please remove "for" before "a".

2021-12-03 20:51 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpc.md
> +|[Troubleshoot](../api/cloudpc-troubleshoot.md)|None|Troubleshoot for a specific [cloudPC](../resources/cloudpc.md) object. Check the Cloud PC and the Session Host health status.|
For consistency, please remove "for" before "a". For clarity, I recommend you to rephrase the second sentence. Suggested revision:

- Troubleshoot a specific \[cloudPC\](../resources/cloudpc.md) object. Use this API to check the health status of the Cloud PC and the session host.

2021-12-03 20:51 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpc.md
> +|[EndGracePeriod](../api/cloudpc-endgraceperiod.md)|None|End the grace period for a [cloudPC](../resources/cloudpc.md) object.|
Please, replace "EndGracePeriod" with "End grace period".

2021-12-03 20:51 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpc.md
> +|[Reprovision cloudPC remote action](../api/manageddevice-reprovisioncloudpc.md)|None|Reprovision a Cloud PC with Intune managed device ID.|
For consistency with the entry in the TOC, please replace "Reprovision cloudPC remote action" with "Reprovision remote action". Please, align the name of all methods in this table with the friendly name provided in the TOC.

2021-12-06 07:58 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|[Reprovision cloudPC remote action](../api/manageddevice-reprovisioncloudpc.md)|None|Reprovision a Cloud PC with Intune managed device ID.|
Updated.

2021-12-06 08:34 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|lastRemoteActionResult|[cloudPcRemoteActionResult](../resources/cloudpcremoteactionresult.md)|The last remote action result of the Cloud PC. Now supported remote actions include: rename, reboot, rep
Hi @JarbasHorst , the lastRemoteActionResult here only refers to the action result for **DMM device**. The actions here should not include "Resize" as DMM device does not support Resize. DMM device now only support rename, reboot, reprovision and troubleshoot. Do I need to update the description to "The last remote action result of the Cloud PC DMM device. The supported remote actions are: Rename, Reboot, Reprovision, and Troubleshoot."?

Then as for the actionName in cloudpcremoteactionresult.md file, yes actually it should include Reprovision, Resize, Rename, Reboot, Troubleshoot, but currently MEM portal only support Resize and Reprovision, DMM device only support Rename, Reboot, Reprovision and Troubleshoot. So do I need to update actionName's description to "The specified action. Supported values in MEM portal: Reprovision, Resize; supported values for DMM device: Rename, Reboot, Reprovision, Troubleshoot"?

2021-12-06 08:42 UTC, RuiHou105 commented on api-reference/beta/api/cloudpc-rename.md
> +Rename a specific Cloud PC. Update the **displayName** for the Cloud PC entity.
@JarbasHorst  Updated. Please take a second look when you got time. Thanks!

2021-12-06 08:51 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
>  |Property|Type|Description|
Updated. Please check.

2021-12-06 08:54 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|[Troubleshoot](../api/cloudpc-troubleshoot.md)|None|Troubleshoot for a specific [cloudPC](../resources/cloudpc.md) object. Check the Cloud PC and the Session Host health status.|
Updated. Please check.

2021-12-06 08:58 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|[Reprovision cloudPC remote action](../api/manageddevice-reprovisioncloudpc.md)|None|Reprovision a Cloud PC with Intune managed device ID.|
@JarbasHorst  Updated. Please check. Thanks.

2021-12-06 09:02 UTC, opbld31 commented
Docs Build status updates of commit _[8b97901](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b979016aa50daf3b65af4ec7715b9dfe05fcc25)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) | [Details](#user-content-0094819f09e3340df09eb0358fea0d24-526b5516)
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcloginresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpcloginresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcloginresult?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0094819f09e3340df09eb0358fea0d24-526b5516"></a>
### [api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpc.md)
 - **Line 29, Column 117**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resource/cloudpc.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112060900337877-14840%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-06T09%3A02%3A02Z&sr=b&sp=r&sig=N7HB8ky7HdvxIhrRdsibGqFu9Bs8MbtblizoiViINLI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 09:24 UTC, opbld31 commented
Docs Build status updates of commit _[fc6f309](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc6f30921f4a068eecd6caf3874a9e237afc3bd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcloginresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpcloginresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcloginresult?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112060922429352-14840%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-06T09%3A24%3A43Z&sr=b&sp=r&sig=cZ1InmDB6ck2I29dZNnEtf5cr%2FfIxwALNa5OtN4FBBU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 21:36 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpc.md
> +Represents a cloud-managed virtual desktop. This Cloud PC is also enrolled into Intune and managed through the Microsoft Endpoint Manager (MEM) portal, so the Cloud PC also has a corresponding Intune
Sorry for the wrong revision. Actually, we don't abbreviate Microsoft because it's a trademark. In this case, please remove (MEM) from this sentence.

2021-12-06 21:36 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpc.md
> +|lastRemoteActionResult|[cloudPcRemoteActionResult](../resources/cloudpcremoteactionresult.md)|The last remote action result of the Cloud PC. Now supported remote actions include: rename, reboot, rep
Hi @RuiHou105, thanks for your detailed answer. 

a) If a DMM device does not support Resize, then you don't need to include it here.
b) As a developer, I would be very interested in understand the values supported in the different cases. In this case, I think the following description would be useful for users consuming APIs. Suggested revision:

- The specified action. Supported values in the Microsoft Endpoint Manager portal are: \`Reprovision\`, \`Resize\`. Supported values in DMM devices are: \`Rename\`, \`Reboot\`, \`Reprovision\`, \`Troubleshoot\`?

For clarity, please spell out DMM without abbreviating it.

2021-12-06 21:51 UTC, JarbasHorst requested changes

2021-12-06 21:51 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpc.md
> +|[Resize remote action](../api/manageddevice-resizecloudpc.md)|None|Upgrade or downgrade an existing CloudPC to another configuration with new vCPU and storage size through Intune managed device ID.|
Please, replace "CloudPC" with "Cloud PC".

2021-12-07 06:44 UTC, opbld31 commented
Docs Build status updates of commit _[8b842c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b842c821c4d2cc906482499390a8f2dcbfbbd4e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcloginresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpcloginresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcloginresult?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112070642288151-14840%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T06%3A44%3A24Z&sr=b&sp=r&sig=pER3OUgGelUKLHSdjpHR5SlrP09H%2BD5694mmFOdolr0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-07 06:45 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|[Resize remote action](../api/manageddevice-resizecloudpc.md)|None|Upgrade or downgrade an existing CloudPC to another configuration with new vCPU and storage size through Intune managed device ID.|
Updated.

2021-12-07 07:02 UTC, opbld33 commented
Docs Build status updates of commit _[049f330](https://github.com/microsoftgraph/microsoft-graph-docs/commits/049f330673cbaf6592b8db9f40d05e709ec249f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcloginresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpcloginresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcloginresult?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcremoteactionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpcremoteactionresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcremoteactionresult?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112070700459947-14840%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T07%3A02%3A30Z&sr=b&sp=r&sig=ax5axFNh4Zih8PpEE4K%2BYuHrehNBBP%2FgwAJtqyv%2BeSU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-07 07:04 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|lastRemoteActionResult|[cloudPcRemoteActionResult](../resources/cloudpcremoteactionresult.md)|The last remote action result of the Cloud PC. Now supported remote actions include: rename, reboot, rep
Hi @JarbasHorst. 
a). Updated.
b). Updated.

Besides, in the updated description, I use "**enterprise Cloud PCs**" to represent DMM devices because there are two kinds of Cloud PC devices: DMM devices are enterprise Cloud PCs; DSS devices are Very Small Business Cloud PCs. So here I use "enterprise Cloud PCs" to represent DMM devices.

2021-12-07 22:39 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpc.md
> +|lastRemoteActionResult|[cloudPcRemoteActionResult](../resources/cloudpcremoteactionresult.md)|The last remote action result of the Cloud PC. Now supported remote actions include: rename, reboot, rep
Thanks for the clarifying.

2021-12-07 22:40 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-12-08 01:21 UTC, Lauragra approved these changes

2021-12-08 01:21 UTC, opbld32 commented
Docs Build status updates of commit _[422e66d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/422e66dc36d7a066616ad52751d290424c970caf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcloginresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpcloginresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcloginresult?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcremoteactionresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/resources/cloudpcremoteactionresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcremoteactionresult?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-14840) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/addAPIsAndPropertiesToCloudPC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112080119377029-14840%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-08T01%3A21%3A32Z&sr=b&sp=r&sig=neHa4vqratvDci7UnHbb%2FHtOwyyOpBJm9SnZf%2Bh9aKI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 03:49 UTC, merged