Add note for app installation about RSC apps
microsoftgraph/microsoft-graph-docs pull request #14922
Opened 2021-11-11 23:19 UTC by jessiechan27

2021-11-11 23:21 UTC, opbld30 commented
Docs Build status updates of commit _[6ccbcee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ccbcee68719d1bc5e581f3805d352b83f246a17)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-14922) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111112319319315-14922%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T23%3A21%3A30Z&sr=b&sp=r&sig=0XeRETQFu%2BSeZ34JcBzekZFbx%2FI63bCzYtuJUSmsrRk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-11 23:24 UTC, AkJo commented on concepts/known-issues.md
> +The API calls for [add app to team](/graph/api/team-post-installedapps.md), [add app to chat](/graph/api/chat-post-installedapps.md), and [add app for user](/graph/api/userteamwork-post-installedapps
We need to call out the respective upgrade APIs as well.

2021-11-12 00:00 UTC, opbld30 commented
Docs Build status updates of commit _[83c9215](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83c9215ee668383c66e1650d0918d094fc8e79fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-14922) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111112358415129-14922%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T00%3A00%3A03Z&sr=b&sp=r&sig=M1gifhW8uN%2F6osh20BCE%2FWZ8Xnvm%2B68idUKCMtynFBo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 00:07 UTC, AkJo requested changes

2021-11-12 00:07 UTC, AkJo commented on concepts/known-issues.md
> +- [Add app for user](/graph/api/userteamwork-post-installedapps.md)
Remove these two that pertain to user scoped apps.

2021-11-18 17:05 UTC, opbld32 commented
Docs Build status updates of commit _[f0db5d7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f0db5d70bb917ccb5fa559b32851a196134561dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-14922) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-14922) (graph-rest-beta) |
[api-reference/beta/api/team-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/beta/api/team-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-installedapps?view=graph-rest-beta&branch=pr-en-us-14922) (graph-rest-beta) |
[api-reference/beta/api/team-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/beta/api/team-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-14922) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/v1.0/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-1.0&branch=pr-en-us-14922) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/v1.0/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-1.0&branch=pr-en-us-14922) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/v1.0/api/team-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-installedapps?view=graph-rest-1.0&branch=pr-en-us-14922) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/v1.0/api/team-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-teamsappinstallation-upgrade?view=graph-rest-1.0&branch=pr-en-us-14922) (>= graph-rest-1.0) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-14922) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111181703421519-14922%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-19T17%3A05%3A19Z&sr=b&sp=r&sig=lNOI3oIgwZoh4avvevtiK6nKv2KsnC9tn3hVIboPfxY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 17:33 UTC, opbld31 commented
Docs Build status updates of commit _[23a321b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23a321bc3bdc2c6b2a934bd20a1370079a9a81db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-14922) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-14922) (graph-rest-beta) |
[api-reference/beta/api/team-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/beta/api/team-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-installedapps?view=graph-rest-beta&branch=pr-en-us-14922) (graph-rest-beta) |
[api-reference/beta/api/team-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/beta/api/team-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-14922) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/v1.0/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-1.0&branch=pr-en-us-14922) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/v1.0/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-1.0&branch=pr-en-us-14922) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/v1.0/api/team-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-installedapps?view=graph-rest-1.0&branch=pr-en-us-14922) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/api-reference/v1.0/api/team-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-teamsappinstallation-upgrade?view=graph-rest-1.0&branch=pr-en-us-14922) (>= graph-rest-1.0) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-apps-notes/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-14922) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111181730405113-14922%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-19T17%3A33%3A27Z&sr=b&sp=r&sig=P%2FeFBmtE6DexbpUqS2VWViWecKbIqFMTIVoQdUvQ8zw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 19:33 UTC, AkJo commented on api-reference/beta/api/chat-post-installedapps.md
> +> - Currently, this operation does not support installation of apps that require resource-specific consent permissions. For details, see [Known issues](/graph/known-issues#Installation-of-apps-that-r
@Lauragra , should both "K" and "I" in Known Issues be uppercase, or should both be lower case?

2021-11-18 19:33 UTC, AkJo commented on api-reference/beta/api/chat-teamsappinstallation-upgrade.md
> +> - Currently, this operation does not support upgrade of apps that require resource-specific consent permissions. For details, see [Known issues](/graph/known-issues#Installation-of-apps-that-requir
Same comment applies here and elsewhere. Please gets @Lauragra 's guidance.

2021-11-18 19:37 UTC, AkJo commented on api-reference/beta/api/team-teamsappinstallation-upgrade.md
> +> **Note:** Currently, this operation does not support upgrade of apps that require resource-specific consent permissions. For details, see [Known issues](/graph/known-issues#Installation-of-apps-tha
Please do ensure that the hyperlink does take you to the right section when the changes are live.

2021-11-18 19:37 UTC, AkJo approved these changes
Approved with comments.

2021-11-18 19:56 UTC, Lauragra commented on api-reference/beta/api/chat-teamsappinstallation-upgrade.md
> +> - Currently, this operation does not support upgrade of apps that require resource-specific consent permissions. For details, see [Known issues](/graph/known-issues#Installation-of-apps-that-requir
This is correct - Known issues (sentence case).

2021-11-18 19:56 UTC, Lauragra commented on api-reference/beta/api/chat-post-installedapps.md
> +> - Currently, this operation does not support installation of apps that require resource-specific consent permissions. For details, see [Known issues](/graph/known-issues#Installation-of-apps-that-r
We use sentence case for titles so Known issues is correct.

2021-11-18 20:33 UTC, jessiechan27 commented on api-reference/beta/api/team-teamsappinstallation-upgrade.md
> +> **Note:** Currently, this operation does not support upgrade of apps that require resource-specific consent permissions. For details, see [Known issues](/graph/known-issues#Installation-of-apps-tha
Will do

2021-11-19 04:30 UTC, merged