Creating documentation for new Recommendations API
microsoftgraph/microsoft-graph-docs pull request #14924
Opened 2021-11-12 00:57 UTC by hafowler

2021-11-12 00:59 UTC, opbld34 commented
Docs Build status updates of commit _[d193cb4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d193cb41ac10bde5d871a4e3288de3c1327464a5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-98e9747108e3907f7709d0f18c2bc918-e3221031)
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-e3221031)
[api-reference/beta/api/recommendation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-47605e265abc80d0e4ef3571d08dc9db-e3221031)
[api-reference/beta/api/recommendation-post-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-post-impactedresources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-post-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-e7b8ec303abf7f54bffc8fd6e4969fc2-e3221031)
[api-reference/beta/api/recommendation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-update?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-0fb7c01e0e7ebcc8cff18a1e35ed8eb6-e3221031)
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-d7338dcfc768ab07e7660e5a9e62e940-e3221031)
[api-reference/beta/api/recommendationresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-update?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-e15cf394d4a8665e2414e25ef455316b-e3221031)
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-7b4e61275e15e934993171aa8e4434c5-e3221031)
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-67b720fc2066db8ac014e0f4c00cce68-e3221031)
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-d731666696fbf85a6d80dfd9f06d57e4-e3221031)
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-649ccc830445ed758828e58b2eb8e7af-e3221031)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-e3221031)
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="98e9747108e3907f7709d0f18c2bc918-e3221031"></a>
### [api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="8d035408ad5d3bba49b03761995573e5-e3221031"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="47605e265abc80d0e4ef3571d08dc9db-e3221031"></a>
### [api-reference/beta/api/recommendation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/aut [...]

2021-11-12 04:14 UTC, opbld32 commented
Docs Build status updates of commit _[647d64a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/647d64abe47d7788c852cdbf5b4c2f5798a21e24)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-649ccc830445ed758828e58b2eb8e7af-758c5354)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-758c5354)
[api-reference/beta/api/recommendation-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="649ccc830445ed758828e58b2eb8e7af-758c5354"></a>
### [api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md)
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/recommendationresource-list.md'.`````
 - **Line 26, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/recommendationresource-update.md'.`````
 - **Line 36, Column 20**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/intune-keyvalue.md'.`````

<a id="0817dce4456c16725d5333633847d38f-758c5354"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aad [...]

2021-11-12 04:24 UTC, opbld31 commented
Docs Build status updates of commit _[e2a6763](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2a676366463351a732951ab1ba502d61b62d72d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recommendation-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111120421280157-14924%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T04%3A24%3A28Z&sr=b&sp=r&sig=LFoSUh1C5m0giWbCit4RVfGzvw4IvOO0VgUlNtKO778%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 04:52 UTC, opbld32 commented
Docs Build status updates of commit _[6e36c67](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e36c673f545c1df51eb48d0b005ab62d07377a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recommendation-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111120450202115-14924%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T04%3A52%3A03Z&sr=b&sp=r&sig=Ly73cT1Zx89gTq2vq2iYI7rdlqDxv5QCRXyiRFLiew0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?gro [...]

2021-11-12 05:02 UTC, opbld30 commented
Docs Build status updates of commit _[643ce96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/643ce9651cc1ad6fb16df4e429118607a5c7ce95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recommendation-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/enums-recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/enums-recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111120500181072-14924%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T05%3A02%3A12Z&sr=b&sp=r&sig=PEmeRcsS3hlsW7GJYFyxVIX6uhD3XQDEtvncVOVfZMw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com [...]

2021-11-12 05:16 UTC, opbld32 commented
Docs Build status updates of commit _[75c70b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/75c70b79f6d1887501af4c3b243ec03aaf570b81)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recommendation-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111120514002051-14924%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T05%3A16%3A02Z&sr=b&sp=r&sig=XaQXMAWFup8W8S2K2MVxYxHmUAxzEAKEWLWvRDtmttk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?gro [...]

2021-11-30 21:26 UTC, opbld33 commented
Docs Build status updates of commit _[b318f22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b318f22963f6dff2c5e602fff94bba00c75533c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recommendation-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111302124274123-14924%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-31T21%3A26%3A20Z&sr=b&sp=r&sig=9L6xz2JyeklrFr2gU7HW3Ig1FppznTrtWTrORKTE5eA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?gro [...]

2021-12-01 10:28 UTC, opbld32 commented
Docs Build status updates of commit _[562d8a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/562d8a3ef48db55ecebe85f296a09086cf9e3d35)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recommendation-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112011026073032-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T10%3A28%3A56Z&sr=b&sp=r&sig=qNJRWEPavCaWyeOyNHI6viDqNCYsy%2BXbzt4IaDEYZwU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?gr [...]

2022-02-28 23:48 UTC, opbld30 commented
Docs Build status updates of commit _[89113e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89113e15861996d63c6676b0cb5ff0b7f63b96f9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-95801719)

<a id="95801719"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202282347206197-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-31T23%3A48%3A05Z&sr=b&sp=r&sig=5UZ3HNZzJmxEtKUPHBv45oIAEsLt0OFF7lOzQ8iupWM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-28 23:58 UTC, opbld34 commented
Docs Build status updates of commit _[80b35ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80b35ca3a7480c8395f76ad131cd9cfa7768eb83)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-27bec0e3)

<a id="27bec0e3"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202282358162754-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-31T23%3A58%3A52Z&sr=b&sp=r&sig=EL3bv6ODaTj14ddbuR5UbskLf0pQXLzyjpYF2q8IirE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-01 00:15 UTC, opbld33 commented
Docs Build status updates of commit _[e1d2e42](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1d2e42289201da4584c94845075df6e35920d9a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-717536c2)
[api-reference/beta/api/recommendation-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14924) |

<a id="8d035408ad5d3bba49b03761995573e5-717536c2"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 72, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to th [...]

2022-03-03 22:06 UTC, FaithOmbongi requested changes
Thank you @hafowler for your extensive work on this PR. I've left a lot of comments but mostly minor fixes. 

- GLOBAL: Please use actual ID in example requests and document real response objects.
- I've recommended in a few areas to avoid using the term directory object because its tightly tied to directoryObject resource type and resources that inherit from it. Can I assume you may increase the scope of this API to return recommendations about resources that don't necessarily inherit from directoryObject?
- I haven't yet reviewed the changelog, but I will. I recommend though that you move it to Line 3 at the top of your file.

2022-03-03 22:06 UTC, FaithOmbongi commented on api-reference/beta/api/recommendation-list-impactedresources.md
> +}
Add the closing backticks here. That might be the cause of the API Doctor error.

2022-03-03 22:06 UTC, FaithOmbongi commented on concepts/permissions-reference.md
> +## Recommendations permissions
```suggestion
## Azure AD recommendations permissions
```

2022-03-03 23:53 UTC, hafowler commented on api-reference/beta/api/recommendation-list-impactedresources.md
> +}
Thanks!

2022-03-03 23:55 UTC, opbld34 commented
Docs Build status updates of commit _[732063a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/732063a4d79a5b3802ac78a74d5ed3ee633ba087)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-0fa3e63c)
[api-reference/beta/api/recommendation-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14924) |

<a id="8d035408ad5d3bba49b03761995573e5-0fa3e63c"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 72, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to th [...]

2022-03-03 23:57 UTC, opbld33 commented
Docs Build status updates of commit _[43d30a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/43d30a8425205eba07f5bff9de70468fb9fbefd6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-5899748a)
[api-reference/beta/api/recommendation-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14924) |

<a id="8d035408ad5d3bba49b03761995573e5-5899748a"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 72, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to th [...]

2022-03-04 00:06 UTC, hafowler commented on api-reference/beta/toc.yml
> +            href: api/recommendationresource-reactivate.md
Yes, I think this falls under Reporting APIs

2022-03-04 00:07 UTC, opbld30 commented
Docs Build status updates of commit _[6ef1782](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ef17828d4aa808c20aae56c9526d30bf871cfa0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-a8e2163c)
[api-reference/beta/api/recommendation-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14924) |

<a id="8d035408ad5d3bba49b03761995573e5-a8e2163c"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 72, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to th [...]

2022-03-04 00:08 UTC, opbld34 commented
Docs Build status updates of commit _[ef95eb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ef95eb6fb1dd5fa3445c3b45c6ec8f464cfad202)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-36b0bdb3)
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-36b0bdb3)
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :warning:Warning | | [Details](#user-content-d731666696fbf85a6d80dfd9f06d57e4-36b0bdb3)

<a id="0817dce4456c16725d5333633847d38f-36b0bdb3"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml)
 - **Line 11427, Column 20**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="8d035408ad5d3bba49b03761995573e5-36b0bdb3"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 72, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="d731666696fbf85a6d80dfd9f06d57e4-36b0bdb3"></a>
### [api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/directory-list-recommendations.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203040006416780-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-04T00%3A08%3A50Z&sr=b&sp=r&sig=LxdMPSevbrad%2B7ZcM%2BqOseJRO%2F2iIhW1Nhpl7vYg6dA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-07 11:02 UTC, FaithOmbongi requested changes
Thank you for your patience @hafowler. I've completed the review on the changelog and made suggestions including:
- Add two entries for the two new relationships in directory resource. Please see the guidance for the structure of the changelog entry (ies): https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog
GLOBAL in the changelog: Please fix all API links; They should be absolute public links preceded with `https://docs.microsoft.com/en-us/graph/api/*`. The links to **resources** should be preceded by `https://docs.microsoft.com/en-us/graph/api/resources/`.
- I've added suggestions to enhance some of the changelog entries. It helps customers get API capability from the changelog - before going to the docs. Please accept, correct, or reject the suggestions as required.

For the TOC: I think these APIs should be under Reporting APIs? What do you think?

2022-03-07 11:02 UTC, FaithOmbongi commented on api-reference/beta/resources/recommendation.md
> +|[List impactedResources](../api/recommendation-list-impactedresources.md)|[recommendationResource](../resources/recommendationresource.md) collection|List the recommendationResource resources from t
```suggestion
|[List impactedResources](../api/recommendation-list-impactedresources.md)|[recommendationResource](../resources/recommendationresource.md) collection|Retrieve the Azure AD resources that are associated with a recommendation.|
```

2022-03-08 04:22 UTC, opbld30 commented
Docs Build status updates of commit _[85677a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85677a4a37d82a1daeaeed40101fe68ea8998627)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-d72656ad)
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-d72656ad)
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :warning:Warning | | [Details](#user-content-d731666696fbf85a6d80dfd9f06d57e4-d72656ad)

<a id="0817dce4456c16725d5333633847d38f-d72656ad"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml)
 - **Line 11479, Column 20**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="8d035408ad5d3bba49b03761995573e5-d72656ad"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 72, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="d731666696fbf85a6d80dfd9f06d57e4-d72656ad"></a>
### [api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/directory-list-recommendations.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203080420163430-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T04%3A22%3A23Z&sr=b&sp=r&sig=ixfYfaEu8CexJt8VXopEpRE1RwQ%2BKMNDMnaD%2BbNpxaQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-08 04:24 UTC, opbld34 commented
Docs Build status updates of commit _[32f14a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32f14a9bfd7603d4771614a8d5d0e0b522956951)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-72fb391b)
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-72fb391b)
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :warning:Warning | | [Details](#user-content-d731666696fbf85a6d80dfd9f06d57e4-72fb391b)

<a id="0817dce4456c16725d5333633847d38f-72fb391b"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml)
 - **Line 11479, Column 20**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="8d035408ad5d3bba49b03761995573e5-72fb391b"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 72, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="d731666696fbf85a6d80dfd9f06d57e4-72fb391b"></a>
### [api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/directory-list-recommendations.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203080422246613-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T04%3A24%3A25Z&sr=b&sp=r&sig=%2FR2GuxlA1EfHQhjqdN1PTxL251emjnfHuNxXedGB0es%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-08 04:26 UTC, opbld31 commented
Docs Build status updates of commit _[035410c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/035410c320678f83fd281c755c142afff8dd19ad)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-3bcfa24a)
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-3bcfa24a)
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :warning:Warning | | [Details](#user-content-d731666696fbf85a6d80dfd9f06d57e4-3bcfa24a)

<a id="0817dce4456c16725d5333633847d38f-3bcfa24a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml)
 - **Line 11479, Column 20**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="8d035408ad5d3bba49b03761995573e5-3bcfa24a"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 72, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="d731666696fbf85a6d80dfd9f06d57e4-3bcfa24a"></a>
### [api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/directory-list-recommendations.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203080423056567-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T04%3A26%3A25Z&sr=b&sp=r&sig=BqRv20QO42kOR9OtxixdHCIwuyaLMRQm4cC%2BRItx3wI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-08 05:13 UTC, hafowler commented on api-reference/beta/resources/recommendation.md
> +|id|String|The unique identifer for the recommendation. Inherited from [entity](../resources/entity.md). This is a concatenation of your tenant id and the recommendation's nickname.|
It is a value known by AAD only

2022-03-08 05:13 UTC, opbld34 commented
Docs Build status updates of commit _[3b05848](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b0584869be67a0bec00cc23a72715d1fb1e4d80)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-6157c150)
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-6157c150)
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :warning:Warning | | [Details](#user-content-d731666696fbf85a6d80dfd9f06d57e4-6157c150)

<a id="0817dce4456c16725d5333633847d38f-6157c150"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml)
 - **Line 11479, Column 20**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="8d035408ad5d3bba49b03761995573e5-6157c150"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 72, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="d731666696fbf85a6d80dfd9f06d57e4-6157c150"></a>
### [api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/directory-list-recommendations.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203080510234561-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T05%3A13%3A36Z&sr=b&sp=r&sig=Al0nXKUAr07Q3pyFzOtaFKfeuQLl0ojLOPwOOf0Nbhw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-08 05:14 UTC, hafowler commented on api-reference/beta/resources/recommendation.md
> +|impactStartDateTime|DateTimeOffset|The future DateTime that a [recommendation](../resources/recommendation.md) should be completed by. |
If a customer doesn't complete a recommendation by the impactStartDate, there could be breaking changes.

2022-03-08 05:16 UTC, opbld30 commented
Docs Build status updates of commit _[dd10fea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd10feae43f9facc50c9f0fb777b071317534c99)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-580ed6cf)
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-580ed6cf)
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :warning:Warning | | [Details](#user-content-d731666696fbf85a6d80dfd9f06d57e4-580ed6cf)

<a id="0817dce4456c16725d5333633847d38f-580ed6cf"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml)
 - **Line 11479, Column 20**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="8d035408ad5d3bba49b03761995573e5-580ed6cf"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 72, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="d731666696fbf85a6d80dfd9f06d57e4-580ed6cf"></a>
### [api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/directory-list-recommendations.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203080514276685-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T05%3A16%3A26Z&sr=b&sp=r&sig=c%2Bos%2FfQ4KSFTXo1gAVtFgtoIFVP0TryG7S%2BnbjhFWrc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-08 05:17 UTC, hafowler commented on api-reference/beta/api/recommendation-dismiss.md
> +|dismissReason|String|Audited reason for deeming a recommendation inapplicable to you.|
Correct, dismiss is tenant-wide

2022-03-08 05:19 UTC, hafowler commented on api-reference/beta/api/recommendation-list-impactedresources.md
> +GET /directory/recommendations/{recommendationId}?$expand=impactedResources
Correct. That was our original intention, but the technical implementation was too complex and required a hacky solution.

2022-03-08 05:19 UTC, opbld34 commented
Docs Build status updates of commit _[f46d095](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f46d09590ab61ebf4e805c8fdc6253e1342eea39)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-593929ea)
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-593929ea)
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :warning:Warning | | [Details](#user-content-d731666696fbf85a6d80dfd9f06d57e4-593929ea)

<a id="0817dce4456c16725d5333633847d38f-593929ea"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml)
 - **Line 11479, Column 20**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="8d035408ad5d3bba49b03761995573e5-593929ea"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 72, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="d731666696fbf85a6d80dfd9f06d57e4-593929ea"></a>
### [api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/directory-list-recommendations.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203080515583232-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T05%3A19%3A35Z&sr=b&sp=r&sig=TY%2BJldZ0HDXwXGIOGzBp8vvq3Bqb7Aa%2BNU32FvCYW9o%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-08 05:20 UTC, hafowler commented on api-reference/beta/api/recommendation-list.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Confirming these parameters.

2022-03-08 05:22 UTC, hafowler commented on api-reference/beta/api/recommendationresource-dismiss.md
> +|dismissReason|String|Audited reason for deeming a [recommendation](../resources/recommendation.md) inapplicable to you.|
This is dismissing the resource, not the recommendation.

2022-03-08 05:23 UTC, hafowler commented on api-reference/beta/api/recommendationresource-get.md
> +GET /directory/impactedResources/{recommendationResourceId}
This is correct. Similar to a previous comment, we had to have a different endpoint in order to support getting the resource directly, not through the recommendation endpoint

2022-03-08 05:27 UTC, hafowler commented on api-reference/beta/resources/recommendationresource.md
> +|owner|String|The user responsible for maintaining the resource.|
Our service sets the ownership if known

2022-03-08 05:28 UTC, hafowler commented on api-reference/beta/resources/recommendationresource.md
> +|resourceType|String|Indicates the type of directory object. Examples include `user`, `application`, etc.|
This is not the property to be deprecated. Will be sure to document which properties will be deprecated, if any

2022-03-08 05:35 UTC, opbld32 commented
Docs Build status updates of commit _[f0de4ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f0de4eed85764b99edf9c351431b36747be59589)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-23e3c3d0)
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-23e3c3d0)
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :warning:Warning | | [Details](#user-content-a0b890a2f296fa59ddce1e21604b179a-23e3c3d0)
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :warning:Warning | | [Details](#user-content-80acf6bff3f6c09dc861701a473ff03b-23e3c3d0)
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :warning:Warning | | [Details](#user-content-d731666696fbf85a6d80dfd9f06d57e4-23e3c3d0)

<a id="0817dce4456c16725d5333633847d38f-23e3c3d0"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml)
 - **Line 11479, Column 20**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="8d035408ad5d3bba49b03761995573e5-23e3c3d0"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 15, Column 71**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'recommendation.md'.`````
 - **Line 72, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="a0b890a2f296fa59ddce1e21604b179a-23e3c3d0"></a>
### [api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'recommendationResource: reactivate' is duplicated with other articles: 'beta/api/recommendationresource-complete.md(10,1), beta/api/recommendationresource-reactivate.md(10,1)'. First level headings must be unique within a docset.`````

<a id="80acf6bff3f6c09dc861701a473ff03b-23e3c3d0"></a>
### [api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'recommendationResource: reactivate' is duplicated with other articles: 'beta/api/recommendationresource-complete.md(10,1), beta/api/recommendationresource-reactivate.md(10,1)'. First level headings must be unique within a docset.`````

<a id="d731666696fbf85a6d80dfd9f06d57e4-23e3c3d0"></a>
### [api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/directory-list-recommendations.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203080528578077-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T05%3A35%3A50Z&sr=b&sp=r&sig=0gPSz5YRtAefcBM%2F9PuJU2H2yuYjyC1nRwpZHoEXV9A%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-08 05:40 UTC, opbld33 commented
Docs Build status updates of commit _[582a4a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/582a4a624c75c771ef199c9eb02f7a6f368e4b22)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-ceddd9b0)
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-ceddd9b0)
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :warning:Warning | | [Details](#user-content-a0b890a2f296fa59ddce1e21604b179a-ceddd9b0)
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :warning:Warning | | [Details](#user-content-80acf6bff3f6c09dc861701a473ff03b-ceddd9b0)
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :warning:Warning | | [Details](#user-content-d731666696fbf85a6d80dfd9f06d57e4-ceddd9b0)

<a id="0817dce4456c16725d5333633847d38f-ceddd9b0"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml)
 - **Line 11479, Column 20**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="8d035408ad5d3bba49b03761995573e5-ceddd9b0"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 15, Column 71**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'recommendation.md'.`````

<a id="a0b890a2f296fa59ddce1e21604b179a-ceddd9b0"></a>
### [api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'recommendationResource: reactivate' is duplicated with other articles: 'beta/api/recommendationresource-complete.md(10,1), beta/api/recommendationresource-reactivate.md(10,1)'. First level headings must be unique within a docset.`````

<a id="80acf6bff3f6c09dc861701a473ff03b-ceddd9b0"></a>
### [api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'recommendationResource: reactivate' is duplicated with other articles: 'beta/api/recommendationresource-complete.md(10,1), beta/api/recommendationresource-reactivate.md(10,1)'. First level headings must be unique within a docset.`````

<a id="d731666696fbf85a6d80dfd9f06d57e4-ceddd9b0"></a>
### [api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/directory-list-recommendations.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203080534031064-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T05%3A40%3A13Z&sr=b&sp=r&sig=s6SqZn7oA5Y98vetupnJI5oFtX9xjovnv5Hmk7BHI3I%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-08 06:08 UTC, opbld31 commented
Docs Build status updates of commit _[940e702](https://github.com/microsoftgraph/microsoft-graph-docs/commits/940e702626d5f0b7e892ccfdc73ffaf897953519)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-cf54e1f7)
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-cf54e1f7)
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :warning:Warning | | [Details](#user-content-a0b890a2f296fa59ddce1e21604b179a-cf54e1f7)
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :warning:Warning | | [Details](#user-content-80acf6bff3f6c09dc861701a473ff03b-cf54e1f7)

<a id="0817dce4456c16725d5333633847d38f-cf54e1f7"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml)
 - **Line 11479, Column 20**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="8d035408ad5d3bba49b03761995573e5-cf54e1f7"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 15, Column 71**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'recommendation.md'.`````

<a id="a0b890a2f296fa59ddce1e21604b179a-cf54e1f7"></a>
### [api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'recommendationResource: reactivate' is duplicated with other articles: 'beta/api/recommendationresource-complete.md(10,1), beta/api/recommendationresource-reactivate.md(10,1)'. First level headings must be unique within a docset.`````

<a id="80acf6bff3f6c09dc861701a473ff03b-cf54e1f7"></a>
### [api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'recommendationResource: reactivate' is duplicated with other articles: 'beta/api/recommendationresource-complete.md(10,1), beta/api/recommendationresource-reactivate.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203080606322875-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T06%3A08%3A33Z&sr=b&sp=r&sig=isUS2t%2BSJ1MaO1YDl7M9BjIuSG2VOY4vHHTso2ab8q4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-08 06:13 UTC, hafowler commented on api-reference/beta/api/recommendation-list.md
> +### Example 2
The pattern you suggest is outdated in the api.md file.

The correct query is what I have documented here. We don't want to document the directory/impactedResources endpoint, as we don't want to encourage customers to call that endpoint. Future recommendations currently in private preview will include a list of resources that are 1000s long. Making the directory/impactedResources call would thus be quite expensive.

2022-03-08 06:15 UTC, hafowler commented on api-reference/beta/resources/recommendation.md
> +Inherits from [entity](../resources/entity.md).
I added my own suggestion in recent commit.

2022-03-08 06:16 UTC, hafowler commented on api-reference/beta/resources/recommendation.md
> +
The recommendationCategory is going to be deprecated. I've added that on the recommendation.md file. So, I don't want to document too much on them here.

2022-03-08 06:17 UTC, hafowler commented on changelog/Microsoft.AAD.Reporting.json
> +      ],
Sorry, what 2 relationships are you referring to?

2022-03-10 21:16 UTC, opbld32 commented
Docs Build status updates of commit _[5d436ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d436acef845fd686c0242083e4107b9c96a7cbd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-368bd2bf)
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :warning:Warning | | [Details](#user-content-8d035408ad5d3bba49b03761995573e5-368bd2bf)
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :warning:Warning | | [Details](#user-content-a0b890a2f296fa59ddce1e21604b179a-368bd2bf)
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :warning:Warning | | [Details](#user-content-80acf6bff3f6c09dc861701a473ff03b-368bd2bf)

<a id="0817dce4456c16725d5333633847d38f-368bd2bf"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml)
 - **Line 11479, Column 20**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="8d035408ad5d3bba49b03761995573e5-368bd2bf"></a>
### [api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md)
 - **Line 15, Column 71**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'recommendation.md'.`````

<a id="a0b890a2f296fa59ddce1e21604b179a-368bd2bf"></a>
### [api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'recommendationResource: reactivate' is duplicated with other articles: 'beta/api/recommendationresource-complete.md(10,1), beta/api/recommendationresource-reactivate.md(10,1)'. First level headings must be unique within a docset.`````

<a id="80acf6bff3f6c09dc861701a473ff03b-368bd2bf"></a>
### [api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'recommendationResource: reactivate' is duplicated with other articles: 'beta/api/recommendationresource-complete.md(10,1), beta/api/recommendationresource-reactivate.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203102113308045-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T21%3A16%3A12Z&sr=b&sp=r&sig=pAOG4gXEk9wedzeuzuCwZuG03k3YvczUyASi0aA2La8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-10 21:23 UTC, opbld33 commented
Docs Build status updates of commit _[a6c6162](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a6c61627622a8805fca116530465decbe6dec978)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-d5654f59)

<a id="0817dce4456c16725d5333633847d38f-d5654f59"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml)
 - **Line 11479, Column 20**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203102121198372-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T21%3A23%3A27Z&sr=b&sp=r&sig=otepTSHOlrUvrzDkecRMcsyByRrZZCYmqdJxs4fhdvY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-10 21:30 UTC, opbld32 commented
Docs Build status updates of commit _[db733c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db733c102061992062fd7d71a216880e910a2079)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-302da5c7)

<a id="0817dce4456c16725d5333633847d38f-302da5c7"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml)
 - **Line 11479, Column 20**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203102128301103-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T21%3A30%3A21Z&sr=b&sp=r&sig=xT0VbgRDxfMx4yf8FcCofK5MdQZnqclakdc3TsByfRo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-10 21:38 UTC, opbld34 commented
Docs Build status updates of commit _[13c40d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13c40d9985fdbedb02fa614b16e3bb2162342464)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directory-list-recommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/directory-list-recommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-recommendations?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-recommendations?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14924) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203102135518951-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T21%3A38%3A10Z&sr=b&sp=r&sig=v85CVZgX1uUOLexFR%2FJ2C9hRoEV1Tc%2BWEPLkzSlpEnE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?t [...]

2022-03-10 22:09 UTC, opbld34 commented
Docs Build status updates of commit _[2756441](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2756441c7b4d0d8cfbf85a976ab555f52d39f580)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directory-list-recommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/directory-list-recommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-recommendations?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-recommendations?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14924) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203102207012435-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T22%3A09%3A05Z&sr=b&sp=r&sig=dQ1yEy%2Fose9mLQ4pFpJ1mtEZGvGjZxw6nHtNq4Pfl44%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tab [...]

2022-03-10 22:14 UTC, opbld31 commented
Docs Build status updates of commit _[0c75fa1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c75fa176ef3ce76276979b06629b8d3df7d613b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directory-list-recommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/directory-list-recommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-recommendations?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-recommendations?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14924) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203102212312588-14924%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T22%3A14%3A21Z&sr=b&sp=r&sig=5AuxDAeNUlLTEm9JWvypfGEVQD207zgvCaRyWzBLu60%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabNa [...]

2022-03-15 19:22 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +      ],
@hafowler, as per the schema, you've added 2 relationships/navigation properties to the directory resource.

<img width="716" alt="image" src="https://user-images.githubusercontent.com/14026935/158454907-7c00fb83-f0d3-4c78-a2ae-f1e7dbbe89e0.png">

I've added the changelog record to lines 569-584. Please document the corresponding relationships in the [directory](https://docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta#relationships) resource page in alphabetical order.

2022-03-15 19:34 UTC, FaithOmbongi commented on api-reference/beta/resources/recommendation.md
> +
Well noted. But because it's going to be live for a while, we still need to give customers the complete information for their benefit while it's currently returned.

2022-03-15 19:53 UTC, opbld30 commented
Docs Build status updates of commit _[8d2ed12](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d2ed12dbb681ec73de5fa68ae405b915baa9527)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directory-list-recommendations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/directory-list-recommendations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-recommendations?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-list-impactedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-list-impactedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-list-impactedresources?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendation-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendation-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendation-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-complete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-complete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-complete?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-dismiss?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-get?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-postpone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-postpone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-postpone?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/api/recommendationresource-reactivate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/api/recommendationresource-reactivate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/recommendationresource-reactivate?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionstep?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/actionurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/actionurl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionurl?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/directory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/directory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendation?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/resources/recommendationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/resources/recommendationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/recommendationresource?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-recommendations?view=graph-rest-beta&branch=pr-en-us-14924) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-11-hafowler-aadr/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-14924) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203151951278516-14924%5Cworkflow_report.html?sv=2020-08-04&se [...]

2022-03-15 20:25 UTC, FaithOmbongi commented on api-reference/beta/api/recommendation-list-impactedresources.md
> +GET /directory/recommendations/{recommendationId}?$expand=impactedResources
Following this up internally

2022-12-09 22:40 UTC, opbld34 commented
Learn Build status updates of commit _[8d2ed12](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d2ed12dbb681ec73de5fa68ae405b915baa9527)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-764e8f30)

<a id="764e8f30"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 8d2ed12dbb681ec73de5fa68ae405b915baa9527 in branch 2021-11-11-hafowler-aadr of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit b82a6447402d2604131e631533421f860d242253). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212092240273831-14924/BuildReport?accessString=c269b2705cb4e64d532b695114977e7ff4b70b34073d3b4bc342863c12d7c626).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-14 22:03 UTC, closed without merging