[CloudPC]Add CloudPC as supported RBAC provider
microsoftgraph/microsoft-graph-docs pull request #14926
Opened 2021-11-12 07:22 UTC by AshleyYangSZ

2021-11-12 07:24 UTC, opbld33 commented
Docs Build status updates of commit _[dee3c5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dee3c5ac2ca8265574288f0a93f8c5696d9db4d0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) | [Details](#user-content-5c066b4f5509f66da630dc3a06482c68-3477d6cd)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |

<a id="5c066b4f5509f66da630dc3a06482c68-3477d6cd"></a>
### [api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md)
 - **Line 172, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111120722133248-14926%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T07%3A24%3A03Z&sr=b&sp=r&sig=GBcLE1DrLrLL3etH2tSNB%2B8Q6vzxAuKVFLpYH9aBKIc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 07:34 UTC, opbld31 commented
Docs Build status updates of commit _[88b6ab7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88b6ab7d4ff3fb5f9ac4384aa6daaff57cda421f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) | [Details](#user-content-5c066b4f5509f66da630dc3a06482c68-1c6527dd)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5c066b4f5509f66da630dc3a06482c68-1c6527dd"></a>
### [api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md)
 - **Line 172, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111120733003940-14926%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T07%3A34%3A41Z&sr=b&sp=r&sig=BZ2gBfZnr2%2Bi62lU7Tt6Ocp2Lv%2BDmUpCITKb2LJWo1M%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 07:56 UTC, opbld32 commented
Docs Build status updates of commit _[9284620](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9284620ac8e106b9224d8ca9a900ce01024e7e15)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) | [Details](#user-content-5c066b4f5509f66da630dc3a06482c68-2e05144c)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5c066b4f5509f66da630dc3a06482c68-2e05144c"></a>
### [api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md)
 - **Line 172, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111120754300228-14926%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T07%3A56%3A24Z&sr=b&sp=r&sig=K6G00g874apqVcCnq6gx7yKGYlvzikOOd%2FCmKDoK3yk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 10:55 UTC, opbld33 commented
Docs Build status updates of commit _[03cebcf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03cebcf676084427f16f3f81a6fc553a6e4d24e2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) | [Details](#user-content-5c066b4f5509f66da630dc3a06482c68-b6026bda)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5c066b4f5509f66da630dc3a06482c68-b6026bda"></a>
### [api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md)
 - **Line 176, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112021053370872-14926%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T10%3A55%3A35Z&sr=b&sp=r&sig=eeFVdkAffLJ1XGRpjBI%2B50T0ibpKziNGDoFfxpMxLiM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-08 05:17 UTC, opbld30 commented
Docs Build status updates of commit _[9e95eeb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e95eebd35ad168b76a6f16cd600b69188ea4351)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) | [Details](#user-content-5c066b4f5509f66da630dc3a06482c68-5775f252)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5c066b4f5509f66da630dc3a06482c68-5775f252"></a>
### [api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md)
 - **Line 176, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112080515086240-14926%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-08T05%3A17%3A35Z&sr=b&sp=r&sig=ZwKgEnr8pdz6VNoB4RjCZ0%2Fzst1StuzX5rfr2HhONZg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 05:29 UTC, opbld33 commented
Docs Build status updates of commit _[f4e2efe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4e2efe608411e67cad80605e743a5e68776ac35)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) | [Details](#user-content-5c066b4f5509f66da630dc3a06482c68-88ccf83c)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5c066b4f5509f66da630dc3a06482c68-88ccf83c"></a>
### [api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md)
 - **Line 176, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112090527543641-14926%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T05%3A29%3A28Z&sr=b&sp=r&sig=NHY6okWDhsmmEJk%2F%2B28DjhrYvhovTRJMr%2Fz5NSaExww%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-11 03:52 UTC, opbld30 commented
Docs Build status updates of commit _[aad9f72](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aad9f72f787a9e22c5b440367b1fa302b7396e11)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) | [Details](#user-content-5c066b4f5509f66da630dc3a06482c68-076cbdc2)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5c066b4f5509f66da630dc3a06482c68-076cbdc2"></a>
### [api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md)
 - **Line 176, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112110349375363-14926%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-11T03%3A52%3A17Z&sr=b&sp=r&sig=vUMCHfnVUfHy17BR6zdqwflvpZytYxoxvFumQv9%2Bdhs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-11 04:23 UTC, angelgolfer-ms commented on api-reference/beta/api/rbacapplication-list-roledefinitions.md
> +- cloud PC
Line 19:
@AshleyYangSZ , is there a specific reason that you changed to lower case 'c' here?
If it's because lines 20-22 all start with lower case, then IMO "Cloud" in "Cloud PC" should remain upper case 'C'. Here, the noun "Cloud PC" is used as an adjective to characterize RBAC providers, and I believe we're indeed referring to Windows 365 Cloud PC, not just "cloud PC" in a generic way, right?

FYI I am going to change this back to upper case 'C'. 
If on the other hand I overlooked your reason and this reference is not limited to Windows 365 Cloud PC RBAC providers, please comment here, and also ping me on Teams for my info. I don't think this should block your doc PR from publishing. We can follow up in the first week of Jan. 2022.

2021-12-11 06:20 UTC, angelgolfer-ms commented on changelog/Microsoft.CloudManagedDesktop.json
> +                {
@AshleyYangSZ , please provide a separate ChangeList record for adding support for each operation (create, update, delete). You can see example 6 in this CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-examples

Consistent Changelist structure will support a richer filtering experience in the future.

2021-12-11 06:36 UTC, angelgolfer-ms commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "Id": "5e030710-8a28-4fb9-a484-c10d15aeb968",
@AshleyYangSZ , this PR also adds support for RoleManagement.Read.All as a permission for the list and get operations. Can you add a ChangeList record for this too?
You can see example 14 in the [changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-examples) CDK topic.

2021-12-11 06:47 UTC, angelgolfer-ms commented on api-reference/beta/api/rbacapplication-post-roledefinitions.md
> +
Line 187: This should say "Create a custom role for a...", not "create the custom role..."

2021-12-11 06:48 UTC, angelgolfer-ms commented on api-reference/beta/api/rbacapplication-post-roledefinitions.md
> +  "description": "A example custom role",
Line 201: "An example custom role", not "a example..."

2021-12-11 06:48 UTC, angelgolfer-ms commented on api-reference/beta/api/rbacapplication-post-roledefinitions.md
> +  "description": "A example custom role",
Same in line 234.

2021-12-11 06:59 UTC, angelgolfer-ms commented on api-reference/beta/api/rbacapplication-post-roledefinitions.md
> +
@AshleyYangSZ , in the "HTTP request" section, after line 52, please add the syntax for Cloud PC.

2021-12-11 07:04 UTC, angelgolfer-ms commented on api-reference/beta/api/unifiedroledefinition-delete.md
> +
@AshleyYangSZ , after line 52, please add a syntax line for Cloud PC as well.

2021-12-11 07:07 UTC, angelgolfer-ms commented on api-reference/beta/api/unifiedroledefinition-delete.md
Lines 80 and 139:
@AshleyYangSZ ,
FYI I changed the title to be: "## Example 1: Delete a **unifiedRoleDefinition** resource for a directory provider". 

Can you do the same for line 139 as well please?

2021-12-11 07:08 UTC, angelgolfer-ms commented on api-reference/beta/api/unifiedroledefinition-delete.md
Never mind, I'll do this one as well.
Just remember, there should be a space between "Example" and the example number, and use an infinitive without to, not second person singular, for the verb that starts the title (in this case, the verb is "delete").

2021-12-11 07:23 UTC, angelgolfer-ms commented on api-reference/beta/api/unifiedroledefinition-update.md
> +
@AshleyYangSZ , after line 54, please add the syntax for Cloud PC.

2021-12-11 07:25 UTC, angelgolfer-ms commented on api-reference/beta/api/unifiedroledefinition-update.md
> +## Example1: Updates a **unifiedRoleDefinition** for a directory provider
@AshleyYangSZ , please see my comments in the "post" operation topic and make the same fixes to the example titles in lines 94 and 171.

2021-12-11 07:28 UTC, angelgolfer-ms requested changes
Hi @AshleyYangSZ , please see my comments in this PR.
As I will start to be OOF next week, please continue to work with @isvargasmsft to complete this PR. Thanks both!

2021-12-11 07:31 UTC, opbld33 commented
Docs Build status updates of commit _[6b4a432](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b4a43279294ed744394f96d303c5dce1df5307e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) | [Details](#user-content-5c066b4f5509f66da630dc3a06482c68-090f8b13)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5c066b4f5509f66da630dc3a06482c68-090f8b13"></a>
### [api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md)
 - **Line 176, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112110730224722-14926%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-11T07%3A31%3A53Z&sr=b&sp=r&sig=MJI2gU0jMVRm%2Frzg%2F1kO0cUHCLEl8k4cJG4Pe8o%2Fz8U%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-13 11:08 UTC, AshleyYangSZ commented on api-reference/beta/api/rbacapplication-list-roledefinitions.md
> +- cloud PC
Agree with your reason and I'm totally fine with changing it to upper case. Thanks for details.

2021-12-13 11:32 UTC, opbld34 commented
Docs Build status updates of commit _[0ba4623](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ba46231ecf0444e34f20499fc63e1c9ee888b59)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) | [Details](#user-content-5c066b4f5509f66da630dc3a06482c68-a4dcd3c9)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5c066b4f5509f66da630dc3a06482c68-a4dcd3c9"></a>
### [api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md)
 - **Line 182, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112131129579280-14926%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-13T11%3A32%3A30Z&sr=b&sp=r&sig=%2BADuStiQ%2BWIV6qdLO8KoFK243QYIIky4lkGf464l0vI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-13 15:21 UTC, opbld31 commented
Docs Build status updates of commit _[3f45cfb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f45cfb71ab807fbb1a4c757d7095010924c90cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-14926) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/CPCRBAC/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112131518006508-14926%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-13T15%3A21%3A35Z&sr=b&sp=r&sig=%2F1iUlM1gL3cnnPjAdgnXAj6Py9IjI810x6jxUDLqNUE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-13 15:48 UTC, isvargasmsft approved these changes

2021-12-14 22:31 UTC, merged