Updates to app object around certification property
microsoftgraph/microsoft-graph-docs pull request #14932
Opened 2021-11-12 20:24 UTC by arpitha-dhanapathi

1. application resource type: Update the properties list with 'certification' resource
2. create a net new .md for certification: https://docs.microsoft.com/en-us/graph/api/resources/certification
3. application-get.md: update the response in the example (with both verifiedPublisher and certification)

Code PR #: 5335990

2021-11-12 20:24 UTC, opbld30 commented
Docs Build status updates of commit _[00e30b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/00e30b66673942c3b3cf6273250c34f6b3d69c77)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c3b43e18)

<a id="c3b43e18"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111122024073326-14932%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T20%3A24%3A20Z&sr=b&sp=r&sig=uZl0XZb852S0s3rLB0cf70KwJygNnqHrWqRXCt%2BMWHE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 21:30 UTC, opbld31 commented
Docs Build status updates of commit _[92e8668](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92e8668aed6c0e9e27579a33f63d02471b11670c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3e64ae3b)

<a id="3e64ae3b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111122130119422-14932%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T21%3A30%3A39Z&sr=b&sp=r&sig=Fm6iUXwmOa1Vul7yH1KR%2FdmNYjJEGExb6xbq%2B0kih88%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 21:32 UTC, opbld33 commented
Docs Build status updates of commit _[668e715](https://github.com/microsoftgraph/microsoft-graph-docs/commits/668e715266284bdf01c9c62a7b9c32c44b0e9689)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-df209b45)

<a id="df209b45"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111122131482352-14932%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T21%3A32%3A10Z&sr=b&sp=r&sig=gn168JGw50AxUa%2Bj0g9kExkDdLPEH1ygIoNOkn9ZUhU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 21:39 UTC, opbld32 commented
Docs Build status updates of commit _[f64f4d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f64f4d4c082beb1ad66c152d855360702f52febb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8de3d9e6)

<a id="8de3d9e6"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111122138528696-14932%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T21%3A39%3A15Z&sr=b&sp=r&sig=o3RI2flbHRzlmjyVom05ybNM7Nc7IkCVARir7nVVAFo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 22:35 UTC, opbld33 commented
Docs Build status updates of commit _[7a909b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a909b8841fe7932f2b071aacae7d98a8033732b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/certification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/certification.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/certification?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) | [Details](#user-content-349755c69e8055331568f09e8b20b651-e10eba66)
[api-reference/beta/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |

<a id="349755c69e8055331568f09e8b20b651-e10eba66"></a>
### [api-reference/beta/resources/certification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/certification.md)
 - **Line 7, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'ardhanap' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111122233394787-14932%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T22%3A35%3A15Z&sr=b&sp=r&sig=Ri3QnRJGTzHbHOnOowJnWl4wCTco9rcHitt8L%2FWPowM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 23:01 UTC, opbld32 commented
Docs Build status updates of commit _[c76b7b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c76b7b47abcd92a9afb2d5dd81c4a14fcc60148b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/certification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/certification?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111122258257040-14932%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T23%3A01%3A36Z&sr=b&sp=r&sig=ehpYAio2geEso1PR%2BNkVWaY1klf0MGTtVMDqm%2BClKt0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 13:22 UTC, psignoret reviewed
Is this also exposed on servicePrincipal, or is that coming in a separate PR?

2021-11-17 13:22 UTC, psignoret commented on api-reference/beta/api/application-get.md
> +           "certificationDetailsUrl": "https://docs.microsoft.com/en-us/microsoft-365-app-certification/forward/azure/631a96bc-a705-4eda-9f99-fdaf9f54f6a2"
I assume the URL which will be included is the locale-agnostic URL, right?

```suggestion
           "certificationDetailsUrl": "https://docs.microsoft.com/microsoft-365-app-certification/forward/azure/631a96bc-a705-4eda-9f99-fdaf9f54f6a2"
```

2021-11-17 13:22 UTC, psignoret commented on api-reference/beta/resources/certification.md
> +Represents the certification of an [application](application.md). For more information, see [M365 App Compliance Program](/microsoft-365-app-certification/docs/enterprise-app-certification-guide). Th
```suggestion
Represents the certification details of an [application](application.md). For more information, see [Microsoft 365 App Compliance Program](/microsoft-365-app-certification/docs/enterprise-app-certification-guide). The certification property of an application is read-only, and can't be manually set. It is updated when the application is certified through the Microsoft 365 App Compliance Program. 
```

2021-11-17 18:31 UTC, opbld32 commented
Docs Build status updates of commit _[ec8cda1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec8cda1b94c94a1c275ec0aeb6d3b527465d672c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/certification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/certification?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111171829347026-14932%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T18%3A31%3A15Z&sr=b&sp=r&sig=VP2VCONm2yO5QbtPpzbeBIAHrd4kD0KJBXCG2YuDz6M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 18:33 UTC, opbld34 commented
Docs Build status updates of commit _[3044839](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3044839f7e8c1bb2fa33375fb2eee6f8593fc112)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/certification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/certification?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111171829534856-14932%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T18%3A33%3A04Z&sr=b&sp=r&sig=af8aOVzY9EUP%2BHUvL5oL4Xpv6QI%2BhNw5aCtu%2FYRxu4Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-19 23:54 UTC, opbld32 commented
Docs Build status updates of commit _[e777ad2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e777ad2b1bf3fbed0d1cd11b1aaf04776779a35e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/certification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/certification?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111192352385019-14932%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-20T23%3A54%3A25Z&sr=b&sp=r&sig=Nr6OHb4rMZMs%2Fvv97opDa7LCxoADTpC716xxpzIXir8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-20 01:48 UTC, Lauragra requested changes
Because this is an API-level change, we'll need an update to the changelog to list the new property and resource. Otherwise looks good!

[Arpitha] - Laura, I don't see a way to direct reply to this comment..hence editing this one in-place. I added updates to the changelog. Please review and approve. Thanks!

2021-11-20 01:49 UTC, opbld33 commented
Docs Build status updates of commit _[2e6413c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e6413cf62ed6184f216c145c122ad3edbe11832)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/certification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/certification?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111200148032171-14932%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-21T01%3A49%3A32Z&sr=b&sp=r&sig=QAkiF%2BDWFgZJu6mc6eMaakMr2X6t1MSRYMP3bVcztUY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-22 19:02 UTC, opbld33 commented
Docs Build status updates of commit _[6689a26](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6689a266ae85db3c14ae1bd978daa801ac103832)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/certification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/certification?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111221900165293-14932%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-23T19%3A02%3A06Z&sr=b&sp=r&sig=TapQCaZp66rfbulMN8h5B0GG6SGq8ipdpM27R%2B5mdaw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-22 19:44 UTC, arpitha-dhanapathi reviewed
Added updates to the changelog

2021-12-01 22:57 UTC, arpitha-dhanapathi commented
Hi Laura - 'content review in progress' label can be removed. I have addressed your inputs. Thanks

2021-12-02 03:40 UTC, opbld31 commented
Docs Build status updates of commit _[85e9e2f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85e9e2fd5fd8a047223d391bd2d39ee7f647f06d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/certification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/certification?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112020339005929-14932%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T03%3A40%3A52Z&sr=b&sp=r&sig=ef%2BhgSlIGZVEj6IeLBmlmgY4TYWzbzVSRLDtRs%2BSxeo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 03:47 UTC, Lauragra approved these changes

2021-12-02 03:49 UTC, opbld32 commented
Docs Build status updates of commit _[8797fb0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8797fb0f60732bb30d1814833990041bd64a659a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[api-reference/beta/resources/certification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/api-reference/beta/resources/certification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/certification?view=graph-rest-beta&branch=pr-en-us-14932) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ardhanap-M365AppObject/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112020347317232-14932%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T03%3A49%3A21Z&sr=b&sp=r&sig=pnHs5pIcnt3%2FZv1LLzagVl44sWam5NcPc5YqpLXKeBk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 03:56 UTC, merged

2023-03-17 09:27 UTC, FaithOmbongi commented
The changes are live. Removing the changes requested label to avoid unactionable notifications. Might need to tweak the bot a bit.