Add device management APIs and resources.
microsoftgraph/microsoft-graph-docs pull request #14939
Opened 2021-11-15 08:11 UTC by adsrivastava2

2021-11-15 08:12 UTC, opbld33 commented
Docs Build status updates of commit _[8127c90](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8127c90778321a19478b232c63c2649d3f1351df)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list-operations?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-1d544ae5180a9d6a456fa4b5e7912128-cbdebb96)
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdevice?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-6e206fd0d8bfb93feba065b98cd68fc4-cbdebb96)
[api-reference/beta/resources/teamworkdeviceactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdeviceactivity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdeviceactivity?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-960528333c8fbefcdbb62475697205fb-cbdebb96)
[api-reference/beta/resources/teamworkdeviceconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdeviceconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdeviceconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-3a012d15965ee6c860f91a18da01c2fc-cbdebb96)
[api-reference/beta/resources/teamworkdevicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdevicehealth?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-b3234924a850245848b573398313799c-cbdebb96)
[api-reference/beta/resources/teamworkdeviceoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdeviceoperation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdeviceoperation?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-7c34065d3eaa11d3f260b794d0a94f7a-cbdebb96)
[api-reference/beta/api/ediscovery-case-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/ediscovery-case-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-case-list-operations?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-c8a6196d7902829e368077cafecfbabb-cbdebb96)
[api-reference/beta/api/teamwork-list-devices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamwork-list-devices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-devices?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (g [...]

2021-11-15 08:21 UTC, opbld34 commented
Docs Build status updates of commit _[720d247](https://github.com/microsoftgraph/microsoft-graph-docs/commits/720d247098aa8f36e1c06703d133837ffe596c1d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list-operations?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-1d544ae5180a9d6a456fa4b5e7912128-8fd256b2)
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdevice?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-6e206fd0d8bfb93feba065b98cd68fc4-8fd256b2)
[api-reference/beta/resources/teamworkdeviceactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdeviceactivity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdeviceactivity?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-960528333c8fbefcdbb62475697205fb-8fd256b2)
[api-reference/beta/resources/teamworkdeviceconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdeviceconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdeviceconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-3a012d15965ee6c860f91a18da01c2fc-8fd256b2)
[api-reference/beta/resources/teamworkdevicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdevicehealth?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-b3234924a850245848b573398313799c-8fd256b2)
[api-reference/beta/resources/teamworkdeviceoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdeviceoperation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdeviceoperation?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-7c34065d3eaa11d3f260b794d0a94f7a-8fd256b2)
[api-reference/beta/api/ediscovery-case-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/ediscovery-case-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-case-list-operations?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-c8a6196d7902829e368077cafecfbabb-8fd256b2)
[api-reference/beta/api/teamwork-list-devices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamwork-list-devices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-devices?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (g [...]

2021-11-15 19:20 UTC, opbld33 commented
Docs Build status updates of commit _[f40ca0a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f40ca0a9e22496ac636ff1b00cf802a1f76205c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamworkdeviceconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdeviceconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdeviceconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-3a012d15965ee6c860f91a18da01c2fc-653e20f0)
[api-reference/beta/api/teamwork-list-devices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamwork-list-devices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-devices?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list-operations?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_chec [...]

2021-11-15 19:28 UTC, opbld31 commented
Docs Build status updates of commit _[816b473](https://github.com/microsoftgraph/microsoft-graph-docs/commits/816b4737ab92dc10037f15be7946d57003c76466)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamwork-list-devices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamwork-list-devices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-devices?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list-operations?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://revi [...]

2021-11-15 20:49 UTC, opbld32 commented
Docs Build status updates of commit _[39939f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39939f7404ec078e550ebcd1a35d9483c141ff02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamwork-list-devices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamwork-list-devices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-devices?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list-operations?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.co [...]

2021-11-17 15:12 UTC, opbld34 commented
Docs Build status updates of commit _[ffbb140](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ffbb140612e5274414ff932b05c311a54339f124)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-f2c0daa4844a83424af0052bdd430814-cfa15cbc)
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdevice?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-6e206fd0d8bfb93feba065b98cd68fc4-cfa15cbc)
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api- [...]

2021-11-17 17:48 UTC, opbld32 commented
Docs Build status updates of commit _[eb3d674](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb3d674fc8fbe7366ebdf5880e9532aa3e89a627)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [...]

2021-11-22 07:13 UTC, opbld30 commented
Docs Build status updates of commit _[754dba9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/754dba915f646c1b9be7c0740bc87cb46c2947f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [...]

2021-11-23 09:22 UTC, harshnat reviewed
Please add changelog for these doc changes.
https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog

2021-11-23 09:28 UTC, harshnat commented
Please update toc file to include all the new api references. 
https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml

2021-11-30 10:56 UTC, opbld33 commented
Docs Build status updates of commit _[b808da3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b808da342c9caa4613537d48882b33341d51fc60)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-909f8065)
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [Vi [...]

2021-11-30 11:01 UTC, opbld34 commented
Docs Build status updates of commit _[edae371](https://github.com/microsoftgraph/microsoft-graph-docs/commits/edae37105f4e4b14b0e941ad3a83341790bebbc3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [...]

2021-12-01 11:48 UTC, mankadnandan approved these changes

2021-12-01 12:23 UTC, harshnat approved these changes

2021-12-01 19:14 UTC, opbld33 commented
Docs Build status updates of commit _[d8c2273](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8c2273e54e4ea8cb897c42a7557944faa6030e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [...]

2021-12-07 06:48 UTC, opbld31 commented
Docs Build status updates of commit _[319e780](https://github.com/microsoftgraph/microsoft-graph-docs/commits/319e780ab809c3e7770e42b75e0a677249963b3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [...]

2021-12-17 17:24 UTC, isvargasmsft commented
@JarbasHorst cam you take a look at this one, please?

@adsrivastava2, would you be so kind to resolve the conflicts in this PR, please?

2021-12-18 20:10 UTC, opbld32 commented
Docs Build status updates of commit _[8e7588b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e7588befa7e9a06ea6a476d8e8570dc8d763d76)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [...]

2021-12-18 20:17 UTC, opbld30 commented
Docs Build status updates of commit _[e5e30f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e5e30f49a509796989879a9db77911df3cd42830)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [...]

2021-12-21 21:50 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-list.md
> +description: "Get the list of all Teams devices provisioned for the tenant."
For clarity, please replace the first appearance of "Teams" with "Microsoft Teams". Please, apply this change also to line 15.

2021-12-21 21:50 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-list.md
> +This method supports the `$filter` (**deviceType**, **hardwareDetail/uniqueId** and **currentUser/id** properties), `$top`, `$select`, `$skipToken` [OData query parameters](/graph/query-parameters) t
Please, add "and" before `$skipToken`.

2021-12-21 21:50 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-list.md
> +| Server-side pagination |     ✓     | `@odata.nextLink`                      | Currently we are sending continuation token only in list request. |
Please, avoid using gerunds where possible; in this case, you can change "sending" to "send". In general, I recommend you to rephrase this sentence. Suggested revision:

- Currently, we send the continuation token only in requests that return a list of \[teamworkDevices\](../resources/teamworkdevice.md).

2021-12-21 21:50 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-list.md
> +| Filter                 |     ✓     | `/devices?$filter=deviceType eq 'TeamsRoom'` | Filter device based on device category |
For clarity, please

- replace the first appearance of "device" with "devices"
- add "the" before the second appearance of "device"
- add a period to the end of this sentence

2021-12-21 21:50 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-list.md
> +| Filter                 |     ✓     | `/devices?$filter=hardwareDetail/uniqueId eq 'value'` | Filter device based on assigned uniqueId to device. |
For clarity, please rephrase this sentence:

- Filter devices based on the \*\*uniqueId\*\* assigned to a device.

2021-12-21 21:50 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-list.md
> +| Filter                 |     ✓     | `/devices?$filter=currentUser/id eq 'value'` |  Filter device based on device logged in user.|
For clarity, please rephrase this sentence:

- Filter devices based on the signed-in user on a device.

2021-12-21 21:50 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-list.md
> +| Page limit                 |     ✓     | `/devices?$top=10` | Get devices with page size 10. Default page limit is 20. Max page limit is 50. |
Please, add "a" before "page" and add "of" after "size" => ...with a page size of 10...

2021-12-21 21:50 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-list.md
> +If successful, this method returns a `200 OK` response code and a collection of [teamworkDevice](../resources/teamworkdevice.md) objects in the response body. The API supports pagination with a defau
For clarity, I recommend you to replace "The API" with "This API". In general, I recommend you to remove the second sentence because the information is already available in the Supported query patterns section =>

... on of [teamworkDevice](../resources/teamworkdevice.md) objects in the response body. ~~The API supports pagination with a default limit of 20 devices per request.~~

2021-12-21 21:50 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-list.md
> +  "@odata.type": "Collection(microsoft.graph.teamworkDevice)"
Please, replace "@odata.type": "Collection(microsoft.graph.teamworkDevice)" with "@odata.type": "microsoft.graph.teamworkDevice" and add the property: "isCollection": true.

Please, apply this change also here:

- api-reference/beta/api/teamworkdeviceoperation-list.md

2021-12-21 21:50 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-restart.md
> +description: "Restart the specified device. "
Please, remove the empty space after the period.

2021-12-21 21:50 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-restart.md
> +Restarting is an async operation. A device is restarted once the async operation completes successfully, which may occur subsequent to a response from this API.
The description for an API topic should start with an imperative verb. In this case, I recommend you to replace "Restarting is an async operation." with

- Restart the specified \[teamworkDevice\](../resources/teamworkdevice.md) asynchronously...

2021-12-21 21:50 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-restart.md
> +This method also returns a `409 Conflict` response code, if the operation is already in queued state.
Please, remove the comma.

2021-12-21 21:50 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-restart.md
> +POST https://graph.microsoft.com/beta/teamwork/devices/{teamworkDeviceId}/restart
For clarity, please replace the placeholder {teamworkDeviceId} with a real example. Please, apply this change also to line 74 => Location: /teamwork/devices({teamworkDeviceId})/operations({opId})

Please, apply these changes also here:

- api-reference/beta/api/teamworkdevice-rundiagnostics.md

2021-12-22 15:14 UTC, isvargasmsft requested changes
Please review Jarbas's comments.

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdeviceconfiguration-get.md
> +|Delegated (personal Microsoft account)|Not Supported.|
Supported doesn't need to be capitalized.

Please, apply this change also here:

- api-reference/beta/api/teamworkdevicehealth-get.md
- api-reference/beta/api/teamworkdeviceoperation-list.md

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevicehealth-get.md
> +description: "Get the health details of the device."
For clarity, please replace "the device" with "a device".

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevicehealth-get.md
> +Get the health details of a device. [TeamworkDeviceHealth](../resources/teamworkdevicehealth.md) is calculated based on device configuration and other device parameters.
1) Please, add "The" before "**t**eamworkDeviceHealth". => The [teamworkDeviceHealth]... 

2) Please, add "the" before device => ...based on the device configuration...

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdeviceoperation-get.md
> +Get the details of an async long-running device [teamworkDeviceOperation](../resources/teamworkdeviceoperation.md).
1) Please, add a comma after async. 

2) For clarity, I think the word "devide" should be remove from this sentence.

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdeviceoperation-list.md
> +This method supports the `$top`, `$select`, `$skipToken` [OData query parameters](/graph/query-parameters) to help customize the response.
Please, add "and" before `$skipToken`

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdeviceoperation-list.md
> +| Server-side pagination |     ✓     | `@odata.nextLink`                      | Currently we are sending continuation token only in list request. |
Please, avoid using gerunds where possible; in this case, you can change "sending" to "send". In general, I recommend you to rephrase this sentence. Suggested revision:

- Currently, we send the continuation token only in requests that return a list of \[teamworkDeviceOperations\](../resources/teamworkdeviceoperation.md).

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdeviceoperation-list.md
> +| Page limit                 |     ✓     | `/devices({deviceId})/operations?$top=10'` | Get operations for a device with page size 10. Default page limit is 20. Max page limit is 50. |
Please, add "a" before "page" and add "of" after "size" => ...with a page size of 10...

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkaccountconfiguration.md
> +description: "Device Teams client account configuration details"
For clarity, I recommend you to rephrase this sentence. Suggested revision:

- Represents the details of the account configuration for a device in Microsoft Teams.

Please, apply this change also to line 16.

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkaccountconfiguration.md
> +These details are only available for Teams Room devices.
Please, replace "These details" with "The details provided".

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkaccountconfiguration.md
> +|onPremisesCalendarSyncConfiguration|[teamworkOnPremisesCalendarSyncConfiguration](../resources/teamworkonpremisescalendarsyncconfiguration.md)|Details of account used to sync calendar.|
Please, add "the" before "account" and "calendar".

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkactiveperipherals.md
> +description: "Active peripherals attached to a device."
For consistency, please start this description with "Represents...".

Please, apply this change also to line 16.

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkcameraconfiguration.md
> +description: "Details of camera configuration of a device."
For consistency, please start this description with "Represents...". In general, I recommend the following revision:

- "Represents the details of the camera..."

Please, apply this change also to line 16.

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkcameraconfiguration.md
> +|contentCameraConfiguration|[teamworkContentCameraConfiguration](../resources/teamworkcontentcameraconfiguration.md)|Configuration for content camera.|
Please, add "the" before "configuration" and "content".

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkcameraconfiguration.md
> +|defaultContentCamera|[teamworkPeripheral](../resources/teamworkperipheral.md)|Info for the configured content camera.|
Please, replace "info" with "information".

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkconfiguredperipheral.md
> +description: "Details of configured peripheral of a device."
For consistency, please start this description with "Represents...". In general, I recommend the following revision:

- "Represents the details of the configured..."

Please, apply this change also to line 16.

2021-12-22 22:58 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkconfiguredperipheral.md
> +|isOptional|Boolean|True if current peripheral is optional. Also used to calculate health state for the device.|
1) Please, add backticks to True => \`True\` 

2) Please, add "the" before "current"

3) For clarity, I recommend you to rephrase the second sentence => This property is also used to calculate the health state for the device.

2022-01-02 18:05 UTC, adsrivastava2 commented on api-reference/beta/api/teamworkdevice-rundiagnostics.md
> +After the POST diagnostics operation returns, you need to GET the [teamworkDeviceOperation](../resources/teamworkDeviceOperation.md)
Updated.

2022-01-02 20:18 UTC, opbld34 commented
Docs Build status updates of commit _[70779a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70779a9c13c3ca24b496303f67b859fdea74e26b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-014c3412)
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [Vi [...]

2022-01-02 20:50 UTC, adsrivastava2 commented on api-reference/beta/api/teamworkdevice-get.md
> +>**Note:** API requirements under the `/beta` version are subject to change. Licensing or payment requirements may apply for this API when made available for production use.
Regarding adding the reference link to "Licensing or payment requirements", The current doc is related to model A and model B disclaimer, and is mostly based on chat APIs.
We have not finalized on the details regarding payments and license, and hence have not updated the Licensing and payment doc.

For now we only want to highlight this point to the user that licensing and payment may be required.
Should I still add the reference to this page [https://docs.microsoft.com/en-us/graph/teams-licenses] teams-licenses ?

2022-01-02 21:55 UTC, opbld30 commented
Docs Build status updates of commit _[cabdfbd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cabdfbddeccb0e829c0d5f0095e0269b9c283bab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a8ba4695)
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [Vi [...]

2022-01-02 22:00 UTC, opbld31 commented
Docs Build status updates of commit _[b5c4ec2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5c4ec2ffb40d2515bcf3aa765633ef0c506872a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [...]

2022-01-03 16:17 UTC, adsrivastava2 commented
@JarbasHorst Kindly re review.

2022-01-03 16:21 UTC, opbld31 commented
Docs Build status updates of commit _[b5c4ec2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5c4ec2ffb40d2515bcf3aa765633ef0c506872a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [...]

2022-01-04 22:31 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkconfiguredperipheral.md
> +|peripheral|[teamworkPeripheral](../resources/teamworkperipheral.md)|More information about the peripheral.|
For clarity, please replace the description "More information about the peripheral" with "Details about the peripherals attached to the device.".

2022-01-04 22:31 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkconnection.md
> +description: "Connection status infromation."
For consistency, please start this description with "Represents...". Also for clarity, I recommend you to rephrase this sentence:

- Represents the details about the connection status of a device and its peripherals.

Please, apply this change also to line 16.

2022-01-04 22:31 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkconnection.md
> +This is helpful in calculating device health.
Please, avoid using gerunds where possible. Also for clarity, I recommend you to rephrase this sentence. Suggested revision:

- The connection status is useful when you calculate the device health.

2022-01-04 22:31 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkconnection.md
> +|connectionStatus|[teamworkConnectionStatus](teamworkconnectionstatus.md)|Enum indicating whether component/peripheral is connected/disconnected or its state is unknown. The possible values are: `unk
1) Please, avoid using gerunds where possible; in this case you can rephrase "indicating" with that "indicates".

2) Please, add "a" before "component".

2022-01-04 22:31 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkconnection.md
> +|lastModifiedDateTime|DateTimeOffset|Time at which the state was last changed. i.e. Indicates connected since when state is connected and disconnected since when state is disconnected.|
Please, avoid non-English words or phrases; in this case please replace "i.e." with "For example, ". For readability and consistency, I recommend you to rephrase this sentence. Suggested revision:

- For example, indicates \_connected since\_ when the state is \`connected\` and \_disconnected since\_ when the state is \`disconnected\`.

2022-01-04 22:31 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkconnectionstatus.md
> +description: "Describes the connection status for device peripheral."
For readability, please replace "for device peripheral" with "of a peripheral device".

Please, use the same sentence in line 16.

2022-01-04 22:31 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkconnectionstatus.md
> +| Member | Value| Description |
Please, add the unknownFutureValue member to this table. For consistency and clarity, please use "Evolvable enumeration sentinel value. Do not use." as the description of the unknownFutureValue enum member.

2022-01-04 22:31 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkcontentcameraconfiguration.md
> +description: "Details of content camera configuration,"
For clarity, please replace "Details of content camera configuration," with

- Represents the details about the configuration for a content camera.

Please, use the same description in line 16.

2022-01-04 22:31 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkcontentcameraconfiguration.md
> +|isContentCameraInverted|Boolean|True if content camera is inverted.|
Please, add backticks to \`True\`. Also please add "the" before "content". Please apply this change also to lines 22 and 23.

2022-01-04 22:31 UTC, JarbasHorst commented
Hello @adsrivastava2, I will continue tomorrow with the content review work on this PR.

2022-01-05 22:33 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdeviceconfiguration.md
> +|softwareVersions|[teamworkDeviceSoftwareVersions](../resources/teamworkdevicesoftwareversions.md)|Information related to device software version like: Firmware/OS/TeamsApp/AdminAgent.|
For clarity, please rephrase this sentence:

- Information related to the software version of the device, such as firmware, operating system, Teams client, and admin agent.

2022-01-05 22:33 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdevicehealth.md
> +description: "Device health details."
For clarity and consistency, I recommend you to rephrase this sentence:

- Represents the health details of a device.

2022-01-05 22:33 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdevicehealth.md
> +Details of device health. It is calculated based on device configuration and other device parameters.
1) Please, replace "Details of device health." with:

- Represents the health details of a device.

2) In the second sentence, please add "the" before the first appearance of "device".

2022-01-05 22:33 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdevicehealth.md
> +|connection|[teamworkConnection](../resources/teamworkconnection.md)|ConnectionStatus info.|
For clarity, please rephrase this sentence:

- Information about the connection status.

2022-01-05 22:33 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdevicehealth.md
> +|hardwareHealth|[teamworkHardwareHealth](../resources/teamworkhardwarehealth.md)|Health related to device hardware.|
Please, add "the" before "device".

2022-01-05 22:33 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdevicehealth.md
> +|loginStatus|[teamworkLoginStatus](../resources/teamworkloginstatus.md)|Login status of teams, skype and exchange.|
For clarity, please rephrase this sentence:

- The login status of Teams, Skype, and Exchange.

2022-01-05 22:33 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdevicehealth.md
> +|peripheralsHealth|[teamworkPeripheralsHealth](../resources/teamworkperipheralshealth.md)|Peripherals health-related info like speaker health, microphone health etc.|
For clarity and consistency, please rephrase this sentence:

- Health details about all peripherals (for example, speaker and microphone) attached to a device.

2022-01-05 22:33 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdevicehealth.md
> +|softwareUpdateHealth|[teamworkSoftwareUpdateHealth](../resources/teamworksoftwareupdatehealth.md)|Software updates available.|
For clarity, please add "for the device" after "available".

2022-01-06 17:15 UTC, isvargasmsft commented on changelog/Microsoft.Teams.Core.json
> +          "Target": "teamwork"
ApiChange value should be Relationship. Please revise accordingly.

2022-01-06 17:57 UTC, isvargasmsft commented on api-reference/beta/resources/teamworkdevice.md
> +|[List operations](../api/teamworkdeviceoperation-list.md)|[teamworkDeviceOperation](../resources/teamworkdeviceoperation.md) collection|Get the teamworkDeviceOperation resources from the operations
We noticed that in addition to the operations navigation property, there are other nav properties (current user, configuration, health, activity) associated to this resource type. Aren't we creating LIST operations for these navigation properties?

2022-01-06 22:22 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdisplayscreenconfiguration.md
> +description: "Details of display screen configuration."
For clarity and consistency, please rephrase this sentence:

- Represents the details about the display screen configuration for a device.

Please, use the same description in line 16; however, in case of line 16, please add a reference link to device. => ...[teamworkDevice]

2022-01-06 22:22 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdisplayscreenconfiguration.md
> +|backlightBrightness|Int32|Brightness level on the device (0-100). Not Applicable for Teams Room Devices.|
Please, add "The" before "brightness".

2022-01-06 22:22 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdisplayscreenconfiguration.md
> +|isHighContrastEnabled|Boolean|True if high contrast mode is enabled. Not Applicable for Teams Room Devices.|
Please, add backticks to "True". Same for line 24.

2022-01-06 22:22 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdisplayscreenconfiguration.md
> +|screensaverTimeout|Duration|Screensaver Timeout from 30 to 3600 secs. Not Applicable for Teams Room Devices.|
Please, don't capitalize "timeout".

2022-01-06 22:22 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkfeaturesconfiguration.md
> +description: "Details of device teams client feature configuration."
For clarity and consistency, please rephrase this sentence. Suggested revision:

- Represents the details about the configuration of Microsoft Teams features for a device.

Please, use the same description in line 16.

2022-01-06 22:22 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkfeaturesconfiguration.md
> +|emailToSendLogsAndFeedback|String|Email address to send logs and feedbacks.|
feedbacks => feedback

2022-01-06 22:22 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkfeaturesconfiguration.md
> +|isAutoScreenShareEnabled|Boolean|Ture if autoScreenShared is enabled.|
Ture => True. Please, add backticks to True. Same for line 23, 24, and 25. Is autoScreenShared a property? If yes, please apply bold formatting to autoScreenShared.

2022-01-06 22:22 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkfeaturesconfiguration.md
> +|isBluetoothBeaconingEnabled|Boolean|True if bluetooth beaconing is enabled.|
bluetooth  => Bluetooth

2022-01-06 22:22 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkfeaturesconfiguration.md
> +|isHideMeetingNamesEnabled|Boolean|True if hide meeting names is enabled.|
hide => hiding

2022-01-06 22:22 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkfeaturesconfiguration.md
> +|isSendLogsAndFeedbackEnabled|Boolean|True if send logs and feedback is enabled.|
send => sending

2022-01-06 22:22 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkhardwareconfiguration.md
> +description: "**TODO: Add Description**"
For clarity and consistency, please rephrase this sentence:

- Represents the details about the hardware configuration for a device.


Please, use the same description in line 16; however, in case of line 16, please add a reference link to device => [teamworkDevice]...

2022-01-06 22:22 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkhardwareconfiguration.md
> +|processorModel|String|Device CPU model.|
For clarity, please rephrase this description:

- The CPU model on the device.

2022-01-06 22:22 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkhardwareconfiguration.md
> +|compute|[teamworkPeripheral](../resources/teamworkperipheral.md)|Compute peripheral details.|
Please, provide a better description (more descriptive) for the navigation properties: compute and hdmiIngest.

2022-01-06 22:22 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkhardwaredetail.md
> +description: "Details of device hardware."
For clarity and consistency, please rephrase this sentence:

- Represents the details about the hardware properties of a device.

Please, use the same description in line 16.

2022-01-06 22:22 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkhardwaredetail.md
> +|uniqueId|String|Device unique Id.|
In regular text, please use ID as the abbreviation for identity => Device unique ID. However, for clarify, I recommend you to rephrase this sentence:

- The unique identifier for the device.

2022-01-09 19:47 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkdevice.md
> +|[List operations](../api/teamworkdeviceoperation-list.md)|[teamworkDeviceOperation](../resources/teamworkdeviceoperation.md) collection|Get the teamworkDeviceOperation resources from the operations
No we are not creating List operations for these properties. A device can have only one signed-in user, one device configuration, health and activity detail so the list operation is not feasible here.

2022-01-09 20:17 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkdisplayconfiguration.md
> +|displayCount|Int32|Total number of connected displays including inbuilt display. Applicable only for Teams Room Devices.|
One can have only one inbuilt display.

2022-01-09 20:34 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkfeaturesconfiguration.md
> +|isAutoScreenShareEnabled|Boolean|Ture if autoScreenShared is enabled.|
No autoScreenShared is not a property

2022-01-10 07:33 UTC, opbld34 commented
Docs Build status updates of commit _[0237093](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0237093395eb6b7e0876688333e71e77917ff5a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [...]

2022-01-10 14:50 UTC, isvargasmsft commented on api-reference/beta/resources/teamwork.md
Clarifications required for this resource type:
1. In the api.md file we are adding the nav property "devices" to the entity called **teamwork**. Because this is an entity, it should be present in the beta TOC, yet it is not there. 
2. Checking in the beta metadata, there is 1 entity called teamwork, but it has only 1 navigation property: workforceIntegrations:
<EntityType Name="teamwork" BaseType="graph.entity">
<NavigationProperty Name="workforceIntegrations" Type="Collection(graph.workforceIntegration)" ContainsTarget="true"/>
</EntityType>

In this topic, the pre-existing nav property is called installedApps.

Checking further in the metadata, I discovered the actual name of this entity is **userTeamwork**:
<EntityType Name="userTeamwork" BaseType="graph.entity">
<NavigationProperty Name="installedApps" Type="Collection(graph.userScopeTeamsAppInstallation)" ContainsTarget="true"/>
</EntityType>

Could you please clarify the nature of this resource type and the inconsistencies with the metadata?

We require all entities to be named precisely. In this case, this naming is conflicting with the other resource called teamwork. Please fix the naming accordingly in the titles, file name, and mentions in other topics. 

In addition, since this is an entity, please add it to the toc.

2022-01-10 14:59 UTC, isvargasmsft commented on changelog/Microsoft.Teams.Core.json
> +          "Target": "teamwork"
Again, as shown in the metadata, please call this resource by its actual name: userTeamwork.

2022-01-10 17:41 UTC, isvargasmsft commented on api-reference/beta/resources/teamworkdevicetype.md
> +|unknownFutureValue|10|Evolvable enumeration sentinel value. Do not use.|
We typically document enums in the enums.md file instead of doing so in a separate topic. We use this approach only if there is additional clarification required to explain the members of the enum (description in this table). 

In this case, I don't think the descriptions are providing more information to the users about what each enum means. 

Could you please justify the decision to document this enum in a separate topic? 

Please consult the guidance (3 options) to document enums here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations?anchor=first-option%3A-in-enums.md

First option: in enums.md
Second option: in parent resource topic (teamworkDevice resource type in this case).
Third option: in a separate dedicated enum topic.

2022-01-10 17:59 UTC, isvargasmsft commented on api-reference/beta/resources/teamworkdevicehealthstatus.md
> +|unknownFutureValue|5|Evolvable enumeration sentinel value. Do not use.|
Please provide more detailed descriptions here. Specially for critical and nonUrgent.

2022-01-10 19:25 UTC, isvargasmsft commented on api-reference/beta/resources/teamworkdeviceconfiguration.md
> +|[Get teamworkDeviceConfiguration](../api/teamworkdeviceconfiguration-get.md)|[teamworkDeviceConfiguration](../resources/teamworkdeviceconfiguration.md)|Read the properties and relationships of a [te
According to the api.md file, this resource also supports the Update method. The descriptions says: "Updates the device configuration via long running operation."

Can you clarify this sentence and why is the method not included in this PR?

2022-01-10 20:15 UTC, opbld31 commented
Docs Build status updates of commit _[a9ce2fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a9ce2fa5e05a03878675693f4953cdf092fedf02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [...]

2022-01-10 20:56 UTC, isvargasmsft commented on api-reference/beta/resources/teamworkspeakerconfiguration.md
> +Details of speaker configuration of a device. These details are applicable only for Microsoft Teams Rooms devices.
Lines 3 and 16: These 2 descriptions should match. 

Also, if we are referring to teamworkDevice resource type, please include the reference link.

2022-01-10 21:03 UTC, isvargasmsft commented on api-reference/beta/resources/teamworkdevicehealth.md
> +Represents the health details of a device. It is calculated based on the device configuration and other device parameters.
If this sentence is referring to teamworkDevice resource type, please include the reference link.

2022-01-10 21:08 UTC, isvargasmsft commented on api-reference/beta/api/teamworkdevicehealth-get.md
> +Get the health details of a device. The [TeamworkDeviceHealth](../resources/teamworkdevicehealth.md) is calculated based on the device configuration and other device parameters.
Please add reference link to teamworkDevice resource type.

2022-01-10 21:09 UTC, isvargasmsft commented on api-reference/beta/api/teamworkdevicehealth-get.md
> +Get the health details of a device. The [teamworkDeviceHealth](../resources/teamworkdevicehealth.md) is calculated based on the device configuration and other device parameters.
Please add reference link to teamworkDevice resource type.

2022-01-10 21:10 UTC, opbld34 commented
Docs Build status updates of commit _[1b20c14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b20c142305e788add9681e8f59653ee7adcafe9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [...]

2022-01-10 21:26 UTC, opbld33 commented
Docs Build status updates of commit _[8721696](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8721696b1966e6d015435a864f2437e82b788737)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [...]

2022-01-10 21:52 UTC, opbld32 commented
Docs Build status updates of commit _[8103bea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8103bea34270d5d570dbb94536c2bb160ff3473f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [...]

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkhardwarehealth.md
> +description: "Details of device hardware health."
For clarity and consistency, please rephrase this sentence:

- Represents the details about the hardware health of a device.

Please, use the same description in line 16.

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkhardwareconfiguration.md
> +|hdmiIngest|[teamworkPeripheral](../resources/teamworkperipheral.md)|The product details of HDMI ingest of a device.|
For readability, please replace the first appearance of "of" with "about". Also, please add "the" before "HDMI" => ...details about the HDMI ingest of...

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkhardwarehealth.md
> +|computeHealth|[teamworkPeripheralHealth](../resources/teamworkperipheralhealth.md)|Compute peripheral health info.|
For consistency, please replace the existing description with:

- The system details for a \[teamworkDevice\](../resources/teamworkdevice.md).

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkhardwarehealth.md
> +|hdmiIngestHealth|[teamworkPeripheralHealth](../resources/teamworkperipheralhealth.md)|HDMI Ingest peripheral health info.|
For consistency, please replace the existing description with:

- The product details about the HDMI ingest of a device.

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkloginstatus.md
> +description: "Login status of teams, skype and exchange."
For clarity and consistency, please rephrase this sentence:

Represents the details about the login status of Microsoft Teams, Skype, and Exchange.

Please, use the same description in line 16.

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkloginstatus.md
> +|exchangeConnection|[teamworkConnection](../resources/teamworkconnection.md)|Exchange connection status info.|
For clarity, please rephrase this description:

- Information about the Exchange connection.

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkloginstatus.md
> +|skypeConnection|[teamworkConnection](../resources/teamworkconnection.md)|Skype connection status info.|
For clarity, please rephrase this description:

- Information about the Skype connection.

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkloginstatus.md
> +|teamsConnection|[teamworkConnection](../resources/teamworkconnection.md)|Teams connection status info.|
For clarity, please rephrase this description:

- Information about the Teams connection.

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkmicrophoneconfiguration.md
> +description: "Details of microphone configuration."
For clarity and consistency, please rephrase this sentence:

Represents the details about the configuration of a microphone.

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkmicrophoneconfiguration.md
> +Deatil of microphone configuration. Applicable only for Microsoft Teams Rooms Devices.
For clarity and consistency, please rephrase this sentence:

Represents the details about the configuration of a microphone. Applicable only for Microsoft Teams Rooms devices.

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkmicrophoneconfiguration.md
> +|isMicrophoneOptional|Boolean|True if configured microphone is optional. Used to compute health state if speaker is not optional.|
Please, add backticks to True => \`True\`. Also, please add "the" before "configured", "health", and "speaker". Also, please explain what can be computed; Is it the health state of the device? For example, "...compute the health state of the device if... For clarity, I recommend the following revision:

- \`True\` if the configured microphone is optional. \`False\` if the speaker is not optional and the health state of the device should be computed.

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkmicrophoneconfiguration.md
> +|defaultMicrophone|[teamworkPeripheral](../resources/teamworkperipheral.md)|Info for the deafult microphone.|
For clarity, please rephrase this sentence:

- Information about the default microphone.

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkmicrophoneconfiguration.md
> +|microphones|[teamworkPeripheral](../resources/teamworkperipheral.md) collection|List of all microphones.|
For clarity, please rephrase this sentence:

- A collection of microphones.

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworknetworkconfiguration.md
> +description: "Details of device network configuration."
For clarity and consistency, please rephrase this sentence:

Represents the details about the network configuration of a device.

Please, use the same description in line 16.

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworknetworkconfiguration.md
> +|defaultGateway|String|Default gateway.|
Please, provide a more descriptive description for all properties (except isDhcpEnabled and isPCPortEnabled) in this table.

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworknetworkconfiguration.md
> +|isDhcpEnabled|Boolean|True if DHCP is enabled.|
Please, add backticks to True. Same for line 26.

2022-01-10 22:44 UTC, JarbasHorst commented on api-reference/beta/resources/teamworknetworkconfiguration.md
> +|isPCPortEnabled|Boolean|True if PC Port is enabled.|
Port doesn't need to be capitalized. Also, please add "the" before PC.

2022-01-11 15:17 UTC, isvargasmsft requested changes
Hello @adsrivastava2, 

Thank you for your work in this PR. 

I noticed a few inconsistencies between the api.md, the metadata and this PR. 

For example, the resource userTeamwork (as named in the metadata) is called teamwork in the docs. This is an inconsistency and conflicts with another resource called teamwork. 

In addition, there are some entity topics that doesn't have presence in the TOC. Please take a look and include them. 

Feel free to ping me on the side if you have any questions. 

Isaac

2022-01-11 23:02 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkteamsclientconfiguration.md
> +|featuresConfiguration|[teamworkFeaturesConfiguration](../resources/teamworkfeaturesconfiguration.md)|Teams client feature config details.|
For clarity and consistency, please rephrase this description:

- The configuration of Microsoft Teams client features for a device.

2022-01-11 23:03 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkteamsclientconfiguration.md
> +|accountConfiguration|[teamworkAccountConfiguration](../resources/teamworkaccountconfiguration.md)|Account details used to sync.|
For clarity and consistency, please rephrase this description:

- The account configuration for a device.

For a better revision, please provide more details about "what gets synced".

2022-01-12 22:27 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added support for the delegated and application permission `TeamworkDevice.Read.All` to the read operations of the [teamworkDevice](https://docs.microsoft.com/en-us/graph/ap
For simplicity, you can combine all changelog entries related to "TeamworkDevice.Read.All" into one. In this case, you just need to change this description. Suggested revision:

- Added support for the delegated and application permission \`TeamworkDevice.Read.All\` to the read operations of the \[teamworkDevice\](https://docs.microsoft.com/en-us/graph/api/resources/teamworkdevice?view=graph-rest-beta), \[teamworkDeviceActivity\](https://docs.microsoft.com/en-us/graph/api/resources/teamworkdeviceactivity?view=graph-rest-beta), \[teamworkDeviceConfiguration\](https://docs.microsoft.com/en-us/graph/api/resources/teamworkdeviceconfiguration?view=graph-rest-beta), \[teamworkDeviceHealth\](https://docs.microsoft.com/en-us/graph/api/resources/teamworkdevicehealth?view=graph-rest-beta), and \[teamworkDeviceOperation\](https://docs.microsoft.com/en-us/graph/api/resources/teamworkdeviceoperation?view=graph-rest-beta) resources.


After combining these changelog entries, you can remove the others.

2022-01-12 22:27 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added support for the delegated and application permission `TeamworkDevice.ReadWrite.All` to the read and write operations of the [teamworkDevice](https://docs.microsoft.com
For simplicity, you can combine all changelog entries related to "TeamworkDevice.ReadWrite.All" into one. In this case, you just need to change this description. Suggested revision:

- Added support for the delegated and application permission \`TeamworkDevice.ReadWrite.All\` to the read and write operations of the \[teamworkDevice\](https://docs.microsoft.com/en-us/graph/api/resources/teamworkdevice?view=graph-rest-beta), \[teamworkDeviceActivity\](https://docs.microsoft.com/en-us/graph/api/resources/teamworkdeviceactivity?view=graph-rest-beta), \[teamworkDeviceConfiguration\](https://docs.microsoft.com/en-us/graph/api/resources/teamworkdeviceconfiguration?view=graph-rest-beta), \[teamworkDeviceHealth\](https://docs.microsoft.com/en-us/graph/api/resources/teamworkdevicehealth?view=graph-rest-beta), and \[teamworkDeviceOperation\](https://docs.microsoft.com/en-us/graph/api/resources/teamworkdeviceoperation?view=graph-rest-beta) resources.


After combining these changelog entries, you can remove the others.

2022-01-12 22:27 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the [teamworkAccountConfiguration](https://docs.microsoft.com/en-us/graph/api/resources/teamworkAccountConfiguration?view=graph-rest-beta) resource type.",
GLOBAL: Please, apply this change to all links in all changelog entries in this changelog record.

For consistency, links in Microsoft Graph docs should be provided in lower case format. In this case, please replace this ...docs.microsoft.com/en-us/graph/api/resources/**teamworkAccountConfiguration**?view=graph-rest-beta with ...docs.microsoft.com/en-us/graph/api/resources/**teamworkaccountconfiguration**?view=graph-rest-beta.

2022-01-12 22:27 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +        {
You added a new method (List devices) to the teamwork resource topic. Please, include this change also in this changelog record.

2022-01-13 18:19 UTC, adsrivastava2 commented on api-reference/beta/resources/teamwork.md
Will add the entities in the TOC, regarding the inconsistency, please find below the latest [csdl](Pull request 461161: Update Device Management service Flags - Repos (visualstudio.com)). The device is the part of teamwork resource only, we need to update it appropriately. Have asked Anand who is the owner of the file to fix it.

2022-01-13 18:55 UTC, adsrivastava2 commented on changelog/Microsoft.Teams.Core.json
> +          "Target": "teamwork"
We have to add devices in the resource teamwork only.

2022-01-13 20:43 UTC, opbld33 commented
Docs Build status updates of commit _[f917879](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f917879b1d68b4c3a38a0f57fbc7d9f6499038f4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnectionstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnectionstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnectionstatus?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [...]

2022-01-13 21:10 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-get.md
> +>**Note:** API requirements under the `/beta` version are subject to change. Licensing or payment requirements may apply for this API when made available for production use.
Thanks for the clarification, @adsrivastava2. You are right! Let's keep this sentence as it is.

2022-01-13 22:01 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkdeviceconfiguration.md
> +|[Get teamworkDeviceConfiguration](../api/teamworkdeviceconfiguration-get.md)|[teamworkDeviceConfiguration](../resources/teamworkdeviceconfiguration.md)|Read the properties and relationships of a [te
We are making few changes in the APIs internally and hence have not integrated it to graph. We have dropped this API as of now, once we add this API, will update the doc as well.

2022-01-13 22:18 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdeviceoperation-get.md
> +description: "Get the details of async teamworkDeviceOperation."
For clarity, please add "an" before "teamworkDeviceOperation".

2022-01-13 22:18 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkaccountconfiguration.md
> +description: "Represents the details of the account configuration for a device in Microsoft Teams."
For consistency with your other resource topics, please replace "of" with "about". Please, apply this change also to line 16.

2022-01-13 22:18 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkactiveperipherals.md
> +description: "Represents active peripherals attached to a device."
For clarity and consistency, please add "the details about the" before "activity". Please, apply this change also to line 16.

2022-01-13 22:18 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkcameraconfiguration.md
> +description: "Represents the details of the camera configuration of a device."
For consistency with your other resource topics, please replace "details of " with "details about". Also, please replace "of" after configuration with "for".

Please, apply these changes also to line 16.

2022-01-13 22:18 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkcameraconfiguration.md
> +This is applicable only for Teams Room devices.
For consistency, please replace "Teams Room" with "Microsoft Teams Rooms".

2022-01-13 22:18 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkcameraconfiguration.md
> +|defaultContentCamera|[teamworkPeripheral](../resources/teamworkperipheral.md)|Information for the configured content camera.|
For clarity, please provide a description that is more descriptive.

2022-01-13 22:18 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-list.md
> +Get the list of all Microsoft Teams [teamworkDevices](../resources/teamworkdevice.md) provisioned for the tenant.
For clarity, please replace \[teamworkDevices\](../resources/teamworkdevice.md) with \[devices\](../resources/teamworkdevice.md).

2022-01-13 22:18 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-rundiagnostics.md
> +Run and generate diagnostic logs for the specified device. This API triggers a long-running operation used to generate logs for a device.
For consistency, please replace the first appearance of "device" with \[teamworkDevice\](../resources/teamworkdevice.md).

2022-01-13 22:18 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdeviceoperation-list.md
> +Get a list of the [teamworkDeviceOperations](../resources/teamworkdeviceoperation.md) linked to a device.
For consistency, please replace the first appearance of "device" with \[teamworkDevice\](../resources/teamworkdevice.md).

2022-01-13 23:00 UTC, opbld31 commented
Docs Build status updates of commit _[86433c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/86433c617a8e1fbb0d86dc587c966735c53b5b1a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-14 19:11 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworksoftwarefreshness.md
> +description: "Describes the software freshness of a peripheral."
Moved this to enums.md as per Isaac's comment.

2022-01-14 19:57 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworksupportedclient.md
> +Describes the supported client of a [teamworkaccountconfiguration](teamworkaccountconfiguration.md).
Moved to enums.md

2022-01-14 20:09 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworksystemconfiguration.md
> +|lockPin|String|Lockpin for the device. This is write-only.|
Yes this description is correct. Updating the same.

2022-01-14 20:23 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkdevice.md
> +|[List operations](../api/teamworkdeviceoperation-list.md)|[teamworkDeviceOperation](../resources/teamworkdeviceoperation.md) collection|Get the **teamworkDeviceOperation** resources from the **opera
It is there 
![image](https://user-images.githubusercontent.com/93187816/149580249-961fb7f1-72cd-48f7-a0f1-923fa3e45ed9.png)

2022-01-14 21:34 UTC, opbld32 commented
Docs Build status updates of commit _[daf99a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/daf99a942126fd4ad47f6f1f68b317a2d0af5d20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-14 22:23 UTC, isvargasmsft commented on api-reference/beta/resources/enums.md
> +
enums missing:
teamworkDeviceType
teamworkHardwareDetail
teamworkDeviceHealthStatus
teamworkPeripheral
teamworkDisplayConfiguration
teamworkDisplayScreenConfiguration

2022-01-14 22:39 UTC, isvargasmsft commented on api-reference/beta/resources/teamworkdevice.md
> +|currentUser|[teamworkUserIdentity](../resources/teamworkuseridentity.md)|The signed-in user on the device.|
Line 37: currentUser property should be a relationship, according to the api.md file.

2022-01-14 22:44 UTC, isvargasmsft commented on api-reference/beta/resources/teamworkdevicetype.md
> +# teamworkDeviceType enum type
Is this enum used by other entities or methods? If not, then please document it in the parent topic.

2022-01-17 16:47 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkdevice.md
> +|currentUser|[teamworkUserIdentity](../resources/teamworkuseridentity.md)|The signed-in user on the device.|
In api.md we wanted to have currentUser as a type graph.identity, then it should have been a relationship, but we marked the currentUser as teamworkUserIdentity hence it is not a relationship. This is a miss in api.md file, it should not be a relationship.

2022-01-17 16:48 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkdevicetype.md
> +# teamworkDeviceType enum type
Documenting it in parent i.e teamworkDevice topic.

2022-01-17 16:57 UTC, opbld31 commented
Docs Build status updates of commit _[adbacd8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/adbacd897ab8e43cde063834be055ac2dd7efe68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-17 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdeviceoperation.md
> +|status|String|The current status of the async operation, for example, `Queued`, `Scheduled`, `InProgress`,  `Successful`, `Cancelled`, and `Failed`.|
In line 29, you say that a possible value for status is "Canceled" and not "Cancelled". What is correct in this case?

2022-01-17 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/enums.md
> +|softwareUpdate|3|Update the device software.|
For clarity, please rephrase this description:

- Update a software on the device.

2022-01-17 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdevice.md
> +|teamsRoom|2|Microsoft Teams Rooms are windows IOT based devices designed to extend the meeting experience to the conference room.|
windows IOT => Windows IoT

2022-01-17 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdevice.md
> +|surfaceHub|3|Surface Hub are wall-mounted or roller-stand-mounted devices with interactive whiteboard.|
For consistency, please add "devices" after "Hub".

2022-01-17 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdevice.md
> +|lowCostPhone|7|Low-cost phone devices are cost-effective Microsoft Teams Phones.|
Please, don't capitalize Phones.

2022-01-17 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdevice.md
> +|sip|9|Session Initiation Protocol (SIP) devices which support Teams calls with Microsoft's SIP Gateway.|
For consistency and clarity, please never abbreviate Microsoft and in general don't use Microsoft's. In this case, please rephrase part of this description => "...with the SIP Gateway from Microsoft".

2022-01-17 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdevice.md
> +|teamsDisplay|5|Teams display devices are the evolution of Teams phones. These are a category of all-in-one dedicated Teams devices that feature an ambient touchscreen and a hands-free experience pow
Please, add "devices" after "These"

2022-01-17 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdisplayconfiguration.md
> +|displayCount|Int32|Total number of connected displays, including inbuilt display. Applicable only for Teams Rooms devices.|
Please, add "the" before "inbuilt". Same change also in line 23.

2022-01-17 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdisplayconfiguration.md
> +|isDualDisplayModeEnabled|Boolean|`True` if dual display mode is enabled. If **isDualDisplayModeEnabled** is `true`, then when the content is shared via the HDMI ingest module on the Microsoft Teams
Please, don't capitalize "Front of Room".

2022-01-17 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkloginstatus.md
> +description: "Represents the details about the login status of Microsoft Teams, Skype, and Exchange."
"Skype" => "Skype for Business"

Please, apply this change also to lines 16, 22, and 23.

2022-01-17 22:57 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkloginstatus.md
> +|teamsConnection|[teamworkConnection](../resources/teamworkconnection.md)|Information about the Skype connection.|
Skype should be Teams here.

2022-01-17 23:15 UTC, JarbasHorst commented on api-reference/beta/resources/teamworknetworkconfiguration.md
> +|defaultGateway|String|The default gateway is the path used to pass information when the destination is not known to the device.|
For clarity, please replace "not known" with "unknown".

2022-01-17 23:15 UTC, JarbasHorst commented on api-reference/beta/resources/teamworknetworkconfiguration.md
> +|primaryDns|String|A primary DNS is the first point of contact for a device that translates hostname into an IP address.|
Please, add "the" before "hostname".

2022-01-18 17:53 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkdeviceoperation.md
> +|status|String|The current status of the async operation, for example, `Queued`, `Scheduled`, `InProgress`,  `Successful`, `Cancelled`, and `Failed`.|
Corrected line 29. It should be Cancelled.

2022-01-18 18:08 UTC, opbld33 commented
Docs Build status updates of commit _[c1d64b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1d64b9e76d1f46290e26b22ca350213f8eb2061)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-18 22:05 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkaccountconfiguration.md
> +The details provided are only available for Microsoft Teams Rooms devices.
For consistency, please replace the second sentence with:

- Applicable only for Microsoft Teams Rooms devices.

2022-01-18 22:07 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkaccountconfiguration.md
> +|onPremisesCalendarSyncConfiguration|[teamworkOnPremisesCalendarSyncConfiguration](../resources/teamworkonpremisescalendarsyncconfiguration.md)|Details of the account used to sync the calendar.|
For clarity, I recommend you to just write: "The account used to sync the calendar".

2022-01-18 22:07 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkaccountconfiguration.md
> +|supportedClient|teamworkSupportedClient|Supported Teams client. The possible values are: `unknown`, `skypeDefaultAndTeams`, `teamsDefaultAndSkype`, `skypeOnly`, `teamsOnly`, `unknownFutureValue`.|
For clarity, please add "The" before "supported".

2022-01-18 22:12 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkcameraconfiguration.md
> +|cameras|[teamworkPeripheral](../resources/teamworkperipheral.md) collection|List of connected cameras.|
For clarity, please add "The" before "list".

2022-01-18 22:17 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdatetimeconfiguration.md
> +|officeHoursEndTime|TimeOfDay|The time of the day that the device is turned off.|
For clarity, please replace "that" with "when". Same for line 23.

2022-01-18 22:23 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdevicehealth.md
> +Represents the health details of a [teamworkDevice](../resources/teamworkdevice.md). It is calculated based on the device configuration and other device parameters.
For clarity, please replace "It" with "The device health" => The device health is calculated...

2022-01-18 22:30 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkdisplayconfiguration.md
> +|isDualDisplayModeEnabled|Boolean|`True` if dual display mode is enabled. If **isDualDisplayModeEnabled** is `true`, then when the content is shared via the HDMI ingest module on the Microsoft Teams
For clarity, please rephrase this description:

- ...mode is enabled. If \*\*isDualDisplayModeEnabled\*\* is \`true\`, then the content will be displayed on both front of room screens instead of just the one screen, when it is shared via the HDMI ingest module on the Microsoft Teams Rooms device. Applicable only...

2022-01-18 22:33 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkloginstatus.md
> +description: "Represents the details about the login status of Microsoft Teams, Skype for Business, and Exchange."
For consistency, please add "in a device" after "Exchange".

2022-01-18 22:43 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkmicrophoneconfiguration.md
> +description: "Represents the details about the microphone configuration of a device."
For clarity, please replace "of" with "for". Same for line 16. => ...configuration for a device.

Please, apply these changes also here:

- api-reference/beta/resources/teamworkspeakerconfiguration.md
- api-reference/beta/resources/teamworknetworkconfiguration.md
- api-reference/beta/resources/teamworksystemconfiguration.md

2022-01-18 22:45 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkspeakerconfiguration.md
> +Represents the details about the speaker configuration of a [teamworkDevice](../resources/teamworkdevice.md). These details are applicable only for Microsoft Teams Rooms devices.
For consistency, please replace the second sentence with:

- Applicable only for Microsoft Teams Rooms devices.

2022-01-18 22:48 UTC, JarbasHorst commented on api-reference/beta/resources/teamworksystemconfiguration.md
> +Represents the details about the system configuration of a [teamworkDevice](../resources/teamworkdevice.md). This detail is not applicable for Microsoft Teams Rooms devices.
For consistency, please replace the second sentence with:

- Not applicable for Microsoft Teams Rooms devices.

2022-01-18 22:49 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkteamsclientconfiguration.md
> +description: "Represents the details about the configuration for the Microsoft Teams client."
For consistency, please add "a device" after "client" => ...Teams client of a device.

2022-01-18 22:54 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkcameraconfiguration.md
> +This is applicable only for Microsoft Teams Rooms devices.
For consistency, please replace the second sentence with:

- Applicable only for Microsoft Teams Rooms devices.

2022-01-19 19:25 UTC, opbld32 commented
Docs Build status updates of commit _[88fc5e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88fc5e0b4edb9f3faae20deb89d01fae90558e00)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-19 21:36 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the **devices** relationship to [teamwork](https://docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta) resource.",
Please, add "the" before "[teamwork]".

2022-01-19 21:36 UTC, JarbasHorst commented on api-reference/beta/toc.yml
> +            - name: Get device configuration
For consistency, please, replace "Get device configuration" with "Get".

2022-01-19 21:36 UTC, JarbasHorst commented on api-reference/beta/toc.yml
> +            - name: Get device health
For consistency, please replace "Get device health" with "Get".

2022-01-19 21:36 UTC, JarbasHorst commented on api-reference/beta/toc.yml
> +            - name: Get device operations
For consistency, please, replace "Get device operations" with "Get".

2022-01-19 21:36 UTC, JarbasHorst commented on api-reference/beta/toc.yml
> +            - name: List device operations
For consistency, please, replace "List device operations" with "List".

2022-01-19 21:36 UTC, JarbasHorst commented on api-reference/beta/toc.yml
> +            - name: Get device activity
For consistency, please replace "Get device activity" with "Get".

2022-01-19 21:36 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-list.md
> +| Pattern                | Supported | Syntax                                 | Notes |
All entries in this list are supported. In this case, the "Supported" column doesn't bring relevant information. I recommend you to remove this column.

Please, apply this change also here: 

- api-reference/beta/api/teamworkdeviceoperation-list.md

2022-01-19 21:36 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdevice-list.md
> +| Server-side pagination |     ✓     | `@odata.nextLink`                      | Currently, we send the continuation token only in requests that return a list of [teamworkDevices](../resources/teamwor
For clarity, I recommend you to rephrase this description:

- You will get a continuation token in the response, when a result set spans multiple pages.

Please, apply this change also here: 

- api-reference/beta/api/teamworkdeviceoperation-list.md

2022-01-19 21:36 UTC, JarbasHorst commented on api-reference/beta/api/teamworkdeviceconfiguration-get.md
> +          "smtpAddress": "admin@m365x975529.onmicrosoft.com",
Please use approved fictitious names for domains and display names. For example, m365x975529 isn't an approved fictitious domain. Also, admin@domain.com should be replaced with a valid example. For more details on approved fictitious names, see https://microsoft.sharepoint.com/sites/CELAWeb-Copyrights-Trademarks-And-Patents/SitePages/trademarks-fictitious-names.aspx.

Please, verify your examples and fix the domains that are not valid.

2022-01-20 16:49 UTC, opbld33 commented
Docs Build status updates of commit _[23b5f35](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23b5f3567cd5b1d3d5ce8ecc49b556303af70536)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-20 20:18 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2022-01-20 20:49 UTC, Lauragra commented on api-reference/beta/resources/teamworkdevice.md
> +Represents the details about a device in Microsoft Teams.
Is this description clear enough? I'm not sure what a device "in" Microsoft Teams is. Is this a device that is running Microsoft Teams, or a device that is connected to a Teams call, perhaps?

2022-01-20 20:54 UTC, Lauragra commented on api-reference/beta/api/teamworkdevice-get.md
> +description: "Read the properties and relationships of a device."
In this description, you might want to clarify that the context is a device related to Microsoft Teams? Note that we also have a "device" resource that represents a device as a directory object.

2022-01-20 20:55 UTC, Lauragra commented on api-reference/beta/api/teamworkdevice-get.md
> +Read the properties (for example, **deviceType**, **hardwareDetail**, **activityState**, and **healthStatus**) and relationships of a [teamworkDevice](../resources/teamworkdevice.md).
It might be helpful to provide a definition of what a "teamworkDevice" is; it's not clear to me from the resource description what we mean by that and how it's different than a "device".

2022-01-21 00:36 UTC, Lauragra commented on api-reference/beta/api/teamworkdevice-list.md
> +Get the list of all Microsoft Teams [devices](../resources/teamworkdevice.md) provisioned for a tenant.
Suggested revision: "Get a list of all Microsoft Teams-enabled devices for a tenant."

2022-01-21 00:43 UTC, opbld32 commented
Docs Build status updates of commit _[a528c0b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a528c0b3cf77eb8a3426cad22a439112d0a58567)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 17:26 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkdevice.md
> +Represents the details about a device in Microsoft Teams.
All the devices which have Teams enabled on them, or basically a device running Teams.

2022-01-21 17:39 UTC, opbld34 commented
Docs Build status updates of commit _[fb04968](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb04968beb043e781bde8cc6fa1868aef2896393)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 19:31 UTC, opbld30 commented
Docs Build status updates of commit _[682c9a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/682c9a76dcf57e9beb0c0520fb85dcd0c584b175)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 20:04 UTC, opbld32 commented
Docs Build status updates of commit _[beed355](https://github.com/microsoftgraph/microsoft-graph-docs/commits/beed355732106f65b3de1bad55366ea0a027b927)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 20:29 UTC, opbld30 commented
Docs Build status updates of commit _[9121c4a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9121c4aa0d190c1c7c8c223928cbee63676a4ee5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 20:31 UTC, opbld34 commented
Docs Build status updates of commit _[9121c4a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9121c4aa0d190c1c7c8c223928cbee63676a4ee5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 20:34 UTC, opbld32 commented
Docs Build status updates of commit _[9d193fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d193fd7be1244d32d17942e2d600043e87e2870)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 20:37 UTC, opbld33 commented
Docs Build status updates of commit _[b09a909](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b09a9098a314f017514eeb8cf63cbca4af268646)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 20:40 UTC, opbld32 commented
Docs Build status updates of commit _[b09a909](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b09a9098a314f017514eeb8cf63cbca4af268646)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 20:42 UTC, opbld32 commented
Docs Build status updates of commit _[4b6c181](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b6c18178417dad9de3b171d38d760a61c20298f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 20:44 UTC, opbld31 commented
Docs Build status updates of commit _[be79c63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be79c63a4deeb0973255213fced00fa133ed84fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 20:47 UTC, opbld34 commented
Docs Build status updates of commit _[be79c63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be79c63a4deeb0973255213fced00fa133ed84fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 20:47 UTC, Lauragra commented on api-reference/beta/api/teamworkdeviceoperation-list.md
> +Get a list of the [operations](../resources/teamworkdeviceoperation.md) that are linked to a Microsoft Teams-enabled [device](../resources/teamworkdevice.md).
What do we mean by "linked to"? Would it be more clear to simply say "... that are running on"?

2022-01-21 20:51 UTC, opbld31 commented
Docs Build status updates of commit _[af121d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af121d659ad380b7b40559818dd55352ccd60ee9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 21:04 UTC, Lauragra commented on api-reference/beta/resources/teamwork.md
> +| [List workforceIntegrations](../api/workforceintegration-list.md) | [workforceIntegration](workforceintegration.md) collection | Get the list of **workforceIntegration** objects associated with thi
I'm unclear as to what we mean by "associated with this **teamwork**. Teamwork is a container resource; what is it intended to represent?

2022-01-21 21:05 UTC, Lauragra commented on api-reference/beta/resources/teamwork.md
> +|[List devices](../api/teamworkdevice-list.md)|[teamworkDevice](../resources/teamworkdevice.md) collection|Get the list of all Teams devices provisioned for the tenant.|
This method would be listed in the teamworkDevice resource topic; does it need to be listed here?

2022-01-21 22:04 UTC, Lauragra commented on api-reference/beta/resources/teamworkaccountconfiguration.md
> +|supportedClient|teamworkSupportedClient|The supported Teams client. The possible values are: `unknown`, `skypeDefaultAndTeams`, `teamsDefaultAndSkype`, `skypeOnly`, `teamsOnly`, `unknownFutureValue`
How do we think of Skype and Teams? When we say supported Teams client, is that inclusive of a Skype client? If the value is skypeOnly, is it still a Teams client?

2022-01-21 22:06 UTC, opbld30 commented
Docs Build status updates of commit _[153d178](https://github.com/microsoftgraph/microsoft-graph-docs/commits/153d17817009df59fe2550d1a30fdb22f17e5cc5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 22:09 UTC, opbld31 commented
Docs Build status updates of commit _[231f2b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/231f2b83ac62b8c27154c9ce99d1ec62e1a89b94)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 22:12 UTC, opbld34 commented
Docs Build status updates of commit _[231f2b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/231f2b83ac62b8c27154c9ce99d1ec62e1a89b94)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 22:19 UTC, opbld31 commented
Docs Build status updates of commit _[9dc7024](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9dc7024ec9b4a643fa637508365ef94373f8cda3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 22:21 UTC, opbld33 commented
Docs Build status updates of commit _[9dc7024](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9dc7024ec9b4a643fa637508365ef94373f8cda3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 22:22 UTC, Lauragra commented on api-reference/beta/resources/userteamwork.md
> +|[List installedApps](../api/userteamwork-list-installedapps.md)|[teamsAppInstallation](../resources/teamsappinstallation.md) collection|Retrieve the list of apps installed in the personal scope of t
This method is currently surfaced in this topic: https://docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta. Confirm that we should be surfacing it in this container resource topic?

2022-01-21 22:40 UTC, Lauragra commented on api-reference/beta/resources/teamworkconfiguredperipheral.md
> +|isOptional|Boolean|`True` if the current peripheral is optional. This property is also used to calculate the health state for the device.|
Not sure if this is clear - how does a Boolean property calculate health state?

2022-01-21 22:45 UTC, Lauragra commented on api-reference/beta/resources/teamworkconfiguredperipheral.md
> +Represents the details about the configured peripheral of a [teamworkDevice](../resources/teamworkdevice.md).
Suggested revision of this description: "Represents details about a perpheral device associated with a Microsoft Teams-enabled device."

2022-01-21 22:49 UTC, opbld31 commented
Docs Build status updates of commit _[bb18b36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb18b36541682113f3e74b0d8d38d4d16f993630)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 22:51 UTC, opbld30 commented
Docs Build status updates of commit _[bb18b36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb18b36541682113f3e74b0d8d38d4d16f993630)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 22:53 UTC, Lauragra commented on api-reference/beta/resources/teamworkcameraconfiguration.md
> +Applicable only for Microsoft Teams Rooms devices.
It might be more clear to refer to them as "devices with Microsoft Teams Rooms enabled."

2022-01-21 23:03 UTC, Lauragra commented on api-reference/beta/resources/teamworkconfiguredperipheral.md
> +|peripheral|[teamworkPeripheral](../resources/teamworkperipheral.md)|Details about the peripherals attached to the device.|
Global: "peripheral" is an adjective; I recommend that you use the phrase "peripheral device" to refer to devices that are connected to a Teams-enabled device. Please update this text to say "peripheral devices attached".

2022-01-21 23:06 UTC, Lauragra commented on api-reference/beta/resources/teamworkconnection.md
> +The connection status is useful when you calculate the device health.
Can you make this statement more clear - useful how? For example, "Connection status is an indicator of device health."

2022-01-21 23:07 UTC, Lauragra commented on api-reference/beta/resources/teamworkcontentcameraconfiguration.md
> +Represents the details about the configuration for a content camera of a [teamworkDevice](../resources/teamworkdevice.md).
Please revise to say "... content camera connected to a Microsoft Teams-enabled device."

2022-01-21 23:09 UTC, Lauragra commented on api-reference/beta/resources/teamworkdatetimeconfiguration.md
> +Represents the details about date and time configurations for a [teamworkDevice](../resources/teamworkdevice.md).
Revise as: "Represents date and time configuration details for a Microsoft Teams-enabled device."

2022-01-21 23:14 UTC, opbld33 commented
Docs Build status updates of commit _[d03a52d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d03a52dd3bd2a957795301a492e67d786bfcd6f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 23:15 UTC, Lauragra commented on api-reference/beta/resources/teamworkdevice.md
> +|[List operations](../api/teamworkdeviceoperation-list.md)|[teamworkDeviceOperation](../resources/teamworkdeviceoperation.md) collection|Get the **teamworkDeviceOperation** resources from the **opera
Please update the method descriptions to match the descriptions in the method topics. In this case, for example, "Get a list of operations that are running on a Teams-enabled device."

2022-01-21 23:17 UTC, opbld31 commented
Docs Build status updates of commit _[d03a52d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d03a52dd3bd2a957795301a492e67d786bfcd6f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-21 23:20 UTC, Lauragra commented on api-reference/beta/resources/teamworkdevice.md
> +|createdBy|[identitySet](../resources/identityset.md)|Identity of the user who created the document.|
What document are you referring to here?

2022-01-21 23:21 UTC, Lauragra commented on api-reference/beta/resources/teamworkdevice.md
> +|createdDateTime|DateTimeOffset|The UTC date and time when the document was created.|
Where you say document, do you mean "device"?

2022-01-21 23:22 UTC, Lauragra commented on api-reference/beta/resources/teamworkdevice.md
> +|hardwareDetail|[teamworkHardwareDetail](../resources/teamworkhardwaredetail.md)|A collection of hardware related properties. For example, **oemSerialNumber** and **model**.|
Please hyphenate "hardware-related".

2022-01-21 23:22 UTC, Lauragra commented on api-reference/beta/resources/teamworkdevice.md
> +|lastModifiedBy|[identitySet](../resources/identityset.md)|Identity of the user who last modified the document.|
Please look out for all references to "document" and clarify.

2022-01-21 23:46 UTC, Lauragra commented on api-reference/beta/resources/teamworkdevice.md
> +|activity|[teamworkDeviceActivity](../resources/teamworkdeviceactivity.md)|The activity properties that change based on the device usage.|
Are we missing the **currentUser** navigation property? I'm seeing that in the CSDL.

2022-01-22 01:16 UTC, opbld31 commented
Docs Build status updates of commit _[9a05642](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a056423dcb6721ad1079fad1630ef40d039eb68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-22 01:18 UTC, Lauragra commented on api-reference/beta/resources/teamworkdeviceactivity.md
> +|createdBy|[identitySet](../resources/identityset.md)|Identity of the user who created the document.|
Please update/clarify the references to document in the property descriptions.

2022-01-22 01:22 UTC, Lauragra commented on api-reference/beta/resources/teamworkdeviceconfiguration.md
> +|createdBy|[identitySet](../resources/identityset.md)|Identity of the user who created the document.|
Please clarify the references to document throughout.

2022-01-22 01:23 UTC, Lauragra commented on api-reference/beta/resources/teamworkdevicehealth.md
> +|createdBy|[identitySet](../resources/identityset.md)|Identity of the user who created the document.|
Please clarify the references to document in the property descriptions.

2022-01-22 01:23 UTC, opbld32 commented
Docs Build status updates of commit _[5aec278](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5aec278c47813d58827dbc7dfd1f5c95f078fc85)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-22 01:26 UTC, opbld32 commented
Docs Build status updates of commit _[5aec278](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5aec278c47813d58827dbc7dfd1f5c95f078fc85)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-22 01:26 UTC, Lauragra commented on api-reference/beta/resources/teamworkdeviceoperation.md
> +Represents the details about async operations on a [teamworkDevice](../resources/teamworkdevice.md). Any async operation ran on a device creates a **teamworkDeviceOperation**. You can retrieve the st
Please revise as: "Represents details about async operations running on a Microsoft Teams-enabled device, including operation status. Any async operation running on a device creates a **teamworkDeviceOperation** object."

2022-01-22 01:27 UTC, Lauragra commented on api-reference/beta/resources/teamworkdeviceoperation.md
> +|completedDateTime|DateTimeOffset|Time at which the operation reached into final state (for example, `Successful`, `Failed`, and `Cancelled`).|
Change "reached into" to "reached a".

2022-01-22 01:27 UTC, Lauragra commented on api-reference/beta/resources/teamworkdeviceoperation.md
> +|createdBy|[identitySet](../resources/identityset.md)|Identity of the user who created the document.|
Please clarify the references to document.

2022-01-22 01:29 UTC, Lauragra commented on api-reference/beta/resources/teamworkdisplayscreenconfiguration.md
> +|backlightBrightness|Int32|The brightness level on the device (0-100). Not Applicable for Microsoft Teams Rooms devices.|
Please lowercase Applicable in the descriptions.

2022-01-22 01:33 UTC, opbld33 commented
Docs Build status updates of commit _[0e6c704](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e6c70423daf22fce9d36d3cbfcd61777d97c35e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-22 01:35 UTC, opbld32 commented
Docs Build status updates of commit _[0e6c704](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e6c70423daf22fce9d36d3cbfcd61777d97c35e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-22 01:40 UTC, opbld30 commented
Docs Build status updates of commit _[5e1ecd3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e1ecd3f2275a1b9e80ba918aa253b3d3180265a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-22 01:42 UTC, opbld31 commented
Docs Build status updates of commit _[5e1ecd3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e1ecd3f2275a1b9e80ba918aa253b3d3180265a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-22 01:45 UTC, Lauragra commented on api-reference/beta/resources/teamworkloginstatus.md
> +Represents Microsoft Teams, Skype for Business, and Exchange sign-in status for a Microsoft Teams-enabled [device](../resources/teamworkdevice.md).
Just verifying that Skype for Business and Exchange are relevant for these Teams APIs?

2022-01-22 01:48 UTC, Lauragra commented on api-reference/beta/resources/teamworkperipheralhealth.md
> +Represents the health details about a particular peripheral of a [teamworkDevice](../resources/teamworkdevice.md).
Revise as: "Represents health details for a peripheral device attached to a Microsoft Teams-enabled device."

2022-01-22 01:48 UTC, Lauragra commented on api-reference/beta/resources/teamworkperipheralshealth.md
> +Represents the health details about all peripherals attached to a [teamworkDevice](../resources/teamworkdevice.md).
"Represents health details for all peripheral devices attached to a Microsoft Teams-enabled device."

2022-01-22 01:56 UTC, Lauragra commented on api-reference/beta/resources/teamworkperipheralhealth.md
> +|isOptional|Boolean|`True` if the peripheral is optional. Used for health computation.|
Are we missing the **peripheral** property here? I see that in the CSDL.

2022-01-22 01:59 UTC, Lauragra commented on api-reference/beta/resources/teamworkteamsclientconfiguration.md
> +Represents the details about the configuration for the Microsoft Teams client of a [teamworkDevice](../resources/teamworkdevice.md). Applicable only for Microsoft Teams Rooms devices.
Revise as "Represents configuration details for the Microsoft Teams client running on a Teams-enabled device."

2022-01-22 02:39 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Enrolled devices
Why is the TOC entry "enrolled devices" ? I'm not sure what this implies the device is enrolled in?

2022-01-22 02:40 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Devices activity
Please change Devices to Device (singular) throughout the TOC.

2022-01-22 02:41 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Devices async operation
Please change to "Device operation".

2022-01-23 19:05 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkloginstatus.md
> +Represents Microsoft Teams, Skype for Business, and Exchange sign-in status for a Microsoft Teams-enabled [device](../resources/teamworkdevice.md).
Yes from the devices a user can log in to Sfb and Exchange, and we give the sign-in details for the same.

2022-01-23 19:44 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkperipheralhealth.md
> +|isOptional|Boolean|`True` if the peripheral is optional. Used for health computation.|
peripheral is a navigation property, which means that it should come under relationship.

2022-01-23 19:47 UTC, adsrivastava2 commented on api-reference/beta/toc.yml
> +        - name: Enrolled devices
It implies devices enrolled with  tenant or devices provisioned for a tenant. What revision do you suggest?

2022-01-23 19:51 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkdeviceoperation.md
> +|createdBy|[identitySet](../resources/identityset.md)|Identity of the user who created the document.|
What do we mean by clarify the references to document. Reference to IdentitySet is already given.

2022-01-23 19:55 UTC, opbld32 commented
Docs Build status updates of commit _[b89d059](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b89d059288d971b9eb1df47b95fc9fcf586ec6c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-24 08:48 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkdeviceactivity.md
> +|createdBy|[identitySet](../resources/identityset.md)|Identity of the user who created the document.|
updated.

2022-01-24 08:55 UTC, opbld30 commented
Docs Build status updates of commit _[3499e7c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3499e7c06e7b3014eba92c5411f22cb61de881a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-25 07:42 UTC, adsrivastava2 commented on api-reference/beta/resources/teamwork.md
> +|[List devices](../api/teamworkdevice-list.md)|[teamworkDevice](../resources/teamworkdevice.md) collection|Get the list of all Teams devices provisioned for the tenant.|
We are adding a new relationship to this resource so thought of showing it to the users regarding supported methods. If you suggest to remove it I can go ahead and do this.

2022-01-25 07:43 UTC, adsrivastava2 commented on api-reference/beta/resources/teamwork.md
> +| [List workforceIntegrations](../api/workforceintegration-list.md) | [workforceIntegration](workforceintegration.md) collection | Get the list of **workforceIntegration** objects associated with thi
This was a change updated by @isvargasmsft.

2022-01-25 07:59 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkaccountconfiguration.md
> +|supportedClient|teamworkSupportedClient|The supported Teams client. The possible values are: `unknown`, `skypeDefaultAndTeams`, `teamsDefaultAndSkype`, `skypeOnly`, `teamsOnly`, `unknownFutureValue`
No skypeOnly refers to support of Only Skype client by some of the legacy devices. Updated the description.

2022-01-25 08:05 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkcameraconfiguration.md
> +Applicable only for Microsoft Teams Rooms devices.
Microsoft Teams Room is a different type of a device.
For all the devices we do not have this option that is -> Microsoft Teams Room enabled. For example for Sip devices and Touch console devices it does not mean anything when we say MTR enabled.
Do you still suggest the revision?

2022-01-25 08:29 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkconfiguredperipheral.md
> +|isOptional|Boolean|`True` if the current peripheral is optional. This property is also used to calculate the health state for the device.|
If the peripheral is optional and it is not connected then the health status of the devices is online, but if it not optional that is required and it is not connected properly, it impacts the health status of the device to go to critical state.

2022-01-25 08:52 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkdevice.md
> +|activity|[teamworkDeviceActivity](../resources/teamworkdeviceactivity.md)|The activity properties that change based on the device usage.|
In api.md we wanted to have currentUser as a type graph.identity, then it should have been a relationship, but we marked the currentUser as teamworkUserIdentity hence it is not a relationship. This is a miss in api.md file, it should not be a relationship.

2022-01-25 08:53 UTC, adsrivastava2 commented on api-reference/beta/resources/userteamwork.md
> +|[List installedApps](../api/userteamwork-list-installedapps.md)|[teamsAppInstallation](../resources/teamsappinstallation.md) collection|Retrieve the list of apps installed in the personal scope of t
Yes this is what @isvargasmsft and I checked from the csdl and corrected the doc.

2022-01-25 09:01 UTC, opbld33 commented
Docs Build status updates of commit _[70e8065](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70e80650f5665fd5c93478e1cf2372fe352bbc92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-25 16:01 UTC, adsrivastava2 commented on api-reference/beta/resources/teamwork.md
> +| [List workforceIntegrations](../api/workforceintegration-list.md) | [workforceIntegration](workforceintegration.md) collection | Get the list of **workforceIntegration** objects associated with thi
It was copied from this doc - https://docs.microsoft.com/en-us/graph/api/resources/workforceintegration?view=graph-rest-beta.
Please suggest revision.

2022-01-26 01:57 UTC, opbld30 commented
Docs Build status updates of commit _[db095af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db095af678fde0c44ef42b177318a5410a584e16)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-26 02:00 UTC, opbld34 commented
Docs Build status updates of commit _[db095af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db095af678fde0c44ef42b177318a5410a584e16)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-26 02:13 UTC, Lauragra commented on api-reference/beta/resources/teamwork.md
> +|[List devices](../api/teamworkdevice-list.md)|[teamworkDevice](../resources/teamworkdevice.md) collection|Get the list of all Teams devices provisioned for the tenant.|
Because we list these methods in the resource type topics, I don't think that we also need to list them here.

2022-01-26 02:57 UTC, Lauragra commented on api-reference/beta/resources/teamwork.md
> +| [List workforceIntegrations](../api/workforceintegration-list.md) | [workforceIntegration](workforceintegration.md) collection | Get the list of **workforceIntegration** objects associated with thi
I think we can remove the methods table from this topic. The revision I would suggest if we think we need to list the methods here would be "Get a list of **workforceIntegrations** associated with a Microsoft Teams-enabled device".  (I'm also not sure what a workforceIntegration is; I think we can improve those docs). If there is a reason to list the methods here because of the nav property, would we list all methods associated with workforceIntegration? Why just the List method?

2022-01-26 03:05 UTC, Lauragra commented on api-reference/beta/resources/teamworkcameraconfiguration.md
> +Applicable only for Microsoft Teams Rooms devices.
Would this be an accurate revised description: "Represents the details about the camera configuration for a Microsoft Teams Rooms [device](../resources/teamworkdevice.md)." In other words, this complex type is only applicable to a device with a deviceType value of `teamsRoom`, that's what you're trying to convey, right?

2022-01-26 03:07 UTC, Lauragra commented on api-reference/beta/resources/teamworkconfiguredperipheral.md
> +|isOptional|Boolean|`True` if the current peripheral is optional. This property is also used to calculate the health state for the device.|
Would it be helpful to make the following clarification: "If set to `false`, this property is also used as part of the calculation of the health state for the device."

2022-01-26 16:08 UTC, adsrivastava2 commented on api-reference/beta/resources/teamworkcameraconfiguration.md
> +Applicable only for Microsoft Teams Rooms devices.
Yes this is what I was trying to convey. Updated the description.

2022-01-26 16:33 UTC, opbld33 commented
Docs Build status updates of commit _[be0e9c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be0e9c821aaea56963db5588895afe400b69c59d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-27 03:51 UTC, Lauragra approved these changes

2022-01-27 04:27 UTC, Lauragra commented on changelog/Microsoft.Teams.Core.json
> +          "Id": "5a1d17b0-c9a6-4c4f-ad7f-f57703ea9518",
Please add similar entries for the all the new methods that have been added.

2022-01-27 04:31 UTC, opbld32 commented
Docs Build status updates of commit _[c85dc74](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c85dc7467df56c105dcf9d387de6f14d53548948)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-27 06:01 UTC, opbld32 commented
Docs Build status updates of commit _[c215965](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c215965affe9f8dd2d0e67c5a764018cd2f6b17f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-28 04:57 UTC, opbld31 commented
Docs Build status updates of commit _[6c83d72](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c83d72f6a78674e9bbcee985223a68227eed322)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-28 05:27 UTC, opbld33 commented
Docs Build status updates of commit _[c75f366](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c75f36622cf67322845e7fc9c29b5bfb030a9cdd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworkdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-restart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-restart?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-rundiagnostics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-rundiagnostics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-rundiagnostics?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevice-updatesoftware.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevice-updatesoftware.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevice-updatesoftware?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceactivity-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceactivity-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceconfiguration-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdevicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdevicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdevicehealth-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-get?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/api/teamworkdeviceoperation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/api/teamworkdeviceoperation-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkdeviceoperation-list?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkaccountconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkaccountconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkaccountconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactiveperipherals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkactiveperipherals.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactiveperipherals?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconfiguredperipheral.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconfiguredperipheral.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconfiguredperipheral?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconnection?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkcontentcameraconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkcontentcameraconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkcontentcameraconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdatetimeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdatetimeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkdatetimeconfiguration?view=graph-rest-beta&branch=pr-en-us-14939) (graph-rest-beta) |
[api-reference/beta/resources/teamworkdevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/adsrivastava-devicemanagement-changes/api-reference/beta/resources/teamworkdevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api [...]

2022-01-28 05:33 UTC, merged