Added documentation for content type sync apis
microsoftgraph/microsoft-graph-docs pull request #14938
Opened 2021-11-15 07:01 UTC by swapnil1993

2021-11-15 07:03 UTC, opbld34 commented
Docs Build status updates of commit _[1f3db7d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f3db7d5db039781d8ba9347cfd143e01e910ac8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-4d55311ddcf0e143cceb20163706131c-46cef9e0)
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-0cf411fd33d940c5a8776e117d0149f0-46cef9e0)
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-eb8edc5aad30462faeffc68c13842847-46cef9e0)
[api-reference/beta/api/ediscovery-case-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/ediscovery-case-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-case-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-c8a6196d7902829e368077cafecfbabb-46cef9e0)
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-e5e931da77c86a4fa611cd457dcc9727-46cef9e0)
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="4d55311ddcf0e143cceb20163706131c-46cef9e0"></a>
### [api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List operations - Microsoft Graph beta' is duplicated in: 'beta/api/ediscovery-case-list-operations.md(2,8), beta/api/list-list-operations.md(2,8), beta/api/site-list-operations.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List operations' is duplicated with other articles: 'beta/api/ediscovery-case-list-operations.md(10,1), beta/api/list-list-operations.md(10,1), beta/api/site-list-operations.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get the richLongRunningOperation resources from the operations navigation property.' is duplicated in 'beta/api/list-list-operations.md(3,14)', 'beta/api/site-list-operations.md(3,14)'.`````

<a id="0cf411fd33d940c5a8776e117d0149f0-46cef9e0"></a>
### [api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List operations - Microsoft Graph beta' is duplicated in: 'beta/api/ediscovery-case-list-operations.md(2,8), beta/api/list-list-operations.md(2,8), beta/api/site-list-operations.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List operations' is duplicated with other articles: 'beta/api/ediscovery-case-list-operations.md(10,1), beta/api/list-list-operations.md(10,1), beta/api/site-list-operations.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get the richLongRunningOperation resources from the operations navigation property.' is duplicated in 'beta/api/list-list-operations.md(3,14)', 'beta/api/site-list-operations.md(3,14)'.`````

<a id="eb8edc5aad30462faeffc68c13842847-46cef9e0"></a>
### [api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md)
 - **Line 19, Column 15**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/longrunningoperation.md'.`````

<a id="c8a6196d79 [...]

2021-11-15 11:44 UTC, opbld30 commented
Docs Build status updates of commit _[7cbb085](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7cbb08564297b39a22bcd0bfb1194672e2e5fd86)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111151142512679-14938%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-16T11%3A44%3A55Z&sr=b&sp=r&sig=R%2Fl81J%2BZofMnrBDXQOGiqn%2Ft4EJnLDInt1YizKj5amg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-15 12:09 UTC, opbld33 commented
Docs Build status updates of commit _[f938841](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f938841e7143b0fa414b5f593c8696a6503d9a75)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111151208000893-14938%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-16T12%3A09%3A32Z&sr=b&sp=r&sig=xKDPmwIgQ7wUw8juj2Lqvilu03UhEuJ6Sj%2F4j2DubqM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-16 05:27 UTC, opbld30 commented
Docs Build status updates of commit _[007a96e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/007a96eec7489fd9a6d74f131c09b5ace1438b12)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111160525274974-14938%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-17T05%3A27%3A54Z&sr=b&sp=r&sig=YfYntdibnfcYt09wokACKBxcqTv4K8cSWT%2BZMYD2f6I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-25 22:35 UTC, isvargasmsft commented on changelog/Microsoft.FileServices.json
>  }
According to the CSDL, there are some complex types missing in this PR:
publicError
publicErrorDetail
publicInnerError

2021-11-25 22:38 UTC, isvargasmsft commented on api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md
> +### Request
Please use the proper structure to list several examples:
H2 Examples
H3 Example 1: description
H4 Request
H4 Response
H3 Example 2: description
H4 Request
H4 Response

2021-11-25 22:39 UTC, isvargasmsft commented on api-reference/beta/api/list-list-operations.md
> +Get the richLongRunningOperation resources from the operations navigation property in a list.
Please include a reference link for the first mention of a resource type and bold subsequent mentions. In this case, please include link for richLongRunningOperation.

2021-11-25 22:40 UTC, isvargasmsft commented on api-reference/beta/api/site-list-operations.md
> +Get the richLongRunningOperation resources from the operations navigation property in a site.
Please include reference link for the resource type.

2021-11-25 22:42 UTC, isvargasmsft commented on changelog/Microsoft.FileServices.json
>  }
The resource type richLongRunningOperation is an entity type. This means it should be included in the TOC.

Please also include the new methods in the TOC.

2021-11-25 22:44 UTC, isvargasmsft commented on changelog/Microsoft.FileServices.json
>  }
In addition, we are including a navigation property to the site and list resource types. 

Please check all the methods that return a list or site object in the response body and update the examples section to include this new properties, if applicable.

2021-11-25 22:45 UTC, isvargasmsft requested changes
Hello @swapnil1993, 

Thank you very much for your work in this PR. Very complete overall. 

Please take a look at my comments regarding completeness. 

Feel free to ping me on the side if you have any questions. 

Kind regards, 

Isaac Vargas

2021-11-29 06:30 UTC, swapnil1993 commented on changelog/Microsoft.FileServices.json
>  }
publicError, publicErrorDetail, publicInnerError, and longRunningOperation were already present earlier in graph in [identity csdl ](https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads?path=/Schemas/beta-Prod.csdl&_a=contents&version=GBmaster) I am just reusing those in FileServices.csdl which is why I excluded changelog entries and TOC entry for these. I have made other changes that were requested, please let me know if I need to include the above changes as well.

2021-12-01 16:55 UTC, opbld32 commented
Docs Build status updates of commit _[98585aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/98585aa1394351147feb9013e91e803088a21dcb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-827006c5)
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-827006c5"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/toc.yml)
 - **Line 14031, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/richlongrunningoperation-get.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112011654065865-14938%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T16%3A55%3A55Z&sr=b&sp=r&sig=Bss2tgZ%2FeLk7F4CunIhR2jZ8bghV0rH2wQwQ2GnC7nw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 17:03 UTC, opbld31 commented
Docs Build status updates of commit _[13e2979](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13e2979ca7a63637d8528c4e07cb4156fad191b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112011702228602-14938%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T17%3A03%3A53Z&sr=b&sp=r&sig=MNUWquubgB%2BCq3Sgj3UhzpsDw1GTJ139Me3Wr8GOnA4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 17:11 UTC, opbld30 commented
Docs Build status updates of commit _[f1bccbf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f1bccbf4e8069da1975483e17c2f5db0d8297f9f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112011710013548-14938%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T17%3A11%3A55Z&sr=b&sp=r&sig=7f99La6eJQ5ZDymJt0Kmeg9uLJVgDmd%2B9JWL%2Fbfu4P8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 17:13 UTC, isvargasmsft commented on changelog/Microsoft.FileServices.json
> +          "ApiChange": "Resource",
ApiChange: should be Relationship.

Was this automatically generated? If so, we should report this error.

2021-12-01 17:13 UTC, isvargasmsft commented on changelog/Microsoft.FileServices.json
> +          "ApiChange": "Resource",
Same here, ApiChange, should be Relationship.

2021-12-01 17:14 UTC, isvargasmsft commented on changelog/Microsoft.FileServices.json
> +          "Target": "addCopyFromContentTypeHub"
The target should be **contentType** resource type in both the description and the target.

2021-12-01 17:15 UTC, isvargasmsft commented on changelog/Microsoft.FileServices.json
> +          "Target": "getCompatibleHubContentTypes"
Same here, the target should be contentType resource type.

2021-12-01 17:15 UTC, isvargasmsft commented on changelog/Microsoft.FileServices.json
> +          "Target": "getCompatibleHubContentTypes"
Please let ud know if these entries were generated or manually created.

2021-12-01 17:18 UTC, isvargasmsft requested changes
Thank you very much, @swapnil1993, for addressing my comments. 

I added some minor fixes. 

I noticed some errors in the changelog entries, were those entries generated by the tool or did you manually add them?

2021-12-02 05:27 UTC, swapnil1993 commented on changelog/Microsoft.FileServices.json
> +          "ApiChange": "Resource",
Yes, this was automatically generated

2021-12-02 05:28 UTC, swapnil1993 commented on changelog/Microsoft.FileServices.json
> +          "Target": "getCompatibleHubContentTypes"
All the entries here were generated from the scirpt

2021-12-02 05:40 UTC, opbld34 commented
Docs Build status updates of commit _[3fa2fbe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fa2fbec7318f0b78dc76f7c16af7b8ef52d5ce9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112020538342660-14938%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T05%3A40%3A36Z&sr=b&sp=r&sig=%2FPMbsQe8hUMXbDa0gEX8UrMFYNCpiuNRlVLSOeLq%2BaQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 17:02 UTC, isvargasmsft approved these changes

2021-12-16 22:50 UTC, isvargasmsft commented
@swapnil1993 whats the status of this PR? Is it ready to merge now?

2021-12-20 12:18 UTC, swapnil1993 commented
> @swapnil1993 whats the status of this PR? Is it ready to merge now?

@isvargasmsft  Sorry for late reply. Currently there is a deployment freeze in SharePoint due to which the code change for this PR will be pushed out to 100% prod by mid-January, post which I will merge this PR. I will keep you updated in case if there is any further delay.

2022-01-12 05:25 UTC, opbld34 commented
Docs Build status updates of commit _[7bf655d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7bf655d2e629515339f147c56524feb0e03ddd73)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201120522144807-14938%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T05%3A25%3A23Z&sr=b&sp=r&sig=ZqNbBzb1vCLWYUkIhos0f5CNyeghfnI68n2ZWoduK1Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 05:33 UTC, opbld32 commented
Docs Build status updates of commit _[def1f1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/def1f1b8ee1f7159e07d0d51fd37ea9e3332b066)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201120523570181-14938%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T05%3A33%3A11Z&sr=b&sp=r&sig=GP4H8HTXUz1%2Bs1NjKw7olrt9KBVDvaTFRXQQkgvSKVE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 03:16 UTC, opbld33 commented
Docs Build status updates of commit _[a9ee9b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a9ee9b9165f8c092f5635b32d26a193a73b5046b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190314133605-14938%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T03%3A16%3A10Z&sr=b&sp=r&sig=LnW7D1SfQztxumkKYIX0XkxDSPNhtun00nRBhXPELoI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 03:18 UTC, opbld33 commented
Docs Build status updates of commit _[d2a421b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2a421b2f9f53a415cc6aff1641865b1cf75546b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190315072140-14938%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T03%3A18%3A30Z&sr=b&sp=r&sig=rfqkLb1U%2FJS953b7i3Et6xCQsfAdS7zwwPkP98bg0Nc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 03:20 UTC, opbld30 commented
Docs Build status updates of commit _[5df7b5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5df7b5f564f13bc3f0d97a75d2abbc1a2fcd8fb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201190317118158-14938%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T03%3A20%3A18Z&sr=b&sp=r&sig=gKUhGSTXY0dGR%2Fc6O99TqczV1vcI8v43OsP%2B11AozZ0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 04:36 UTC, Lauragra commented on api-reference/beta/api/list-list-operations.md
> +# List operations in a list
Please make the H1 and the Title "List operations", per our topic title guidelines.

2022-01-20 04:37 UTC, Lauragra commented on api-reference/beta/api/list-list-operations.md
> +Get the [richLongRunningOperation](../resources/richlongrunningoperation.md) resources from the operations navigation property in a [list](../resources/list.md).
Suggested friendlier description here: "Get the list of [richLongRunningOperations](../resources/richlongrunningoperation.md) associated with a list."

2022-01-20 04:38 UTC, Lauragra commented on api-reference/beta/api/list-list-operations.md
> +GET /sites/{sitesId}/lists/{listId}/operations
This is a minor point, but should we consistently make the placeholder ID singular, i.e. "siteId" instead of "sitesId"?

2022-01-20 04:39 UTC, Lauragra commented on api-reference/beta/api/richlongrunningoperation-get.md
> +GET /sites/{sitesId}/lists/{listId}/operations/{richLongRunningOperation-ID}
Would it be beneficial to customers to explain that one can get a rich long running operation from a site or a list, and show examples of both?

2022-01-20 04:55 UTC, swapnil1993 commented on api-reference/beta/api/richlongrunningoperation-get.md
> +GET /sites/{sitesId}/lists/{listId}/operations/{richLongRunningOperation-ID}
That is covered in "list-list-operations", "site-list-operations" along with references in site and list resources as well.

2022-01-20 06:12 UTC, Lauragra commented on api-reference/beta/api/site-list-operations.md
> +title: "List operations in a site"
Per the file naming guidelines, the title and H1 here should be "List operations".

2022-01-20 06:12 UTC, Lauragra commented on api-reference/beta/api/site-list-operations.md
> +Get the [richLongRunningOperation](../resources/richlongrunningoperation.md) resources from the operations navigation property in a [site](../resources/site.md).
Suggested revision: "Get the list of [richLongRunningOperation](../resources/richlongrunningoperation.md) associated with a site."

2022-01-20 06:16 UTC, opbld31 commented
Docs Build status updates of commit _[cce1a15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cce1a15800428aba7672099453349addc90d86d1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-4d55311ddcf0e143cceb20163706131c-bfb1ed37)
[api-reference/beta/api/ediscovery-case-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/ediscovery-case-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-case-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-c8a6196d7902829e368077cafecfbabb-bfb1ed37)
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="4d55311ddcf0e143cceb20163706131c-bfb1ed37"></a>
### [api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List operations - Microsoft Graph beta' is duplicated in: 'beta/api/ediscovery-case-list-operations.md(2,8), beta/api/list-list-operations.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List operations' is duplicated with other articles: 'beta/api/ediscovery-case-list-operations.md(10,1), beta/api/list-list-operations.md(10,1)'. First level headings must be unique within a docset.`````

<a id="c8a6196d7902829e368077cafecfbabb-bfb1ed37"></a>
### [api-reference/beta/api/ediscovery-case-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/ediscovery-case-list-operations.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List operations - Microsoft Graph beta' is duplicated in: 'beta/api/ediscovery-case-list-operations.md(2,8), beta/api/list-list-operations.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List operations' is duplicated with other articles: 'beta/api/ediscovery-case-list-operations.md(10,1), beta/api/list-list-operations.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200613588999-14938%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T06%3A16%3A19Z&sr=b&sp=r&sig=enS%2BnlJoeTrBncvpLKzNynLhjIPdjImKs%2ByXDoMO71o%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files  [...]

2022-01-20 06:19 UTC, opbld33 commented
Docs Build status updates of commit _[7a183ba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a183bae2d4baf32e324ff4b23358ef778605ea1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-4d55311ddcf0e143cceb20163706131c-d4bc061e)
[api-reference/beta/api/ediscovery-case-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/ediscovery-case-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-case-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-c8a6196d7902829e368077cafecfbabb-d4bc061e)
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="4d55311ddcf0e143cceb20163706131c-d4bc061e"></a>
### [api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List operations - Microsoft Graph beta' is duplicated in: 'beta/api/ediscovery-case-list-operations.md(2,8), beta/api/list-list-operations.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List operations' is duplicated with other articles: 'beta/api/ediscovery-case-list-operations.md(10,1), beta/api/list-list-operations.md(10,1)'. First level headings must be unique within a docset.`````

<a id="c8a6196d7902829e368077cafecfbabb-d4bc061e"></a>
### [api-reference/beta/api/ediscovery-case-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/ediscovery-case-list-operations.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List operations - Microsoft Graph beta' is duplicated in: 'beta/api/ediscovery-case-list-operations.md(2,8), beta/api/list-list-operations.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List operations' is duplicated with other articles: 'beta/api/ediscovery-case-list-operations.md(10,1), beta/api/list-list-operations.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201200614040805-14938%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T06%3A19%3A11Z&sr=b&sp=r&sig=OGS7X3y84Kk7xYgBQhSGotSHvhFyDLy2HG2AKuZPQ8w%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you  [...]

2022-01-20 06:19 UTC, swapnil1993 commented on api-reference/beta/api/list-list-operations.md
> +# List operations in a list
I have made the change but it is showing warning that there is a duplicate title in some other file.

2022-01-21 01:10 UTC, opbld30 commented
Docs Build status updates of commit _[1a4f58b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a4f58bdce2180ea13135736ad5740ea93547dc3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-4d55311ddcf0e143cceb20163706131c-3c141b00)
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-0cf411fd33d940c5a8776e117d0149f0-3c141b00)
[api-reference/beta/api/ediscovery-case-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/ediscovery-case-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-case-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-c8a6196d7902829e368077cafecfbabb-3c141b00)
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="4d55311ddcf0e143cceb20163706131c-3c141b00"></a>
### [api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List operations - Microsoft Graph beta' is duplicated in: 'beta/api/ediscovery-case-list-operations.md(2,8), beta/api/list-list-operations.md(2,8), beta/api/site-list-operations.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List operations' is duplicated with other articles: 'beta/api/ediscovery-case-list-operations.md(10,1), beta/api/list-list-operations.md(10,1), beta/api/site-list-operations.md(10,1)'. First level headings must be unique within a docset.`````

<a id="0cf411fd33d940c5a8776e117d0149f0-3c141b00"></a>
### [api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List operations - Microsoft Graph beta' is duplicated in: 'beta/api/ediscovery-case-list-operations.md(2,8), beta/api/list-list-operations.md(2,8), beta/api/site-list-operations.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List operations' is duplicated with other articles: 'beta/api/ediscovery-case-list-operations.md(10,1), beta/api/list-list-operations.md(10,1), beta/api/site-list-operations.md(10,1)'. First level headings must be unique within a docset.`````

<a id="c8a6196d7902829e368077cafecfbabb-3c141b00"></a>
### [api-reference/beta/api/ediscovery-case-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/ediscovery-case-list-operations.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List operations - Microsoft Graph beta' is duplicated in: 'beta/api/ediscovery-case-list-operations.md(2,8), beta/api/list-list-operations.md(2,8), beta/api/site-list-operations.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/val [...]

2022-01-21 01:14 UTC, opbld32 commented
Docs Build status updates of commit _[e22c3d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e22c3d21f4422a0613ee47f764ccc644ec1c7f68)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-4d55311ddcf0e143cceb20163706131c-65271482)
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-0cf411fd33d940c5a8776e117d0149f0-65271482)
[api-reference/beta/api/ediscovery-case-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/ediscovery-case-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-case-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-c8a6196d7902829e368077cafecfbabb-65271482)
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="4d55311ddcf0e143cceb20163706131c-65271482"></a>
### [api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List operations - Microsoft Graph beta' is duplicated in: 'beta/api/ediscovery-case-list-operations.md(2,8), beta/api/list-list-operations.md(2,8), beta/api/site-list-operations.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List operations' is duplicated with other articles: 'beta/api/ediscovery-case-list-operations.md(10,1), beta/api/list-list-operations.md(10,1), beta/api/site-list-operations.md(10,1)'. First level headings must be unique within a docset.`````

<a id="0cf411fd33d940c5a8776e117d0149f0-65271482"></a>
### [api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List operations - Microsoft Graph beta' is duplicated in: 'beta/api/ediscovery-case-list-operations.md(2,8), beta/api/list-list-operations.md(2,8), beta/api/site-list-operations.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List operations' is duplicated with other articles: 'beta/api/ediscovery-case-list-operations.md(10,1), beta/api/list-list-operations.md(10,1), beta/api/site-list-operations.md(10,1)'. First level headings must be unique within a docset.`````

<a id="c8a6196d7902829e368077cafecfbabb-65271482"></a>
### [api-reference/beta/api/ediscovery-case-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/ediscovery-case-list-operations.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List operations - Microsoft Graph beta' is duplicated in: 'beta/api/ediscovery-case-list-operations.md(2,8), beta/api/list-list-operations.md(2,8), beta/api/site-list-operations.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/val [...]

2022-01-21 01:17 UTC, opbld30 commented
Docs Build status updates of commit _[fb5c6b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb5c6b25e0cc2efb81a70cd8073448c0325835a7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-4d55311ddcf0e143cceb20163706131c-6ac70c7d)
[api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-0cf411fd33d940c5a8776e117d0149f0-6ac70c7d)
[api-reference/beta/api/ediscovery-case-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/ediscovery-case-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscovery-case-list-operations?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) | [Details](#user-content-c8a6196d7902829e368077cafecfbabb-6ac70c7d)
[api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-addcopyfromcontenttypehub.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/contenttype-getcompatiblehubcontenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-getcompatiblehubcontenttypes?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/api/richlongrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/richlongrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/richlongrunningoperation-get?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/richlongrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/richlongrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/richlongrunningoperation?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopyfromcontenttypehub?view=graph-rest-beta&branch=pr-en-us-14938) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="4d55311ddcf0e143cceb20163706131c-6ac70c7d"></a>
### [api-reference/beta/api/list-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/list-list-operations.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List operations - Microsoft Graph beta' is duplicated in: 'beta/api/ediscovery-case-list-operations.md(2,8), beta/api/list-list-operations.md(2,8), beta/api/site-list-operations.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List operations' is duplicated with other articles: 'beta/api/ediscovery-case-list-operations.md(10,1), beta/api/list-list-operations.md(10,1), beta/api/site-list-operations.md(10,1)'. First level headings must be unique within a docset.`````

<a id="0cf411fd33d940c5a8776e117d0149f0-6ac70c7d"></a>
### [api-reference/beta/api/site-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/site-list-operations.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List operations - Microsoft Graph beta' is duplicated in: 'beta/api/ediscovery-case-list-operations.md(2,8), beta/api/list-list-operations.md(2,8), beta/api/site-list-operations.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List operations' is duplicated with other articles: 'beta/api/ediscovery-case-list-operations.md(10,1), beta/api/list-list-operations.md(10,1), beta/api/site-list-operations.md(10,1)'. First level headings must be unique within a docset.`````

<a id="c8a6196d7902829e368077cafecfbabb-6ac70c7d"></a>
### [api-reference/beta/api/ediscovery-case-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-12-test/ctsyncapi/api-reference/beta/api/ediscovery-case-list-operations.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List operations - Microsoft Graph beta' is duplicated in: 'beta/api/ediscovery-case-list-operations.md(2,8), beta/api/list-list-operations.md(2,8), beta/api/site-list-operations.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/val [...]

2022-01-21 01:22 UTC, merged