Update add-properties-profilecard.md
microsoftgraph/microsoft-graph-docs pull request #14955
Opened 2021-11-16 10:00 UTC by PollyNincevic

Added instructions on how to delete a custom attribute per PM request

2021-11-16 10:02 UTC, opbld34 commented
Docs Build status updates of commit _[e86e496](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e86e496cddb8a5e7b3624b5b5e8ab140ec5e8523)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/PollyNincevic-patch-2-1/concepts/add-properties-profilecard.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-14955) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111161000306504-14955%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-17T10%3A02%3A00Z&sr=b&sp=r&sig=lpN7O09ic1oRXDIBQTPUMlUAY%2BE08%2FkjNkDg2ymGKis%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-16 10:16 UTC, opbld33 commented
Docs Build status updates of commit _[47d3052](https://github.com/microsoftgraph/microsoft-graph-docs/commits/47d3052f08279349fcc8a470563de354ab06ebcd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/PollyNincevic-patch-2-1/concepts/add-properties-profilecard.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-14955) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111161014214588-14955%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-17T10%3A16%3A07Z&sr=b&sp=r&sig=iMO5yJkWkmUHJW1BSIQP8V%2FTNQNbckwYMi3y%2FPOpcoE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-16 10:17 UTC, opbld34 commented
Docs Build status updates of commit _[628a480](https://github.com/microsoftgraph/microsoft-graph-docs/commits/628a480598c675ef7f8b4ef790048970d78976df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/PollyNincevic-patch-2-1/concepts/add-properties-profilecard.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-14955) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111161014588204-14955%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-17T10%3A17%3A38Z&sr=b&sp=r&sig=vrjpyilBw9T5UBPcvPRBTuJ%2B2hpv6TZVJ%2FueMTRbhaE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-23 15:32 UTC, isvargasmsft commented
@kevinbellinger, what's the status of this PR? Is the technical review complete?

2021-12-08 08:28 UTC, angelgolfer-ms commented on concepts/add-properties-profilecard.md
> +## Removing a custom attribute
Line 151:
Please title this section as "Deleting a custom attribute".
Reason: In our REST API in general and in this case with the profileCardProperties nav property, there's a subtle distinction between using "remove" vs "delete". Because ContainsTarget is specified as "true" for profileCardProperties, a nav propertu of organizationSettings, we should use "delete". See the definition of the nav property in the beta metadata:

<EntityType Name="organizationSettings" BaseType="graph.entity">
...
<NavigationProperty Name="profileCardProperties" Type="Collection(graph.profileCardProperty)" ContainsTarget="true"/>
</EntityType>

2021-12-08 09:24 UTC, angelgolfer-ms commented on concepts/add-properties-profilecard.md
> +To remove a custom attribute, run the following query in [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer):
Hi @PollyNincevic , the body of this section is extremely slim. I don't have all the relevant context, but maybe you can check with your PMs. I can imagine at the very least, you'd want to model the prior section "Adding custom attributes" and say something like:
"Following the same mapping between Azure AD custom extension attributes and profile card custom attributes (such as `customAttribute1`) as described in the preceding section Adding a custom attribute (link to that section), you can delete a custom attribute using the [delete](/graph/api/profilecardproperty-delete?view=graph-rest-beta) operation as shown in the example below.

### Example
The following example deletes the custom attribute `customAttribute5` from the organization settings. A successful deletion returns `HTTP 204`.

#### Request

<!-- {
  "blockType": "request",
  "name": "delete_profilecardproperty_example"
}-->
```http
DELETE https://graph.microsoft.com/beta/organization/{organizationId}/settings/profileCardProperties/customAttribute5
```

#### Response
<!-- {
  "blockType": "response",
  "truncated": true
} -->
```http
HTTP/1.1 204 No Content
```




BTW, I'd suggest renaming the existing section title "Adding custom attributes" as "Adding a custom attribute". Both that operation and this delete operation work on only one attribute at a time.

2021-12-08 09:31 UTC, angelgolfer-ms commented on concepts/add-properties-profilecard.md
>  ```
To make this new section for deletion parallel with the existing section in line 76, and to make the request and response in that example clearer, please add the following subsection titles:

- After line 107, add an H4 subsection with the title "Request".
- After line 131 before the line ```http```, add an H4 subsection with the title "Response".

2021-12-08 09:36 UTC, angelgolfer-ms commented on concepts/add-properties-profilecard.md
>    ]
Since you're adding an example for deleting a customer profile card property, you should please:
- Retitle the topic from "Add additional properties to the profile card..." to "Add or delete custom properties from the profile card using the profile card API in Microsoft Graph (preview)".
- After line 17, add a sentence to say something like 
  "You can also delete custom attributes from profile cards of the organization."

2021-12-08 09:48 UTC, angelgolfer-ms commented on concepts/add-properties-profilecard.md
> +To remove a custom attribute, run the following query in [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer):
Wanted to point out explicitly, in our REST API docs, when we show how to make a REST operation call, we just describe what it does and show the REST request and REST response. We don't explicitly tell customers to use Graph Explorer. Graph Explorer was primarily developed as a tool to let customers try out APIs quickly without the overhead of creating an app, for learning or prototyping purpose.

Instead of using Graph Explorer to carry out production work, we'd like customers to create apps and make the calls from their apps, either as REST API calls directly or by using an SDK.

2021-12-08 09:49 UTC, angelgolfer-ms requested changes
@PollyNincevic , please see my comments and follow-up suggestions in my email (to be sent shortly).

2021-12-14 14:04 UTC, PollyNincevic commented on concepts/add-properties-profilecard.md
> +## Removing a custom attribute
Section renamed to "Deleting a custom attribute"

2021-12-14 14:04 UTC, PollyNincevic commented on concepts/add-properties-profilecard.md
> +To remove a custom attribute, run the following query in [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer):
Thank you for the detailed feedback! I have updated per your suggestions.

2021-12-14 14:04 UTC, PollyNincevic commented on concepts/add-properties-profilecard.md
>  ```
Updated

2021-12-14 14:05 UTC, PollyNincevic commented on concepts/add-properties-profilecard.md
>    ]
Updated per suggestions

2021-12-14 14:05 UTC, PollyNincevic commented on concepts/add-properties-profilecard.md
> +To remove a custom attribute, run the following query in [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer):
Thank you. Section replaced with what you had suggested in comments above.

2021-12-14 14:12 UTC, PollyNincevic commented
Changes made per Angela comments. @isvargasmsft fyi

2021-12-14 14:13 UTC, opbld34 commented
Docs Build status updates of commit _[f5a7ba3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5a7ba3c45141ad5811a95b04b625cf0a80988e0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/PollyNincevic-patch-2-1/concepts/add-properties-profilecard.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-14955) | [Details](#user-content-2c47f6674d1fe0637c99263de7e6e3af-19f2491c)

<a id="2c47f6674d1fe0637c99263de7e6e3af-19f2491c"></a>
### [concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/PollyNincevic-patch-2-1/concepts/add-properties-profilecard.md)
 - **Line 160, Column 309**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/profilecardproperty-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112141410463965-14955%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-14T14%3A13%3A18Z&sr=b&sp=r&sig=P0Q9w6pUqeaymcMh%2FbvLO0J5gWKNETTLHd8AnmIYzFM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 16:08 UTC, opbld30 commented
Docs Build status updates of commit _[f4fabe1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4fabe110e9942b43ea6fa9d95d26ca7e685bbd2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/PollyNincevic-patch-2-1/concepts/add-properties-profilecard.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-14955) | [Details](#user-content-2c47f6674d1fe0637c99263de7e6e3af-5434727d)

<a id="2c47f6674d1fe0637c99263de7e6e3af-5434727d"></a>
### [concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/PollyNincevic-patch-2-1/concepts/add-properties-profilecard.md)
 - **Line 160, Column 309**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/profilecardproperty-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112151606557443-14955%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T16%3A08%3A52Z&sr=b&sp=r&sig=0LN9NtM86ARCxZqW%2Bd5cI65Fg7mACGX7809IX3dQrPU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 21:05 UTC, opbld30 commented
Docs Build status updates of commit _[9f06de8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f06de8f41f4bd0184ca38d110552645067917cc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/PollyNincevic-patch-2-1/concepts/add-properties-profilecard.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-14955) | [Details](#user-content-2c47f6674d1fe0637c99263de7e6e3af-5faef59e)

<a id="2c47f6674d1fe0637c99263de7e6e3af-5faef59e"></a>
### [concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/PollyNincevic-patch-2-1/concepts/add-properties-profilecard.md)
 - **Line 160, Column 309**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/profilecardproperty-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112152103353943-14955%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T21%3A05%3A36Z&sr=b&sp=r&sig=hEaUbhm28h9dsQ%2BYk7zggurJK%2Fket0FCygReoqvm2Yw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 21:20 UTC, opbld34 commented
Docs Build status updates of commit _[5ecfa0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5ecfa0c371bf7e4c3b555ea0caab45ec8a6d7b8a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/PollyNincevic-patch-2-1/concepts/add-properties-profilecard.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-14955) | [Details](#user-content-2c47f6674d1fe0637c99263de7e6e3af-8ede6702)

<a id="2c47f6674d1fe0637c99263de7e6e3af-8ede6702"></a>
### [concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/PollyNincevic-patch-2-1/concepts/add-properties-profilecard.md)
 - **Line 160, Column 309**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/profilecardproperty-delete'.`````
 - **Line 160, Column 309**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: ../api/profilecardproperty-delete?view=graph-rest-beta. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112152118087732-14955%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T21%3A20%3A02Z&sr=b&sp=r&sig=R2AMUaypwj3nDsf1qTdJBtFi11wPe2TDlSL0%2BaNsxVI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 21:23 UTC, opbld33 commented
Docs Build status updates of commit _[dd3a46a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd3a46ae046954f48fbab270eca371e5e2326b08)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/PollyNincevic-patch-2-1/concepts/add-properties-profilecard.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-14955) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112152121417066-14955%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T21%3A23%3A36Z&sr=b&sp=r&sig=IwekfUgJAtBHogWkro9875LrpvNZ7PQgfzMys%2FryuHk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 21:31 UTC, opbld30 commented
Docs Build status updates of commit _[cf81d3d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cf81d3dae24fcd8cccc6c3d44c20eceb633db416)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/PollyNincevic-patch-2-1/concepts/add-properties-profilecard.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-14955) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112152129212155-14955%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T21%3A31%3A09Z&sr=b&sp=r&sig=ZHllkkiRm37CfWj%2FOvk3RiYtLXzDXSJfcsQMm4WJSF0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 21:42 UTC, opbld31 commented
Docs Build status updates of commit _[e9c84c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e9c84c7983efd23b4dfe03f569cc4103ad9476d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/PollyNincevic-patch-2-1/concepts/add-properties-profilecard.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-14955) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112152140556868-14955%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T21%3A42%3A29Z&sr=b&sp=r&sig=4Qoa6l8UxoAE3oGksclGT7X7EtKaO5eP5fxBTd2wEIY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 21:45 UTC, isvargasmsft approved these changes

2021-12-16 23:03 UTC, merged