2021 11 16 aspati astgraph remove apidocs remove1
microsoftgraph/microsoft-graph-docs pull request #14950
Opened 2021-11-16 05:47 UTC by aspati

Removing unused members, unused enums

2021-11-16 05:49 UTC, opbld30 commented
Docs Build status updates of commit _[56ad880](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56ad880ce32c9ff94b6b066f317d29548552661e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111160547472235-14950%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-17T05%3A49%3A22Z&sr=b&sp=r&sig=R66FuTSctr%2FCzlL4L3HpBY3YxV%2BxDHHTwGVlNrTgFz0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-16 06:05 UTC, opbld30 commented
Docs Build status updates of commit _[c7de052](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c7de0522e088ba6d672df789c0d26114baf62526)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111160601363765-14950%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-17T06%3A05%3A11Z&sr=b&sp=r&sig=ipefys8DsxRGo6hmmdWxG3by1vPG8zhfLF0vb00GY8k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-16 06:09 UTC, opbld32 commented
Docs Build status updates of commit _[f822632](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f822632223112896450df95d2fcd9442941fc4b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111160607152944-14950%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-17T06%3A09%3A05Z&sr=b&sp=r&sig=VaFKn9XueYlOrShu3ETKNh0PHaE76BQXU2n7K5%2Ft8eE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-16 08:42 UTC, angelgolfer-ms requested changes
Hi, please add the changelog JSON for these changes - removing the mode property from the simulation resource, removing the simulationMode enumeration, and removing the notCompleted enum member. You can add to each of their description something like they are not used or not returned by the API, to clarify these are not deprecation.

2021-11-16 09:33 UTC, aspati commented
> Hi, please add the changelog JSON for these changes - removing the mode property from the simulation resource, removing the simulationMode enumeration, and removing the notCompleted enum member. You can add to each of their description something like they are not used or not returned by the API, to clarify these are not deprecation.

@angelgolfer-ms , added changelog. Please check.

2021-11-16 09:35 UTC, opbld32 commented
Docs Build status updates of commit _[99a4cf2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/99a4cf2795cd543b1765c25242a38c916751ba18)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111160933161386-14950%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-17T09%3A35%3A09Z&sr=b&sp=r&sig=X2UjShr7CjIgJUEt2B5ATZ6WTJ6m1mZAWxv4FOZoaPw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 04:58 UTC, opbld32 commented
Docs Build status updates of commit _[cb6225a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb6225ae3be7d3bbac4ecc97b75b2b955fc5c5dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111170457200844-14950%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T04%3A58%3A55Z&sr=b&sp=r&sig=hJm2hn%2FIl76OQfinvqFPHBjHmU9AxsrTq13LHP5CHTY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 09:10 UTC, opbld31 commented
Docs Build status updates of commit _[8d341f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d341f7b754b75ced05b1aa6bcf8d1af929bbf43)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111180907150296-14950%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-19T09%3A10%3A01Z&sr=b&sp=r&sig=LBtrD6Oflx3cnPw%2B%2BQcAzoQEGGr1jXLjB3pe5PjSoIU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-18 09:13 UTC, angelgolfer-ms commented on changelog/Microsoft.Security.AttackSimulation.json
> +      "SubArea": "Attack simulation and training"
Line 35:
FYI now that the "Attack simulation and training" sub-node exists in the TOC, you'd have to specify the SubArea value as well, so that the changelog can indicate in the section title something like "Security | Attack simulation and training". We do that when under a top level node (e.g., Security) in the TOC, there are multiple services.

You didn't have to do that in your the last (and the debut) PR in September because that "Attack simulation and training" didn't exist yet.

2021-11-18 09:19 UTC, angelgolfer-ms commented on changelog/Microsoft.Security.AttackSimulation.json
>      {
@aspati, I made some fixes directly in your PR for the changelog items for this PR.
However, please add back the entire changelog record that was specified in the last PR 13789. If we merge this PR as is with the last changelog record removed, the resultant changelog will no longer display those changelog items for that PR, and that would be confusing.
You can see an image of what I mean by a changelog record in this section of the changelog CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=summary-process

2021-11-18 09:21 UTC, angelgolfer-ms requested changes
@aspati , thanks for the changelog update.
Please see my comment in the changelog JSON file Microsoft.Security.AttackSimulation.json.

2021-11-19 06:16 UTC, opbld33 commented
Docs Build status updates of commit _[e632793](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e632793c970823d7985a12977cb0041a569e0b7a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111190614266681-14950%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-20T06%3A16%3A04Z&sr=b&sp=r&sig=jdhHQRhdcwjqmQDQRJXk90wlwfry%2Fvu%2Bb1nnynkiQdw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-19 06:17 UTC, aspati commented on changelog/Microsoft.Security.AttackSimulation.json
>      {
@angelgolfer-ms , fixed changelog. Please check.

2021-11-19 07:29 UTC, angelgolfer-ms approved these changes
Thanks, the changelog JSON file looks complete now.

2021-11-22 13:48 UTC, opbld34 commented
Docs Build status updates of commit _[56373e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56373e4c8a992b22382964e47977f67b4ee7563e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111221346548904-14950%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-23T13%3A48%3A29Z&sr=b&sp=r&sig=sEZg1DwWv1QcMelc5Iu2gp%2B2lry2ZIV3fZUryhtGtac%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-30 02:22 UTC, opbld32 commented
Docs Build status updates of commit _[23ffba4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23ffba4c46049e7c64373a2bda78f95e021a9f09)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[api-reference/beta/resources/simulation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/api-reference/beta/resources/simulation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/simulation?view=graph-rest-beta&branch=pr-en-us-14950) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-11-16-aspati-astgraphRemove-apidocs-remove1/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111300221089465-14950%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-31T02%3A22%3A42Z&sr=b&sp=r&sig=aWAwX5MlhaFo%2B5Z8zdI56B5XYrj%2BQnOz6astwK%2BjmmM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-30 02:24 UTC, merged