Refactoring MCAS to MDCA
microsoftgraph/microsoft-graph-docs pull request #14968
Opened 2021-11-17 13:04 UTC by Tzoref12

Hi, I'm a PM from Microsoft Defender for Cloud Apps (MDCA), formerly MCAS.
During Ignite, we announced rebranding to the Defender suite.
I noticed that few pages referring to our product still use the outdated name, and therefore submitting this update.

2021-11-17 13:05 UTC, opbld33 commented
Docs Build status updates of commit _[953588b](https://github.com/Tzoref12/microsoft-graph-docs/commits/953588b1e1e2450a884c36ecef499af490645036)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/security-api-overview.md](https://github.com/Tzoref12/microsoft-graph-docs/blob/patch-2/api-reference/v1.0/resources/security-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/security-api-overview?view=graph-rest-1.0&branch=pr-en-us-14968) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111171304232105-14968%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T13%3A05%3A58Z&sr=b&sp=r&sig=RUMabAahn7qOD08xymzHT6RD3XfpDPJlWS9BqjFXv%2BI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 19:36 UTC, isvargasmsft approved these changes
Addressing missing files in PR 14967.

2021-11-19 04:58 UTC, angelgolfer-ms requested changes
@Tzoref12 , it looks like this same topic has 3 other instances of "Microsoft Cloud App Security" in line 45. Can you please  replace those instances?

Also, a search in the Microsoft Graph docs returns a few other files with this name "Microsoft Cloud App Security" (5 files, 11 results), including the one instance in this PR. I took a quick look at each of those contexts and they seem to be eligible for replacement. Can you please follow up? Thanks!

2021-11-23 21:21 UTC, isvargasmsft commented
Resuming work in this PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/15008

2021-11-23 21:21 UTC, closed without merging