Update riskdetection-get.md
microsoftgraph/microsoft-graph-docs pull request #14974
Opened 2021-11-17 21:59 UTC by ebasseri

small correction to clarify that specifying a GUID in this call will return a specific risk detection object, not all the risk detections for a specific user. I tested this on my demo tenant and you cannot make a call here to pivot on the userID, as far as I can tell.

2021-11-17 22:00 UTC, opbld31 commented
Docs Build status updates of commit _[cc6f206](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc6f206a92dfcaa82ff166b0d6627f14fd39a5b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/riskdetection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskdetection-get?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111172159081618-14974%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-18T22%3A00%3A42Z&sr=b&sp=r&sig=kc1wGnaj9E903Ilg2QqpmXmNGWN59F1Eq1c0pJqobXs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-17 22:58 UTC, cloudhandler approved these changes

2021-11-23 16:54 UTC, opbld30 commented
Docs Build status updates of commit _[2c1d76c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c1d76cbe43a0fcc72902ad4ce9bc7cbbd692abe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/riskyserviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskyserviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-a3e8cac403876e16c7087583d2263c48-471dc8e4)
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-4c7bd0f169d551f917d99c95e5ba35b8-471dc8e4)
[api-reference/beta/api/serviceprincipalriskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/serviceprincipalriskdetection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-21ba6fcd16514d4d7d0319a43bedf4df-471dc8e4)
[api-reference/beta/api/riskdetection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskdetection-get?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) |

<a id="a3e8cac403876e16c7087583d2263c48-471dc8e4"></a>
### [api-reference/beta/api/riskyserviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskyserviceprincipal.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/riskyserviceprincipal-list.md'.`````
 - **Line 21, Column 70**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/riskyserviceprincipal.md'.`````
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/riskyserviceprincipal-get.md'.`````
 - **Line 22, Column 67**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/riskyserviceprincipal.md'.`````
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/riskyserviceprincipal-list-history.md'.`````
 - **Line 23, Column 63**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/riskyserviceprincipalhistoryitem.md'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/riskyserviceprincipal-dismiss.md'.`````
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/riskyserviceprincipal-confirmcompromised.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/riskyserviceprincipal.md(3,14)', 'beta/api/serviceprincipalriskdetection.md(3,14)'.`````

<a id="4c7bd0f169d551f917d99c95e5ba35b8-471dc8e4"></a>
### [api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/serviceprincipalriskdetection-get.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 15, Column 54**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/serviceprincipalriskdetection.md'.`````
 - **Line 48, Column 67**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/serviceprincipalriskdetection.md'.`````

<a id="21ba6fcd16514d4d7d0319a43bedf4df-471dc8e4"></a>
### [api-reference/beta/api/serviceprincipalriskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/serviceprincipalriskdetection.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 28, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main [...]

2021-11-24 20:06 UTC, opbld32 commented
Docs Build status updates of commit _[52867e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52867e14e1ff6e6762d9f80795f1ffc563848944)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-947d8642473ba32273c0a1cc56197e16-748ae9c2)
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-d646f4de703ace2344c720fa368614ee-748ae9c2)
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-ce71634c15cbeec36dbbc66ccb39ab88-748ae9c2)
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-364e72443c9b9bb1a5643d9b9ba8585b-748ae9c2)
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskyserviceprincipal-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-66a23d71c5b1757986ab6354098e75b3-748ae9c2)
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-748ae9c2)
[api-reference/beta/api/riskyserviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskyserviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-a3e8cac403876e16c7087583d2263c48-748ae9c2)
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-4c7bd0f169d551f917d99c95e5ba35b8-748ae9c2)
[api-reference/beta/api/serviceprincipalriskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/serviceprincipalriskdetection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-21ba6fcd16514d4d7d0319a43bedf4df-748ae9c2)
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/resources/riskyserviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-dded2166454c2d90f035d9e327b8a868-748ae9c2)
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/resources/serviceprincipalriskdetection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-61b5e9f830d86ff06efea1db5bab6259-748ae9c2)
[api-reference/beta/api/riskdetection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskdetection-get?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) |

<a id="947d8642473ba32273c0a1cc56197e16-748ae9c2"></a>
### [api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="d646f4de703ace2344c720fa368614ee-748ae9c2"></a>
### [api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="ce71634c15cbeec36dbbc66ccb39ab88-748ae9c2"></a>
### [api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md)
 - [...]

2021-12-01 19:58 UTC, opbld32 commented
Docs Build status updates of commit _[e613e98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e613e98b8d9d8f61dcd4e4c4191c6a14f13bac5d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-riskyserviceprincipals?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-947d8642473ba32273c0a1cc56197e16-c273cbe4)
[api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskyserviceprincipal-list-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-list-history?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-a52075278831cedb9dbb9a05745c5d34-c273cbe4)
[api-reference/beta/api/riskyserviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskyserviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-a3e8cac403876e16c7087583d2263c48-c273cbe4)
[api-reference/beta/api/serviceprincipalriskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/serviceprincipalriskdetection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-21ba6fcd16514d4d7d0319a43bedf4df-c273cbe4)
[api-reference/beta/resources/riskyserviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/resources/riskyserviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/riskyserviceprincipal?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-dded2166454c2d90f035d9e327b8a868-c273cbe4)
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/resources/serviceprincipalriskdetection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) | [Details](#user-content-61b5e9f830d86ff06efea1db5bab6259-c273cbe4)
[api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/identityprotectionroot-list-serviceprincipalriskdetections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprotectionroot-list-serviceprincipalriskdetections?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) |
[api-reference/beta/api/riskdetection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskdetection-get?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskyserviceprincipal-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskyserviceprincipal-dismiss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-dismiss?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) |
[api-reference/beta/api/riskyserviceprincipal-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskyserviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyserviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipalriskdetection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/serviceprincipalriskdetection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipalriskdetection-get?view=graph-rest-beta&branch=pr-en-us-14974) (graph-rest-beta) |

<a id="947d8642473ba32273c0a1cc56197e16-c273cbe4"></a>
### [api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/identityprotectionroot-list-riskyserviceprincipals.md)
 - **Line 74, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="a52075278831cedb9dbb9a05745c5d34-c273cbe4"></a>
### [api-reference/beta/api/riskyserviceprincipal-list-history.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskyserviceprincipal-list-history.md)
 - **Line 47, Column 81**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/riskyserviceprincipalhistoryitem.md'.`````
 - **Line 70, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="a3e8cac403876e16c7087583d2263c48-c273cbe4"></a>
### [api-reference/beta/api/riskyserviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ebasseri-patch-1/api-reference/beta/api/riskyserviceprincipal.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'riskyServicePrincipal resource type - Microsoft Graph beta' is duplicated in: 'beta/api/riskyserviceprincipal.md(2,8), beta/resources/riskyserviceprincipal.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metad [...]

2022-02-10 16:25 UTC, ebasseri commented
@cloudhandler this PR is blocked. can you please unblock?

2022-02-10 16:35 UTC, opbld34 commented
Docs Build status updates of commit _[a5e035f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5e035f6dc687b0a920a6b85e1c2eb721c7dc1ea)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b9ccb73b)

<a id="b9ccb73b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202101634469877-14974%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-13T16%3A35%3A37Z&sr=b&sp=r&sig=wMfdAETpdM8kuTQhRjwHMg%2BmZN2%2B2R433IK0OcvNEZU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-10 16:37 UTC, opbld34 commented
Docs Build status updates of commit _[5ab3590](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5ab3590af80f8a10b3f193a1b6f34f5bee574c17)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-987eb8f4)

<a id="987eb8f4"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202202101636084729-14974%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-13T16%3A37%3A09Z&sr=b&sp=r&sig=%2FrCvBDCmY28QXLs8Yl3vLOGK3eC88C3EHv7Yuqp36Jw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 17:31 UTC, Danielabom requested changes

2022-04-21 16:09 UTC, ebasseri commented on api-reference/beta/api/riskdetection-get.md
> +### Example 2: Get a specific risk detection object
@cloudhandler can you please review this feedback?

2022-05-04 16:36 UTC, cloudhandler commented on api-reference/beta/api/riskdetection-get.md
> +### Example 2: Get a specific risk detection object
@Danielabom  I don't understand the question. Example 1 doesn't need an ID because it's just retrieving all risk detections. Example 2 is retrieving a specific risk detection, hence the ID in the request.

2022-11-24 00:13 UTC, closed without merging