Added Go SDK examples
microsoftgraph/microsoft-graph-docs pull request #14998
Opened 2021-11-19 20:05 UTC by jasonjoh

2021-11-19 20:07 UTC, opbld34 commented
Docs Build status updates of commit _[5a58a19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a58a198105b65f911a574f07bfd5176a690b2b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/create-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/customize-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-expand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-expand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-headers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-headers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-index.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-queryparams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-queryparams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-read.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-read.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-select.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-select.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111192005447510-14998%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-20T20%3A07%3A25Z&sr=b&sp=r&sig=r2Bt%2BRjiB9wRUi0T28TuxF6XY8nJ2X1P%2FSHC0uZg%2Fa0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-19 20:26 UTC, baywet requested changes
thanks for taking the time to put all of that together! a few minor comments. Let me make the changes in the service libs so you can update the version thing

2021-11-19 20:26 UTC, baywet commented on concepts/sdks/customize-client.md
> +    GraphServiceVersion:        "",
could use msgraphsdk.clientOptions if I changed the c for a C instead, what do you think?

2021-11-19 20:26 UTC, baywet commented on concepts/sdks/customize-client.md
> +allMiddleware := make([]khttp.Middleware, len(defaultMiddleware)+1)
I believe you should be able to get around by doing

```golang
allMiddleware := []khttp.Middleware {
   mycustom.NewCustomHandler(),
   defaultMiddleware...
}
```

And drop the copy etc... (I haven't tested the code though)

2021-11-19 20:37 UTC, baywet commented on concepts/sdks/customize-client.md
> +    GraphServiceVersion:        "",
https://github.com/microsoftgraph/msgraph-beta-sdk-go/pull/15
https://github.com/microsoftgraph/msgraph-sdk-go/pull/22

2021-11-19 20:48 UTC, jasonjoh commented on concepts/sdks/customize-client.md
> +    GraphServiceVersion:        "",
Sure if you think that's the way to go I'm all for it.

2021-11-19 20:48 UTC, jasonjoh commented on concepts/sdks/customize-client.md
> +allMiddleware := make([]khttp.Middleware, len(defaultMiddleware)+1)
Ah yeah, thanks for that.

2021-11-19 20:52 UTC, opbld34 commented
Docs Build status updates of commit _[7064973](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70649735736ff5da2cc5cf27b2e71bde2ad35759)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/create-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/customize-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-expand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-expand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-headers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-headers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-index.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-queryparams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-queryparams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-read.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-read.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-select.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-select.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111192050442497-14998%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-20T20%3A52%3A15Z&sr=b&sp=r&sig=wyvaMk7dPGtSeyzgv2BgFQ3fJUcQPRSIlniRKq4v0%2Fo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-19 20:55 UTC, opbld33 commented
Docs Build status updates of commit _[c86b57e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c86b57eb69f7bf8d6179aba518fcf540710fe276)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/create-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/customize-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-expand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-expand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-headers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-headers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-index.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-queryparams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-queryparams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-read.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-read.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-select.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-select.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111192053200268-14998%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-20T20%3A55%3A02Z&sr=b&sp=r&sig=x2uyz4n3%2FshZxnnCSXSBPSXcPkK6zx%2BXSZpU9IcFdvQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-19 20:57 UTC, opbld33 commented
Docs Build status updates of commit _[4700961](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4700961f6f2294b2a075b53364e3fd19b4425ef3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/create-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/customize-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-expand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-expand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-headers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-headers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-index.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-queryparams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-queryparams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-read.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-read.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-select.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-select.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111192054079673-14998%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-20T20%3A57%3A04Z&sr=b&sp=r&sig=L8rH6vWpY2sBTq6Eo7MhxMva1%2F32XJASfH%2B%2BxJDLl5Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-19 20:57 UTC, jasonjoh commented on concepts/sdks/customize-client.md
> +allMiddleware := make([]khttp.Middleware, len(defaultMiddleware)+1)
Should be resolved now

2021-11-19 20:58 UTC, jasonjoh commented on concepts/sdks/customize-client.md
> +    GraphServiceVersion:        "",
Should be resolved now

2021-11-19 21:15 UTC, baywet requested changes

2021-11-19 21:15 UTC, baywet commented on concepts/sdks/customize-client.md
> +defaultMiddleware := core.GetDefaultMiddlewaresWithOptions(core.ClientOptions)
```suggestion
defaultMiddleware := core.GetDefaultMiddlewaresWithOptions(msgraphsdk.ClientOptions)
```

2021-11-19 21:15 UTC, baywet commented on concepts/sdks/customize-client.md
> +allMiddleware := []khttp.Middleware{
```suggestion
allMiddleware := append(defaultMiddleware, mycustom.NewCustomHandler())
```

2021-11-19 21:15 UTC, baywet commented on concepts/sdks/customize-client.md
> +    mycustom.NewCustomHandler(),
```suggestion
```

2021-11-19 21:15 UTC, baywet commented on concepts/sdks/customize-client.md
> +    defaultMiddleware...
```suggestion
```

2021-11-19 21:15 UTC, baywet commented on concepts/sdks/customize-client.md
> +}
```suggestion
```

2021-11-19 21:16 UTC, baywet approved these changes

2021-11-19 21:18 UTC, opbld34 commented
Docs Build status updates of commit _[81ace5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81ace5f3677d5540f7611a318e25426054ea923c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/create-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/customize-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-expand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-expand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-headers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-headers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-index.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-queryparams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-queryparams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-read.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-read.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-select.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-select.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111192115332836-14998%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-20T21%3A18%3A38Z&sr=b&sp=r&sig=CwfJVQG4b6O1K1DhO88Ge3wkX6A%2FCt%2B2y9OCv67LOhc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-22 14:45 UTC, baywet commented on concepts/sdks/customize-client.md
> +defaultMiddleware := core.GetDefaultMiddlewaresWithOptions(msgraphsdk.ClientOptions)
```suggestion
defaultMiddleware := core.GetDefaultMiddlewaresWithOptions(msgraphsdk.GetDefaultClientOptions())
```
```suggestion
defaultMiddleware := core.GetDefaultMiddlewaresWithOptions(msgraphsdk.ClientOptions)
```

2021-11-22 14:47 UTC, opbld33 commented
Docs Build status updates of commit _[1ce3312](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ce33123c2dd7da2fcec3b416a315ac7cb23881f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/create-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/customize-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-expand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-expand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-headers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-headers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-index.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-queryparams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-queryparams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-read.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-read.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-select.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-select.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111221445454020-14998%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-23T14%3A47%3A30Z&sr=b&sp=r&sig=5YEEFc7lqUvB5OJH7PLMRGUaASKoOFDXFknqgRsG9sc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 18:55 UTC, opbld33 commented
Docs Build status updates of commit _[0a0eb13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a0eb13187c2473cc6d74225e0ecc2f0989edb13)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/create-requests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/customize-client.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/customize-client?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-expand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-expand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-headers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-headers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-index.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-queryparams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-queryparams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-read.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-read.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-select.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-select.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |
[concepts/sdks/includes/snippets/go/create-requests-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-go-sdk/concepts/sdks/includes/snippets/go/create-requests-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/create-requests?branch=pr-en-us-14998) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202111291853269249-14998%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-30T18%3A55%3A14Z&sr=b&sp=r&sig=pX%2BjSQbdK7iK7o3bpdtSHzABETxw8hGBwy9SzvNU1SU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 19:36 UTC, merged